### ISSUE TITLE
DRM it seems to add some time before the drm #EXT-X-KEY:METHOD=SAMPLE-AES,URI 

### ISSUE THREAD

**Issue by s3bubble** [google/shaka-packager#1001]
## System info
**Operating System**: <e.g. macOS Sierra, Ubuntu 14.04 trusty etc>

macOS Montery
**Shaka Packager Version**: <e.g. v1.6.1, commit SHA etc>
## Issue and steps to reproduce the problem

When using DRM it seems to add some time before the drm #EXT-X-KEY:METHOD=SAMPLE-AES,URI tag see below

```
#EXTM3U
#EXT-X-VERSION:6
## Generated with https://github.com/google/shaka-packager version v2.6.1-634af65-release
#EXT-X-TARGETDURATION:3
#EXT-X-PLAYLIST-TYPE:VOD
#EXTINF:2.000,
1.ts
#EXTINF:2.000,
2.ts
#EXTINF:2.000,
3.ts
#EXT-X-DISCONTINUITY
#EXT-X-KEY:METHOD=SAMPLE-AES,URI="skd://fps.ezdrm.com/;f0c97fbc1c66499cbfe9d9199486d268",KEYFORMATVERSIONS="1",KEYFORMAT="com.apple.streamingkeydelivery"
#EXTINF:2.000,
4.ts
#EXTINF:2.000,
5.ts
#EXTINF:2.000,
6.ts 
```

**Packager Command**:
`./packager-osx-x64 'in=/Users/samueleast/Desktop/assets/intro.mp4,stream=audio,segment_template=/Users/dave/production/audio/$Number$.aac,playlist_name=/Users/dave/production/audio/main.m3u8,hls_group_id=audio,hls_name=Default' 'in=/Users/dave/rendition_1280x720.mp4,stream=video,segment_template=/Users/dave/production/p720/$Number$.ts,playlist_name=/Users/dave/production/p720/main.m3u8' 'in=/Users/dave/rendition_854x480.mp4,stream=video,segment_template=/Users/dave/production/p480/$Number$.ts,playlist_name=/Users/dave/production/p480/main.m3u8' --segment_duration 2 --protection_scheme cbcs --enable_raw_key_encryption --keys label=AUDIO:key_id=f0c97fbc1c66499cbfe9d91994000000:key=c2d0bd12513aa9889797d454f863986d:iv=f0c97fbc1c66499cbfe9d91994000000,label=SD:key_id=f0c97fbc1c66499cbfe9d91994000000:key=c2d0bd12513aa9889797d454f863986d:iv=f0c97fbc1c66499cbfe9d91994000000,label=HD:key_id=f0c97fbc1c66499cbfe9d91994000000:key=c2d0bd12513aa9889797d454f863986d:iv=f0c97fbc1c66499cbfe9d91994000000 --protection_systems FairPlay --hls_key_uri 'skd://fps.ezdrm.com/;f0c97fbc1c66499cbfe9d91994000000' --hls_master_playlist_output /Users/dave/production/master.m3u8`

What is the expected result?

When I encode the same file with Bento4 it looks like this.

```
#EXTM3U
#EXT-X-VERSION:5
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-INDEPENDENT-SEGMENTS
#EXT-X-TARGETDURATION:2
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-KEY:METHOD=SAMPLE-AES,URI="skd://fps.ezdrm.com/;bb844ef1ba74466191be1a68ec7ad90e",KEYFORMAT="com.apple.streamingkeydelivery",KEYFORMATVERSIONS="1"
#EXTINF:2.000000,
segment-0.ts
#EXTINF:2.000000,
segment-1.ts
#EXTINF:2.000000,
segment-2.ts
#EXTINF:2.000000,
segment-3.ts
#EXTINF:2.000000,
```

Not sure why the #EXT-X-DISCONTINUITY tag is being added.

**Comment by bugre** [comment]
The entries you see before " #EXT-X-KEY:METHOD=" are , probably, the result of the default 'clear_lead' time, that'll generate the starting segments up to 'clear_lead=xx' time (default 5 secs) unencrypted content. ref. https://google.github.io/shaka-packager/html/options/general_encryption_options.html?highlight=clear_lead

For the X-DISCONTINUITY, if i remember correctly when you change characteristics of segments that follow you should add it ti signal the change, in this case, the segments after the signaling will be encrypted and before not.

**Comment by joeyparrish** [comment]
@bugre, thank you for the explanation.  I think you are exactly right.

@s3bubble, does this answer your question?

**Comment by s3bubble** [comment]
Ok thanks yes close we will look into this.
