### ISSUE TITLE
Support for external, non-segmented subtitles

### ISSUE THREAD

**Issue by s3bubble** [google/shaka-packager#1005]
I have encoded my media using Shaka packager to add webvtt subtitles using the command here.

https://google.github.io/shaka-packager/html/tutorials/text.html#examples

packager 'in=input.vtt,stream=text,init_segment=init.mp4,segment_template=text_$Number$.mp4'

The player we are using is videojs and it doesnt support embedded subtitles.

Does shaka packager have any options to simply package non-segmented subtitles like the dash specs?

Like this.
``` xml
<AdaptationSet mimeType="text/vtt" lang="en"> 
    <Representation id="caption" bandwidth="123">
        <BaseURL>subtitles/en.vtt</BaseURL> 
    </Representation>
</AdaptationSet>
```

Turns out we can just parse and update the manifest seems to work but it would be good if shaka packager did this.
``` js
const xml2js = require('xml2js');
const fs = require('fs')

fs.readFile('./master.mpd', 'utf8', (err, data) => {
    if (err) {
        console.error(err)
        return
    }
    xml2js.parseString(data, function(err, result) {
        result.MPD.Period[0].AdaptationSet.push({
            '$': { mimeType: 'text/vtt', lang: 'en' },
            Representation: {
                '$': { id: 'caption', bandwidth: '123' },
                BaseURL: ['subtitles/sub.vtt']
            }
        });
        const builder = new xml2js.Builder();
        const xml = builder.buildObject(result);
        console.log('Save updated manifest', xml);
    });

});
```

**Comment by joeyparrish** [comment]
Packager **does** support non-segmented VTT, just as it supports non-segmented streams of all types.  But your command line explicitly requested segmentation through the init_segment and segment_template parameters.  Replace those with output= as in the other examples on the docs page you linked to.

Does this help?
