### ISSUE TITLE
Can I make a docker image into a folder that links so files?

### ISSUE THREAD

**Issue by baehongjun0212** [google/shaka-packager#1009]
## System info
**Operating System**: <macOS Big Sur, Ubuntu 18.04 trusty etc>
**Shaka Packager Version**: f018c9a9bf

## Issue and steps to reproduce the problem
My Linux server has a 'shaka_packager' folder and a 'transcoder' folder.

**Config.mk file in transcoder folder**
`
CNMV_TRANS_LIB_PATH := $(TOPDIR)/src
CNMV_TRANS_LIB_NAME := libCNMVTranscoding.a

ifeq ($(USE_SHAKA), 1)
Shaka Packager Library
SHAKA_PKG_LIB_PATH := $(SHAKA_PKG_SRC_PATH)/out/Release/lib
SHAKA_PKG_LIB_NAME := packager
endif

Nvidia Cuda Driver Library
CUDA_DRV_LIB_PATH ?= $(CUDA_PATH)/lib64/stubs
CUDA_DRV_LIB_NAME ?= cuda

Nvidia Cuda Runtime Library
CUDA_RT_LIB_PATH ?= $(CUDA_PATH)/lib64
CUDA_RT_LIB_NAME ?= cudart

Nvidia Management Library
CUDA_NVML_LIB_PATH ?=$(CUDA_PATH)/lib64/stubs
CUDA_NVML_LIB_NAME ?=nvidia-ml

NVCODEC Libraries
NVCODEC_LIB_PATH ?= $(TOPDIR)/src/3rdlib/nvidia/NvCodec/Lib/linux/stubs/x86_64
NVDEC_LIB_NAME ?= nvcuvid
NVENC_LIB_NAME ?= nvidia-encode

.SUFFIXES : .o .cpp .cu

%.o : %.cpp
        $(CPP) $(MODULE_FLAGS) -c $< -o $@

%.o : %.cu
        $(NVCC) $(NVCCFLAGS) -c $< -o $@
`

Like the code above, if enter the `make` command in the transcoder folder, you will link the `.so` file of the shaka packager.
I want to upload the tasks uploaded to this Linux server as docker images to the AWS server.
To that end, I have a question while building `Dockerfile`.

Is it possible to make one docker image when one folder is in the form of importing so files from another folder?

**Comment by kqyang** [comment]
I haven't tried it myself, but I think it will work as long as the file paths are handled correctly.
