### ISSUE TITLE
Shaka packager generates file permissions issues.

### ISSUE THREAD

**Issue by jbuduoo** [google/shaka-packager#1021]
## System info
**Operating System**: Rocky-8.4-x86_64
**Shaka Packager Version**:v2.6.1

## Issue and steps to reproduce the problem

**Packager Command**:
In the Linux environment, I use JAVA's ProcessBuilder to execute the shaka packager.
```
/opt/asorigin/web/bin/packager \
in=udp://224.1.2.3:1235,stream=audio,init_segment='/opt/asorigin/content/vod/nfs/s02/audio/audio_init.mp4',segment_template='/opt/asorigin/content/vod/nfs/s02/audio/audio_$Number$.m4s',playlist_name='/opt/asorigin/content/vod/nfs/s02/audio/audio.m3u8',hls_group_id=audio,hls_name=ENGLISH \
in=udp://224.1.2.3:1235,stream=video,init_segment='/opt/asorigin/content/vod/nfs/s02/h264_360/h264_360p_init.mp4',segment_template='/opt/asorigin/content/vod/nfs/s02/h264_360/h264_360p_$Number$.m4s',playlist_name='/opt/asorigin/content/vod/nfs/s02/h264_360/h264_360p.m3u8' \
--segment_duration 5 \
--fragment_duration 5 \
--minimum_update_period 5 \
--min_buffer_time 5 \
--preserved_segments_outside_live_window 10 \
--time_shift_buffer_depth 40 \
--hls_master_playlist_output /opt/asorigin/content/vod/nfs/s02/s02.m3u8 \
--hls_playlist_type LIVE
```
![](https://i.imgur.com/JTtAY5w.png)

But found the generated files, permissions are 640. This makes the front-end web page unable to open.
![](https://i.imgur.com/w5VIYoQ.png)
![](https://i.imgur.com/BkOL8fQ.png)

What is the expected result?
If I execute the same execution directly in linux, the permission is 644
![](https://i.imgur.com/omh5hJU.png)
![](https://i.imgur.com/Y7HmTHH.png)

What happens instead?

<Please attach the input files or email to shaka-packager-issues@google.com.>
<Please provide any additional information below.>

I want to execute it in java, and the permission is also 644. I don't know if there are any parameters that have not been added, so this situation occurs. Please let me know, thank you.

**Comment by joeyparrish** [comment]
What is the value of your [umask](https://en.wikipedia.org/wiki/Umask) when you run Java?  Is it different from the umask in your shell?  Does ProcessBuilder provide a way to set the umask for the subprocess?

**Comment by jbuduoo** [comment]
I have been working on umask for a long time, but I can't get it out.
I use this method to solve the problem of permissions.

ArrayList<String> list = new ArrayList<>();
list.add("su");
list.add("-s");
list.add("/bin/bash");
list.add("daemon");
list.add("-c");
list.add("/opt/asorigin/web/bin/packager "
		+ "'in=" + bean.getInput() + ",stream=audio,init_segment=" + bean.getNewPath()+ "audio/audio_init.mp4,segment_template=" + bean.getNewPath()+ "audio/audio_$Number$.m4s,playlist_name=" + bean.getNewPath()+ "audio/audio.m3u8,hls_group_id=audio,hls_name=ENGLISH' "
		+ "'in=" + bean.getInput() + ",stream=video,init_segment=" + bean.getNewPath()+ "video/video_init.mp4,segment_template=" + bean.getNewPath()+ "video/video_$Number$.m4s,playlist_name=" + bean.getNewPath() + "video/video.m3u8' "
		+ "--segment_duration 5 "
		+ "--fragment_duration 5 "
		+ "--minimum_update_period 5 "
		+ "--min_buffer_time 5 "
		+ "--preserved_segments_outside_live_window 10 "
		+ "--time_shift_buffer_depth 40 "
		+ "--hls_master_playlist_output '" + bean.getNewPath() + profileRulesBeanArray[0].getName() + ".m3u8' "
		+ "--hls_playlist_type LIVE");
		
ProcessBuilder processBuilder = new ProcessBuilder(list);

**Comment by joeyparrish** [comment]
I would recommend against running Packager as root.  Also, I don't see any answer to my question about umask.

I believe this is an issue with your execution environment, and not with Packager itself.  Please double-check the umask of the Java process executing the Packager command, as that is likely to be the root cause.
