### ISSUE TITLE
How to setup owner key server for encrypted and gen rsa signing key

### ISSUE THREAD

**Issue by haithanhnguyen** [google/shaka-packager#104]
Hi mod,

I've tried to encrypted video and player it with dashIF. So, I haven't key_server. So, how can I build a private key_server, and how to gen widevine_private.der key for packager.

I'm newbie. I hope your help soon. Thanks very much.

**Comment by kqyang** [comment]
A quick question, is it for personal use or commercial use?

widevine_private.der is needed if you want to use a Widevine license server for the content encryption. You'll need to sign an agreement with Google first. 

If it is for personal use, it is probably easier for you to use fixed key instead. The keys can be provided to the player when starting playing the streams.

Let's know if you'd like to go with Widevine license server, I'll share further instructions.

**Comment by imalex** [comment]
If you do wish to use the Widevine License Service, please use our contact form at http://www.widevine.com/contact.html to begin the process to complete the necessary agreements.

**Comment by haithanhnguyen** [comment]
Thanks @kqyang and @imalex , I want to using Widevine license server. Please share me instructions to using!

**Comment by kqyang** [comment]
Sure. You can use the contact form at http://www.widevine.com/contact.html to begin the process to complete the necessary agreements.

**Comment by kqyang** [comment]
I am closing this bug. Feel free to re-open it if you have more questions.
