### ISSUE TITLE
Package Video with Multiple Language Audio and Subtitles

### ISSUE THREAD

**Issue by grantg182** [google/shaka-packager#107]
Hi

I am trying to generate an MPD and have a few issues. Firstly, my content consists of MP4 video containers which consists of one video track and two or more audio tracks. Further audio tracks (in other languages) are also available in MP4 containers, so it could be possible to have a video playback with several audio tracks available.

My first problem encountered was due to "Files with MDAT before MOOV is not supported yet" which resulted in having to re-encode the MP4's in ffmpeg using the '-movflags faststart' switch. This resulted in the loss of all but one of the audio tracks from within the MP4.

Ok, so I thought I could just add the audio tracks back during compilation using the shaka packager. Here is what I have been attempting to do:-

./packager input=multilingual_video.mp4,stream=video,output=output_multilingual_video.mp4 input=arabic_audio.mp4,stream=audio,output=output_arabic_audio.mp4 input=french_audio.mp4,stream=audio,output=output_french_audio.mp4 input=german_audio.mp4,stream=audio,output=output_german_audio.mp4 input=english.webvtt,stream=text,lang=en,output=output_english.webvtt input=french.webvtt,stream=text,lang=fr,output=output_french.webvtt input=german.webvtt,stream=text,lang=de,output=output_german.webvtt input=spanish.webvtt,stream=text,lang=es,output=output_spanish.webvtt --profile on-demand --mpd_output output_vod.mpd

multilingual_video.mp4 already contains english and spanish tracks, so I am trying to add arabic, french and german audio tracks to this list as well as append subtitles in only 4 languages. But then I run into major problems.

The resulting mp4 has no audio, "ffmpeg -i" reports there is only the video source in the mp4, so all of the audio tracks are being lost somehow. 

Furthermore, I tried using MP4Box but this resulted in Shaka Player reporting multiple issues with the manifest as the MP4Box manifest structure is not to standard. One thing that was a major advantage of MP4Box is that I could use it to export both the .mpd and a .mp4 which contained the video track and all audio tracks in one single file. This is particularly useful in the case of iOS devices which are (now) capable of playing back MP4 content natively, thus Shaka can handle other browsers and the MP4 can be sent straight to iOS devices (some video playback experience is better than none right?) and still provide the rich user experience of audio track/sub track selection using iOS browsers native controls.

Am I using the flags incorrectly for building my MP4 for the manifest? Is it best to exclude all audio tracks from the MP4 before compiling using the packager?

Unfortunately I have not found much in terms of documentation for the packager so am hoping someone out there can advise what my options are.

Thanks!

**Comment by kqyang** [comment]
1. For the problem "Files with MDAT before MOOV is not supported yet", are you using the latest packager? It is already supported. If you are still running into this problem, can you send the source file to me for debugging? (You can either upload it to somewhere and share with me or email the file to me directly - you can find my email address in [CONTRIBUTORS](https://github.com/google/shaka-packager/blob/master/CONTRIBUTORS) file.)

2. We don't support multiplex audio and video in the same file (DASH spec requires that every stream in its own file). You can extract the audio streams in your source to separate files, e.g.

./packager input=multilingual_video.mp4,stream=video,output=output_multilingual_video.mp4 
                  input=multilingual_video.mp4,stream=[audio0],output=output_multilingual_audio_eng.mp4
                  input=multilingual_video.mp4,stream=[audio1],output=output_multilingual_audio_spa.mp4  
...

Replace [audio0] and [audio1] below with the actual stream index. You can find out the stream index with ./packager input=multilingual_video.mp4 --dump_stream_info command.

Let me know if there is any other questions.

**Comment by grantg182** [comment]
1. I am using "shaka-packager version 32482c0-release" which I believe to be the latest build, which was obtained by running "gclient sync" on this git. If you can confirm this is the latest build then I can send across one of my test sources.

2. Great, that makes sense now. I guess I'll just have to live with that!

I'll try run through some further tests this morning using the appropriate commands to extract the audio into separate files. I assume to add further audio steams (which are not included in the video mp4) I would just need to add a further input= using an incremental [audio#]?

**Comment by kqyang** [comment]
Re 1: Yes, it is the latest.

> I assume to add further audio steams (which are not included in the video mp4) I would just need to add a further input= using an incremental [audio#]?

Partially correct. To add further audio streams, you'll just need to add further input= clause. The stream indicator can be either descriptive like "audio" or "video", or a number to indicate the stream index in the source. What you do originally, i.e. input=french_audio.mp4,stream=audio,output=output_french_audio.mp4, will work.

**Comment by grantg182** [comment]
Thanks kqyang, content has now been built successfully. Thanks again.

**Comment by ivanovaleksey** [comment]
Hello, I have the same problem but my video contains only 1 audio channel 
(according to `--dump_stream_info`).

I use sample videos from [sample-videos](http://www.sample-videos.com).
```
root@af3e5b750a97:/media# packager input=SampleVideo_1280x720_30mb.mp4 --dump_stream_info
[1129/100107:INFO:demuxer.cc(88)] Demuxer::Run() on file 'SampleVideo_1280x720_30mb.mp4'.
[1129/100107:INFO:demuxer.cc(160)] Initialize Demuxer for file 'SampleVideo_1280x720_30mb.mp4'.

File "SampleVideo_1280x720_30mb.mp4":
Found 2 stream(s).
Stream [0] type: Video
 codec_string: avc1.4d401f
 time_scale: 12800
 duration: 2186752 (170.8 seconds)
 is_encrypted: false
 codec: H264
 width: 1280
 height: 720
 pixel_aspect_ratio: 1:1
 trick_play_factor: 0
 nalu_length_size: 4

Stream [1] type: Audio
 codec_string: mp4a.40.2
 time_scale: 48000
 duration: 8201216 (170.9 seconds)
 is_encrypted: false
 codec: AAC
 sample_bits: 16
 num_channels: 6
 sampling_frequency: 48000
 language: und
```

But when I try to do something with the video the error occurs:
```
root@af3e5b750a97:/media# packager input=SampleVideo_1280x720_30mb.mp4,stream=1,output=audio.mp4 input=SampleVideo_1280x720_30mb.mp4,stream=0,output=video.mp4
[1129/100139:INFO:demuxer.cc(88)] Demuxer::Run() on file 'SampleVideo_1280x720_30mb.mp4'.
[1129/100139:INFO:demuxer.cc(160)] Initialize Demuxer for file 'SampleVideo_1280x720_30mb.mp4'.
[1129/100139:ERROR:mp4_media_parser.cc(263)] Not implemented reached in bool shaka::media::mp4::MP4MediaParser::ParseBox(bool *) Files with MDAT before MOOV is not supported yet.
[1129/100139:ERROR:packager_main.cc(461)] Packaging Error: 8 (PARSER_FAILURE): Cannot parse media file SampleVideo_1280x720_30mb.mp4
```

I use official Docker image with latest release
```
root@af3e5b750a97:/media# packager --version
packager version cc778f6-release
```

Could you please help me to understand the problem?
Is it something wrong with the video?

**Comment by grantg182** [comment]
As per the error message, the shaka code states:-

`The code ends up here only if a MOOV box is not yet seen.`

So yes, the issue is with your source MP4's. You can resolve this by using '-movflags faststart' flags in ffmpeg for those MP4's which produce this error when you attempt to package via Shaka.

**Comment by ivanovaleksey** [comment]
Thank you @grantg182,
I was fighting with building `AtomicParsley` to inspect the video.
Seems like I succeed with 
```
$ ffmpeg -i SampleVideo_1280x720_30mb.mp4 -movflags +faststart foo.mp4
```

**Comment by kqyang** [comment]
Emm... "MDAT before MOOV" should already be supported. I have opened a separate bug for it in #298. Not sure if it is a regression or something else is going on. Thanks for reporting the issue!
