### ISSUE TITLE
fragmented mp4 in live profile (question)

### ISSUE THREAD

**Issue by peyoh** [google/shaka-packager#109]
Hi, 
Is possible to generate fragmented mp4 files in live profile? I cannot find such config option.

Peyo

**Comment by kqyang** [comment]
It is already generating fragmented mp4 file.

Can you clarify the question? Do you mean having init segment and media segments in one single file?

**Comment by peyoh** [comment]
Hi KQ,
maybe I misundersttod what fragmented mp4 is. Sorry if that is true.  Currently all metadata is in the first file. All other segments carry only raw data. 
For example:
Here is the file with metadata:
```
[root@boron 502]# mediainfo edash-video-576.mp4
General
Complete name                            : edash-video-576.mp4
Format                                   : dash
Codec ID                                 : dash (iso6/mp41/avc1)
File size                                : 812 Bytes
Encoded date                             : UTC 2016-06-08 08:48:59
Tagged date                              : UTC 2016-06-08 08:48:59

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L3
Format settings, CABAC                   : Yes
Format settings, ReFrames                : 2 frames
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
Width                                    : 720 pixels
Height                                   : 576 pixels
Display aspect ratio                     : 16:9
Frame rate                               : 25.000 fps
Standard                                 : PAL
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Encoded date                             : UTC 2016-06-08 08:48:59
Tagged date                              : UTC 2016-06-08 08:48:59

Here is the consequent segment:

[root@boron 502]# mediainfo edash-video-576-25269.mp4
General
Complete name                            : edash-video-576-25269.mp4
Format                                   : QuickTime
Format/Info                              : Original Apple specifications
File size                                : 3.01 MiB

```

**Comment by kqyang** [comment]
I see. So you want to include the init segment in the media segments? Metadata is in the init segment, which is identical for all media segments. So by separating init segment and media segments, the player would not need to download and parse the metadata again and again. It is also DASH spec's requirement to separate init segment and media segments for live profile. 

There is no option in edash-packager / shaka-packager to include the init segment in the media segments. But if you really want to do that, you can simply concatenate the init segment with the media segment after the media segments being generated. I am curious what is the background of this question.

**Comment by kqyang** [comment]
Oh, btw, it is not true that the media segments carry only raw data. It does not carry the "track" / "media" level information but it contains all the sample level information. So it is more adequate to say that metadata is spread in init segment and media segments. init segment contains "track" / "media" level metadata, i.e. the identical and common part of the metadata, and media segments contains "sample" level metadata.

**Comment by peyoh** [comment]
Aha, clear.
That was just a question, because I was asked myself "What will happen if  some data in the init segment changes on the fly?". Then the raw segments before the change will become unusable.
