### ISSUE TITLE
Package with Adaption

### ISSUE THREAD

**Issue by grantg182** [google/shaka-packager#111]
Hi

I am looking into packaging with various bandwidths, using the Shaka Player to test the network and load various bitrate streams where appropriate.

In the packager, what do I need to do to create the AdaptionSet for each bitrate stream? I have tested this by manually editing the DASH manifest, but would like to know how to do this via terminal. For example:-

```
packager \
  input=sintel.mp4,stream=audio,output=sintel_audio.mp4 \
  input=sintel.mp4,stream=video,output=sintel_video_low_bitrate.mp4 \
  input=sintel.mp4,stream=video,output=sintel_video_high_bitrate.mp4 \
  input=sintel_english_input.vtt,stream=text,output=sintel_english.vtt \
--profile on-demand \
--mpd_output sintel_vod.mpd
```

What flags do I need to use on the low and high bitrate video stream input commands to generate the MPD correctly?

Thanks!

**Comment by kqyang** [comment]
If you want the player to adapt between different streams, videos of different bitrate should be in the same AdaptationSet but different Representation. This is what Shaka Packager is doing now.

Why do you want to create an AdaptationSet for each bitrate stream? It won't be adaptable with this.

Shaka Packager will creates the streams in different AdaptationSet if the streams are of different type (audio v.s. video) or different codec (h.264 v.s. h.265) or different languages etc.

**Comment by kqyang** [comment]
I am closing this issue. Feel free to re-open it if you have more questions.
