### ISSUE TITLE
Add support for edts box

### ISSUE THREAD

**Issue by swaroopgn** [google/shaka-packager#112]
https://github.com/google/shaka-packager/blob/4f9c8ea7817b397c4f2dd83311f528200650bd3d/packager/media/formats/mp4/track_run_iterator.cc#L157

If the input file contains edts boxes shaka packager ignores it. edts/elst is a commonly used mechanism to support priming samples for AAC.

I am working on a patch for this and would like to submit it soon

**Comment by kqyang** [comment]
Cool. Thanks for working on addressing the issue!
