### ISSUE TITLE
"Off-by-one frame" bug when packaging from mp2 to mp4?

### ISSUE THREAD

**Issue by gkop** [google/shaka-packager#113]
Thanks for your work helping us package our DASH video! :)

Here's my test case:

```bash
#!/usr/bin/env bash

packager | grep "edash-packager version" # version v1.4.1-9f2da1e-release

wget http://static.coshx.com/example.ts

packager input=example.ts,stream_selector=0,output=video_init.mp4,segment_template=\$Time\$.mp4v,output_format=MP4,bandwidth=200000 -single_segment=false

ls -l *.mp4v
mp4dump 356038323.mp4v
```

The resulting media fails to play in the demo Shaka Player app ([using this manifest](https://gist.github.com/gkop/1bed9f8d888f2e4ceb966cf75a80b9d1)) due to an EME error. When I edit the TFDT box on 356038323.mp4v and change the base media decode time from 356035320 to 356038323, then the output _does_ play successfully in the demo Shaka Player app. I'm somewhat new to video, but it makes sense to me that the base media decode time should match the manifest timestamp and the filename timestamp. Instead it appears to be off by one frame. Is this a bug or am I misunderstanding how to use this project?

**Comment by kqyang** [comment]
It is actually a bug in Chrome: https://bugs.chromium.org/p/chromium/issues/detail?id=398130#c13, which unfortunately is not fixed yet.

Usually for the first frame, the presentation timestamp and decoding timestamp are the same, but it is not the case for your test content. There is a difference of 3003 ticks. Chrome uses decoding timestamp for the seeking right now, while it should use presentation timestamp instead.

A typical workaround to the problem is to adjust the manifest to use the decoding time instead, i.e.
replacing **<S t="356038323"** with **<S t="356035320"** in the manifest.

Let us know if you have more questions.

**Comment by gkop** [comment]
Hmm, still struggling here - having trouble corroborating with [a recent ffprobe](https://gist.github.com/gkop/175f118a49a9d3d18afcae912c35b186) that the pts and dts are in fact different on the frames of this example fragment:

```
ffprobe -show_frames -show_entries frame=pkt_pts,pkt_dts -of json example.ts
```

The first 229 frames have matching dts and pts, the 230th frame is missing dts. Could that be what is causing the problem here, the missing dts on the 230th frame?

Also I have a questions about rewriting the manifest with dts: then I would like to name my fragments by dts to match the manifest - but shaka packager doesn't have a template variable for dts :/ Am I thinking about this the wrong way? How are others doing this?

**Comment by kqyang** [comment]
> The first 229 frames have matching dts and pts, the 230th frame is missing dts. Could that be what is causing the problem here, the missing dts on the 230th frame?

It will only cause problem if it is the first frame of a segment. Btw, what is the EME error you are talking about?

> Also I have a questions about rewriting the manifest with dts: then I would like to name my fragments by dts to match the manifest - but shaka packager doesn't have a template variable for dts :/ Am I thinking about this the wrong way? How are others doing this?

Shaka packager does not provide an option to output in dts right now. I'll see if we can generate a patch for you to try.

I have never seen complaints from others with mismatching pts/dts for live streams. For on-demand streams, it is easy to adjust the manifest manually or with a script.

**Comment by gkop** [comment]
When I say EME error, I mean an error that shaka player traces to the browser (in my case Chrome 52.0.2743.49 beta (64-bit)):

![shaka_error](https://cloud.githubusercontent.com/assets/222582/16462739/7b37aa90-3de7-11e6-85b2-071a7b254810.png)

Why would ffprobe disagree with shaka packager as to wheth the pts and dts match or not for this example fragment? How can we get to the bottom of this?

**Comment by kqyang** [comment]
> Why would ffprobe disagree with shaka packager as to wheth the pts and dts match or not for this example fragment? How can we get to the bottom of this?

Good question. Didn't notice that earlier. I will investigate.

**Comment by kqyang** [comment]
Looks like it is a problem in _ffprobe -show_frames_: https://trac.ffmpeg.org/ticket/2375

You can use _ffprobe -show_packets_ instead, which works correctly.

**Comment by gkop** [comment]
Cool, thank you so much!

My experiments suggest your idea of using dts in the manifest and rewriting the filenames will solve this problem.

If it's not too much trouble, I'd very much <3 a patch exposing a dts variable in the filename templates.
