### ISSUE TITLE
HLS Live Stream .m3u8 Generation

### ISSUE THREAD

**Issue by codyhui8** [google/shaka-packager#114]
As I understand right now, the only way for shaka-packager to generate .m3u8 files is to generate it at the end of the video. As such, a HLS stream will not be generated as we can assume that the stream is endless. Are there any plans to implement HLS packaging for live streams(udp://) anytime soon?

**Comment by kqyang** [comment]
There are a few pieces missing for live support, but yes, we are planning to add live support this quarter.

**Comment by hariszukanovic** [comment]
We are quite interested in this feature.
Any updates on this activity?

thanx in advance

**Comment by kqyang** [comment]
We are planning to add support for live stream generation this quarter. Stay tuned.

**Comment by hariszukanovic** [comment]
@kqyang I might be able to help and contribute on this issue if someone could provide some initial pointers

**Comment by kqyang** [comment]
Great. Here are a few pointers:

1. You should take some time to read through hls spec first if you are not familiar with it already. Here is the latest version of the draft spec: https://tools.ietf.org/html/draft-pantos-http-live-streaming-20, specifically, section 6.2.2 which covers the live playlist: https://tools.ietf.org/html/draft-pantos-http-live-streaming-20#section-6.2.2

2. The code for HLS handling is in https://github.com/google/shaka-packager/tree/master/packager/hls/. Most code should just work for live. Other than the changes for https://tools.ietf.org/html/draft-pantos-http-live-streaming-20#section-6.2.2, you will also want to save the individual playlists on every new segments.

@rkuroiwa do you have anything else in mind?

@hariszukanovic Let us know if you have any questions and when you start working on it. Thanks.

**Comment by rkuroiwa** [comment]
One thing.
https://github.com/google/shaka-packager/tree/master/packager/media/event
hls_notify_muxer_listener* files must be modified as well to complete packaging (i.e. generate media files and manifests). Currently the code assumes VOD. Looking at mpd_notify_muxer_listener* might help.
