### ISSUE TITLE
HTTP 403 error

### ISSUE THREAD

**Issue by chinlungli-tutk** [google/shaka-packager#119]
When I am using shaka-packager to get my segments as audio.mp4/video.mp4/example.mpd files.
I put the files on the HTTP Server and get the mpd file url.
When I used the client(dashif.org/reference/players/javascript/latest/samples/dash-if-reference-player/index.html) to test I got the error message
(audio.mp4/video.mp4/example.mpd files are put on the amazon s3)
【XMLHttpRequest cannot load https://s3-ap-northeast-1.amazonaws.com/dashtutk/01/video.mp4. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://dashif.org' is therefore not allowed access. The response had HTTP status code 403.】
Can anyone give some help?
Thanks.

My mpd file is below
https://www.dropbox.com/s/pzx73sgw95ej668/example.mpd?dl=0

**Comment by kqyang** [comment]
This is a CORS failure: https://en.wikipedia.org/wiki/Cross-origin_resource_sharing

You need to config your web/content server at amazon s3 to allow access from http://dashif.org. Alternatively setup a dashif player in the same domain as your content.

I am closing this issue. Feel free to re-open it if you have other questions.

**Comment by chinlungli-tutk** [comment]
Solved.
Thanks for help!
