### ISSUE TITLE
segmentTemplate different startNumber in the representations

### ISSUE THREAD

**Issue by peyoh** [google/shaka-packager#122]
Hello, 
I've just opened issue in exoplayer repo [1675](https://github.com/google/ExoPlayer/issues/1675) but meanwhile I've noticed something.
I have two live manifests generated from the master branch packager. 
Manifest 1: 

```
    <AdaptationSet id="1" contentType="video" maxWidth="720" maxHeight="576" frameRate="90000/3600" par="16:9">
      <Representation id="1" bandwidth="1696455" codecs="avc1.64001e" mimeType="video/mp4" sar="64:45" width="640" height="512">
        <SegmentTemplate timescale="90000" initialization="edash-video-512.mp4" media="edash-video-512-$Number$.mp4" startNumber="38784">
          <SegmentTimeline>
            <S t="34905132000" d="900000" r="8640"/>
          </SegmentTimeline>
        </SegmentTemplate>
      </Representation>
      <Representation id="2" bandwidth="897590" codecs="avc1.640015" mimeType="video/mp4" sar="64:45" width="480" height="384">
        <SegmentTemplate timescale="90000" initialization="edash-video-384.mp4" media="edash-video-384-$Number$.mp4" startNumber="38784">
          <SegmentTimeline>
            <S t="34905222000" d="900000" r="8640"/>
          </SegmentTimeline>
        </SegmentTemplate>
      </Representation>
      <Representation id="3" bandwidth="3036134" codecs="avc1.64001e" mimeType="video/mp4" sar="64:45" width="720" height="576">
        <SegmentTemplate timescale="90000" initialization="edash-video-576.mp4" media="edash-video-576-$Number$.mp4" startNumber="38784">
          <SegmentTimeline>
            <S t="34904862000" d="900000" r="8640"/>
          </SegmentTimeline>
        </SegmentTemplate>
      </Representation>
    </AdaptationSet>
```

Manifest 2:

```
    <AdaptationSet id="1" contentType="video" maxWidth="1920" maxHeight="1080" frameRate="90000/3600" par="16:9">
      <Representation id="1" bandwidth="5770363" codecs="avc1.4d001f" mimeType="video/mp4" sar="1:1" width="1280" height="720">
        <SegmentTemplate timescale="90000" initialization="edash-video-720.mp4" media="edash-video-720-$Number$.mp4" startNumber="57746">
          <SegmentTimeline>
            <S t="60709580496" d="950400" r="2057"/>
            <S t="62665503696" d="954000"/>
            <S t="62666457696" d="950400" r="6123"/>
          </SegmentTimeline>
        </SegmentTemplate>
      </Representation>
      <Representation id="2" bandwidth="8605990" codecs="avc1.640028" mimeType="video/mp4" sar="1:1" width="1920" height="1080">
        <SegmentTemplate timescale="90000" initialization="edash-video-1080.mp4" media="edash-video-1080-$Number$.mp4" startNumber="56463">
          <SegmentTimeline>
            <S t="60709645296" d="972000" r="2011"/>
            <S t="62665309296" d="975600"/>
            <S t="62666284896" d="972000" r="5987"/>
          </SegmentTimeline>
        </SegmentTemplate>
      </Representation>
    </AdaptationSet>

```

With manifest 2, when exoplayer try to switch from 720 to 1080, a outOfBounds exception is thrown in segment list array. 
That is because number of segments is different in the different segment templates. Is normal  to have different segments count in one adaptation set?

**Comment by ojw28** [comment]
Shouldn't the packager be guaranteeing segment alignment and setting `@segmentAlignment=true` on the `AdaptationSet`? I could be wrong, but I think DASH-IF IOP requires `@segmentAlignment=true` on all `AdaptationSet` elements for live (and `@subSegmentAlignment=true` for vod).

**Comment by kqyang** [comment]
If the source streams do not have aligned GOPs, then the packager won't be able to generate aligned media segments. @peyoh, can you share a few media segments from the output, so we can check if they have aligned GOPs? Thanks.

@ojw28 Packager should guarantee segment alignments if the input streams are alignment; otherwise if the input streams are not aligned, there is no way to generate aligned segments without encoding the input streams again. Packager will still proceed the packaging in this case, although it is not complaint to DASH-IF IOP. A lot of players do support unaligned media segments.

**Comment by peyoh** [comment]
Here are some segments:
[Segments ](https://drive.google.com/a/peyo.me/folderview?id=0B7KCfFBKrvsNaWEydHR0VWlvZjA&usp=sharing)

**Comment by kqyang** [comment]
I checked the segments. The streams actually have aligned GOPs (1 second GOP). We need to improve packager to do proper synchronization so the streams start at the same GOP.

@peyoh Before it is fixed, you may just restart packaging, it should generate aligned segments (@segmentAlignment == true) most of the time.

**Comment by kqyang** [comment]
This is already fixed in master.
