### ISSUE TITLE
availabilityStartTime far behind the timeShiftBufferDepth

### ISSUE THREAD

**Issue by peyoh** [google/shaka-packager#123]
Hello, 
I've noticed, that availabilityStartTime goes behind the timeShiftBufferDepth (86400S). Is this expected behavior?
The packager is from master. 

<MPD xmlns="urn:mpeg:dash:schema:mpd:2011" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xlink="http://www.w3.org/1999/xlink" xsi:schemaLocation="urn:mpeg:dash:schema:mpd:2011 DASH-MPD.xsd" xmlns:cenc="urn:mpeg:cenc:2013" minBufferTime="PT2S" type="dynamic" profiles="urn:mpeg:dash:profile:isoff-live:2011" publishTime="2016-07-13T13:27:52Z" availabilityStartTime="2016-07-04T19:24:31Z" minimumUpdatePeriod="PT5S" timeShiftBufferDepth="PT86400S">

**Comment by kqyang** [comment]
Yes, that is expected. We derive availabilityStartTime from the timestamp in the media file:

```
availabilityStartTime = Now() - timestamp_from_media + availability_start_time_offset
```
availability_start_time_offset is a configurable offset.

I am closing this bug. Feel free to re-open if if you have more questions.
