### ISSUE TITLE
Cannot parse media file

### ISSUE THREAD

**Issue by chinlungli-tutk** [google/shaka-packager#125]
Hi guys:
     I use shaka-packager to package mp4 file from ipcam streaming for dash using
but I get the errorCode : 
Failed to parse avcc.
Error parsing mp4 file "aa.mp4"
"Demuxer failed to initialize: 8(PARSER_FAILURE): Cannot parse media file".
    My source media mp4 file is below:
https://www.dropbox.com/s/sa3g50brjghofzb/aa.mp4?dl=0
Can anyone give some idea??
(VLC/QuickTime player can work.)

**Comment by kqyang** [comment]
It is caused by #126, we don't support gap_in_frame_num_value_allowed flag yet. We also discover another problem in the content: the first sample has a duration of 0. It is not strictly spec complaint, but I think it makes sense to remove this restriction in the packager #127.

**Comment by kqyang** [comment]
This should have been fixed.
