### ISSUE TITLE
Playready support

### ISSUE THREAD

**Issue by Natarajan92** [google/shaka-packager#128]
Shaka-Packager has support for playready DRM encryption for live dash packaging ?

**Comment by kqyang** [comment]
No. Do you want playready + widevine or playready only? We are not familiar with playready, especially for live. External contribution will be welcomed!

**Comment by Natarajan92** [comment]
For Live streaming, we need Playready + Widevine.

**Comment by hariszukanovic** [comment]
Do you mean Playready output in Smooth Streaming protocol?

**Comment by Natarajan92** [comment]
No, I have asked for Mpeg-Dash live stream with PlayReady + Widevine Encryption

**Comment by sammirata** [comment]
I also have the need for PlayReady + Widevine encryption

**Comment by InsideSecure-DRM-Admin** [comment]
Hello, 

I have done some work to add PlayReady support to shaka-packager.
Currently, I have only added very basic functionality. Basically only VOD is supported with CENC and For example PlayReady encryption cannot be combined with other encryptions like Widevine or fixed key.

My goal is to continue working on this. Next stage would probably be to implement support for generating Widevine and Playready pssh boxes simultaneously to packaged mp4 file. Live streaming use case might come after that.

**Comment by kqyang** [comment]
@InsideSecure-DRM-Admin Thanks for working on this. As mentioned in the pull request, the change I mentioned earlier has been merged. Feel free to review the change and let us know if it works for you.

> My goal is to continue working on this. Next stage would probably be to implement support for generating Widevine and Playready pssh boxes simultaneously to packaged mp4 file. Live streaming use case might come after that.

These are not supported right now. If you want to work on it, let us know and we can discuss how it should be implemented. Thanks.

**Comment by Sean-X** [comment]
if possible could playready3.0 be supported too?

**Comment by zshenker** [comment]
@kqyang Are there still any plans to support Widevine + Playready simultaneously? Will the PlayReady support here work for WebM as well as fMP4 media?

Ideally I am looking for a solution that will allow we to do DASH, VP9, WebM with CENC for Widevine+PlayReady for playback in Chrome, Firefox & Edge.

**Comment by kqyang** [comment]
Yes, the multi-DRM/multi-PSSH support is tracked in https://github.com/google/shaka-packager/issues/245.

> Will the PlayReady support here work for WebM as well as fMP4 media?

Yes, it should work for both WebM and fMP4. For WebM, the PSSHs are only put in the DASH manifest, but that shouldn't be an issue. We have not tried WebM on Edge. We'll find out later.

**Comment by kqyang** [comment]
Closing this issue as we already supports PlayReady.
