### ISSUE TITLE
Cross-compile for arm, arm64

### ISSUE THREAD

**Issue by pathammer** [google/shaka-packager#129]
I'm trying to cross compile packager to run on an arm computer for an embedded application. I've set these environment variables:

```
GYP_CROSSCOMPILE=1
GYP_DEFINES="target_arch=arm64"
```

and run `gclient runhooks` but ninja produces the same ouput. Am I doing something wrong or is there no cross-compilation support?

Thanks!

**Comment by kqyang** [comment]
Put GYP_DEFINES and gclient runhooks in one line:

```
GYP_DEFINES="target_arch=arm64" gclient runhooks
```

Let me know if it still does not work for you.

**Comment by pathammer** [comment]
Thank you. That got compilation started but now I get the following linker error
```
ninja -C out/Debug  
ninja: Entering directory `out/Debug'
[12/89] LINK wvm_unittest
FAILED: wvm_unittest 
../../packager/third_party/llvm-build/Release+Asserts/bin/clang++ -Wl,-z,now -Wl,-z,relro -Wl,--fatal-warnings -Wl,-z,defs -pthread -Wl,-z,noexecstack -fPIC -Wl,--disable-new-dtags -o wvm_unittest -Wl,--start-group obj/media/formats/wvm/wvm_unittest.wvm_media_parser_unittest.o obj/testing/libgtest.a obj/testing/libgmock.a obj/media/test/libmedia_test_support.a obj/media/formats/wvm/libwvm.a obj/base/libbase.a obj/base/libbase_static.a obj/base/allocator/liballocator_extension_thunks.a obj/third_party/modp_b64/libmodp_b64.a obj/base/third_party/dynamic_annotations/libdynamic_annotations.a obj/base/libsymbolize.a obj/base/libxdg_mime.a obj/third_party/libevent/libevent.a obj/media/test/librun_tests_with_atexit_manager.a obj/media/base/libmedia_base.a obj/media/base/libwidevine_pssh_data_proto.a obj/third_party/protobuf/libprotobuf_lite.a obj/third_party/boringssl/libboringssl.a obj/third_party/curl/libcurl.a obj/third_party/libxml/libxml2.a obj/third_party/icu/libicuuc.a obj/third_party/icu/libicudata.a obj/third_party/zlib/libchrome_zlib.a obj/third_party/zlib/libzlib_x86_simd.a obj/version/libversion.a obj/media/codecs/libcodecs.a obj/media/formats/mp2t/libmp2t.a obj/media/formats/mpeg/libmpeg.a -Wl,--end-group  -lrt -ldl
obj/third_party/boringssl/src/crypto/aes/boringssl.aes.o: In function `AES_encrypt':
/repo/dash_pack/shaka_packager/src/out/Debug/../../packager/third_party/boringssl/src/crypto/aes/aes.c:1067: undefined reference to `asm_AES_encrypt'
obj/third_party/boringssl/src/crypto/aes/boringssl.aes.o: In function `AES_decrypt':
/repo/dash_pack/shaka_packager/src/out/Debug/../../packager/third_party/boringssl/src/crypto/aes/aes.c:1072: undefined reference to `asm_AES_decrypt'
obj/third_party/boringssl/src/crypto/aes/boringssl.aes.o: In function `AES_set_encrypt_key':
/repo/dash_pack/shaka_packager/src/out/Debug/../../packager/third_party/boringssl/src/crypto/aes/aes.c:1077: undefined reference to `asm_AES_set_encrypt_key'
obj/third_party/boringssl/src/crypto/aes/boringssl.aes.o: In function `AES_set_decrypt_key':
/repo/dash_pack/shaka_packager/src/out/Debug/../../packager/third_party/boringssl/src/crypto/aes/aes.c:1082: undefined reference to `asm_AES_set_decrypt_key'
obj/third_party/boringssl/src/crypto/aes/boringssl.mode_wrappers.o: In function `AES_cbc_encrypt':
/repo/dash_pack/shaka_packager/src/out/Debug/../../packager/third_party/boringssl/src/crypto/aes/mode_wrappers.c:92: undefined reference to `asm_AES_cbc_encrypt'
obj/third_party/boringssl/src/crypto/rand/boringssl.hwrand.o: In function `CRYPTO_hwrand':
/repo/dash_pack/shaka_packager/src/out/Debug/../../packager/third_party/boringssl/src/crypto/rand/hwrand.c:36: undefined reference to `CRYPTO_rdrand_multiple8_buf'
/repo/dash_pack/shaka_packager/src/out/Debug/../../packager/third_party/boringssl/src/crypto/rand/hwrand.c:45: undefined reference to `CRYPTO_rdrand'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
[17/89] CXX obj/media/formats/mp4/mp4.track_run_iterator.o
ninja: build stopped: subcommand failed.
```

**Comment by kqyang** [comment]
Em... Looks like we are missing a few functions in boringssl's arm build.

**Comment by pathammer** [comment]
I got it to succesfully build and link by manually adding the preprocessor define OPENSSL_NO_ASM to my boringssl.ninja. That should have been done by gclient:

boringssl.gyp
``` python
['target_arch == "arm" and msan == 0', {
          'conditions': [
            ['OS == "linux" or OS == "android"', {
              'sources': [ '<@(boringssl_linux_arm_sources)' ],
            }, {
              'defines': [ 'OPENSSL_NO_ASM' ],
            }],
          ],
        }],
        ['target_arch == "arm64" and msan == 0', {
          'conditions': [
            ['OS == "linux" or OS == "android"', {
              'sources': [ '<@(boringssl_linux_aarch64_sources)' ],
            }, {
              'defines': [ 'OPENSSL_NO_ASM' ],
            }],
          ],
        }]
```

I'm trying to figure out why that define didn't get set by gclient.

Unrelated - can you tell me how to set my cc, cxx, and ar variables to point to the toolchain I need for my target?

**Comment by kqyang** [comment]
I assume that the OS is "linux". It is expected that "OPENSSL_NO_ASM" is not defined then.

The gyp file was copied from Chromium. I haven't look into why it works in Chromium but not in shaka packager. We are probably missing something here.

Feel free to submit a pull request to define "OPENSSL_NO_ASM" unconditionally for arm builds for now. We can figure out how to make ASM work later. 

As for cc, cxx and ar variables, you should be able to set it by exporting the environment variables, e.g.

% export AR=/usr/local/crosstool-trusted/arm-2009q3/bin/arm-none-linux-gnueabi-ar
% export AS=/usr/local/crosstool-trusted/arm-2009q3/bin/arm-none-linux-gnueabi-as
% export CC=/usr/local/crosstool-trusted/arm-2009q3/bin/arm-none-linux-gnueabi-gcc
% export CXX=/usr/local/crosstool-trusted/arm-2009q3/bin/arm-none-linux-gnueabi-g++
% export LD=/usr/local/crosstool-trusted/arm-2009q3/bin/arm-none-linux-gnueabi-ld

The ninja will pick up what is in environment variable if it is set.

**Comment by garretmcgraw** [comment]
I tried this approach but ended up getting the following back from the cross compiler.  Any ideas?


> /home/me/tools-master/arm-bcm2708/arm-bcm2708hardfp-linux-gnueabi/bin/arm-bcm2708hardfp-linux-gnueabi-gcc -MMD -MF obj/third_party/zlib/zlib.gzlib.o.d -DV8_DEPRECATION_WARNINGS -D_FILE_OFFSET_BITS=64 -DNO_TCMALLOC -DDISABLE_NACL -DCHROMIUM_BUILD -DCR_CLANG_REVISION=274369-1 -DUI_COMPOSITOR_IMAGE_TRANSPORT -DUSE_AURA=1 -DUSE_PANGO=1 -DUSE_CAIRO=1 -DUSE_DEFAULT_RENDER_THEME=1 -DUSE_LIBJPEG_TURBO=1 -DENABLE_WEBRTC=1 -DENABLE_MEDIA_ROUTER=1 -DENABLE_PEPPER_CDMS -DENABLE_NOTIFICATIONS -DUSE_UDEV -DFIELDTRIAL_TESTING_ENABLED -DENABLE_TASK_MANAGER=1 -DENABLE_EXTENSIONS=1 -DENABLE_PDF=1 -DENABLE_PLUGINS=1 -DENABLE_SESSION_SERVICE=1 -DENABLE_THEMES=1 -DENABLE_PRINTING=1 -DENABLE_BASIC_PRINTING=1 -DENABLE_PRINT_PREVIEW=1 -DENABLE_SPELLCHECK=1 -DENABLE_CAPTIVE_PORTAL_DETECTION=1 -DENABLE_SUPERVISED_USERS=1 -DENABLE_MDNS=1 -DENABLE_SERVICE_DISCOVERY=1 -DV8_USE_EXTERNAL_STARTUP_DATA -DFULL_SAFE_BROWSING -DSAFE_BROWSING_CSD -DSAFE_BROWSING_DB_LOCAL -DUSE_LIBPCI=1 -DUSE_NSS_CERTS=1 -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DWTF_USE_DYNAMIC_ANNOTATIONS=1 -D_DEBUG -D_GLIBCXX_DEBUG=1 -Igen -I../../packager/third_party/zlib -fstack-protector --param=ssp-buffer-size=4 -Werror -pthread -fno-strict-aliasing -Wall -Wno-unused-parameter -Wno-missing-field-initializers -fvisibility=hidden -pipe -fPIC -fcolor-diagnostics -Wheader-hygiene -Wno-char-subscripts -Wno-unneeded-internal-declaration -Wno-covered-switch-default -Wstring-conversion -Wno-c++11-narrowing -Wno-deprecated-register -Wno-inconsistent-missing-override -Wno-shift-negative-value -Wno-undefined-var-template -Wno-nonportable-include-path -Wno-unused-variable -target aarch64-linux-gnu --sysroot=/home/me/shaka_packager_arm/src/packager/build/linux/debian_jessie_arm64-sysroot -O0 -g -funwind-tables   -c ../../packager/third_party/zlib/gzlib.c -o obj/third_party/zlib/zlib.gzlib.o
> arm-bcm2708hardfp-linux-gnueabi-gcc: error: unrecognized command line option '-fcolor-diagnostics'
> arm-bcm2708hardfp-linux-gnueabi-gcc: error: unrecognized command line option '-Wheader-hygiene'
> arm-bcm2708hardfp-linux-gnueabi-gcc: error: unrecognized command line option '-Wstring-conversion'
> arm-bcm2708hardfp-linux-gnueabi-gcc: error: unrecognized command line option '-target'
> ninja: build stopped: subcommand failed.
>

**Comment by kqyang** [comment]
What are the commands you are using?

The latest code should work without exporting environments, i.e. (remember to clear AR, AS, CC, CXX, LD environments)

```
GYP_CROSSCOMPILE=1 GYP_DEFINES="target_arch=arm" gclient runhooks
ninja -C out/Debug
```

**Comment by garretmcgraw** [comment]
This made it work.  Thanks!!
