### ISSUE TITLE
Unable to determine output format for vtt file

### ISSUE THREAD

**Issue by FantasRu** [google/shaka-packager#130]
Hi.
I am intend to add a subtitle.So i try this:
```
packager \
  input=a.mp4,stream=audio,output=a_audio.mp4 \
  input=a.mp4,stream=video,output=a_video.mp4 \
  input=c.vtt,stream=text,output=c_packaged.vtt \
--profile on-demand \
--mpd_output a.mpd
```
And it return a error:

`[0721/225818:ERROR:stream_descriptor.cc(170)] Unable to determine output format for file c_packaged.vtt`

BTW,here is my test file `c.vtt`

```
WEBVTT

1
00:00:02.961 --> 00:00:04.963
°ÑÍßÁÐ½ðÅªµÃ¹»²ÒµÄ

2
00:00:04.963 --> 00:00:05.964
ÊÇÕâÑùÂð

3
00:00:05.964 --> 00:00:08.967
ºß ÄÇÅ®µÄ²»ÈÃËû¼ûº¢×Ó

4
00:00:08.967 --> 00:00:10.969
ÌìÌìÔìËûµÄÒ¥

5
00:00:10.969 --> 00:00:12.971
»¹¸ø²¿³¤Ð´ÐÅ

6
00:00:12.971 --> 00:00:13.972
°²µÂÁÒÍ¬Ö¾

7
00:00:13.972 --> 00:00:15.974
ÄãÍþÐÅ¸ß Äã Äã¸úÉÏÃæËµËµ


````
May you tell me the solution of this error?
Thanks  :)

In addition,i use docker building the packager.Will this be a problem for this error?

**Comment by kqyang** [comment]
@FantasRu Thanks for reporting this problem. It is a regression in v1.4.0. We'll fix the problem soon.
