### ISSUE TITLE
UDP problem with live streaming

### ISSUE THREAD

**Issue by orlandomatei** [google/shaka-packager#133]
I have a stream source (created with ffmpeg) which plays fine in VLC. The problem is that if I already have a client connected to that stream shaka-packager cannot connect to it. For example I open the stream with VLC and then run shaka-packager I will receive this error:

[0802/112146:INFO:demuxer.cc(60)] Initialize Demuxer for file 'udp://224.0.0.1:2014'.
[0802/112146:ERROR:udp_file_posix.cc(193)] Could not bind UDP socket
[0802/112146:ERROR:packager_main.cc(301)] Demuxer failed to initialize: 5 (FILE_FAILURE): Cannot open file for reading udp://224.0.0.1:2014

If I close VLC and nothing is connected to the stream then shaka-packager will work. This conflict is related only to shaka-packager as I am able to open multiple VLC instances or other players or even ffmpeg. On the other hand if I manage to open the stream with shaka-packager then I cannot open it with VLC or anything else in parallel.

Is there a way to open the stream with shaka-packager just as a client? Maybe some flags that I missed?

Thanks.

**Comment by kqyang** [comment]
Interesting. We'll investigate how to obtain shared access instead of exclusive access to the socket.

**Comment by peyoh** [comment]
setsockopt so_reuseaddr and let ksoftirqd to do it's job

**Comment by orlandomatei** [comment]
Forgive my ignorance but is there a parameter I can add to the udp link (something like udp://224.0.0.1:2014/?so_reuseaddr) to instruct shaka-packager to obtain shared access?

Thanks.

**Comment by peyoh** [comment]
Unfortunately not. It must be set with setsockopt() on the udp socket in the shaka source and recompile. I have never tested it here btw, because this usage isn't good for production use because highter ksoftirqd load. 
I think @kqyang can help.

**Comment by sammirata** [comment]
so_reuseaddr is used by any and all other UDP listening applications in our PRODUCTION environment and we see no performance impact. The point of multicast udp input is to be able to open it from multiple applications at the same time. Without this flag, you cannot. Here is the patch that we use on our version of the packager for anyone that is brave enough to compile their own:

commit 8c9c6ca84ce20426f3fe262babf3fb57cf5ea748
Author: Sergio Ammirata <sergio@ammirata.net>
Date:   Sat Mar 26 11:24:05 2016 -0400

    do not require exclusive bind of udp sockets

diff --git a/packager/media/file/udp_file_posix.cc b/packager/media/file/udp_file_posix.cc
index 6df6fbf..625531f 100644
--- a/packager/media/file/udp_file_posix.cc
+++ b/packager/media/file/udp_file_posix.cc
@@ -187,6 +187,9 @@ bool UdpFile::Open() {
   local_sock_addr.sin_family = AF_INET;
   local_sock_addr.sin_port = htons(dest_port);
   local_sock_addr.sin_addr.s_addr  = htonl(dest_addr);
+  // We do not need to require exclusive bind of udp sockets
+  int optval = 1;
+  setsockopt(new_socket.get(), SOL_SOCKET, SO_REUSEADDR, &optval, sizeof(optval));
   if (bind(new_socket.get(),
            reinterpret_cast<struct sockaddr*>(&local_sock_addr),
            sizeof(local_sock_addr))) {

**Comment by sammirata** [comment]
Here is the patch as an attachment: 
[udp.patch.zip](https://github.com/google/shaka-packager/files/422685/udp.patch.zip)

**Comment by kqyang** [comment]
@sammirata Cool. Thanks for working on this. Would you like to contribute this patch to shaka packager? You can send a pull request!

It will be good to make it configurable though, e.g. enabled only if having "reuse" in udp url, something like "udp://224.0.0.1:2014?reuse=1" (Feel free to work on it if you want; If not, I can work on it after your change is merged)

Thanks!

**Comment by sammirata** [comment]
Yes, I would like to contribute a patch. I have never done it before using github pull requests. I did not see the config parser inside the udp module. Where is it defined?

**Comment by kqyang** [comment]
Cool. Thanks!

Right now the port address is assumed to contain only ip address and port number, which is parsed in https://cs.corp.google.com/github/google/shaka-packager/packager/media/file/udp_file_posix.cc?rcl=52cbcb321df0cb2c831516f20b05edbc7dcd6828&l=57

To support configurable options, we can extract the strings after "?" and split the strings using base::SplitStringIntoKeyValuePairs: https://cs.chromium.org/chromium/src/base/strings/string_split.h?rcl=0&l=86

**Comment by kqyang** [comment]
@sammirata are you still working on it? You may just submit a pull request for your original patch first. I'll make it configurable later.

**Comment by sammirata** [comment]
I just submitted a pull request for the original patch

**Comment by hariszukanovic** [comment]
Hi,
What is the current status of this patch?

**Comment by kqyang** [comment]
The patch is already merged, with socket reuse enabled by default. I'll submit another patch shortly - in the new patch, socket reuse is configurable with reuse flag in the url string, something like: udp://224.1.2.30:88?reuse=1 (reuse is set to 0 by default)
