### ISSUE TITLE
Packager cannot parse h264 nalu created by x264 library when it is of fixed size

### ISSUE THREAD

**Issue by sammirata** [google/shaka-packager#134]
The packager cannot read an input stream or file if you make such a stream or file with any x264 option that will create a fixed size NALU. x264 options include slice-max-size=x, slices=x, tune=zerolatency, etc
The packager errors out with:
[0811/090118:ERROR:packager_main.cc(503)] Packaging Error: 8 (PARSER_FAILURE): Cannot parse media file

**Comment by kqyang** [comment]
Can you attach a sample failing content? (You may email it to me directly - you can find my email address in the contributors file)

**Comment by sammirata** [comment]
I just emailed you two TS sample files. One has slice_max_size=1500 and the second one does not.

**Comment by kqyang** [comment]
I didn't receive it. Are you sending to the right email address?

**Comment by sammirata** [comment]
I had sent it to Gabe by mistake. Let me know if you got it now.

**Comment by kqyang** [comment]
Yes, I just received it. Thanks for reporting the problem. We'll look into it.

**Comment by sammirata** [comment]
Any update on this issue?

**Comment by kqyang** [comment]
Yes, we have found where the problem is: in the current logic, a VCL NAL unit always starts a new access unit, which is incorrect. We are working on a fix, which should be ready soon.

**Comment by kqyang** [comment]
@sammirata This issue should have been fixed. Please re-open the bug if you are still seeing the problem. Thanks.
