### ISSUE TITLE
widevine command error, help!!!

### ISSUE THREAD

**Issue by wlc520123** [google/shaka-packager#136]
packager input=sintel.mp4,stream=video,output=encrypted_sintel.mp4 \
--enable_widevine_encryption \
--key_server_url "https://license.uat.widevine.com/cenc/getcontentkey/widevine_test" \
--content_id "3031323334353637" \
--signer "widevine_test" \
--rsa_signing_key_path "widevine_test_private.der"

after i run a command like this,
actually, it is this:
packager input='/VID_20160711_171714.mp4',\
stream=video,output=~/encrypted_sintel.mp4\
 --enable_widevine_decryption --enable_widevine_encryption\
 --key_server_url "https://license.uat.widevine.com/cenc/getcontentkey/widevine_test" \
--content_id "3031323334353637" \
--signer "widevine_test" \
--aes_signing_key  "1ae8ccd0e7985cc0b6203a55855a1034afc252980e970ca90e5202689f947ab9" \
--aes_signing_iv "d58ce954203b7c9a9a9d467f59839249" 

but the command still has error:

[0817/141247:ERROR:http_key_fetcher.cc(134)] curl_easy_perform() failed: Timeout was reached.
[0817/141348:ERROR:http_key_fetcher.cc(134)] curl_easy_perform() failed: Timeout was reached.
[0817/141450:ERROR:http_key_fetcher.cc(134)] curl_easy_perform() failed: Timeout was reached.
[0817/141554:ERROR:http_key_fetcher.cc(134)] curl_easy_perform() failed: Timeout was reached.
[0817/141702:ERROR:http_key_fetcher.cc(134)] curl_easy_perform() failed: Timeout was reached.
[0817/141702:ERROR:packager_util.cc(94)] Widevine encryption key source failed to fetch keys: 11 (SERVER_ERROR): Failed to recover from server internal error.

The server could not access?
Why? And how to deal with it? 
I am sue that my firefox browser can "over the wall" .

I have a mp4, and want to make widevine protection, then playback it on android phone.
Just for testing. But the command could be executed successfully.

**Comment by kqyang** [comment]
It works for me. Can you try again? If you are still not able to access it, try ping "ping license.uat.widevine.com" to see if anything comes back.

**Comment by wlc520123** [comment]
Thanks, very much.
I get the access to license.uat.widevine.com. But there is a new error:
[0818/103550:ERROR:widevine_key_source.cc(470)] 'AAABkAAAAAAAAAAA' is not in JSON format.
[0818/103550:ERROR:packager_util.cc(94)] Widevine encryption key source failed to fetch keys: 11 (SERVER_ERROR): Failed to decode response 'AAABkAAAAAAAAAAA'.

**Comment by wlc520123** [comment]
that's my fault, i use an error server_url.
Thanks

**Comment by wlc520123** [comment]
this command OK, then , output the encrypted_sintel.mp4.
I push this mp4 to android phone. It playback well.
but according to log of android, drmomaplugin is called, not widevine .
why?
here is part of logs:
08-18 11:11:04.369 20545 20545 D AddonVideoDrmUtils: isDrmFile
08-18 11:11:04.379  2010  2375 E DrmOmaPlugIn: DrmOmaPlugIn::canHandle: /storage/emulated/0/DCIM/encrypted_sintel.mp4 
08-18 11:11:04.379 20545 20545 D CommonControllerOverlay: showPlaying
08-18 11:11:04.379 20545 20545 D MoviePlayer: mVideoView.isPlay() false
08-18 11:11:04.379 20545 20545 D MoviePlayer: position=0 duration=289717
08-18 11:11:04.389 20545 20545 I MoviePlayerVideoView: surfaceCreated
08-18 11:11:04.389 20545 20545 I MoviePlayerVideoView: openVideo()
08-18 11:11:04.389  2605  2655 I MediaFocusControl:  AudioFocus  requestAudioFocus() from android.media.AudioManager@3c11875e req=2flags=0x0
08-18 11:11:04.389  2605  2655 I MediaFocusControl: AudioFocus  removeFocusStackEntry(): removing entry for android.media.AudioManager@3c11875e
08-18 11:11:04.409  2010  4669 E DrmOmaPlugIn: DrmOmaPlugIn::onOpenDecryptSession() : offset:0, length:68848419, fd:18
08-18 11:11:04.409  2010  4669 E         : DcfParser::parse (null)
08-18 11:11:04.409  2010  4669 E         : DcfParser::parse (null), version: 0
08-18 11:11:04.409  2010  4669 E DrmOmaPlugIn: DrmOmaPlugIn::onOpenDecryptSession() : dcf parse error
08-18 11:11:04.419  2011 29685 I MediaPlayerService: [35] setVideoSurfaceTexture(0xf5c70ee0)
08-18 11:11:04.419  2011  2011 I MediaPlayerService: [35] setVideoSurfaceTexture(0xf5c70fa0)
08-18 11:11:04.419 20545 20545 I MoviePlayerVideoView: surfaceChanged w=720h= 480
08-18 11:11:04.419 20545 20545 I MoviePlayerVideoView: end setting size: 720x480
08-18 11:11:04.419 20545 20545 I MoviePlayerVideoView: end setting size: 720x480
08-18 11:11:04.449  2010  6131 E DrmOmaPlugIn: DrmOmaPlugIn::onInitialize : 5125
08-18 11:11:04.449  2010  6131 E DrmOmaPlugIn: DrmOmaPlugIn::onSetOnInfoListener : 5125
08-18 11:11:04.459  2010  2375 E DrmOmaPlugIn: DrmOmaPlugIn::onOpenDecryptSession() : offset:0, length:68848419, fd:18
08-18 11:11:04.459  2010  2375 E         : DcfParser::parse (null)
08-18 11:11:04.459  2010  2375 E         : DcfParser::parse (null), version: 0
08-18 11:11:04.459  2010  2375 E DrmOmaPlugIn: DrmOmaPlugIn::onOpenDecryptSession() : dcf parse error
08-18 11:11:04.459 20545 20545 D AudioManager: AudioManager dispatching onAudioFocusChange(-2) for android.media.AudioManager@3c11875ecom.android.gallery3d.app.MovieActivity$1@3b69773f
08-18 11:11:04.459 20545 20545 D MovieActivity: audiofocusChange:-2
08-18 11:11:04.459 20545 20545 D MoviePlayer: mVideoView.isPlay() false
08-18 11:11:04.459 20545 20545 D MoviePlayer: position=0 duration=289717
08-18 11:11:04.469  2010  2010 E DrmOmaPlugIn: DrmOmaPlugIn::onTerminate : 5125
08-18 11:11:04.489 20545 20545 I MoviePlayerVideoView: OnVideoSizeChangedListener mVideoWidth= 720mVideoHeight= 480

**Comment by wlc520123** [comment]
when the command executing, logs:
[0818/132709:INFO:demuxer.cc(60)] Initialize Demuxer for file '/home/likewise-open/SPREADTRUM/jieying.li/VID_20160713_152311.mp4'.
[0818/132709:WARNING:mp4_media_parser.cc(538)] Pixel aspect ratio in PASP box (65536,65536) does not match with SAR in AVCDecoderConfigurationRecord (1,1). Use AVCDecoderConfigurationRecord.
[0818/132709:INFO:demuxer.cc(176)] Demuxer::Run() on file '/home/likewise-open/SPREADTRUM/jieying.li/VID_20160713_152311.mp4'.
[0818/132709:INFO:single_segment_segmenter.cc(117)] Update media header (moov) and rewrite the file to 'encrypted_sintel.mp4'.
[0818/132709:INFO:mp4_muxer.cc(172)] MP4 file 'encrypted_sintel.mp4' finalized.
Packaging completed successfully.

**Comment by kqyang** [comment]
Which player are you using to play the encrypted content?

**Comment by wlc520123** [comment]
Thanks very much for your respond.

I used both preinstall video player and exoplay demo in https://github.com/kimhou/Android/tree/master/VideoDemoPro.
Is there a 'must' player for widevine mp4?

And what is the meaning of options enable_widevine_decryption and enable_widevine_encryption? I could not understand them clearly through the help of the packager command.

In additional, I generate 3 mp4, by only with enable_widevine_decryption / only with enable_widevine_encryption / with both enable_widevine_decryption and enable_widevine_encryption.
For preinstall palyer, this 3 mp4 playback well.
For Exoplayer, only the mp4 generated with only enable_widevine_decryption option  playback well.
But none of them use the widevine plugin in phone.

**Comment by kqyang** [comment]
> Is there a 'must' player for widevine mp4?

No, there is no 'must' player - any player that supports Android MediaDrm (https://developer.android.com/reference/android/media/MediaDrm.html) should be ok.

> And what is the meaning of options enable_widevine_decryption and enable_widevine_encryption?

--enable_widevine_decryption is needed if the input is encrypted and you want to decrypt it; --enable_widevine_encryption is used to enable encryption of the content.

Since your input is not encrypted, --enable_widevine_decryption has no effect.

> For preinstall palyer, this 3 mp4 playback well.

I have no idea why it works with the preinstalled player. What is the packaging command you use? Can you change to a different content_id instead of "3031323334353637"?

> For Exoplayer, only the mp4 generated with only enable_widevine_decryption option playback well.

What is the license url you use? Do you see any error logging from Widevine plugin when playing content packaged with --enable_widevine_encryption? What "phone" are you using?

**Comment by wlc520123** [comment]
Thanks for your answer, first.

I use phone: nexus 5,  "google 相册" a preinstalled app

I used another contend_id "3031323334353640" and a new mp4 file(playback well on nexus 5), run packager command again, and get a new encrypted file.

At first few seconds (10s), the encrpted video can play well.  Then, it cloud not, having 
blurred screen or mosaic, and could not recognize the video. But it can playback continue, not stop.

From the log, widevine model is used, by 'WVCdm' tag is founded.
I think it maybe because the license is not get. But I don't know where  and what  to set the license url, for the  "google 相册" is a preinstall apk in the phone.

**Comment by wlc520123** [comment]
And there is another problem:
The encrypted video has no voice during its playback （first 10s）

**Comment by kqyang** [comment]
The preinstalled "google 相册"  knows nothing about widevine testing server. Please use an app which you can specify/modify license server instead, e.g. exoplayer; you may use https://widevine-proxy.appspot.com/proxy as the license server.

> The encrypted video has no voice during its playback （first 10s）

Audio and video are demuxed, so to generate audio, you need to have an audio stream statement, e.g. input=sintel.mp4,stream=audio,output=encrypted_sintel_audio.mp4.

**Comment by wlc520123** [comment]
I changed the server url for my player, but could not payback ether. 
on phone nexus 5: could not load the video.
because i push the video to /sdcard/widevine, but  the player load video from /storage/emulated/0/widevine, and  i can not push video to this path, for permission denied. so my video could not be loaded and playback.

Then i tried other android phone with widevine level 3 use my player, but just play first 10s.

The player i use is the one from android source code  /vendor/widevine/proprietary/samplePlayer for testing, and i don't no where to get it at first. 
Also, I tried player shared by other people, http://download.csdn.net/download/shareye1992/9554209, could not playback ether.

So, do you have a player? That will be helpful. Thank you very much.

**Comment by kqyang** [comment]
exoplayer: https://github.com/google/ExoPlayer

Also, the content is usually hosted online instead of stored locally - though it should work even if stored locally.

**Comment by wlc520123** [comment]
OK, thanks for your tips.
On line video is the next step, after I try this local video playback well.

**Comment by kqyang** [comment]
I am closing this bug. Feel free to re-open it if you have more questions.

**Comment by wlc520123** [comment]
How to reopen it?

**Comment by wlc520123** [comment]
exoplayer demo in https://github.com/google/ExoPlayer  is a client-server mode app, I add my video huoguoen.mp4, it could not playback.
Then I make a mpd use this command, and add huoguoen.mpd to server and exoplayer demo, 
mpd_generator \
--input "huoguoen.mp4.media_info" \
--output "huoguoen.mpd"
Butt it could not playback, ether.

Then I checked out the mpd works after 10s.  Does it the mater?

**Comment by wlc520123** [comment]
my work is:


  1. Download shaka-packager(https://github.com/google/shaka-packager) and build it. command I used: 
cd ~ 
mkdir shaka_packager 
cd shaka_packager 
gclient config https://www.github.com/google/shaka-packager.git --name=src 
gclient sync cd src ninja -C out/Debug

2.Get a video (huoguo.mp4) and change it to widevine protection, using command:
cd ~/shaka-packager/src/out/Debug

./packager input='huoguo.mp4',stream=video,output=huoguoen.mp4 \
--enable_widevine_encryption \
--key_server_url "https://license.uat.widevine.com/cenc/getcontentkey/widevine_test" \
--content_id "3031323334353640" \
--signer "widevine_test" \
--aes_signing_key "1ae8ccd0e7985cc0b6203a55855a1034afc252980e970ca90e5202689f947ab9" \
--aes_signing_iv "d58ce954203b7c9a9a9d467f59839249" \
--output_media_info

./mpd_generator \
--input "huoguoen.mp4.media_info" \
--output "huoguoen.mpd"

Finally, huoguoen.mp4 and huoguo.mpd can be generated.
And huoguoen.mp4 can playback well at first 10s using pre-installed video player(without a widevine license server url).

3.build self simple server:
Use a phone
(marked as phone1) which can run as root ,and open 8080 as httpd service:
adb shell
busybox httpd -p 8080 -h /sdcard/www/

Then, push huoguoen.mp4 & huoguoen.mpd to /sdcard/www/:
adb push /path/to/huoguoen.mp4 /sdcard/www/
adb push /path/to/huoguoen.mpd /sdcard/www/

Then, use another phone (marked as phone2) to playback the video huoguoen.mp4.

Phone1 and phone2 connect to the same wifi, and we can get the ip address of phone1 (e.g.192.168.1.2).

To verify connection well:
Using phone2's browser, we input and goto http://192.168.1.2/huoguoen.mp4.
The video can playback well at first 10s using pre-installed video player.

4.add this video source to exoplayer
Get the source of exoplayer and make a self new project usting the demo.
In samples.java, add codes:

private static final String WIDEVINE_GTS_MPD1 =
"http://192.168.1.2:8080/huoguoen.mpd";

public static final Sample[] LOCAL = new Sample[] {
new Sample("huoguoen", "3031323334353640","widevine_test","http://192.168.1.2:8080/huoguoen.mpd", Util.TYPE_DASH),
new Sample("huoguoen1", "3031323334353640", "widevine_test",
WIDEVINE_GTS_MPD1, Util.TYPE_DASH),
};

In SampleChooserActivity.java add codes:
group = new SampleGroup("local");
group.addAll(Samples.LOCAL);

5.build and run, after installed the apk, the main activity has a new list:
-local
----huoguoen
----huoguoen1

6.playback the video added by my self:
click the huoguoen or huoguoen1, the palyer can be display.
But could not playback.

**Comment by kqyang** [comment]
If you have any problem with using exoplayer, please ask there instead: https://github.com/google/ExoPlayer. I believe exoplayer bundles a few manifests for testing. You may want to try that out first.
