### ISSUE TITLE
self-initializing segments

### ISSUE THREAD

**Issue by sammirata** [google/shaka-packager#137]
I have an application that requires the live profile with self-initializing segments. I have not seen in any documents how to configure self-initializing segments. Are they supported?

**Comment by kqyang** [comment]
No, that is not supported. In fact, it is not compliant to DASH spec:

23009-1:2012
7.3 Media Presentation based on the ISO base media file format
7.3.1 General

> For ISOBMFF-based Media Presentation the following applies:
>
> 1) In all cases for which a Representation contains more than one Media Segment, the following applies:
>
> i) The Initialization Segment as defined in 6.3.3 shall be present.
> ii) Media Segments shall not be self-initializing. The Media Segment format is defined in 6.3.4.

We will support self-initializing segments for TS output though.
