### ISSUE TITLE
Problems playing webm in Firefox

### ISSUE THREAD

**Issue by carsanper** [google/shaka-packager#138]
Hello,
 We have the following dash multicodec example:

http://video.i3television.es/dash/multicodec/manifest.mpd

Playing in Shaka player demo site (http://shaka-player-demo.appspot.com/demo/) on Chrome works perfectly but in Firefox it stops after 12s.

In fact the proper Shaka Player example Angel One (multicodec,multilingual) has the same problem only in Firefox

 I have also attached the script that generates my example:

packager --profile on-demand \
  input=v-1080-libx264.tmp.mp4,stream=video,output=output/v-1080-libx264.mp4 \
  input=v-720-libx264.tmp.mp4,stream=video,output=output/v-720-libx264.mp4 \
  input=v-480-libx264.tmp.mp4,stream=video,output=output/v-480-libx264.mp4 \
  input=v-360-libx264.tmp.mp4,stream=video,output=output/v-360-libx264.mp4 \
  input=v-240-libx264.tmp.mp4,stream=video,output=output/v-240-libx264.mp4 \
  input=v-240-libx264.tmp.mp4,stream=audio,output=output/audio.mp4 \
  input=v-1080-vp9.tmp.webm,stream=video,output=output/v-1080-vp9.webm \
  input=v-720-vp9.tmp.webm,stream=video,output=output/v-720-vp9.webm \
  input=v-480-vp9.tmp.webm,stream=video,output=output/v-480-vp9.webm \
  input=v-360-vp9.tmp.webm,stream=video,output=output/v-360-vp9.webm \
  input=v-240-vp9.tmp.webm,stream=video,output=output/v-240-vp9.webm \
  input=v-240-vp9.tmp.webm,stream=audio,output=output/audio.webm \
  --mpd_output output/manifest.mpd

Any suggest in order to fox this issue?.

**Comment by kqyang** [comment]
It is a known problem in firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1291451

The problem has been fixed in firefox 49. Can you try version 49 beta release?

I am closing this issue. Feel free to re-open it if you are still seeing problem in version 49.

**Comment by carsanper** [comment]
In version 49 beta it works perfectly. Thank you!
