### ISSUE TITLE
create segment-template type VOD contents

### ISSUE THREAD

**Issue by xixi10111011** [google/shaka-packager#142]
hi all,

I can use the command-line example to generate a single-segment type VOD contents.

But it seems that it is not able to generate segment-template type VOD contents, it seems that segment-template type is only used in LIVE case.

is there a way to create segment-template type VOD contents?

**Comment by kqyang** [comment]
My last statement is incorrect. We can actually use live profile with static MPD@Type for non-live content. This does exactly what is requested in this issue.
