### ISSUE TITLE
About generate AES protected hls through shaka packager

### ISSUE THREAD

**Issue by YingChen-dci** [google/shaka-packager#144]
Hello,
We know that Shaka Packager is support HLS now, and thinking to try to generate AES protected hls through shaka packager. Input video file will be .mp4 .
As "Added TS (output) and HLS (output) with SAMPLE-AES encryption support. Note that only H.264 and AAC are supported right now." being mentioned in changelog.
And several hls flag being added in packager, according packager -help result.

We would like to know how the packager command look like
For example, like:
packager input=/root/media/Uyuni_02.mp4,stream=video,output=/var/www/contents/enc_Uyuni_02.mp4
--playlist_name "hls_Uyuni_02.m3u8" 
--hls_base_url "xxx"
--hlls_master_playlist_output "/var/www/contents"

it would be great to have sample or document etc..

**Comment by kqyang** [comment]
There are actually some examples in README (scroll to the bottom). Here is an example with encryption:

```
./packager 'in=bourne_1000k.mp4,stream=video,segment_template=test/media_video_$Number$.ts,playlist_name=video_playlist.m3u8' 'in=bourne_1000k.mp4,stream=audio,segment_template=test/media_audio_$Number$.ts,playlist_name=audio_playlist.m3u8' --single_segment=false --hls_master_playlist_output="test/master_playlist.m3u8" --hls_base_url="http://localhost:10000/test/" --enable_widevine_encryption --key_server_url "https://license.uat.widevine.com/cenc/getcontentkey/widevine_test" --content_id "3031323334353637" --signer "widevine_test" --aes_signing_key "1ae8ccd0e7985cc0b6203a55855a1034afc252980e970ca90e5202689f947ab9" --aes_signing_iv "d58ce954203b7c9a9a9d467f59839249"
```

Let us know if it works for you.

**Comment by kqyang** [comment]
Close due to inactivity. Feel free to reopen it if needed.
