### ISSUE TITLE
Multi-period DASH

### ISSUE THREAD

**Issue by grantg182** [google/shaka-packager#146]
Hey

I was wondering how to implement multi-period DASH. Essentially, I am looking to have more than one audio/video set represented by a single MPD to allow the creation of an mpd which plays back an advert (with audio/video) and then the video programme (audio/video). There would be no specific time length associated with either, although they will be muxed by ffmpeg to ensure the tracks are the same length, but would prefer these to be stored individually instead of muxing the advert with the programme to create a single mp4 with both advert+programme audio/video in one file.

Have searched around and found nothing on this subject with any meaningful output. 

Can anyone help? Thanks!

**Comment by kqyang** [comment]
It is not supported right now. We are thinking of supporting it later this year or early next year!

**Comment by grantg182** [comment]
Thanks, hopefully sooner rather than later ;-)

**Comment by grantg182** [comment]
Just wondering if there has been any movement on this?

**Comment by coopers98** [comment]
Adding my support for this one

**Comment by kqyang** [comment]
Experimental support for multi-period DASH is already added.
