### ISSUE TITLE
curl_easy_perform() fails on Windows 10

### ISSUE THREAD

**Issue by hchen1506** [google/shaka-packager#147]
I am running an example command on Windows (Win 10, 64 bit) as follows:

``` shell
./out/Release/packager.exe \
  'input=udp://224.1.1.5:5003,stream=audio,init_segment=live-audio.mp4,segment_template=live-audio-$Number$.mp4,bandwidth=130000'  \
  'input=udp://224.1.1.5:5003,stream=video,init_segment=live-video-sd.mp4,segment_template=live-video-sd-$Number$.mp4,bandwidth=2000000' \
  'input=udp://224.1.1.5:5002,stream=video,init_segment=live-video-hd.mp4,segment_template=live-video-hd-$Number$.mp4,bandwidth=5000000' \
--profile live \
--mpd_output live.mpd \
--enable_widevine_encryption \
--key_server_url "https://license.uat.widevine.com/cenc/getcontentkey/widevine_test" \
--content_id "3031323334353637" \
--signer "widevine_test" \
--aes_signing_key "1ae8ccd0e7985cc0b6203a55855a1034afc252980e970ca90e5202689f947ab9" \
--aes_signing_iv "d58ce954203b7c9a9a9d467f59839249" \
--crypto_period_duration 1800
```

It fails with errors as follows:

``` shell
[0909/172048:ERROR:http_key_fetcher.cc(134)] curl_easy_perform() failed: Peer certificate cannot be authenticated with given CA certificates.
[0909/172048:ERROR:packager_util.cc(94)] Widevine encryption key source failed to fetch keys: 7 (HTTP_FAILURE): curl_easy_perform() failed: Peer certificate cannot be authenticated with given CA certificates.
```

Same errors occur when I encrypt some local videos.

**Comment by hchen1506** [comment]
One simple way to make it work is to download a certificate "cacert.pem" from 

https://curl.haxx.se/docs/caextract.html

And add one line on the source code:

--- i/packager/media/base/http_key_fetcher.cc
+++ w/packager/media/base/http_key_fetcher.cc
@@ -116,6 +116,7 @@ Status HttpKeyFetcher::FetchInternal(HttpMethod method,
   curl_easy_setopt(curl, CURLOPT_FOLLOWLOCATION, 1L);
   curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, AppendToString);
   curl_easy_setopt(curl, CURLOPT_WRITEDATA, response);
**\+ curl_easy_setopt(curl, CURLOPT_CAINFO, "cacert.pem");**
   if (method == POST) {
     curl_easy_setopt(curl, CURLOPT_POSTFIELDS, data.c_str());
     curl_easy_setopt(curl, CURLOPT_POSTFIELDSIZE, data.size());

**Comment by kqyang** [comment]
I am thinking of just disabling peer verification. Since the peer end point is specified by the user running packaging, it does not seem that there is any risk involved.

```
curl_easy_setopt(curl, CURLOPT_SSL_VERIFYPEER, 0);
```

What do you think?
