### ISSUE TITLE
it is possible to crypt only half of the contant ?

### ISSUE THREAD

**Issue by guillaumemarc** [google/shaka-packager#148]
i have some drop frame with my device with is in widevine level 3. I want to only crypt half of the file to to avoid  drop frame. 
I propose to do 10s in clear 10 crypted 10s in clear  10 crypted .... it is possible ?

**Comment by kqyang** [comment]
No, that is not supported - it is not secure either.

However, pattern encryption is supported: see "cens" or "cbcs" encryption modes in CENC v3 spec (ISO/IEC 23001-7:2016).  By default, a 1:9 skip pattern is used, i.e. every one 16-bytes-block out of 10 16-bytes-blocks are encrypted. Pattern encryption can be enabled with flag --protection_scheme=cens or --protection_scheme=cbcs.

Note that the player may need to be updated to support the new encryption schemes.

**Comment by kqyang** [comment]
Close due to in-activities. Feel free to re-open it if needed.
