### ISSUE TITLE
dropped audio sample muxing ts -> mp4

### ISSUE THREAD

**Issue by baconz** [google/shaka-packager#150]
I'm trying remux TS -> MP4, and it seems like the packager is dropping the last audio sample. 

I have attached some content to replicate with -- If you run against source.ts in the attached zip with 47363dd06afe03467c65d4639ad34c4c8283553f:

```
packager 'input=source.ts,output=packaged-init.mp4,stream=audio,segment_template=packaged-$Time$.mp4,output_format=MP4'
```

The muxer seems to drop the last sample:

```
$ ffprobe  -show_packets -show_entries packet=codec_type,pts,dts,duration -i source.ts  -of csv 2>/dev/null | fgrep audio  | wc -l
      51
```

```
$ ffprobe  -show_packets -show_entries packet=codec_type,pts,dts,duration -i <(cat packaged-init.mp4 packaged-1379760.mp4)  -of csv 2>/dev/null | fgrep audio  | wc -l
      50
```

Am I looking at something the wrong way here?

[sample_dropped.zip](https://github.com/google/shaka-packager/files/473691/sample_dropped.zip)

**Comment by kqyang** [comment]
There are only 50 frames in the source content. You can count the number of frames and number of packets using the below command:

```
❯ ffprobe -show_streams -count_frames -count_packets source.ts
```

Look for nb_read_frames and nb_read_packets in the output.

I am closing it as invalid. Feel free to re-open it or just post another comment if you have more questions.
