### ISSUE TITLE
failed to determine the text file format for vtt file in v.1.5.1

### ISSUE THREAD

**Issue by FantasRu** [google/shaka-packager#152]
HI,it me too.I used to raise this questions in [#130](https://github.com/google/shaka-packager/issues/130).
After that,i updated `packager` in docker.And it worded well.
Then,in this time.I deployed packager in `Ubuntu 16.04`.And this problem happened again.

```
shaka-packager version v1.5.1-c540e5a-release: Packager driver program. Usage:
```
```
$ packager \
> input=/home/user/video/lib/456/456-sd.mp4,stream=video,output=/home/user/video/lib/456/456-sd-packed.mp4 \
> input=/home/user/video/lib/456/456-ld.mp4,stream=audio,output=/home/user/video/lib/456/456-audio-packed.mp4 \
> input=../empty.vtt,stream=text,output=/home/user/video/lib/456/456.vtt \
> --profile on-demand \
> --mpd_output /home/user/video/lib/456/456.mpd
[0918/111012:ERROR:packager_main.cc(194)] Failed to determine the text file format for ../empty.vtt
```

**Comment by kqyang** [comment]
What is inside "empty.vtt"? An empty file? 

Packager inspects the file and determines whether it is a valid vtt file; if it is not valid, an error like above will be reported.

**Comment by kqyang** [comment]
Close due to inactivity. Feel free to reopen it if needed.
