### ISSUE TITLE
parse P frame not well

### ISSUE THREAD

**Issue by FeiCao** [google/shaka-packager#153]
Hi,
packager version is 1.4.x 
I have a h264 file, packager could not support well, I frame can parse normally, but p frame is not. could you help me?

I upload the h264 file to my cloud, you can download from the link(http://pan.baidu.com/s/1i57CeBr; password: vpai), thank you!

**Comment by kqyang** [comment]
The file does not seem to be a valid mp4 or ts file. Can you upload a mp4 or ts containing the I-frame and a problematic p frame instead?

**Comment by FeiCao** [comment]
That is a h264 standard file, it is an input stream file. and you want me to upload the segments ?
I uploaded the segments and mpd file(link: http://pan.baidu.com/s/1dEGr9hJ    password:2sqq)

**Comment by kqyang** [comment]
This looks like Chrome's problem. I tried on Safari and Edge, both works.

Can you file a bug in crbug.com instead? You may cc me in the bug report: kqyang@chromium.org
