### ISSUE TITLE
what kind of video/audio can be protected with widevine using e-dash packager?

### ISSUE THREAD

**Issue by wlc520123** [google/shaka-packager#157]
I'm trying to make some videos protected with widevine.
the kinds of my videos are: mp4/3gp/avi/dat/dpg/fla/mpeg/mpg/rmvb/rv/swf/wmv
Are there some kinds of video could not be protected with widevine using this packager?
What kinds of videos this packager can running correctly to protect videos using widevine?

**Comment by wlc520123** [comment]
i.e. I could not understand the list "Current supported codecs" in README, and could not find corecctly video/audio

**Comment by kqyang** [comment]
The list you provided are containers. ISO-BMFF, aka mp4 is supported. Other container formats mentioned in your list, like 3gp may work as it is derived from iso-bmff. I am not familiar with other container formats you mentioned. If they are based on iso-bmff or mpeg-2-ts, then they are supported.

**Comment by wlc520123** [comment]
What extension name of videos using the container MPEG2-TS?
What containers are derived from ISO-BMFF? And what are the extension names? Is there any website can be referenced?

Thanks.

**Comment by kqyang** [comment]
> What extension name of videos using the container MPEG2-TS?
Typically with extension .ts

> What containers are derived from ISO-BMFF? And what are the extension names? Is there any website can be referenced?
https://en.wikipedia.org/wiki/ISO_base_media_file_format
