### ISSUE TITLE
Automatic track_type recognition for UHD1/2

### ISSUE THREAD

**Issue by chartelt** [google/shaka-packager#163]
In recent version 1.5.1 support for track_types Audio, SD and HD only is given from what I see and SD/HD threshold is configurable. I was wondering about a planned addition of automatic recognition of UHD track types in upcoming versions of the packager, since I understood that the Widevine Cloud Service now recognizes track type UHD1/2.

**Comment by kqyang** [comment]
Yes, working in progress. Stay tuned.
