### ISSUE TITLE
Support for Dolby AC3 in MPEG2-TS

### ISSUE THREAD

**Issue by lpluto** [google/shaka-packager#165]
I would like to ask if you plan to add Dolby AC3/EAC3 support for HLS and if yes then when can we expect this feature?

**Comment by kqyang** [comment]
Yes, but we don't have a resource to work on it right now. The earliest time would be some time in 2017.

**Comment by zshenker** [comment]
@kqyang We would be very interested in support for AC3/E-AC3 in TS containers.

**Comment by kqyang** [comment]
Move EAC3 to a separate issue (#279) as there are extra complexities involved. @zshenker do you need both AC3 and E-AC3 support?

**Comment by zshenker** [comment]
@kqyang We are ideally needing to support both AC3 & EAC3 to have parity with our existing packaging tools.

**Comment by kqyang** [comment]
Sure. Another question, do you use AC-4 right now or plan to use AC-4 in the future?

**Comment by zshenker** [comment]
@kqyang We are not using AC-4 currently, and no plans for it at this stage. AC-3 & E-AC3 are really the focus for us currently.
