### ISSUE TITLE
Setting clear lead to zero does not work for encrypted M3U8 outputs

### ISSUE THREAD

**Issue by bmurphy1976** [google/shaka-packager#169]
I discovered that setting `--clear-lead 0` when generating an encrypted M3U8 output does not work properly.  If clear lead is set to zero, none of the segments in the file are encrypted if encryption is enabled.  It must be set to something greater than zero in order for encryption to kick in.

The problem with not supporting a clear lead of zero is that the leading unencrypted segments in the M3U8s will cause a noticeable audio glitch when the encryption kicks in when played back in Safari on OSX. 

I dug around in the code, and `HlsNotifyMuxerListener::OnEncryptionStart` is called before `HlsNotifyMuxerListener::OnMediaStart`, but it expects `media_started_` to be true.  `media_started_` is of course set to true by `HlsNotifyMuxerListener::OnMediaStart`.

I was able to create a file that was fully encrypted from the beginning by adding an additional call to `this->OnEncryptionStart();` to the end of `HlsNotifyMuxerListener::OnMediaStart` in `hls_notify_muxer_listener.cc`:

```c++
void HlsNotifyMuxerListener::OnMediaStart(const MuxerOptions& muxer_options,
                                          const StreamInfo& stream_info,
                                          uint32_t time_scale,
                                          ContainerType container_type) {
  MediaInfo media_info;
  if (!internal::GenerateMediaInfo(muxer_options, stream_info, time_scale,
                                   container_type, &media_info)) {
    LOG(ERROR) << "Failed to generate MediaInfo from input.";
    return;
  }
  const bool result = hls_notifier_->NotifyNewStream(
      media_info, playlist_name_, ext_x_media_name_, ext_x_media_group_id_,
      &stream_id_);
  if (!result) {
    LOG(WARNING) << "Failed to notify new stream.";
    return;
  }

  media_started_ = true;

  this->OnEncryptionStart();
}
```

This works (at least for my test case), but I don't understand the code well enough to see the full consequences of making this additional call.

**Comment by kqyang** [comment]
Thanks for reporting this problem. Good findings on HlsNotifyMuxerListener::OnEncryptionStart and HlsNotifyMuxerListener::OnMediaStart. You are correct that there is a problem there. We'll look into how to fix it.
