### ISSUE TITLE
Custom Common Encryption API interface

### ISSUE THREAD

**Issue by lpluto** [google/shaka-packager#170]
Shaka Packager uses Common Encryption API for Widevine DRM to get required data to encrypt content. Request contains "drm_types":["WIDEVINE"]. 

Would it be possible to implement this interface to provide encryption data also for other key systems, e.g. PlayReady?

It would help with limitation to only 1 key when using fixed key encryption. 

Kind regards,
Łukasz Pluto

**Comment by kqyang** [comment]
> Would it be possible to implement this interface to provide encryption data also for other key systems, e.g. PlayReady?

Yes, definitely. You can implement the key source interface defined here: https://github.com/google/shaka-packager/blob/master/packager/media/base/key_source.h. You can then replace the key source used in https://github.com/google/shaka-packager/blob/master/packager/app/packager_util.cc#L108 to the custom key source you implemented. Let us know if you have any further / detail questions!

> It would help with limitation to only 1 key when using fixed key encryption.

Not sure what you mean on this. Support different keys for different streams in fixed key encryption?

**Comment by lpluto** [comment]
Thank you for information. 

I mean that when using "enable_fixed_key_encryption" option then there is no possibility to use different keys per Audio/SD/HD/UHD? Ot maybe it can be done when running packager 	separately for streams of type Audio/SD/HD/UHD, getting MPD info files and combining them to receive final MPD manifest?

**Comment by kqyang** [comment]
I see. Yes, that is the only way to do it right now. We do want to support it directly at some point, but we don't have resource working on it right now.

**Comment by kqyang** [comment]
Closing this issue. Feel free to reopen it if you have more questions.
