### ISSUE TITLE
Widevine encrypted content playback issue.

### ISSUE THREAD

**Issue by pssreddy** [google/shaka-packager#171]
http://shaka-player-demo.appspot.com/demo/ is not playing the DASH Widevine encrypted content generated by shaka-packager version 47363dd (centos 7) . The Player is throwing Shaka Error DRM.REQUESTED_KEY_SYSTEM_CONFIG_UNAVAILABLE ().

Used Command For Generating the Widevine encrypted content:

./packager input=/home/user/Desktop/streams/600.mp4,stream=video,output=/var/www/html/mpeg/encrypted_600_cenc.mp4 
--enable_widevine_encryption=true 
--key_server_url "https://license.uat.widevine.com/cenc/getcontentkey/widevine_test" 
--content_id "3031323334353637" 
--signer "widevine_test" 
--aes_signing_key "1ae8ccd0e7985cc0b6203a55855a1034afc252980e970ca90e5202689f947ab9" 
--aes_signing_iv "d58ce954203b7c9a9a9d467f59839249" 
-protection_scheme "cenc" 
-webm_subsample_encryption="true" 
--mpd_output /var/www/html/mpeg/600_senc.mpd

Please suggest the solution ASAP as am struggling with this issue from last few days.

Thanks in advance.

**Comment by kqyang** [comment]
The command should work although some of the parameters can be omitted. (Actually the same command worked for me)

What browser are you using for playback? From the error, looks like the player/browser does not recognize Widevine DRM.

Can you attach the generated mpd and maybe the media files as well?

**Comment by pssreddy** [comment]
Thank-you for your replay,
Please find the attached zip file("dash_encry_vod.zip") contains manifest and media file.
I tried to play content using **http://shaka-player-demo.appspot.com/demo/** player.


[dash_encry_vod.zip](https://github.com/google/shaka-packager/files/599144/dash_encry_vod.zip)

**Comment by kqyang** [comment]
The content looks good. I don't have problem playing the content.

Which proxy server are you using? 

Do you have problem playing the sample asset comes with shaka-player-demo?

**Comment by pssreddy** [comment]
Sorry for late reply, i was out of station.

I have no issue with playing shaka-player's sample widevine asset ( "Tears of Steel (Widevine)" ).

I tried to play my content using below custom license server url.
"https://license.uat.widevine.com/cenc/getcontentkey/widevine_test"

This time player existed with following error,
Shaka Error DRM.LICENSE_REQUEST_FAILED (shaka.util.Error { "category": 1, "code": 1002, "data": [ "https://license.uat.widevine.com/cenc/getcontentkey/widevine_tset" ], "message": "Shaka Error NETWORK.HTTP_ERROR (https://license.uat.widevine.com/cenc/getcontentkey/widevine_tset)", "stack": "Error: Shaka Error NETWORK.HTTP_ERROR (https://license.uat.widevine.com/cenc/getcontentkey/widevine_tset)\n at new shaka.util.Error (http://shaka-player-demo.appspot.com/lib/util/error.js:77:13)\n at XMLHttpRequest.xhr.onerror (http://shaka-player-demo.appspot.com/lib/net/http_plugin.js:77:14)" })

For more information please find the attached console log.

Question:
Is the following license server url is valid ? If not, do we have any sample test license server url.
"https://license.uat.widevine.com/cenc/getcontentkey/widevine_test"
[console_log.txt](https://github.com/google/shaka-packager/files/608960/console_log.txt)

thank-you

**Comment by kqyang** [comment]
The license server url should be: https://proxy.uat.widevine.com/proxy. Note that it is only for testing.

**Comment by pssreddy** [comment]
Thanks a lot @kqyang, am able to play the content.

**Comment by pssreddy** [comment]
@kqyang How to play HLS encrypted content..?
I tried to play HLS encrypted content using below players

1. **Apple Safari**  Only able to play for first 10 seconds and remaining segments are glitchy.

2. **https://www.hlsplayer.net/** No playback started.

3. **https://chrome.google.com/webstore/detail/native-hls-playback/emnphkkblegpebimobpbekeedfgemhof/reviews?hl=en-US** Only able to play for first 10 seconds and frozen.

Used the following Command for encrypting the segments:

input=/home/siva/Desktop/streams/fifo1.mp4,stream=video,segment_template=/var/www/html/mpeg/hls/output$Number$.ts,playlist_name=video_playlist.m3u8'   'input=/home/siva/Desktop/streams/fifo1.mp4,stream=audio,segment_template=/var/www/html/mpeg/hls/output_audio$Number$.ts,playlist_name=audio_playlist.m3u8,hls_group_id=audio,hls_name=ENGLISH'   --single_segment=false --enable_widevine_encryption=true --key_server_url "https://license.uat.widevine.com/cenc/getcontentkey/widevine_test" --content_id "3031323334353637" --signer "widevine_test" --aes_signing_key "1ae8ccd0e7985cc0b6203a55855a1034afc252980e970ca90e5202689f947ab9" --aes_signing_iv "d58ce954203b7c9a9a9d467f59839249" -protection_scheme "cenc"  --hls_master_playlist_output="/var/www/html/mpeg/hls/master_playlist.m3u8"   --hls_base_url="http://192.168.8.43/mpeg/hls/"

Please find the attachment for encrypted segments output.

[hls_widevine_encry.tar.gz](https://github.com/google/shaka-packager/files/619311/hls_widevine_encry.tar.gz)


thank-you

**Comment by kqyang** [comment]
You'll need to find a player that supports Widevine + HLS, which unfortunately, is not supported in the players you mentioned.

You may try --fixed_key_encryption instead, which should play in Safari.

As for DASH CBCS, are you using Chrome? I don't think Chrome supports CBCS right now.

**Comment by pssreddy** [comment]
Hi KongqunYang,

The license server url(" https://proxy.uat.widevine.com/proxy ") which you provided was working earlier. 
Now If i use this as Custom license server, shaka player is throwing below error.
shaka Error DRM.REQUESTED_KEY_SYSTEM_CONFIG_UNAVAILABLE ()

can you please suggest...! Thank-You

**Comment by kqyang** [comment]
Is it the same content?

**Comment by pssreddy** [comment]
Yes, same content. It is already available in attachments(Third message attachment).

I am trying to play our custom encrypted asset using chrome-cast (Result : **Fail**), then i tried to play in shaka-player, found this error(**shaka Error DRM.REQUESTED_KEY_SYSTEM_CONFIG_UNAVAILABLE ()**), the same license server url was working for our custom asset and shaka-packagers output.

Now it is not working..
[dash_encry_vod.zip](https://github.com/google/shaka-packager/files/700711/dash_encry_vod.zip)

**Comment by pssreddy** [comment]
Yes, same content.
It seems like Operating System Issue, please find the observation below

It is not working with
OS               : CentOS release 6.8 (Final)
Web browser : GoogleChrome ( Version 54.0.2840.90 (64-bit) )
Web browser : GoogleChrome ( Version 55.0.2883.87 (64-bit) ) ( Upgraded to latest version after checking in widows )

It is working with windows am proceeding with it.
OS  : windows 7 professional
Web browser : GoogleChrome ( Version 55.0.2883.87 (64-bit) )

**Comment by kqyang** [comment]
Are you using the shaka player demo @ https://shaka-player-demo.appspot.com/demo/?

Can you check if you are able to play the Widevine asset included in the demo site?

I suggest you posting the question/issue in https://github.com/google/shaka-player instead. They can help you identify where the problem is.

**Comment by sivarajendranaidu** [comment]
Created a Widevine CENC DASH Content using shaka packager with following command
./packager input=/home/siva/Desktop/fifo.mp4,stream=video,output=/home/siva/Desktop/fifo_v_cenc.mp4 --enable_widevine_encryption=true --key_server_url "https://license.uat.widevine.com/cenc/getcontentkey/widevine_test" --content_id "3031323334353637" --signer "widevine_test" --aes_signing_key "1ae8ccd0e7985cc0b6203a55855a1034afc252980e970ca90e5202689f947ab9" --aes_signing_iv "d58ce954203b7c9a9a9d467f59839249" -protection_scheme "cenc" --mpd_output /home/siva/Desktop/fifo_v_cenc.mpd
[0404/032902:INFO:demuxer.cc(58)] Initialize Demuxer for file '/home/siva/Desktop/fifo.mp4'.
[0404/032902:INFO:track_run_iterator.cc(166)] Edit list with media time 0 ignored.
[0404/032902:INFO:demuxer.cc(170)] Demuxer::Run() on file '/home/siva/Desktop/fifo.mp4'.
[0404/032904:INFO:single_segment_segmenter.cc(118)] Update media header (moov) and rewrite the file to '/home/siva/Desktop/fifo_v_cenc.mp4'.
[0404/032905:INFO:mp4_muxer.cc(165)] MP4 file '/home/siva/Desktop/fifo_v_cenc.mp4' finalized.
Packaging completed successfully.

As current shaka player is not supporting playback over http; I had setup Shaka Player v2.0.0-debug  locally and testing on Chrome Browser (Windows 8.1) using LA_URL : https://proxy.uat.widevine.com/proxy in Shaka Player

Only first few frames are decoded and latter stalls

Please find the error prompted as follows:
Shaka Error DRM.LICENSE_REQUEST_FAILED (shaka.util.Error { "category": 1, "code": 1002, "data": [ "https://proxy.uat.widevine.com/proxy" ], "message": "Shaka Error NETWORK.HTTP_ERROR (https://proxy.uat.widevine.com/proxy)", "stack": "Error: Shaka Error NETWORK.HTTP_ERROR (https://proxy.uat.widevine.com/proxy)\n at new shaka.util.Error (http://192.168.9.79/shaka-player/lib/util/error.js:63:13)\n at XMLHttpRequest.xhr.onerror (http://192.168.9.79/shaka-player/lib/net/http_plugin.js:86:14)" })

**Comment by kqyang** [comment]
This looks like a player side network error. @joeyparrish Any idea what is going on?

**Comment by joeyparrish** [comment]
Error code 1002 (HTTP_ERROR) is not any specific HTTP status code, such as 404.  It indicates that the entire HTTP request was blocked by the client or otherwise failed below the level of HTTP.

Usually, this is due to a CORS error.  If you open the JavaScript console, Chrome will tell you explicitly in an error message there if the request failed due to cross-origin restrictions.

@pssreddy, can you confirm if there are errors in the JS console to this effect?

**Comment by sivarajendranaidu** [comment]
@joeyparrish / @kqyang

Please find the JS Console output.
XMLHttpRequest cannot load https://pror/demo/#asset=http://192.168.43.246/dash_encry_vod/fifo_v_cenc.mpd;license=https://proxy.uat.widevine.com/proxy;lang=en-US:1 XMLHttpRequest cannot load https://proxy.uat.widevine.com/proxy. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://192.168.43.191' is therefore not allowed access.
main.js:466 Player error s…a.u…l.Error {category: 6, code: 6007, data: Array[1], message: "Shaka Error DRM.LICENSE_REQUEST_FAILED (shaka.util…91/shaka-player/lib/net/http_plugin.js:86:14)"↵})", stack: "Error: Shaka Error DRM.LICENSE_REQUEST_FAILED (sha…191/shaka-player/lib/media/drm_engine.js:1024:24)"}

It got License 200 0K
Request URL:https://proxy.uat.widevine.com/proxy
Request Method:POST
Status Code:200 
Remote Address:216.239.32.27:443

I had fixed the CORS issue at the apache server where I had my shaka packager created content.
I tried the content which pssreddy had posted too. I am having same issue.

I am using WAMPSERVER as webserver on Windows 8.1 where my shaka player is hosted
Is there any settings which I need to check at player side

I too feel that same content was playing fine earlier

Please provide your inputs.

**Comment by joeyparrish** [comment]
@pssreddy, this is the important part of the log:

```
XMLHttpRequest cannot load
https://pror/demo/#asset=http://192.168.43.246/dash_encry_vod/fifo_v_cenc.mpd;license=https://proxy.uat.widevine.com/proxy;lang=en-US:1 XMLHttpRequest cannot load https://proxy.uat.widevine.com/proxy.
No 'Access-Control-Allow-Origin' header is present on the requested resource.
Origin 'http://192.168.43.191' is therefore not allowed access.
```

The license server proxy does not allow you to access it from your local site.  Try this proxy instead, which does permit access from anywhere: https://widevine-proxy.appspot.com/proxy

**Comment by sivarajendranaidu** [comment]
Thanks a lot @joeyparrish / @kqyang for your kind support
I was able to play content with LA_URL = https://widevine-proxy.appspot.com/proxy

**Comment by joeyparrish** [comment]
Glad we could help!

**Comment by sivarajendranaidu** [comment]
Hi @joeyparrish  / @kqyang 
I am trying to use https://widevine-proxy.appspot.com/proxy to play content in Shaka Player created by Shaka Packager.
Please find the error in the shaka Player as follows:
main.js:466 Player error shaka.util.Error {category: 6, code: 6001, data: Array(0), message: "Shaka Error DRM.REQUESTED_KEY_SYSTEM_CONFIG_UNAVAILABLE ()", stack: "Error: Shaka Error DRM.REQUESTED_KEY_SYSTEM_CONFIG…:8080/shaka-player/lib/media/drm_engine.js:522:27"}

Please find the shaka Packager sample attached.
Please provide your inputs.

Thanks and Regards,
Rajendra
[shaka_output.zip](https://github.com/google/shaka-packager/files/1901581/shaka_output.zip)

**Comment by joeyparrish** [comment]
@sivarajendranaidu: Are you using Chrome?  Is the application URL http or https?  Shaka Player has an entry for this in our [FAQ](https://shaka-player-demo.appspot.com/docs/api/tutorial-faq.html) which I quote below:

> **Q:** I am getting `REQUESTED_KEY_SYSTEM_CONFIG_UNAVAILABLE` or error code 6001.
> 
> **A:** The most common cause is that you are not using a secure origin.  The EME API in the browser requires a secure origin, which means `https` or `localhost`.  Chrome enforces this requirement, but other browsers may not yet.  See the [announcement][eme_https] for more info.
> 
> You should also check that your platform/browser actually supports the key system.  If your manifest contains only PlayReady, it will need to be played on IE/Edge, a Chromecast, or another device with PlayReady.  See the [DRM tutorial][drm_tutorial] for more info.
> 
> This will also happen if you use `Storage` to store protected content (when `usePersistentLicense` is true).  Currently, persistent licenses are supported on Chromebooks and Chrome 64+ on Mac/Windows.  On other platforms, you can only store clear content or store only the content offline (i.e. set `usePersistentLicense` configuration to false).

[drm_tutorial]: https://shaka-player-demo.appspot.com/docs/api/tutorial-drm-config.html
[eme_https]: https://sites.google.com/a/chromium.org/dev/Home/chromium-security/deprecating-powerful-features-on-insecure-origins

I hope that helps!
