### ISSUE TITLE
Packager fails to parse WebM from ffmpeg over udp

### ISSUE THREAD

**Issue by iSchluff** [google/shaka-packager#172]
Hi.
With the commands

```
ffmpeg -y -hide_banner -analyzeduration 10000 -i rtmp://foo/rtmp/bar \
  -map v:0 -map a:0 \
    -c:v libvpx -threads 4 -aspect 16:9 -pix_fmt yuv420p -deadline realtime -crf 10 \
    -s 640x360 -bufsize 2.0M -b:v 0.8M -maxrate:v 1.0M -keyint_min 50 -g 50 -r 25 \
    -c:a libvorbis -ar 44100 -ac 2 -b:a 192k \
    -f webm udp://127.0.0.1:5001
```
and

```
shaka-packager \
"input=udp://127.0.0.1:5001,stream_selector=video,init_segment=v360.webm,segment_template=v360_\$Number\$.webm,bandwidth=800000" \
  --profile live --single_segment=0 --dump_stream_info \
  --mpd_output ${DASH_PREFIX}/manifest.mpd
```

The packager reports
```
[1118/091808:INFO:demuxer.cc(60)] Initialize Demuxer for file 'udp://127.0.0.1:5001'.
[1118/091808:ERROR:demuxer.cc(99)] Not implemented reached in shaka::media::Status shaka::media::Demuxer::Initialize()
[1118/091808:ERROR:packager_main.cc(314)] Demuxer failed to initialize: 4 (UNIMPLEMENTED): Container not supported.
```

**Comment by kqyang** [comment]
Is shaka-packager started after ffmpeg or before ffmpeg? If it is the former, can you try starting shaka-packager first?

I think the problem is that ffmpeg only transmits the init-segment in the beginning of the stream; the init-segment contains the track information, which is necessary to setup the packaging.

**Comment by iSchluff** [comment]
If I start the packager first I get
```
[1118/200840:INFO:demuxer.cc(60)] Initialize Demuxer for file 'udp://127.0.0.1:5001'.
[1118/200847:ERROR:packager_main.cc(314)] Demuxer failed to initialize: 8 (PARSER_FAILURE): Cannot parse media file udp://127.0.0.1:5001
```
instead once the ffmpeg stream starts.

**Comment by kqyang** [comment]
I took a look at the output generated by ffmpeg. There were two tracks generated. However, the tracks element and the second track_entry element (for audio) indicate "unknown size".

```
tracks (unknown size)
  track_entry
    video
  track_entry (unknown size)
    audio
```

Right now, shaka packager does not handle unknown sizes except for Segment element and Cluster element: https://github.com/google/shaka-packager/blob/master/packager/media/formats/webm/webm_parser.cc#L752. They are needed as the size of these elements would not be known in live streaming case. But I don't understand why ffmpeg generates unknown size for "tracks" and "track_entry" elements, which can be computed easily during encoding.

An update is needed in either ffmpeg (to properly compute the size for tracks and track_entry elements) or shaka-packager (to support unknown size tracks / track_entry elements).

If you remove the audio output from transcoding, it should work, i.e.

```
ffmpeg -y -hide_banner -analyzeduration 10000 -i rtmp://foo/rtmp/bar \
  -map v:0 -map a:0 \
    -c:v libvpx -threads 4 -aspect 16:9 -pix_fmt yuv420p -deadline realtime -crf 10 \
    -s 640x360 -bufsize 2.0M -b:v 0.8M -maxrate:v 1.0M -keyint_min 50 -g 50 -r 25 \
    -an \
    -f webm udp://127.0.0.1:5001
```

**Comment by vaage** [comment]
@iSchluff is this still an issue for you? @kqyang do we have an action item for this issue?

**Comment by kqyang** [comment]
We should check if it is already fixed in ffmpeg. If not, we need to either fix the problem in ffmpeg or handle it in packager.

**Comment by vaage** [comment]
So I ran this again.

I used [this](http://peach.themazzone.com/durian/movies/sintel-1024-surround.mp4) copy of Sintel as input and ran these commands in parallel.
```
ffmpeg -y -hide_banner -analyzeduration 10000 -i sintel-1024-surround.mp4 -map v:0 -map a:0 -c:v libvpx -threads 4 -aspect 16:9 -pix_fmt yuv420p -deadline realtime -crf 10 -s 640x360 -bufsize 2.0M -b:v 0.8M -maxrate:v 1.0M -keyint_min 50 -g 50 -r 25 -c:a libvorbis -ar 44100 -ac 2 -b:a 192k -f webm udp://127.0.0.1:5001

packager "input=udp://127.0.0.1:5001,stream_selector=video,init_segment=v360.webm,segment_template=v360_\$Number\$.webm,bandwidth=800000" --profile live --single_segment=0 --dump_stream_info --mpd_output manifest.mpd
```

If I started the packager first, everything worked. If I started FFMPEG first I got:
```
[0302/151055:INFO:demuxer.cc(88)] Demuxer::Run() on file 'udp://127.0.0.1:5001'.
[0302/151055:INFO:demuxer.cc(160)] Initialize Demuxer for file 'udp://127.0.0.1:5001'.
[0302/151055:ERROR:demuxer.cc(204)] Not implemented reached in shaka::Status shaka::media::Demuxer::InitializeParser()
[0302/151055:ERROR:packager_main.cc(470)] Packaging Error: 4 (UNIMPLEMENTED): Container not supported.
```

I was using a debug local build of the packager based off our master branch and was using version 3.4.1-1 of FFMPEG.

@kqyang, since it works as long as you start the packager first, are we comfortable closing this issue?

**Comment by kqyang** [comment]
@vaage Which version of ffmpeg are you using?

**Comment by vaage** [comment]
Commit `033fa651055f6e8cc02844f86711bb8aa5ba8a13` ("Removed Old WebVtt Code") in master. I have one more commit after it.

**Comment by iSchluff** [comment]
Yeah, I can reproduce this works with ffmpeg-3.4 if the packager is started before ffmpeg.
