### ISSUE TITLE
Segments not generated for video but generated for audio?

### ISSUE THREAD

**Issue by ethanjyx** [google/shaka-packager#174]
Hi there, I am trying to generate DASH with 2 second segments with Shaka packager, here is the command I used:

`packager input=crf33.webm,stream=audio,output=try4audio.webm input=crf33.webm,stream=video,output=try4video.webm --profile on-demand --single_segment=false --segment_duration=2 --mpd_output try4.mpd`

After this command, I used mkvextract to inspect the cues inside the generated files.
mkvextract cues try4video.webm 0:try4videocues.txt
mkvextract cues try4audio.webm 0:try4audiocues.txt

try4videocues.txt shows 
`timecode=00:00:00.007000000 duration=- cluster_position=316 relative_position=-
`which means there is only one segment

try4audiocues.txt shows
```
timecode=00:00:00.000000000 duration=- cluster_position=430 relative_position=-
timecode=00:00:02.001000000 duration=- cluster_position=14673 relative_position=-
timecode=00:00:04.001000000 duration=- cluster_position=28017 relative_position=-
timecode=00:00:06.001000000 duration=- cluster_position=42038 relative_position=-
timecode=00:00:08.001000000 duration=- cluster_position=56074 relative_position=-
timecode=00:00:10.001000000 duration=- cluster_position=69678 relative_position=-
timecode=00:00:12.001000000 duration=- cluster_position=83888 relative_position=-

```

Looks like the segment information was not put into the video stream. When I load this dash manifest inside a player, it also does not load the video in segments. What is wrong here?

**Comment by kqyang** [comment]
```--single_segment``` should not be set to false. Can you try again with the below command:

```
packager input=crf33.webm,stream=audio,output=try4audio.webm input=crf33.webm,stream=video,output=try4video.webm --profile on-demand --segment_duration=2 --mpd_output try4.mpd
```

**Comment by ethanjyx** [comment]
Thanks for answering! Unfortunately I am still getting the same thing.

**Comment by kqyang** [comment]
I suspect that that there is only key frame in your content. By default, packager generates new segments/clusters only at GOP boundary. If there is only one key frame (the first frame), packager will only generate one cluster.

Can you extract key frames and verify? http://superuser.com/questions/885452/extracting-the-index-of-key-frames-from-a-video-using-ffmpeg

**Comment by ethanjyx** [comment]
You are right. There is only one key frame. Let me try with a video with more key frames.

**Comment by ethanjyx** [comment]
Yes! It is working now after I use a video with more key frames 👍 

Thanks @kqyang  :)
