### ISSUE TITLE
Crash while demuxing big buck bunny video.

### ISSUE THREAD

**Issue by rkuroiwa** [google/shaka-packager#175]
Revision: 9ed8303a06c315fd1fda8d10f0fc64931325000a

Repro steps:
1. Get "Standard 2D" 1080p 30 fps big buck bunny video. http://distribution.bbb3d.renderfarming.net/video/mp4/bbb_sunflower_1080p_30fps_normal.mp4
2. (optional) Rename it to bbb.mp4
3. $ ./packager 'in=bbb.mp4,stream=video,output=bbb_frag.mp4'

Result:
Packager crashes.

Expected:
No crash.

Other notes:
The crash is in BoxReader's destructor.
It looks like a double free on a pointer. When I watch children_.size() it is some really big number.

**Comment by kqyang** [comment]
There is another problem that input stream contains esds with object type of 0x6B and without DecoderSpecificInfo, which is not supported currently.

**Comment by rkuroiwa** [comment]
I will close this since the fix no longer crashes the process. If there is more work to enable parsing, it should be a separate issue.
