### ISSUE TITLE
HLS output chunk duration issue

### ISSUE THREAD

**Issue by Palethorn** [google/shaka-packager#179]
I've been playing with the source code and have created a quick and dirty patch for live profile with regards to issue #114, but I have a weird issue. For this kind of input stream:

> Input #0, mpegts, from 'udp://127.0.0.1:10000':
>   Duration: N/A, start: 19.773333, bitrate: N/A
>   Program 1 
>     Metadata:
>       service_name    : Service01
>       service_provider: FFmpeg
>     Stream #0:0[0x100]: Video: h264 (Constrained Baseline) ([27][0][0][0] / 0x001B), yuv420p, 720x576 [SAR 64:45 DAR 16:9], 25 fps, 25 tbr, 90k tbn, 50 tbc
>     Stream #0:1[0x101]: Video: h264 (Constrained Baseline) ([27][0][0][0] / 0x001B), yuv420p, 720x576 [SAR 64:45 DAR 16:9], 25 fps, 25 tbr, 90k tbn, 50 tbc
>     Stream #0:2[0x102](spa): Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 65 kb/s (clean effects)
>     Stream #0:3[0x103](dos): Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 55 kb/s (clean effects)

I have to specify exactly 8 seconds for segment_duration in shaka and GOP of 50 for FPS 25 for the segmenter to round up nicely, which of course produces chunks of duration 8 seconds. For example, if I set segment_duration to 10 in shaka packager, segmenter produces video chunks with duration of 20 seconds while audio chunks look OK. Re-sampling the audio in ffmpeg doesn't produce any different results. Setting the GOP to 250 frames on the transcoder with input/output FPS of 25, then telling shaka to produce 10s segments should work perfectly, but it doesn't. Same thing happens with VOD, but it's less noticeable. Any way to fix this?

**Comment by kqyang** [comment]
So

- Segment duration: 8 seconds, GOP: 50, FPS: 25, produces 8 seconds chunks

- Segment duration: 10 seconds, GOP: 50, FPS: 25, produces 20 seconds chunks?
That shouldn't happen, it may produce 12 seconds chunks though.

The current segmentation logic is to create a new segment when the accumulated duration >= specified segment duration. It is possible that there may be rounding error, e.g. the accumulated duration of 5 GOPS, could be slightly less than 10 seconds, so the segmentor has to wait for another GOP before generating the segments. We are planning to fix the problem in the next release. 

Here is a workaround you can try before it is fixed: if you want a segment duration of 10 seconds, set the segment duration to 10-0.1, i.e. 9.9.

**Comment by Palethorn** [comment]
Actually, segment duration: 10 seconds, GOP: 50, FPS: 25, does produce 12 seconds chunks.
I'll try your suggestion.

**Comment by Palethorn** [comment]
Tried your suggestion @kqyang. Audio chunks now have duration 9.920 and video chunks are 10.000. I'm guessing that this is good enough for now.

**Comment by Palethorn** [comment]
Hello,
We have encountered another issue. We are still testing live patch, and our stream stops after approximately hour and a half. Could the difference in chunk duration between video and audio be the cause? We have already addressed this issue here: #186

**Comment by kqyang** [comment]
Shaka-packager does not support live HLS. Do you have your own patch to support live packaging?

> our stream stops after approximately hour and a half.

What does it mean? The player stops playing? Does it resume if you restart the player? Do you see abnormal duration in generated manifests?

**Comment by Palethorn** [comment]
We have our own patch for live. Safari native player just stops without any error, but continues to refresh chunklists. Player resumes after refresh. I have inspected every request using mitmproxy around the time it stops and I see no abnormalities. Chunk durations seem OK, but audio chunks are always little shorter than video chunks, as I commented already.

**Comment by kqyang** [comment]
It is not possible to make audio chunks to have exact the same duration as video chunks, so I don't think it is the issue here.

Have you tried quicktime or other HLS players? They may give more meaningful errors when it fails.

Also, do you mind sharing your live patch, or possibly contribute your live change back to shaka-packager? It will help us debug the issue here.

**Comment by kqyang** [comment]
Close due to inactivities. Feel free to re-open it if there is still an issue.
