### ISSUE TITLE
OSError: [Errno 2] No such file or directory: '/Library/Developer/CommandLineTools/Platforms/MacOSX.platform/Developer/SDKs'

### ISSUE THREAD

**Issue by ChernyshovYuriy** [google/shaka-packager#180]
There is error:
```
OSError: [Errno 2] No such file or directory: '/Library/Developer/CommandLineTools/Platforms/MacOSX.platform/Developer/SDKs'
```
when perform
```
gclient sync
```

This is stack trace:
```
Traceback (most recent call last):
  File "./build/mac/find_sdk.py", line 90, in <module>
    print main()
  File "./build/mac/find_sdk.py", line 58, in main
    sdks = [re.findall('^MacOSX(10\.\d+)\.sdk$', s) for s in os.listdir(sdk_dir)]
OSError: [Errno 2] No such file or directory: '/Library/Developer/CommandLineTools/Platforms/MacOSX.platform/Developer/SDKs'
gyp: Call to 'python ./build/mac/find_sdk.py 10.10' returned exit status 1 while in /Users/yuriyc/Development/shaka_packager/src/packager/packager.gyp.
Error: Command '/usr/bin/python src/gyp_packager.py --depth=src/packager' returned non-zero exit status 1 in /Users/yuriyc/Development/shaka_packager
```
Mac OS Sierra 10.12.1 (16B2555)
Python 2.7.10

Path "/Library/Developer/CommandLineTools" contains Library/ and usr/ only.

**Comment by kqyang** [comment]
Do you have XCode installed on your system? Preferably XCode 7.3+.

**Comment by ChernyshovYuriy** [comment]
No ...
Installing now. Will inform about result.

**Comment by ChernyshovYuriy** [comment]
Ok,
Got it resolved by installing Xcode.
Thanks!
However, still not able to install it because of next issue:
```
________ running '/usr/bin/python src/gyp_packager.py --depth=src/packager' in '/Users/yuriyc/Development/shaka_packager'
Updating projects from gyp files...
gyp: Call to 'config/mac/find_curl_ca_bundle.sh' returned exit status 1 while in /Users/yuriyc/Development/shaka_packager/src/packager/third_party/curl/curl.gyp.
Error: Command '/usr/bin/python src/gyp_packager.py --depth=src/packager' returned non-zero exit status 1 in /Users/yuriyc/Development/shaka_packager
```

**Comment by kqyang** [comment]
The system is missing curl ca bundle, can you try this instruction: http://superuser.com/questions/247686/wheres-the-ca-cert-bundle-on-osx

**Comment by ChernyshovYuriy** [comment]
The answer is so ridiculous ...
**wget** was missing.
So, at least there is not a word about requirements, like Xcode and wget.
It was quite new MacBook without anything installed.

Now I am able to sync and doing ninja operation.

**Comment by kqyang** [comment]
Cool! Thanks for the finding! 

> So, at least there is not a word about requirements, like Xcode and wget.

True, we'll be adding more detailed instructions in README soon. It will hopefully make things easier in the future for the first time setups.
