### ISSUE TITLE
Question about the AES signing

### ISSUE THREAD

**Issue by derrickzecheng** [google/shaka-packager#182]
I am sorry to bother you guys :)

Hi, to the dear developer,
I am trying to use vlc package the video that I have like this, to a localhost server

vlc bbb.mp4 --sout '#transcode{vcodec=h264,scale=Auto}dp{mux=ts,dst=129.93.230.113:5003}'

And after that, I am using the shaka packager to cut that video into segment, and output it on my localhost

./packager 'input=udp://129.93.230.113:5003,stream=video,init_segment=/var/www/html/shaka/live-video.mp4,segment_template=/var/www/html/shaka/live-video-$Number$.mp4,bandwidth=2000000' --profile live --mpd_output /var/www/html/shaka/live.mpd

And I am using the MP4client player to play it like this 
MP4Client http://129.93.230.113/shaka/live.mpd

It does play, and the latency is a little bit. But it does play.

But when I use the 
./packager   'input=udp://129.93.230.113:5003,stream=video,init_segment=live-video.mp4,segment_template=live-video-$Number$.mp4,bandwidth=2000000' --profile live --mpd_output /var/www/html/shaka/live.mpd --enable_widevine_encryption --key_server_url "https://license.uat.widevine.com/cenc/getcontentkey/widevine_test" --content_id "3031323334353637" --signer "widevine_test" --aes_signing_key "1ae8ccd0e7985cc0b6203a55855a1034afc252980e970ca90e5202689f947ab9" --aes_signing_iv "d58ce954203b7c9a9a9d467f59839249" --crypto_period_duration 1800

It just doesn't play anything. I think it maybe because it is still under that signature, so cannot play.

Now I am wondering that is there any MP4 or Shaka player that can provide the verifying feature in order to match the AES signing feature, that built in the MP4 player, is there any recommandation?

**Comment by kqyang** [comment]
You need to use a HTML5/EME player and set license server url in the player properly. The license server for the above content is: https://license.uat.widevine.com/cenc/getcontentkey/widevine_test.

**Comment by derrickzecheng** [comment]
Thanks for your help! I am trying to use the Shaka-player!
