### ISSUE TITLE
where is the “base” folder 

### ISSUE THREAD

**Issue by FeiCao** [google/shaka-packager#187]
Hi, I can not find the “base” folder, look at the pic, where may I get these codes? thank you!
![code](https://cloud.githubusercontent.com/assets/12422206/21712050/64211666-d42d-11e6-8f50-fd10665ccb95.png)

**Comment by kqyang** [comment]
If you follow the instructions in https://github.com/google/shaka-packager and use gclient sync to populate the source, it should be available in packager/base directory.

**Comment by kqyang** [comment]
Closing this issue. Feel free to reopen it if you have more questions.
