### ISSUE TITLE
How can I inspect the file structure of DASH injected webM files?

### ISSUE THREAD

**Issue by ethanjyx** [google/shaka-packager#190]
After injecting DASH information, WebM files shall have the init chunk and index chunk for DASH, is this right? How can I inspect the structure of the WebM files to understand the position of these chunks in the file?

**Comment by kqyang** [comment]
> After injecting DASH information, WebM files shall have the init chunk and index chunk for DASH, is this right? 

Correct.

> How can I inspect the structure of the WebM files to understand the position of these chunks in the file?

You can find out the position of init chunk from initialization range in mpd and the position of index chunk from index range in mpd. 

As for the media chunks, you'll need to parse the index chunk (which is basically a cues element) to find out . You may also use an ebml viewer or mkv viewer to parse the elements in webm files.

Hope I have answered your questions. Feel free to re-open the issue if you have more questions.

**Comment by ethanjyx** [comment]
I wonder if it is possible to place the index chunk just next to init chunk? i.e make the ranges close to each other.

For example, <Initialization range="0-295" />, indexRange="296-400"

**Comment by kqyang** [comment]
That is what shaka-packager is doing now. Are you seeing a gap between init range and index range?

**Comment by ethanjyx** [comment]
Yes I am having something like this:

```
<?xml version="1.0" encoding="UTF-8"?>
<MPD
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns="urn:mpeg:DASH:schema:MPD:2011"
  xsi:schemaLocation="urn:mpeg:DASH:schema:MPD:2011"
  type="static"
  mediaPresentationDuration="PT12.013S"
  minBufferTime="PT1S"
  profiles="urn:webm:dash:profile:webm-on-demand:2012">
<Period id="0" start="PT0S" duration="PT12.013S" >
<AdaptationSet id="0" bitstreamSwitching="true" subsegmentAlignment="true" subsegmentStartsWithSAP="1">
<Representation id="v0"  mimeType="video/webm" codecs="vp9" width="1920" height="1080" bandwidth="2185736">
<BaseURL>dash_12sec.webm</BaseURL>
<SegmentBase
  indexRange="3374923-3375027">
<Initialization
  range="0-440" />
</SegmentBase>
</Representation>
</AdaptationSet>
<AdaptationSet id="1" bitstreamSwitching="true" subsegmentAlignment="true" subsegmentStartsWithSAP="1">
<Representation id="a1"  mimeType="audio/webm" codecs="vorbis" lang="eng" audioSamplingRate="48000" bandwidth="69157">
<BaseURL>12sec_audio.webm</BaseURL>
<SegmentBase
  indexRange="117637-117702">
<Initialization
  range="0-4389" />
</SegmentBase>
</Representation>
</AdaptationSet>
</Period>
</MPD>

```

Although I lost the command that created this. I am still having this issue for one build I have.

**Comment by kqyang** [comment]
It looks like you are using an old shaka-packager build. The index chunk used to be created in the end of the file after writing the chunks. It was updated in Sep 2016 to move index chunk before media chunks: https://github.com/google/shaka-packager/commit/97fc9828f01826e99e83469875870bc7f1a477c5.

Are you having trouble building latest shaka-packager? What is it?

**Comment by ethanjyx** [comment]
Thanks for the information! I will try building with another build and see how it goes.

**Comment by ethanjyx** [comment]
We were using v1.5.1, this seems to be the latest stable release, but it is without the change. Do you have a recommendded changeset that I should roll to?

**Comment by kqyang** [comment]
You may use ToT. I am going to release a new version some time this week from ToT.

**Comment by ethanjyx** [comment]
Thanks. For clarification, by ToT do you mean the latest commit of now?

**Comment by kqyang** [comment]
yes

**Comment by ethanjyx** [comment]
I am not sure if you were aware of this, but libwebm build rules are outdated https://github.com/google/shaka-packager/blob/master/packager/third_party/libwebm/libwebm.gyp#L16-L25

they seem to have been switched to cpp and hpp

**Comment by kqyang** [comment]
No, I don't see that they were updated: https://github.com/webmproject/libwebm/tree/master/mkvmuxer

**Comment by ethanjyx** [comment]
Hmmm not sure what is going on but when I was trying to build it downloaded a bunch of hpp and cpp files.

**Comment by ethanjyx** [comment]
Seems a lot of third party libraries need to be updated :) I am pushing for a new release here which would be greatly helpful. You mentioned we will have a new release this week, what is the ETA? :)

**Comment by kqyang** [comment]
Some time today!
