### ISSUE TITLE
Packager can't parse webm file with error "Unsupported display unit type 4"

### ISSUE THREAD

**Issue by sonaldev** [google/shaka-packager#192]
Hi,

I am trying to use the packager for preparing DASH on-demand profile manifest for progressive webm files. However, packager fails to parse my webm files. Following is the packager command I am using and the error message. I encoded my webm files using ffmpeg libvpx 1.6.1. Need your help in figuring out why packager thinks the display unit is 4. 

packager input=input.webm,stream=video,output=input_dash.webm --segment_duration=2 --mpd_output output.mpd

[0120/075918:INFO:demuxer.cc(58)] Initialize Demuxer for file 'input.webm'.
[0120/075918:ERROR:webm_video_client.cc(101)] Unsupported display unit type 4
[0120/075918:ERROR:packager_main.cc(311)] Demuxer failed to initialize: 8 (PARSER_FAILURE): Cannot parse media file input.webm

Please find a sample input.webm here. https://www.dropbox.com/s/4hhx3o1hs89f5q3/input.webm?dl=0

Thanks a ton for helping out!

I am using the latest build of shaka-packager. I can play the webm file on VLC and ffplay. Also, it appears that the display unit is set to 0 in the file.

**Comment by kqyang** [comment]
I checked the file. It indeed contains a value of 4 for the DisplayUnit (See the byte @ offset #1b8 or use any ebml viewer), which is not defined in the webm spec: https://www.webmproject.org/docs/container/#DisplayUnit.

How do you encode the file? You may need to check with ffmpeg to see why it is generating a display unit of 4.

**Comment by sonaldev** [comment]
Thanks Kongqun for looking into this! I used the following ffmpeg commands to encode the webm.

ffmpeg -i original.mp4 -c:v libvpx-vp9 -pass 1 -b:v 0 -crf 33 -r 30 -threads 8 -speed 4 -tile-columns 6 -frame-parallel 1 -g 60 -an -f webm -y /dev/null
ffmpeg -i original.mp4 -c:v libvpx-vp9 -pass 2 -b:v 0 -crf 33 -r 30 -threads 8 -speed 4 -tile-columns 6 -frame-parallel 1 -g 60 -auto-alt-ref 1 -lag-in-frames 25 -c:a libvorbis -b:a 64k -f webm -y input.webm

Let me know if you have any suggestions. I will follow up with the ffmpeg folks too.

**Comment by kqyang** [comment]
It is probably related to your source content. Looks like ffmpeg is not able to figure out the display aspect ratio, so it writes MATROSKA_VIDEO_DISPLAYUNIT_UNKNOWN (4) in DisplayUnit field: https://github.com/FFmpeg/FFmpeg/blob/e7dec52d4da7fad61f65529d5a396968e3dfe777/libavformat/matroskaenc.c#L1245. Either something wrong with ffmpeg or the content.

I'll close this issue here.  (but feel free to reopen / update this issue if you have more findings)

**Comment by sonaldev** [comment]
Encoding with ffmpeg using video filter setsar=1:1 fixed this error.

**Comment by kqyang** [comment]
Cool. Thanks for the update.
