### ISSUE TITLE
Support for HLS with fragmented MP4

### ISSUE THREAD

**Issue by rounce** [google/shaka-packager#193]
Now that Apple have added fragmented MP4 along with MPEG-CENC support to HLS for iOS 10 (https://developer.apple.com/streaming/examples/advanced-stream-fmp4.html), are there plans to expand the shaka packager to generate a HLS manifest for the content as well?

**Comment by kqyang** [comment]
Yes, it is on our road map! We are planning to work on in the coming months.

**Comment by rounce** [comment]
Thanks. It is possible to see your roadmap somewhere?
P.S. I has found out the hls with fMP4 is able to generate https://github.com/axiomatic-systems/Bento4/blob/master/Source/Python/utils/mp4-dash.py So far with him I will experiment.

**Comment by kqyang** [comment]
> It is possible to see your roadmap somewhere?

That is a good question. Right now it is not open to public. I am thinking of publicise it on github. Will need to go through some process...

**Comment by kqyang** [comment]
It is now supported with https://github.com/google/shaka-packager/commit/4891d9a6bf96f3655a7df4b908f96cc036a8c51b

Right now only multi-segment mp4 is supported. Support for single-segment mp4 will be added in Q2.

**Comment by rounce** [comment]
Hello.
"Support for single-segment mp4 will be added in Q2." Is the timeline still valid?

**Comment by kqyang** [comment]
That is delayed due to resource issue. We are working on it right now. It should be done in early Q3. The issue is tracked in #183. Feel free to subscribe to the issue.
