### ISSUE TITLE
How to create webm encrypted with Clear Key for shaka-player?

### ISSUE THREAD

**Issue by nampdn** [google/shaka-packager#195]
Hi, I'm trying to use packager/webm_crypt to create a single audio/video webm encrypted to play with [shaka-player Clear Key](http://shaka-player-demo.appspot.com/docs/api/tutorial-drm-config.html). But I can't find any document of how to get the KID, and Key to force shaka-player to decrypt and play it without using any license server.
I've checked out the shaka-packager's API and the README but I got nothing for webm encryption.

**Comment by kqyang** [comment]
You can package a clear key webm using fixed key encryption:

```
packager in=input.webm,stream=video,out=output.webm --enable_fixed_key_encryption --key <key in hex> --key_id <key id in hex> --mpd_output output.mpd
```

Let us know if there is more questions.

**Comment by nampdn** [comment]
Awesome, thank you a lots. I can encrypt webm and play it in shaka-player.
Can you provide a little bit more document of how to encrypt multiple files at a time with different key id & key pairs and then output the encrypted file with mpd?

For example: I have 4 webm files, and video should use different key than audio:

- sintel-video-1k.webm
- sintel-video-2k.webm
- sintel-audio-en.webm
- sintel-audio-fr.webm

**Comment by kqyang** [comment]
"Fixed key encryption" does not support multiple key id / key pairs right now. You can workaround the problem by packaging video and audio separately then merge the mpds manually.

**Comment by nampdn** [comment]
Got it. Thanks you.

**Comment by nampdn** [comment]
@kqyang I have gave a try to package and merge manually, but I meet a small problem, my video has silent about 5 seconds in the initial of the clip. When I combine the audio together with video, the frame is not synchronized between sound and picture. How is the best way to merge mpd files together with audio synced?

**Comment by kqyang** [comment]
The video and audio should be synchronized before doing packaging. If not, you can use ffmpeg to shift the timestamps.
