### ISSUE TITLE
CBCS Encryption of Audio Samples

### ISSUE THREAD

**Issue by sivarajendranaidu** [google/shaka-packager#197]
I had created the CBCS Encrypted Sample for Audio Only Stream using Shaka Packager
As CBCS for Audio needs to follow 9.7 Whole-block Full Sample Encryption; In CBC Encryption if the input sample is not integral multiple of 16 byte block the trailing bytes needs be unencrypted.
Do we need to signal them as clear data as with Sub-Sample Encryption? or Just merge the encrypted block with unencrypted trailing bytes.
Please provide your inputs.

**Comment by kqyang** [comment]
No, they don't need to be signaled as clear data using Sub-Sample encryption. The unencrypted trailing bytes should be merged with the encrypted block. That is what we do in shaka-packager and I think that is what is indicated in the spec.

**Comment by kqyang** [comment]
I am closing this bug. Feel free to re-open it if you have more questions.

**Comment by sivarajendranaidu** [comment]
Hi,
I had created a video only sample with cbcs encryption mode using shaka packager.
I noticed that each video sample had the clear bytes equal to offset from frame_begin to video slice header.
I noticed the BytesOfProtectedData were not rounded to encrypt block size (16).
With reference to 9.6.2	Example of pattern encryption applied to a video NAL unit
"Note: Pattern encryption is represented by vertical black and white lines representing a pattern of encrypted cipher blocks followed by clear Blocks. The pattern spans the protected range of a Subsample specified by BytesOfProtectedData, and approximately spans the video data following the slice header. Byte or Block alignment may require that the start of BytesOfProtectedData is not at the first bit of slice data, but some number of bits or bytes following that. Multiple Subsamples may be mapped to a single NAL and multiple clear NALs to a single Subsample in the ‘cens’ scheme, but a single Subsample per VCL NAL may be required for the ‘cbcs’ scheme."

Do we need to adjust the clear bytes such that BytesOfProtectedData is multiple of 16?
If Video Slice data is less than 160 bytes (minimum bytes required for 1:9 pattern encryption) do we need to encrypt or leave it clear?

Please provide your inputs.

**Comment by kqyang** [comment]
For encryption scheme 'cbc1', 'cens', BytesOfProtectedData shall be multiple of 16 bytes.

However, for encryption scheme 'cbcs', BytesOfProtectedData is not required to be multiple of 16 bytes. Instead, the spec says:

> 10.4 ‘cbcs’ AES-CBC subsample pattern encryption scheme
> The first complete byte of video slice data (following the video slice header) SHALL begin a single Subsample protected byte range indicated by the start of BytesOfProtectedData, which extends to the end of the video NAL.

As for your second question: if the video slice data is more than 16 bytes, the first 16 bytes will be encrypted, otherwise it will be left in clear.

See this paragraph from the spec:

> 9.6 Pattern encryption
> If the last Block pattern in a Subsample is incomplete, the partial pattern SHALL be followed until truncated by the BytesOfProtectedData size and any partial crypt_byte_block SHALL remain unencrypted.

Hope this answers your question.

**Comment by sivarajendranaidu** [comment]
Thanks a lot kqyang
With reference to  9.7 Whole-block Full Sample Encryption for Audio Samples using cbcs

> _In whole-block full sample encryption, the entire sample is protected. Every sample is encrypted starting at offset 0 (there is no unprotected preamble) up to the last 16-byte boundary, leaving any trailing 0-15 bytes in the clear. The IV is reset at every sample._ 

I have two queries namely

- What does "The IV is reset at every sample" mean ? Do we need to encrypt every sample with different IV? But In case of 'cbcs' we use constant IV instead of Per_Sample_IV will this statement hold good?

-When we were using 'cbcs' [10.4	‘cbcs’ AES-CBC subsample pattern encryption scheme ] for audio Do we need have crypt_block as 10 and skip_block as 0 and have tenc box version as 1 instead of 0?

Please provide your inputs.

**Comment by kqyang** [comment]
> What does "The IV is reset at every sample" mean ? Do we need to encrypt every sample with different IV? But In case of 'cbcs' we use constant IV instead of Per_Sample_IV will this statement hold good?

It means the IV is reset back to the initial value (the constant iv). It only applies to 'cbcs'.

> When we were using 'cbcs' [10.4	‘cbcs’ AES-CBC subsample pattern encryption scheme ] for audio Do we need have crypt_block as 10 and skip_block as 0 and have tenc box version as 1 instead of 0?

It is not clearly defined in the spec. I think either options below should be fine:
(1) version = 1, crypt_block = 1, skip_block = 0 (this is what shaka-packager is doing)
(2) crypt_block = 0 and skip_block = 0; version can be either 0 or 1
