### ISSUE TITLE
Support for hardware accelerated AES

### ISSUE THREAD

**Issue by kqyang** [google/shaka-packager#198]
Right now we use low level AES_xxx apis when performing encryption and decryption (https://github.com/google/shaka-packager/blob/master/packager/media/base/aes_encryptor.cc), which is not able to take advantage of hardware accelerated AES-NI instructions.

We should study and look into the feasibility of switching to EVP apis which will use AES-NI instructions automatically when it is available.

**Comment by ronalcelaya** [comment]
Hi,
I'm trying to add EVP api to aes_encryptor.cc
Until now, using cbcs with EVP is working but is not using aesni (I'm using perf top).
Do I have to build boringssl or shaka-packager in a specific way in order to use aesni?

**Comment by ronalcelaya** [comment]
Hi @kqyang Thanks for answer. I'm using CentOS 7.6
Great. I'm going to update to lastest stable boringssl. I think using AES-NI could improve my pipeline.

**Comment by kqyang** [comment]
@ronalcelaya Have you tried updating boringssl? Let us know if there is any problem.

> Even using EVP?

Yes.
