### ISSUE TITLE
Setting the -webm_subsample_encryption flag when using fixed key encryption seems to have no effect

### ISSUE THREAD

**Issue by fallaciousreasoning** [google/shaka-packager#199]
I'm trying to create a subsample encrypted webm file, preferably clearkey encrypted so I can test subsample encryption in Firefox.

The command I attempted was
```
packager input=sintel.webm,stream=video,output=encrypted_sintel.webm -enable_fixed_key_encryption -key 808B9ADAC384DE1E4F56140F4AD76194 -key_id 2cdb0ed6119853e7850671c3e9906c3c -webm_subsample_encryption
```
However, when reading the file in nestegg, the encrypted signal byte was still 00000001 (indicating encryption but no partitioning) instead of 00000011 (partitioning and encryption) and the file successfully played (in a build of FF that does not support subsample encryption).

**Comment by kqyang** [comment]
Is it VP9 or VP8? We do subsample encryption for VP9 only. 

Also, it is enabled by default - if you are using v1.6.0, so there is no need to add "-webm_subsample_encryption" flag.

**Comment by fallaciousreasoning** [comment]
Ah okay, that might have been my problem. Thanks for getting back to me.
