### ISSUE TITLE
Did shaka packager support SegmentList ?

### ISSUE THREAD

**Issue by markviu** [google/shaka-packager#200]
Hi there,

Did shaka packager support segment list like following? If so, how to generate it by it.?

     <SegmentList duration="6000" timescale="1000">
          <Initialization range="28-848" sourceURL="b60f_w_1.vpv.mp4"/>
          <SegmentURL media="b60f_w_1.vpv.mp4" mediaRange="849-146889"/>
          <SegmentURL media="b60f_w_1.vpv.mp4" mediaRange="146890-265213"/>
          <SegmentURL media="b60f_w_1.vpv.mp4" mediaRange="265214-389673"/>
          <SegmentURL media="b60f_w_1.vpv.mp4" mediaRange="389674-499131"/>
          <SegmentURL media="b60f_w_1.vpv.mp4" mediaRange="499132-625317"/>

**Comment by kqyang** [comment]
No. That is not supported. Any reason you want SegmentList instead of SegmentTemplate?

**Comment by markviu** [comment]
Sorry to reply you late due to travel. 
Will SegmentList help the player to switch on the beginning of each chunk more precisely and smoothly like hls chunks? In other words, can the player do the smoothly profile change without it ?

Thanks,

**Comment by kqyang** [comment]
Yes, it can also be achieved with SegmentTemplate. And with SegmentTemplate, the manifest looks cleaner and the manifest size is also much smaller.

**Comment by kqyang** [comment]
Closed due to in-activities. Feel free to re-open it if you have more questions.
