### ISSUE TITLE
Error with generated mpd file

### ISSUE THREAD

**Issue by vedavidhbudimuri** [google/shaka-packager#201]
While using the mpd file generated by packager player throwing below error.
Must have @mediaPresentationDuratio on MPD or an explicit @duration on the last period.

I used below commands to generate the mpd file:

packager input=/media/720p.mp4,stream=audio,output=audio.mp4          input=/media/720p.mp4,stream=video,output=video.mp4          --mpd_output example.mpd --generate_static_mpd

packager   'input=audio.mp4,stream=audio,init_segment=audio_init.mp4,segment_template=audio-$Number$.mp4'  'input=video.mp4,stream=video,init_segment=video_init.mp4,segment_template=video-$Number$.mp4'--mpd_output live_static.mpd --generate_static_mpd

**Comment by kqyang** [comment]
Thanks for reporting the problem. Can you attach the problematic mpd(s)?

**Comment by kqyang** [comment]
We analyzed problem and discovered that there were indeed a problem with live static mpd. The problem should be fixed in [v1.6.1](https://github.com/google/shaka-packager/releases/tag/v1.6.1). Please give it a try and let us know if it does not work.

**Comment by vedavidhbudimuri** [comment]
Is the docker image updated?

**Comment by kqyang** [comment]
Yes, docker tag release-v1.6.1: https://hub.docker.com/r/google/shaka-packager/builds/bgddyg36hgxptxy23dauudd/
