### ISSUE TITLE
Player unable to read subtitles

### ISSUE THREAD

**Issue by vedavidhbudimuri** [google/shaka-packager#204]
Tried to generate a mpd file using below command

packager 'input=vp.mp4,stream=audio,init_segment=audio.mp4,segment_template=audio-$Number$.mp4' 'input=vp.mp4,stream=video,init_segment=video.mp4,segment_template=video-$Number$.mp4' 'input=value_proposition.vtt,stream=subtitle,init_segment=vp_english_init.vtt,segment_template=vp_english-$Number$.vtt,language=eng' --mpd_output vp.mpd --generate_static_mpd

But player is unable to read my subs.

**Comment by kqyang** [comment]
Can you attach the generated manifest and the subtitle files? Also, which player are you using?

**Comment by vedavidhbudimuri** [comment]
Issue is with the player. Sorry for the trouble
