### ISSUE TITLE
Received non valid mp4 file while decrypting wmv

### ISSUE THREAD

**Issue by ff40** [google/shaka-packager#206]
There is a problem using shaka-packager with the result of decrypting the file, in the form of broken frames. Testing video is performed using ffmpeg, the command: 'ffmpeg -i filename -f null -'. As a result, produces errors of the form (the part of the log):

[H264 @ 0x2948a80] concealing 1334 DC, 1334 AC, 1334 MV errors in B frame
[H264 @ 0x2990000] concealing 1452 DC, 1452 AC, 1452 MV errors in P frame
[H264 @ 0x29d7580] concealing 1302 DC, 1302 AC, 1302 MV errors in B frame
[H264 @ 0x2a1eb00] concealing 1195 DC, 1195 AC, 1195 MV errors in P frame
[H264 @ 0x2848700] Reference 3> = 2
[H264 @ 0x2848700] error while decoding MB April 23, bytestream 631
[H264 @ 0x2848700] concealing 1302 DC, 1302 AC, 1302 MV errors in B frame
[H264 @ 0x27a07c0] Reference 4> = 4
[H264 @ 0x27a07c0] error while decoding MB 16 0, bytestream 1890
[H264 @ 0x27a07c0] concealing 1452 DC, 1452 AC, 1452 MV errors in P frame
[H264 @ 0x281eb80] concealing 1300 DC, 1300 AC, 1300 MV errors in B frame
[H264 @ 0x2901500] top block unavailable for requested intra mode at 1 0

The problem itself is shown as a gray screen. To decrypt the used version shaka_packager 1.3.1, 1.5.1, 1.6.1, the result of all of them is about the same. Please indicate on the possible solutions to the problem, or the reason for which some content can not be decrypted.

**Comment by kqyang** [comment]
@ff40 I assume you are talking about wvm files. Can you attach the source content or send the source content to me if it cannot be shared publicly (you can find my email address in [CONTRIBUTORS](https://github.com/google/shaka-packager/blob/master/CONTRIBUTORS) file) and describe how you decrypt it?

Thanks.

**Comment by ff40** [comment]
@kqyang Link to the file wvm:
https://drive.google.com/file/d/0BzsuGeYN_c1lOW40Tmo4RW5Wa1k/view?usp=sharing
Command to decrypt(pattern): 
shaka_packager --enable_widevine_decryption input=input.wvm,stream=0,output=output.mp4 --key_server_url=https://license.widevine.com/cenc/getcontentkey/_signer_ --signer=_signer_ --aes_signing_key=_aes_signing_key_ --aes_signing_iv=_aes_signing_iv_

**Comment by kqyang** [comment]
@ff40 Thanks for the file. What's your signer's name? (I don't need signing key and iv)

**Comment by ff40** [comment]
@kqyang I write to you on said email. Notify if the letter was lost or you do not find. The letter was sent from ff40532@gmail.com

**Comment by kqyang** [comment]
Thanks. Btw, do you see problems on all video you have or only a particular video?

**Comment by ff40** [comment]
@kqyang The problem is not observed at all video. Mostly the problem occurs after decoding video that was encoded in 2015. It should be noted that we have no problem with the playback of the video (wvm) before decrypting.

**Comment by kqyang** [comment]
The problem is caused by varying SPS/PPS in the stream. However, in the current code, we don't expect SPS/PPS to change from frame to frame. We will have a fix soon.

**Comment by ff40** [comment]
Thanks for your help.
