### ISSUE TITLE
Widevine encrypting without server call.

### ISSUE THREAD

**Issue by salmoro** [google/shaka-packager#207]
I am testing EZDRM for Widevine and the way their service seems to work is that you do an http call to their server and it'll respond by providing the info necessary for encryption (Content_ID, Key, KeyId, PSSH, etc.).

With my limited knowledge and understanding, it appears that this is not compatible with shaka-packager's method for Widevine encryption which includes acquiring the keys (which uses a specific server request protocol).

Assuming this is correct, are there any suggestions to how I can encrypt my content with shaka packager and EZDRM's provided data? I figure if there's no simple solution, I can ultimately stand up a server in the middle that will serve shaka packager's request in the manner it desires (assuming I can find out what exactly the protocol is). This is obviously far from ideal and would love to avoid this. 

Any ideas?
Thanks,
Sal

**Comment by kqyang** [comment]
> I am testing EZDRM for Widevine and the way their service seems to work is that you to an http call to their server and it'll respond by providing you the info necessary for encryption (Content_ID, Key, KeyId, PSSH, etc.).

That is actually similar to what we do. Do you know the format of their request and response? You could update https://github.com/google/shaka-packager/blob/master/packager/media/base/widevine_key_source.cc - probably add another ezdrm_key_source for their request and response format.

Another option is to use fixed key: you can request key, key_id, pssh from ezdrm, then provide the information to shaka packager: --enable_fixed_key_encryption --key_id xxx --key xxx --pssh xxx

Let us know if you have more questions.

**Comment by salmoro** [comment]
Thanks for the prompt response.

Their request is three fields: `u: username, p: password [,c: content_id]` as described [here](https://wvm.ezdrm.com/ws/LicenseInfo.asmx?op=GenerateKeys).

Their response is as follows:
![chrome_2017-03-02_17-57-57](https://cloud.githubusercontent.com/assets/20197680/23530915/f2977a24-ff71-11e6-9908-951baea30e8e.png)


If I were to use fixed key encryption, serverUrl and contentId are not included. Does this mean I have to deal with that separately when it comes to decryption (at playback) as opposed to letting the player figure it out from the information stored in the headers?

**Comment by kqyang** [comment]
The content id should be available in the pssh generated by ezdrm. So no need to worry about it.

We don't actually store the server url anywhere in the media file so you'll need to tell the player the server url anyway.

**Comment by salmoro** [comment]
Oh perfect! Thanks for the clarifications. This is super helpful. Thanks very much.
