### ISSUE TITLE
what is the best way to feed data to packager from a different source, e.g. tuner

### ISSUE THREAD

**Issue by anikzad** [google/shaka-packager#208]
Hi, 
I was wondering what is the best way to feed data at real-time to the packager? for example if we have a 20 Mbps muxed transport, what is the easiest way to feed the data as it is received or read?

Thanks in advance,

**Comment by kqyang** [comment]
The easiest way would be to implement the media::File interface. Here is an example with data fed from UDP: https://github.com/google/shaka-packager/blob/master/packager/media/file/udp_file.cc. Let us know if you have questions with that.

**Comment by anikzad** [comment]
Thanks let me try this.

**Comment by kqyang** [comment]
Close due to inactivities. Feel free to re-open it if there is more questions.
