### ISSUE TITLE
Packager can't parse file with error "Box '' run to EOS"

### ISSUE THREAD

**Issue by rounce** [google/shaka-packager#209]
packager input=fd08dd412a87c4c.mp4,stream=video,output=fd08dd412a87c4c.m4v input=fd08dd412a87c4c.mp4,stream=1,output=fd08dd412a87c4c_1.m4a --mpd_output fd08dd412a87c4c.mpd
..
[0311/001950:ERROR:box_reader.cc(119)] Not implemented reached in bool shaka::media::mp4::BoxReader::ReadHeader(bool *)Box '' run to EOS.
[0311/001950:ERROR:packager_main.cc(506)] Packaging Error: 8 (PARSER_FAILURE): Cannot parse media file /mnt/media5/video/2abfe7fef0a41b1/fd08dd412a87c4c.mp4

This video was obtained using ffmpeg:  -vcodec libx264 -coder 0 -level 30 -subq 7 -qcomp 0.6 -trellis 2 -i_qfactor 0.71 -qmin 10 -qmax 51 -qdiff 4 -me_method hex -me_range 16 -sc_threshold 0 -partitions all -refs 1 -flags +loop+mv4 -movflags faststart"

MP4Box and Bento4 fragmanter read this file without any issues.
It turns out I can not use the skaka packager for video transcoded by ffmpeg?

[the file](http://media5.krasview.ru/video/2abfe7fef0a41b1/fd08dd412a87c4c.mp4)

**Comment by kqyang** [comment]
The file you attached is actually not a valid mp4 file. There are an extra 734657 bytes of data in the end does not belong to any box. It will work if you remove it, for example, using this command: 
```
head -c 258099769 test.mp4 > test2.mp4
```

Then run packager again on `test2.mp4`.

> It turns out I can not use the shaka packager for video transcoded by ffmpeg?

The video transcoded by ffmpeg is supported in shaka-packager. For this particular video, if it is transcoded using the above command, then I think there is a bug somewhere in ffmpeg, results in an invalid mp4 file.
