### ISSUE TITLE
Packager truncating WebM video files

### ISSUE THREAD

**Issue by paullewis** [google/shaka-packager#210]
## Issue

I'm finding that WebM files are being truncated by version 924d6d4693-release. In particular I have a 720p WebM video that is truncated from 36,336,882 bytes to 35,648,887. The 1080p version of the same video is truncated even more severely: 72,773,711 bytes to 35,649,836 bytes.

## Repro
Grab the following files:
1. [720p WebM Video](https://storage.googleapis.com/biograf-video-files/temp/v-0720p-1800k-libvpx-vp9.webm)
2. [Vorbis video](https://storage.googleapis.com/biograf-video-files/temp/a-eng-0128k-libvorbis.webm)

```bash
# macOS bash
stat -f%z v-0720p-1800k-libvpx-vp9.webm # 36336882
```

And then run:
```bash
packager input=a-eng-0128k-libvorbis.webm,stream=audio,output=a-eng-0128k-libvorbis.webm \
         input=v-0720p-1800k-libvpx-vp9.webm,stream=video,output=v-0720p-1800k-libvpx-vp9.webm \
         --mpd_output example.mpd
```

```bash
# macOS bash
stat -f%z v-0720p-1800k-libvpx-vp9.webm # 35648887
```

## System info
**Operating System**: 10.12.2 macOS Sierra and Ubuntu 14.04 trusty
**FFMpeg**: 3.2.2
**libvpx**: 1.6.1
**packager**: 924d6d4693-release

**Comment by paullewis** [comment]
If I don't have the packager overwrite the original files, but rather say, for example output=video.webm, everything works just fine.

**Comment by kqyang** [comment]
Thanks for reporting the problem and including the detail repro instructions! Working on a fix now.
