### ISSUE TITLE
Possible integer overflow in StreamInfo::set_duration()

### ISSUE THREAD

**Issue by sylt** [google/shaka-packager#214]
## System info
**Operating System**: Ubuntu 14.04 trusty
**Shaka Packager Version**: c223bc9-release

## Issue and steps to reproduce the problem

When I tried to segment a WebM file with a long duration, I got a mediaPresentationDuration attribute in my MPD manifest that was about int64_t(-1), but written as floating point (it was something like 1.844e+13).

According to libwebm (using the mkvparser_sample program), my WebM stream header looks like this:

		 libwebm version: 1.0.0.30
			    EBML Header
		EBML Version		: 1
		EBML MaxIDLength	: 4
		EBML MaxSizeLength	: 8
		Doc Type		: webm
		Pos			: 43

			   Segment Info
		TimeCodeScale		: 1000000 
		Duration		: 4096000000000
		Duration(secs)		: 4096.000
		Track Name		: NULL
		Muxing App		: Lavf57.41.100
		Writing App		: Lavf57.41.100
		Position(Segment)	: 55
		Size(Segment)		: 51598901

This duration will be (correctly) parsed by the WebM parser in the shaka-packager, but in WebMMediaParser::ParseInfoAndTracks(), where we should set the parsed duration to our AudioStreamInfo or VideoStreamInfo using StreamInfo::set_duration(), there will in this case be an integer overflow.

The reason is that the duration accepted by StreamInfo::set_duration() is int, as opposed to int64_t or uint64_t (which by the way is the internal representation for the duration in the StreamInfo class). Once I exchanged that to uint64_t, my mediaPresentationDuration was alright again.

Thank you for having a look! :)

**Comment by kqyang** [comment]
That is definitely a bug. Thanks for catching it! Since you have a fix already, would you like to submit a pull request to fix the issue? See https://github.com/google/shaka-packager/blob/master/CONTRIBUTING.md on how to contribute.

**Comment by kqyang** [comment]
@sylt Thanks for fixing the bug!
