### ISSUE TITLE
Support on Windows OS

### ISSUE THREAD

**Issue by kqyang** [google/shaka-packager#22]

**Comment by kqyang** [comment]
With docker, we can now use edash-packager on Windows: https://github.com/google/edash-packager#using-docker-for-testingdevelopment

We will still work on supporting Windows directly, but with low priority.

**Comment by gggin** [comment]
'python generate_version_string.py' returned exit status 1.

**Comment by kqyang** [comment]
Yah, there are still some problems with Windows build. Unfortunately, we don't have resource working on it right now.

**Comment by gggin** [comment]
tks

**Comment by kqyang** [comment]
Addressed in https://github.com/google/shaka-packager/commit/336ea5cb34b607d2c292e1b2a826faafd6f514bc
