### ISSUE TITLE
State of -webm-subsample-encryption since 3d7635d5d

### ISSUE THREAD

**Issue by sylt** [google/shaka-packager#220]
In 3d7635d5d, I saw that a new encryption handler was integrated. Good stuff! :) However, since that change, I can't see that the option webm_subsample_encryption does anything any more. It might be that I have missed something though (and if so, my apologies).

One would think that packager_test.py would have caught this, but I would say that there was a problem with the initial commit (db92c9a) in this regard: The tests that were added for WebM subsample encryption only tested what happened for -webm-subsample-encryption=true (i.e., the default value). There was not a corresponding test (as far as I can see) for the output of -webm_subsample_encryption=false. If this is indeed a behavior change, maybe that's why this wasn't caught.

This is by the way not that important for what I use shaka-packager for, it is simply an observation I've made when looking through the code. I thought that if the flag isn't used any more, it might just as well be removed.

Thanks for having a look :)

**Comment by kqyang** [comment]
Good catch. We were talking about deprecating the flag, but I forgot that it has not been deprecated yet and forgot that we still have that flag present. We'll fix it.
