### ISSUE TITLE
Cleanup old segments

### ISSUE THREAD

**Issue by pryg-skok** [google/shaka-packager#223]
## System info
**Operating System**: Ubuntu 16.04.1 xenial
**Shaka Packager Version**: 437d48f-release

## Issue and steps to reproduce the problem

Packager generates segments and everything works fine, but I wonder why packager has no option for keep only live window: so it should remove old chunks?

**Packager Command**: packager 'input=udp://127.0.0.1:5000?reuse=1,stream=1,init_segment=audio.mp4,segment_template=audio-$Number$.mp4,bandwidth=64000' 'input=udp://127.0.0.1:5000?reuse=1,stream=0,init_segment=video-lq.mp4,segment_template=video-lq-$Number$.mp4,bandwidth=400000' 'input=udp://127.0.0.1:5000?reuse=1,stream=2,init_segment=video-hq.mp4,segment_template=video-hq-$Number$.mp4,bandwidth=1500000' --segment_duration 6 --minimum_update_period 6 --suggested_presentation_delay 18 --fragment_duration 6 --time_shift_buffer_depth 36 --mpd_output live.mpd

What is the expected result?
Add option for cleanup old segments which accept max available time for segment. After this timeout segment will be removed.

What happens instead?
There is no such option or maybe I can't find it.

**Comment by pryg-skok** [comment]
It seems that question about removing old segments was already asked two years ago. Have you planned to do this? If it not, may I ask - why such easy task should be offloaded to external routine?

**Comment by kqyang** [comment]
We did not implement it earlier because there were some concerns on doing this internally in packager, e.g. the content serving server may not be the same server doing the content packaging; the contents could be better managed outside of packager.

That said, I agree that there should be an option/flag to do that inside the packager. We'll add this to our Q2 planning :smile: 

What I am thinking now is to add a boolean flag, e.g. _--remove_old_segments_: a segment is considered old if it falls outside the live window, i.e. outside _time_shift_buffer_depth_ plus max mpd update delay: _minimum_update_period_.

**Comment by pryg-skok** [comment]
Nice plan! :)
When you think about this option please take into account that there is a case when "live window" may not be as same as chunk availability. Because HLS client may start their playing (as [recommended](https://tools.ietf.org/html/draft-pantos-http-live-streaming-07#section-6.3.3) in old version of draft -> widely used): "the client SHOULD NOT choose a segment which starts less than three target durations from the end of the Playlist file". The problem here that we can't control it and we should use short playlists to be close to real time.

In same time we may need to store this chunks on CDN or somewhere else and these subsystems may be on load and not have enough time (which equals to "live window" time) to download and store chunk.

So sometimes it's better to separate "live window" duration and chunk availability, because one need short playlists and on the other side chunk should be available longer.

**Comment by kqyang** [comment]
>  "the client SHOULD NOT choose a segment which starts less than three target durations from the end of the Playlist file".

I am not super clear on this. Let's say we have a playlist like this:

```
   ...
   #EXTINF:8,
   101.ts
   #EXTINF:8,
   102.ts
   #EXTINF:8,
   103.ts
   #EXTINF:8,
   104.ts
   #EXTINF:8,
   105.ts
   #EXTINF:8,
   106.ts
```
Does it mean that the client can only start on 104.ts or before but not 105.ts and 106.ts?

If my understanding is correct, then it won't be a problem for us as we will only remove the segments after it is removed from the manifest.

**Comment by pryg-skok** [comment]
> Does it mean that the client can only start on 104.ts or before but not 105.ts and 106.ts?

Well it depends... For our knowledge - yes it is. The behavior of most tested devices and platforms is like this. Also there are devices that start their playback from start of playlist, i.e. 101.ts
Also we need to generate larger playlists if we need more time longer available and this is not big problem, but not necessary.

> If my understanding is correct, then it won't be a problem for us as we will only remove the segments after it is removed from the manifest.
So, basically, yes, it's not a problem for most of cases, but also such solution (playlist length * chunk durations == chunk availability time) maybe can be replaced here for more general. So it's up to you, actually. )

**Comment by rmoe-picodigital** [comment]
Just wanted to put a +1 on having this feature in the shaka packager, my company also requires this functionality, and having it in the packager would be great.

**Comment by GScharfofMars** [comment]
+1
