### ISSUE TITLE
Error while playback of shaka packager

### ISSUE THREAD

**Issue by shreyasreedhar** [google/shaka-packager#229]
## System info
**Shaka Packager Version**: <e.g. v1.6.1, commit SHA etc>

## Issue and steps to reproduce the problem
There is just a screeching noise at times and the manifest and segments get downloaded . The playback shows buffering time. but the audio content doesnt play 

**Packager Command**:

Extra steps to reproduce the problem?
(1)I am trying to play a widevine manifest file but while playing back i am getting 
the below error 
+ audio/mp4; codecs="mp4a.40.2" is supported  player.js:191:3
MKSC Object { audioCapabilities: Array[1], videoCapabilities: undefined, initDataTypes: undefined, distinctiveIdentifier: "optional", persistentState: "optional", sessionTypes: Array[1] }  eme_manager.js:292:5
onEncrypted_ Uint8Array [ 0, 0, 0, 153, 112, 115, 115, 104, 0, 0, 143 more… ] Object { type: "encrypted", initDataType: "cenc", initData: Uint8Array[153] }  eme_manager.js:535:3
Starting each stream from 82904.3793444  stream_video_source.js:1566:3
onSessionMessage_ message { target: MediaKeySession, isTrusted: true, messageType: "license-request", message: ArrayBuffer, currentTarget: MediaKeySession, eventPhase: 2, bubbles: false, cancelable: false, defaultPrevented: false, composed: false, timeStamp: 1493710038202000 }  eme_manager.js:651:3
Stream audio/mp4: stream has started.  stream.js:700:3
All Streams have completed startup!  stream_video_source.js:1641:3
Timestamp correction -4.00003045797348e-7  stream_video_source.js:1709:3
Player error error { target: null, isTrusted: false, detail: Error, eventPhase: 0, bubbles: true, cancelable: false, defaultPrevented: false, composed: false, timeStamp: 1493710038568000, cancelBubble: false, NONE: 0 }  app.js:884:3
	app.onPlayerError_ http://emmy9.casa.umass.edu/shaka-player/app.js:884:3
	shaka.util.FakeEventTarget.prototype.recursiveDispatch_ http://emmy9.casa.umass.edu/shaka-player/lib/util/fake_event_target.js:167:9
	shaka.util.FakeEventTarget.prototype.recursiveDispatch_ http://emmy9.casa.umass.edu/shaka-player/lib/util/fake_event_target.js:180:5
	shaka.util.FakeEventTarget.prototype.dispatchEvent http://emmy9.casa.umass.edu/shaka-player/lib/util/fake_event_target.js:145:10
	shaka.media.EmeManager.prototype.requestLicense_/<
What is the expected result?

What happens instead?

<Please attach the input files.>
<Please provide any additional information below.>

**Comment by kqyang** [comment]
@shreyasreedhar Can you describe the problem in more detail? What content are you trying to play? Which version of packager are you using to package the content? Is there a sample output we can use to verify? Thanks.

**Comment by kqyang** [comment]
Close due to inactivity. Feel free to re-open it if needed.
