### ISSUE TITLE
Playready Content Creation Support

### ISSUE THREAD

**Issue by sivarajendranaidu** [google/shaka-packager#230]
## System info
**Operating System**: Centos 7
**Shaka Packager Version**: Latest Version from GIT (packager version 1e2da22-debug)
Needed help to create Playready Content using fixed KEY,KEY_ID, LA_URL using Shaka Packager.
Can you please provide Command example for playready. Is our shaka packager created content is playable in shaka player?
Please provide your inputs

**Comment by kqyang** [comment]
Here is a sample command you can use:

```
./packager  'input=sd.mp4,stream=video,output=pr-fixed-key-sd.mp4' 'input=audio.mp4,stream=audio,output=pr-fixed-key-audio.mp4' --clear_lead=0 --mpd_output pr-fixed-key.mpd --enable_playready_encryption --playready_key_id <key id in hex>
 --playready_key <key in hex>
```

We receive some reports that there are some problems with playready in the latest code right now. If you are seeing problems, use an old commit instead: https://github.com/google/shaka-packager/commit/24b0e3031aad86e904a72e737bcc0b3dee151b54

**Comment by kqyang** [comment]
Close due to inactivities. Feel free to re-open it if anything comes up.
