### ISSUE TITLE
udp input timeout not working Not implemented reached

### ISSUE THREAD

**Issue by arpu** [google/shaka-packager#231]
## System info
**Operating System**:  fedora 25
**Shaka Packager Version**:  1.6 linux bin 

## Issue and steps to reproduce the problem

**Packager Command**:
./packager-linux  'input=udp://127.0.0.1:8888?reuse=0&timeout=8,stream=video,init_segment=live-video-sd.mp4,segment_template=live-video-sd-$Number$.mp4'  --mpd_output live.mpd

Extra steps to reproduce the problem?
(1)
(2)

What is the expected result?
packager should closed after 5 sec timeout 
What happens instead?
packager not starting
[0504/225632:INFO:demuxer.cc(58)] Initialize Demuxer for file 'udp://127.0.0.1:8888?timeout=5'.
[0504/225632:ERROR:demuxer.cc(97)] Not implemented reached in shaka::media::Status shaka::media::Demuxer::Initialize()
[0504/225632:ERROR:packager_main.cc(311)] Demuxer failed to initialize: 4 (UNIMPLEMENTED): Container not supported.

works without timeout=5

**Comment by kqyang** [comment]
It is timeout in microseconds. You should specify 5000000 if you want the timeout to be 5 seconds.

For the error above, it is expected as if the timeout is set to 5 us, the packager could not receive anything, so it just errors out.

I am closing this bug. Feel free to re-open it if you are still seeing problems.
