### ISSUE TITLE
Encrypt mp4box dash chunks

### ISSUE THREAD

**Issue by aaani** [google/shaka-packager#232]
Apologies for not following the template. 

I am using mp4box for creating m4s Dash chunks from mp4 files. Is there anyway I can Widevine encrypt m4s files. 

```
➜  shaka-packager packager input=hd-00001.m4s,stream=video,output=encrypted-hd-00001.m4s --enable_widevine_encryption --key_server_url "https://license.uat.widevine.com/cenc/getcontentkey/XX-MASKED-XX" --content_id "3031323322223637" -aes_signing_iv="XX-MASKED-XX" -aes_signing_key="XX-MASKED-XX" --signer="XX-MASKED-XX"
[0508/172721:ERROR:stream_descriptor.cc(170)] Unable to determine output format for file encrypted-hd-00001.m4s
```

**Comment by kqyang** [comment]
That is not supported right now (we are thinking of adding the support some time later this year).

Is there any reason that you don't use Shaka Packager to create m4s Dash chunks from mp4 files directly? Then you don't need mp4box any more.

**Comment by sempi** [comment]
@kqyang Is that what you have in mind?
[chunk1.mp4,chunk2.mp4,chunk3.mp4] -(shaka-packager)-> [init.mp4,chunk1.m4s,chunk2.m4s,chunk3.m4s]

Can this approach then be used when initially only [chunk1.mp4] is available to create [init.mp4,chunk1.m4s]. Then [chunk2.mp4] becomes available and [chunk2.m4s] is created. And so on. The client would use a live playlist so it can fetch one chunk after the other as time progresses.

**Comment by kqyang** [comment]
@sempi Is chunk1.mp4, chunk2.mp4 ... what you have before feeding to mp4box? One thing you can do right now is to feed the chunks one by one to shaka packager, you will get [init.mp4, chunk1.m4s] from [chunk1.mp4] and [init.mp4, chunk2.m4s] from [chunk2.mp4] ... and so on; all init.mp4 should match if the codec configuration does not vary from chunk to chunk and you provide the same parameters to shaka packager. (You'll also need to set the fragment duration to be larger than your chunk duration to avoid producing multiple chunks from shaka packager)

Does that work for you?

**Comment by aaani** [comment]
So I followed the steps above but my init files for chunks don't match. They are almost the same but there are a few bits that are different.
Also if I created a playlist from the outcome of above with init.mp4 for the first chunk as the init file for the playlist, but shaka plays back the first chunk only and then stop.

**Comment by aaani** [comment]
@kqyang Right, we have chunk1.mp4, chunk2.mp4..., chunkN.mp4 and our goal is to widevine encrypt these chunks and playback in the shaka player. Please advice what the best practice is for our use case.

**Comment by kqyang** [comment]
@aaani The init segments should match with the only differences in timestamps (if decoder config is not varying).

Can you share the source chunks and also output playlist including output init segments and output media segments? You can email to me if it cannot be shared publicly. (you can find my email address in CONTRIBUTORS file)

**Comment by kqyang** [comment]
@aaani Thanks for the sample contents.

I thought the input chunks had proper timestamps, but it is not. From your samples, all the chunks started at 0. We do not alter timestamps in Shaka Packager. We may open up APIs to allow users to do custom processing in the future, but for now, you'll have to use some other mechanism to update the timestamps (e.g. use ffmpeg).

Here is a simple script to do packaging and update BaseMediaDecoderTime in the output chunks. It should work for your test contents. Note that this is only meant to be a workaround and it only works if all chunks have the same initialization data and similar durations. You should fix the timestamps in your source contents if possible.

```
#!/bin/sh

set -e

for index in 0 1 2 3
do
packager \
  in=hd-0000${index}.mp4,stream=video,init_segment=hd-init.mp4,segment_template=hd-\$Number%05d\$-fragmented.mp4 \
  --generate_static_mpd --mpd_output hd.mpd
mv hd-init.mp4 hd-init-${index}.mp4
mv hd-00001-fragmented.mp4 hd-0000${index}-fragmented-temp.mp4
mv hd.mpd hd-${index}.mpd
done

MEDIA_TIME_SCALE=90000
SEGMENT_DURATION=2

for index in 0 1 2 3
do
mv hd-0000${index}-fragmented-temp.mp4 hd-0000${index}-fragmented.mp4
# Update base media decode time.
printf "000094: %08x" $((index * MEDIA_TIME_SCALE * SEGMENT_DURATION)) | xxd -r - hd-0000${index}-fragmented.mp4
done

mv hd-init-0.mp4 hd-init.mp4
```
