### ISSUE TITLE
Demuxer failed to initialize: 8 (PARSER_FAILURE)   webm vp9

### ISSUE THREAD

**Issue by arpu** [google/shaka-packager#234]
## System info
**Operating System**: centos 7.3
**Shaka Packager Version**: version v1.6.2-6b98f0d-release-

## Issue and steps to reproduce the problem
packer input from mkfifo with webm vp9/opus 
does not work 

works with ffmpeg
output from test with ffmpeg 
Input #0, matroska,webm, from 'mkfifos/4GkN_2SaN1X':
  Metadata:
    ICY-PUB         : 0
    ICY-METADATA    : 1
    ICY-NAME        : mehome_360
    ENCODER         : Lavf57.71.100
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0(eng): Video: vp9 (Profile 0), 1 reference frame, yuv420p(tv, progressive, left), 3840x2160, SAR 1:1 DAR 16:9, 24 fps, 24 tbr, 1k tbn, 1k tbc (default)
    Side data:
      spherical: equirectangular (0.000000/0.000000/0.000000) 
    Stream #0:1(eng): Audio: vorbis, 48000 Hz, stereo, fltp (default)

**Packager Command**:

Extra steps to reproduce the problem?
(1)
(2)

What is the expected result?
demux webm with vp9 and vorbis/opus audio from mkfifo 
What happens instead?
[0518/014315:INFO:demuxer.cc(58)] Initialize Demuxer for file 'mkfifos/4GkN_2SaN1X'.
[0518/014324:ERROR:packager_main.cc(311)] Demuxer failed to initialize: 8 (PARSER_FAILURE): Cannot parse media file mkfifos/4GkN_2SaN1X

<Please attach the input files.>
<Please provide any additional information below.>

**Comment by kqyang** [comment]
Can you describe more details of the problem? For example, where is the input from? What is the packager command line you are using? It will be great if you can share a full repro instruction.

**Comment by arpu** [comment]
hi i think i have the same problem described here https://github.com/google/shaka-packager/issues/172
i need to ask if i can upload the test video

**Comment by kqyang** [comment]
Definitely! You can upload test test video to any public storage (e.g. Google drive) and share the link here or email to this mailing list: shaka-packager-issues@google.com. Thanks.

**Comment by arpu** [comment]
ok first i will try git version from  shaka-packager maybe this helps

**Comment by kqyang** [comment]
Close due to inactivities. Feel free to re-open it if anything comes up.
