### ISSUE TITLE
Generate content with many bitrate available

### ISSUE THREAD

**Issue by Pierpaolo1992** [google/shaka-packager#236]
Hi, i'm using shaka packager in order to create DRM-based DASH content. When i create encrypted content, for example with the following command:

`packager input=Face-Off.mp4,stream=audio,output=Face-Off-Audio.mp4 input=Face-Off.mp4,stream=video,output=Face-Off-Video.mp4 --profile on-demand --enable_widevine_encryption --key_server_url "https://license.uat.widevine.com/cenc/getcontentkey/widevine_test" --content_id "3031323334353637" --signer "widevine_test" --aes_signing_key "1ae8ccd0e7985cc0b6203a55855a1034afc252980e970ca90e5202689f947ab9" --aes_signing_iv "d58ce954203b7c9a9a9d467f59839249" --mpd_output Face-Off.mpd`

The created Face-Off.mpd contains only has only one `<Representation>` for each `<AdaptationSet>`: is there only one bitrate available for my content? If yes, this shoud not be correct because of adaptive nature of DASH. Am i right?

I've seen that in shaka-packager there is a `bandwidth `flag that specifies the bit rate of the specific tracks. I've seen that there is no chances to create an mpd with many bitrate value (and so many `<Representation>` tag. How does Shaka-Player manage the situation in which the estimated available bandwitdh is lesser than segment bitrate?

**Comment by kqyang** [comment]
Shaka Packager does not do transcoding, so you'll need to transcode your contents to different bitrates outside to packager, which can be achieved with FFmpeg. 

As for bandwidth flag, you can use that to fine-tune what appears in the manifest. If you are not sure about the bandwidth, just skip it and packager will calculate the bandwidth internally, which should work well unless the bitrate varies significantly from segment to segment.

**Comment by kqyang** [comment]
Closing this bug. Feel free to re-open it if you have more questions.
