### ISSUE TITLE
HLS segment template error

### ISSUE THREAD

**Issue by vijaykumarchettiar** [google/shaka-packager#238]
## System info
**Operating System**:  Ubuntu 14.04 LTS
**Shaka Packager Version**: v1.6.2

## Issue and steps to reproduce the problem

**Packager Command**:

 ./packager input=http://xxxxxxxxxxxx/hls/Teleshopping-1495600849/Teleshopping-149560084910M.m3u8,stream=video,segment_template=Teleshopping-149560084910M_$Number$.ts,playlist_name=Teleshopping-1495600849.m3u8 --hls_master_playlist_output="master.m3u8"  --hls_base_url="http://xxxxxxxxxxxx/hls/"  --enable_widevine_encryption --key_server_url "https://license.uat.widevine.com/cenc/getcontentkey/widevine_test"  --content_id "3031323334353637" --signer "widevine_test"  --aes_signing_key "xxxxxxxxxxxx" --aes_signing_iv "xxxxxxxxxxxx"

Extra steps to reproduce the problem?
(1)
(2)

What is the expected result?
The given input should be encrypted using signing IV, signing key and license url and store into the server.
What happens instead?
getting the below error 
[0525/074417:ERROR:muxer_util.cc(50)] SegmentTemplate: '$' should appear in pairs.
[0525/074417:ERROR:packager_main.cc(252)] ERROR: segment template with 'Teleshopping-149560084910M_$.ts' is invalid.

<Please attach the input files.>
<Please provide any additional information below.>
Please confirm the above syntax is correct or any additional parameter to be add.

**Comment by kqyang** [comment]
I suspect `$` is removed by bash.

Can you try enclose the parameter in `''` or escape `$`, e.g. something like this, 

./packager 'input=http://xxxxxxxxxxxx/hls/Teleshopping-1495600849/Teleshopping-149560084910M.m3u8,stream=video,segment_template=Teleshopping-149560084910M_$Number$.ts,playlist_name=Teleshopping-1495600849.m3u8' --hls_master_playlist_output="master.m3u8" --hls_base_url="http://xxxxxxxxxxxx/hls/" --enable_widevine_encryption --key_server_url "https://license.uat.widevine.com/cenc/getcontentkey/widevine_test" --content_id "3031323334353637" --signer "widevine_test" --aes_signing_key "xxxxxxxxxxxx" --aes_signing_iv "xxxxxxxxxxxx"

**Comment by vijaykumarchettiar** [comment]
thanks it's executes with the enclose the parameters in single quotes. However the below error comes.

Demuxer::Run() on file 'http://xxxxxxxxxx/hls/Antaryami-1495675149/Antaryami-1495675149.m3u8'.
[0525/083354:INFO:demuxer.cc(158)] Initialize Demuxer for file 'http://xxxxxxxxxx/hls/Antaryami-1495675149/Antaryami-1495675149.m3u8'.
[0525/083354:ERROR:packager_main.cc(544)] Packaging Error: 5 (FILE_FAILURE): Cannot open file for reading http://xxxxxxxxxx/hls/Antaryami-1495675149/Antaryami-1495675149.m3u8

i am able to play this url vlc or any other player. But packager command say it  can't open the url. Is that source (input) content should be available within same server where the packager installed and runs.

thanks in advance.

**Comment by kqyang** [comment]
Sorry for not spotting it earlier. Shaka Packager does not support "http" as input or output. Only local file and UDP are supported right now.

**Comment by vijaykumarchettiar** [comment]
thanks, i got execute the command successfully using udp as source. However i only get the result TS segment files and that even without encryption. The master.m3u8 and player.m3u8 file doesn't generate. I have given the IV, Key and license get url correctly.

What could be problem?

**Comment by kqyang** [comment]
Live HLS is not supported yet, see #114. We are actively working on it - we are targeting to have this supported this month. Sorry for not making it clear earlier.

**Comment by vijaykumarchettiar** [comment]
that means it should record it for VOD from udp to hls segments. that case what's the flag in the packager command for VOD instead of live.

**Comment by kqyang** [comment]
There is no way to generate a VOD stream from UDP, which is a live source.

**Comment by vijaykumarchettiar** [comment]
Is it MPD generation support for both Live and VOD from UDP input? please let me know, so that we move with MPD for now and later when the live hls support updated in the shaka packager.

**Comment by kqyang** [comment]
Yes, DASH MPD generation is supported for UDP input.

**Comment by vijaykumarchettiar** [comment]
One more question,
what if the STB box (android) rooted? will the CDM will function after the rooting of the box?

**Comment by kqyang** [comment]
Yes, android devices can be unlocked to allow users to install custom system images and it does not affect the content security.  Content keys and secure data path are enforced in a trusted execution environment (TEE). TEE code can not be modified even if the device is unlocked/rooted.

**Comment by vijaykumarchettiar** [comment]
Wetek core 2 Android 6.1 STB box - is it supported by Widevine CDM?

**Comment by kqyang** [comment]
Yes.

**Comment by kqyang** [comment]
Close due to inactivities. Feel free to re-open it or file a new issue if there are still questions.

**Comment by vijaykumarchettiar** [comment]
Hello support,
is live hls support enabled and updated in the repository?

**Comment by kqyang** [comment]
Not yet. Will land this week.

**Comment by kqyang** [comment]
Live HLS is now supported in master: b4aa34b.
