### ISSUE TITLE
widevine fixed key decryption command run successfully with wrong key

### ISSUE THREAD

**Issue by astroyang** [google/shaka-packager#240]
## System info
**Operating System**: macOS Sierra
**Shaka Packager Version**: packager version 655fe7b-release

## Issue and steps to reproduce the problem

**Packager Command**:
packager input=xxx.mp4,stream=audio,output=xxx_decrypt.mp4 --enable_fixed_key_decryption --key_id=xxx --key=xxx

What is the expected result?
The key provided is wrong so I would expect the command to fail. Is this expected? How can I detect if the key is not correct, or the result file is not valid(apart from playing back)?

What happens instead?

```
[0530/090524:INFO:demuxer.cc(58)] Initialize Demuxer for file 'xxx.mp4'.
[0530/090524:INFO:demuxer.cc(170)] Demuxer::Run() on file 'xxx.mp4'.
[0530/090524:INFO:single_segment_segmenter.cc(90)] Update media header (moov) and rewrite the file to 'xxx_decrypt.mp4'.
[0530/090525:INFO:mp4_muxer.cc(166)] MP4 file 'xxx_decrypt.mp4' finalized.
Packaging completed successfully.
```

**Comment by kqyang** [comment]
The content is encrypted using common encryption, i.e. using AES-CTR, which comes down to a bunch of XOR operations. Thus the decryption operation itself will always succeed. So unfortunately, there is no way to know if a given key is correct or not without trying to decode or analyze the decrypted content. 

It is possible to implement a verification / sanity check after decryption to check if the decrypted media sample (I assume it is AAC for your case) is still a valid AAC frame. Let us know if you have any ideas.

You may also just feed the decrypted output to FFmpeg or another similar tool to check if the content can be decoded.
