### ISSUE TITLE
Not able to do Widevine with "cbc1"

### ISSUE THREAD

**Issue by atoztoa** [google/shaka-packager#243]
## System info
**Operating System**: Ubuntu 16
**Shaka Packager Version**: packager version 19be04e-release

## Issue and steps to reproduce the problem

**Packager Command**:

`packager   input=big_buck_bunny.mp4,stream=audio,output=big_buck_bunny_audio_wv.mp4   input=big_buck_bunny.mp4,stream=video,output=big_buck_bunny_video_wv.mp4   --enable_widevine_encryption   --key_server_url "https://license.uat.widevine.com/cenc/getcontentkey/widevine_test"   --content_id "3031323334353637"   --signer "widevine_test"   --aes_signing_key "1ae8ccd0e7985cc0b6203a55855a1034afc252980e970ca90e5202689f947ab9"   --aes_signing_iv "d58ce954203b7c9a9a9d467f59839249"   --mpd_output big_buck_bunny_vod_wv.mpd   --protection_scheme 'cbc1'`

What is the expected result?

CBC encrypted content.

What happens instead?

```
WARNING: availability_time_offset is deprecated and ignored.
[0608/170142:INFO:demuxer.cc(88)] Demuxer::Run() on file 'big_buck_bunny.mp4'.
[0608/170142:INFO:demuxer.cc(158)] Initialize Demuxer for file 'big_buck_bunny.mp4'.
[0608/170142:ERROR:box_definitions.cc(623)] Not implemented reached in virtual bool shaka::media::mp4::SampleDescription::ReadWriteInternal(shaka::media::mp4::BoxBuffer *)SampleDecryption type 0 is not handled. Skipping.
[0608/170142:ERROR:box_definitions.cc(2065)] Not implemented reached in virtual bool shaka::media::mp4::MediaInformation::ReadWriteInternal(shaka::media::mp4::BoxBuffer *)
[0608/170142:ERROR:box_definitions.cc(623)] Not implemented reached in virtual bool shaka::media::mp4::SampleDescription::ReadWriteInternal(shaka::media::mp4::BoxBuffer *)SampleDecryption type 0 is not handled. Skipping.
[0608/170142:ERROR:box_definitions.cc(2065)] Not implemented reached in virtual bool shaka::media::mp4::MediaInformation::ReadWriteInternal(shaka::media::mp4::BoxBuffer *)
[0608/170142:INFO:single_segment_segmenter.cc(89)] Update media header (moov) and rewrite the file to 'big_buck_bunny_audio_wv.mp4'.
[0608/170142:INFO:mp4_muxer.cc(209)] MP4 file 'big_buck_bunny_audio_wv.mp4' finalized.
[0608/170142:INFO:single_segment_segmenter.cc(89)] Update media header (moov) and rewrite the file to 'big_buck_bunny_video_wv.mp4'.
[0608/170142:INFO:mp4_muxer.cc(209)] MP4 file 'big_buck_bunny_video_wv.mp4' finalized.
Packaging completed successfully.
```
This doesn't play in Shaka Player.

Also, I see that Google server only returns "key" for the content, no IV is returned.

`{
   "status":"OK",
   "drm":[
      {
         "type":"WIDEVINE",
         "system_id":"edef8ba979d64acea3c827dcd51d21ed"
      }
   ],
   "tracks":[
      {
         "type":"SD",
         "key_id":"Gc9JFLHkWmaILWfxzUj70g==",
         "key":"B0BKMJ2dsLUBYysSyMMIAQ==",
         "pssh":[
            {
               "drm_type":"WIDEVINE",
               "data":"EhAZz0kUseRaZogtZ/HNSPvSEhAiQO/mAT9XL65IqQOgfa5SEhBTeoB50+FdoK6BLsrWskf+EhCrQRXgqH1R/Z4rblX8w0HWEhB+bw+HeSBSUb/3KfRxabEjGg13aWRldmluZV90ZXN0IgwwMTIzNDU2N2UwMDBIscaJmwY="
            }
         ]
      },
      {
         "type":"HD",
         "key_id":"IkDv5gE/Vy+uSKkDoH2uUg==",
         "key":"vHa+FF/K5KxCU0sFgIAPSw==",
         "pssh":[
            {
               "drm_type":"WIDEVINE",
               "data":"EhAZz0kUseRaZogtZ/HNSPvSEhAiQO/mAT9XL65IqQOgfa5SEhBTeoB50+FdoK6BLsrWskf+EhCrQRXgqH1R/Z4rblX8w0HWEhB+bw+HeSBSUb/3KfRxabEjGg13aWRldmluZV90ZXN0IgwwMTIzNDU2N2UwMDBIscaJmwY="
            }
         ]
      },
      {
         "type":"UHD1",
         "key_id":"U3qAedPhXaCugS7K1rJH/g==",
         "key":"YGpJNiT4h1418FJ7ZGua4g==",
         "pssh":[
            {
               "drm_type":"WIDEVINE",
               "data":"EhAZz0kUseRaZogtZ/HNSPvSEhAiQO/mAT9XL65IqQOgfa5SEhBTeoB50+FdoK6BLsrWskf+EhCrQRXgqH1R/Z4rblX8w0HWEhB+bw+HeSBSUb/3KfRxabEjGg13aWRldmluZV90ZXN0IgwwMTIzNDU2N2UwMDBIscaJmwY="
            }
         ]
      },
      {
         "type":"UHD2",
         "key_id":"q0EV4Kh9Uf2eK25V/MNB1g==",
         "key":"LeiWIjbMwWc/spWH66zIyg==",
         "pssh":[
            {
               "drm_type":"WIDEVINE",
               "data":"EhAZz0kUseRaZogtZ/HNSPvSEhAiQO/mAT9XL65IqQOgfa5SEhBTeoB50+FdoK6BLsrWskf+EhCrQRXgqH1R/Z4rblX8w0HWEhB+bw+HeSBSUb/3KfRxabEjGg13aWRldmluZV90ZXN0IgwwMTIzNDU2N2UwMDBIscaJmwY="
            }
         ]
      },
      {
         "type":"AUDIO",
         "key_id":"fm8Ph3kgUlG/9yn0cWmxIw==",
         "key":"jmTEknxzu78FmN2FZP6WQQ==",
         "pssh":[
            {
               "drm_type":"WIDEVINE",
               "data":"EhAZz0kUseRaZogtZ/HNSPvSEhAiQO/mAT9XL65IqQOgfa5SEhBTeoB50+FdoK6BLsrWskf+EhCrQRXgqH1R/Z4rblX8w0HWEhB+bw+HeSBSUb/3KfRxabEjGg13aWRldmluZV90ZXN0IgwwMTIzNDU2N2UwMDBIscaJmwY="
            }
         ]
      }
   ]
}`

**Comment by kqyang** [comment]
Which browser are you using? I could be wrong but I don't think there is any browser supports 'cbc1' encryption scheme right now.

> Also, I see that Google server only returns "key" for the content, no IV is returned.

Google server does not return IV, which is randomly generated inside packager instead.

**Comment by atoztoa** [comment]
Using Chrome.

If the IV is randomly generated by packager, then how would the client get this info?

**Comment by kqyang** [comment]
Chrome does not support 'cbc1'. You need to use a platform that supports 'cbc' encryption modes.

It is encoded in the mp4 container. If you are interested in how it is encoded, you can read 23001-7: Common encryption in ISO base media file format.

**Comment by atoztoa** [comment]
Are you saying the IV is part of the mpd? Or the actual media segments?

**Comment by kqyang** [comment]
In the actual media segments.

**Comment by atoztoa** [comment]
OK, and the player supporting CBC will use the value from the segment to decrypt?

**Comment by kqyang** [comment]
Yes.

**Comment by atoztoa** [comment]
So, is this the first block which will be used as IV?

**Comment by kqyang** [comment]
No, the IV is put in in 'tenc' box (if contant across samples) or 'senc' (if varies across samples). Check out 23001-7: Common encryption in ISO base media file format for details.

**Comment by atoztoa** [comment]
Kool, got it. Then what about TS packaging?

**Comment by atoztoa** [comment]
Which player supports CBC? I tried ExoPlayer, shows garbled video.

**Comment by kqyang** [comment]
They are probably still working on it (I could be wrong though). You may want to file an issue / question to ExoPlayer. Feel free to include me in the issue.

**Comment by atoztoa** [comment]
Sorry for the cross posting, how do I do TS packaging for Widevine?

**Comment by kqyang** [comment]
Here is an example. It uses SAMPLE-AES by default, which is not supported in Chrome either.

packager \  'input=input.mp4,stream=video,segment_template=output$Number$.ts,playlist_name=video_playlist.m3u8' \
'input=input.mp4,stream=audio,segment_template=output_audio$Number$.ts,playlist_name=audio_playlist.m3u8,hls_group_id=audio,hls_name=ENGLISH' \
  --hls_master_playlist_output="master_playlist.m3u8" \
  --hls_base_url="http://localhost:10000/"  \
--enable_widevine_encryption \
--key_server_url "https://license.uat.widevine.com/cenc/getcontentkey/widevine_test" \
--content_id "3031323334353637" \
--signer "widevine_test" \
--aes_signing_key "1ae8ccd0e7985cc0b6203a55855a1034afc252980e970ca90e5202689f947ab9" \
--aes_signing_iv "d58ce954203b7c9a9a9d467f59839249"

**Comment by atoztoa** [comment]
Can't we do DASH with TS?

**Comment by kqyang** [comment]
No supported right now.

**Comment by atoztoa** [comment]
What about playback? Do we have support for playing DASH TS?

**Comment by kqyang** [comment]
I don't know if there is any player supporting DASH TS.

**Comment by atoztoa** [comment]
Thank you.
