### ISSUE TITLE
Feature request: DVR support for live stream

### ISSUE THREAD

**Issue by mardu** [google/shaka-packager#244]
Most of the common packagers today are supporting live stream DVR feature. Is there any plans to add DVR support for Shaka-packager?

**Comment by kqyang** [comment]
We already support adjusting buffer depth (--time_shift_buffer_depth). Is there anything else needed for DVR support?

**Comment by mardu** [comment]
Thank you for the quick answer. We will test it and let you know if it works.

**Comment by kqyang** [comment]
Close due to inactivities. Feel free to re-open it if anything comes up.
