### ISSUE TITLE
Cannot play with clear key encrypted mp4-dash live stream

### ISSUE THREAD

**Issue by sonysuqin** [google/shaka-packager#247]
**Operating System**: RHEL6.3
**Shaka Packager Version**: 1.6.3

I use follow command to produce mp4-dash stream.

packager 'input=1.mp4,stream=video,init_segment=1_v_seg-0.mp4,segment_template=1_v_seg-$Number$.mp4' 'input=1.mp4,stream=audio,init_segment=1_a_seg-0.mp4,segment_template=1_a_seg-$Number$.mp4' --mpd_output 1_seg_e.mpd --segment_duration 10

Then I feed 1_seg_e.mpd to a simple player demo base on shaka-player,it played success.
When I encrypt the stream with fixed key using follow command:

packager 'input=1.mp4,stream=video,init_segment=1_v_seg-0.mp4,segment_template=1_v_seg-$Number$.mp4' 'input=1.mp4,stream=audio,init_segment=1_a_seg-0.mp4,segment_template=1_a_seg-$Number$.mp4' --mpd_output 1_seg_e.mpd --segment_duration 10 --enable_fixed_key_encryption --key "15161718191a1b1c1d1e1f2021222324" --key_id "202122232425262728292a2b2c2d2e2f"

The same player demo failed to play this stream.

What wrong with it?

[sk.html.txt](https://github.com/google/shaka-packager/files/1123738/sk.html.txt)
[myapp.js.txt](https://github.com/google/shaka-packager/files/1123739/myapp.js.txt)

**Comment by kqyang** [comment]
I don't think the keys you put in the drm config is correct. It should be:

```
      clearKeys: {
        'ICEiIyQlJicoKSorLC0uLw==': 'FRYXGBkaGxwdHh8gISIjJA==',
      }
```

The padding "==" is part of the base64 string, which should not be omitted.

**Comment by sonysuqin** [comment]
Ok,I found the problem,after I change the keyid and key in my js file from base64 string to plain hex string,it play success.
Thank you all the way.

**Comment by kqyang** [comment]
You are right. Should be hex string there. Glad you found out that.
