### ISSUE TITLE
Cannot print variable's value in gdb.

### ISSUE THREAD

**Issue by sonysuqin** [google/shaka-packager#248]
**Operating System**: RHEL6.3
**Shaka Packager Version**: 1.6.3

I'm reading code of shaka-packager,now I wan't to debug the code using gdb,but I found I can't print all variable's value,is it normal or there's something wrong with my build?

My build operation followed:
https://github.com/google/shaka-packager

Except that glibc version of my system is 2.12,but building shaka-packager needs glibc 2.15,in order not to impact the system,I used a standalone  glibc 2.15 version and ran follow build command:
LD_PRELOAD=/data/hezhen/glibc-2.15/lib/libc-2.15.so ninja -C out/Debug
It built success.
When run shaka-packager with gdb,some info output like:
Missing separate debuginfos, use: debuginfo-install glibc-2.12-1.149.el6_6.5.x86_64

I don't much about ninja,how can I solve this problem to show variables in gdb?

**Comment by kqyang** [comment]
It is not related to ninja. You are just missing debug-info packages. Try: https://access.redhat.com/solutions/1506273

**Comment by sonysuqin** [comment]
@kqyang 
It might not be that problem,I've written a simple test code on the same machine,compiled with g++, it also output that warning when debugging with gdb,but variables printed normally.
I think it means losing of the symbols of the glibc itself.

**Comment by sonysuqin** [comment]
Ok，after I update gdb from 7.2 to 7.8 ，this problem solved.
Thank you all the way.

**Comment by kqyang** [comment]
Glad to hear that.
