### ISSUE TITLE
Is the encrpytion/decryption algorithm in shaka-packager compatible with openssl

### ISSUE THREAD

**Issue by sonysuqin** [google/shaka-packager#249]
I found shaka-packager uses AES CBC & CTR for encrpytion & decryption，is it completely compatible with openssl？Or is there any customization?

**Comment by kqyang** [comment]
The encryption / decryption in shaka-packager is implemented according to relevant specifications. For example, for CENC encryption modes (cenc / cbcs / cbc1 / cens), it is implemented according to ISO/IEC 23001-7:2016 Common encryption in ISO base media file format files, which is often referred to as CENC spec. It employs standard AES CBC / CTR algorithm with custom requirements on the initialization vector and how to apply the encryption/decryption to the media sample - see CENC spec for the details. In fact, we are using openssl inside shaka-packager to perform all the encryption / decryption.

**Comment by sonysuqin** [comment]
I got it.It's boringssl,a branch of openssl.
Thank you.
