### ISSUE TITLE
Shaka packaged hls fails to play on Chromecast

### ISSUE THREAD

**Issue by AlphaSolutions7** [google/shaka-packager#250]
## System info
**Operating System**: windows 10
**Shaka Packager Version**: 1.6.2

## Issue and steps to reproduce the problem
Use shaka to package HLS for vod 

**Packager Command**:
"in=d:\video_1280x720_1800.mp4,stream=video,hls_group_id=audio_1,segment_template=d:\output\video_1800000/segment_$Number$.ts,playlist_name=video_1800000_hls.m3u8,hls_name=video_1800000"
"in=d:\video_854x480_1200.mp4,stream=video,hls_group_id=audio_1,segment_template=d:\output\video_1200000/segment_$Number$.ts,playlist_name=video_1200000_hls.m3u8,hls_name=video_1200000"  
"in=d:\video_640x360_800.mp4,stream=video,hls_group_id=audio_1,segment_template=d:\output\video_800000/segment_$Number$.ts,playlist_name=video_800000_hls.m3u8,hls_name=video_800000"  
"in=d:\video_512x288_400.mp4,stream=video,hls_group_id=audio_1,segment_template=d:\output\video_400000/segment_$Number$.ts,playlist_name=video_400000_hls.m3u8,hls_name=video_400000"  
"in=d:\video_aac_128.mp4,stream=audio,hls_group_id=audio_1,segment_template=d:\output\audio_128000/segment_$Number$.ts,playlist_name=audio_128000_hls.m3u8,hls_name=audio_128000" 
 --segment_duration=3 --hls_master_playlist_output="d:\output\master.m3u8"

Extra steps to reproduce the problem?
(1) Encode for hls with the proper video profile, level, and key frame interval (3xfps for this example). 
(2) Package HLS with Shaka, no encryption. 

What is the expected result?
Video should stream successfully on Chromecast player. 

What happens instead?
Video streamed successfully with different hls players, and different browsers, including Safari on Mac, Edge, Firefox, Roku, but Chromecast raises MEDIA_ERR_SRC_NOT_SUPPORTED error. the same video works fine on Chromecast when packaged with other hls packaging tools.

<Please attach the input files or email to shaka-packager-issues@google.com.>
https://www.dropbox.com/sh/1xc8ijvnv6tjfwh/AABkgWVEaASgAMWBgdOqMEoFa?dl=0

<Please provide any additional information below.>

**Comment by kqyang** [comment]
Unfortunately the default Chromecast player (MPL) has problem supporting variant stream right now. Have you tried using shaka-player on Chromecast? It should work.

**Comment by AlphaSolutions7** [comment]
thank you @kqyang , we switched players and it looks good.

**Comment by kqyang** [comment]
Great!
