### ISSUE TITLE
Video not playing on Firefox when packaging it with shaka packager + clearkey

### ISSUE THREAD

**Issue by mhassanist** [google/shaka-packager#251]
## System info
**Operating System**: Windows 7
**Shaka Packager Version**: latest pulled

## Issue and steps to reproduce the problem

**Packager Command**:
packager  input=input.mp4,stream=audio,init_segment=audio.mp4,segment_template=audio-$Number$.mp4 input=input.mp4,stream=video,init_segment=video.mp4,segment_template=video-$Number$.mp4' --mpd_output live_static.mpd --enable_fixed_key_encryption --key "E6DD428E76CC154441A2ED3CECE4A3DB" --key_id "20000000200020002000200000000002" --generate_static_mpd

What is the expected result?
The encrypted video plays normally on all supported browsers and Android Exo Player. 

What happens instead?
Plays only on Chrome locally. Does not play on Firefox locally, Chrome (when files hosted on amazon aws) and from Android exo player.

However, when I package the files using bento4 mp4dash , it works on all except on Chrome when files hosted on amazon aws.

```
mp4fragment input.mp4 input-frag.mp4 

mp4dash --encryption-key=audio:20000000200020002000200000000002:E6DD428E76CC154441A2ED3CECE4A3DB,video:20000000200020002000200000000002:E6DD428E76CC154441A2ED3CECE4A3DB input.mp4 --exec-dir=C:\bento\bin 
```

I noticed the difference in the manifest file generated by both as follow:

>> From Shaka packager 
```
<?xml version="1.0" ?>
<MPD mediaPresentationDuration="PT1M2.320S" minBufferTime="PT5.40S" profiles="urn:mpeg:dash:profile:isoff-live:2011" type="static" xmlns="urn:mpeg:dash:schema:mpd:2011" xmlns:cenc="urn:mpeg:cenc:2013">
  <!-- Created with Bento4 mp4-dash.py, VERSION=1.8.0-615 -->
  <Period>
    <!-- Video -->
    <AdaptationSet maxHeight="360" maxWidth="480" mimeType="video/mp4" minHeight="360" minWidth="480" segmentAlignment="true" startWithSAP="1">
      <!-- MPEG Common Encryption -->
      <ContentProtection cenc:default_KID="27992649-6a7f-5d25-da69-f2b3b2799a7f" schemeIdUri="urn:mpeg:dash:mp4protection:2011" value="cenc"/>
      <SegmentTemplate duration="5400" initialization="$RepresentationID$/init.mp4" media="$RepresentationID$/seg-$Number$.m4s" startNumber="1" timescale="1000"/>
      <Representation bandwidth="240068" codecs="avc1.4D4015" frameRate="25" height="360" id="video/avc1" scanType="progressive" width="480"/>
    </AdaptationSet>
    <!-- Audio -->
    <AdaptationSet mimeType="audio/mp4" segmentAlignment="true" startWithSAP="1">
      <!-- MPEG Common Encryption -->
      <ContentProtection cenc:default_KID="27992649-6a7f-5d25-da69-f2b3b2799a77" schemeIdUri="urn:mpeg:dash:mp4protection:2011" value="cenc"/>
      <SegmentTemplate duration="5400" initialization="$RepresentationID$/init.mp4" media="$RepresentationID$/seg-$Number$.m4s" startNumber="1" timescale="1000"/>
      <Representation audioSamplingRate="44100" bandwidth="133241" codecs="mp4a.40.2" id="audio/und/mp4a">
        <AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="2"/>
      </Representation>
    </AdaptationSet>
  </Period>
</MPD>
```

>> From mp4dash
```
<?xml version="1.0" encoding="UTF-8"?>
<!--Generated with https://github.com/google/shaka-packager version v1.6.2-6b98f0d-release-->
<MPD xmlns="urn:mpeg:dash:schema:mpd:2011" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xlink="http://www.w3.org/1999/xlink" xsi:schemaLocation="urn:mpeg:dash:schema:mpd:2011 DASH-MPD.xsd" xmlns:cenc="urn:mpeg:cenc:2013" profiles="urn:mpeg:dash:profile:isoff-live:2011" minBufferTime="PT2S" type="static" mediaPresentationDuration="PT62.415S">
  <Period id="0">
    <AdaptationSet id="0" contentType="audio" segmentAlignment="true">
      <ContentProtection value="cenc" schemeIdUri="urn:mpeg:dash:mp4protection:2011" cenc:default_KID="20000000-2000-2000-2000-200000000002"/>
      <ContentProtection schemeIdUri="urn:uuid:1077efec-c0b2-4d02-ace3-3c1e52e2fb4b">
        <cenc:pssh>AAAANHBzc2gBAAAAEHfv7MCyTQKs4zweUuL7SwAAAAEgAAAAIAAgACAAIAAAAAACAAAAAA==</cenc:pssh>
      </ContentProtection>
      <Representation id="0" bandwidth="129413" codecs="mp4a.40.2" mimeType="audio/mp4" audioSamplingRate="44100">
        <AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="2"/>
        <SegmentTemplate timescale="44100" initialization="audio.mp4" media="audio-$Number$.mp4" startNumber="1">
          <SegmentTimeline>
            <S t="0" d="441344" r="5"/>
            <S t="2648064" d="104448"/>
          </SegmentTimeline>
        </SegmentTemplate>
      </Representation>
    </AdaptationSet>
    <AdaptationSet id="1" contentType="video" width="480" height="360" frameRate="90000/3600" segmentAlignment="true" par="4:3">
      <ContentProtection value="cenc" schemeIdUri="urn:mpeg:dash:mp4protection:2011" cenc:default_KID="20000000-2000-2000-2000-200000000002"/>
      <ContentProtection schemeIdUri="urn:uuid:1077efec-c0b2-4d02-ace3-3c1e52e2fb4b">
        <cenc:pssh>AAAANHBzc2gBAAAAEHfv7MCyTQKs4zweUuL7SwAAAAEgAAAAIAAgACAAIAAAAAACAAAAAA==</cenc:pssh>
      </ContentProtection>
      <Representation id="1" bandwidth="227584" codecs="avc1.4d4015" mimeType="video/mp4" sar="1:1">
        <SegmentTemplate timescale="90000" initialization="video.mp4" media="video-$Number$.mp4'" startNumber="1">
          <SegmentTimeline>
            <S t="3600" d="972000"/>
            <S t="975600" d="932400"/>
            <S t="1908000" d="990000"/>
            <S t="2898000" d="957600"/>
            <S t="3855600" d="968400"/>
            <S t="4824000" d="788400"/>
          </SegmentTimeline>
        </SegmentTemplate>
      </Representation>
    </AdaptationSet>
  </Period>
</MPD>
```

Another question: why in all cases does not work after uploading to live server on Google chrome ?

Attachements
- Original Video Before Encryption

- Live links
http://ec2-52-42-32-95.us-west-2.compute.amazonaws.com/shaka/shaka_final/ (packaged with Shaka)
http://ec2-52-42-32-95.us-west-2.compute.amazonaws.com/shaka/shaka_final/mp4dash/ (packaged with mp4dash - test on firefox)

**Comment by kqyang** [comment]
Have you uploaded the media files to AWS? Where are they located? I am not able to get the files, e.g. http://ec2-52-42-32-95.us-west-2.compute.amazonaws.com/shaka/shaka_final/video-1.mp4 does not work.

**Comment by mhassanist** [comment]
There is a apostrophe at the end, video-1.mp4'

[Uploading mp4dash.zip…]()
[Uploading shaka_final.zip…]()

**Comment by kqyang** [comment]
The player reports error code 6001. See https://shaka-player-demo.appspot.com/docs/api/shaka.util.Error.html for the description of the error code. For your case, it is because the key system is not available from unsecure contexts. (ie. requires HTTPS) See https://goo.gl/EEhZqT. You'll need to serve the contents in https instead.

**Comment by mhassanist** [comment]
Thanks for your  replay. I have hosted the content on  https server (free certificate).
Now the result is 
https://www.gotripapp.com/shaka_final/   -> packaged with shaka 
--> playing on chrome : pass
--> playing on firefox : failed

https://www.gotripapp.com/shaka_final/mp4dash/ -> packaged with mp4dash
--> playing on chrome : pass
--> playing on firefox : pass

**Comment by kqyang** [comment]
We'll investigate. Thanks for reporting.

**Comment by kqyang** [comment]
@mhassanist I am actually seeing a different error: the player keeps buffering. I'll ask for shaka-player team for help. 

As for putting outputs in different folders, you can do that in shaka-packager by specifying the folders in the command, i.e.

```
input=input.mp4,stream=audio,init_segment=audio/audio.mp4,segment_template=audio/audio-$Number$.mp4 input=input.mp4,stream=video,init_segment=video/video.mp4,segment_template=video/video-$Number$.mp4' 
```

@joeyparrish Can you help take a look? Thanks.

**Comment by joeyparrish** [comment]
I can't tell what's wrong on Firefox.  There's nothing obviously wrong about the content.

Your repro page is using Shaka Player v2.1.3.  I also tried v2.1.5 and v2.0.8 and got the same results.  So I do not believe it is a regression in Shaka Player.

My best guess is that this is either a bug in Firefox's ClearKey implementation or in Firefox's MediaSource implementation.  Please [file a bug on Mozilla](https://bugzilla.mozilla.org/) and provide them with a [link to your demo](https://www.gotripapp.com/shaka_final/).  Then link to the bug from here so that we can CC the right folks at Mozilla and help them investigate if needed.

**Comment by mhassanist** [comment]
@joeyparrish  if so why it works with no problem with other packagers (i.e. mp4dash)

**Comment by joeyparrish** [comment]
@mhassanist, I don't know.  From what I can tell, there's nothing obviously wrong with the content.  If I can't see the problem with the content or manifest, and it plays well in other browsers, then I have to assume for now that it's a Firefox bug.  If someone from Mozilla looks into it and can explain to us why the content is at fault, then we can fix it on our side.

The folks at Mozilla are very helpful, and I'm sure we can figure out the cause with their help.  If you will file a bug with them, I will make sure it gets to the right people and that we determine which piece of software is responsible.  Thanks!

**Comment by kqyang** [comment]
@mhassanist, Have you had a chance to file an issue on Mozilla?

**Comment by kqyang** [comment]
@mhassanist Sorry for not getting back to you earlier. I think it is caused by the clear lead, which is not handled properly in earlier versions of Firefox. I am not sure exactly which version fixed the issue, but v59 works. 

That is why it works on mp4dash but not Shaka Packager as Shaka Packager has a default 10 seconds clear lead, which you can disable by setting --clear_lead=0 (https://google.github.io/shaka-packager/html/documentation.html#general-encryption-options).

Does this answer your question?
