### ISSUE TITLE
Add leading zeros to $Number$ and/or $Time$ to segment_template

### ISSUE THREAD

**Issue by PyRo1509** [google/shaka-packager#252]
Enhancement Request:

Currently it splits:
video9.ts
video10.ts
....
video99.ts
video100.ts

Would be nice to allow for included zeros:
video009.ts
video010.ts
...
video099.ts
video100.ts

Thank you.

**Comment by kqyang** [comment]
It is already supported. We support the below mentioned format scheme:

> ISO/IEC 23009-1 Media presentation description and segment formats 
> 5.3.9.4.4 Template-based Segment URL construction 
>
> Each identifier may be suffixed, within the enclosing ‘$’ characters, with an additional format tag aligned with the printf format tag as defined in IEEE 1003.1-2008 [10] following this prototype:
>
> %0[width]d
>
> The width parameter is an unsigned integer that provides the minimum number of characters to be printed. If the value to be printed is shorter than this number, the result shall be padded with zeros. The value is not truncated even if the result is larger.

So to generate with 3 digits, you can use:

```
video$Number%03d$.ts
```
