### ISSUE TITLE
Wrong installation need help!

### ISSUE THREAD

**Issue by chanof** [google/shaka-packager#255]
hi there, im moving from dashcast 
an error occured during Shaka Packager :
MacBook-Pro-di-Gian:shaka_packager gian$ ninja -C out/{Debug,Release} [Module]
ninja: Entering directory `out/Debug'
ninja: fatal: chdir to 'out/Debug' - No such file or directory
i try different try & error without result i can't close the installation, it is mac compatible?
Cause in linux im unable to get gclient working
Someone could help me  a little?

**Comment by kqyang** [comment]
Yes, both MAC and Linux are supported. Have you followed the instruction in https://github.com/google/shaka-packager. Does `gclient sync` execute successfully?

**Comment by chanof** [comment]
thank for fast reply! yes gclient work, i think to correct install depot tools, i don't exactly understand where execute "ninja -C out/{Debug,Release} [Module]" and if need some modify, 
the error after execution is the above

**Comment by chanof** [comment]
sorry you re right, gclient sync result 2 errors

OSError: [Errno 2] No such file or directory: '/Library/Developer/CommandLineTools/Platforms/MacOSX.platform/Developer/SDKs'
gyp: Call to 'python ./build/mac/find_sdk.py 10.10' returned exit status 1 while in /Users/gianmariaallibrante/shaka_packager/src/packager/packager.gyp.
Error: Command '/usr/bin/python src/gyp_packager.py --depth=src/packager' returned non-zero exit status 1 in /Users/gianmariaallibrante/shaka_packager

**Comment by kqyang** [comment]
Sorry for not making it clear. The OS X 10.10 SDK is needed to compile packager on MAC. Alternatively you can get prebuilt binaries in Release section.

**Comment by chanof** [comment]
I also want to setup a Debian system, may i know from the basicOS  installation which stuff i need to correctly run and and generate live streaming segments?

**Comment by kqyang** [comment]
I have not tried Debian myself, but https://github.com/google/shaka-packager#setting-up-for-development should work. Just follow the instructions there. Let us know if anything comes up.

**Comment by chanof** [comment]
I will! Thanks for support
