### ISSUE TITLE
Debian 9 Shaka Packager installation for live use

### ISSUE THREAD

**Issue by chanof** [google/shaka-packager#256]
Hello to all! i'm a student for my thesis i choose a mpeg-dash tv. I run for some time DashCast but after a lot of try and error  i choose to try something more stable
My mission is to setup inside Debian an mpeg-dash pseude-live transcoder to broadcast a playlist of videos over and over even multibitrate and send it to a web server.
All processes must be open source like this project which i like to share, and i would like to use this post to find and fix all bugs till the completion.
Thank in advance for support

-Installation on debian 9 amd64
-apt-get install git curl build-essential

An error occurred after "gclient sync" 
"ninja -C out/{Debug,Release} [Module]"
ninja: Entering directory `out/Debug'
ninja: error: unknown target 'out/Release'

Someone know how can i fix it?
Thanks
Gian

a piece of the log:
_______ running '/usr/bin/python src/packager/third_party/binutils/download.py' in '/home/user/shaka_packager'
0> Downloading /home/user/shaka_packager/src/packager/third_party/binutils/Linux_x64/binutils.tar.bz2...
Success!
Downloading 1 files took 13.307278 second(s)
Downloading /home/user/shaka_packager/src/packager/third_party/binutils/Linux_x64/binutils.tar.bz2
Extracting /home/user/shaka_packager/src/packager/third_party/binutils/Linux_x64/binutils.tar.bz2
Hook '/usr/bin/python src/packager/third_party/binutils/download.py' took 14.88 secs

________ running '/usr/bin/python src/packager/tools/clang/scripts/update.py --if-needed' in '/home/user/shaka_packager'
Updating Clang to 274369-1...
Creating directory /home/user/shaka_packager/src/packager/third_party/llvm-build
Downloading prebuilt clang
Downloading https://commondatastorage.googleapis.com/chromium-browser-clang/Linux_x64/clang-274369-1.tgz .......... Done.
Creating directory /home/user/shaka_packager/src/packager/third_party/llvm-build/Release+Asserts
clang 274369-1 unpacked
Hook '/usr/bin/python src/packager/tools/clang/scripts/update.py --if-needed' took 10.85 secs

________ running '/usr/bin/python src/gyp_packager.py --depth=src/packager' in '/home/user/shaka_packager'
Updating projects from gyp files...

________ running '/usr/bin/python src/packager/build/util/lastchange.py -o src/packager/build/util/LASTCHANGE' in '/home/user/shaka_packager'
user@debian:~/shaka_packager$ cd src
user@debian:~/shaka_packager/src$ ninja -C out/{Debug,Release} [Module]
ninja: Entering directory `out/Debug'
ninja: error: unknown target 'out/Release'

**Comment by chanof** [comment]
I would also like to ask if the project for you can be achieved ?
I have recreated all processes

I'd like to know if sync a mpeg-dash live encoding output local folder with an ftp will make the live 
and what tool to use for that purpose?

Cause for the moment my tests are only on the local network/webserver (apache) 
Thanks!

**Comment by kqyang** [comment]
> ninja -C out/{Debug,Release} [Module]

[Module] needs to be released with an actual module. If you don't have any module to build in mind, just use `ninja -C out/Debug` or `ninja -C out/Release` which builds all modules.

> I'd like to know if sync a mpeg-dash live encoding output local folder with an ftp will make the live
and what tool to use for that purpose?

Are you asking what tool to use to sync between local storage and the ftp server? We don't have a recommendation but there are a lot of ftp syncing tool available, just Google it. You can consider using a cloud provider, e.g. Amazon AWS, Google Cloud, Microsoft Azure. They usually provide their own tools to sync from client to server.

**Comment by chanof** [comment]
Hi! as i sad i did all the process before but i test it only in local on a web server which also did the encode directly on the html folder of apache.
So i wonder to know if the common ways to sync folder with ftp are useful for send the live packages of dash, if it is possible or if the web server have to do this by add another service for video dash encoder like what i do, 
Your answer make me understand that yes, it is possible to correct send a dash live broadcast to ftp by folder sincronization
Stop me if aim wrong :)

i did 
ninja -C out/Debug
after i did
ninja -C out/Release
Now i try to run simply "packager" on terminal but the command is unknown
what is going on?
Thanks!!!

**Comment by kqyang** [comment]
> Your answer make me understand that yes, it is possible to correct send a dash live broadcast to ftp by folder sincronization

Yes. Do note that you may need special care for the manifest as it is constantly being updated. You need to make sure it does not happen that the manifest is updated and uploaded but the media stream referenced in the new manifest is not uploaded. One way to solve this problem is to create a copy of the manifest during syncing and upload the copied manifest after all media files are synced.

> Now i try to run simply "packager" on terminal but the command is unknown

`packager` can be found in out/Release directory.

**Comment by chanof** [comment]
What I'm doing wrong?
user@debian:~/shaka_packager/src/out/Release$ packager
-su: packager: comando non trovato
user@debian:~/shaka_packager/src/out/Release$ ls
build.ninja        media_base_unittest   packager_test.py
chunking_unittest  media_event_unittest  protoc
codecs_unittest    mp2t_unittest         pyproto
crypto_unittest    mp4_unittest          status_unittest
demuxer_unittest   mpd_generator         test_env.py
file_unittest      mpd_unittest          trick_play_unittest
gen                obj                   webm_unittest
hls_unittest       packager              webvtt_unittest
icudtl.dat         packager_app.py       wvm_unittest
libpackager.a      packager_test

**Comment by chanof** [comment]
Im redoing all to understand where I'm wrong,
What you say is very interesting, i suppose to need doing some test.
This make me think that maybe i don't really need to encode the video live:
Can i create the mpeg dash files end upload them with an mpd included for live that use the actual time to choose which point of the video show to users?

**Comment by chanof** [comment]
Another thing i have to report is that client ask me to run not under root, is print that is sad use it by root..
To complete the install i execute all with no root permission
I think this can be the problem

**Comment by kqyang** [comment]
> user@debian:/shaka_packager/src/out/Release$ packager

You need to include the path, so it should be ./packager.

And no, you don't need root permission to do packaging.

**Comment by chanof** [comment]
Hi! thank you for your special help, it run!
Can you suggest me which command can i use to process a list of videos and when the list is finished it restart again over and over?
I ask it cause i understand shaka_packager can generate also only mpd or only fragments, i need a constant fragment process and mpd update for live use from mp4 videos, to run it with dash.js
Thanks!

**Comment by kqyang** [comment]
Not sure what you are asking. The `packager` program is able to generate the fragments and update mpds.

**Comment by kqyang** [comment]
Close due to inactivity. Feel free to reopen it if you have more questions.
