### ISSUE TITLE
Removing old segment files for live streaming applications

### ISSUE THREAD

**Issue by rmoe-picodigital** [google/shaka-packager#257]
## System info
**Operating System**: Ubuntu 16.04
**Shaka Packager Version**: 096c22e-release

Would it be possible to have the packager remove old segment files after some time period?  In relation to issue [223](https://github.com/google/shaka-packager/issues/223), we have a need to remove from the filesystem the video files after a certain time period.  And since the packager, after it receives the feature in issue 223, would know when a segment is removed from the mpd file, at some time period shortly after that event the video file could also be removed from the filesystem.

**Comment by kqyang** [comment]
Duplicate of #223. We planned to address #223 last quarter but short of resources. We should be able to address it this quarter.
