### ISSUE TITLE
Fairplay support patch

### ISSUE THREAD

**Issue by Palethorn** [google/shaka-packager#258]
**Shaka Packager Version**: b451d3a7ca6f454b4905043d56dd9620247d8c71

**Packager Command**:
```./packager \ 'input=udp://127.0.0.1:11000,stream=3,segment_template=fairplay_video-$Number$.ts,playlist_name=video.m3u8' \
 'input=udp://127.0.0.1:11000,stream=0,segment_template=fairplay_audio1-$Number$.ts,playlist_name=audio1.m3u8,hls_group_id=audio1,hls_name=EN' \
  --enable_fixed_key_encryption \
  --clear_lead 0 \
  --key ... \
  --key_id ... \
  --iv ... \
  --hls_playlist_type LIVE  \
  --hls_master_playlist_output="playlist.m3u8"
```
I would like to properly patch shaka-packager to produce SAMPLE-AES crypted content. The end result is having this kind of header in HLS chunklist:
```#EXT-X-KEY:METHOD=SAMPLE-AES,URI="skd://entry",KEYFORMAT="com.apple.streamingkeydelivery",KEYFORMATVERSIONS="1"```
instead of this one which requires transfering key in clear format:
```#EXT-X-KEY:METHOD=SAMPLE-AES,URI="data:text/plain;base64,...",IV=0x...,KEYFORMAT="identity"```
I already have it working by hardcoding the header into media_playlist. I would like to submit a proper patch for this. Any pointers on how should I approach this task?

**Comment by Palethorn** [comment]
Would I be able to add another FOURCC to packager/media/base/fourccs.h, for example FOURCC_cbcf for fairplay, and then perform necessary checks?

**Comment by kqyang** [comment]
@Palethorn Thanks for helping on improving Shaka Packager.

I suggest adding a new key system instead of using fourcc to signal fairplay since fairplay is really a key system protocol while fourcc is used to indicate the encryption format.

(1) Define a system id for fairplay:

https://github.com/google/shaka-packager/blob/master/packager/media/base/fixed_key_source.h#L22

Fairplay does not an official system id defined right now. We can use an arbitrary unique 16-byte string here.

(2) Add fairplay key system to encryption_key->key_system_info when appropriate flag is defined:

https://github.com/google/shaka-packager/blob/master/packager/media/base/fixed_key_source.cc#L115

(3) Add appropriate logic below to notify encryption to the media playlists:

https://github.com/google/shaka-packager/blob/master/packager/hls/base/simple_hls_notifier.cc#L365

Btw, how should `URI` to look like? I assume it needs to be passed down as well. Does it need to be template formatted, e.g. from KEY_ID?

**Comment by Palethorn** [comment]
@kqyang thanks you for the information. Things seem clearer now.
URI has a loose format in this case. skd://path is an example provided by Fairplay SDK documentation as it specifies how a player requests a key using license acquisition url. So yeah, we can probaby use that template for now. I suggest accepting it as an optional parameter to a packager command at some later time.

**Comment by kqyang** [comment]
> I suggest accepting it as an optional parameter to a packager command at some later time.

Sounds good to me.

> Oh, and I stumbled on this some time ago: https://forums.developer.apple.com/thread/6185. There is an unofficial systemID for fairplay which is 29 70 1F E4 3C C7 4A 34 8C 5B AE 90 C7 43 9A 47.

Interesting! I think it is fine to use this system id to indicate fairplay internally in packager. 

> I see that MediaPlaylist::EncryptionMethod::kSampleAesCenc is added as a supported encryption method. 

We defined our own extension to signal CENC with CTR mode in HLS. MediaPlaylist::EncryptionMethod::kSampleAesCenc indicates that the content is encrypted using CTR (cenc protection scheme in CENCv3) and it tells the player to generate the custom tag we defined for CTR mode. This custom tag is also supported in [Shaka Player](https://github.com/google/shaka-player).

As a separate topic, Widevine does support the original Sample-AES (CBC mode) on some platforms, e.g. Chromecast, Android (I forgot which revision starts supporting it, but it is supported in the latest revision). You'll need a player that understands Widevine signaling to play the content.
 
There is no public document on the Widevine signaling in HLS yet. We'll be happy to compile one. Stay tuned.

**Comment by Palethorn** [comment]
OK, thank you for the information.

**Comment by Palethorn** [comment]
I need to handle URI info. Right now it's a key_id base64 encoded https://github.com/google/shaka-packager/blob/master/packager/hls/base/simple_hls_notifier.cc#L161. It seems to mess up the license acquisition. Should I move that operation out of there and under here https://github.com/Palethorn/shaka-packager/blob/fairplay_key_system_support/packager/hls/base/simple_hls_notifier.cc#L377

**Comment by Palethorn** [comment]
Accidentally closed the issue.

**Comment by Palethorn** [comment]
Just tested this with fMP4 support. Runs just fine. For people wondering about the command:
```
packager \
  'input=udp://127.0.0.1:11000,stream=3,init_segment=init_v.mp4,segment_template=video-$Number$.mp4,playlist_name=video.m3u8' \
  'input=udp://127.0.0.1:11000,stream=0,init_segment=init_a1.mp4,segment_template=audio1-$Number$.mp4,playlist_name=audio1.m3u8,hls_group_id=audio1,hls_name=EN' \
  --enable_fixed_key_encryption \
  --clear_lead 0 \
  --key A6B3EE86A5DA9FB98BCD44DEAFA91B31 \
  --key_id 5b0813d7dbb044929bf5baf5a57fe1df \
  --iv 7c6288634401226c552dc1d1d31f96f8 \
  --hls_playlist_type LIVE  \
  --protection_scheme cbcs \
  --pssh <insert_pssh_here> \
  --hls_master_playlist_output="playlist.m3u8"
```
pssh is generated using packager/tools/pssh/pssh-box.py, just give it systemID for fairplay from above.

**Comment by awakenedguy** [comment]
Successfully produced fmp4 hls encrypted with Sample-AES (not FairPlay). But the result is unplayable by hls.js [https://github.com/video-dev/hls.js/issues/173](url). Something appears to be clearly wrong. Is it a known problem?

**Comment by kqyang** [comment]
@awakenedguy No. We are not aware of this issue. We'll look into it. Can you also attach the link to the packaged files you generated or email it to shaka-packager-issues@google.com?

**Comment by awakenedguy** [comment]
Sure, here is [unencrypted stream](https://video-8f60.kxcdn.com/demo_Shaka_unencrypted/master.m3u8), and here is exactly the [same but encrypted with clear key Sample-AES](https://video-8f60.kxcdn.com/demo_Shaka_Sample-AES/master.m3u8).

You can see it live, [unencrypted ]() and [encrypted ](https://video-dev.github.io/hls.js/demo/?src=https%3A%2F%2Fvideo-8f60.kxcdn.com%2Fdemo_Shaka_unencrypted%2Fmaster.m3u8&enableStreaming=true&autoRecoverError=true&enableWorker=true&dumpfMP4=false&levelCapping=-1&defaultAudioCodec=undefined)one.

**Comment by kqyang** [comment]
It does look like hls.js problem. I packaged a stream: https://storage.googleapis.com/wvtemp/kqyang/hls_cbcs/master.m3u8. It works in both Safari and QuickTime but does not work in hls.js.

I'll close this issue. Feel free to re-open it or open another issue if there is any update.

You may want to file an issue on hls.js to see if they have any clue on what is going on.
