### ISSUE TITLE
File permissions for .mpd file

### ISSUE THREAD

**Issue by atoztoa** [google/shaka-packager#259]
## System info
**Operating System**: Ubuntu 16
**Shaka Packager Version**: 19be04e-release

## Issue and steps to reproduce the problem

**Packager Command**:

packager input=udp://239.215.1.33:7001?interface=172.22.71.232&reuse=1,stream=audio,init_segment=espn_audio.mp4,segment_template=espn_audio-$Number$.mp4,bandwidth=64000 --enable_widevine_encryption --content_id 6573706e --signer widevine_test --aes_signing_key 1ae8ccd0e7985cc0b6203a55855a1034af02689f947ab9 --aes_signing_iv d58ce954207f59839249 --crypto_period_duration 100 --mpd_output boo.mpd

What is the expected result?
boo.mpd created with proper permissions.

What happens instead?

boo.mpd has 400 permission.

This only happens in one Ubuntu machine. In another instance, the file is properly created.

How is the file permissions determined?

**Comment by kqyang** [comment]
We don't manipulate file permissions in packager. It is all determined by the system. Here is an article on setting file permissions in linux: https://unix.stackexchange.com/questions/1314/how-to-set-default-file-permissions-for-all-folders-files-in-a-directory. Hope that helps.

**Comment by Palethorn** [comment]
I've noticed the same issue with HLS packaging. 
`
-rw-------  1 xxx    xxx      319 Aug  1 10:48 audio1.m3u8
-rw-------  1 xxx    xxx      275 Aug  1 10:48 playlist.m3u8
-rw-------  1 xxx    xxx      135 Aug  1 10:48 video.m3u8
`
even though:
` getfacl .
# file: .
# owner: xxx
# group: xxx
# flags: -s-
user::rwx
group::r-x
other::r-x
default:user::rwx
default:group::rw-
default:other::rw-
`

**Comment by Palethorn** [comment]
Could it be that using mkstemp for WriteFileAtomically messes up the permissions without any regard to acl settings?

**Comment by kqyang** [comment]
@Palethorn You are right. Thanks for spotting that! Didn't know that mkstemp creates the file with 0600 permission. @atoztoa Thanks for reporting the issue. We are working on a fix.

**Comment by kqyang** [comment]
This should be fixed now. @atoztoa @Palethorn Let us know if you are still seeing problems.

**Comment by atoztoa** [comment]
Is this in the head?

**Comment by kqyang** [comment]
Yes.

**Comment by atoztoa** [comment]
This issue is verified fixed.
