### ISSUE TITLE
widevine CE CDM doesnt play shaka packaged mp4

### ISSUE THREAD

**Issue by pavankn** [google/shaka-packager#261]
Hi, 
I have encrypted an MP4 using shaka packager and found that the default IV size is 8 bytes  . 
I am trying to play this content in my Raspberry pi which uses widevine CE cdm shared library to decrypt the encrypted MP4 .  Unfortunately, this .so supports only IV size of 16 bytes and not 8 bytes as generated by shakha .  Let me know how should i approach this problem 

I am using the below command to package the mp4 file

./packager input=/MyStream/SintelTrailer.mp4,stream=video,output=WVSintelTrailerVideo.mp4 --enable_widevine_encryption \
--key_server_url "https://license.uat.widevine.com/cenc/getcontentkey/widevine_test" \
--signer "widevine_test" --content_id "4d794e616d6549734e697474616c6150" \
--aes_signing_key "1ae8ccd0e7985cc0b6203a55855a1034afc252980e970ca90e5202689f947ab9" \
--aes_signing_iv "4d794e616d6549734e697474616c6150" --crypto_period_duration 0 --output_media_info

Pavan

**Comment by kqyang** [comment]
@pavankn The media parser need to zero extend the IV to 16 bytes before passing it to CDM APIs.

In case you are curious, we generate 8-byte IV for 'cenc' encryption mode in Shaka Packager as it is recommended by the CENC spec. See 23001-7:2016 10.1 'cenc' AES-CTR scheme for details.

**Comment by pavankn** [comment]
@kqyang , 
Thanks a lot for this simple fix . Worked like a charm
