### ISSUE TITLE
Error when using webm generated by ffmpeg

### ISSUE THREAD

**Issue by argotan** [google/shaka-packager#263]
The S.O. It is neon 16.04 (ubuntu) and packager-linux version v1.6.2-6b98f0d-release. I'm coding several files with ffmpeg in both mp4 and webm. With the mp4 files generated by ffmpeg I do not have any problems. But, I compromise with the webm, packager gives me error, gives the same the command you use, it is always the same error

```
./Packager-linux in=original_ff_vp9.webm --dump_stream_info
[0814/191831: INFO: demuxer.cc (58)] Initialize Demuxer for file 'original_ff_vp9.webm'.
[0814/191831: ERROR: packager_main.cc (311)] Demuxer failed to initialize: 8 (PARSER_FAILURE): Can not parse media file original_ff_vp9.webm
```

To generate the webm file, I followed the command they recommend on the [webm web page](Http://wiki.webmproject.org/adaptive-streaming/instructions-to-playback-adaptive-webm-using-dash) itself

```
VP9_DASH_PARAMS = "- tile-columns 4-frame-parallel 1"

Ffmpeg -i input_video.y4m -c: v libvpx-vp9 -s 160x90 -b: v 250k -keyint_min 150 -g 150 $ {VP9_DASH_PARAMS} -an -f webm -dash 1 video_160x90_250k.webm
```

The most funny thing is if I use hadbrake to encode the video in a mkv with vp9 codec, packager works perfectly.

What am I doing wrong when coding with ffmpeg the files type webm?

Thank you

**Comment by kqyang** [comment]
Thanks for reporting the problem. Can you upload the output from FFmpeg or email it to shaka-packager-issues@google.com? That will help us locate the problem faster.

**Comment by argotan** [comment]
ffmpeg
`
ffmpeg -i original.mp4 -c:v libvpx-vp9 -s 160x90 -b:v 250k -keyint_min 150 -g 150 -tile-columns 4 -frame-parallel 1 -an -f webm -dash 1 video90.webm >> out_ffmpeg.txt   
ffmpeg version 3.3-1~16.04.york0 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 5.4.1 (Ubuntu 5.4.1-8ubuntu1~16.04.york0) 20170304
  configuration: --prefix=/usr --extra-version='1~16.04.york0' --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
  WARNING: library configuration mismatch
  avutil      configuration: --prefix=/usr --extra-version='2~ubuntu16.04.1~ppa1' --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
  avresample  configuration: --prefix=/usr --extra-version='2~ubuntu16.04.1~ppa1' --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
  swscale     configuration: --prefix=/usr --extra-version='2~ubuntu16.04.1~ppa1' --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
  swresample  configuration: --prefix=/usr --extra-version='2~ubuntu16.04.1~ppa1' --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
  postproc    configuration: --prefix=/usr --extra-version='2~ubuntu16.04.1~ppa1' --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
  libavutil      55. 58.100 / 55. 58.100
  libavcodec     57. 89.100 / 57. 89.100
  libavformat    57. 71.100 / 57. 71.100
  libavdevice    57.  6.100 / 57.  6.100
  libavfilter     6. 82.100 /  6. 82.100
  libavresample   3.  5.  0 /  3.  5.  0
  libswscale      4.  6.100 /  4.  6.100
  libswresample   2.  7.100 /  2.  7.100
  libpostproc    54.  5.100 / 54.  5.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'original.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf57.71.100
  Duration: 00:00:20.95, start: 0.000000, bitrate: 22399 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709), 3840x2160 [SAR 1:1 DAR 16:9], 22352 kb/s, 29.67 fps, 29.67 tbr, 90k tbn, 59.35 tbc (default)
    Metadata:
      handler_name    : VideoHandler
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, mono, fltp, 93 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> vp9 (libvpx-vp9))
Press [q] to stop, [?] for help
[libvpx-vp9 @ 0x55c80d131300] v1.5.0
Output #0, webm, to 'video90.webm':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf57.71.100
    Stream #0:0(und): Video: vp9 (libvpx-vp9), yuv420p, 160x90 [SAR 1:1 DAR 16:9], q=-1--1, 250 kb/s, 29.67 fps, 1k tbn, 29.67 tbc (default)
    Metadata:
      handler_name    : VideoHandler
      encoder         : Lavc57.89.100 libvpx-vp9
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: -1
frame=  620 fps= 57 q=0.0 Lsize=     468kB time=00:00:20.86 bitrate= 183.8kbits/s speed=1.91x    
video:463kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 1.028481%
`

packager
`
./packager-linux in=video90.webm --dump_stream_info
[0814/220929:INFO:demuxer.cc(58)] Initialize Demuxer for file 'video90.webm'.
[0814/220929:ERROR:packager_main.cc(311)] Demuxer failed to initialize: 8 (PARSER_FAILURE): Cannot parse media file video90.webm`

Is there any way to know through packager, if a file is fragmented or not? As mp4info by [bento4](https://www.bento4.com/developers/dash/)

**Comment by kqyang** [comment]
Sorry, I mean the generated webm file from FFmpeg, i.e. video90.webm above. Can you upload it some where or email it to shaka-packager-issues@google.com?

> Is there any way to know through packager, if a file is fragmented or not? As mp4info by bento4

For WebM? `Fragmented` only applies to mp4.

There is a `--dump_stream_info` option which can be used to dump basic stream information, like codec, resolution etc. It does not tell whether the stream is fragmented mp4 though.

**Comment by argotan** [comment]
ok, you dowloand from this [link](https://drive.google.com/file/d/0B3AB896AthdMMEx3MlBoc2JOTlE/view?usp=sharing)

**Comment by kqyang** [comment]
@argotan v1.6.2 does not support the newly added WebM Color element, which is added recently. Can you try the latest build from ToT? It should work.

We will have a new release sometime end of this month or beginning of next month.

**Comment by argotan** [comment]
The term ToT, I do not know it. I understand that you are asking me to build from the source code. But before publishing the error, try to compile it, following the instructions, but it gives me error. When doing the gclient sync, at the end of the error:

```

running '/usr/bin/python src/gyp_packager.py --depth=src/packager' in '/home/spartero/Escritorio/pruebas dash/packager'
Updating projects from gyp files...
gyp: Call to './build/linux/sysroot_ld_path.sh /home/spartero/Escritorio/pruebas dash/packager/src/packager/build/linux/debian_wheezy_amd64-sysroot' returned exit status 1 while in /home/spartero/Escritorio/pruebas dash/packager/src/packager/packager.gyp.
Error: Command '/usr/bin/python src/gyp_packager.py --depth=src/packager' returned non-zero exit status 1 in /home/spartero/Escritorio/pruebas dash/packager

```

And if I continue with the instructions, I enter src
```
Ninja -C Out / Release
or
Ninja -C Out / Release
or
Ninja -C Out / {Debug, Release}
```

They give me the same error
```
Ninja: Entering directory `out/Release/
Ninja: error: loading 'build.ninja': No such file or directory
```
I created the directory out / Release, and one of the errors indicated that there were no such directories. In compilations, I'm not very good

**Comment by kqyang** [comment]
There is a white space in directory name 'pruebas dash', which the build script does not know how to handle, so `gclient sync` failed. Can you try a different directory without white space?

You may also use the [docker image](https://github.com/google/shaka-packager#using-docker-for-testing--development), which is updated on every commit.

**Comment by argotan** [comment]
Ok day, solved
