### ISSUE TITLE
multiple keys in PSSH for single media (audio) input

### ISSUE THREAD

**Issue by dulmandakh** [google/shaka-packager#264]
## System info

**Operating System**: macOS Sierra

**Shaka Packager Version**: 1.6.2 

## Issue and steps to reproduce the problem

**Packager Command**:

```
packager in=audio.mp4,stream=audio,out=audio-enc.mp4 --enable_widevine_encryption --key_server_url "https://license.uat.widevine.com/cenc/getcontentkey/widevine_test" --content_id 74657374 --signer "widevine_test" --aes_signing_key "1ae8ccd0e7985cc0b6203a55855a1034afc252980e970ca90e5202689f947ab9"  --aes_signing_iv "d58ce954203b7c9a9a9d467f59839249"  --output_media_info
mpd_generator --input="audio-enc.mp4.media_info" --output="audio.mpd"
```

or combined

```
packager in=audio.mp4,stream=audio,out=audio-enc.mp4 --enable_widevine_encryption --key_server_url "https://license.uat.widevine.com/cenc/getcontentkey/widevine_test" --content_id 74657374 --signer "widevine_test" --aes_signing_key "1ae8ccd0e7985cc0b6203a55855a1034afc252980e970ca90e5202689f947ab9"  --aes_signing_iv "d58ce954203b7c9a9a9d467f59839249" -mpd_output audio.mpd
```

## What is the expected result?
If you analyze PSSH in DASH manifest file it should contain a single key for audio. For example, PSSH of audio in test contents on Widevine Integration Platform contains single key. Also bento4's mp4-dash output contains single key.

## What happens instead?
PSSH contains multiple keys (key containers and key_ids) for single media file

**Comment by kqyang** [comment]
Widevine license server returns all keys for all tracks by default in a single license, to avoid sending multiple license requests for the same content, which in turn, saves license round trip time. 

The audio itself is still encrypted by audio key only. The other keys are for SD/HD/UHD video.

Is this causing any problems for you? Or do you just want to clarify?

**Comment by dulmandakh** [comment]
I'm trying to implement offline playback on Android, but it fails to
restore keys using persisted key set id. After some digging I found that
PSSH contains 4 keys or key containers, key ids, therefore license server
is returning 4 licenses.

Could it be the cause of key restore failure?

**Comment by kqyang** [comment]
No. What is the error your are getting when you tried to restore the keys?

**Comment by dulmandakh** [comment]
I use ExoPlayer and its OfflineLicenseHelper to download license, so I
persist key set id returned from OfflineLicenseHelper.downloadLicense. But
when I try to play downloaded content setting
DefaulDrmSessionManager.setMode(MODE_PLAYBACK, <persisted key set id>),
then it fails with below exception. Surfing the internet I read that it may
be caused by missing content in a manifest. So I assumed that I'm receiving
many licenses for a single content and couldn't restore them.

MediaDrm: Drm event (2,0) ExoPlayerImplInternal: Renderer error.
com.google.android.exoplayer2.ExoPlaybackException at
com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.feedInputBuffer(MediaCodecRenderer.java:708)
at
com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:511)
at
com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:479)
at
com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:308)
at android.os.Handler.dispatchMessage(Handler.java:98) at
android.os.Looper.loop(Looper.java:154) at
android.os.HandlerThread.run(HandlerThread.java:61) Caused by:
android.media.MediaCodec$CryptoException: Error decrypting data: requested
key has not been loaded

**Comment by kqyang** [comment]
We don't have expertise on how ExoPlayer works. We'll need ExoPlayer folks to take a look at this issue. I noticed that you already filed an issue to ExoPlayer: https://github.com/google/ExoPlayer/issues/3111. Can you attach a full bug report as requested by @ojw28? I'll close this bug. Let's discuss there instead. I'll subscribe to https://github.com/google/ExoPlayer/issues/3111. Feel free to @ me if you need any input from me.
