### ISSUE TITLE
downloadable mpd_generator

### ISSUE THREAD

**Issue by dulmandakh** [google/shaka-packager#266]
This is a request to build and make mpd_generator command available on github. It's a lot of work to download and build shaka-packager from source just to have mpd_generator command.

Thank you

**Comment by kqyang** [comment]
We were actually thinking of deprecating mpd_generator. Is there any specific use case that you'll need `mpd_generator`, which cannot be accomplished with `packager` directly?

**Comment by dulmandakh** [comment]
I couldn't find a way to enerate mpd file from media info files

**Comment by kqyang** [comment]
You can generate mpd files directly using packager, skipping the intermediate media info files altogether. If there is a reason that you want to have the intermediate step, we'll be happy to know :)

**Comment by dulmandakh** [comment]
It would be easy to reuse encrypted content if we can specify media info as
input for packager.
