### ISSUE TITLE
No fast seek with static mpd but fetches all segments until target

### ISSUE THREAD

**Issue by XYG6** [google/shaka-packager#268]
## System info
**Operating System**: Debian 8
**Shaka Packager Version**: 12c61d6-release

## Issue and steps to reproduce the problem

**Packager Command**:

	 packager 'input='$INPUTVIDEO',stream=video,output='$OUTPUTFOLDER'/segmented.mp4,segment_template='$PVIDEO'/session-\$Number$.mp4' \
	 'input='$INPUTVIDEO',stream=audio,output='$OUTPUTFOLDER'audio.mp4,segment_template='$PAUDIO'/audio-\$Number$.mp4' \
	 --enable_widevine_encryption --key_server_url "***" \
	 --content_id "***" --signer "movie" --aes_signing_key "***" \
	 --aes_signing_iv "" -base_urls=***/sessions/segmented/segmented.mp4 \
	 --generate_static_mpd=true -segment_duration=1 \
	 -mpd_output ***/segmented/segmented.mpd

*MOOV data has already been placed at the beginning of the input video file.

**What's the goal?**

I generate 1 second segments of the movie, this is done on purpose on static content, therefore I've enabled --generate_static_mpd=true.

**What is the expected result?**

A fast seekable video stream, meaning if I click on Shaka player on minute 24, the player must load instantly the closest segment for the nearest frame of the 24th minute of the movie.

**What happens instead?**

The player is fetching all segments until it finds the right position, which is good if your fast forward only some minutes ahead, but which is really bad if you want to fast forward to the 24th minute of the movie directly for example.

**Ideas**
Is there maybe a way to make Shaka packager build an approximate index of the segments for fast lookup ?

**MPD file**

	This XML file does not appear to have any style information associated with it. The document tree is shown below.
	
	<MPD xmlns="urn:mpeg:dash:schema:mpd:2011" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:cenc="urn:mpeg:cenc:2013" xsi:schemaLocation="urn:mpeg:dash:schema:mpd:2011 DASH-MPD.xsd" profiles="urn:mpeg:dash:profile:isoff-live:2011" minBufferTime="PT2S" type="static" mediaPresentationDuration="PT4657S">
	<BaseURL>***/sessions/clear/</BaseURL>
	<Period id="0">
	<AdaptationSet id="0" contentType="video" width="720" height="384" frameRate="12800/512" segmentAlignment="true" par="15:8">
	<ContentProtection value="cenc" schemeIdUri="urn:mpeg:dash:mp4protection:2011" cenc:default_KID="2276afbc-db5c-5033-a4f4-2f1200e0f2ed"/>
	<ContentProtection schemeIdUri="urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed">
	<cenc:pssh>
	XXX</cenc:pssh>
	</ContentProtection>
	<Representation id="0" bandwidth="302399" codecs="avc1.64001e" mimeType="video/mp4" sar="1:1">
	<SegmentTemplate timescale="12800" initialization="clear.mp4" media="session-$Number$.mp4" startNumber="1">
	<SegmentTimeline>
	<S t="36557824" d="25600" r="899"/>
	<S t="59597824" d="12800"/>
	</SegmentTimeline>
	</SegmentTemplate>
	</Representation>
	</AdaptationSet>
	<AdaptationSet id="1" contentType="audio" segmentAlignment="true">
	<ContentProtection value="cenc" schemeIdUri="urn:mpeg:dash:mp4protection:2011" cenc:default_KID="7212acd2-ed85-5b27-9b60-3714ffe22bd9"/>
	<ContentProtection schemeIdUri="urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed">
	<cenc:pssh>
	XXX
	</cenc:pssh>
	</ContentProtection>
	<Representation id="1" bandwidth="166282" codecs="mp4a.40.2" mimeType="audio/mp4" audioSamplingRate="48000">
	<AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="2"/>
	<SegmentTemplate timescale="48000" initialization="audio/audio.mp4" media="audio/audio-$Number$.mp4" startNumber="1">
	<SegmentTimeline>
	<S t="137068544" d="48128" r="1795"/>
	<S t="223506432" d="30720"/>
	</SegmentTimeline>
	</SegmentTemplate>
	</Representation>
	</AdaptationSet>
	</Period>
	</MPD>

**Comment by kqyang** [comment]
+ @joeyparrish

Yes, it does. That is what SegmentTimeline is used for. Do you have the packaged content hosted some where? We can try if we are able to repro your problem in our side. Alternatively, you can also provide the source content to us.

**Comment by XYG6** [comment]
The related content is copyright protected and I cannot reproduce the same error with a demo movie.

I've made sure to prepare the movie so it has the same frame size : 

	ffmpeg -y -i source.mp4 -codec:v libx264 -movflags +faststart -r 25 -g 50 -x264opts "keyint=50:min-keyint=50:no-scenecut" -c:a copy -y encoded.mp4

The generated MPD : 

	<?xml version="1.0" encoding="UTF-8"?>
	
	<MPD xmlns="urn:mpeg:dash:schema:mpd:2011" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xlink="http://www.w3.org/1999/xlink" xsi:schemaLocation="urn:mpeg:dash:schema:mpd:2011 DASH-MPD.xsd" xmlns:cenc="urn:mpeg:cenc:2013" profiles="urn:mpeg:dash:profile:isoff-live:2011" minBufferTime="PT2S" type="static" mediaPresentationDuration="PT4657.02S">
	  <BaseURL>https://xxx/sessions/segments/output.mp4</BaseURL>
	  <Period id="0">
	    <AdaptationSet id="0" contentType="video" width="720" height="384" frameRate="12800/512" segmentAlignment="true" par="15:8">
	      <ContentProtection value="cenc" schemeIdUri="urn:mpeg:dash:mp4protection:2011" cenc:default_KID="2276afbc-db5c-5033-a4f4-2f1200e0f2ed"/>
	      <ContentProtection schemeIdUri="urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed">
		<cenc:pssh>xxx</cenc:pssh>
	      </ContentProtection>
	      <Representation id="0" bandwidth="313619" codecs="avc1.64001e" mimeType="video/mp4" sar="1:1">
		<SegmentTemplate timescale="12800" initialization="output.mp4" media="/sessions/segmentsprob/seg/session-$Number$.mp4" startNumber="477">
		  <SegmentTimeline>
		    <S t="36557824" d="76800" r="299"/>
		    <S t="59597824" d="12800"/>
		  </SegmentTimeline>
		</SegmentTemplate>
	      </Representation>
	    </AdaptationSet>
	    <AdaptationSet id="1" contentType="audio" segmentAlignment="true">
	      <ContentProtection value="cenc" schemeIdUri="urn:mpeg:dash:mp4protection:2011" cenc:default_KID="7212acd2-ed85-5b27-9b60-3714ffe22bd9"/>
	      <ContentProtection schemeIdUri="urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed">
		<cenc:pssh>xxx</cenc:pssh>
	      </ContentProtection>
	      <Representation id="1" bandwidth="164853" codecs="mp4a.40.2" mimeType="audio/mp4" audioSamplingRate="48000">
		<AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="2"/>
		<SegmentTemplate timescale="48000" initialization="audio.mp4" media="/sessions/segmentsprob/audio/audio-$Number$.mp4" startNumber="569">
		  <SegmentTimeline>
		    <S t="136683520" d="240640" r="359"/>
		    <S t="223313920" d="223232"/>
		  </SegmentTimeline>
		</SegmentTemplate>
	      </Representation>
	    </AdaptationSet>
	  </Period>
	</MPD>

The startNumber="569" is way too high, so I have to set it manually to 1 so that the movie can start
or I'd get : 

    Ignoring large gap at 0

The segmentTimeline is also false, it should only contain 1 line because the framerate is the same on the whole movie.

Could this happen if the movie is too long (>1hour) ? That's the only pattern I've spotted yet.

I've also just noticed that the movie cannot play past minute 30 (media sourc error) even if the movie is 1:30 long and the packaged segments are available until segment session-777.mp4 (and it stops at session-301.mp4).

I get from the player debug : 

	(all): seeked: unbuffered seek: clearing all buffers
	streaming_engine.js:699 (audio:2) clear: handling right now
	streaming_engine.js:1983 (audio:2) clearing buffer
	streaming_engine.js:699 (video:1) clear: handling right now
	streaming_engine.js:1983 (video:1) clearing buffer
	streaming_engine.js:1991 (audio:2) cleared buffer
	streaming_engine.js:1991 (video:1) cleared buffer
	streaming_engine.js:1027 (audio:2) buffered to end of presentation
	streaming_engine.js:1027 (video:1) buffered to end of presentation

What happens there is really strange.

**Comment by kqyang** [comment]
Em... Just noticed that you are using an old version with sliding window bug - though it should not cause the problem you were seeing initially, but it is the cause for one of the behaviors you were seeing in the previous comment. Can you try [ToT](https://github.com/google/shaka-packager/commits/master) or [v1.6.2](https://github.com/google/shaka-packager/releases/tag/v1.6.2) instead?

**Comment by XYG6** [comment]
Thank you very much this solved my issues!

**Comment by kqyang** [comment]
Good to know. Thanks for the update!

**Comment by kqyang** [comment]
Mark as duplicate of https://github.com/google/shaka-packager/issues/216
