### ISSUE TITLE
Error adding sample to segment: segment too large

### ISSUE THREAD

**Issue by skstronghold** [google/shaka-packager#271]
## System info
**Operating System**: Ubuntu 14.04 trusty
**Shaka Packager Version**: bc903d2d83a69d9c1f7a7e1dc02270d85aed4495

## Issue and steps to reproduce the problem

**Packager Command**: packager --segment_duration=5 input=video_X240.webm,stream=video,output=video_X240_vid.webm --mpd_output manifest.mpd

What is the expected result? Generated MPD manifest

What happens instead? Packaging Error. 
`[0919/055413:INFO:demuxer.cc(88)] Demuxer::Run() on file 'video_X240.webm'.
[0919/055413:INFO:demuxer.cc(160)] Initialize Demuxer for file 'video_X240.webm'.
[0919/055413:ERROR:segmenter.cc(409)] Error adding sample to segment: segment too large, 34 seconds.
[0919/055413:ERROR:demuxer.cc(314)] Failed to process sample 256 11 (MUXER_FAILURE): Error adding sample to segment: segment too large
[0919/055413:ERROR:packager_main.cc(363)] Packaging Error: 8 (PARSER_FAILURE): Cannot parse media file video_X240.webm
`

All segments are of ~5 sec duration. There is no segment that is too large.

Output of `mse_json_manifest` is here - https://pastebin.com/Y8h41YmR
Output of `webm_dump` is here - https://pastebin.com/Ae4SEguw

Why is this error being thrown? Packaging works fine if I generate manifest using other tools like `webm-dash-manifest` from `ffmpeg`

**Comment by kqyang** [comment]
Thanks for reporting the problem!

There may be an overflow somewhere. From your webm_dump, the frame duration is 500ms, i.e. the frame rate is 2. The current code might have problem handling that.

Do you mind sharing your source content with us? You can email it to shaka-packager-issues@google.com. Thanks!

**Comment by skstronghold** [comment]
Its a sequence of images with audio overlay.  You can get source content from this link - https://goo.gl/jUjQae

**Comment by kqyang** [comment]
The GOP size is set to 120. `packager` by default generates GOP aligned segments, which results in segment size of 120 * 0.5, i.e. 60 seconds, which is too large (the max segment size allowed is 32 seconds). To solve your problem, you'll either need to adjust GOP size or allow segment not to be GOP aligned, i.e.

```shell
$ packager --segment_duration=5 input=video_X240.webm,stream=video,output=video_X240_vid.webm --mpd_output manifest.mpd --segment_sap_aligned=false --fragment_sap_aligned=false
```

**Comment by skstronghold** [comment]
FFmpeg is not respecting the FPS specified via `-r` parameter. So I changed video filters to `-vf fps=24,scale=-2:240` from `-vf scale=-2:240`. Doing this resolved the issue.
