### ISSUE TITLE
Playback of purchased video content through youtube in browser

### ISSUE THREAD

**Issue by pavankn** [google/shaka-packager#273]
Hello Joey Parrish , 
This is a quick question and may not be related to shaka packager . Excuses for that . 
We are not able to play purchased video through youtube app using our widevine setup on raspberry pi . The error we observe is that youtube license server doesn't respond to our CDM key request message  . 
In another scenario when we use youtube EME dash player below with a custom manifest and custom license server (which is widevine-proxy.appspot.com/proxy) , the license server responds with 200 ok and we get a license key which is further used in decrypting and it works well . 
yt-dash-mse-test.commondatastorage.googleapis.com/demo-player/dash-player-01b.html

Need your inputs on how to get youtube to get playing the purchased content . Do we need any special keys/special account to get that working ??

Pavan

**Comment by kqyang** [comment]
Hi Pavan, as you said, this is not the right place for a question like this. Please post the question in Widevine or cwip mailing list instead. Thanks.

(I assume the device make/model needs to be certified by Youtube to be able to play Youtube premium content)
