### ISSUE TITLE
ShakaPackager cannot analyse this VP9/WebM file

### ISSUE THREAD

**Issue by pscplayco** [google/shaka-packager#275]
## System info
**Operating System**: Ubuntu 14.4
**Shaka Packager Version**: packager version 65d5ecc-release

## Issue and steps to reproduce the problem

The file is located here:
http://dev-cdn-lb.parsifalentertainment.com/Tests/POWERARAOOREDOOPromo_0.5M.webm

It plays perfectly well on a Chrome browser through streaming but ShakaPackager fails to work with it:

**Packager Command**:
packager input=POWERARAOOREDOOPromo_0.5M.webm --dump_stream_info
[1005/094210:INFO:demuxer.cc(88)] Demuxer::Run() on file 'POWERARAOOREDOOPromo_0.5M.webm'.
[1005/094210:INFO:demuxer.cc(160)] Initialize Demuxer for file 'POWERARAOOREDOOPromo_0.5M.webm'.
Segmentation fault (core dumped)

I've been trying to use a SW analyser for VP9 files, but it doesn't seem to find anything strange with the file, so maybe it has to do with some limitation on Shaka? Could someone please check what the problem could be?

Thank you in advance

**Comment by kqyang** [comment]
That is a bug. Thanks for reporting the problem! We'll have a fix soon.

**Comment by kqyang** [comment]
@pscplayco This should be fixed. Let us know if you are still seeing problems.

**Comment by pscplayco** [comment]
@kqyang , thanks for helping fixing the issue. Nevertheless if I try now with the above file, I get:

packager POWERARAOOREDOOPromo_0.5M.webm --dump_stream_info
[1009/090245:ERROR:stream_descriptor.cc(81)] Invalid stream descriptors name/value pairs.

**Comment by kqyang** [comment]
You missed "input=" keyword:

```
packager input=POWERARAOOREDOOPromo_0.5M.webm --dump_stream_info
```

**Comment by pscplayco** [comment]
Oppss, sorry, and thank you, confirmed it's working fine now.
