### ISSUE TITLE
Cannot start packager when the parameter generate_dash_if_iop_compliant_mpd is added to the command line.

### ISSUE THREAD

**Issue by dario-binagora** [google/shaka-packager#277]
## System info
**Operating System**: Ubuntu 14.04.3 LTS
**Shaka Packager Version**: v1.6.1

## Issue and steps to reproduce the problem
We have been using version 1.5.1 and for a given set of media files we got a packaing output for DASH that contained one AdaptationSet elements in the MPD manifest. However, when we updated to shaka packager version 1.6.1, we started getting two AdaptationSet and the different layers were arbitrary splitted into the two sets. This caused an issue in our player, since the layers that were grouped in the second AdaptionSet were ignored. These were layers with high resolution (HD).

We found in the release notes for v1.6.1 that there was a parameter called generate_dash_if_iop_compliant_mpd and after analyzing its usage, we found out that in order to have all the layers in only one AdaptionSet we would need to set this parameter with value = "false" (or "0").

We tried adding this parameter to our command line, however when we start the packager we are getting the error "[1009/202731:ERROR:stream_descriptor.cc(87)] Invalid stream descriptors name/value pairs.". We tried setting different values and moving the parameter along the command line, but the error persists.

**Packager Command**:
/home/ubuntu/shaka-packager/src/out/Release/packager \
input=/tmp/shaka/input/L01-sd-320k.mp4,stream=video,output=/tmp/shaka/out/enc_L01-sd-320k.mp4  \
input=/tmp/shaka/input/L02-sd-560k.mp4,stream=video,output=/tmp/shaka/out/enc_L02-sd-560k.mp4  \
input=/tmp/shaka/input/L03-sd-925k.mp4,stream=video,output=/tmp/shaka/out/enc_L03-sd-925k.mp4  \
input=/tmp/shaka/input/L04-sd-1216k.mp4,stream=video,output=/tmp/shaka/out/enc_L04-sd-1216k.mp4  \
input=/tmp/shaka/input/L05-720hd-1500k.mp4,stream=video,output=/tmp/shaka/out/enc_L05-720hd-1500k.mp4  \
input=/tmp/shaka/input/L06-720hd-2000k.mp4,stream=video,output=/tmp/shaka/out/enc_L06-720hd-2000k.mp4  \
input=/tmp/shaka/input/L07-1080hd-2700k.mp4,stream=video,output=/tmp/shaka/out/enc_L07-1080hd-2700k.mp4  \
input=/tmp/shaka/input/L08-1080hd-3800k.mp4,stream=video,output=/tmp/shaka/out/enc_L08-1080hd-3800k.mp4  \
input=/tmp/shaka/input/L01-sd-320k.mp4,stream=audio,output=/tmp/shaka/out/enc_audio_L01-sd-320k.mp4  \
--key_server_url https://license.uat.widevine.com/cenc/getcontentkey/XX \
--content_id 41585F353030303dasd44af13139  \
--signer signername  \
--aes_signing_key xxxyyyyzzzxxxyyyzzz  \
--aes_signing_iv 4453434234256453453  \
--mpd_output /tmp/shaka/out/Widevine_Dash_playlist.mpd  \
--profile on-demand --enable_widevine_encryption --crypto_period_duration 0 --clear_lead 0 \
--generate_dash_if_iop_compliant_mpd 0

What is the expected result?
Packaging should start.

What happens instead?
I am getting the following error after adding the parameter "--generate_dash_if_iop_compliant_mpd 0": "[1009/202731:ERROR:stream_descriptor.cc(87)] Invalid stream descriptors name/value pairs."

Thanks in advance,
Darío

**Comment by kqyang** [comment]
Sorry for the misleading error message. `generate_dash_if_iop_compliant_mpd` is a boolean flag, please replace 

```
--generate_dash_if_iop_compliant_mpd 0
```

With

```
--generate_dash_if_iop_compliant_mpd=false
```

It should work with that. 

And to clarify what you have observed:

> However, when we updated to shaka packager version 1.6.1, we started getting two AdaptationSet and the different layers were arbitrary splitted into the two sets. This caused an issue in our player, since the layers that were grouped in the second AdaptionSet were ignored. These were layers with high resolution (HD).

We put SD and HD representations in different AdaptationSets to be compliant to [DASH-IF-IOP](http://dashif.org/wp-content/uploads/2017/09/DASH-IF-IOP-v4.1-clean.pdf) document, as SD and HD representations are encrypted with different keys. Seamless switching is enabled using Supplemental Descriptor with URI `urn:mpeg:dash:adaptation-set-switching:2016`. This is supported in exo-player and Shaka Player. We are planning to deprecate the flag `generate_dash_if_iop_compliant_mpd`. I suggest you updating your player to support this cross AdaptationSet switching mechanism.

**Comment by dario-binagora** [comment]
Thanks for your quick response kqyang. So we had two errors:
- One was that we were not using the "=" sign to assign values to parameters. We were not using it for other parameters and it was working ok. After adding the "=" sign it worked correctly.
- We were not considering the DASH-IF-IOP specification, so we need to review our player and make it compliant. For the short term, we will apply generate_dash_if_iop_compliant_mpd=false parameter.

Regards,

**Comment by kqyang** [comment]
> One was that we were not using the "=" sign to assign values to parameters. We were not using it for other parameters and it was working ok. After adding the "=" sign it worked correctly.

That is a problem with gflags boolean flag type, which, unlike other flag types, does not allow spaces. Another option would be to use `--nogenerate_dash_if_iop_compliant_mpd`, which is equivalent to `generate_dash_if_iop_compliant_mpd=false`.
