### ISSUE TITLE
DASH-Playready packaging from AcquirePackagingData

### ISSUE THREAD

**Issue by sangdonlee** [google/shaka-packager#278]
## System info
**Operating System**: Ubuntu 14.04 trusty
**Shaka Packager Version**:  c87c4c2-release

## Issue and steps to reproduce the problem

**Packager Command**:

`packager input=tears-of-steel-1.ismv,stream=video,output=tears-of-still-shaka-pr-1.mp4 --clear_lead 0 --output_media_info --profile on-demand --enable_playready_encryption  --program_identifier scalable_test_1 --playready_server_url "https://[testurl]/playready/rightsmanager.asmx?accountid=test&CrmId=test" --client_cert_file "test.cert.pem" --client_cert_private_key_file "test.key.pem"`

What is the expected result?
It should have successfully retrieved AcquirePackagingData response to an EmbeddedLicenseStore which would be used packaging the Playready media files, then also generate PSSH box to contain Playready Object Header version 4.1 while generating MPD <cenc:pssh> node. 

What happens instead?
When execute above command, the packager threw errors: 

[1011/090245:ERROR:http_key_fetcher.cc(162)] curl_easy_perform() failed: Failure when receiving data from the peer.
[1011/090245:ERROR:playready_key_source.cc(298)] Server response:
[1011/090245:INFO:demuxer.cc(88)] Demuxer::Run() on file 'tears-of-steel-1.ismv'.
[1011/090245:INFO:demuxer.cc(160)] Initialize Demuxer for file 'tears-of-steel-1.ismv'.
[1011/090245:ERROR:aes_encryptor.cc(42)] Invalid AES key size: 0
[1011/090245:ERROR:mp4_media_parser.cc(763)] Failed to process the sample.
[1011/090245:ERROR:packager_main.cc(363)] Packaging Error: 9 (ENCRYPTION_FAILURE): Failed to create encryptor

OR, 
Is there any other manual workaround?

tcpdump shows the SSL session is successful. 
![image](https://user-images.githubusercontent.com/5633234/31431418-5d98338e-aebf-11e7-9f34-2a01c2835dbe.png)

**Comment by kqyang** [comment]
I don't see client cert private key password provided in the command line. Can you provide the password (--client_cert_private_key_password)?

There is really not much things we can if it still does not work as the error came from curl directly. I'd suggest using curl command line tool directly to post to the playready server to see if it is possible to make it work.

```
curl -H "Content-Type: text/xml" -H "SOAPAction:http://schemas.microsoft.com/DRM/2007/03/protocols/AcquirePackagingData" -X POST -d '<?xml version="1.0" encoding="UTF-8"?><soap:Envelope xmlns="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><soap:Body><AcquirePackagingData xmlns="http://schemas.microsoft.com/DRM/2007/03/protocols"><challenge xmlns="http://schemas.microsoft.com/DRM/2007/03/protocols/AcquirePackagingData/v1.0"><ProtectionSystems><ProtectionSystemId>9A04F079-9840-4286-AB92-E65BE0885F95</ProtectionSystemId></ProtectionSystems><StreamProtectionRequests><StreamInformation><ProgramIdentifier>scalable_test_1</ProgramIdentifier><OffsetFromProgramStart>P0S</OffsetFromProgramStart></StreamInformation></StreamProtectionRequests></challenge></AcquirePackagingData></soap:Body></soap:Envelope>' "https://[testurl]/playready/rightsmanager.asmx?accountid=test&CrmId=test" ...
```

**Comment by sangdonlee** [comment]
Thanks for your reply. 

The private key pem file isn't password protected, so I didn't pass that in. But also tried with -client_cert_private_key_password "something" to make the code happy - no luck. 

I tested CURL below and returning the API response successfully. 


`curl -H "Content-Type: text/xml"  -X POST --data @body.xml "https://[testurl]/playready/rightsmanager.asmx?accountid=test&CrmId=test" -E "test.cert.pem"  --key "test.key.pem" -v `

* Hostname was NOT found in DNS cache
*   Trying x.y.y.y...
* Connected to ???.com (x.y.y.y) port 443 (#0)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
* SSLv3, TLS handshake, Server hello (2):
* SSLv3, TLS handshake, CERT (11):
* SSLv3, TLS handshake, Server key exchange (12):
* SSLv3, TLS handshake, Server finished (14):
* SSLv3, TLS handshake, Client key exchange (16):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSL connection using ECDHE-RSA-AES256-SHA384
* Server certificate:
* 	 subject: C=??; ST=??? ???; L=Hoofddorp; O=??? B.V; CN=*.???
* 	 start date: 2015-11-10 00:00:00 GMT
* 	 expire date: 2017-11-09 23:59:59 GMT
* 	 subjectAltName: test.com matched
* 	 issuer: C=US; O=GeoTrust Inc.; CN=GeoTrust SSL CA - G3
* 	 SSL certificate verify ok.
> POST /playready/rightsmanager.asmx?accountid=comcast&CrmId=MAN HTTP/1.1
> User-Agent: curl/7.35.0
> Host: ???.com
> Accept: */*
> Content-Type: text/xml
> Content-Length: 822
>
* upload completely sent off: 822 out of 822 bytes
* SSLv3, TLS handshake, Hello request (0):
* SSLv3, TLS handshake, Client hello (1):
* SSLv3, TLS handshake, Server hello (2):
* SSLv3, TLS handshake, CERT (11):
* SSLv3, TLS handshake, Server key exchange (12):
* SSLv3, TLS handshake, Request CERT (13):
* SSLv3, TLS handshake, Server finished (14):
* SSLv3, TLS handshake, CERT (11):
* SSLv3, TLS handshake, Client key exchange (16):
* SSLv3, TLS handshake, CERT verify (15):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
< HTTP/1.1 200 OK
< Cache-Control: private, max-age=0
< Content-Type: text/xml; charset=utf-8
* Server Microsoft-IIS/8.5 is not blacklisted
< Server: Microsoft-IIS/8.5
< X-AspNet-Version: 4.0.30319
< X-Powered-By: ASP.NET
< Access-Control-Allow-Method: POST,GET
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Headers: content-type, soapaction, Range
< Date: Wed, 11 Oct 2017 21:06:20 GMT
< Content-Length: 5090
<
<?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><soap:Body><AcquirePackagingDataResponse xmlns="http://schemas.microsoft.com/DRM/2007/03/protocols"><AcquirePackagingDataResult xmlns="http://schemas.microsoft.com/DRM/2007/03/protocols/AcquirePackagingData/v1.0"><StreamProtectionResponses><StreamProtectionInformation><StreamInformation><ProgramIdentifier>scalable_test_1</ProgramIdentifier><OffsetFromProgramStart>P0S</OffsetFromProgramStart></StreamInformation><KeyRotationOffsetFromProgramStart>-P0Y0M0DT0H0M0S</KeyRotationOffsetFromProgramStart><EncryptionType>Aes128Bit</EncryptionType><KeyId>45d07126-95e4-4c8b-b359-a00fda9979f4</KeyId><KeyData> **removed** </AcquirePackagingDataResult></AcquirePackagingDataResponse></soap:Body></soap:Envelope>

**Comment by kqyang** [comment]
I have an idea of what is going on. We assumed all private key was password protected, which is not true in your case. I have a quick patch, which should address your problem. Can you try applying the below patch and let me know if it solves your problem?

[0001-Playready-Allow-unencrypted-client-cert-private-key.patch.txt](https://github.com/google/shaka-packager/files/1377273/0001-Playready-Allow-unencrypted-client-cert-private-key.patch.txt)

**Comment by sangdonlee** [comment]
I have applied the patch and re-run, unfortunately doesn't work still returning the same error.
Looking at the tcpdump for the SSL connection, it appears very normal it follows the handshake process correctly.

WARNING: profile is deprecated and ignored.
WARNING: profile is deprecated and ignored.
[1011/235301:ERROR:http_key_fetcher.cc(162)] curl_easy_perform() failed: Failure when receiving data from the peer.
[1011/235301:ERROR:playready_key_source.cc(298)] Server response:
[1011/235301:INFO:demuxer.cc(88)] Demuxer::Run() on file 'tears-of-steel-1.ismv'.
[1011/235301:INFO:demuxer.cc(160)] Initialize Demuxer for file 'tears-of-steel-1.ismv'.
[1011/235301:ERROR:aes_encryptor.cc(42)] Invalid AES key size: 0
[1011/235301:ERROR:mp4_media_parser.cc(763)] Failed to process the sample.
[1011/235301:ERROR:packager_main.cc(363)] Packaging Error: 9 (ENCRYPTION_FAILURE): Failed to create encryptor

So, I assume the playready server return none 20x response due to below. 
- Wrong format of SOAP body (this would return 500)
- content-type header (this would return 415)

**Comment by sangdonlee** [comment]
A note here this maybe an issue. 
DNS resolves my FQDN to two IP addresses 

In manual curl command, this is working. 
Hostname was NOT found in DNS cache
* Trying x.x.x.x...
* Connected to testurl.com (y.y.y.y) port 443 (#0)

When packager opens SSL, it is still trying to open SSL using the IP of x.x.x.x rather than y.y.y.y 
then ended up getting and alert, observing in tcpdump (which is in my first comment above)

![image](https://user-images.githubusercontent.com/5633234/31473505-ad7a2c46-af40-11e7-90bd-428739fe4bc4.png)

**Comment by sangdonlee** [comment]
Applied the patch but, still getting the same error.

The SSL stops at Encrypt Alert, it seems that private key isn't loaded, but the cert was good. 
Secure Sockets Layer
TLSv1.2 Record Layer: Encrypted Alert
Version: TLS 1.2 (0x0303)
Length: 80
Alert Message: Encrypted Alert

**Comment by kqyang** [comment]
Can I access your playready test server from my end? I'll happy to debug it from my end if it is doable. You can send the certificates to my email listed in CONTRIBUTORS file.

If not, try updating the CURL options in https://github.com/google/shaka-packager/blob/master/packager/media/base/http_key_fetcher.cc#L100 to match the curl command line you used. It is possible that your server does not like one of the options.

You may also use Wireshark to analyze network traces, which could be helpful to understand what is going on.

**Comment by sangdonlee** [comment]
Unfortunately, I cannot provide the certs at the test server owned by someone else. I did some workaround bypassing SSL comms to make a success call using packager options - Download the soap AcquireResponseData from Playready server using manual crul and load that onto my web server(non SSL), then the packaging against that - this works and packaging it successfully. 
However, I will need to ensure the content is playing back - the pssh box doesn't look like correct after mpd_generate. 

For instance: 
          <cenc:pssh>AAABRnBzc2gAAAAAmgTweZhAQoarkuZb4IhflQAAASYmAQAAAQADABwBRVNUAAABAAEAAAEcAAABDiZx0EXklYtMs1mgD9qZefT0eA7MUThQSpl+lvmoGflDAAAAAFhNUgAAAAAD9HgOzFE4UEqZfpb5qBn5QwADAAEAAADOAAIABAAAAAgAAwACAAAANAAAABMAAAAMWd7kcAABADIAAAAMAAAAAAABADQAAAAKAAAAAAAzAAAACgACAAMACQAAAG4AAQAKAAAAPiZx0EXklYtMs1mgD9qZefQAAQACACDaa33tB+LkYi1CBN0H6xZu0wlAPyn4rCLTptNTN0TEnQABAFIAAAAo4anTT3b02UaqE6DvpNodCgAIICsFLWpzjT4AAQAAABEAAQALAAAAHAABABBMTMkQMOJCEe8hLt5kviR7AAA=</cenc:pssh>
This appears not presenting WRMHEADER 4.1.0.0

I will try your curl patch soon and let you know. Thanks heaps.

**Comment by yohanncon** [comment]
Hi sangdonlee, it looks like the PlayReady Packager, AcquirePackagingData soap service, created a pssh with only an embedded license store.  To include the WRMHEADER information the Packager should also include a rights management header, PlayReadyHeader object.

**Comment by sangdonlee** [comment]
Hi yohanncon, Thanks for your reply. 
Did you have a sample response xml from AcquirePackagingData? Also a sample for the pssh box in the mpd manifest with PlayReadyHeader version 4.1.0.0? Thanks.

**Comment by yohanncon** [comment]
Sample AcquirePackagingData response.  The Data element contains the pssh box.

<?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><soap:Body><AcquirePackagingDataResponse xmlns="http://schemas.microsoft.com/DRM/2007/03/protocols"><AcquirePackagingDataResult xmlns="http://schemas.microsoft.com/DRM/2007/03/protocols/AcquirePackagingData/v1.0"><StreamProtectionResponses><StreamProtectionInformation><StreamInformation><ProgramIdentifier>sample</ProgramIdentifier><OffsetFromProgramStart>P0S</OffsetFromProgramStart></StreamInformation><EncryptionType>Aes128Bit</EncryptionType><KeyId>f7db4e02-4446-588b-90f1-91b486df7045</KeyId><KeyData>eKHcBkYRlwfpA1FNigBzXw==</KeyData><ProtectionSystemSpecificHeaderBoxes><ProtectionSystemSpecificHeaderBoxContents><ProtectionSystemId>9A04F079-9840-4286-AB92-E65BE0885F95</ProtectionSystemId><Data>WgQAAAIAAwAcAUVTVAAAAQABAAABHAAAAQ4CT9vXRmWLWJDxkbSGq3BFaCZQZg38qEmie9S7aTHUNgAAAABYTVIAAAAAA2gmUGYN/KhJonvUu2kx1DYAAwABAAAAzgACAAQAAAAIAAMAAgAAADQAAAATAAAADFno1xQAAQAyAAAADAAAAAAAAQA0AAAACgfQAAAAMwAAAAoAAgADAAkAAABuAAEACgAAAD4CT9vXRmWLWJDxkbSGq3BFAAEAAgAgFPYowZ6CwMrjyfXItaS1KdGR0gupZFzNP5lA/kGNlhsAAQBSAAAAKAJP29dGZYtYkPGRtIarcEUACHl3ckg60E0CAAEAAAABAAEACwAAABwAAQAQgT6Fac1Juy3+7bEw3X3oDAAAAQAwAzwAVwBSAE0ASABFAEEARABFAFIAIAB4AG0AbABuAHMAPQAiAGgAdAB0AHAAOgAvAC8AcwBjAGgAZQBtAGEAcwAuAG0AaQBjAHIAbwBzAG8AZgB0AC4AYwBvAG0ALwBEAFIATQAvADIAMAAwADcALwAwADMALwBQAGwAYQB5AFIAZQBhAGQAeQBIAGUAYQBkAGUAcgAiACAAdgBlAHIAcwBpAG8AbgA9ACIANAAuADEALgAwAC4AMAAiAD4APABEAEEAVABBAD4APABQAFIATwBUAEUAQwBUAEkATgBGAE8APgA8AEsASQBEACAAQQBMAEcASQBEAD0AIgBBAEUAUwBDAFQAUgAiACAAQwBIAEUAQwBLAFMAVQBNAD0AIgBlAFgAZAB5AFMARAByAFEAVABRAEkAPQAiACAAVgBBAEwAVQBFAD0AIgBBAGsALwBiADEAMABaAGwAaQAxAGkAUQA4AFoARwAwAGgAcQB0AHcAUgBRAD0APQAiAD4APAAvAEsASQBEAD4APAAvAFAAUgBPAFQARQBDAFQASQBOAEYATwA+ADwAQwBVAFMAVABPAE0AQQBUAFQAUgBJAEIAVQBUAEUAUwAgAHgAbQBsAG4AcwA9ACIAIgA+ADwAUwBUAFIARQBBAE0ASQBEAD4AZQB5AEoAdwBjAG0AOQAyAGEAVwBSAGwAYwBpAEkANgBJAG4AZABwAFoARwBWADIAYQBXADUAbABYADMAUgBsAGMAMwBRAGkATABDAEoAbgBjAG0AOQAxAGMARgA5AHAAWgBDAEkANgBJAG4AZABwAFoARwBWADIAYQBXADUAbABYADMAUgBsAGMAMwBRAGkATABDAEoAegBaAFgASgAyAGEAVwBOAGwAWAAyAGwAawBJAGoAbwBpAGQAMgBsAGsAWgBYAFoAcABiAG0AVgBmAGQARwBWAHoAZABDAEoAOQA8AC8AUwBUAFIARQBBAE0ASQBEAD4APAAvAEMAVQBTAFQATwBNAEEAVABUAFIASQBCAFUAVABFAFMAPgA8AC8ARABBAFQAQQA+ADwALwBXAFIATQBIAEUAQQBEAEUAUgA+AA==</Data></ProtectionSystemSpecificHeaderBoxContents></ProtectionSystemSpecificHeaderBoxes></StreamProtectionInformation></StreamProtectionResponses></AcquirePackagingDataResult></AcquirePackagingDataResponse></soap:Body></soap:Envelope>

**Comment by hieuletrung** [comment]
I'm trying to make a CURL to PlayReady test server
`curl -H "Content-Type: text/xml" -H "SOAPAction:http://schemas.microsoft.com/DRM/2007/03/protocols/AcquirePackagingData" -X POST -d '<?xml version="1.0" encoding="UTF-8"?><soap:Envelope xmlns="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><soap:Body><AcquirePackagingData xmlns="http://schemas.microsoft.com/DRM/2007/03/protocols"><challenge xmlns="http://schemas.microsoft.com/DRM/2007/03/protocols/AcquirePackagingData/v1.0"><ProtectionSystems><ProtectionSystemId>9A04F079-9840-4286-AB92-E65BE0885F95</ProtectionSystemId></ProtectionSystems><StreamProtectionRequests><StreamInformation><ProgramIdentifier>scalable_test_1</ProgramIdentifier><OffsetFromProgramStart>P0S</OffsetFromProgramStart></StreamInformation></StreamProtectionRequests></challenge></AcquirePackagingData></soap:Body></soap:Envelope>' "http://playready-testserver.azurewebsites.net/rightsmanager.asmx"`

But it always fail with error 500: internal server error
`<?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><soap:Body><soap:Fault><faultcode>soap:Server</faultcode><faultstring>System.Web.Services.Protocols.SoapException: Internal service error
   at Microsoft.Media.Drm.RightsManager.ConvertRmServerException(RMServerException ex)
   at Microsoft.Media.Drm.RightsManager.AcquirePackagingData(PackagingChallenge challenge)</faultstring><faultactor>http://playready-testserver.azurewebsites.net/rightsmanager.asmx</faultactor><detail><Exception><StatusCode>0x8004c600</StatusCode><DebuggingData>Server record locator = 596082f3-4d3c-466d-bb24-66a3f24329cb</DebuggingData></Exception></detail></soap:Fault></soap:Body></soap:Envelope>`

Is there anything wrong with my command?

**Comment by yohanncon** [comment]
Hi hieuletrung, the server returned an internal error.  Which means, you need access to the server to get the full message.  Do you know if this server supports Packaging?

**Comment by hieuletrung** [comment]
@yohanncon , not sure since I'm using the Microsoft Test PlayReady server here http://test.playready.microsoft.com/

**Comment by kqyang** [comment]
@sangdonlee @hieuletrung Is there any update? Do you still need help on this issue?
