### ISSUE TITLE
Support for Dolby EAC3 in MPEG2-TS

### ISSUE THREAD

**Issue by kqyang** [google/shaka-packager#279]
This is split from #165.

**Comment by zshenker** [comment]
@kqyang What is involved in supporting E-AC3 in addition to AC3?

**Comment by kqyang** [comment]
It is just some extra work for SAMPLE-AES support (https://developer.apple.com/library/content/documentation/AudioVideo/Conceptual/HLS_Sample_Encryption/Encryption/Encryption.html#//apple_ref/doc/uid/TP40012862-CH2-SW22).

For AC3 setup, it is straight forward, for E-AC3, need some additional parsing to generate EC3SpecificBox content. I don't expect it to be complicated, but will involves one or two days of extra work.

**Comment by zshenker** [comment]
In case it helps, code from Bento4 that parses the dec3 atoms, https://github.com/axiomatic-systems/Bento4/blob/master/Source/C++/Core/Ap4Dec3Atom.cpp

**Comment by kqyang** [comment]
What we need is a dec3 generator instead of a dec3 parser (generates dec3 from e-ac3 bitstream). Thanks though.

**Comment by zshenker** [comment]
@kqyang Is this work completed now or is there still more to do on this?

**Comment by kqyang** [comment]
The ec3 in TS generation work is done but the parsing work is not, i.e. you can do: mp4 (with ec3) to ts (with ec3), but not: ts (with ec3) to mp4 (with ec3).

**Comment by cgp1081** [comment]
We're unable to get E-AC3 playback with Shaka packaged Fairplay content.  The same content works when packaged with other tools.
Shaka:
https://cbsentallaccess.akamaized.net/intl_vms/2018/01/18/1139892803890/1306845_fp_hls/master_shaka.m3u8

Bento4:
https://cbsentallaccess.akamaized.net/intl_vms/2018/01/18/1139892803888/1306810_fp_hls/master_bento.m3u8

**Comment by cgp1081** [comment]
AC3 and AAC work as expected

**Comment by jigneshdhruv** [comment]
E-AC3 does work with clear HLS. It is not working with Fairplay DRM.

**Comment by kqyang** [comment]
@jigneshdhruv @cgp1081 We have a fix. It should be pushed some time this week.

**Comment by kqyang** [comment]
@jigneshdhruv @cgp1081 The fix has been pushed. Please verify.
