### ISSUE TITLE
Colour info leads to the failure of shaka-packaging

### ISSUE THREAD

**Issue by pickn6** [google/shaka-packager#284]
## System info
**Operating System**: macOS Sierra
**Shaka Packager Version**: v1.6.1

## Issue and steps to reproduce the problem
with ffmpeg 3.4, generate a webm file: 
ffmpeg -i <input.mp4> -an -c:v libvpx-vp9 -pix_fmt yuv420p -aq-mode 1 -auto-alt-ref 1 -lag-in-frames 16 -static-thresh 0 -arnr-maxframes 7 -arnr-strength 5 -arnr-type 3 -b:v 1M -speed 4 -g 60 test.webm

This test.webm contains the colour info under Track as
      Colour:
        ChromaSitingHorz        : 1
        ChromaSitingVert        : 2
        Range                   : 1

test.webm can be decoded w/o any issue. However, it fails the packager with the command below:

**Packager Command**:
packager in=test.webm,stream=video,output=out.webm --mpd_output vod.mpd -fragment_duration 2 -segment_duration 8

What is the expected result?
the webm output should be packaged.

What happens instead?
packager failure with error.

<Please attach the input files or email to shaka-packager-issues@google.com.>
<Please provide any additional information below.>

**Comment by kqyang** [comment]
I think this is a duplicate of #275. Can you try if using latest commit fix your problem?

**Comment by pickn6** [comment]
Verified against 72df5af150afb16e0d389f848865980458d668f7. Closing.
