### ISSUE TITLE
Support iframe playlist in HLS

### ISSUE THREAD

**Issue by kqyang** [google/shaka-packager#287]
https://tools.ietf.org/html/draft-pantos-http-live-streaming-23#section-4.3.3.6
https://developer.apple.com/library/content/technotes/tn2288/_index.html#//apple_ref/doc/uid/DTS40012238-CH1-I_FRAME_PLAYLIST

**Comment by jigneshdhruv** [comment]
What is the status for this enhancement request?

**Comment by kqyang** [comment]
No updates yet. We will be looking into it in next few weeks.
