### ISSUE TITLE
Long timeshift issue, too many files created

### ISSUE THREAD

**Issue by jakubvojacek** [google/shaka-packager#288]
## System info
Debian 9
packager version e889578a2d-release

## Issue and steps to reproduce the problem

`/usr/bin/packager in=udp://239.100.0.2:1000?interface=192.168.4.48&reuse=1,stream=audio,init_segment=channel-hd-59e865873a0e5_audio.mp4,segment_template=audio_channel-hd-59e865873a0e5-$Number$.mp4 in=udp://239.100.0.2:1000?interface=192.168.4.48&reuse=1,stream=video,init_segment=channel-hd-59e865873a0e5_video_576.mp4,segment_template=video_576_channel-hd-59e865873a0e5-$Number$.mp4 in=udp://239.100.0.2:1001?interface=192.168.4.48&reuse=1,stream=video,init_segment=channel-hd-59e865873a0e5_video_288.mp4,segment_template=video_288_channel-hd-59e865873a0e5-$Number$.mp4 --time_shift_buffer_depth 259200 --mpd_output channel-hd-59e865873a0e5.mpd --hls_playlist_type LIVE --hls_master_playlist_output channel-hd-59e865873a0e5.m3u8`

## What is the expected result?

Dash and HLS get created.

## What happens instead?

Too many files that the filesystem cannot handle, is there a way to use a directory structure to improve filesystem performance or is there some other recommended way to achieve this?

**Comment by kqyang** [comment]
Can you describe in more detail what performance issue you are seeing? 

You can put different representations in different directories, i.e.

> ...stream=audio,init_segment=audio/channel-hd-59e865873a0e5.mp4,segment_template=audio/channel-hd-59e865873a0e5-$Number$.mp4...stream=video,init_segment=video_288/channel-hd-59e865873a0e5.mp4,segment_template=video_288/channel-hd-59e865873a0e5-$Number$.mp4...

A buffer depth of 259200 is really big so I am not sure if this can help much.

There may be space for optimization in DASH MPD generation and HLS playlist generation code as well. Are you seeing differences if you enable DASH output or HLS output only?

Also, what filesystem are you using? You may want to try with a more efficient file system.

**Comment by jakubvojacek** [comment]
We're using ext4 FS. The number of files is in hundreds of thousands so that's far from optimal. I was hoping that there would be an option to dynamically distribute files to subfolders, something like current day/current hour (`date +"%a/%H"`) as name of the folder or somehow force the packager to use much bigger files (like one file per 15 minutes) without affecting broadcast delay.

Any thoughts about this?

**Comment by jakubvojacek** [comment]
Just discovered it's possible to format `$Number$` variable like `$Number%05d$`. Would be nice to do `$Number%.3s$` as that would solve my problem. Is there anything like that supported?

**Comment by rkuroiwa** [comment]
I can't really think of a great solution for this problem.

If we supported SegmentList, then we could solve this issue by allowing segments in different directories every e.g. 1000 segments.
But since the time_shift_buffer_depth is so big, there will be e.g. 25920 entries per Representation. Gzipping might help but probably not optimal.

Another thing we could do is Period support. But IIRC, the spec nor DASH IOP mention how to do smooth switching among Periods.

To answer your question about `%.3s` formatting, since the MPD spec doesn't allow that, players won't understand it. Also IIUC, that would overwrite the files.

**Comment by jakubvojacek** [comment]
Thank you for the feedback, we will try to think of solution.
