### ISSUE TITLE
NPM module and the license

### ISSUE THREAD

**Issue by nampdn** [google/shaka-packager#290]
Hi, can I build the npm module with the pre-built binaries file under name of `shaka-packager` with the current licensing?

**Comment by vaage** [comment]
@kqyang This is a software licensing question. I do not feel comfortable answering this. Do you know who would be confident answering this question?

**Comment by nampdn** [comment]
The only I want to do is wrap shaka-player pre-built binaries with NodeJS AP for easy usage in Node server.

**Comment by vaage** [comment]
@nampdn We can checking with out open source legal team to get you the most accurate answer possible. Once we hear back from them, we will let you know more.

**Comment by nampdn** [comment]
Thank you @vaage! I'm waiting on it.

**Comment by kqyang** [comment]
@nampdn We talked to our legal team. We can add npm release to our release process, so every time we have a new release on Github (https://github.com/google/shaka-packager/releases), we will release the prebuilt binaries to npm at the same time with the same version number. This makes sure they are always in sync.

We notice that you already set up a dummy shaka-packager project on npmjs: https://www.npmjs.com/package/shaka-packager. Can you transfer the ownership back to us? That is required for the release (we can only push to a npm project we own).

This should meet your needs. If there is anything else you want for npm, let us know. We will be happy to review and accommodate.

Does that sound good to you?

**Comment by nampdn** [comment]
@kqyang Thank you and your legal so much. I bet it always better than me to do a side wrapper for this.
Can you tell me your team npm user so that I can transfer the ownership?

**Comment by kqyang** [comment]
@nampdn Thanks. You can transfer it to me first and I'll take care of the rest. My npm user name is the same as my Github user name: kqyang.

**Comment by nampdn** [comment]
@kqyang I added you to the package, do I need to do anything else?

**Comment by kqyang** [comment]
@nampdn Thanks. We'll also need you to remove yourself from the package's owners. I hope you don't mind.

**Comment by nampdn** [comment]
Nevermind, I did it.
Can I know your plan when the npm package will be available for production use?

**Comment by kqyang** [comment]
Thanks @nampdn! I am planning to push it tomorrow, after verifying everything works as expected.

**Comment by nampdn** [comment]
Woot! Can't wait for it.

**Comment by kqyang** [comment]
@nampdn Just realized that we'll need to go through extra open source reviews for npm release. Will let you know once it is pushed to npm registry.

**Comment by nampdn** [comment]
It's ok @kqyang, thank you!
