### ISSUE TITLE
gcc-5-glibc-2.23 build fails because of -Werror=unused-variable

### ISSUE THREAD

**Issue by roticv** [google/shaka-packager#293]
## System info
**Operating System**: Centos 7/Linux 4.6
**Shaka Packager Version**: git rev 622ff64595ec9d5f92f1e8e992fb6019567dbc68

## Issue and steps to reproduce the problem

**Packager Command**:
Tried to build with gcc5-glibc-2.23 and ended up with a lot of errors due to unused variables and since the flag was to upgrade warnings as errors, the compilation wasn't complete. This works on gcc4.9

**Comment by kqyang** [comment]
Thanks for reporting the issue. We'll look into it.

**Comment by roticv** [comment]
I added the flag '-Wno-error' and builds nicely for me

**Comment by kqyang** [comment]
Related to #286. Both are fixed.
