### ISSUE TITLE
Always zero earliest_presentation_time in SIDX doesn't make sense

### ISSUE THREAD

**Issue by pudding8757** [google/shaka-packager#303]
## System info
**Operating System**: Ubuntu 16.04
**Shaka Packager Version**: b3194866a6a7ba80aace681e6cd8d874f2e3d518

## Issue and steps to reproduce the problem
I generated a TS file using GStreamer and then, the resulting mp4 file's SIDX box did not
reflect actual the earliest presentation time (It always set to zero from the commit 3e6190ec2bd3598d217631140f76d06f6136a0ae).

**Packager Command**:
shaka-packager  input=myinput.ts,stream=video,output=myoutput.mp4

Extra steps to reproduce the problem?
(1)
(2)

What is the expected result?
ISOBMFF spec is saying that the "earliest_presentation_time" is the earliest presentation time of any content in the reference stream in the first subsegment. So it shouldn't be zero in some cases.

What happens instead?
The first subsegment's tfdt is saying that is non-zero but earliest_presentation_time in SIDX is zero.
It's inconsistent.

<Please attach the input files or email to shaka-packager-issues@google.com.>
<Please provide any additional information below.>

**Comment by kqyang** [comment]
I don't remember the exact history, but I believe it is there to workaround playback problems. The fix is easy, but we'll need to evaluate if it would break playbacks.

**Comment by kqyang** [comment]
@pudding8757 Do you have a sample content we can test with?

**Comment by pudding8757** [comment]
@kqyang  Sure! It's available at https://github.com/pudding8757/test-contents/blob/master/nonzero_start_pts.ts

**Comment by kqyang** [comment]
Chrome still does not support negative DTS, so we'll need to be careful with PTS adjustment. https://bugs.chromium.org/p/chromium/issues/detail?id=398141 (marked as fixed but not enabled by default).

Moving to milestone 2.1.0 as it is more difficult than previously thought.

**Comment by kqyang** [comment]
Cherry-picked for v2.0.3.
