### ISSUE TITLE
Cosmetic issue with raw key page of docs

### ISSUE THREAD

**Issue by jmcsagdc** [google/shaka-packager#309]
In description of test vectors for the tutorial:

https://google.github.io/shaka-packager/html/tutorials/raw_key.html

The docs here use a different text box which has no scrollbar and is not bound by the dimensions of the page. See screen shot.

![raw-key2017-12-19](https://user-images.githubusercontent.com/15971368/34171447-30e636c8-e4a3-11e7-88cc-abaf3ec13d2a.png)

**Comment by kqyang** [comment]
Yah, it does not look nice. It is partially the restriction of sphinx doc generator and HTML table. It is possible to workaround the problem by forcing fix-layout table, but then the table won't look nice. 

I'll close the issue for now.

Let us know if you have any suggestions on how to solve the problem and feel free to re-open it. Thanks.
