### ISSUE TITLE
How to add UTCTiming to dash mpd?

### ISSUE THREAD

**Issue by jakubvojacek** [google/shaka-packager#311]
## System info
**Operating System**: Debian latest
**Shaka Packager Version**: 1.6.2 (latest)

## Issue and steps to reproduce the problem

We are trying to create dash via shaka packager but we are unable to add the UTCTiming element into the generated mpd. Is there any parameter in which we could tell shaka packager the address of our time server (something like https://github.com/google/shaka-player/issues/386#issuecomment-227898001).

I tried googling for UTCTiming element and shaka package but was unable to find anything. 

Thank you

**Comment by kqyang** [comment]
Thanks for bringing up the feature. It is not supported right now. We'll be happy to add the feature.
