### ISSUE TITLE
HEVCDecoderConfigurationRecord gives incorrect codec string when NAL units have emulation_prevention_three_byte

### ISSUE THREAD

**Issue by l-law** [google/shaka-packager#312]
## System info
**Operating System**: Ubuntu 16.04
**Shaka Packager Version**: 22c758ed069a6e626204f11b00faa1cc7f7f3164

## Issue and steps to reproduce the problem
Use EsParserH265 to parse HEVC ES (extracted from TS packets).
Check codec_string() from VideoStreamInfo from NewStreamInfoCB.
The output codec string is wrong and seems it didn't handle emulation_prevention_three_byte (0x000003).

What is the expected result?
Give me a correct codec string, eg. hev1.1.6.L150.90

What happens instead?
It gave me hev1.1.C0000006.L0.0.90.0.0.3
0xC is exactly the inversion of 0x3.
Profile became L0 because it read the wrong byte.
And there was one extra 0x3 in the end.

<Please attach the input files or email to shaka-packager-issues@google.com.>
<Please provide any additional information below.>

Attached VPS for reference.
![vps_capture](https://user-images.githubusercontent.com/19425074/34508496-024c8612-f07b-11e7-9574-ed5691a2b01f.png)

**Comment by kqyang** [comment]
Good catch! The problem comes from the incorrect handling in https://github.com/google/shaka-packager/blob/master/packager/media/codecs/h265_byte_to_unit_stream_converter.cc#L56, where we shouldn't just copy the data without escaping it first. Do you have a sample input we can use for verification after the fix?

**Comment by l-law** [comment]
What kind of sample input is needed? I can prepare a few H265 packets in binary, is this enough for the verification?

**Comment by kqyang** [comment]
@l-law Preferably H265 packets packaged in TS. I already have a fix available. I'll push it some time this week. It also works for us if you can verify after it is pushed.

**Comment by kqyang** [comment]
@l-law The fix is just pushed. Let us know the results when you have a chance to test. Thanks.

**Comment by l-law** [comment]
Sorry for late reply. I have updated my copy to include the fix and it worked, codec string for H265 is the same as I expected.
