### ISSUE TITLE
Incorrect CHANNELS reported in HLS Manifest for EC3 and AC3 Audio

### ISSUE THREAD

**Issue by jigneshdhruv** [google/shaka-packager#313]
## System info
**Operating System**: Ubuntu 16.04
**Shaka Packager Version**: 66f713f-release

## Issue and steps to reproduce the problem
We are passing 3 audio mp4 files(2-channel AAC, 5.1 Channel EC3 and AC3) along with several video mp4's to Shaka Packager. Shaka packager is successfully able to create the master manifest files but it reports CHANNELS for all the 3 MP4 files as '2' instead of '6' for ec-3 and ac-3 audio.

**Packager Command**:
Edited command to remove full paths.
packager 'in=AES_5_1_Test_TestVideo_20M_1295280_128.mp4,stream=audio,segment_template=AES_5_1_Test_TestVideo_20M_1295280_128/seg_$Number$.ts,playlist_name=AES_5_1_Test_TestVideo_20M_1295280_128/stream.m3u8,hls_group_id=AES_5_1_Test_TestVideo_20M_1295280_128,hls_name=ENGLISH' 'in=AES_5_1_Test_TestVideo_20M_1295280_192.mp4,stream=audio,segment_template=AES_5_1_Test_TestVideo_20M_1295280_192/seg_$Number$.ts,playlist_name=AES_5_1_Test_TestVideo_20M_1295280_192/stream.m3u8,hls_group_id=AES_5_1_Test_TestVideo_20M_1295280_192,hls_name=ENGLISH' 'in=AES_5_1_Test_TestVideo_20M_1295280_384.mp4,stream=audio,segment_template=AES_5_1_Test_TestVideo_20M_1295280_384/seg_$Number$.ts,playlist_name=AES_5_1_Test_TestVideo_20M_1295280_384/stream.m3u8,hls_group_id=AES_5_1_Test_TestVideo_20M_1295280_384,hls_name=ENGLISH' 'in=AES_5_1_Test_TestVideo_20M_1295280_375.mp4,stream=video,segment_template=AES_5_1_Test_TestVideo_20M_1295280_375/seg_$Number$.ts,playlist_name=AES_5_1_Test_TestVideo_20M_1295280_375/stream.m3u8' 'in=AES_5_1_Test_TestVideo_20M_1295280_750.mp4,stream=video,segment_template=AES_5_1_Test_TestVideo_20M_1295280_750/seg_$Number$.ts,playlist_name=AES_5_1_Test_TestVideo_20M_1295280_750/stream.m3u8' 'in=AES_5_1_Test_TestVideo_20M_1295280_1500.mp4,stream=video,segment_template=AES_5_1_Test_TestVideo_20M_1295280_1500/seg_$Number$.ts,playlist_name=AES_5_1_Test_TestVideo_20M_1295280_1500/stream.m3u8' --clear_lead 0 --segment_duration 6 --hls_master_playlist_output 1295281_fp_hls/master.m3u8

What is the expected result?
For EC-3 and AC-3 Audio Channels should be reported as '6'.
What happens instead?
For EC-3 and AC-3, channels are getting reported as '2' in the manifest.

<Please attach the input files or email to shaka-packager-issues@google.com.>
<Please provide any additional information below.>

**Comment by kqyang** [comment]
@jigneshdhruv Do you have a sample input file we can use to repro the issue? You can attach it here or email it to  shaka-packager-issues@google.com? Thanks.

**Comment by jigneshdhruv** [comment]
Hello Yang,

I have attached a tarball that contains 3 audio mp4's with 2channel AAC and 5.1channel (AC3 and EC3). There are 2 video only streams also. When you will package the content, you will see "2 channels" for all audio in the master manifest.

[shaka_hls_channel_test.tar.gz](https://github.com/google/shaka-packager/files/1604517/shaka_hls_channel_test.tar.gz)
 
Thanks,
Jignesh

**Comment by jigneshdhruv** [comment]
I would also like to know what parameters I need to set in packager to have "AUTOSELECT=YES,DEFAULT=YES" in audio reference in the master HLS manifest file.
Currently "AUTOSELECT & DEFAULT fields are not getting set for the AUDIO in the master manifest file.

Thanks.

**Comment by jigneshdhruv** [comment]
Any updates? Thanks.

**Comment by kqyang** [comment]
@jigneshdhruv The "AUTOSELECT" and "DEFAULT" tags are not supported right now. Feel free to file a feature request for it.

Also, I would like to understand more on how you are planning to use it. Do you want to mark a Rendition with a particular language as AUTOSELECT/DEFAULT or to mark a Rendition with a specified number of channels as AUTOSELECT/DEFAULT? 

From what I understand, AUTOSELECT and DEFAULT are  both designed to help client to choose the Rendition to play. DEFAULT indicates the client **SHOULD** play this Rendition while AUTOSELECT indicates the client **MAY** choose to play this Rendition. So DEFAULT is stronger than AUTOSELECT. It does not seem to make sense to set both attributes.

As for the wrong number of channels, we have found the problem and we are working on a fix.

**Comment by jigneshdhruv** [comment]
I will file a separate feature request for AUTOSELECT=YES. We basically need to set it on the audio renditions.

Do you have any ETA on when the channel bug will be fixed?

Thanks.

**Comment by kqyang** [comment]
I already have a fix pending to be pushed. Should be out some time this week.

**Comment by jigneshdhruv** [comment]
Let us know when the fix is pushed out. Thanks.

**Comment by kqyang** [comment]
@jigneshdhruv The fix has been pushed. Please verify! Thanks.

**Comment by jigneshdhruv** [comment]
I will download the latest code later today and will let you know the result. Thanks.

**Comment by synologic** [comment]
Looks like it's fixed in both hls and dash. Good job

**Comment by jigneshdhruv** [comment]
Verified. Channels are showing up correctly in HLS and DASH. Thanks.
