### ISSUE TITLE
Not able to generate pssh key using java like pssh-box.py

### ISSUE THREAD

**Issue by Pratikasai** [google/shaka-packager#314]
Hi,
I have a pssh key and I used pssh box to decode it.So it gives me data as follows: 

  System ID: Widevine XXXX-XXXX-XXXX-XXXXX-XXXX
  PSSH Data (size: 52):
    Widevine Data:
      Key IDs (2):
        00008109-c257-4a42-82c3-88c051c2c9de
        00310a84-310e-4eb6-a301-60e794c908df
      Provider: XXXX XXXXXXX

Now I want to implement same using java.

I deserialized a PSSH key using Widevine message in java.So I converted it from base64 to byte array.Since I dont know the headers for that psshkey ,I remove first 32  bytes which are for headers and decoded remaining using protobuf with widevine . I get 

key_id: "\000\000\201\t\302WJB\202\303\210\300Q\302\311\336"
key_id: "\0001\n\2041\016N\266\243\001`\347\224\311\b\337"
provider: XXXX XXXXXXX

so comparing the data from above result.
1)"provider" field is coming same
2) "Key Id"  : this field is not matching. 

**So I wanted to ask** what type of encoding is done to key Id ("00008109-c257-4a42-82c3-88c051c2c9de") in the widevine message itself in order to replicate "\000\000\201\t\302WJB\202\303\210\300Q\302\311\336".

currently I am building widevine message like:

pssh.WidevineCencHeader widevineCencHeader = pssh.WidevineCencHeader.newBuilder().setProvider(provider)				.addKeyId(ByteString.copyFromUtf8("00008109c2574a4282c388c051c2c9de"))				.addKeyId(ByteString.copyFromUtf8("00310a84310e4eb6a30160e794c908df")).build();

**Comment by kqyang** [comment]
It is using GUID format: https://en.wikipedia.org/wiki/Universally_unique_identifier#Format:

> In its canonical textual representation, the sixteen octets of a UUID are represented as 32 hexadecimal (base 16) digits, displayed in five groups separated by hyphens, in the form 8-4-4-4-12 for a total of 36 characters (32 alphanumeric characters and four hyphens). 

It is a way to display the binary string. (1) `00008109-c257-4a42-82c3-88c051c2c9de` is equivalent to (2) `\000\000\201\t\302WJB\202\303\210\300Q\302\311\336`. Just that (1) uses GUID format and (2) uses raw string.

**Comment by Pratikasai** [comment]
Thanks  @kqyang  ,It worked
I used this,
 byte[] data1 = Hex.decodeHex("00008109c2574a4282c388c051c2c9de".toCharArray());
 byte[] data2 = Hex.decodeHex("00310a84310e4eb6a30160e794c908df".toCharArray());

Pssh.WidevineCencHeader widevineCencHeader = Pssh.WidevineCencHeader.newBuilder().setProvider(provider)				.addKeyId(ByteString.copyFrom(data1)).addKeyId(ByteString.copyFrom(data2)).build();
