### ISSUE TITLE
Enable support for AUTOSELECT=YES on audio renditons

### ISSUE THREAD

**Issue by jigneshdhruv** [google/shaka-packager#315]
## System info
**Operating System**: <Ubuntu 16.04>
**Shaka Packager Version**: <66f713f-release>

New Feature Request:
Can you please provide a option to set "AUTOSELECT=YES" on audio renditions in the master HLS manifest file?

Let me know if you have questions.

Thanks.

**Comment by kqyang** [comment]
We have a `--default_language` option in DASH 

```
--default_language <language>
   Any tracks tagged with this language will have <Role ... value=”main” /> in the manifest. This allows the player to choose the correct default language for the content.
```

We can extend it to support HLS as well, i.e. adding "AUTOSELECT=YES" option to audio rendition with language == default_language. Is that sufficient for your use case? Or do you prefer an explicit `autoselect` option which you can apply to any rendition?

**Comment by jigneshdhruv** [comment]
For now, we need to apply autoselect flag to audio rendition only.

Thanks.

**Comment by jigneshdhruv** [comment]
Any ETA on this enhancement request for autoselect?

**Comment by rkuroiwa** [comment]
IIUC, AUTOSELECT is used to choose e.g. non-commentary streams, because under most cases, it makes sense to select the audio stream of the content rather than the commentary.

So I think it would have to be part of the stream descriptor.

Since DASH has 'main', 'alternate', 'commentary', etc. it might make sense to add something like 'role' descriptor. Also DASH allows specifying multiple roles so maybe we want to leave room that as well, e.g. dub & alternate.

@jigneshdhruv 
Tell us your use cases so we all have a better idea of what the problem is.

**Comment by jigneshdhruv** [comment]
This request is for master HLS manifest files. AUTOSELECT indicates the client MAY choose to play this audio rendition. Setting AUTOSELECT=TRUE flag in master manifest allows the player to pick up that audio stream.
In out usecase, if we do not have AUTOSELECT=TRUE for audio renditions, player skips the audio and is only playing the video.
We were using BENTO4 and it also adds AUTOSELECT=TRUE flag to audio renditions.

https://developer.apple.com/library/content/documentation/General/Reference/HLSAuthoringSpec/Requirements.html
See section 2.12, 2.13

**Comment by jigneshdhruv** [comment]
Let me know if you have more questions. Any ETA on this enhancement feature will be very much appreciated.

Thanks.

**Comment by kqyang** [comment]
@jigneshdhruv Can you give an example list of audio renditions? Are they of different languages? And which audio rendition you would like to auto select?

**Comment by cgp1081** [comment]
@kqyang Here is some sample streams

Tested devices - AppleTV Gen 4, iPhone X, avplayer

DEFAULT = YES - **audio plays**
https://cbsentallaccess.akamaized.net/intl_vms/2018/01/05/1130340419611/1298535_fp_hls/DefaultNE.m3u8

No AUTOSELECT or DEFAULT - **no audio track selected, no audio**
https://cbsentallaccess.akamaized.net/intl_vms/2018/01/05/1130340419611/1298535_fp_hls/Defaultmaster.m3u8

AUTOSELECT=YES - **audio plays**
https://cbsentallaccess.akamaized.net/intl_vms/2018/01/05/1130340419611/1298535_fp_hls/DefaultAS.m3u8

So it seems that without the autoselect or default attributes, we are unable to get audio playback in avplayer

**Comment by jigneshdhruv** [comment]
https://kb.developer.dolby.com/support/solutions/articles/16000040077-best-practices-for-encoding-and-delivering-dolby-audio-to-apple-devices-

Check the above URL where Dolby also recommends to have AUTOSELECT or DEFAULT flag set to YES in master HLS variant.

**Comment by zshenker** [comment]
Also in this HLS sample from Apple AUTOSELECT and DEFAULT are set to YES for all 3 Audio groups, https://devstreaming-cdn.apple.com/videos/streaming/examples/img_bipbop_adv_example_ts/master.m3u8

**Comment by kqyang** [comment]
@cgp1081 @jigneshdhruv @zshenker Thanks for the inputs! Here is our plan:

1. Add "AUTOSELECT=YES" to all audio renditions. We'll make it configurable if we need to support commentary audio streams in the future. It should be sufficient for now.
2. Enable "--default_language" support in HLS. If it is set and if it matches with the language in the audio rendition, set "DEFAULT=YES".

Does that sound good to you?

We'll work on it next week!

**Comment by jigneshdhruv** [comment]
@kqyang Yes it does sound good. Next week sounds fine. Thanks.

**Comment by jigneshdhruv** [comment]
@kqyang Any update on this enhancement? Will this feature be made available this week?

**Comment by kqyang** [comment]
Working on it! Will be pushed this week or early next week.

**Comment by kqyang** [comment]
@cgp1081 @jigneshdhruv @zshenker It is now supported. Let us know if you find any problems.
