### ISSUE TITLE
no output from live source

### ISSUE THREAD

**Issue by thex82** [google/shaka-packager#316]
Hi folks,

Shaka isn't creating the m3u8 files from a live udp source.

./packager 'input=udp://227.1.1.1:2600?interface=10.50.5.250,stream=0,init_segment=hls/0.mp4,segment_template=hls/$Number$.mp4,playlist_name=hls/live.m3u8' -hls_master_playlist_output hls/h264_master.m3u8 

I get the .mp4 but that's it.

Also, is there a way to limit the number of files to 5 or 10 files for HLS or DASH?

thanks

**Comment by kqyang** [comment]
@thex82 Can you clarify? Do you mean that you get all the mp4 outputs but no playlists? 

`playlist_name=hls/live.m3u8` should be ``playlist_name=live.m3u8` instead as it is relative to master playlist directory.

> Also, is there a way to limit the number of files to 5 or 10 files for HLS or DASH?

You can set --time_shift_buffer_depth to limit number of media segments in the DASH manifest and HLS playlist. Note that we don't delete the actual files from the disc - which you'll need to do it outside of packager.

**Comment by thex82** [comment]
Hi,

yes I get all the mp4s but no playlist.

**Comment by kqyang** [comment]
Which version of packager are you using?

**Comment by thex82** [comment]
packager version v1.6.2-6b98f0d-release

**Comment by kqyang** [comment]
There is a known problem with that version on HLS with MP4 support. You can try the latest commit on Github. Or if you don't mind waiting, we will be releasing a new version some time this month.

In the mean time, you can try DASH.

**Comment by kqyang** [comment]
v2.0.0 has been released, which has proper support for HLS with fMP4. Let us know if you are still seeing problems with v2.0.0.
