### ISSUE TITLE
Failure to parse a seemingly valid MP4 file

### ISSUE THREAD

**Issue by charlie-ht** [google/shaka-packager#319]
## System info
**Operating System**: Ubuntu 17.10
**Shaka Packager Version**: shaka-packager version v1.6.2-6b98f0d-release

## Issue and steps to reproduce the problem

**Packager Command**:
```
 ~/bin/shaka-packager   in=lambs.mp4,stream=audio,output=lambs-audio.mp4   in=lambs.mp4,stream=video,output=lambs-video.mp4   --mpd_output lambs.mpd 
```

What is the expected result?
No errors, the demuxed A/V files and an MPD manifest. The MP4 file looks valid and plays on my desktop. This is the output of the `mp4info` command from Bento SDK,

```
> mp4info lambs.mp4 
File:
  major brand:      mp42
  minor version:    0
  compatible brand: isom
  compatible brand: mp42
  fast start:       yes

Movie:
  duration:   39752 ms
  time scale: 1000
  fragments:  no

Found 2 Tracks
Track 1:
  flags:        7 ENABLED IN-MOVIE IN-PREVIEW
  id:           1
  type:         Video
  duration: 39752 ms
  language: ```
  media:
    sample count: 1192
    timescale:    90000
    duration:     3577636 (media timescale units)
    duration:     39752 (ms)
    bitrate (computed): 16994.751 Kbps
  display width:  1920.000000
  display height: 1080.000000
  frame rate (computed): 29.986
  Sample Description 0
    Coding:      avc1 (H.264)
    Width:       1920
    Height:      1080
    Depth:       24
    AVC Profile:          100 (High)
    AVC Profile Compat:   0
    AVC Level:            40
    AVC NALU Length Size: 4
    AVC SPS: [67640028acd201e0089f9652020c020da1426a]
    AVC PPS: [68ee06e2c0]
    Codecs String: avc1.640028
Track 2:
  flags:        7 ENABLED IN-MOVIE IN-PREVIEW
  id:           2
  type:         Audio
  duration: 39723 ms
  language: ```
  media:
    sample count: 1862
    timescale:    48000
    duration:     1906687 (media timescale units)
    duration:     39723 (ms)
    bitrate (computed): 128.111 Kbps
  Sample Description 0
    Coding:      mp4a (MPEG-4 Audio)
    Stream Type: Audio
    Object Type: MPEG-4 Audio
    Max Bitrate: 128000
    Avg Bitrate: 128000
    Buffer Size: 768
    Codecs String: mp4a.40.2
    MPEG-4 Audio Object Type: 2 (AAC Low Complexity)
    MPEG-4 Audio Decoder Config:
      Sampling Frequency: 48000
      Channels: 2
    Sample Rate: 48000
    Sample Size: 16
    Channels:    2
```

What happens instead?
I see this,
```
> ~/bin/shaka-packager   in=lambs.mp4,stream=audio,output=lambs-audio.mp4   in=lambs.mp4,stream=video,output=lambs-video.mp4   --mpd_output lambs.mpd 
[0125/114509:INFO:demuxer.cc(58)] Initialize Demuxer for file 'lambs.mp4'.
[0125/114509:ERROR:box_reader.cc(82)] Failure while processing: SkipBytes(box_size)
[0125/114509:ERROR:box_definitions.cc(1422)] Failure while processing: ReadWriteHeaderInternal(buffer) && buffer->PrepareChildren() && buffer->ReadWriteChild(&handler) && buffer->TryReadWriteChild(&id3v2)
[0125/114509:ERROR:box_reader.cc(95)] Failure while processing: child->Parse(itr->second.get())
[0125/114509:ERROR:box_definitions.cc(2223)] Failure while processing: ReadWriteHeaderInternal(buffer) && buffer->PrepareChildren() && buffer->ReadWriteChild(&header) && buffer->TryReadWriteChild(&metadata) && buffer->TryReadWriteChild(&extends)
[0125/114509:ERROR:mp4_media_parser.cc(296)] Failure while processing: moov_->Parse(reader)
[0125/114509:ERROR:packager_main.cc(311)] Demuxer failed to initialize: 8 (PARSER_FAILURE): Cannot parse media file lambs.mp4
```

I can send the video file if it's necessary, but perhaps I'm doing something obviously wrong.

**Comment by kqyang** [comment]
Can you attach the link to the content in this issue or send the content to shaka-packager-issues@google.com? Thanks.

**Comment by kqyang** [comment]
From what is in the error message, it appears that the ID3v2 box is not well formed. I cannot confirm without seeing the content. 

Close due to inactivity. Feel free to re-open the issue if you have questions.

**Comment by charlie-ht** [comment]
@kqyang Really sorry for missing your responses :( I had some issues classifying Github mail locally. Anyway... Here's is the source media I am using, I uploaded it to my drive account,

https://drive.google.com/file/d/1E8Uw5sV9m1RS8TX4W2Zbh0E5x9st39Ud/view?usp=sharing

**Comment by kqyang** [comment]
@charlie-ht I looked into the file you uploaded. It has an invalid meta box.

Here is the box structure in your content:

```
ftyp
  moov
    mvhd
    meta
    trak[0]
    trak[1]
  free
  mdat
```

`meta` box should be a full mp4 box with 12 bytes of header. The first 4 bytes is the size of the `meta` box; the second 4 bytes is fourcc of `meta`; the third 4 bytes is supposed to be the flag and version of the `meta` box; followed by the children boxes of `meta`, i.e. 4 bytes size + 4 byte fourcc + ...

However, by looking at the data in your `meta` box:

```
00 00 00 77 6d 65 74 61 00 00 00 21 68 64 6c 72 00 00 00 00 ...
```

It only has 8 bytes of header, followed by the child box `hdlr`. This is not compliant to the spec. And it results in an error when parsing the box. It is possible to ignore the error when parsing `meta` box in packager.

I am curious how was the file generated and which tool is used to generate the box.

**Comment by charlie-ht** [comment]
This was taken on a moto g4 plus, android 7.0 phone with the default camera
app (I think, unless Moto has done something). I'm not sure how to get more
information about it, i still use the same phone so please let me know if
there's more info you might need.

**Comment by kqyang** [comment]
I see. So somehow Android Camera app is not doing things correctly. We'll workaround the bug in packager. Thanks for reporting the problem!

**Comment by kqyang** [comment]
Cherry-picked for v2.0.1.
