### ISSUE TITLE
How to encrypted different stream with different keys using Widevine?

### ISSUE THREAD

**Issue by charlie-ht** [google/shaka-packager#320]
## System info
**Operating System**: Ubunut 17.10
**Shaka Packager Version**: latest release

I see nothing in https://google.github.io/shaka-packager/html/tutorials/widevine.html about different stream with different keys, as is explained in the Raw Key section using `--keys`

Only way I can think to do it is to demux the A/V streams and encrypt each one with a different key? Then combine with mpd_generator, which the developers of this project say they want to remove and don't know of good use cases for.

Are there examples of using widevine with a `--keys` equivalent?

**Comment by kqyang** [comment]
Are you managing the content keys yourself (i.e. runs your own license server) or are the content keys managed by Widevine server?

For the former case, use --enable_raw_key_encryption and you can provide custom PSSHs (including Widevine PSSH) in --pssh. See the examples in https://google.github.io/shaka-packager/html/tutorials/raw_key.html#examples for details.

For the latter case, use --enable_widevine_encryption and the keys are managed by Widevine server. Widevine server generates different keys for AUDIO, SD, HD, UHD1, UHD2 automatically. You cannot and there is no need to inject the keys.

**Comment by kqyang** [comment]
Close due to inactivity. Feel free to open another issue if you have more questions.

**Comment by charlie-ht** [comment]
I'm **very, very** sorry for not seeing your responses @kqyang -- dropped the ball here. That does answer my question, thank you!
