### ISSUE TITLE
Option "temp_dir" doesn't work on Centos7

### ISSUE THREAD

**Issue by lpluto** [google/shaka-packager#322]
## System info
**Operating System**: CentOS Linux release 7.4.1708 (Core)
**Shaka Packager Version**: 9ecee466587b41c4d64572b22ae430f8b573531e

## Issue and steps to reproduce the problem
We're trying to use "temp_dir" option on Centos 7 and packager is still using "/tmp" directory for temp file. Do you maybe know how to properly set this param?

**Packager Command**:
packager \
in=in.mp4,stream=audio,output=audio.mp4 \
in=in.mp4,stream=video,output=video.mp4 \
--enable_widevine_encryption \
--key_server_url https://license.uat.widevine.com/cenc/getcontentkey/widevine_test \
--content_id 7465737420636f6e74656e74206964 \
--signer widevine_test \
--aes_signing_key 1ae8ccd0e7985cc0b6203a55855a1034afc252980e970ca90e5202689f947ab9 \
--aes_signing_iv d58ce954203b7c9a9a9d467f59839249 \
--temp_dir /path/to/temp \
--mpd_output manifest.mpd

**What is the expected result?**
Packager will use temporary directory from "temp_dir" option

**What happens instead?**
Packager uses "/tmp" for temporary directory

<Please attach the input files or email to shaka-packager-issues@google.com.>
<Please provide any additional information below.>

**Comment by kqyang** [comment]
@lpluto Thanks for reporting the issue. Can you provide more information? For example, do you have the names of the temporary files created by packager in "/tmp"?

**Comment by lpluto** [comment]
@kqyang Sure, temp file names looks like this, e.g. ".org.chromium.Chromium.6lByfa", so they look like packager omits "temp_dir" option.
