### ISSUE TITLE
Demuxer failed to initialize: 8 (PARSER_FAILURE)

### ISSUE THREAD

**Issue by jfurton** [google/shaka-packager#323]
## System info
**Operating System**: Windows 10
**Shaka Packager Version**: v1.6.2,

## Issue and steps to reproduce the problem

Starting from this original:
https://s3.amazonaws.com/jzf-file-share/antonov60.mp4

I created a webm vp9 transcode with ffmpeg. (latest ffmpeg version N-89894-g18e2ac032e but 3.4.1 has same results ):

`ffmpeg -i antonov60.mp4 -c:v libvpx-vp9 -s 3840x1920 -b:v 1024k -keyint_min 24 -g 24 -tile-columns 4 -frame-parallel 1 -an -f webm -dash 1 antonov60.webm
`
Which generates me this:
https://s3.amazonaws.com/jzf-file-share/antonov60.webm

Checking it with packager-win.exe:

```
packager-win.exe input=antonov60.webm --dump_stream_info
[0129/160204:INFO:demuxer.cc(58)] Initialize Demuxer for file 'antonov60.webm'.
[0129/160204:ERROR:packager_main.cc(311)] Demuxer failed to initialize: 8 (PARSER_FAILURE): Cannot parse media file antonov60.webm
```

I was hoping to see the video track info printed, but for some reason the demuxer does not like it. Unfortunately the error message does not tell me what exactly I should do differently. 

Any help is appreciated.

**Comment by kqyang** [comment]
There is a known problem with new color attributes handling in v1.6.2. Can you try the latest build? You can find latest build binary from AppVeyor artifacts: https://ci.appveyor.com/project/shaka/shaka-packager

**Comment by jfurton** [comment]
you are so right. With the latest build it's working great!!!

```
D:\>packager-win.exe input=antonov60.webm --dump_stream_info
[0129/174708:INFO:demuxer.cc(89)] Demuxer::Run() on file 'antonov60.webm'.
[0129/174708:INFO:demuxer.cc(161)] Initialize Demuxer for file 'antonov60.webm'.

File "antonov60.webm":
Found 1 stream(s).
Stream [0] type: Video
 codec_string: vp09.00.10.08.00.02.02.02.00
 time_scale: 1000000
 duration: 60042000 (60.0 seconds)
 is_encrypted: false
 codec: VP9
 width: 3840
 height: 1920
 pixel_aspect_ratio: 1:1
 trick_play_factor: 0
 nalu_length_size: 0

Packaging completed successfully.

```


Thanks for pointing me to the right direction. Can you maybe tell us more about what was wrong with the color attributes?

**Comment by kqyang** [comment]
@jfurton It should be a duplicate of https://github.com/google/shaka-packager/issues/284. Also see https://github.com/google/shaka-packager/issues/275. We did not support the new WebM color info earlier.
