### ISSUE TITLE
cbcs HLS (MP4) audio stream doesn't play in Safari on macOS

### ISSUE THREAD

**Issue by vladimir-kazakov** [google/shaka-packager#326]
When I create cbcs HLS (MP4) audio stream using Shaka Packager `aa4bb49-release`, such stream doesn't play on macOS 10.13.3 in Safari 11.0.3. Unfortunately, Safari doesn't provide any details.

The following command is used to produce this stream:

```
packager \
  'in=In/audio-128k.mp4,stream=audio,init_segment=Out/audio-128k-init.mp4,segment_template=Out/audio-128k-$Number$.mp4,playlist_name=audio-128k.m3u8' \
  --enable_raw_key_encryption --protection_scheme cbcs --clear_lead 0 --mp4_include_pssh_in_stream=false \
  --keys 'label=:key_id=11111111111111111111111111111111:key=22222222222222222222222222222222' --iv 33333333333333333333333333333333 \
  --segment_duration 2 --fragment_duration 2 \
  --hls_key_uri 'https://.../key.bin' --hls_master_playlist_output Out/index.m3u8
```

When I use `mediafilesegmenter` (a packager from Apple) in order to achieve the same goal, the output from this packager successfully plays. So, it seems that Shaka Packager is doing something wrong. Interestingly enough, this issue affects only audio streams. Video streams play without any problems.

The files from both packagers can be accessed here: https://1drv.ms/f/s!Ah-Kf_FqISskkQnY9LLGzb5bI3ZM. In order to play such media, the value of the `URI` attribute of the `EXT-X-KEY` tag in the HLS manifest must be changed to a valid URL that points to `key.bin`.

**Comment by kqyang** [comment]
@vladimir-kazakov Thanks for reporting the issue. Can you provide the source content 'audio-128k.mp4' as well? It will help us re-pro the issue. Thanks.

**Comment by kqyang** [comment]
The problem is that Safari does not like v1 tenc box, although there is no pattern (v1 tenc box is only necessary if pattern encryption is used). It looks like a bug in Safari as Safari crashed when trying to playing the stream, but we'll fix it in packager anyway.

**Comment by vladimir-kazakov** [comment]
@kqyang, I uploaded the source audio into the "source" folder.

> The problem is that Safari does not like v1 tenc box, although there is no pattern (v1 tenc box is only necessary if pattern encryption is used).

Is it really so? I'm comparing init segments in mp4dump from Bento4, and it shows me that mediafilesegmenter used tenc v1 (such media works in Safari), but Shaka Packager used v0 (such media does not work in Safari).

About the pattern encryption. According to the CENC standard (third edition), `cbcs` is a protection scheme that uses the pattern encryption. And in the section 8.2.3, it explicitly says that in this case the tenc version must be equal to 1:

> version SHALL be zero unless pattern-based encryption is in use, whereupon it SHALL be 1.

**Comment by kqyang** [comment]
Sorry, that is a typo, I meant "Safari does not like v0 tenc box".
