### ISSUE TITLE
Non MP4 extension for DASH Live Init Segments

### ISSUE THREAD

**Issue by zshenker** [google/shaka-packager#331]
Trying to use .m4s(or anything other than .mp4) as the extension for the DASH Init Segments, returns the error:
```
[0220/161015:ERROR:packager_main.cc(465)] Failed to initialize packager: 3 (INVALID_ARGUMENT): Unsupported output format.
```

Commonly with DASH I see .m4s or .m4v used as the extensions of the init and/or media segments. 

Would be great to have support for a broader range of file extensions on the init segment.

@kqyang

**Comment by rkuroiwa** [comment]
Probably just adding several lines for 'm4s'.
https://github.com/google/shaka-packager/blob/master/packager/media/base/container_names.cc#L1734
https://github.com/google/shaka-packager/blob/master/packager/media/base/container_names.cc#L1753

m4v and m4a should work, if those are good enough.

**Comment by kqyang** [comment]
@zshenker 

> Commonly with DASH I see .m4s or .m4v used as the extensions of the init and/or media segments.

As @rkuroiwa mentioned, .m4v is supported, but we have never seen .m4s as the extension of the init segment. I think .m4s should only be used as the extension of the media segments. Let me know if I am wrong.

**Comment by zshenker** [comment]
@kqyang As far as I know the DASH spec doesn't explicitly have an allowed list of file extensions for the init segment, so it seems like .m4s could be used.

**Comment by kqyang** [comment]
@zshenker Sure, we'll add support for it.

**Comment by kqyang** [comment]
Cherry-picked for v2.0.1.
