### ISSUE TITLE
Is it possible to use EME without using shake-player?

### ISSUE THREAD

**Issue by lenny0702** [google/shaka-packager#333]
Hi, I just have a question here, so please forgive to not use the default issue form, I am just so excited to finally find such a good tool to encrypt the media file for EME!

My problem is I made a successful sample to play a shake-packager encrypted audio using shaka-player, however, shake-player is just too big for me. I only want to use EME play audio for me. 

So I am wondering if it's possible to play encrypted audio just using native browser API? Just like only set src="encrypted.mp4", and set the encryption key value in JS. Just like what is it in this sample: [https://simpl.info/eme/clearkey/](https://simpl.info/eme/clearkey/) Or I still have to use the shake-player and dash tech to play very simple encrypted audio file even I don't slice it at all ?

I tried this with shaka-packager, the encryption command is 
`packager input=/media/example.mp4,stream=audio,output=/media/audio.mp4            input=/media/example.mp4,stream=video,output=/media/video.mp4            --mpd_output /media/example.mpd --enable_raw_key_encryption --keys label=:key_id=E6DD428E76CC154441A2ED3CECE4A3DB:key=20000000200020002000200000000002 --generate_static_mpd`
the encryption is successful, but when I try to play it by set the src of video tag. the "encrypted" event of EME doesn't fire at all.

We need this so much, thanks in advance if someone can answer my question. A sample would be so appreciated.

**Comment by rkuroiwa** [comment]
There is a chromium bug for this.
crbug.com/170793
Basically the bug is for supporting mp4 w/ EME.
I don't know about limitations of other browsers.

The example page that you linked uses webm and webm should work. So (in chromium) if you could use codecs that are supported by chromium that can be packaged in webm, then you should be able to use EME with src=.

**Comment by kqyang** [comment]
@rkuroiwa The bug only affects Chromium. I think @lenny0702 is talking about Chrome, which does have MP4 support, otherwise Shaka Player will not work either.

I am not familiar with player. Following the steps in https://www.html5rocks.com/en/tutorials/eme/basics/#clear-key should just work. @vaage @joeyparrish Do you have any idea where the problem might be above.

**Comment by vaage** [comment]
@lenny0702 What you want to do should be possible. Shaka Player does not do anything special to play encrypted content. Most of what Shaka Player does is parse manifests, set up EME, set up Media Source, and handle ABR. So rest assured, what you are asking to do, is possible.

Looking at your packager command, I am little confused. You are packaging audio and video but then say you just want to play audio. Could you elaborate on what you are doing so I can understand exactly what you are looking to accomplish?

**Comment by kqyang** [comment]
Ahh... Actually @rkuroiwa is right. I misread the bug. Encrypted MP4 without MSE is not supported in Chrome. Please discard my comment above.

@lenny0702 You'll need to use either WebM with "src" or MP4 with MSE. As @vaage mentioned, you don't really need Shaka Player to use MSE. There are actually steps in https://www.html5rocks.com/en/tutorials/eme/basics/#clear-key using MSE as well.

**Comment by lenny0702** [comment]
@kqyang No no no, you're right! Thanks you so much! You solve my problem! Actually you remind me of that bug. I didn't know that before. What I did is using the "src=" way with mp4, which doesn't work indeed. I think this bug also still exists in the chrome too.

But when I transfer the same encrypted video and audio to a demo using the MSE based player. It finally worked! The encrypted event was fired, and the audio and the video are decrypted and played normally.

Thanks to the response from all you guys! I so appreciate it.
