### ISSUE TITLE
Shaka packager HLS Output Generation Problem.

### ISSUE THREAD

**Issue by WhiteDove101** [google/shaka-packager#337]
Hello
I tried to make hls live stream .m3u8 from udp stream by using shaka packager.
It works now so some files are generated continually but it doesn't generate the h264_master.m3u8 output file.
Am I missing something?

**Comment by vaage** [comment]
Hello @WhiteDove101,

In order to assist you, could you please include the packager command you are running and the output from `ls <your source media directory>` ?

**Comment by WhiteDove101** [comment]
packager \
  'in=udp://225.1.3.100:3300?reuse=1&interface=0.0.0.0,stream=audio,init_segment=audio_init.mp4,segment_template=audio_$Number$.m4s,playlist_name=audio.m3u8,hls_group_id=audio,hls_name=ENGLISH' \
  'in=udp://225.1.3.100:3300?reuse=1&interface=0.0.0.0,stream=video,init_segment=h264_360p_init.mp4,segment_template=h264_360p_$Number$.m4s,playlist_name=h264_360p.m3u8' \
  'in=udp://225.1.3.10:3300?reuse=1&interface=0.0.0.0,stream=video,init_segment=h264_480p_init.mp4,segment_template=h264_480p_$Number$.m4s,playlist_name=h264_480p.m3u8' \
   --hls_master_playlist_output ./h264_master.m3u8

**Comment by WhiteDove101** [comment]
And here is Output Folder
![image](https://user-images.githubusercontent.com/26065238/36922062-a31b3fac-1e34-11e8-807e-bbcb4aab37c2.png)

**Comment by WhiteDove101** [comment]
now it's generating over 300 files.

**Comment by vaage** [comment]
@WhiteDove101 if I understand the output folder image correctly, no media playlists and no master playlists are getting generated, is that correct?

**Comment by WhiteDove101** [comment]
Yes, it is not generating audio.m3u8,  h264_360p.m3u8 and h264_master.m3u8 files

**Comment by vaage** [comment]
Is your live stream publicly available? It would be easier for me to look into this if I could run the command myself.

If not, could you try running the command but use an absolute filepath for `--hls_master_playlist_output`? The other m3u8 paths are based of it and I am concerned it may be writing them somewhere else.

**Comment by WhiteDove101** [comment]
I hosted this on local only.
And I tried to use /var/www/html/ folder but it isn't making.

**Comment by vaage** [comment]
@kqyang Is there something I am overlook in the command? It looks like it should work to me.

@WhiteDove101 How are you generating your live stream? Is it something I could do so I could repo this locally?

**Comment by WhiteDove101** [comment]
I tried this
--hls_master_playlist_output /var/www/html/h264_master.m3u8
And I am making live stream by using ffmpeg

**Comment by vaage** [comment]
@WhiteDove101 does packager have permission to write to `/var/www/html/`? On my machine, by default, that directory is read only.

What happens if you use `--hls_master_playlist_output /tmp/h264_master.m3u8`?

**Comment by WhiteDove101** [comment]
I gave full permission on that folder 777.

--hls_master_playlist_output /tmp/h264_master.m3u8
And it isn't making the output file.

**Comment by WhiteDove101** [comment]
I am using binary packager not source code.
is that problem?

**Comment by vaage** [comment]
That should not be a problem, but to be sure, what version of the packager are you using?

**Comment by WhiteDove101** [comment]
I am using latest version downloaded.

**Comment by vaage** [comment]
@WhiteDove101, @kqyang and I talked offline and we think we found the problem. Could you try adding `--hls_playlist_type LIVE` to your command.

By default the packager assumes VOD content, so it is waiting for the streams to end before writing the manifest. If you tell the packager that the playlist is LIVE, it will periodically write the manifest to disc.

**Comment by WhiteDove101** [comment]
Yeah, it works correctly.
Now it's success.
Thank you.
