### ISSUE TITLE
Dolby Vision support

### ISSUE THREAD

**Issue by kqyang** [google/shaka-packager#341]
Dolby Vision Profiles: https://www.dolby.com/us/en/technologies/dolby-vision/dolby-vision-profiles-levels-v1-2-92-171021.pdf

Our priority is to add support for profile 5 (which is an HEVC Main10 single stream) first, which is the only required and pushed by Dolby right now as far as I know.

Look at Dolby's spec at https://www.dolby.com/us/en/technologies/dolby-vision/dolby-vision-bitstreams-within-the-iso-base-media-file-format.pdf, it seems trivial to add support for Dolby Vision Profile 5. What we need is to add support for Dolby Vision sample entries and Dolby Vision Configuration box. Everything else should be transparent.

**Comment by kqyang** [comment]
Updated Dolby Vision specs:

https://www.dolby.com/us/en/technologies/dolby-vision/dolby-vision-profiles-levels-v1-2-93-180420.pdf
https://www.dolby.com/us/en/technologies/dolby-vision/dolby-vision-bitstreams-within-the-iso-base-media-file-format-v2.0.pdf
https://www.dolby.com/us/en/technologies/dolby-vision/dolby-vision-streams-within-the-mpeg-dash-format-v1.1.pdf

**Comment by kqyang** [comment]
Latest updates from Dolby:

https://www.dolby.com/us/en/technologies/dolby-vision/dolby-vision-streams-within-the-http-live-streaming-format-v2.0.pdf
https://www.dolby.com/us/en/technologies/dolby-vision/dolby-vision-streams-within-the-mpeg-dash-format-v2.0.pdf

Both specs introduce changes in Dolby Vision signaling in m3u8 and mpd compare to previous version.

**Comment by kqyang** [comment]
Updated profiles-levels specification: https://www.dolby.com/us/en/technologies/dolby-vision/dolby-vision-profiles-levels_v1.3.1.pdf

**Comment by jigneshdhruv** [comment]
@kqyang Any update on this ticket? Can we expect DV/HDR+ support in Shaka Packager in the next release? Thanks.

**Comment by kqyang** [comment]
@jigneshdhruv No. We'll update this issue if there are any updates.

**Comment by kqyang** [comment]
Dolby Vision is already supported. Move the work on Dolby Vision backward compatible profile to #690.
