### ISSUE TITLE
Shaka packager HLS iOS issue

### ISSUE THREAD

**Issue by WhiteDove101** [google/shaka-packager#357]
I am trying to use shaka packager streaming in iphone app.
I received the source code from CWIP support team also tested it with other sample mpd streams.
I made live stream .mpd file and m3u8 file from server and tried to use this on iOS app(CDM player).
When I made new .mpd file from mp4 file it plays well but live stream is not playing.
Here I made .mpd and .m3u8 file from udp://23.345.23.232:2333 stream.

But it doesn't play it.
Please resolve this problem.
Thanks.

**Comment by vaage** [comment]
@WhiteDove101 Could you supply us with the command you used to run the packager?

**Comment by WhiteDove101** [comment]
I confirm the shaka packager command is correct because I tested the packager command result (mpd file) on Web browser(shaka player) and android.
But iOS app only is not playing with unknown error.

But here is command lines.

./packager-linux 'input=udp://231.51.36.3:7776?reuse=1&interface=0.0.0.0,stream=audio,init_segment=./media/audio_init.mp4,segment_template=./media/audio_$Number$.m4s,playlist_name=audio.m3u8,hls_group_id=audio,hls_name=ENGLISH' 'input=udp://231.51.36.3:7776?reuse=1&interface=0.0.0.0,stream=video,init_segment=./media/h264_360p_init.mp4,segment_template=./media/h264_360p_$Number$.m4s,playlist_name=h264_360p.m3u8' --hls_playlist_type LIVE --hls_master_playlist_output ./media/star-select-hd.m3u8 --mpd_output ./media/star-select-hdm3.mpd

**Comment by SeawardT** [comment]
The iOS SDK supports live streaming, but the player app has to be able to parse the originating playlist appropriately. This has been added to the Reference Player already, but has not been merged to the public repository. I will be pushing a new build next week that will have the support. Most of the work is determining when to update the incoming manifest and then when to pull new segments.

**Comment by WhiteDove101** [comment]
Thank you @SeawardT .
If iOS SDK supports live streaming can you please give me guide how to use the sdk for live streaming?
Especially I don't need others because I already tried to use for other steaming so if you send me guide how to use the ios sdk for live streaming, it's very helpful.(This is a little urgent).
Hope your kind guide.
Thanks.

**Comment by SeawardT** [comment]
I have posted a diff on the iOS Discuss forums that you can pull down and try out.

**Comment by WhiteDove101** [comment]
Hi Seaward T,
Thank you for your new code posting.
But I can't get access to the widevine-ios-discuss@googlegroups.com.
Can you please give me access to the discuss forum or send me source code to the email directly?
Thanks.

**Comment by WhiteDove101** [comment]
I tested the iOS app and it plays the video about 10 secs and stop forever.
Can you please help me with this?
I am waiting for your reply, now.
Thanks.

**Comment by SeawardT** [comment]
Ill need more information before I can assist.  I would recommend posting your questions in the iOS forum as it seems to be a player issue not packaging. Please post a link or some output from the debugger so I can assist.

**Comment by kqyang** [comment]
I am closing this issue. @WhiteDove101 Please follow the instructions by @SeawardT and post your questions with "more information" in the iOS forum instead.

**Comment by WhiteDove101** [comment]
I tested the sample video with Live stream named "Gource Live Stream" from the list json file.
It plays the video well but after about 10 seconds it stops to play the video.
I hope you please help me with this.
Thanks.
