### ISSUE TITLE
invalid EXT-X-KEY in .m3u8 file

### ISSUE THREAD

**Issue by fuzing** [google/shaka-packager#358]
When packaging for HLS with fmp4 using raw key encryption, the packager is creating it's EXT-X-KEY with "SAMPLE-AES-CTR" which does not appear to be valid in the HLS specification (despite being referenced in the Widevine specification) - (see: https://tools.ietf.org/html/rfc8216)

In any event, I am not referencing Widevine, yet SAMPLE-AES-CTR is being injected.

**Comment by kqyang** [comment]
@fuzing The default protection scheme is cenc (AES-CTR with no pattern), which is not defined in HLS spec, so we borrowed Widevine extension "SAMPLE-AES-CTR" to indicate this protection scheme. 

HLS spec only allows "cbcs" for fmp4. If you want to do "cbcs", you'll need to specify the protection scheme as "cbcs" explicitly via `--protection_scheme` flag: https://google.github.io/shaka-packager/html/tutorials/raw_key.html#general-encryption-options.

**Comment by fuzing** [comment]
OK - that makes sense.   Thank you.
