### ISSUE TITLE
Packager ignores segment_duration

### ISSUE THREAD

**Issue by jakubvojacek** [google/shaka-packager#359]
## System info
**Operating System**: Debian
**Shaka Packager Version**: packager version f2e9c95628-release

## Issue and steps to reproduce the problem

**Packager Command**:
```
packager  'in=udp://239.100.200.1:1235?interface=172.16.128.42&reuse=1,stream=audio,language=cze,stream_selector=1,init_segment=eurosport-1-hd-42_audio.mp4,segment_template=audio/eurosport-1-hd-42-$Number$.mp4' --segment_duration 1 'in=udp://239.100.200.1:1234?interface=172.16.128.42&reuse=1,stream=video,init_segment=eurosport-1-hd-42_video_576.mp4,segment_template=video_576/eurosport-1-hd-42-$Number$.mp4' --segment_duration 1 --mpd_output eurosport-1-hd-42.mpd 
```

What is the expected result?
I would expect that when I selected segment duration of 1 second, all segments would be 1 second long. But thats not the case. Video segments are cca 12 seconds long I believe
```
-rw-r--r--  1 root root 1509022 2018-03-27 21:02:57.119563282 +0200 eurosport-1-hd-42-35.mp4
-rw-r--r--  1 root root 1460130 2018-03-27 21:02:44.815722959 +0200 eurosport-1-hd-42-34.mp4
-rw-r--r--  1 root root 1488983 2018-03-27 21:02:32.863878077 +0200 eurosport-1-hd-42-33.mp4
-rw-r--r--  1 root root 1598516 2018-03-27 21:02:20.920033095 +0200 eurosport-1-hd-42-32.mp4
-rw-r--r--  1 root root 1543480 2018-03-27 21:02:08.960188327 +0200 eurosport-1-hd-42-31.mp4
-rw-r--r--  1 root root 1447425 2018-03-27 21:01:56.864345331 +0200 eurosport-1-hd-42-30.mp4
-rw-r--r--  1 root root 1508167 2018-03-27 21:01:44.924500316 +0200 eurosport-1-hd-42-29.mp4
```

while audio segmets are having correct length

```
-rw-r--r--  1 root root 16321 2018-03-27 21:02:06.572219323 +0200 eurosport-1-hd-42-378.mp4
-rw-r--r--  1 root root 16899 2018-03-27 21:02:05.540232717 +0200 eurosport-1-hd-42-377.mp4
-rw-r--r--  1 root root 16546 2018-03-27 21:02:04.476246528 +0200 eurosport-1-hd-42-376.mp4
-rw-r--r--  1 root root 16215 2018-03-27 21:02:03.468259611 +0200 eurosport-1-hd-42-375.mp4
-rw-r--r--  1 root root 16437 2018-03-27 21:02:02.756268853 +0200 eurosport-1-hd-42-374.mp4
-rw-r--r--  1 root root 16485 2018-03-27 21:02:01.716282351 +0200 eurosport-1-hd-42-373.mp4
-rw-r--r--  1 root root 16478 2018-03-27 21:02:00.612296682 +0200 eurosport-1-hd-42-372.mp4
```

Is this correct behaviour? Does it have to do something with the input data? Can we somehow control this?

Thank you

**Comment by kqyang** [comment]
@jakubvojacek What is the video GOP size? It seems like the GOP is about 12 seconds. Can you check and confirm?

By default, we align segments with GOP boundary. This behavior can be changed, see https://google.github.io/shaka-packager/html/documentation.html#chunking-options - we don't recommend changing it though.

**Comment by jakubvojacek** [comment]
you were right!

We were having ffmpeg running with fps 25 and gop 300. In order to have 3.2 seconds long segments, we needed to change the gop to 80 (80/25=3.2). It now works like a charm

Thank you, closing
