### ISSUE TITLE
Feature Request:  AVERAGE-BANDWIDTH in HLS Master Manifest

### ISSUE THREAD

**Issue by zshenker** [google/shaka-packager#361]
HLS Master Manifests, in the #EXT-X-STREAM-INF can have an AVERAGE-BANDWIDTH attribute, that can help the ABR algorithm on some devices.

Spec docs: https://tools.ietf.org/html/draft-pantos-http-live-streaming-23#page-28

@kqyang What would be involved in calculating and including the HLS master manifest the AVERAGE-BANDWIDTH values?

**Comment by kqyang** [comment]
@zshenker It should be easy to do.
