### ISSUE TITLE
(ENCRYPTION_FAILURE): Failed to encrypt NAL frame.

### ISSUE THREAD

**Issue by simhavenkat** [google/shaka-packager#367]
## System info
**Operating System**:  macOS High Sierra
**Shaka Packager Version**: 2.0.2

## Issue and steps to reproduce the problem
I am getting the following errors when packaging with fixed key encryption. Removing the encryption options - the command succeeds. The mp4 plays fine and loads in isoviewer with the atoms as shown. 
Any ideas on how to debug this? I can send a pointer to the mp4 if needed. Let me know. 

**Packager Command**:
```
out/Debug/packager input=~/videosamples/-iGKLCc.mp4,stream='video',output='/tmp/-iGKLCc.mp4' --segment_duration=2 --enable_fixed_key_encryption --key_id '<removed>' --key '<removed>' --pssh '<removed>' --mpd_output '/tmp/manifest.mpd'
```
Extra steps to reproduce the problem?
(1) 
(2)

What is the expected result?
Expected the packager command to succeed - but fails. 
What happens instead?
I get these errors.
```
[0402/162731:INFO:track_run_iterator.cc(166)] Edit list with media time 1088 ignored.
[0402/162731:WARNING:nalu_reader.cc(107)] Unspecified or reserved nal_unit_type 31 (header 0x1f).
[0402/162731:ERROR:encryption_handler.cc(557)] Failed to parse NAL units.
[0402/162731:ERROR:demuxer.cc(319)] Failed to process sample 256 9 (ENCRYPTION_FAILURE): Failed to encrypt NAL frame.
```

<Please attach the input files or email to shaka-packager-issues@google.com.>
<Please provide any additional information below.>
![screen shot 2018-04-02 at 4 37 21 pm](https://user-images.githubusercontent.com/34262633/38221404-2f749418-3694-11e8-8636-64a494881af3.png)

**Comment by kqyang** [comment]
@simhavenkat From the log, the stream contains an invalid NAL unit. There is no NAL unit with type equals to 31.  Shaka Packager parses NAL units to determine if the NAL unit should be encrypted.

If you send the content to us at <shaka-packager-issues@google.com>, we'll look into the content and confirm the findings.

Do you know how is the source content encoded? And why does it contain invalid NAL units?

**Comment by simhavenkat** [comment]
Ok found the source of these - turns something in the path is adding these - i don't know yet what the reason is - but its not a corrupt stream - more like a non compliant one. 

What is the side effect of ignoring these? I locally modified and it encrypted the stream ok.

**Comment by kqyang** [comment]
It should be fine as long as it is not the result of data corruption, but it may not work on some platforms if they have a strict check for compliance.
