### ISSUE TITLE
Shaka Packager sends an incorrect Content-Type header while making a key request

### ISSUE THREAD

**Issue by KristjanJ** [google/shaka-packager#372]
## System info
**Operating System**: Windows 10 build 1709
**Shaka Packager Version**: 2.0.2

## Issue and steps to reproduce the problem
Shaka Packager makes a request to the Key Server using the HTTP header 'Content-Type: text/xml' while it is JSON content. In an older version it used to be 'application/x-www-form-urlencoded'. In any case, the correct one would be 'application/json'.

**Packager Command**:
packager-win
in=captain.mp4,stream=audio,init_segment=captain_audio/init.mp4,segment_template=captain_audio/$Number$.m4s
in=captain.mp4,stream=video,init_segment=captain/init.mp4,segment_template=captain/$Number$.m4s
-profile on-demand
-enable_widevine_encryption
-key_server_url "..."
-content_id "39643130376364632D373835612D343830392D626462612D363038303965373361333166"
-signer "widevine_test"
-aes_signing_key "..."
-aes_signing_iv "..."
-generate_static_mpd
-mpd_output captain.mpd

Extra steps to reproduce the problem?
None

What is the expected result?
Expected is that the Content-Type HTTP header has the value 'application/json' or is unspecified.

What happens instead?
Content-Type HTTP header has the value 'text/xml'.

**Comment by kqyang** [comment]
Looks like there is a bug. @KristjanJ Thanks for letting us know the problem. We'll fix it.

**Comment by kqyang** [comment]
Cherry-picked for v2.0.3.
