### ISSUE TITLE
Shaka Packager - Incorrect Bandwidth representation in dash manifest

### ISSUE THREAD

**Issue by jigneshdhruv** [google/shaka-packager#376]
I was evaluating Dash manifest files packaged using Shaka packager. It seems that Shaka packager is not representing correct bandwidth for video renditions.

If we have a output rendition at 4.5Mbps, it is getting represented in manifest as 3.7Mbps. I am seeing this consistently across all dash manifest. However bandwidth's are represented correctly in HLS manifest.

We are using Shaka Packager version: packager version 033fa65-release

Here is a snippet from dash manifest:
> <Representation id=“7” bandwidth=“3733213" codecs=“avc1.640028” mimeType=“video/mp4" sar=“1:1” width=“1920" height=“1080”>
       <SegmentTemplate timescale=“11988" initialization=“CBS_INSTINCT_106_AA_6CH_30M_1392407_4500/init.m4v” media=“CBS_INSTINCT_106_AA_6CH_30M_1392407_4500/seg_$Number$.m4s” startNumber=“1”>

Actual bitrate for 4500kbps mp4 is 4482kbps.
> video	H264 High@4, 2421.797 secs, 4482 kbps, 1920x1080 @ 23.975998 fps

It seems that shaka-packager has not implemented Representation@bandwidth attribute correctly for dash manifest. 

Can you please take a look and get it fixed?

Thanks.

**Comment by kqyang** [comment]
@jigneshdhruv Thanks for reporting the issue. Looks like we misinterpret Representation@bandwidth attribute.

We used average segment bitrate but we should really use max segment bitrate instead according to DASH spec:

> Consider a hypothetical constant bitrate channel of
bandwidth with the value of this attribute in bits per second
(bps). Then, if the Representation is continuously delivered
at this bitrate, starting at any SAP that is indicated either by
@startWithSAP or by any Segment Index box, a client can
be assured of having enough data for continuous playout
providing playout begins after @minBufferTime *
@ bandwidth bits have been received (i.e. at time
@minBufferTime after the first bit is received).
For dependent Representations this value specifies the
bandwidth according to the above definition for the
aggregation of this Representation and all complementary
Representations.

**Comment by jigneshdhruv** [comment]
Any ETA on this ticket?

**Comment by kqyang** [comment]
It is already done. I'll merge it today.

**Comment by jigneshdhruv** [comment]
Thanks KQ.

**Comment by kqyang** [comment]
Cherry-picked for v2.0.3.

**Comment by jigneshdhruv** [comment]
Any ETA on when fix will be reviewed and committed. Thanks.
