### ISSUE TITLE
Support End Roll Ad Insertion

### ISSUE THREAD

**Issue by vaage** [google/shaka-packager#377]
Right now ad insertion does not handle end-roll ads. The key problem is cues that come after the streams end when do not get sent downstream. For example:

```
Cues:    |       |            |
Video: [------------------]
Audio: [-----------------]
Text:  [------------]
```
The third cue will never be added as no video samples pass it allowing it to be dispatched downstream. Even in the case where there is no video:
```
Cues:    |       |            |
Audio: [--------------]
Audio: [-------------]
Text:  [------------]
```
Since all streams end before the last cue, they do not wait at a cue event, allowing it to be sent downstream.

We need a way to handle post-roll ads.

**Comment by kqyang** [comment]
I thought about it again. There is nothing we can do / we need to do here.

For DASH, the post roll can be done easily during Ad Insertion phase, by adding an Ad Period in the end.

For HLS, likewise, the post roll can be added during Ad Insertion phase, by adding a discontinuity tag in the end, followed by Ad segments. According to HLS spec, player is responsible to synchronize different streams/renditions using EXT-X-DISCONTINUITY-SEQUENCE tag.
