### ISSUE TITLE
Embedded mp4 subtitles support (dvd_subtitles)?

### ISSUE THREAD

**Issue by jakubvojacek** [google/shaka-packager#379]
## System info
**Operating System**: latest debian
**Shaka Packager Version**: packager version daac6869fb-release

## Issue and steps to reproduce the problem
I have read on shaka's repository homepage that 

> WebVTT in both text form and embedded in MP4

I have managed to package vtt subtitles quite easily however I was wondering how do subtitles embedded in mp4 work. I have MKV file that has dvd_subtitles `Stream #0:4(cze): Subtitle: dvd_subtitle, 720x576`. I tried to get them into mp4 via `ffmpeg -txt_format bitmap -i frozen.mkv -map 0:4 -c copy subs.mp4` or `ffmpeg -i frozen.mkv -map 0:4 -c copy subs.mp4` into an mp4 file (not sure which is correct, but neither works). 

**Packager Command**:
```
packager  'in=frozen.mkv_288.mp4,stream=video,init_segment=frozen.mkv_video_288.mp4,segment_template=video_288_frozen.mkv-$Number$.mp4'  'in=subs.mp4,stream=text,init_segment=srt_init.mp4,segment_template=srt_$Number$.mp4,language=cs' --mpd_output frozen.mkv.mpd --generate_static_mpd
```
I would expect that this would create playbable MPD manifest. However it ends with `Segmentation fault` instead. 

Can you please guide what part I am doing wrong (could be ffmpeg, could be packager?) and whether is this even possible to achieve?

Thank you

**Comment by vaage** [comment]
@jakubvojacek Yes, we support both reading and writing webvtt subtitles from text and mp4. Could you clarify one thing for me, which are you trying to do:
- `VTT in Text --> VTT in MP4`
- `VTT in MP4 --> VTT in MP4`
- `VTT in MP4 --> VTT in Text`

The only scenario that is not currently supported right now is `VTT in MP4 --> VTT in Text`. So as long as you are not intending to do that, it should work.

Can you supply us with the input files that you are feeding to the packager so that we can reproduce this locally?

**Comment by jakubvojacek** [comment]
After reading your post, I guess that what I want is not possible. The subtitles are not encoded in vtt but as dvd subtitles, therefore images I believe.

I have attached the sample mkv [frozen.mkv.zip](https://github.com/google/shaka-packager/files/1904475/frozen.mkv.zip) file from which I tried to get subtitles out using the ffmpeg command shared in my first post. Anyway, I am also attaching the mp4 subtitles that I have generated [subs.mp4.zip](https://github.com/google/shaka-packager/files/1904507/subs.mp4.zip)

In order for you to check why the seg fault is thrown instead of some regular error, I am also attaching all files required for the packager command from my first post [frozen.zip](https://github.com/google/shaka-packager/files/1904552/frozen.zip)

Thank you
Jakub

**Comment by vaage** [comment]
Thank you @jakubvojacek. I am going to label this as a bug to investigate why we are getting a segfault.

**Comment by vaage** [comment]
We had a partial solution for inputting MP4s, but it was not complete and would yield incorrect results. In this part of the pipeline, there was the previously mentioned segfault.

We have removed that part of the pipeline, so the seg-faulting-code is now gone, which in a way fixes the issue, so I will be closing this issue.

Right now we do not have immediate plans to add back the mp4 input code, as there has not been enough demand for it. When there is enough demand voiced from the community, we are open to scheduling the work (#405).
