### ISSUE TITLE
Split Text Segments To Align Segments When Outputting To MP4

### ISSUE THREAD

**Issue by vaage** [google/shaka-packager#382]
Right now when we output text segments to MP4, they don't align with the video and audio segments.

The problem is that (unlike with text-based text samples) we don't use the text chunker that will but the segments at segment boundaries.

We need to:
1. Change the webvtt text demuxer to output text samples so that we can use the text chunker.
2. Use the text chunker before converting the samples to mp4 boxes.

**Comment by vaage** [comment]
@kqyang Anything else you think we should add to the issue here?

**Comment by kqyang** [comment]
SGTM. I assume that we do not need any special handling to support Ad Cues with the mentioned approach.

**Comment by vaage** [comment]
Ah, yes. We will need to update the text-to-mp4 handler to pass through cue events and segment info as it did not have to do that before.
