### ISSUE TITLE
FR: Generate one file per representation per period while generating on-demand profile with cue points

### ISSUE THREAD

**Issue by KameshDevarakonda** [google/shaka-packager#384]
Currently Shaka Packager , even when cue points are specified, generates one single file per representation across all periods which is not 100% spec compliant.

Media Segments should not contain any presentation time TP that is smaller than the value of the @presentationTimeOffset, TO. However, if this is the case, then presentation of the Media Segment is expected to only take place for presentation times greater than or equal to TO.

To be 100% spec compliant, split into multiple files with every period in its own file.

**Comment by vaage** [comment]
@kqyang Is this the same as what we were talking about yesterday in regards to "Content splicing for on-demand profile"?
