### ISSUE TITLE
Packaging Live Stream UDP to HLS Output

### ISSUE THREAD

**Issue by hungphidev** [google/shaka-packager#385]
## System info
**Operating System**: Ubuntu 17.10
**Shaka Packager Version**:  222737d5b5-release
## Issue and steps to reproduce the problem

**Packager Command**:
`packager 'in=udp://239.13.0.191:5191?reuse=1,stream=audio,init_segment=audio-init.mp4,segment_template=audio-$Number$.mp4' 
'in=udp://239.13.0.191:5191?reuse=1,stream=video,init_segment=h264-init.mp4,segment_template=h264-$Number$.mp4' 
--enable_widevine_encryption --key_server_url https://license.uat.widevine.com/cenc/getcontentkey/xxx --content_id XXXX --signer xxx --aes_signing_key xxx --aes_signing_iv xxx  --profile live --single_segment=false  --hls_playlist_type live --time_shift_buffer_depth 120 --hls_master_playlist_output h264_master.m3u8`

1. The output of this process is h264_master.m3u8, stream_1.m3u8 and stream_0.m3u8. But the info of DRM encryption is `#EXT-X-KEY:METHOD=SAMPLE-AES-CTR,URI="data:text/plain;base64,AAAAm3Bzc2gAAAAA7e+xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxL5HbzXP8SEJcaIM8AL1s1noXXXXXXXXXXXXmbFwa198uWhGrB+QhJEaCG1vYml0dnZuIg81dGVzdF92dHYxX2xpdmXXXXXX=",KEYID=0xBC74EAEXXXXXXXXXXXX57C31D0A04FBB22,KEYFORMATVERSIONS="1",KEYFORMAT="urn:uuid:xxxxxxxx-xxxx-4ace-xxxx-27dcd51xxxxx"` just appeared in stream_1.m3u8 and stream_0.m3u8. 
How can I put that info to h264_master.m3u8?

2. Please give me the sort explain of `--hls_key_uri` and how can I use them!

Thank you!

**Comment by kqyang** [comment]
@hungphidev Any reason you want to put the DRM information in master playlist? They are put in the media playlists per HLS specification: https://tools.ietf.org/html/draft-pantos-http-live-streaming-23#section-4.3.2.4.

> Please give me the sort explain of --hls_key_uri and how can I use them!

Can you describe your use case first? 

`--hls_key_uri` is needed for Fairplay and Identity key (clear key). It contains a URI that specifies how to obtain the key. If you are using Widevine, this flag is not needed.
