### ISSUE TITLE
widevine encryption - shaka player demo - stall after first few chunks

### ISSUE THREAD

**Issue by stranger29** [google/shaka-packager#394]
## System info
**Operating System**: Centos 7
**Shaka Packager Version**: 2.0.3 (2.0.0 - same result)

## Issue and steps to reproduce the problem

**Packager Command**:
      ~/shaka/packager-linux \
  'in=udp://239.1.4.143:1235?reuse=1,stream=audio,init_segment=audio_init.mp4,segment_template=audio_$Time$.m4s' \
  'in=udp://239.1.4.143:1235?reuse=1,stream=video,init_segment=h264_360p_init.mp4,segment_template=h264_360p_$Time$.m4s' \
  'in=udp://239.1.4.143:1236?reuse=1,stream=video,init_segment=h264_432p_init.mp4,segment_template=h264_432p_$Time$.m4s' \
  'in=udp://239.1.4.143:1237?reuse=1,stream=video,init_segment=h264_450p_init.mp4,segment_template=h264_450p_$Time$.m4s' \
  'in=udp://239.1.4.143:1238?reuse=1,stream=video,init_segment=h264_720p_init.mp4,segment_template=h264_720p_$Time$.m4s' \
  'in=udp://239.1.4.143:1239?reuse=1,stream=video,init_segment=h264_721p_init.mp4,segment_template=h264_721p_$Time$.m4s' \
  --enable_widevine_encryption \
  --key_server_url https://license.uat.widevine.com/cenc/getcontentkey/widevine_test \
  --content_id 7465737420636f6e74656e74206964 \
  --signer widevine_test --include_common_pssh  \
  --aes_signing_key 1ae8ccd0e7985cc0b6203a55855a1034afc252980e970ca90e5202689f947ab9 \
  --aes_signing_iv d58ce954203b7c9a9a9d467f59839249   --mpd_output h264.mpd 

Extra steps to reproduce the problem?
open demo shaka player in chrome:
https://shaka-player-demo.appspot.com/demo/
put in https URL to manifest and
https://license.uat.widevine.com/cenc/getcontentkey/widevine_test
as a license server

What is the expected result?
continuous playout

What happens instead?
first 10 seconds after packaging start playing just fine, after that it stalls with Shaka Error DRM.LICENSE_REQUEST_FAILED error

Not sure if it's the packager issue but since only first few "chunks" could be played properly and player restart doesn't help looks like it.

**Comment by kqyang** [comment]
The playback license server URL is incorrect, try `//proxy.uat.widevine.com/proxy?provider=widevine_test`.

It plays fine for the first 10 seconds because of 10 seconds clear lead, i.e. the first 10 seconds are not encrypted.

**Comment by stranger29** [comment]
@kqyang 
Perfect, it's working now (still using https://license.uat.widevine.com/cenc/getcontentkey/widevine_test  for packager, but for player - proxy.uat.widevine.com/proxy?provider=widevine_test), thank you !
