### ISSUE TITLE
Segment Template with Duration

### ISSUE THREAD

**Issue by ltrayanov** [google/shaka-packager#400]
Hi, 
I am working on a project of packaging a low latency live stream. One of the suggestions that I receive was to use a SegmentTemplate with duration.  We tried that with ffmpeg and our glass to glass latency was around 2sec. Added benefit was the lower network activity since minimumUpdatePeriod was set very high.

How can we set the ShakaPackager to use a Segment Template with Duration? Any help would be greatly appreciated.

**Comment by vaage** [comment]
@ltrayanov Our segment template system currently supports Segment Number and Segment Time. I have not heard of segment template with duration. Could you explain to me how that should work?

**Comment by ltrayanov** [comment]
@vaage The manifest of the a template with duration includes info about all future segments and clients don't need to do manifest updates to learn about future segments. The ffmpeg argument is:

 -use_template 1 \        # Use templated names for output
 -use_timeline 0 \        # Dont use the segment time in the template

The segment template in the generated mpd file should look like:

 <SegmentTemplate timescale="1000000" duration="1000000" initialization="init-$RepresentationID$.mp4" media="test-$RepresentationID$-$Number%05d$.mp4" startNumber="1">
</SegmentTemplate>
 
Thats the only way I achieved a low latency live stream.

**Comment by kqyang** [comment]
@ltrayanov Looks like you are looking for SegmentTemplate with constant duration. We have experimental support for this in Shaka Packager under flags: `--allow_approximate_segment_timeline --segment_template_constant_duration`. Both flags needs to be set in addition to normal packaging command: https://google.github.io/shaka-packager/html/tutorials/live.html.

**Comment by ltrayanov** [comment]
@vaage  Sorry about that. The segment template in the generated mpd file should look like:
" <SegmentTemplate timescale="1000000" duration="1000000" initialization="init-$RepresentationID$.mp4" media="test-$RepresentationID$-$Number%05d$.mp4" startNumber="1">
</SegmentTemplate>"

**Comment by vaage** [comment]
@ltrayanov Thank you for sharing that. Did what @kqyang suggest work for you?

**Comment by ltrayanov** [comment]
@vaage I will try the flags on Tuesday next week and post an update. Thanks!

**Comment by andrea-f** [comment]
@vaage thanks for sharing the flags, I am currently running:
```packager \
  'input=forzalazio.mp4,stream=video,init_segment=video/init.mp4,segment_template=video/$Number$.m4s' \
  --segment_duration 1 \
  'input=forzalazio.mp4,stream=audio,init_segment=audio/init.mp4,segment_template=audio/$Number$.m4s' \
  --segment_duration 1 \
  --enable_widevine_decryption \
  --enable_widevine_encryption \
  --key_server_url https://license.uat.widevine.com/cenc/getcontentkey/widevine_test \
  --content_id HEXSTRING \
  --signer widevine_test \
  --aes_signing_key 1ae8ccd0e7985cc0b6203a55855a1034afc252980e970ca90e5202689f947ab9 \
  --aes_signing_iv d58ce954203b7c9a9a9d467f59839249 \
  --mpd_output manifest.mpd \
  --allow_approximate_segment_timeline \
  --segment_template_constant_duration \
```
Which gives me:
```
<?xml version="1.0" encoding="UTF-8"?>
<!--Generated with https://github.com/google/shaka-packager version 53aa775ea4-release-->
<MPD xmlns="urn:mpeg:dash:schema:mpd:2011" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:mpeg:dash:schema:mpd:2011 DASH-MPD.xsd" xmlns:cenc="urn:mpeg:cenc:2013" profiles="urn:mpeg:dash:profile:isoff-live:2011" minBufferTime="PT2S" type="dynamic" publishTime="2018-10-31T20:22:35Z" availabilityStartTime="2018-10-31T20:22:27Z" minimumUpdatePeriod="PT5S" timeShiftBufferDepth="PT1800S">
  <Period id="0" start="PT0S">
    <AdaptationSet id="0" contentType="audio" lang="en" segmentAlignment="true">
      <ContentProtection value="cenc" schemeIdUri="urn:mpeg:dash:mp4protection:2011" cenc:default_KID="00be9459-7212-5f91-903c-4199caacf619"/>
      <ContentProtection schemeIdUri="urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed">
        <cenc:pssh>AAAAPnBzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAAB4iFnBlYXJsdHZfdGVzdF9leG9wbGF5ZXJI49yVmwY=</cenc:pssh>
      </ContentProtection>
      <Representation id="0" bandwidth="326673" codecs="mp4a.40.2" mimeType="audio/mp4" audioSamplingRate="48000">
        <AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="2"/>
        <SegmentTemplate timescale="48000" initialization="audio/init.mp4" media="audio/$Number$.m4s" startNumber="1" duration="48000"/>
      </Representation>
    </AdaptationSet>
    <AdaptationSet id="1" contentType="video" width="1280" height="720" frameRate="30000/1001" segmentAlignment="true" par="16:9">
      <ContentProtection value="cenc" schemeIdUri="urn:mpeg:dash:mp4protection:2011" cenc:default_KID="110f6be6-8e27-5787-95a4-14f9bb45ff44"/>
      <ContentProtection schemeIdUri="urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed">
        <cenc:pssh>AAAAPnBzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAAB4iFnBlYXJsdHZfdGVzdF9leG9wbGF5ZXJI49yVmwY=</cenc:pssh>
      </ContentProtection>
      <Representation id="1" bandwidth="13488008" codecs="avc1.64001f" mimeType="video/mp4" sar="1:1">
        <SegmentTemplate timescale="30000" initialization="video/init.mp4" media="video/$Number$.m4s" startNumber="1" duration="30000"/>
      </Representation>
    </AdaptationSet>
  </Period>
</MPD>
```
So correctly, there are no `SegmentTimeline` tags. To serve the file I am using an hosted version of [DASHIF v1.5](https://github.com/Dash-Industry-Forum/dash-live-source-simulator) and playback on https://bitmovin.com/demos/drm.

**Comment by kqyang** [comment]
Renamed Segment Template with Duration to better reflect what this issue is. We'll be working on Low Latency with Chunked CMAF in Q1 2019, which can further reduce the latency. Stay tuned.

Closing this issue as it is addressed. Feel free to reply or re-open it if there are other questions.

**Comment by michael-riha** [comment]
@ltrayanov 
`We tried that with ffmpeg and our glass to glass latency was around 2sec`
Can you tell me how you did it?

I tried so many variations of arguments in ffmpeg without any success.
I never got a working chunked fragment with multiple `moof+mdata`-chunkes.
How to?

**Comment by kqyang** [comment]
@michael-riha You can feed the output from ffmpeg to Shaka Packager. Packager generates a chunk with multiple (moof+mdat)s if you set `segment_duration` to a multiple of `fragment_duration`.
