### ISSUE TITLE
Allow Removal of "wvtt" from CODEC

### ISSUE THREAD

**Issue by cgp1081** [google/shaka-packager#402]
## System info
Gen 3 AppleTV Devices

Though WebVTT captions are supported on these devices, content with "wvtt" in the CODEC: of #EXT-X-STREAM-INF: will not play on these devices.  Content playback error is given.

When "wvtt" is removed, content loads normally and WebVTT captions found in #EXT-X-MEDIA:TYPE=SUBTITLES work as expected.

Per HLS guidelines wvtt is optional and its exclusion will allow content to play correctly w/WebVTT captions on all Apple devices
https://developer.apple.com/library/content/documentation/General/Reference/HLSAuthoringSpec/Requirements.html
5.10. The kind of subtitles SHOULD be specified in the CODECS attribute of the associated EXT-X-STREAM-INF tags. You SHOULD use “stpp.ttml.im1t” to identify IMSC1 subtitles. You MAY use “wvtt" to identify WebVTT subtitles.

**Comment by vaage** [comment]
@cgp1081 Could you try changing it to be "wvtt" instead of ".wvtt"? It may just be that we have an off-by-one substring problem and are actually adding an invalid codec type (".wvtt" instead of "wvtt").

**Comment by cgp1081** [comment]
Let me update the original post, it is alread "wvtt'

#EXT-X-STREAM-INF:BANDWIDTH=6016584,CODECS="avc1.640028,mp4a.40.2,wvtt"

**Comment by vaage** [comment]
@kqyang How would you like to handle this. What we are doing is not against spec. This sounds more like a player problem than a packaging problem.

**Comment by cgp1081** [comment]
@vaage I do agree that its a player issue, but Apple likely won't be updating firmware on these older pre-tvOS devices - which unfortunately still have a significant amount of users.  The only way to get streams to play there is by removing the vtt.

**Comment by kqyang** [comment]
I agree with @cgp1081. It is an Apple platform issue, but unfortunately we do not have control over the Apple platform. I agree that the best solution is to workaround it in packager.

**Comment by kqyang** [comment]
Cherry-picked to v2.1.1.
