### ISSUE TITLE
[doc] live HLS example is incorrect, with '--hls_playlist_type' flag missing

### ISSUE THREAD

**Issue by osztrovszky** [google/shaka-packager#403]
## System info
**Operating System**: Debian 9.3
**Shaka Packager Version**: packager version bbd5e07-release

## Issue and steps to reproduce the problem

**Packager Command**: 
`packager   'in=udp://239.190.176.151:5000,stream=0,init_segment=0_init.mp4,segment_template=0/$Number$.m4s,playlist_name=0/main.m3u8'   'in=udp://239.190.176.151:5000,stream=1,init_segment=1_init.mp4,segment_template=1/$Number$.m4s,playlist_name=1/main.m3u8'   'in=udp://239.190.176.151:5000,stream=2,init_segment=2_init.mp4,segment_template=2/$Number$.m4s,playlist_name=2/main.m3u8'   --hls_master_playlist_output h264_master.m3u8`

What is the expected result?
Create the chunks and the playlist files.

What happens instead?
The chunks are created but no master playlist and no playlist / profile.

**Comment by vaage** [comment]
@osztrovszky Does this still happen if you use a non-UDP input?

**Comment by kqyang** [comment]
@osztrovszky You are right. That should be updated. Thanks for letting us know!

I'll keep this issue open until the document bug is fixed.
