### ISSUE TITLE
[Feature Request] HLS allow CHARACTERISTICS attribute to be set on #EXT-X-MEDIA

### ISSUE THREAD

**Issue by zshenker** [google/shaka-packager#404]
@kqyang 
In HLS the #EXT-X-MEDIA tag has a CHARACTERISTICS attribute that can be set for subtitle & audio renditions. It would be great to have support for this in Shaka Packager.

In particular initially we are interested in being able to include descriptive audio tracks in our HLS streams. I have not explored how this is represented in DASH, but would eventually want support for something similar there too.

From the HLS spec
```
CHARACTERISTICS
      The value is a quoted-string containing one or more Uniform Type
      Identifiers [UTI] separated by comma (,) characters.  This
      attribute is OPTIONAL.  Each UTI indicates an individual
      characteristic of the Rendition.

      A SUBTITLES Rendition MAY include the following characteristics:
      "public.accessibility.transcribes-spoken-dialog",
      "public.accessibility.describes-music-and-sound", and
      "public.easy-to-read" (which indicates that the subtitles have
      been edited for ease of reading).

      An AUDIO Rendition MAY include the following characteristic:
      "public.accessibility.describes-video".

      The CHARACTERISTICS attribute MAY include private UTIs.
```

**Comment by vaage** [comment]
@zshenker Thanks for suggesting this addition. I will mark it as a feature request and will add it to our backlog so that it can be reviewed during a future planning session.

As a user, do you have any suggestions on how you would want the command to look like? 

Also, do you know if DASH as a similar feature that could be paired with this? In general we try to avoid having command params that only affect HLS or DASH.

**Comment by kqyang** [comment]
The closest one I know of in DASH is `Role` and `Accessibility`, which seems to serve the same or a similar purpose but unfortunately not exactly in the same form:

```
5.8.4.2 Role

For the element Role the @schemeIdUri attribute is used to identify the role scheme employed to identify
the role of the media content component. Roles define and describe characteristics and/or structural functions of media content components.

One Adaptation Set or one media content component may have assigned multiple roles even within the same scheme.

This part of ISO/IEC 23009 defines a simple role scheme in 5.8.5.5.

In addition, this part of ISO/IEC 23009 defines other roles schemes to support signalling for multiple view
signals in 5.8.5.6.

5.8.4.3 Accessibility

For the element Accessibility the @schemeIdUri attribute is used to identify the accessibility scheme
employed. Accessibility is a general term used to describe the degree to which the DASH Media Presentation is available to as many people as possible.

NOTE Accessibility elements fulfill a very similar purpose with respect to media content
components as for Role elements, but are specifically intended for accessibility.

One Adaptation Set or one media content component may have assigned multiple accessibility purposes even within the same scheme.

This part of ISO/IEC 23009 does not define a specific accessibility scheme, but the simple role scheme in 5.8.5.5 may be used to express a minimum amount of accessibility information.
```
**5.8.5.5 DASH role scheme**

| Role@value  | Description |
| ----------------- | --------------- |
| caption | captions (see note 3 below) |
| subtitle | subtitles (see note 3 below) |
| main | main media component(s) which is/are intended for presentation if no other information is provided |
| alternate | media content component(s) that is/are an alternative to (a) main media content component(s) of the same media component type (see note 2 below) |
| supplementary | media content component that is supplementary to a media content component of a different media component type (see Note 1 below) |
| commentary | media content component with commentary (e.g. director’s commentary) (typically audio) |
| dub | media content component which is presented in a different language from the original (e.g. dubbed audio, translated captions) |

> NOTES
> 1) A normal audio/video program labels both the primary audio and video as "main". However, when the two media component types are not equally important, for example (a) video providing a pleasant visual experience to accompany a music track that is the primary content or (b) ambient audio accompanying a video showing a live scene such as a sports event, that is the primary content, the accompanying media may be assigned a "supplementary" role.
> 2) alternate media content components should carry other descriptors to indicate in what way it differs from the main media content components (e.g. a Viewpoint descriptor or a Role descriptor), especially when multiple alternate media content components including multiple supplementary media content components are available.
> 3) open (“burned in”) captions or subtitles would be marked as media type component "video" only, but having a descriptor saying “caption” or “subtitle”;

**Comment by zshenker** [comment]
@kqyang Any updates on when this feature might be implemented?

**Comment by kqyang** [comment]
@zshenker We had some discussions but the work has not been planned yet. One of pain points is the different signaling in DASH and HLS. Also, do you have answers to @vaage's question earlier?

**Comment by kqyang** [comment]
Addressed in https://github.com/google/shaka-packager/commit/273ab09f053e68904e971959a7a8ee39dd6df987.
