### ISSUE TITLE
Feature Request: always use detailed VP9 codec strings with profile info

### ISSUE THREAD

**Issue by joeyparrish** [google/shaka-packager#406]
For background, see https://github.com/WICG/media-capabilities/issues/85.  To summarize that, the MediaCapabilities API will not accept `codecs="vp9"`, even for `video/webm`.  It will require the use of a full vp9 codec string with profile info, such as `codecs="vp09.00.10.08"`.

I would like Shaka Packager to output such a string for VP9, regardless of manifest or container formats.

I checked VP9 support via `MediaSource.isTypeSupported` on Firefox, Chrome, Safari, IE, and Edge on various platforms, with both MP4 and WebM.  I found that with up-to-date browsers, any platform that supports `codecs="vp9"` also supports `codecs="vp09.00.10.08"`.

The browsers which currently support VP9 are Chrome, Firefox, and Edge.  Since all of those are "evergreen" browsers which auto-update, I don't think we need to be concerned about compatibility with older versions of those browsers that might not understand the new codec strings.

If an older version of Chrome or Firefox were still in use by a small segment of users, service providers that target multiple browsers would almost certainly have MP4/H.264 content available as a fallback, and those older browsers could still use that.

Therefore I expect this is a low-risk change.

**Comment by vaage** [comment]
@joeyparrish Thank you for bringing this to our attention.

I have labeled this work as an "enhancement" and have put it in our backlog so that it will be taken into consideration during our next planning session.

**Comment by suzande** [comment]
Content was tested replacing the Media Identifier of "vp9" to codecs="vp09.00.10.08" in the --mpd_output *.mpd file.  Verified playback using Shaka Player v2.4.0-uncompiled, ExoPlayer V1 and ExoPlayer V2.

**Comment by kqyang** [comment]
@suzande Thanks for the verification!

**Comment by kqyang** [comment]
Cherry-picked to v2.1.1.
