### ISSUE TITLE
HLS master playlist doesn't have the protocol version

### ISSUE THREAD

**Issue by vladimir-kazakov** [google/shaka-packager#407]
When creating fMP4 HLS content (at least 1 audio and 1 video stream), I noticed that the master playlist file doesn't have the protocol version specified in the EXT-X-VERSION tag. This tag is completely missing, which is wrong, because according to the [HLS standard](https://tools.ietf.org/html/rfc8216), section 4.3.1.2, this tag "MUST appear in all Playlists containing tags or attributes that are not compatible with protocol version 1 to support interoperability with older clients". The master playlist does contain tags that were added in later versions of the protocol. Moreover, support for fMP4 was added starting from the protocol version 7, according to the following article: https://developer.apple.com/library/content/qa/qa1752/_index.html. So, the master playlist must contain the EXT-X-VERSION tag with the correct version of the protocol.

I'm using 64-bit Ubuntu 16.04 and Shaka Packager 55050fe-release.

**Comment by kqyang** [comment]
@vladimir-kazakov Thanks for bringing this up. I don't think it is necessary to include EXT-X-VERSION in master playlist.

> MUST appear in all Playlists containing tags or attributes that are not compatible with protocol version 1 to support interoperability with older clients

Yes, that is the guideline we need to follow, but I don't think there is any tags or attributes that are not compatible with protocol version 1 in master playlist.

> The master playlist does contain tags that were added in later versions of the protocol. 

Can you list the tags that you think are not compatible with version 1? 

Here is the list of version-compatibility flags: https://tools.ietf.org/html/draft-pantos-http-live-streaming-20#section-7.

In https://developer.apple.com/library/content/qa/qa1752/_index.html, it lists the new features included in each version. It actually says that:

> You need only specify the protocol version that is required for backward compatibility of a given feature. 

Some of the features / tags are backward compatible, like "SUBTITLES" mentioned in the example, which is ignored on older versions.

> support for fMP4 was added starting from the protocol version 7 (should be 6 actually)

Version 6 adds support for EXT-X-MAP in a Media Playlist that does not contain EXT-X-I-FRAMES-ONLY. EXT-X-MAP will be present in the media playlist referenced by master playlist, but not in the master playlist. Master playlist does not include any features / tags that are incompatible to version 1.

Correct me if I am wrong!

**Comment by vladimir-kazakov** [comment]
@kqyang, my initial comment is based on the figure 2, from the [understanding the EXT-X-VERSION tag](https://developer.apple.com/library/archive/qa/qa1752/_index.html) article. According to it, here's the list of things that I see that appeared after the first version of the HLS protocol:
* The RESOLUTION attribute of the EXT-X-STREAM-INF tag. (v2)
* The EXT-X-MEDIA tag. (v4)
* The AUDIO attribute of the EXT-X-STREAM-INF tag. (v4)
* The CHANNELS attribute of the EXT-X-MEDIA tag. (v7)
* Support for fMP4. (v7)

Sure, the section 7 in the HLS standard tells us:
> The EXT-X-MEDIA tag and the AUDIO, VIDEO, and SUBTITLES attributes of the EXT-X-STREAM-INF tag are backward compatible to protocol version 1, but playback on older clients may not be desirable.  A server MAY consider indicating an EXT-X-VERSION of 4 or higher in the Master Playlist but is not required to do so.

But, first of all, more features appeared that are not mentioned in this quote. Second, the backwards compatibility of some features is questionable. For example, fMP4 won't work on clients that don't support at least the 7th version of the protocol. Another example: the EXT-X-MEDIA tag, which often defines how to access audio streams. As content providers or consumers, are we interested in playback without audio?

The backwards compatibility is actually a very interesting topic. I do understand that there may be cases when we want to say to the client "just play whatever you can, ignoring everything you don't understand", but at the same time, I also see cases when "don't play it, if you don't support everything" is needed. The last one is also useful for testing which content is supported by which platforms. The presence of the version tag is also an explicit indication for a person that more advanced features are used, which may require more modern platforms. Perhaps, Shaka Packager could allow users to specify whether they want the version tag in the master playlist or not? This would make it possible to support both cases.

> support for fMP4 was added starting from the protocol version 7
>> (should be 6 actually) Version 6 adds support for EXT-X-MAP in a Media Playlist that does not contain EXT-X-I-FRAMES-ONLY.

The EXT-X-MAP is used when using fMP4, but strictly speaking, it's not only for fMP4. These are two different features, and according to the figure 2, fMP4 appeared in v7.

**Comment by kqyang** [comment]
@vladimir-kazakov There are three different types of versions mentioned in article [understanding the EXT-X-VERSION tag](https://developer.apple.com/library/archive/qa/qa1752/_index.html):

- Spec version: This is the version of the HLS specification. The latest version is 23.
- iOS version: iOS platform version.
- HLS protocol compatibility version: This is the HLS protocol compatibility version, sometimes simplified as compatibility version or protocol version, which appears in EXT-X-VERSION.

Figure 2 describes the updates in the spec - the protocol is not necessary updated in each spec update. And yes, fMP4 support is related to EXT-X-MAP support, but they are different. fMP4 is introduced in HLS spec 20 and iOS version 10, but there is no need for HLS protocol update to support that as HLS protocol compatibility version 6 is sufficient to support it.

> For example, fMP4 won't work on clients that don't support at least the 7th version of the protocol. 

As mentioned above, it is possible for a player supporting HLS protocol compatibility version 6 only to support fMP4 as long as it is supported in the underlying client. This happens on various HLS javascript players, e.g. hls.js, Shaka Player support fMP4 playback on Chrome as long as it understands HLS protocol compatibility version 6.

> Another example: the EXT-X-MEDIA tag, which often defines how to access audio streams. As content providers or consumers, are we interested in playback without audio?

That is not desirable, but you may not have an option here. The first choice is always to update the player on the client to support it, but the player may not be update-able. In this case, I think having video only is always better than having nothing on the client.

> I do understand that there may be cases when we want to say to the client "just play whatever you can, ignoring everything you don't understand",

I think it is very important and that is why Apple designs HLS protocol to be backward compatible. 

> but at the same time, I also see cases when "don't play it, if you don't support everything" is needed

I don't think it is practical as you typically don't have control on all the clients unless you are only interested in making the content work on a particular device, which you have full control with. The usage scenario may exist, but I think it will be rare. Even in this case, I don't see a benefit of disallowing backward compatibility.

> The last one is also useful for testing which content is supported by which platforms. The presence of the version tag is also an explicit indication for a person that more advanced features are used, which may require more modern platforms.

There is "EXT-X-VERSION" specified in the media playlist, which should be sufficient for this purpose.

> Perhaps, Shaka Packager could allow users to specify whether they want the version tag in the master playlist or not? 

As explained above, I don't see it useful, and it could be confusing if it is not designed carefully.

**Comment by vladimir-kazakov** [comment]
> This is the version of the HLS specification. The latest version is 23.

If I understand correctly, all these versions up to 23 are drafts. The final version is [RFC 8216](https://tools.ietf.org/html/rfc8216).

> Figure 2 describes the updates in the spec - the protocol is not necessary updated in each spec update.

Well, if new things appear in the protocol after its initial release, it looks to me as the protocol was updated. Yes, its version stayed the same, but it now has more features that clients don't know about.

> fMP4 is introduced in HLS spec 20 and iOS version 10, but there is no need for HLS protocol update to support that as HLS protocol compatibility version 6 is sufficient to support it.

But clients that support protocols up to v6 won't be able to play it. To play such content, they'll have to support v7. If so, then why not mention it in the EXT-X-VERSION? This change is not backwards compatible.

I actually even tried playing fMP4 content on iOS 9.3.5, and, as expected, it failed. According to the figure 2, this client supports the protocol v7, but this support is incomplete, since there were updates to the protocol after that. So, in order to play such content, the client must have a more complete support for the protocol v7. What this tells us is that just saying that v7 is required is not 100% correct, but at the same time, it seems to me that it's still better than saying that v6 is required or not saying anything at all.

**Comment by kqyang** [comment]
> If I understand correctly, all these versions up to 23 are drafts. The final version is RFC 8216.

Correct. The draft version is used Apple in various places, including figure 2 you quoted earlier.

> Well, if new things appear in the protocol after its initial release, it looks to me as the protocol was updated. Yes, its version stayed the same, but it now has more features that clients don't know about.

You are mixing spec versions with protocol compatibility versions. HLS spec 23 != protocol compatibility version 7.

In fact, HLS spec defines the behavior for all the HLS protocol compatibility versions up to the max version supported by that version of HLS spec.

> But clients that support protocols up to v6 won't be able to play it. To play such content, they'll have to support v7. 

No, that is not true. Shaka Packager actually sets EXT-X-VERSION to 6 and it works. 

> If so, then why not mention it in the EXT-X-VERSION? This change is not backwards compatible.

Not sure what you mean here.

> I actually even tried playing fMP4 content on iOS 9.3.5, and, as expected, it failed. According to the figure 2, this client supports the protocol v7, but this support is incomplete, since there were updates to the protocol after that. 

It is not that there were protocol updates, but instead there were feature updates in the device, or in another word, the HLS draft spec version the device supports. The behavior difference you observed on iOS 9.3.5 and iOS 10.3.1 is because they support different HLS spec versions (HLS spec version 19 vs HLS spec version 23) although they support the same exact HLS protocol compatibility version 7.

**Comment by vladimir-kazakov** [comment]
@kqyang, thank you for this interesting and useful discussion. It helped me to better understand the role of the EXT-X-VERSION tag.

I guess I just had very high expectations for this tag. I was thinking about using it as a guarantee that all features of content will be supported by a client. In case if some feature is not supported, there's no point to play such content. Now I see that it's not possible just by using the protocol version. I guess the safer approach, in this case, is to target a specific minimal version of the client that supports all features that the content uses.

I agree that the current behavior of Shaka Packager is correct and according to the section 7 of the HLS specification. So, there's no need to change anything.
