### ISSUE TITLE
Docker hub instructions link broken

### ISSUE THREAD

**Issue by aibanez** [google/shaka-packager#408]
## System info
N/A

## Issue and steps to reproduce the problem
Instructions link in docker hub is broken

Extra steps to reproduce the problem?
(1) Go to https://hub.docker.com/r/google/shaka-packager/
(2) Click on "Using Docker.
Instructions are **available here**."

What is the expected result?
Access to the documentation [link](https://github.com/google/shaka-packager/blob/master/docs/source/docker_instructions.md)
What happens instead?
https://hub.docker.com/r/google/shaka-packager/docs/source/docker_instructions.md/ gives 404

**Comment by kqyang** [comment]
That is because relative url is used in README file. We'll switch to absolute url instead.

Thanks for reporting the problem!
