### ISSUE TITLE
Exoplayer is pausing frequently after 10~ 20 seconds with Shaka packager LiveStreaming mpd

### ISSUE THREAD

**Issue by WhiteDove101** [google/shaka-packager#409]
I have a problem with Exoplayer.
It's pausing frequently every 20s with live streaming packager command after I use the updated packager.
Please let me know how I can solve this problem.

**Comment by vaage** [comment]
@WhiteDove101 I am sorry to hear that you are having issues. What I would suggest you start with is:

Check if the content has problems with other players. I would personally suggest [Shaka Player](https://github.com/google/shaka-player). They have a live demo which you may be able to use. Here is a [link](https://shaka-player-demo.appspot.com/demo/#build=uncompiled) to demo.

If Shaka Player has problems too, then there may be is something wrong with the content and then we can take a closer look there.

However, if Shaka Player can play it, I would suggest you talk to the ExoPlayer project. Here is the [link](https://github.com/google/ExoPlayer) to their GitHub page.
