### ISSUE TITLE
'/usr/bin/python src/packager/third_party/binutils/download.py' returned non-zero exit status 1

### ISSUE THREAD

**Issue by mdaftab88** [google/shaka-packager#412]
## System info
**Operating System**: Ubuntu 16.04

## Issue
Hi all,

I apologise for asking a silly question but I stuck very badly that's why I'm here. 

I am trying to build shaka-packager by following the instructions given at [https://github.com/google/shaka-packager/blob/master/docs/source/build_instructions.md](https://github.com/google/shaka-packager/blob/master/docs/source/build_instructions.md)

I have installed **depot_tools** inside ~/bin/ directory and also trying to do all the setup for installing **shaka-packager** inside the same ~/bin/ directory.

My directory structure is like below:

> /home/aftab
>   &nbsp; &nbsp; &nbsp; &nbsp;|---- bin
>   &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp; &nbsp;|---- depot_tools
>   &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp; &nbsp;|---- shaka-packager
> 

When I fire `gclient sync`, I am getting an error
```
OSError: [Errno 2] No such file or directory
Error: Command '/usr/bin/python src/packager/third_party/binutils/download.py' returned non-zero exit status 1 in /home/aftab
![evan-kirby-263913](https://user-images.githubusercontent.com/25167441/41341864-66240f5e-6f18-11e8-9805-269314c75e6a.jpg)

![error](https://user-images.githubusercontent.com/25167441/41342268-78e4434c-6f19-11e8-9c5e-b8ba595da1c5.png)
/bin/shaka_packager
```
I too have updated my _.bashrc_ file as below:

`export PATH="$PATH:$HOME/bin/depot_tools"`

I'm also sharing screenshot of the error. 

![error](https://user-images.githubusercontent.com/25167441/41342304-89515eea-6f19-11e8-9ac9-8e93df1cbaed.png)

Please help and thanks in advance.

**Comment by mdaftab88** [comment]
I resolved the issue by doing all the stuff inside my home directory ( despite of doing it inside ~/bin/ directory). I don't know what was wrong doing it inside ~/bin directory.

If anyone knows then please explore it.

**Comment by kqyang** [comment]
That is weird. We haven't seen similar issues before. I wonder what happens when you invoke `download_from_google_storage` directly, i.e.

```bash
❯ download_from_google_storage --no_resume --no_auth --bucket chromium-binutils -s /home/aftab/bin/shaka-packager/src/packager/third_party/binutils/Linux_x64/binutils.tar.bz2.sha1
```

**Comment by kdHub** [comment]
I also was observing this when building using gclient. In my case having depot_tools in the shaka directory was root cause of this output and moving it to proper location outside the shaka_package directory resolved my issue after update to bashrc with export PATH="$PATH:$HOME/bin/depot_tools"

**Comment by Sectur1** [comment]
![screenshot from 2018-07-23 13-53-09](https://user-images.githubusercontent.com/22817492/43085984-32f41dea-8e94-11e8-89ad-3ba22d5830af.png)
I have the same issue. Above is my screenshot
