### ISSUE TITLE
Opus + ISO-BMFF + MSE

### ISSUE THREAD

**Issue by gregorym** [google/shaka-packager#414]
Hi,

I am interested in using Opus ISE-FMFF with the Media Source Extensions. Where can find if browsers (Firefox & Chrome) are working on MSE support?

**Comment by kqyang** [comment]
I think it is already supported in Firefox. Let us know if you are seeing any problems.

I don't think there is plan to support Opus in ISO-BMFF with MSE in Chrome right now. You can follow up on this Chromium issue: https://bugs.chromium.org/p/chromium/issues/detail?id=649438.
