### ISSUE TITLE
Raw key and key rotation

### ISSUE THREAD

**Issue by jakubvojacek** [google/shaka-packager#415]
Hello,

this is not mentioned in the documentation but I believe I read it somewhere - is it possible to use raw keys and key rotation for live content? Think it can be done by providing multiple PSSH's but in the PSSHs, there needs to be information about the period index / count / seconds. Is it possible to generate these PSSHs using pssh-box.py tool or is this even possible at all?

Thank you

**Comment by vaage** [comment]
@jakubvojacek, thanks for the question. As this is a very domain-specific question, I will need @kqyang to chime in on it.

**Comment by kqyang** [comment]
@jakubvojacek We do support key rotation with raw key, but it uses a very naive key rotation algorithm: https://github.com/google/shaka-packager/blob/master/packager/media/base/raw_key_source.cc#L73. It is designed for testing, and should not be used in production. 

To make it ready for production use, the keys and PSSHs for all periods should be provided to packager. One option I can think of is to have a file with keys; the file will be updated periodically by an external script to rotate the keys; packager can re-load the file with updated keys when crossing crypto periods.

That said, the user is still responsible for managing the keys as in the standard non-key rotation raw key scenario. 

I'd suggest using Widevine managed keys if it works for you: https://google.github.io/shaka-packager/html/tutorials/widevine.html. It is simpler and it already supports key rotation. 

> Is it possible to generate these PSSHs using pssh-box.py tool or is this even possible at all?

Not supported right now, but that is certainly doable.

**Comment by jakubvojacek** [comment]
We might be wanting to use multidrm in the future (widevine + playready + ..) for which we need to be managing the keys ourselves, I believe. That is why I was considering using our own keys and not the widevine's service.

At the cwip training, I got an impression that most partners generate their own keys. What is the general practice that you see? For now, we will go only with widevine so might as well let widevine generate and manage the keys, I guess.

**Comment by kqyang** [comment]
> We might be wanting to use multidrm in the future (widevine + playready + ..)

I see.

We added support for playready pssh generation with widevine managed keys (`--enable_widevine_encryption`) recently with flag `--generate_playready_pssh`. So you can potentially use multi-drm with widevine managed keys (your playready server needs to talk to Widevine backend to get the keys though in license time).  Similarly for playready managed keys and your own managed keys.

> At the cwip training, I got an impression that most partners generate their own keys. What is the general practice that you see?

I think that is probably true at this moment, but that is for non key rotation. For key rotation, I recommend using Widevine managed keys for simplicity.

**Comment by jakubvojacek** [comment]
@kqyang already using key rotation using widevine key servers (at least think so, got `crypto_period_duration` set for 60 for testing purposes and it's all playing well). Should I observe something different in the MPD when using key rotation? Because right now it seems to be quite the same.

Please feel free to close this in case you do not want to work on supporting raw key and key rotation properly.

Thank you!

**Comment by kqyang** [comment]
That is great. Thanks for the update.

> Should I observe something different in the MPD when using key rotation? 

Yes, there is a difference: we do not put the PSSH in MPD when key rotation is enabled as PSSH changes every time key rotates.

I'll close this issue for now as we have no plan to work on it in foreseeable future (of course, it could change if there is a strong demand - we can always re-open it if it is needed).

**Comment by jsvictor** [comment]
Hi all,

I intend to serve my content using Google Widevine, and use the key rotation feature.
Does Google Widevine License server also generate keys? I understand that the license server/ key management server from Google Widevine provides the encryption key to:
1. Packager (for encryption of content) and 
2. Client (in the form of license, for decryption)

However, to deliver encrypted content to my client devices, can Widevine license server also generate keys for my content and deliver them to packager? Or do I have to generate the keys myself and host the keys on license server? 

Any help would be highly appreciated!

Regards,
John

**Comment by jakubvojacek** [comment]
@jsvictor yes, widevine does generate & store the keys if requested, please refer to the documentation here https://google.github.io/shaka-packager/html/tutorials/widevine.html#examples

**Comment by jsvictor** [comment]
@jakubvojacek thank you for your quick response!

I am trying to encrypt my content using key rotation. Can Google Widevine key server generate multiple keys and give it to Shaka Packager? Also, how will the Widevine license server get those keys for generating license for the client devices?

**Comment by jakubvojacek** [comment]
@jsvictor as per the documentation, the only thing you need to add to the packager command to enable key rotation is `crypto_period_duration` (in seconds). The packager itself will take care of getting keys from widevine servers periodically and encrypting the content it with. 

as per the decryption on client devices, you do not need to implement anything different when playing content with key rotation. The end device player (whether its shaka player, android exoplayer, ...) will be issuing license requests to the widevine proxy (which for widevine test credentials is https://proxy.uat.widevine.com/proxy) with content keys and the proxy will be returning correct licenses. 

You can find more information and documentation (as well as sample python proxy) on the cwip portal (but you need to be part of the cwip program in order to access most of these).

**Comment by jsvictor** [comment]
@jakubvojacek Thank you for the detailed explanation. 
Is the Widevine license server (which distributes license to clients via proxy) same as the Widevine Key server which generates keys?

**Comment by jakubvojacek** [comment]
@jsvictor  yes, it is
