### ISSUE TITLE
Windows build failed with Ninja

### ISSUE THREAD

**Issue by Jason239** [google/shaka-packager#419]
I don't know if it's right to ask a question here.
I have a question about building on Windows
I was succeeded to build binary immediately on Ubuntu.
but on Windows, failed.
After entering the command 'ninja -C out \ Release_x64', an error occurs during the build with 'The warn is treated as an error and no generated 'object' file exists.' message.
especially, most of this errors were files in 'boringssl'.
I tried to edit .gyp scripts, but it didn't work.

what should I do?

**Comment by kqyang** [comment]
@LeeSangGoo Thanks for filing the issue. Can you provide more information? For example, (1) Windows version. (2) Packager source code revision. (3) The error messages.

**Comment by LeeSangGoo** [comment]
@kqyang  Thanks for your quick reply. 
This is the execution environment.

(1) Windows version : Windows 10 Pro, x64
(2) Packager source code revision : Latest version(6b4a75b6bacdac6b0b9f598c365c8f84f0a7fd70)
(3) Visual Studio version : 2015 Professional v14.0.25431.01 Update 3
(4) The error messages : 
[failed_log.txt](https://github.com/google/shaka-packager/files/2140434/failed_log.txt)

Please tell me if you need any more information.

**Comment by kqyang** [comment]
@LeeSangGoo Thanks for the info! 

Here is what I saw from the log:

```bash
d:\works\shaka_packager\src\packager\third_party\boringssl\src\crypto\internal.h: error C2220: °æ°í°¡ ¿À·ù·Î Ã³¸®µÇ¾î »ý
¼ºµÈ 'object' ÆÄÀÏÀÌ ¾ø½À´Ï´Ù.
d:\works\shaka_packager\src\packager\third_party\boringssl\src\crypto\internal.h: warning C4819: ÇöÀç ÄÚµå ÆäÀÌÁö(949)¿¡
¼­ Ç¥½ÃÇÒ ¼ö ¾ø´Â ¹®ÀÚ°¡ ÆÄÀÏ¿¡ µé¾î ÀÖ½À´Ï´Ù. µ¥ÀÌÅÍ°¡ ¼Õ½ÇµÇÁö ¾Ê°Ô ÇÏ·Á¸é ÇØ´ç ÆÄÀÏÀ» À¯´ÏÄÚµå Çü½ÄÀ¸·Î ÀúÀåÇÏ½Ê½Ã¿À.
...
d:\works\shaka_packager\src\packager\third_party\boringssl\src\crypto\base64\base64.c: error C2220: °æ°í°¡ ¿À·ù·Î Ã³¸®µÇ
¾î »ý¼ºµÈ 'object' ÆÄÀÏÀÌ ¾ø½À´Ï´Ù.
d:\works\shaka_packager\src\packager\third_party\boringssl\src\crypto\base64\base64.c: warning C4819: ÇöÀç ÄÚµå ÆäÀÌÁö(9
49)¿¡¼­ Ç¥½ÃÇÒ ¼ö ¾ø´Â ¹®ÀÚ°¡ ÆÄÀÏ¿¡ µé¾î ÀÖ½À´Ï´Ù. µ¥ÀÌÅÍ°¡ ¼Õ½ÇµÇÁö ¾Ê°Ô ÇÏ·Á¸é ÇØ´ç ÆÄÀÏÀ» À¯´ÏÄÚµå Çü½ÄÀ¸·Î ÀúÀåÇÏ½Ê
½Ã¿À.
...
d:\works\shaka_packager\src\packager\third_party\boringssl\src\include\openssl\aead.h: error C2220: °æ°í°¡ ¿À·ù·Î Ã³¸®µÇ
¾î »ý¼ºµÈ 'object' ÆÄÀÏÀÌ ¾ø½À´Ï´Ù.
d:\works\shaka_packager\src\packager\third_party\boringssl\src\include\openssl\aead.h: warning C4819: ÇöÀç ÄÚµå ÆäÀÌÁö(9
49)¿¡¼­ Ç¥½ÃÇÒ ¼ö ¾ø´Â ¹®ÀÚ°¡ ÆÄÀÏ¿¡ µé¾î ÀÖ½À´Ï´Ù. µ¥ÀÌÅÍ°¡ ¼Õ½ÇµÇÁö ¾Ê°Ô ÇÏ·Á¸é ÇØ´ç ÆÄÀÏÀ» À¯´ÏÄÚµå Çü½ÄÀ¸·Î ÀúÀåÇÏ½Ê
½Ã¿À.
```

According to https://msdn.microsoft.com/en-us/library/ms173715.aspx
> The file contains a character that cannot be represented in the current code page (number). Save the file in Unicode format to prevent data loss.
>
> C4819 occurs when an ANSI source file is compiled on a system with a codepage that cannot represent all characters in the file.

I checked these files and there are indeed non-ASCII characters in the comment section of these files. It is safe to just suppress the warning during compilation. We'll prepare a fix soon.

In the mean while, if you want to try, you can edit the source code yourself to suppress the warning:

```diff
--- c/packager/third_party/boringssl/boringssl.gyp
+++ w/packager/third_party/boringssl/boringssl.gyp
@@ -34,7 +34,7 @@
       },
       # TODO(davidben): Fix size_t truncations in BoringSSL.
       # https://crbug.com/429039
-      'msvs_disabled_warnings': [ 4267, ],
+      'msvs_disabled_warnings': [ 4267, 4819, ],
       'conditions': [
         ['component == "shared_library"', {
           'defines': [
@@ -73,7 +73,7 @@
       'dependencies': [ 'boringssl_asm' ],
       # TODO(davidben): Fix size_t truncations in BoringSSL.
       # https://crbug.com/429039
-      'msvs_disabled_warnings': [ 4267, ],
+      'msvs_disabled_warnings': [ 4267, 4819, ],
       'conditions': [
         ['component == "shared_library"', {
           'defines': [
```

**Comment by LeeSangGoo** [comment]
@kqyang 

Is it correct to add the error code inside the boringssl.gyp file?
I've run Ninja after edit it, but the same warning occurred..
And, how about C2220 error? 
Is there any solution about that error..? 
Do I need to install something on my local machine?

**Comment by kqyang** [comment]
Ah, you need to run `gclient runhooks` before running `ninja`. This updates the build files, which is necessary after changing gyp files.

C2220 is the result of C4819, so it will be gone after fixing C2220.

There could be C4819 in other third_party modules though, but we can address them one by one.

**Comment by LeeSangGoo** [comment]
oh, I see. Thank you for your detailed explanation.

So I fixed some modules, and It but I've been in trouble again at 'gtest'.
I already added 'msvs_disabled_warnings': [ 4819, ]' in gtest.gyp, 
but the same error continues to occur. (error C2220, warning C4819)

I edited it like this,

 ```
 'includes': [
    'gtest.gypi',
  ],
  'targets': [
    {
      'target_name': 'gtest',
      'toolsets': ['host', 'target'],
      'type': 'static_library',
      'msvs_disabled_warnings': [ 4267, 4819, ],        # here
      'sources': [
        '<@(gtest_sources)',
      ],
     ...
```

I haven't used gyp, so I don't know well.. Is it wrong?

**Comment by kqyang** [comment]
Thanks for trying. That looks correct.

Can you post the whole build log?

You may also send a pull request so we can review your change.

**Comment by LeeSangGoo** [comment]
Here is it.
[gtest_error_log.txt](https://github.com/google/shaka-packager/files/2157496/gtest_error_log.txt)

I edited only that part.

**Comment by kqyang** [comment]
@LeeSangGoo Thanks for the log. It is because the header file is indirectly included in another module, i.e. in a dependent module, so you'll need to modify the dependent settings in line 196 of gtest.gyp: https://github.com/google/shaka-packager/blob/master/packager/testing/gtest.gyp#L196.  Let us know if it works if you add 4819 there too.

**Comment by kqyang** [comment]
@LeeSangGoo That is great! I am a bit surprised that you have to update almost all modules though. Can you try if you can get it work by just having the below change?

```diff
--- c/packager/common.gypi
+++ w/packager/common.gypi
@@ -61,6 +61,10 @@
             '-Wno-unguarded-availability',
           ],
         },
+        'msvs_disabled_warnings': [ 4819, ],
+        'direct_dependent_settings': {
+          'msvs_disabled_warnings': [ 4819, ],
+        },
         'conditions': [
           ['clang==0', {
             'cflags': [
```

As for the link error with 64-bit build, is your system 32-bit or 64-bit? You won't be able to build for 64-bit if your operation system is 32-bit. You can build for both 32-bit and 64-bit if your system is 64-bit.

**Comment by LeeSangGoo** [comment]
@kqyang  I got the source again and tried to build it again by modifying only that part, but I get 4819 from modules as 'base', 'media'. 

And.. my system is x64, but I'll use x86 build. So It's okay. Thank you very much!

**Comment by LeeSangGoo** [comment]
I do not know if I should send a pull request with msvs_disabled_warnings added for all modules, but I will close the issue. 
Thank you so much for your support.

**Comment by kqyang** [comment]
@LeeSangGoo Thanks for putting your effort in resolving the problem yourself. If you can send a pull request, it will be really appreciated.

As  for the x86/x64 build, I am not very familiar with Windows command shell, I am afraid that the setting for GYP_DEFINES may not be carried forward, so another thing you can try is to set GYP_DEFINES and `gclient runhooks` in a single command:

```bash
GYP_DEFINES='target_arch=x64' gclient runhooks
ninja.exe -C .\out\Release_x64\
```
