### ISSUE TITLE
MP2 is not passed in Shaka packger command.

### ISSUE THREAD

**Issue by WhiteDove101** [google/shaka-packager#421]
Hi
I tried to play the ts file by using shaka packager.
When I use this the input audio codec is mp2.
Shaka packger shows error with audio codec but if I change the input stream or file then it works perfectly.
Can you please let me know how can I process the mp2 audio in shaka packager?
I am waiting good helps here.
Thanks.

**Comment by kqyang** [comment]
Unfortunately, Shaka Packager does not support mp2 audio right now. I don't think it is supported in Chrome MSE either.

You'll need to transcode the audio to aac or other supported codecs.
