### ISSUE TITLE
Empty segmentTemplate when subtitle file is empty

### ISSUE THREAD

**Issue by jakubvojacek** [google/shaka-packager#422]
## System info
**Operating System**: latest debian
**Shaka Packager Version**: version 1600909c4b-release (master)

## Issue and steps to reproduce the problem
Packaging VOD (actually a catchup event, but thats like VOD) with subtitles. But there happened to be no subtitles available in the event's timeframe. Therefore the `vtt` file was empty. The content was packaged successfully but the generated MPD is not playable via shaka player (plays with dashjs though) due to `SegmentTemplate does not contain any segment information: the SegmentTemplate must contain either an index URL template a SegmentTimeline, or a segment duration. ` I am attaching sample MPD for reference [2018-06-30-17-29-412343-euromaxx.mpd.txt](https://github.com/google/shaka-packager/files/2152144/2018-06-30-17-29-412343-euromaxx.mpd.txt).

Is this an issue in shaka packager or shaka player? One possible workaround would be to check the generated vtt file before packaging and remove the subtitle portion of the command but would like to avoid that. 

**Packager Command**:
```
packager  'in=/data/assets/channels//ct24-9/recordings/2018/06/30/2018-06-30-18-00-412345-zpravy/output.mp4,stream=0,init_segment=2018-06-30-18-00-412345-zpravy_video_640_360.mp4,segment_template=video_640_360/video_640_360_2018-06-30-18-00-412345-zpravy-$Number$.mp4' 'in=/data/assets/channels//ct24-9/recordings/2018/06/30/2018-06-30-18-00-412345-zpravy/output.mp4,stream=1,init_segment=2018-06-30-18-00-412345-zpravy_video_720_410.mp4,segment_template=video_720_410/video_720_410_2018-06-30-18-00-412345-zpravy-$Number$.mp4' 'in=/data/assets/channels//ct24-9/recordings/2018/06/30/2018-06-30-18-00-412345-zpravy/output.mp4,stream=2,language=cs,init_segment=2018-06-30-18-00-412345-zpravy_audio_cs.mp4,segment_template=audio/audio_cs_2018-06-30-18-00-412345-zpravy-$Number$.mp4' 'in=/data/assets/channels//ct24-9/recordings/2018/06/30/2018-06-30-18-00-412345-zpravy/output.vtt,stream=text,init_segment=2018-06-30-18-00-412345-zpravy_subtitle_init.mp4,segment_template=subtitle/ttv_$Number$.m4s,language=cs' --mpd_output 2018-06-30-18-00-412345-zpravy.mpd --generate_static_mpd --hls_master_playlist_output 2018-06-30-18-00-412345-zpravy.m3u8 --fragment_duration 3.2 --segment_duration 3.2  --suggested_presentation_delay 5 --min_buffer_time 3.2 --minimum_update_period 5 --default_language=cs
```

**Comment by kqyang** [comment]
@jakubvojacek This is similar to this feature request https://github.com/google/shaka-packager/issues/354. We are hesitant to support things like this directly in Shaka Packager as we think it is better to be handled outside of packager. We think it is better for usability and clarity with the assumption that If the stream is provided to Shaka Packager, then it should be a valid stream and it should be present in the generated manifest. Of course, we will reconsider the decision if there are strong user requests to support this.

@joeyparrish Joey, do you think if it makes sense to support a manifest like this in Shaka Player?

**Comment by jakubvojacek** [comment]
> We think it is better for usability and clarity with the assumption that If the stream is provided to Shaka Packager, then it should be a valid stream

But the file was valid, I believe, even though empty, still valid.

When you're watching a live channel with closed captions available, you have the option to switch them off or on. When you're watching a recording of some event from the same channel, the captions should still appear as available (even when empty for given time period), that is the correct user experience in our opinion, that is why I am would like to avoid not having the subtitles generated.

**Comment by joeyparrish** [comment]
This is something that Shaka Player should be able to handle.  I'll file an issue there.

**Comment by joeyparrish** [comment]
https://github.com/google/shaka-player/issues/1484

**Comment by kqyang** [comment]
Thanks Joey! 

@jakubvojacek Your argument makes sense to me. I'll close the bug and leave it to be handled by Shaka Player. Feel free to re-open the bug or post comments if you think it is useful to handle it in packager as well.
