### ISSUE TITLE
MPD file is not generated in HLS live streaming

### ISSUE THREAD

**Issue by WhiteDove101** [google/shaka-packager#423]
Hi
I am running shaka packger command with HLS live stream.
But I can't find .mpd file.
Here is command I used.
sudo ./packager 'input=udp:///192.168.150.225:12301?reuse=1&interface=0.0.0.0,stream=audio,init_segment=./media/audio3_init.mp4,segment_template=./media/audio3_$Number$.m4s,playlist_name=audio3.m3u8,hls_group_id=audio,hls_name=ENGLISH' 'input=udp://192.168.150.225:12301?reuse=1&interface=0.0.0.0,stream=video,init_segment=./media/h264_360p3_init.mp4,segment_template=./media/h264_360p3_$Number$.m4s,playlist_name=h264_360p3.m3u8' --hls_playlist_type LIVE --hls_master_playlist_output ./media/simple.m3u8 --mpd_output ./media/ZeeMarathi-hd.mpd
Could you please let me know what the issue is?
there are only .m4s and .mp4 files.

**Comment by kqyang** [comment]
@WhiteDove101 Can you describe the issue in more detail? For example, these information will help us isolate the issue:
- Shaka Packager Version
- Operating System Version
- Do you see any error on the command line? Can you post the logging?
- Can you post a screenshot of the files that are generated?

**Comment by WhiteDove101** [comment]
Hi Kqyang,
Thank you for your reply.
- Shaka packager version : 2.1.0
- Operating System Version : atom
- I don't see any errors on the command line.
- please check the image I uploaded
![image](https://user-images.githubusercontent.com/26065238/42193640-b97ffc24-7e3d-11e8-9daa-ad51c35984c4.png)

**Comment by kqyang** [comment]
I have no idea what is going on. I have a few questions:

1. What is the difference between this setup and your previous setup mentioned in https://github.com/google/shaka-packager/issues/409? 
2. What is atom? Is it an operating system derived from Linux or from Windows, or maybe DOS?
3. There are a lot of unrelated files in the screenshot you captured above. Can you run in a clean directory? And maybe capture the list in a text file?
4. Can you try setting up --temp_dir? You can set it to a temp directory in your local folder, for example, `./media/temp/`.

**Comment by WhiteDove101** [comment]
I checked the command carefully again and it was missing some letters so I fixed it and work perfectly.
Thanks.
