### ISSUE TITLE
Not able create a content with clear key encryption

### ISSUE THREAD

**Issue by priyanshugupta27** [google/shaka-packager#424]
## System info
**Operating System**: <Ubuntu 14.04>
**Shaka Packager Version**: <e.g. v1.6.1, commit SHA etc>

## Issue and steps to reproduce the problem
Not able to create a content with clear key encryption

I used the below mentioned command:
packager \ input=test.mp4,stream=video,output=myvideo_video.mp4 \ input=test.mp4,stream=audio,output=myvideo_audio.m4a \ --enable_raw_key_encryption --enable_raw_key_decryption \ -key ffad6c3ff4ab9a5783563197e57286cc -key_id ffad6c3ff4ab9a5783563197e57286cc \ --mpd_output myvideo_vod.mpd

Extra steps to reproduce the problem?
(1)
(2)

What is the expected result?
Output should be the clear key encrypted content

What happens instead?
Getting the below error:
ERROR: --key is required if --enable_raw_key_encryption/decryption.

<Please attach the input files or email to shaka-packager-issues@google.com.>
<Please provide any additional information below.>

**Comment by kqyang** [comment]
@priyanshugupta27 It seems to be caused by "\". You don't need to have "\" if it is followed by a space. Alternatively, you can append a new line after "\".

Can you try again with "\" removed?

**Comment by priyanshugupta27** [comment]
Sorry but in the below command I am not able to see "".

packager \ input=test.mp4,stream=video,output=myvideo_video.mp4 \ input=test.mp4,stream=audio,output=myvideo_audio.m4a \ --enable_raw_key_encryption --enable_raw_key_decryption \ -key ffad6c3ff4ab9a5783563197e57286cc -key_id ffad6c3ff4ab9a5783563197e57286cc \ --mpd_output myvideo_vod.mpd

Can you please specify where you are indicating "".

**Comment by priyanshugupta27** [comment]
Attaching the manifest for reference:

<MPD xmlns="urn:mpeg:dash:schema:mpd:2011" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:cenc="urn:mpeg:cenc:2013" xsi:schemaLocation="urn:mpeg:dash:schema:mpd:2011 DASH-MPD.xsd" profiles="urn:mpeg:dash:profile:isoff-on-demand:2011" minBufferTime="PT2S" type="static" mediaPresentationDuration="PT132.96S">
<Period id="0">
<AdaptationSet id="0" contentType="video" width="720" height="404" frameRate="25000/1000" subsegmentAlignment="true" par="25:14">
<ContentProtection value="cenc" schemeIdUri="urn:mpeg:dash:mp4protection:2011" cenc:default_KID="abba271e-8bcf-552b-bd2e-86a434a9a5d9"/>
<ContentProtection schemeIdUri="urn:uuid:1077efec-c0b2-4d02-ace3-3c1e52e2fb4b">
<cenc:pssh>
AAAANHBzc2gBAAAAEHfv7MCyTQKs4zweUuL7SwAAAAGruicei89VK70uhqQ0qaXZAAAAAA==
</cenc:pssh>
</ContentProtection>
<Representation id="0" bandwidth="1312666" codecs="avc1.42c01e" mimeType="video/mp4" sar="1:1">
<BaseURL>video.mp4</BaseURL>
<SegmentBase indexRange="1107-1306" timescale="25000">
<Initialization range="0-1106"/>
</SegmentBase>
</Representation>
</AdaptationSet>
<AdaptationSet id="1" contentType="audio" subsegmentAlignment="true">
<ContentProtection value="cenc" schemeIdUri="urn:mpeg:dash:mp4protection:2011" cenc:default_KID="abba271e-8bcf-552b-bd2e-86a434a9a5d9"/>
<ContentProtection schemeIdUri="urn:uuid:1077efec-c0b2-4d02-ace3-3c1e52e2fb4b">
<cenc:pssh>
AAAANHBzc2gBAAAAEHfv7MCyTQKs4zweUuL7SwAAAAGruicei89VK70uhqQ0qaXZAAAAAA==
</cenc:pssh>
</ContentProtection>
<Representation id="1" bandwidth="65740" codecs="mp4a.40.2" mimeType="audio/mp4" audioSamplingRate="44100">
<AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="2"/>
<BaseURL>audio.mp4</BaseURL>
<SegmentBase indexRange="957-1156" timescale="44100">
<Initialization range="0-956"/>
</SegmentBase>
</Representation>
</AdaptationSet>
</Period>
</MPD>

**Comment by priyanshugupta27** [comment]
Attaching the manifest for you reference.`
<MPD xmlns="urn:mpeg:dash:schema:mpd:2011" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:cenc="urn:mpeg:cenc:2013" xsi:schemaLocation="urn:mpeg:dash:schema:mpd:2011 DASH-MPD.xsd" profiles="urn:mpeg:dash:profile:isoff-on-demand:2011" minBufferTime="PT2S" type="static" mediaPresentationDuration="PT132.96S">
<Period id="0">
<AdaptationSet id="0" contentType="video" width="720" height="404" frameRate="25000/1000" subsegmentAlignment="true" par="25:14">
<ContentProtection value="cenc" schemeIdUri="urn:mpeg:dash:mp4protection:2011" cenc:default_KID="abba271e-8bcf-552b-bd2e-86a434a9a5d9"/>
<ContentProtection schemeIdUri="urn:uuid:1077efec-c0b2-4d02-ace3-3c1e52e2fb4b">
<cenc:pssh>
AAAANHBzc2gBAAAAEHfv7MCyTQKs4zweUuL7SwAAAAGruicei89VK70uhqQ0qaXZAAAAAA==
</cenc:pssh>
</ContentProtection>
<Representation id="0" bandwidth="1312666" codecs="avc1.42c01e" mimeType="video/mp4" sar="1:1">
<BaseURL>video.mp4</BaseURL>
<SegmentBase indexRange="1107-1306" timescale="25000">
<Initialization range="0-1106"/>
</SegmentBase>
</Representation>
</AdaptationSet>
<AdaptationSet id="1" contentType="audio" subsegmentAlignment="true">
<ContentProtection value="cenc" schemeIdUri="urn:mpeg:dash:mp4protection:2011" cenc:default_KID="abba271e-8bcf-552b-bd2e-86a434a9a5d9"/>
<ContentProtection schemeIdUri="urn:uuid:1077efec-c0b2-4d02-ace3-3c1e52e2fb4b">
<cenc:pssh>
AAAANHBzc2gBAAAAEHfv7MCyTQKs4zweUuL7SwAAAAGruicei89VK70uhqQ0qaXZAAAAAA==
</cenc:pssh>
</ContentProtection>
<Representation id="1" bandwidth="65740" codecs="mp4a.40.2" mimeType="audio/mp4" audioSamplingRate="44100">
<AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="2"/>
<BaseURL>audio.mp4</BaseURL>
<SegmentBase indexRange="957-1156" timescale="44100">
<Initialization range="0-956"/>
</SegmentBase>
</Representation>
</AdaptationSet>
</Period>
</MPD>`

**Comment by kqyang** [comment]
@priyanshugupta27 There is 10-second clear lead by default, so looks like your play is not handling clear lead correctly. You can either fix you player or set --clear_lead=0 (https://google.github.io/shaka-packager/html/documentation.html#general-encryption-options).

And sorry for the confusing suggestion in the earlier commend. I meant "\\" not "\".. Forgot that I had to type "\\\\"... I am glad that you managed to make it work!

**Comment by kqyang** [comment]
@priyanshugupta27 It really depends on the player implementation. This looks like a bug in the player. You may want to file a bug to the player. Alternatively, you can switch to a well supported player, e.g. Shaka Player, dash.js, or ExoPlayer (depends on your platform).
