### ISSUE TITLE
Create Visual Studio build files (.sln / .vcxproj)

### ISSUE THREAD

**Issue by Jason239** [google/shaka-packager#426]
Hi,

In the previously received source, project files(.vcxproj) and solution files(.sln) are created for each module. When I receive the source again from the new directory, there are no solution files. 

Do I have to enter special commands to get solution files?
I don't know how I got the solution files from the previous source files. :(

**Comment by kqyang** [comment]
Yes, the solution files are generated after running `gclient runhooks` or `gclient sync`.

**Comment by LeeSangGoo** [comment]
I already tried it several times, but it doesn't generated.

**Comment by LeeSangGoo** [comment]
`gclient runhooks` and  `gclient sync` seems to have succeeded without problems.

**Comment by kqyang** [comment]
@LeeSangGoo That is weird. It should be created after running `gclient`. Just to make sure, you have checked both directories `out\Debug` and `out\Release`?

I don't have a Windows machine right now. Will try if I can find one.

@rkuroiwa Any idea what is going on?

**Comment by LeeSangGoo** [comment]
Both directories look normal.
Do specific files need to be in those directories?

Currently, ninja build is doing well.
But I can't open VS because there are no solution files and project files.

For now, I'll use the previous sources until we find the problem. Thank you!

**Comment by rkuroiwa** [comment]
The build rules are generated by GYP, it's best to look into GYP.
Try setting GYP_GENERATORS to msvs-ninja.
i.e. in cmd, do
set GYP_GENERATORS=msvs-ninja,ninja
and then runhooks.

**Comment by Jason239** [comment]
Ah, you are right.
The proj files was successfully generated.
I tried it in PowerShell as a fool.. :(

Thanks! 
And this issue will be closed.

**Comment by Jason239** [comment]
I have reopened the issue for a while with additional questions.

In some cases, it seems that there is case which it is built by calling ninja(in .vcxproj file as below), 
```
  <Target Name="Build">
    <Exec Command="call ninja.exe -C $(OutDir) $(ProjectName)" />
  </Target>
  <Target Name="Clean">
    <Exec Command="call ninja.exe -C $(OutDir) -tclean $(ProjectName)" />
  </Target>
```
and there is the other case which it is built by just Visual Studio.

If I don't want to use the ninja build, do I have to `runhooks` after setting a specific GYP_GENERATORS?

**Comment by rkuroiwa** [comment]
setting GYP_GENERATORS to just "msvs" might work. But I haven't tried this in years and I do not know whether GYP that comes with the packager checkout works with the config at all.

I strongly recommend using ninja. gclient and ninja both comes with depot tools so there's no extra step to use ninja.

**Comment by Jason239** [comment]
Okay, I got it.

Thanks for your support!
