### ISSUE TITLE
how to pass path dynamically into packager commandline

### ISSUE THREAD

**Issue by kaushikkunal99** [google/shaka-packager#428]
## System info
**Operating System**: <e.g. macOS Sierra, Ubuntu 14.04 trusty etc>
MACOSX sierra
**Shaka Packager Version**: <e.g. v1.6.1, commit SHA etc>
packager version v2.0.3-ef93a1d-release
## Issue and steps to reproduce the problem
How to pass path dynamically into packaging command line,${DES_PATH} in the below example. When i put this it says its missing $ sign. Since it expects double dollar sign.

**Packager Command**:
  /Users/kkaushik/Documents/development/packager/packager \
      'in=/Users/kkaushik/Documents/development/packager/content/paulblart/wm/A/ToS_1080p_3M/video.mp4,stream=audio,init_segment=wm/audio/und/mp4a/init.mp4,segment_template=wm/audio/und/mp4a/$Number$.m4s' \
      'in=${SRC_PATH}/wm/A/ToS_1080p_3M/video.mp4,stream=video,init_segment=${DES_PATH}/1080/A/wm/video/avc1/ToS_1080p_3M/seg_init_0.mp4,segment_template=${DES_PATH}/1080/A/wm/video/avc1/ToS_1080p_3M/seg_$Time$.m4s' \
      'in=${SRC_PATH}/wm/B/ToS_1080p_3M/video.mp4,stream=video,init_segment=${DES_PATH}/1080/B/wm/video/avc1/ToS_1080p_3M/seg_init_0.mp4,segment_template=${DES_PATH}/1080/B/wm/video/avc1/ToS_1080p_3M/seg_$Time$.m4s' \
      'in=${SRC_PATH}/wm/A/ToS_720p_2M/video.mp4,stream=video,init_segment=${DES_PATH}/720/A/wm/video/avc1/ToS_720p_2M/seg_init_0.mp4,segment_template=${DES_PATH}/720/A/wm/video/avc1/ToS_720p_2M/seg_$Time$.m4s' \
      'in=${SRC_PATH}/wm/B/ToS_720p_2M/video.mp4,stream=video,init_segment=${DES_PATH}/720/B/wm/video/avc1/ToS_720p_2M/seg_init_0.mp4,segment_template=${DES_PATH}/720/B/wm/video/avc1/ToS_720p_2M/seg_$Time$.m4s' \

Starting packaging 1 $start
[0706/130303:ERROR:packager_main.cc(472)] Failed to initialize packager: 3 (INVALID_ARGUMENT): In segment templates, '$' should appear in pairs.
Packaging 1 Completed
Starting packaging 2
[0706/130303:ERROR:pack

**Comment by kqyang** [comment]
@kaushikkunal99 It looks like '$' in '$Number$' and '$Time$' are incorrectly handled by the shell. Can you try escape '$' in '$Number$' and '$Time$'? I.e.

```bash
/Users/kkaushik/Documents/development/packager/packager 
'in=/Users/kkaushik/Documents/development/packager/content/paulblart/wm/A/ToS_1080p_3M/video.mp4,stream=audio,init_segment=wm/audio/und/mp4a/init.mp4,segment_template=wm/audio/und/mp4a/\$Number\$.m4s' 
```

**Comment by kqyang** [comment]
@kaushikkunal99 This is because you enclosed the command in `''`, which disables shell processing and shell variable replacement. This has nothing to do with packager.

Anyway, you should remove `''` and do something like this:

```bash
/Users/kkaushik/Documents/development/packager/packager \
  in=/Users/kkaushik/Documents/development/packager/content/paulblart/wm/A/ToS_1080p_3M/video.mp4,stream=audio,init_segment=${PKG_FOLDER}/wm/audio/und/mp4a/init.mp4,segment_template=${PKG_FOLDER}/wm/audio/und/mp4a/\$Number\$.m4s \
...
```

I am closing the bug as it is not related to Shaka Packager. You can still reply to this issue if you have more questions.
