### ISSUE TITLE
Is it possible to create AES 128 encrypted HLS content using Shaka Packager?

### ISSUE THREAD

**Issue by priyanshugupta27** [google/shaka-packager#429]
## System info
**Operating System**: <e.g. macOS Sierra, Ubuntu 14.04 trusty etc>
**Shaka Packager Version**: <e.g. v1.6.1, commit SHA etc>

## Issue and steps to reproduce the problem

**Packager Command**:

Extra steps to reproduce the problem?
(1) Can you please provide few references of the documentation?
(2)

What is the expected result?

What happens instead?

<Please attach the input files or email to shaka-packager-issues@google.com.>
<Please provide any additional information below.>

**Comment by kqyang** [comment]
No. That is not supported right now. Any reason you want AES-128 not SAMPLE-AES?

**Comment by priyanshugupta27** [comment]
Not specific just want to know for my knowledge and it will be great if you can share the documentaion to encrypt the content with SAMPLE-AES.
Thanks in advance

**Comment by kqyang** [comment]
Follow the instruction here: https://google.github.io/shaka-packager/html/tutorials/raw_key.html. For HLS, you can specify the optional `--hls_key_uri`: https://google.github.io/shaka-packager/html/documentation.html#hls-options.

Let us know if you have more questions.
