### ISSUE TITLE
Distinguishing close captions and subtitles in DASH

### ISSUE THREAD

**Issue by jakubvojacek** [google/shaka-packager#430]
Hello,

currently, there is an option `--default_language <language>`. This option does mark both text and audio track of the same language as main (default), which is not desired in our use case. Would it be possible to add new option `--default_text_language` perhaps? Or use a different approach and add `role` as a parameter to the segment template?

Thank you

**Comment by kqyang** [comment]
@jakubvojacek Do you mind describing your use case in more detail? Thanks.

> Or use a different approach and add role as a parameter to the segment template? 

We'd like to have the same command syntax for DASH and HLS and role seems to be DASH centric. `--default_text_language` looks like a good option if we were to implement it.

**Comment by jakubvojacek** [comment]
@kqyang right now when we have `cs` audio track and `cs` text track, both are enabled by default. In the case of closed captions, those should be hidden by default. But when the default language (`--default_language`) would be `cs`, it would be displayed by default by players that do respect `main` role (such as dashjs). This could be handled on player side but would require for another logic to be implemented

**Comment by kqyang** [comment]
I see, it shouldn't be assigned `main` role in this case. I thought about it again. It will be more extensible to support general `role` option. We'll need to come up with a way to make it work for both DASH and HLS. Let us know if you have any suggestions.

This is related to #404. Added to v2.3 milestone tentatively.

**Comment by jakubvojacek** [comment]
> Yes, it is on our priority list. We will push the solution probably in the week after thanksgiving.
perfect 👍 

> What I understood about the problem is that --default_language was applied to the close captions by mistake. For your case, none of the caption tracks should be made "default", i.e. with "main" role.

that's exactly right
> I also have a question for you. Will there be any use case that you want a default language for audio but another default language for text?

yes, definitely, for an example we got CNN channel in English audio and Czech subtitles, and we want both enabled by default.

**Comment by kqyang** [comment]
@jakubvojacek Ok, we will add support for --default_text_language too.

**Comment by kqyang** [comment]
Reopen the issue. Commit https://github.com/google/shaka-packager/commit/273ab09f053e68904e971959a7a8ee39dd6df987 is really for #404.

**Comment by jakubvojacek** [comment]
Works like a charm, thank you 👍
