### ISSUE TITLE
Generate init.m4v and mpd without full package

### ISSUE THREAD

**Issue by cgp1081** [google/shaka-packager#432]
To support multiple DRM license profiles(persistence settings etc...) we would like to be able to generate multiple init.m4v segments and mpd's(different pssh values) to serve in different cases, while pointing to the same encrypted segments.

Is there a way to generate init.m4v and .mpd outputs without packaging the rest of the DASH segments?  The only way I've found to accomplish this currently is to package the stream twice, move inits and mpd from 2nd package into first, trash segments from 2nd.

**Comment by kqyang** [comment]
@cgp1081 You shouldn't need different init.m4v and mpd in this case. You can pass all the PSSHs to packager to generate a single init.m4v and mpd for all DRMs. It is up to the player to choose an appropriate DRM system to use.

Let us know if you have more questions.

**Comment by cgp1081** [comment]
@kqyang We've been unable to make it work with a single init and mpd - even when passing both pssh's to packager.  Our DRM policies are served based on content IDs and were unable to choose between multiple content IDs from a single widevine pssh.

**Comment by kqyang** [comment]
@cgp1081 As discussed offline, for your particular use case, we think it is better to be solved in the server side. We don't want to support it in packager to encourage this behavior. 

If it is required, an alternative to package the stream twice is to do post processing on the generated init.m4v and mpd to generate the other "version" of init.m4v and mpd, which should be trivial string replacements.

Closing the bug as "will not implement". Let us know if you have more questions.
