### ISSUE TITLE
Example videos in tutorial do not exist

### ISSUE THREAD

**Issue by hchen1506** [google/shaka-packager#436]
See https://google.github.io/shaka-packager/html/tutorials/raw_key.html#examples

$ packager \
  in=h264_baseline_360p_600.mp4,stream=audio,output=audio.mp4 \
  in=h264_baseline_360p_600.mp4,stream=video,output=h264_360p.mp4 \
  in=h264_main_480p_1000.mp4,stream=video,output=h264_480p.mp4 \
  in=h264_main_720p_3000.mp4,stream=video,output=h264_720p.mp4 \
  in=h264_high_1080p_6000.mp4,stream=video,output=h264_1080p.mp4 \
  --enable_raw_key_encryption \
  --keys label=:key_id=abba271e8bcf552bbd2e86a434a9a5d9:key=69eaa802a6763af979e8d1940fb88392 \
  --mpd_output h264.mpd

There is no h264_baseline_360p_600.mp4, h264_baseline_360p_600.mp4, h264_main_480p_1000.mp4, video in the repository. There is a good command example, but I cannot just copy/paste to rerpoduce this command. So I suggest one of follows:
1) Use bear-1280x720.mp4, bear-640x360.mp4, bear-320x180.mp4 in the packager/media/test/data.
2) Create those non-exist video and put in a tutorial directory, so that developers can reproduce this command.

**Comment by vaage** [comment]
@kqyang Would it be worth building our tutorials around realistic content, for example using one of the Blender Open Source videos ([sintel](https://durian.blender.org/download/)). We could just point to the download links for them (and not have them in the repo).

**Comment by hchen1506** [comment]
Oh, I saw the https://google.github.io/shaka-packager/html/tutorials/encoding.html page, which has the ffmpeg commands to generate those videos.

I think it may still be worth pre-generating those content for the users, so that the results do not depend on users local ffmpeg version.

**Comment by hchen1506** [comment]
The "original.mp4" in https://google.github.io/shaka-packager/html/tutorials/encoding.html is also non-existing.

**Comment by kqyang** [comment]
@vaage @hchen1506 We want to work with a variety of contents. Not just one or a few golden files. Users should be able to use any files they have - as long as it is using a supported container and codec. And almost always, they want to use their own files.

> the results do not depend on users local ffmpeg version.

It should not matter which ffmpeg is used. If there are problems, then there is a bug in either packager or ffmpeg that needs to be fixed.
