### ISSUE TITLE
Link error occurred when using packager library

### ISSUE THREAD

**Issue by Jason239** [google/shaka-packager#438]
I want to customize the packager app.
And I want to use it in the form of using a library that has been built, not a whole new build in every time.

So I refer to about 72 libraries that are created when I build sources.

I mean, I have built the app source separately, referenced other libraries, and included header files in the app source.

But 68 link errors occurred as LNK2001, LNK2019 on base.lib, file.lib, libcrul.lib, etc.

Obviously, I referenced all libraries, such as base.lib, that were normally built,
 why would this happen?

I built it on Visual Studio 2015, Windows 10.

The encoding will break, but I attached the error log.
[link_errors.txt](https://github.com/google/shaka-packager/files/2217848/link_errors.txt)

Thank you.

**Comment by Jason239** [comment]
These are the referenced libraries.

![1](https://user-images.githubusercontent.com/8487254/43059154-136acbee-8e86-11e8-92ce-239240eb54c0.PNG)

![2](https://user-images.githubusercontent.com/8487254/43059155-160a0a22-8e86-11e8-94ca-f15a82655cb2.PNG)

**Comment by kqyang** [comment]
@Jason239 I don't know how you link the library right now. Can you share more details? Also, you shouldn't need to link all the 72 libraries. You can link packager.lib only and use the interface defined in https://github.com/google/shaka-packager/blob/master/packager/packager.h.

**Comment by Jason239** [comment]
ah, you mean only packager.lib and include packager.h? not libpackager.lib?

**Comment by Jason239** [comment]
I tried to build the following source(sample source) after I added the built libpackager.lib to the linker option of my project by adding it to an additional dependency, 
but I got link errors like LNK2001, 2019.
```
#include <cstdlib>
#include <vector>

#include "packager/packager.h"
#include "packager/status.h"

int main() {
	shaka::Packager packager;

	// Setup packaging parameters.
	shaka::PackagingParams packaging_params;
	// Use default parameters here.

	// Setup stream descriptors.
	std::vector<shaka::StreamDescriptor> stream_descriptors;
	shaka::StreamDescriptor stream_descriptor;
	stream_descriptor.input = "input.mp4";
	stream_descriptor.stream_selector = "video";
	stream_descriptor.output = "output_video.mp4";
	stream_descriptors.push_back(stream_descriptor);
	shaka::StreamDescriptor stream_descriptor2;
	stream_descriptor2.input = "input2.mp4";
	stream_descriptor2.stream_selector = "audio";
	stream_descriptor2.output = "output_audio2.mp4";
	stream_descriptors.push_back(stream_descriptor2);

	shaka::Status status = packager.Initialize(packaging_params,
		stream_descriptors);
	if (!status.ok()) { ; }
	status = packager.Run();
	if (!status.ok()) { ; }
	return 0;
}
```

This is the libpackager.lib analysis detected by the utility dumpbin in Command Prompt of visual studio.
[libpackager_undname.txt](https://github.com/google/shaka-packager/files/2223204/libpackager_undname.txt)

And this is the VS error log.
[vs_error.txt](https://github.com/google/shaka-packager/files/2223206/vs_error.txt)


Why do I get an error like LNK2001 because the library seems to have all the necessary functions?

**Comment by kqyang** [comment]
Em.. I'll try if I can find a Windows to reproduce the problem locally.

**Comment by Jason239** [comment]
I tried to build on Linux(Ubuntu 16.04 x64) because you don't seem to have windows environment.
The sample source is same, and the compile command is as below.
`gcc -o ./packager/packager.h ./packager/packager.cc packager_main_test.cc -I ./ -I ./packager/ -I ./packager/third_party/protobuf_origin/src -I ./packager/third_party/libxml/src/include/ -I ./packager/third_party/libxml/linux/include/ -I ./packager/third_party/icu/source/common/ -L. -lpackager -std=c++11
`

These are the functions the library has.
`nm -C ./libpackager.a | less > FuncInLib.txt`
[FuncInLib.txt](https://github.com/google/shaka-packager/files/2243587/FuncInLib.txt)


And this is the error log.
[log.txt](https://github.com/google/shaka-packager/files/2243533/log.txt)

It seems to be a similar error in Windows.. what am I doing wrong?

**Comment by Jason239** [comment]
I tried to build on Linux(Ubuntu 16.04 x64) because you don't seem to have windows environment.
The sample source is same, and the compile command is as below.
`g++ -o packager_test ./packager/status.h ./packager/packager.h sample_source.cc -I ./ -I ./packager/ -I ./packager/third_party/protobuf_origin/src -I ./packager/third_party/libxml/src/include/ -I ./packager/third_party/libxml/linux/include/ -I ./packager/third_party/icu/source/common/ -L. -lpackager -std=c++11
`

These are the functions the library has.
`nm -C ./libpackager.a | less > FuncInLib.txt`
[FuncInLib.txt](https://github.com/google/shaka-packager/files/2244659/FuncInLib.txt)



And this is the error log.
[log.txt](https://github.com/google/shaka-packager/files/2244661/log.txt)


It seems to be a similar error in Windows.. what am I doing wrong?

**Comment by kqyang** [comment]
You are right. "libpackager.a" does depend on static libraries and object files. You'll have to include all the dependencies. 

Alternatively, if you are ok with linking against a shared library, you can config it to use "shared_library":

```
❯ GYP_DEFINES='libpackager_type=shared_library' gclient runhooks
```

 It should work on Linux and Mac, but probably not on Windows right now, which we can fix.

**Comment by Jason239** [comment]
uhm.. so I tried with a shared library, and the compilation succeeded.
But the 'core dumped' error is occurred in the 'packager.Initialize' function.

Is there a good way to debug or analyze this error?
And will this error be reproduced on your side too?

I'm sorry I'm not familiar with Linux :(

**Comment by kqyang** [comment]
@Jason239 The crash is likely because of the inconsistency between gcc and clang. Can you try build the shared library again with clang disabled? 

```bash
> GYP_DEFINES='libpackager_type=shared_library clang=0' gclient runhooks
> ninja -C out/Release
```

And then link it to your sample app.

**Comment by Jason239** [comment]
```
cc = cc
cxx = c++
ld = $cc
ldxx = $cxx

```
I've used .so which I checked that clang is disabled, but the result is the same.

**Comment by Jason239** [comment]
```
GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.5) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./packager_test...(no debugging symbols found)...done.
[New LWP 974]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `./packager_test'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  __memcpy_sse2_unaligned () at ../sysdeps/x86_64/multiarch/memcpy-sse2-unaligned.S:35
35      ../sysdeps/x86_64/multiarch/memcpy-sse2-unaligned.S: 그런 파일이나 디렉터리가 없습니다. (It means 'There are no such files or directories.')

```
This is an analysis of the crash dump with gdb.
Will this help?

**Comment by kqyang** [comment]
Emm...

Ok, can you try if you are seeing the exact thing by running the below commands:

```
> GYP_DEFINES='libpackager_type=shared_library clang=0' gclient runhooks
> ninja -C out/Release
> g++ -o packager_test sample_source.cc -I ./ -Lout/Release/lib -lpackager -std=c++11
> LD_LIBRARY_PATH=out/Release/lib ./packager_test
```

**Comment by Jason239** [comment]
I had to remove '-Werror ' in line 39 of 'out/Release/obj/packager.ninja' file because the warning causes error.

And this is the error log.

```
$ LD_LIBRARY_PATH=out/Release/lib ./packager_test

[0802/140643:FATAL:chunking_handler.cc(33)] Check failed: chunking_params.segment_duration_in_seconds != 0u (0 vs. 0)
#0 0x7f2dc86b067e base::debug::StackTrace::StackTrace()
#1 0x7f2dc86b725e logging::LogMessage::~LogMessage()
#2 0x7f2dc858ecf8 shaka::media::ChunkingHandler::ChunkingHandler()
#3 0x7f2dc8574123 shaka::media::(anonymous namespace)::CreateAudioVideoJobs()
#4 0x7f2dc857af78 shaka::media::(anonymous namespace)::CreateAllJobs()
#5 0x7f2dc857c8c2 shaka::Packager::Initialize()
#6 0x0000004011b6 main
#7 0x7f2dc7bca830 __libc_start_main
#8 0x000000400ff9 _start

중지됨 (core dumped)
```

 I got new sources and tried it.

Are there any specific requirements for native libraries?
Or is the sample code wrong?

**Comment by Jason239** [comment]
oh, I added a below line, then It seems to be running successfully.
`packaging_params.chunking_params.segment_duration_in_seconds = 5;`


The printed output is like this,
```
[0802/152508:INFO:demuxer.cc(88)] Demuxer::Run() on file '~/build_shaka/Sintel.2010.480P.mp4'.
[0802/152508:INFO:demuxer.cc(160)] Initialize Demuxer for file '~/build_shaka/Sintel.2010.480P.mp4'.
```
but.. there is no output file. I can't find it.

**Comment by Jason239** [comment]
Then I also tried to build using your app as a sample.
`g++ -o packager_test ./test_app/* -I ./ -I ./packager/third_party/gflags/gen/posix/include/ -I ./packager/ -I ./packager/third_party/boringssl/src/include/ -Lout/Release/lib -lpackager -std=c++11`

And I got this errors.
[2.txt](https://github.com/google/shaka-packager/files/2252797/2.txt)


I don't know why I keep getting 'undefined reference' errors in the 'logging', 'base', and 'google' namespace functions as you can see above.
These are the files I built.

```
$ ls test_app/
ad_cue_generator_flags.cc  manifest_flags.cc  packager_main.cc                   raw_key_encryption_flags.h  validate_flag.h
ad_cue_generator_flags.h   manifest_flags.h   playready_key_encryption_flags.cc  retired_flags.cc            vlog_flags.cc
crypto_flags.cc            mpd_flags.cc       playready_key_encryption_flags.h   retired_flags.h             vlog_flags.h
crypto_flags.h             mpd_flags.h        protection_system_flags.cc         stream_descriptor.cc        widevine_encryption_flags.cc
hls_flags.cc               muxer_flags.cc     protection_system_flags.h          stream_descriptor.h         widevine_encryption_flags.h
hls_flags.h                muxer_flags.h      raw_key_encryption_flags.cc   
```

**Comment by Jason239** [comment]
Does that mean I need to link to static library such as base, file, gflags, and license_notice?
Because these don't have shared libraries.

**Comment by Jason239** [comment]
This error occurs even if the library is disabled with clang.
It's weird.
```
g++ -o packager_test ./test_app/* -I ./ -I ./packager/third_party/gflags/gen/posix/include/ -I ./packager/ -I ./packager/third_party/boringssl/src/include/ -Lout/Release/lib -lbase -lfile -lpackager -lgflags -llicense_notice -std=c++11
out/Release/lib/libbase.a: error adding symbols: Malformed archive
collect2: error: ld returned 1 exit status
```

**Comment by kqyang** [comment]
I am a little bit confused, so you want both (1) the packager lib function provided by packager/packager.h and libpackager.so and (2) also the command parsing and app functionality in packager/app?

Is (1) not sufficient for your use case?

**Comment by Jason239** [comment]
Yes, but I'd like to customize it by adding some functionality to the current parsing functionality of your app.

**Comment by Jason239** [comment]
Thank you for your continued support even though the issue has not being solved easily.

> If that is not feasible for you, you can take gyp generated visual studio project file as a basis and start your development from that.

As you told me, It doesn't work on Windows If I use shared library. So I think I can't visual studio based development..

> In that case, you'll need to pull in more dependencies. It will be much easier if you can base your development on the current GYP meta-build system.

I'm confused about how to get more dependencies.
So you mean, should I use GYP meta-build system to solve the dependency problem mentioned above?
And it means, It's hard to use as a built library, and I have to build it together using the GYP meta build system. 
Is my understanding correct?
Then I'll try it even though I've never used it.

**Comment by kqyang** [comment]
Since what you want to do is to customize and extend the current packager app, I assume that you do not really care whether to link against the shared library or the static library. It is easier to just link the static library.

As stated above, you have two options:

- Use the GYP meta-build system
You can add / update the dependency using the GYP language.

- Take the GYP generated visual studio project file as a basis
You can then develop using visual studio and add new dependencies in visual studio. If you are more comfortable with this, you can go this approach.

**Comment by Jason239** [comment]
Okay I got it.
Since I need to develop on Mac and Linux too, so I'll try to develop it based on GYP.
I'll ask you if I have any questions about it.

Thank you!

**Comment by coooltype** [comment]
It is being developed using the shaka static library.
The development environment is Ubuntu 16.04.
The problem is that the "Malformed archive" error occurs when linking libraries(base, allocator, packed_audio etc..) that "libpackager.a" needs.

After the NINJA build, if you run a symbolic scan in the folder where the library is located, you have a symbolic.
However, if you move the library to a different folder, a "Malformed archive" error occurs.
In addition, the symbol is not searched.
I think if the object file(.o) and the archive file(.a) are together, the symbol is searched.
An "undefined reference" error will occur even if you link and build the library without moving the library.

Windows OS and macOS do not encounter this problem and include a symbol in the library.
What should I do?

**Comment by kqyang** [comment]
It might be related to clang vs gcc. Are you using gcc in to build your code? Try building shaka static library using gcc too if that is the case. You can do that by disabling clang: 

```shell
$ GYP_DEFINES='clang=0' gclient runhooks
```
