### ISSUE TITLE
Unsucessful download

### ISSUE THREAD

**Issue by Sectur1** [google/shaka-packager#440]
## System info
**Operating System**: <e.g. macOS Sierra, Ubuntu 14.04 trusty etc>
**Shaka Packager Version**: <e.g. v1.6.1, commit SHA etc>

## Issue and steps to reproduce the problem

**Packager Command**:

Extra steps to reproduce the problem?
(1)
(2)

What is the expected result?
## Issue and steps to reproduce the problem

**Packager Command**:
![screenshot from 2018-07-23 13-53-09](https://user-images.githubusercontent.com/22817492/43077615-e0f9e3d0-8e7f-11e8-9e79-da05de6f8363.png)

What happens instead?

<Please attach the input files or email to shaka-packager-issues@google.com.>
<Please provide any additional information below.>
I ran gclient sync and it generated this error what should I do

**Comment by kqyang** [comment]
@Sectur1 It looks like the script is not able to find `download_from_google_storage` tool, which is in depot_tools. Have you added depot_tools to PATH?

**Comment by Sectur1** [comment]
Yeah thanks. I had a hard time adding it to PATH but I finally figured it
out
