### ISSUE TITLE
Segmented output with DASH + HLS packaging

### ISSUE THREAD

**Issue by Jason239** [google/shaka-packager#442]
I tried to package DASH and HLS at the same time like this.

`./packager 'in=../../Sintel.2010.720P.mp4,stream=audio,segment_template=shaka_vod_hls/audio/$Number$.aac,playlist_name=audio/stream.m3u8,hls_group_id=audio' 'in=../../Sintel.2010.720P.mp4,stream=video,segment_template=shaka_vod_hls/video/$Number$.ts,playlist_name=video/stream.m3u8,iframe_playlist_name=video/iframe.m3u8' 'in=../../Sintel.2010.720P.mp4,stream=audio,init_segment=shaka_vod/audio/init.mp4,segment_template=shaka_vod/audio/$Number$.m4s' 'in=../../Sintel.2010.720P.mp4,stream=video,init_segment=shaka_vod/video/init.mp4,segment_template=shaka_vod/video/$Number$.m4s' --hls_master_playlist_output shaka_vod_hls/master.m3u8 --generate_static_mpd --mpd_output shaka_vod/stream.mpd`

And the packaging is complete, but somewhat seems strange.
First, I got a lot of incomprehensible logs as below. 

` Segments should not be overlapping. The new segment starts at 78446250 but the previous s                                           egment ends at 79200000.`

This doesn't appear when I package each.

And there are strange files such as stream_0.m3u8, stream_2.m3u8 in the hls output directory(in my case, shaka_vod_hls). The manifest files(mpd, master m3u8) also looks different from when it was packaged separately.

I know the 'Single file MP4 output with DASH + HLS' is well doing. 
but if I want to segmented(such as '.ts' or '.m4s') output, how can I do?

I also tried as below, but It was failed.
`'in=../../Sintel.2010.720P.mp4,stream=audio,init_segment=shaka_vod/audio/init.mp4,segment_template=shaka_vod/audio/$Number$.m4s,segment_template=shaka_vod_hls/audio/$Number$.aac,playlist_name=audio/stream.m3u8,hls_group_id=audio' `

**Comment by kqyang** [comment]
You specified four stream descriptors. Looks like you want the first two stream descriptors to be used for HLS and the latter two stream descriptors to be used for DASH. That is not how packager works. All four stream descriptors are used by both HLS and DASH.

If you want to package for DASH and HLS at the same time, you'll need to use m4s as TS is not well supported in DASH. 

You may also package DASH and HLS separately.

Option (1) m4s for both DASH and HLS:

```bash
./packager \
'in=../../Sintel.2010.720P.mp4,stream=audio,init_segment=shaka_vod/audio/init.mp4,segment_template=shaka_vod/audio/$Number$.m4s,playlist_name=audio/stream.m3u8,hls_group_id=audio'  \
'in=../../Sintel.2010.720P.mp4,stream=video,init_segment=shaka_vod/video/init.mp4,segment_template=shaka_vod/video/$Number$.m4s,playlist_name=video/stream.m3u8,iframe_playlist_name=video/iframe.m3u8'  \
--hls_master_playlist_output shaka_vod/master.m3u8 \
--generate_static_mpd --mpd_output shaka_vod/stream.mpd
```

Option (2) Separate commands for DASH and HLS:

```bash
./packager  \
'in=../../Sintel.2010.720P.mp4,stream=audio,segment_template=shaka_vod_hls/audio/$Number$.aac,playlist_name=audio/stream.m3u8,hls_group_id=audio'  \
'in=../../Sintel.2010.720P.mp4,stream=video,segment_template=shaka_vod_hls/video/$Number$.ts,playlist_name=video/stream.m3u8,iframe_playlist_name=video/iframe.m3u8'  \
--hls_master_playlist_output shaka_vod_hls/master.m3u8 
```

```bash
./packager \
'in=../../Sintel.2010.720P.mp4,stream=audio,init_segment=shaka_vod/audio/init.mp4,segment_template=shaka_vod/audio/$Number$.m4s'  \
'in=../../Sintel.2010.720P.mp4,stream=video,init_segment=shaka_vod/video/init.mp4,segment_template=shaka_vod/video/$Number$.m4s' \
--generate_static_mpd --mpd_output shaka_vod/stream.mpd
```

Does that help?

**Comment by Jason239** [comment]
Ah~ I understood well
Thanks for your detailed explanation !
