### ISSUE TITLE
shaka-packager not generating output files

### ISSUE THREAD

**Issue by mdaftab88** [google/shaka-packager#444]
## System info
**Operating System**: Ubuntu 16.04
**Shaka Packager Version**: release-v2.1.0

## Issue and steps to reproduce the problem
I followed instructions to use shaka-packager using Docker ([link](https://github.com/google/shaka-packager/blob/master/docs/source/docker_instructions.md)) on my local machine.

I have installed shaka-packager with following command:
`sudo docker pull google/shaka-packager:release-v2.1.0`

And then went to packager console through following command:
`sudo docker run -v /home/aftab/:/media -it --rm google/shaka-packager`

Note: Video file is /home/aftab/media/example.mp4

**Packager Command**:
 `packager input=/media/example.mp4,stream=audio,output=/media/audio.mp4 \  `
 `     input=/media/example.mp4,stream=video,output=/media/video.mp4 \  `
 `     --mpd_output /media/example.mpd  `

**Packager Command Output:**
![shaka-packager](https://user-images.githubusercontent.com/25167441/43307180-29b7e93c-919b-11e8-99c7-4182a6511f1c.png)

What is the expected result?
It should generate three files inside my /home/aftab/media directory

- audio.mp4
- video.mp4
- example.mpd

What happens instead?
It is not generating any of the above files.

I think, I am doing some silly mistake while setting it up. Please help and suggest if I am wrong.

**Comment by kqyang** [comment]
"/media" is mapped to your "/home/aftab" directory. Can you check "/home/aftab" directory?

**Comment by mdaftab88** [comment]
Yes, you are right. All the files are inside my "/home/aftab/" directory. 

Thanks a lot. :)
