### ISSUE TITLE
Segmentation fault when packaing VOD with an empty VTT file

### ISSUE THREAD

**Issue by jakubvojacek** [google/shaka-packager#446]
## System info
**Operating System**: latest debian
**Shaka Packager Version**: latest master

## Issue and steps to reproduce the problem
Hello,

is it considered a bad content to attempt to package VOD with empty VTT file? When attempting to do so, I am getting seg. fault. When I remove the empty VTT file from the packager command, it works. 

**Packager Command**:
```
packager  \
'in=output.mp4,stream=0,init_segment=2018-08-01-21-06-487366-svet-motoru-trial-mm-cr-kyselka_video_640_360.mp4,segment_template=video_640_360/video_640_360_2018-08-01-21-06-487366-svet-motoru-trial-mm-cr-kyselka-$Number$.mp4' \
'in=output.mp4,stream=1,init_segment=2018-08-01-21-06-487366-svet-motoru-trial-mm-cr-kyselka_video_720_410.mp4,segment_template=video_720_410/video_720_410_2018-08-01-21-06-487366-svet-motoru-trial-mm-cr-kyselka-$Number$.mp4' \
'in=output.mp4,stream=2,init_segment=2018-08-01-21-06-487366-svet-motoru-trial-mm-cr-kyselka_video_1920_1080.mp4,segment_template=video_1920_1080/video_1920_1080_2018-08-01-21-06-487366-svet-motoru-trial-mm-cr-kyselka-$Number$.mp4' \
'in=output.mp4,stream=3,language=cs,init_segment=2018-08-01-21-06-487366-svet-motoru-trial-mm-cr-kyselka_audio_cs.mp4,segment_template=audio/audio_cs_2018-08-01-21-06-487366-svet-motoru-trial-mm-cr-kyselka-$Number$.mp4' \
'in=subtitle_19.vtt,stream=text,init_segment=2018-08-01-21-06-487366-svet-motoru-trial-mm-cr-kyselka_subtitle_init_19.mp4,segment_template=subtitle_19/ttv_$Number$.m4s,language=cs-teletext' \
'in=subtitle_20.vtt,stream=text,init_segment=2018-08-01-21-06-487366-svet-motoru-trial-mm-cr-kyselka_subtitle_init_20.mp4,segment_template=subtitle_20/ttv_$Number$.m4s,language=cs-subs' \
--mpd_output 2018-08-01-21-06-487366-svet-motoru-trial-mm-cr-kyselka.mpd --generate_static_mpd --hls_master_playlist_output 2018-08-01-21-06-487366-svet-motoru-trial-mm-cr-kyselka.m3u8 --fragment_duration 3.2 --segment_duration 3.2  --suggested_presentation_delay 5 --min_buffer_time 3.2 --minimum_update_period 5 --default_language=cs  
```

Extra steps to reproduce the problem?
(1) output.mp4 is here https://goo.gl/LLPP8U
(2) subtitle files are here [subtitle_20.vtt.txt](https://github.com/google/shaka-packager/files/2250987/subtitle_20.vtt.txt)
[subtitle_19.vtt.txt](https://github.com/google/shaka-packager/files/2250988/subtitle_19.vtt.txt)

**What is the expected result?**
To have packaged VOD. The reason why the second file is empty is because of a drift in my tool that is supposed to keep inserting empty cues every one second. When the tools detects a cue from ccextractor, it synchronizes it's clock with the cue therefore drift will not happen. When there are no subtitles detected by the ccextractor, it happens :( Planning to fix that by running periodically ffprobe (every X minutes) on the input stream, detecting it's time and syncing by that (or don't you have any other idea that could help?).

Anyway, it should not end with Segmentation fault, right?

**What happens instead?**
Segmentation fault

**Thank you**

**Comment by kqyang** [comment]
Make sense. Thanks for reporting the issue. Will fix it soon.

> When there are no subtitles detected by the ccextractor, it happens :( 

Do you mean that it happens because there are no cues at all for that VOD content? With the above fix, we will not include this text stream in the DASH manifest if there are no samples instead of having an empty segment timeline. Will this work for you?

**Comment by jakubvojacek** [comment]
Thank you! 👍
