### ISSUE TITLE
Protobuf  Version

### ISSUE THREAD

**Issue by PING0814** [google/shaka-packager#447]
Hello, I want to include "simple_mpd_notifier.h" in my project to generate mpd file, but it show below error msg while compiling with my code:
 #error incompatible with your Protocol Buffer headers

I am using Protobuf  3.4.0. 
Is it possible to upgrade the Shaka Protobuf from 3.0.0 to 3.4.0?

**Comment by kqyang** [comment]
We have no plan to update Protobuf version used in Shaka Packager right now, but since you are building with source code directly, you should be able to update the dependency of the MpdBuilder to link with your protobuf. 

Let us know if you have more questions. We also welcome ideas or proposals!

**Comment by PING0814** [comment]
Thanks for the reply. I tried to install 3.4.0 Protobuf and modified the value of the "use_system_protobuf" in protoc.gypi to force it to use my machine Protobuf, but still cannot update it . Is it possible to give me an example how to do it? Thanks for your great help!

**Comment by kqyang** [comment]
@PING0814 I'd love to but unfortunately we have other priorities right now. I'll probably try a later time.

For now, what functions do you need in simple_mpd_notifier.h? Is https://github.com/google/shaka-packager/blob/master/packager/mpd/util/mpd_writer.cc sufficient for your need? You can also build your version of mpd_writer to get around the protobuf incompatibility since mpd_writer uses serialized form, which I believe it is compatible with 3.4.

**Comment by PING0814** [comment]
Thanks for the suggestion, I want to use NotifyNewContainer() and NotifyNewSegment() func in simple_mpd_notifier.h. I tried just use mdp_writer.cc, but I found that the base class also need to include "media_info.pb.h which is related to protobuf.
And I also tried to set use_system_protobuf=1 when running gyp, but it still fails. Can this flag be used for using system proto buf?

**Comment by kqyang** [comment]
> I tried just use mdp_writer.cc, but I found that the base class also need to include "media_info.pb.h which is related to protobuf.

Yes, but if you are using serialized form, then you can use different versions of protobuf for mediainfo proto producer and consumer.

> And I also tried to set use_system_protobuf=1 when running gyp, but it still fails. Can this flag be used for using system proto buf?

I checked the code briefly. It looks like it applies to protoc only, so you'll probably need to modify  other targets in protobuf.gyp if you want to go this route.

**Comment by kqyang** [comment]
You can try if you can create a protobuf_full_do_not_use target when use_system_protobuf is 1.
