### ISSUE TITLE
Appveyor ci is crashing in packager_test (Windows)

### ISSUE THREAD

**Issue by kqyang** [google/shaka-packager#449]
https://ci.appveyor.com/project/shaka/shaka-packager/build/job/2t0arfp6plq880va

```unittest
[----------] 9 tests from PackagerTest
[ RUN      ] PackagerTest.Version
[       OK ] PackagerTest.Version (0 ms)
[ RUN      ] PackagerTest.Success
[       OK ] PackagerTest.Success (198 ms)
[ RUN      ] PackagerTest.MissingStreamDescriptors
[       OK ] PackagerTest.MissingStreamDescriptors (0 ms)
[ RUN      ] PackagerTest.MixingSegmentTemplateAndSingleSegment
[       OK ] PackagerTest.MixingSegmentTemplateAndSingleSegment (1 ms)
[ RUN      ] PackagerTest.SegmentAlignedAndSubsegmentNotAligned
[       OK ] PackagerTest.SegmentAlignedAndSubsegmentNotAligned (144 ms)
[ RUN      ] PackagerTest.SegmentNotAlignedButSubsegmentAligned
[       OK ] PackagerTest.SegmentNotAlignedButSubsegmentAligned (1 ms)
[ RUN      ] PackagerTest.WriteOutputToBuffer
Command exited with code 666
```

It seems that it could fail in any of the tests above except for PackagerTest.Version: https://ci.appveyor.com/project/shaka/shaka-packager/build/1.0.554. There are no crash dumps - the test just exits without any logging or tracing.

**Comment by kqyang** [comment]
Appveyor allows RDP (remote desktop) into the build machines for debugging (one hour limit): https://www.appveyor.com/docs/how-to/rdp-to-build-worker/.

**Comment by kqyang** [comment]
The crashing is caused by #448. Somehow it can only be re-produced in Appveyor ci but not elsewhere, including local Window machines.

**Comment by hchen1506** [comment]
I guess it maybe because the Appveyor machine is slow so that the race condition is easier to happen.
