### ISSUE TITLE
[Question] Frame-accurate jumping not working

### ISSUE THREAD

**Issue by gabrielboliveira** [google/shaka-packager#450]
## System info
**Operating System**: macOS High Sierra 10.13.6 (and Ubuntu 16.04 on server)
**Shaka Packager Version**: v2.1.0-cf40acc-release

## Issue and steps to reproduce the problem

This is a question related to a problem I'm facing with frame accuracy. Not solely related to shaka-packager since I had this problem with Bento4 also. 

Basically, with some files it's freezing the first frame(s) and I cannot guarantee frame accuracy jumping. I'm using THEOplayer as the web player, but I've also tested with shaka-player and the issues still happens, so I believe it's not a player bug.

I have two frame jumping buttons on my app, to jump forward or backward frame by frame. On the background, I do a simple calculation on the frame duration based on the framerate (24 fps: 1/24 = 0,042 s) and then add to the current time.

This is the `input.mp4` jumping the frames. The top timecode is a js calculated timecode, and the second one is a burned in timecode on the video (that's frame accurate burned in).

![](https://user-images.githubusercontent.com/11093090/36801014-aeedf906-1c8f-11e8-987a-2d2de0799666.gif)

This is the `input.mp4` converted to DASH with shaka-packager (command below). The first frame is freezed, and it starts to jump from the second one. It happens on both Chrome and Firefox.

![](https://user-images.githubusercontent.com/11093090/36802281-4079ebfc-1c93-11e8-8c71-f280f62167af.gif)

I also have another problem specifically on Chrome, that some specific frames sync up (jumps 2 instead of 1 and then it's synced), but this doesn't happen on Firefox:

![](https://user-images.githubusercontent.com/11093090/36801405-ca9c1196-1c90-11e8-95ad-5c56a9b270ca.gif)

I have some more gifs examples and videos that I can send on the email (not provide publicly here).

This happens on a lot of video files (not any specific one). Some are worse than others, freezing 2 or even 3 frames at the beginning. Some don't even have that problem.

I've tested changing GOP size to 1, or 72 (for 24fps videos), but it didn't change.

Do you guys have any suggestion, or even faced this issue before? Thanks for the help.

**Comment by kqyang** [comment]
It looks like a limitation in MSE to me. @joeyparrish Does MSE support frame accurate seeking?

Try use timestamps accurate to microseconds (0.041667 instead of 0.042) might help, since that is what is specified in MSE spec and what is being used in Chrome and Firefox implementations.

Do you have video samples I can try (with GOP size of 1 and 72)? You can send the links to shaka-packager-issues@google.com if they cannot be shared publicly.

**Comment by gabrielboliveira** [comment]
Thanks for your quick response!

@kqyang At first I thought it might be the microseconds accuracy, however I tested manually setting the video element time with more accuracy. But I discovered that actually, the video frame was freezed and didn't really change after setting the second frame timing.

Example:

1.  `0.041667` - No changes
2.  `0.042` - No changes
3.  `0.083334` - No changes
4. `0.084` - Changes to frame 1 (00:00:00:01)

So indeed it looks like the frame 0 repeats itself on frame 1 (frame 0 and 1 are equal), and only on frame 2 it really changes to frame 1.

Some videos freezes 2, or even 3 frames. So the same logic fits, it will change the frame after 0.125001 (0.041667 * 3)

I'm preparing the video files to send on that email. Should receive them soon.

**Comment by kqyang** [comment]
@gabrielboliveira I tried both two streams. The stream with GOP size of 1 works perfectly; For the stream with GOP size of 72, the freeze in the beginning is because of the initial composition offset - the presentation time actually starts at 0.083334 - it works perfectly afterwards, i.e. "video.currentTime = 0.126" displays "00:00:00:01", "video.currentTime = 0.168" displays "00:00:00:02" ...

We added EditList support in v2.2, which is released last week. Both streams should work perfectly with the new packager release.

Can you try and let us know?

**Comment by gabrielboliveira** [comment]
@kqyang Thanks for your response!

I think this is the key: `because of the initial composition offset`. I'll update our packager version and reprocess all files. I'll update here as soon as I test everything

Quick question. I found this parameter on help:

```
  Flags from ../../packager/media/formats/mp4/track_run_iterator.cc:
    -mp4_reset_initial_composition_offset_to_zero (MP4 only. If it is true,
      reset the initial composition offset to zero, i.e. by assuming that there
      is a missing EditList.) type: bool default: true
```

It says that default is true. Should it automatically reset the composition offset to zero then?

**Comment by kqyang** [comment]
Yes, using an Edit List, to make the initial presentation time starts from 0 instead of a non-zero value. It kicks in only if the Edit List is missing from the source content; a warning message will also be displayed in this case.

**Comment by gabrielboliveira** [comment]
@kqyang I've done some testing on our system and looks like it fixed. With some video files of 23.976, 24, 25 and 29.97 fps all frames were exactly right. I'll ask some other guys from our team to also test and check if everything is working as expected.

Thank you guys so much for your help! You're all so nice and attentive 😄 

I believe we can close this issue, if necessary I can reopen it or open a new one.
