### ISSUE TITLE
[Feature Request] Support AV1

### ISSUE THREAD

**Issue by kqyang** [google/shaka-packager#453]
AV1 is the next generation video codec developed by the Alliance for Open Media (AOMedia): https://github.com/AOMediaCodec.

It is supported in Firefox Nightly (since Nov 2017), Chrome 69, FFmpeg 4.0.

Relevant specifications:

[AV1 Codec ISO Media File Format Binding](https://aomediacodec.github.io/av1-isobmff/)
[AOM AV1 codec mapping in Matroska/WebM](https://github.com/Matroska-Org/matroska-specification/blob/master/codec/av1.md)
[AV1 Bitstream & Decoding Process Specification](https://aomediacodec.github.io/av1-spec)

**Comment by rainliu** [comment]
hi kqyang,

could you take a look at issue #485 ?

For packager/media/test/data/bear-av1.webm, there is no issue for me, but it doesn't work for my av1.webm file.

Thanks.
