### ISSUE TITLE
DRM question, user-key

### ISSUE THREAD

**Issue by welzon** [google/shaka-packager#454]
Hello,

I have started working in packaging only a few weeks ago. My job in this company, to try out Shaka Packager. The packaging with VoD and live content works well, I have learnt it from documentation, but about DRM  I would like to ask a question.
The company using a Multi-DRM vendor, which gave them a unique key (user-key). I'm pretty sure I have to use it, but I couldnt find where can I implement it. My guess is in the pssh, but I'm not sure. 
I hope you can understand my problem, and someone can help me.  I think its quite obvious, only I couldnt figure it out.

Thanks

**Comment by kqyang** [comment]
"Raw Key" is probably what you need: https://google.github.io/shaka-packager/html/tutorials/raw_key.html#using-raw-key. You should be able to request for encryption keys (including key_ids) and a pre-generated pssh (which includes multiple protection systems) from your Multi-DRM vendor. 

Does that answer your question?

**Comment by welzon** [comment]
I'll try it soon.
I forget to mention, that I have encryption keys so key_ids and also content_ids are reachable. So I hope pssh will be the answer.  I'm not familiar with it, can you help me how to pre-generate? I think I read a documentation somewhere about it, but not sure.
Also thanks for the quick response.

**Comment by kqyang** [comment]
It should be provided by your Multi-DRM vendor. 

If you vendor does not provide it, you can try generating it using --protection_systems flag in Shaka Packager. It may just work, depending on your vendor's configuration.

**Comment by welzon** [comment]
Thanks for the help, I got every information from Multi-DRM vendor. I can generate VoD files with widevine. I'll go on, with other DRMs and with live streams. I hope everything will work, so I close this issue.
Thanks again.
