### ISSUE TITLE
Parsing packaged subtitles

### ISSUE THREAD

**Issue by okycelt** [google/shaka-packager#456]
Hello,

We use Shaka packager to package subtitles into DASH creating .mp4 and .m4s files. However, Widevine iOS SDK (specifically Universal DASH Transmuxer) currently doesn't support transmuxing subtitle streams so we're currently without subtitles on iOS. 

On the git repo of UDT (https://github.com/google/universal-dash-transmuxer/issues/16), we were suggested to try parsing the .m4s files from packager ourselves in order to retrieve the original .vtt / .webvtt.

Do you have any useful documentation about how the source subtitles are packaged into .mp4 and .m4s, which could help us parse it back? 

Thank you

**Comment by vaage** [comment]
The packager packages VTT into MP4 according to the spec (@kqyang would be able to tell you exactly which one). But if you are looking for a sample implementation of parsing VTT in MP4, the [Shaka Player](https://github.com/google/shaka-player) does that.

While their [implementation](https://github.com/google/shaka-player/blob/master/lib/text/mp4_vtt_parser.js) is in Javascript, it should be able to give you a reference on how to do it yourself, regardless of what language you need to implement it in.

**Comment by kqyang** [comment]
It is implemented according to [14496-30:2014 Timed text and other visual overlays in ISO base media file format](https://www.iso.org/standard/63107.html).

As @vaage pointed out, Shaka Player's implementation should be a good reference for you.

Let us know if you have other questions.

**Comment by okycelt** [comment]
Thank you very much. I think both sources will be useful for us.

**Comment by kqyang** [comment]
I'll close this issue as your question has been addressed. Feel free to reply to this issue or open another issue if you have more questions.
