### ISSUE TITLE
Problem with the SSL CA cert (path? access rights?)

### ISSUE THREAD

**Issue by kaushikkunal99** [google/shaka-packager#457]
## System info
**Operating System**: AWS Linux AMI
**Shaka Packager Version**: packager version v2.2.0-9e9833e-release

## Issue and steps to reproduce the problem
gives error while packaging content.
We use this url for contentKey https://license.widevine.com/cenc/getcontentkey/spedmg
What would be the issue. 

Error-:
Starting packaging 1 ${start}
[0822/225134:ERROR:http_key_fetcher.cc(225)] curl_easy_perform() failed: Problem with the SSL CA cert (path? access rights?).
[0822/225134:ERROR:packager_util.cc(106)] Widevine encryption key source failed to fetch keys: 7 (HTTP_FAILURE): curl_easy_perform() failed: Problem with the SSL CA cert (path? access rights?).
[0822/225134:ERROR:packager_main.cc(512)] Failed to initialize packager: 3 (INVALID_ARGUMENT): Failed to create key source.

**Comment by kaushikkunal99** [comment]
this is the actual command

/opt/software/packager in=/opt/jobs/ae900cc4-f67c-417d-95e8-3e3eb63490b8/tmp/wm/A/ToS_216p_1M/video.mp4,stream=audio,init_segment=wm/audio/und/mp4a/init.mp4,segment_template=wm/audio/und/mp4a/\$Number\$.m4s in=/opt/jobs/ae900cc4-f67c-417d-95e8-3e3eb63490b8/tmp/wm/A/ToS_216p_1M/video.mp4,stream=video,init_segment=tmp/216/A/wm/video/avc1/ToS_216p_1M/seg_init_0.mp4,segment_template=tmp/216/A/wm/video/avc1/ToS_216p_1M/seg_\$Time\$.m4s in=/opt/jobs/ae900cc4-f67c-417d-95e8-3e3eb63490b8/tmp/wm/B/ToS_216p_1M/video.mp4,stream=video,init_segment=tmp/216/B/wm/video/avc1/ToS_216p_1M/seg_init_0.mp4,segment_template=tmp/216/B/wm/video/avc1/ToS_216p_1M/seg_\$Time\$.m4s in=/opt/jobs/ae900cc4-f67c-417d-95e8-3e3eb63490b8/tmp/wm/A/ToS_404p_1M/video.mp4,stream=video,init_segment=tmp/404/A/wm/video/avc1/ToS_404p_1M/seg_init_0.mp4,segment_template=tmp/404/A/wm/video/avc1/ToS_404p_1M/seg_\$Time\$.m4s in=/opt/jobs/ae900cc4-f67c-417d-95e8-3e3eb63490b8/tmp/wm/B/ToS_404p_1M/video.mp4,stream=video,init_segment=tmp/404/B/wm/video/avc1/ToS_404p_1M/seg_init_0.mp4,segment_template=tmp/404/B/wm/video/avc1/ToS_404p_1M/seg_\$Time\$.m4s in=/opt/jobs/ae900cc4-f67c-417d-95e8-3e3eb63490b8/tmp/wm/A/ToS_540p_1M/video.mp4,stream=video,init_segment=tmp/540/A/wm/video/avc1/ToS_540p_1M/seg_init_0.mp4,segment_template=tmp/540/A/wm/video/avc1/ToS_540p_1M/seg_\$Time\$.m4s in=/opt/jobs/ae900cc4-f67c-417d-95e8-3e3eb63490b8/tmp/wm/B/ToS_540p_1M/video.mp4,stream=video,init_segment=tmp/540/B/wm/video/avc1/ToS_540p_1M/seg_init_0.mp4,segment_template=tmp/540/B/wm/video/avc1/ToS_540p_1M/seg_\$Time\$.m4s in=/opt/jobs/ae900cc4-f67c-417d-95e8-3e3eb63490b8/tmp/wm/A/ToS_720p_2M/video.mp4,stream=video,init_segment=tmp/720/A/wm/video/avc1/ToS_720p_2M/seg_init_0.mp4,segment_template=tmp/720/A/wm/video/avc1/ToS_720p_2M/seg_\$Time\$.m4s in=/opt/jobs/ae900cc4-f67c-417d-95e8-3e3eb63490b8/tmp/wm/B/ToS_720p_2M/video.mp4,stream=video,init_segment=tmp/720/B/wm/video/avc1/ToS_720p_2M/seg_init_0.mp4,segment_template=tmp/720/B/wm/video/avc1/ToS_720p_2M/seg_\$Time\$.m4s in=/opt/jobs/ae900cc4-f67c-417d-95e8-3e3eb63490b8/tmp/wm/A/ToS_1080p_3M/video.mp4,stream=video,init_segment=tmp/1080/A/wm/video/avc1/ToS_1080p_3M/seg_init_0.mp4,segment_template=tmp/1080/A/wm/video/avc1/ToS_1080p_3M/seg_\$Time\$.m4s in=/opt/jobs/ae900cc4-f67c-417d-95e8-3e3eb63490b8/tmp/wm/B/ToS_1080p_3M/video.mp4,stream=video,init_segment=tmp/1080/B/wm/video/avc1/ToS_1080p_3M/seg_init_0.mp4,segment_template=tmp/1080/B/wm/video/avc1/ToS_1080p_3M/seg_\$Time\$.m4s --generate_static_mpd --mpd_output wm/ae900cc4-f67c-417d-95e8-3e3eb63490b8.mpd --enable_widevine_encryption --key_server_url https://license.widevine.com/cenc/getcontentkey/spedmg --content_id 5a8ae9 --signer spedmg --aes_signing_key ****************** --generate_dash_if_iop_compliant_mpd=false --aes_signing_iv ********* --fragment_duration 2

**Comment by kqyang** [comment]
@kaushikkunal99 Are you using the prebuilt packager binary in Shaka Packager Release? The failure is because Shaka Packager is unable to locate the CA BUNDLE on your machine. 

Can you check if file `/etc/ssl/certs/ca-certificates.crt` exists on your machine?

If not, how about the below files?

```
       '/etc/pki/tls/certs/ca-bundle.crt'
       '/etc/ssl/ca-bundle.pem'
       '/etc/ssl/cert.pem'
       '/etc/ssl/certs/ca-bundle.crt'
       '/etc/ssl/certs/ca-certificates.crt'
       '/usr/local/share/certs/ca-root.crt'
       '/usr/share/ssl/certs/ca-bundle.crt'
```

If any of the above files exist, you can copy it to /etc/ssl/certs/ca-certificates.crt. This should resolve your problem.

Alternatively, you can re-build Shaka Packager on your machine, which will try to locate a valid CA BUNDLE by itself.

**Comment by kaushikkunal99** [comment]
i did that but now i get another error. could you check. Can it be issue with the keys?

[0823/014134:ERROR:widevine_key_source.cc(406)] Received non-OK license response: {"response":"eyJzdGF0dXMiOiJTSUdOQVRVUkVfRkFJTEVEIiwiZHJtIjpbXSwidHJhY2tzIjpbXX0="}
[0823/014134:ERROR:packager_util.cc(106)] Widevine encryption key source failed to fetch keys: 13 (SERVER_ERROR): Failed to extract encryption key from '{"response":"eyJzdGF0dXMiOiJTSUdOQVRVUkVfRkFJTEVEIiwiZHJtIjpbXSwidHJhY2tzIjpbXX0="}'.
[0823/014134:ERROR:packager_main.cc(512)] Failed to initialize packager: 3 (INVALID_ARGUMENT): Failed to create key source.

**Comment by kaushikkunal99** [comment]
@kqyang I have tried few things buy building the packager from source. It seems to work fine with widevine_test url and keys but not with our keys. What could be the issue.

:ERROR:widevine_key_source.cc(406)] Received non-OK license response: {"response":"eyJzdGF0dXMiOiJTSUdOQVRVUkVfRkFJTEVEIiwiZHJtIjpbXSwidHJhY2tzIjpbXX0="}
[0823/164240:ERROR:packager_util.cc(106)] Widevine encryption key source failed to fetch keys: 13 (SERVER_ERROR): Failed to extract encryption key from '{"response":"eyJzdGF0dXMiOiJTSUdOQVRVUkVfRkFJTEVEIiwiZHJtIjpbXSwidHJhY2tzIjpbXX0="}'.
[0823/164240:ERROR:packager_main.cc(512)] Failed to initialize packager: 3 (INVALID_ARGUMENT): Failed to create key source.
