### ISSUE TITLE
Add year to logging timestamp

### ISSUE THREAD

**Issue by jakubvojacek** [google/shaka-packager#462]
Hello,

would it be possible to add year to the logging output that's produced by the packager?

```
[0828/091027:INFO:demuxer.cc(88)] Demuxer::Run() on file 'udp://239.100.201.2:1234'.
```

would turn into

```
[20180828/091027:INFO:demuxer.cc(88)] Demuxer::Run() on file 'udp://239.100.201.2:1234'.
```

I am processing the output of packager and saving the events for analysis and it would be helpful to have the year information there. Most of the times, the year would be the current year with the exception of 12/31 - 1/1, that could cause some bad logging data.

Thank you

**Comment by kqyang** [comment]
Unfortunately, the logging module is provided by a third_party library (chromium base): https://cs.chromium.org/chromium/src/base/logging.cc?rcl=9983115b5c066addb668dea33bfe1a381c5f560c&l=891.

We are thinking of switching to google/glog for the logging, which does have "year" in the logging timestamp: https://github.com/google/glog/blob/master/src/logging.cc#L997. That will not happen some time soon though.

> Most of the times, the year would be the current year with the exception of 12/31 - 1/1, that could cause some bad logging data.

Luckily that is not difficult to handle :). 

I'll close this issue as "will not implement". Feel free to reply if you have more questions.

**Comment by vaage** [comment]
@kqyang Would swapping over to google/glog be something your willing to take as a pull request? If so, you could change this to "help wanted" with the instruction that the solution is to adopt google/glog.

**Comment by kqyang** [comment]
@vaage That is dependent on https://github.com/google/shaka-packager/issues/346, which is not a trivial task, unfortunately.
