### ISSUE TITLE
File full path for help message

### ISSUE THREAD

**Issue by Jason239** [google/shaka-packager#464]
I am currently using the shaka packager as SDK.
However, in the third party gflags_reporting.cc, the function 'ShowUsageWithFlagsMatching' is printing internal full file paths.

`fprintf(stdout, "\n  Flags from %s:\n", flag->filename.c_str());`

Is there an option that will prevent the entire path from being printed?

**Comment by kqyang** [comment]
Not that I am aware of. You can update flags_reporting.cc to remove that printing if you don't like. If you want to it in a clean way, you can file an issue to gflags https://github.com/gflags/gflags/issues to add an option to hide the file names.

Does that answer your question?

**Comment by Jason239** [comment]
Okay!
Thank you!
