### ISSUE TITLE
More than one instance of shaka::Packager running together

### ISSUE THREAD

**Issue by leonidgurevich** [google/shaka-packager#468]
## System info
**Operating System**:Ubuntu 16.04

Did anybody tried to create executable that runs several instances of shaka::Packager, each with it's own set of Packaging parameters and Stream descriptors? 
When I tried it - I was able to initialize all of them, but Packager::Run() started only for the first one. 
Is this locking behavior expected? Any ideas, why?

Thanks!

**Comment by kqyang** [comment]
Are you trying to start all of them at the same time? You'll need to run them in different processes/threads as Packager::Run() blocks.

**Comment by leonidgurevich** [comment]
Thanks a lot! Looks much better now.

**Comment by kqyang** [comment]
Great! Is your problem fixed? Can we close this issue?

**Comment by leonidgurevich** [comment]
Thanks again!
