### ISSUE TITLE
Audio and video unaligned in segment timeline

### ISSUE THREAD

**Issue by jakubvojacek** [google/shaka-packager#471]
## System info
**Operating System**: latest debian
**Shaka Packager Version**: master

## Issue and steps to reproduce the problem

**Packager Command**:
```
packager  'in=udp://239.0.1.36:1000?reuse=1&buffer_size=10000000,stream=0,bandwidth=400000,init_segment=dtv-44_video_640_360.mp4,segment_template=video_640_360/dtv-44-$Number$.mp4' 'in=udp://239.0.1.36:1000?reuse=1&buffer_size=10000000,stream=1,bandwidth=1000000,init_segment=dtv-44_video_720_410.mp4,segment_template=video_720_410/dtv-44-$Number$.mp4' 'in=udp://239.0.1.36:1000?reuse=1&buffer_size=10000000,stream=2,bandwidth=2500000,init_segment=dtv-44_video_1920_1080.mp4,segment_template=video_1920_1080/dtv-44-$Number$.mp4' 'in=udp://239.0.1.36:1000?reuse=1&buffer_size=5000000,stream=3,language=spa, init_segment=dtv-44_audio_spa-490.mp4,segment_template=audio_spa-490/audio_spa-490-$Number$.mp4' --time_shift_buffer_depth 15000 --hls_playlist_type LIVE --hls_master_playlist_output dtv-44.m3u8 --mpd_output dtv-44.mpd --fragment_duration 3.2 --segment_duration 3.2  --suggested_presentation_delay 5 --min_buffer_time 3.2 --minimum_update_period 5 --default_language=spa --allow_approximate_segment_timeline --io_cache_size 3000000 
```

**What is the expected result?**
Smooth playback in players

**What happens instead?**
There seems to be an issue with non-synchronized audio / video. It's better described in https://github.com/google/shaka-player/issues/1572#issuecomment-420356595 as I originally thought it was a shaka player issue. When watching this channel in mcast, there seem to be no issues, also nor ffmpeg nor packager reports any errors. 

Not really sure how to reproduce this on your side, please let me know if you need anything from us. Do you think this could be caused by shaka packager or an issue in the content?

Thank you

**Comment by kqyang** [comment]
@jakubvojacek It looks like encoding or source problem to me since packager does not change incoming media timestamps unless there is a bug somewhere in packager in extracting the timestamps. Can you record a few minutes of source content and share with me?

**Comment by kaushikkunal99** [comment]
hi There,

Similar issue on our side as well. We are using Shaka packager to generate DASH timeline. The video starts of fine but when we seek to middle or more it starts to go out of sync with audio
Attached is the mpd file if it helps.

**Comment by kqyang** [comment]
@kaushikkunal99 I don't think what you have is the same issue. I looked at the attached mpd, which is for an on-demand content (using DASH static live profile) while the problem in this issue is that the audio somehow lags behind video at the live edge for about 2 minutes. Can you open another issue and describe it in detail? Thanks!

**Comment by kaushikkunal99** [comment]
Ok opened https://github.com/google/shaka-packager/issues/472

Thanks

**Comment by jakubvojacek** [comment]
@kqyang will try to get the recordings as soon as possible and post here, thank you

**Comment by kqyang** [comment]
@jakubvojacek Any update on this issue?

**Comment by jakubvojacek** [comment]
@kqyang still having the issues but didnt get the files yet, can we please keep this open for few more days?

**Comment by kqyang** [comment]
@jakubvojacek No problem!

**Comment by jakubvojacek** [comment]
A colleague of mine helped me analyze the inputs and it seems that there are indeed issues on the input occasionally rather that in packager, sorry about wasting your time.
