### ISSUE TITLE
Option --default_language not working for HLS

### ISSUE THREAD

**Issue by mdaftab88** [google/shaka-packager#473]
## System info
**Operating System**: Ubuntu
**Shaka Packager Version**: 2.2.0 (51d39d9-release)

## Issue and steps to reproduce the problem

**Packager Command**:
`packager 
'in=audio_french.mp4,stream=audio,language=fr,segment_template=audio_french/$Number$.aac,playlist_name=audio_french/main.m3u8,hls_name=FRENCH' 
'in=audio_english.mp4,stream=audio,language=en,segment_template=audio_english/$Number$.aac,playlist_name=audio_english/main.m3u8,hls_name=ENGLISH' 
'in=audio_german.mp4,stream=audio,language=de,segment_template=audio_german/$Number$.aac,playlist_name=audio_german/main.m3u8,hls_name=GERMAN' 
'in=video-240.mp4,stream=video,segment_template=h264_240p/$Number$.ts,playlist_name=h264_240p/main.m3u8,iframe_playlist_name=h264_240p/iframe.m3u8' 
'in=video-480.mp4,stream=video,segment_template=h264_480p/$Number$.ts,playlist_name=h264_480p/main.m3u8,iframe_playlist_name=h264_480p/iframe.m3u8' 
'in=video-720.mp4,stream=video,segment_template=h264_720p/$Number$.ts,playlist_name=h264_720p/main.m3u8,iframe_playlist_name=h264_720p/iframe.m3u8' 
'in=video-1080.mp4,stream=video,segment_template=h264_1080p/$Number$.ts,playlist_name=h264_1080p/main.m3u8,iframe_playlist_name=h264_1080p/iframe.m3u8' 
--default_language de 
--hls_master_playlist_output h264_master.m3u8`

What is the expected result?
When I play this manifest using shaka-player on ipad safari, it plays english audio.

What happens instead?
It should play German audio file

Extra information:
I looked into h264_master.m3u8 file, it contains AUTOSELECT=YES for all the three audio languages.

![image](https://user-images.githubusercontent.com/25167441/45361430-c0b99880-b5ef-11e8-9b65-0d27a42e2820.png)
.

**Comment by kqyang** [comment]
In your attachment, the German audio file has attribute "DEFAULT=YES" set. 

According to [HLS](https://tools.ietf.org/html/rfc8216) spec:

      DEFAULT

      The value is an enumerated-string; valid strings are YES and NO.
      If the value is YES, then the client SHOULD play this Rendition of
      the content in the absence of information from the user indicating
      a different choice.  This attribute is OPTIONAL.  Its absence
      indicates an implicit value of NO.

      AUTOSELECT

      The value is an enumerated-string; valid strings are YES and NO.
      This attribute is OPTIONAL.  Its absence indicates an implicit
      value of NO.  If the value is YES, then the client MAY choose to
      play this Rendition in the absence of explicit user preference
      because it matches the current playback environment, such as
      chosen system language.

So packager is doing the correct thing. Is it possible that on your client you indicated you want English?

**Comment by kqyang** [comment]
@mdaftab88 Any update on this issue?

**Comment by mdaftab88** [comment]
@kqyang Sorry for late response.

Actually I am using mpd output for playing video using shaka-player. But shaka-player does not supported on ipad or iphone. So I am trying to play video using shaka-packager hls with ts output when device is ipad or iphone. This is working fine but only issue is default language. 

**_Is it possible that on your client you indicated you want English?_**
At client I am just using `video.src `, nothing other than this. So there is no way so that English got selected by client.

Thanks.

**Comment by kqyang** [comment]
@mdaftab88 Are you using video.src directly or using Shaka Player?

**Comment by joeyparrish** [comment]
On iOS, it would have to be `video.src`.  Shaka Player is not usable on iOS yet, and when it becomes usable on iOS, it will be passing everything through to `video.src`.

**Comment by joeyparrish** [comment]
I just tested this with a colleague on our own multilingual content, and we found that the `DEFAULT` attribute is applied to the media playlist corresponding to the `--default_language` flag.  So that seems to be in order, and makes sense with the spec text quoted by @kqyang above.

What language is the iOS device set to at the OS level?

**Comment by mdaftab88** [comment]
@kqyang @joeyparrish when `shaka.Player.isBrowserSupported()` returns false,  I am assigning path of my m3u8 file to `video.src`.

**Comment by mdaftab88** [comment]
@joeyparrish 

**What language is the iOS device set to at the OS level?**
I am not sure about this. Will check and update you asap.

**Comment by mdaftab88** [comment]
@joeyparrish 

This make sense. As I change the language preferences at the OS level, it works. 

But again, the question is: **Is there a way to override this?** Because there is no meaning of making a language default if it depends on OS level settings. I know this is not within the scope of shaka-packager, but please suggest if there is a way to override it.

**Comment by joeyparrish** [comment]
Safari's native HLS implementation does not seem to have any API to select a language.  A player using MediaSource would, of course, give you an API for this.  But Safari on iOS does not offer MediaSource, so even a future version of Shaka Player which runs on iOS would not be capable of this.

If there **is** some way to select audio languages in Safari, you would have to find out from Apple.  I'm sorry I can't give you an authoritative answer on this.

**Comment by mdaftab88** [comment]
@joeyparrish 

Thanks a lot for making everything clear to me. I got no solution for this but still I will always be thankful to you for giving me detailed information.

Since this issue is not within the scope of shaka-packager (as well as shaka-player), so closing it.

**Comment by joeyparrish** [comment]
I'm glad we could help.  Thanks for being patient with us during the investigation.
