### ISSUE TITLE
raw key encryption producing output with both encrypted and unencrypted content

### ISSUE THREAD

**Issue by sammirata** [google/shaka-packager#477]
I am using the following command line to encrypt a single small transport stream file (one video and two audios in that order):
/usr/sbin/packager input=/data/public/cache/cbsreality/ts/PLA1_FOOD_NETWORK_UHD_2018_09_14_00_57_57-17811.ts,stream_selector=0,init_segment=/data/public/cache/cbsreality/ts/PLA1_FOOD_NETWORK_UHD_2018_09_14_00_57_57-17811-video-0-init.mp4,segment_template=/data/public/cache/cbsreality/ts/PLA1_FOOD_NETWORK_UHD_mono-video-0-$Time$.mp4 -segment_duration=1000 -fragment_duration=1000 -mp4_sequence_number_initial=20000 -mpd_output /data/public/cache/cbsreality/m3u8/PLA1_FOOD_NETWORK_UHD_2018_09_14_00_57_57-17811-video-0.mpd --enable_raw_key_encryption --keys label=:key_id=c2af7d2d61df454fbe198666f93b6822:key=755840218baf89d91bde031b0bd40efb --iv=c2af7d2d61df454fbe198666f93b6822 --pssh 000000577073736800000000EDEF8BA979D64ACEA3C827DCD51D21ED0000003708011210C2AF7D2D61DF454FBE198666F93B68221A0B62757964726D6B65796F732210C2AF7D2D61DF454FBE198666F93B68222A024844 -allow_approximate_segment_timeline

The resulting init file has this structure (extracted with mp4info):
sergio@sergio-Asus-2-in-1-Q525UA:~/Videos/drm$ /home/sergio/Development/Bento4-SDK-1-5-1-624.x86_64-unknown-linux/bin/mp4info PLA1-video-1t-init.mp4 
File:
  major brand:      isom
  minor version:    0
  compatible brand: iso8
  compatible brand: mp41
  compatible brand: dash
  compatible brand: avc1
  compatible brand: cmfc
  fast start:       yes

Movie:
  duration:   0 ms
  time scale: 90000
  fragments:  yes

Found 1 Tracks
Track 1:
  flags:        7 ENABLED IN-MOVIE IN-PREVIEW
  id:           1
  type:         Video
  duration: 0 ms
  language: und
  media:
    sample count: 0
    timescale:    90000
    duration:     0 (media timescale units)
    duration:     0 (ms)
    bitrate (computed): 0.000 Kbps
    sample count with fragments: 0
    duration with fragments:     0
    duration with fragments:     0 (ms)
  display width:  1280.000000
  display height: 720.000000
  Sample Description 0
    [ENCRYPTED]
      Coding:         encv
      Scheme Type:    cenc
      Scheme Version: 65536
      Scheme URI:     
    Coding:      avc1 (H.264)
    Width:       1280
    Height:      720
    Depth:       24
    AVC Profile:          77 (Main)
    AVC Profile Compat:   40
    AVC Level:            31
    AVC NALU Length Size: 4
    AVC SPS: [674d401feca02802dd8088000003000800000301e078c18cb0]
    AVC PPS: [68efbc80]
    Codecs String: avc1.4D401F
  Sample Description 1
    Coding:      avc1 (H.264)
    Width:       1280
    Height:      720
    Depth:       24
    AVC Profile:          77 (Main)
    AVC Profile Compat:   40
    AVC Level:            31
    AVC NALU Length Size: 4
    AVC SPS: [674d401feca02802dd8088000003000800000301e078c18cb0]
    AVC PPS: [68efbc80]
    Codecs String: avc1.4D401F

Am I understanding the data correctly? Do I have two Samples inside the track, one encrypted and one unencrypted? ... it should not be doing this. How can I fix/troubleshoot this?

**Comment by kqyang** [comment]
By default, there is a 6 seconds clear lead. You can disable the clear lead if you do not want it: `--clear_lead=0`. See https://google.github.io/shaka-packager/html/documentation.html#general-encryption-options.

Hope that helps!

**Comment by sammirata** [comment]
Thank you!!!
Adding --clean_lead=0 got rid of the clear content. The files were on average about 6 seconds which made the encryption useless because of that ...
Now, there is only one sample and it is encrypted.
