### ISSUE TITLE
The stream starts only later

### ISSUE THREAD

**Issue by welzon** [google/shaka-packager#479]
## System info

**Operating System:** 4.9.0-6-amd64
**Shaka Packager Version:** packager version 26997bb-release

## Issue and steps to reproduce the problem

**Packager Command:**

packager 
'in=udp://239.190.176.151:5000,stream=1,init_segment=a_init.mp4,segment_template=a$Number$.m4s' 'in=udp://239.190.176.151:5000,stream=2,init_segment=b_init.mp4,segment_template=b$Number$.m4s'
'in=udp://239.190.176.151:5000,stream=0,init_segment=c_init.mp4,segment_template=c$Number$.m4s'
'in=udp://239.190.176.151:5000,stream=3,init_segment=d_init.mp4,segment_template=d$Number$.m4s'
--mpd_output h264live.mpd

What is the expected result?
If I start the stream it works immediately.

What happens instead?
Only in the first ~20 sec (first 3 segments) it isn't started, after that it works normally. If I stop then starts again, I have to wait another 3 segments, before it works.

I have tried it with two different player (jw, dashif.org). Copied the links and the error messages from console.

http://reference.dashif.org/dash.js/v2.3.0/samples/dash-if-reference-player/index.html
SegmentsUtils.js:253 Uncaught TypeError: Cannot read property 'start' of null
 
https://developer.jwplayer.com/tools/stream-tester/
JW Player Error 240000. For more information see https://developer.jwplayer.com/jw-player/docs/developer-guide/api/errors-reference/#240000

I'm not even sure if it is Shaka Packager problem, but maybe it offers a solution, and you can help me.
Thanks

**Comment by kqyang** [comment]
@welzon The streaming start latency should be about 2 to 3 segments. It seems like you are using the default segment duration of 10 seconds based on the packager version you are using: 26997bb. So I am not surprised to see a start up time of ~20s.

If you want a faster start up, you should try to reduce the GOP size and the segment duration. 

What is your GOP size right now?
