### ISSUE TITLE
MPD @mediaPresentationDuration generated value

### ISSUE THREAD

**Issue by ctoshni** [google/shaka-packager#480]
Hi, i'm using latest Shaka version ;

Shaka packager is generating mediaPresentationDuration as "PT345.8399963378906S". I have a usecase to verify this duration but due to 13 digits after decimal "." my code fails to convert it. I wanted to check -
1. In which format shaka-packager generates mediaPresentationDuration?
2. Is there any parameter in the command which I can specify to control this generated mediaPresentationDuration?

**Comment by kqyang** [comment]
@ctoshni 

> In which format shaka-packager generates mediaPresentationDuration?

It is computed using the floating point library from http://www.netlib.org/fp/. You can also checkout the source code here: https://cs.chromium.org/chromium/src/base/third_party/dmg_fp/g_fmt.cc?rcl=9a4a94d66c8b42c979b083a4062ea1b696b146e8&l=30.

We used to have a lower precision string format, but it was causing problems in multi-period contents as MSE and most browsers require at least micro-seconds precision. 

The exact algorithm for the double to string conversion may be subject to change, but we will always make sure that it has micro-seconds precision.

> Is there any parameter in the command which I can specify to control this generated mediaPresentationDuration?

No. You can fork the project and update the code to use a lower precision conversion algorithm if you want: https://github.com/google/shaka-packager/blob/6b4a75b6bacdac6b0b9f598c365c8f84f0a7fd70/packager/mpd/base/mpd_utils.cc#L180.

Not sure what is your use case. Another way would be to update your code to support arbitrary number of digits if it is easier.

Does that answer your question?

**Comment by ctoshni** [comment]
@kqyang - 

> We used to have a lower precision string format, but it was causing problems in multi-period contents as MSE and most browsers require at least micro-seconds precision.

If shaka-packager generates microseconds precision i.e 10^-6 then why mediaPresentationDuration got generated in 10^-12 i.e "PT345.8399963378906S" ?

**Comment by kqyang** [comment]
Our goal is to generate **at least** microseconds precision :). Better than microseconds precision is not necessary but always a plus, especially that it does not require additional work with the floating point library we are using.

**Comment by ctoshni** [comment]
Thanks!
