### ISSUE TITLE
Prebuilt binaries picking up flags from now deleted build

### ISSUE THREAD

**Issue by SingingTree** [google/shaka-packager#481]
## System info
**Operating System**: Windows 10
**Shaka Packager Version**:  v2.2.0-9e9833ea63-release

## Issue and steps to reproduce the problem

**Packager Command**: `packager-win.exe`

When running the above prebuilt Windows binary, I see a number of command line flags listed from shaka-packager build I used to have on my machine, but has since been deleted.

What is the expected result?

When running the command I expect to see the default help output for the shaka-packager.

What happens instead?

I see the expected help output, but it is followed by a number of other flags that are stated to be from my old and removed shaka-packager local build. For example, I see the following output as part of the help shown:

```
Flags from c:\projects\shaka-packager\src\packager\third_party\gflags\src\src\gflags_completions.cc:
    -tab_completion_columns (Number of columns to use in output for tab
      completion) type: int32 default: 80
    -tab_completion_word (If non-empty, HandleCommandLineCompletions() will
      hijack the process and attempt to do bash-style command line flag
      completion on this value.) type: string default: ""
```
where `c:\projects\shaka-package` is where shaka-packager was where I had the shaka-packager src.

I see a large number of such outputs. I imagine there is some files that I've failed to clean up when removing my local shaka-packager build, but am having trouble locating them.

**Comment by kqyang** [comment]
@SingingTree It actually has nothing to do with your deleted build. They are the actual flags defined in the prebuilt binary :). The prebuilt binary happens to be built from the same path: https://github.com/google/shaka-packager/blob/master/appveyor.yml#L16.

**Comment by SingingTree** [comment]
Ha, just a coincidence then. Thanks for clarifying!
