### ISSUE TITLE
Allow adding CUSTOMATTRIBUTES element in PlayReady Header

### ISSUE THREAD

**Issue by yutuoheng** [google/shaka-packager#482]
As mentioned in [PlayReady Header Specification](https://docs.microsoft.com/en-us/playready/specifications/playready-header-specification), there is a CUSTOMATTRIBUTES element where the content author can add arbitrary XML. Is there any way that we can add our XML in this element with Shaka Packager?

**Comment by kqyang** [comment]
Yes, Shaka Packager supports user provided PSSH. You can put anything in the PSSH, including the CUSTOMATTRIBUTES. See https://google.github.io/shaka-packager/html/tutorials/raw_key.html for examples.

Does that answer your question?

**Comment by yutuoheng** [comment]
Ah yes. Thanks a lot!
