### ISSUE TITLE
Can't generate AV1 dash and manifest for input AV1 webm file

### ISSUE THREAD

**Issue by rainliu** [google/shaka-packager#485]
## System info
**Operating System**: <e.g. macOS Sierra, Ubuntu 14.04 trusty etc>
macOS
**Shaka Packager Version**: <e.g. v1.6.1, commit SHA etc>
master

## Issue and steps to reproduce the problem
(https://github.com/google/shaka-packager/files/2426108/bbb_30s_av1_144p.webm.zip)

**Packager Command**:

Extra steps to reproduce the problem?
1). unzip bbb_30s_av1_144p.webm.zip to get bbb_30s_av1_144p.webm
2) /Debug/packager in=bbb_30s_av1_144p.webm,stream=video,output=dash_bbb_30s_av1_144p.webm --mpd_output bbb_30s_av1_144p.mpd

What is the expected result?
should generate dash webm and mpd file without crash.

What happens instead?
can't parse input AV1 webm

[0927/152553:INFO:demuxer.cc(88)] Demuxer::Run() on file 'bbb_30s_av1_144p.webm'.
[0927/152553:INFO:demuxer.cc(160)] Initialize Demuxer for file 'bbb_30s_av1_144p.webm'.
[0927/152553:ERROR:av1_codec_configuration_record.cc(45)] Failure while processing: data_size > 0
[0927/152553:ERROR:webm_video_client.cc(72)] Failed to parse AV1 codec_private.
[0927/152553:ERROR:packager_main.cc(517)] Packaging Error: 8 (PARSER_FAILURE): Cannot parse media file bbb_30s_av1_144p.webm

<Please attach the input files or email to shaka-packager-issues@google.com.>
<Please provide any additional information below.>
[](url)
[bbb_30s_av1_144p.webm.zip](https://github.com/google/shaka-packager/files/2426109/bbb_30s_av1_144p.webm.zip)

**Comment by kqyang** [comment]
@rainliu I don't think the file you have is compliant to av1 in WebM spec. According to https://github.com/Matroska-Org/matroska-specification/blob/master/codec/av1.md#codecprivate-1, CodecPrivate is mandatory, which is missing in bbb_30s_av1_144p.webm.

How is the file encoded?

**Comment by rainliu** [comment]
@kqyang, thanks for pointing out. The file is encoded by using ffmpeg 4.0.2. It looks like ffmpeg just add the CodecPrivate a few day ago: https://git.ffmpeg.org/gitweb/ffmpeg.git/commitdiff/4755b6e6d194b0a0fb72957cd3dc0eaf7b2375f7

**Comment by kqyang** [comment]
@rainliu Great. I'll close this issue now. Feel free to re-open or reply to this issue if you are still seeing problems with latest version of ffmpeg.
