### ISSUE TITLE
Raw Keys not encrypting content

### ISSUE THREAD

**Issue by cdgriffith** [google/shaka-packager#486]
## System info
**Operating System**: Windows 10 x64
**Shaka Packager Version**: v2.2.1

## Issue and steps to reproduce the problem

**Packager Command**:  `packager-win.exe in=darkroom_timer.mp4,stream=audio,output=audio1.mp4,drm_label=AUDIO in=darkroom_timer.mp4,stream=video,output=video1.mp4,drm_label=VIDEO --enable_raw_key_encryption --keys label=AUDIO:key_id=11111111111111111111111111111111:key=11111111111111111111111111111111,label=VIDEO:key_id=11111111111111111111111111111111:key=11111111111111111111111111111111 --protection_scheme cenc --protection_systems CommonSystem --mpd_output 1.mpd`

What is the expected result?  `video1.mp4` to be encrypted. 

What happens instead? `video1.mp4` can be played without specifying keys using Media Player Classic. 

<Please attach the input files or email to shaka-packager-issues@google.com.>
<Please provide any additional information below.>

I am trying to switch from using mp4dash to make sure my files don't have any issues with Shaka Player. The command I would use for that is `mp4dash.bat --encryption-key=11111111111111111111111111111111:11111111111111111111111111111111 --no-split darkroom_timer.mp4`  which does produce a protected file. 

[darkroom_timer.zip](https://github.com/google/shaka-packager/files/2429574/darkroom_timer.zip)

**Comment by kqyang** [comment]
@cdgriffith There is a default 6 seconds clear lead. You can try setting the default clear lead to 0 and try again: https://google.github.io/shaka-packager/html/documentation.html#general-encryption-options. Let us know if it addresses your problem!

**Comment by cdgriffith** [comment]
Ah ha! Totally missed that setting, thank you very much @kqyang !
