### ISSUE TITLE
Cannot demux mpeg-ts with AC-3/E-AC-3 (kFrameSizeCodeTable columns are reversed)

### ISSUE THREAD

**Issue by dcaiafaISP** [google/shaka-packager#487]
## System info
**Operating System**: all
**Shaka Packager Version**: v2.2.1

mp2t/ac3_header.cc: kFrameSizeCodeTable columns (fscod) are reversed. They are ordered 32, 44.1 and 48 (as in A/52 Table 5.18), but fscod is 0 = 48, 1 = 44.1, 2 = 32.

For example: kFrameSizeCodeTable[22][0] should be 448, instead it is 672. So EsParserAudio consistently calculates the wrong frame size and ends up discarding everything.

**Comment by kqyang** [comment]
@dcaiafaISP Thanks for the bug report. Yes, you are right. Would like to submit a pull request to fix the problem?

**Comment by dcaiafaISP** [comment]
@kqyang Absolutely, was already planning to.

**Comment by kqyang** [comment]
@dcaiafaISP Great! Thanks for your help.

**Comment by kqyang** [comment]
@dcaiafaISP Are you still working on your patch/pull request?
