### ISSUE TITLE
This is not an issue but a request for recommendations on encoding settings

### ISSUE THREAD

**Issue by pineapplejoe** [google/shaka-packager#488]
I have looked for a place that covers this and I have not found anything (that isnt already advanced and uses terms I dont know). 

I am using AWS MediaConvert to take original video and creating DASH output. 

I am creating three streams - 720, 1080 and 1440. Respective bitrates (in Mbps) are avg 2 max 3, avg 3.5 max 4.5 and avg 5 max 8.  

Additional settings are 
"SegmentLength": 2, 
"MinBufferTime": 10, 
"FragmentLength": 4, 
"GopSize": 60 
"GopClosedCadence": 1

Im trying to ensure that transitions between different variants are as seamless as possible to minimize jitter and lag.  What I have now is better than my previous settings (fragment length of 30 and a few more variations) - im finding that this is more experimentation and im looking for more determinism or at least a deeper pool of experience.  

Target devices are devices (laptops, tablets) on wifi or lan.  not so much cellular.  The content is being served out of s3/cloudfront. 

Are there general encoding recommendations for the resolutions noted above?

Thanks

**Comment by kqyang** [comment]
I am not familiar with AWS MediaConvert and what the setting means. It seems to be more of a question for AWS support.

As for a general encoding recommendations, you need to make sure that all variations have aligned GOPs. It looks like you are serving an on-demand content. We recommend a segment duration of 6 seconds, a GOP duration of 1 to 3 seconds (segment duration should be a multiple of GOP duration).

You should be able to achieve seamless transition with a good player, e.g. Shaka Player.

Hope that helps. Feel free to re-open the issue if you have more questions.

**Comment by pineapplejoe** [comment]
Thanks @kqyang. I made the adjustments and things seem to be better but still encountering performance issues. 

Maybe this is a question for the shaka-player - which I am also using but what do you recommend for the variants?  How far apart should the bitrates be? 

Per above I have the following streams - 720, 1080 and 1440. Respective bitrates (in Mbps) are avg 2 max 3, avg 3.5 max 4.5 and avg 5 max 8.

720: 2Mbps
1080: 3.5 Mbps
1440: 5 Mpbs

I've added another stream with a few better settings at 1440: 7Mbps.

Are these separations too big?  Should I have more streams that are closer together?

**Comment by kqyang** [comment]
For performance issue, are you still talking about jitter and lag?

> Maybe this is a question for the shaka-player

Yes, please file an issue to shaka-player, and they will help you on adaptation related problems. 

> Are these separations too big? Should I have more streams that are closer together?

No, it seems adequate to me.
