### ISSUE TITLE
Possible issue with packaging higher bitrates

### ISSUE THREAD

**Issue by jakubvojacek** [google/shaka-packager#489]
## System info
**Operating System**: latest debian
**Shaka Packager Version**: 8d11e5ea6494dd70513b38d7c1d5bb1b42a56e8c

## Issue and steps to reproduce the problem

**Packager Command**:
```
packager -v 10  'in=udp://239.100.1.23:1234?reuse=1&buffer_size=25000000,stream=0,bandwidth=300000,init_segment=eurosport-1-hd-test-52_video_640_360.mp4,segment_template=video_640_360/eurosport-1-hd-test-52-$Number$.mp4' 'in=udp://239.100.1.23:1234?reuse=1&buffer_size=25000000,stream=1,bandwidth=800000,init_segment=eurosport-1-hd-test-52_video_720_410.mp4,segment_template=video_720_410/eurosport-1-hd-test-52-$Number$.mp4' 'in=udp://239.100.1.23:1234?reuse=1&buffer_size=37500000,stream=2,bandwidth=2500000,init_segment=eurosport-1-hd-test-52_video_1920_1080.mp4,segment_template=video_1920_1080/eurosport-1-hd-test-52-$Number$.mp4' 'in=udp://239.100.1.23:1234?reuse=1&buffer_size=75000000,stream=3,bandwidth=5000000,init_segment=eurosport-1-hd-test-52_video_1920_1080_2.mp4,segment_template=video_1920_1080_2/eurosport-1-hd-test-52-$Number$.mp4' 'in=udp://239.100.1.23:1234?reuse=1&buffer_size=120000000,stream=4,bandwidth=8000000,init_segment=eurosport-1-hd-test-52_video_1920_1080_2.mp4,segment_template=video_1920_1080_2/eurosport-1-hd-test-52-$Number$.mp4' 'in=udp://239.100.1.23:1234?reuse=1&buffer_size=25000000,stream=5,bandwidth=128000,language=cze, init_segment=eurosport-1-hd-test-52_audio_cze.mp4,segment_template=audio_cze/audio_cze-$Number$.mp4' 'in=udp://239.100.1.23:1234?reuse=1&buffer_size=25000000,stream=6,bandwidth=128000,language=eng, init_segment=eurosport-1-hd-test-52_audio_eng.mp4,segment_template=audio_eng/audio_eng-$Number$.mp4' 'in=udp://239.100.1.23:1234?reuse=1&buffer_size=25000000,stream=7,bandwidth=128000,language=hun, init_segment=eurosport-1-hd-test-52_audio_hun.mp4,segment_template=audio_hun/audio_hun-$Number$.mp4' 'in=udp://239.100.1.23:1234?reuse=1&buffer_size=25000000,stream=8,bandwidth=128000,language=rn, init_segment=eurosport-1-hd-test-52_audio_rn.mp4,segment_template=audio_rn/audio_rn-$Number$.mp4' 'in=/data/assets/channels//live/eurosport-1-hd-test-52/channel_cs.vtt,stream=text,init_segment=eurosport-1-hd-test-52_subtitle_init_cs.mp4,segment_template=subtitle_cs/ttv_$Number$.mp4,language=cs' --time_shift_buffer_depth 15000 \
--mpd_output eurosport-1-hd-test-52.mpd \
--fragment_duration 1.6 \
--segment_duration 1.6 \
--suggested_presentation_delay 10 \
--min_buffer_time 3 \
--minimum_update_period 4 \
--default_language=eng \
--allow_approximate_segment_timeline \
--utc_timings urn:mpeg:dash:utc:http-head:2014=https://mw.xxxxx.eu/time.txt \
--io_cache_size 34224000
```

What is the expected result?
I would like for the player to be able to play the highest bitrate (8000000). 

What happens instead?
All the other bitrates are playing fine except for `8000000`. When we switch to this bitrate, the player stops. We tested on shaka player, dashjs and exoplayer. The shaka player ended up with an error `CHUNK_DEMUXER_ERROR_APPEND_FAILED: Append: stream parsing failed. Data size=131072 append_window_start=0 append_window_end=inf` and dashjs ended up with error `[7145][StreamController] Video Element Error: MEDIA_ERR_DECODE (CHUNK_DEMUXER_ERROR_APPEND_FAILED: Append: stream parsing failed. Data size=131072 append_window_start=0 append_window_end=inf) `. The URL to a sample MPD is https://goo.gl/z6KB3c.

Not entirely sure what is the issue but since 3 different players are failing, I am assuming its a content issue. Can you please check the error reported by the players and tell me whether it sounds like packager issue, input issue or a player issue?

Thank you
Jakub

**Comment by kqyang** [comment]
Re-produced the problem successfully. Will take a deep look later.

**Comment by kqyang** [comment]
@jakubvojacek Looks like there are some data corruptions in the `mdat` - not sure how did it occur. Can you try to record a few minutes of input streams and share with us (you may email it to shaka-packager-issues@google.com if it cannot be shared publicly)?

**Comment by jakubvojacek** [comment]
@kqyang please download the input multicast that we feed to the packager here https://goo.gl/2wcqYv

Thank you

**Comment by rkuroiwa** [comment]
@jakubvojacek if that's the exact command that you used, then it looks like `eurosport-1-hd-test-52_video_1920_1080_2.mp4` and all files under `video_1920_1080_2/` are getting overwritten by whichever gets processed later (5MBps stream or 8MBps stream).
I believe stream 4 should go to `eurosport-1-hd-test-52_video_1920_1080_3.mp4` and `video_1920_1080_3`

**Comment by jakubvojacek** [comment]
How could I have missed that. It works flawlessly now, thank you

**Comment by kqyang** [comment]
@rkuroiwa Good catch! We should consider adding some validations in output file names to avoid problems like this to happen again.
