### ISSUE TITLE
Multiple audio tracks in an mp4 file

### ISSUE THREAD

**Issue by Jason239** [google/shaka-packager#490]
I have some multi tracks mp4 file.
And I want to packaging it with DASH, HLS.

There are 3 kinds of audio track. 
Those are one ac-3 codec and two mp4a codecs.

But if I tried with below commands, in case of DASH, all kinds of AdaptationSet of audio tracks are marked with an ac-3 codec.
`./packager 'in=D:\contents\SAMPLE_SINTEL\Sintel_720p_multi_audio_track.mp4,stream=video,init_segment=shaka_vod/video/1/init.mp4,segment_template=shaka_vod/video/$Number$.m4s' 'in=D:\contents\SAMPLE_SINTEL\Sintel_720p_multi_audio_track.mp4,stream=audio,init_segment=shaka_vod/audio/1/init.mp4,segment_template=shaka_vod/audio/1/$Number$.m4s' 'in=D:\contents\SAMPLE_SINTEL\Sintel_720p_multi_audio_track.mp4,stream=audio,init_segment=shaka_vod/audio/2/init.mp4,segment_template=shaka_vod/audio/2/$Number$.m4s'--generate_static_mpd --mpd_output shaka_vod/stream.mpd`

When I packaging these files as above, all seem to be packaged using only one(first) audio track.

How can I package it in this situation? 
I don't want to separate tracks before packaging.

**Comment by Jason239** [comment]
https://mpdsample.s3.amazonaws.com/share/Sintel_720p_multi_audio_track.mp4

This is the file what I tested.

**Comment by rkuroiwa** [comment]
I forgot how I exactly navigate to [this](https://google.github.io/shaka-packager/html/options/stream_descriptors.html) doc, but IIUC, stream ID (number) has to be specified.
When I run `--dump_stream_info` on the file, I see
video: 0
audio (AC-3): 1
audio (mp4a): 2
audio (mp4a): 3

So the command has to be something like 
`./packager 'in=D:\contents\SAMPLE_SINTEL\Sintel_720p_multi_audio_track.mp4,stream=video,init_segment=shaka_vod/video/1/init.mp4,segment_template=shaka_vod/video/$Number$.m4s' 'in=D:\contents\SAMPLE_SINTEL\Sintel_720p_multi_audio_track.mp4,stream=1,init_segment=shaka_vod/audio/1/init.mp4,segment_template=shaka_vod/audio/1/$Number$.m4s' 'in=D:\contents\SAMPLE_SINTEL\Sintel_720p_multi_audio_track.mp4,stream=2,init_segment=shaka_vod/audio/2/init.mp4,segment_template=shaka_vod/audio/2/$Number$.m4s'--generate_static_mpd --mpd_output shaka_vod/stream.mpd`

**Comment by Jason239** [comment]
Ah, that's a clear solution, I missed it.
Thanks !
