### ISSUE TITLE
Effects of IV on CENC(as PlayReady)

### ISSUE THREAD

**Issue by Jason239** [google/shaka-packager#491]
I applied the PlayReady and Widevine DRM to DASH packaing in my system.
And I tried playback test on a web player, and it succeeded in Chrome(Widevine) but failed on the Edge(PlayReady).

So I checked the cause of the failure. And I found out that was just a matter of whether the --iv parameter was used. All conditions(key, key id, pssh etc) except the iv parameter were the same. If I remove the iv option from the command and package it, it works well.

Since my system also deals with FPS packaging, I used the iv parameters together. 
How does this iv parameter affect PlayReady? or CENC encryption?

**Comment by kqyang** [comment]
> How does this iv parameter affect PlayReady?

IV affects CENC, or more precisely how the bits are encrypted using AES. It is DRM system agnostic.  It should not affect PlayReady. If it works in Widevine, then it should work in PlayReady, unless there is a bug in Edge's CDM.

What IV are you using? If it is 16-bytes, you can try a different IV with 8 bytes (16 hex digits). It might be possible that Edge assumes the IV is 8 bytes, although both are allowed by the spec. You may also try different IVs to see if it makes a difference as not specifying IV to Shaka Packager really just means that Shaka Packager will randomly generates an IV for you.

**Comment by Jason239** [comment]
Oh yes, if I try to apply 8 bytes iv, it works fine.
And I understood it. Your answer is very helpful. 

Thanks very much.
