### ISSUE TITLE
shaka-packager is not installed.

### ISSUE THREAD

**Issue by voiddeveloper** [google/shaka-packager#494]
## System info
**Operating System**: Ubuntu 16.04 
**Shaka Packager Version**: latest

## Issue and steps to reproduce the problem

**Packager Command**:

**Extra steps to reproduce the problem?**

$ sudo apt-get update
$ sudo apt-get install build-essential curl git python
$ git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
$ export PATH="$PATH:/home/ubuntu/depot_tools" 

// => The "depot_tools" folder is in the "/ home / ubuntu" path.

$ sudo apt-get install g++
$ sudo apt-get install -y build-essential

// => I added the above two lines to run the gclient command.

$ mkdir shaka_packager && cd shaka_packager
$ gclient config https://www.github.com/google/shaka-packager.git --name=src --unmanaged
$ gclient sync
$ cd src
$ ninja -C out/Release
$ packager --version

**What is the expected result?**

I thought I could see the version information.

 **What happens instead?**

packager : command not found 

![screen shot 2018-10-23 at 5 48 21 pm](https://user-images.githubusercontent.com/17779284/47348248-02a82500-d6ec-11e8-8d1f-10914d6ead5e.png)

And I tried another way.

$ sudo apt-get update
$ sudo apt-get install build-essential curl git python
$ git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
$ export PATH="$PATH:/home/ubuntu/depot_tools" 
$ sudo apt-get install g++
$ sudo apt-get install -y build-essential
$ mkdir shaka_packager && cd shaka_packager
$ gclient config https://www.github.com/google/shaka-packager.git --name=src --unmanaged
$ gclient sync
$ cd src
$ ./packager/build/install-build-deps.sh
$ ninja -C out/Release
$ packager --version

 **What happens instead?**

Still the same reaction.

packager : command not found 

![screen shot 2018-10-23 at 5 48 21 pm](https://user-images.githubusercontent.com/17779284/47348248-02a82500-d6ec-11e8-8d1f-10914d6ead5e.png)

**Comment by rkuroiwa** [comment]
If `ninja -C out/Release` succeeded, then the packager binary is at `out/Release/packager`

**Comment by voiddeveloper** [comment]
yes.  I went to that path and typed the command "packager --version" but still got the same error.


![screen shot 2018-10-24 at 1 03 09 pm](https://user-images.githubusercontent.com/17779284/47405596-456e0980-d78d-11e8-923b-36d151bc5be0.png)


![screen shot 2018-10-24 at 1 04 35 pm](https://user-images.githubusercontent.com/17779284/47405621-63d40500-d78d-11e8-93f2-0255a8d775e3.png)

**Comment by voiddeveloper** [comment]
@hieuletrung Thank you.

**Comment by kqyang** [comment]
@voiddeveloper Looks like your problem has been solved. I am closing the issue. Feel free to reply or open another issue if you have other questions.
