### ISSUE TITLE
HLS peak bandwidth bug for very short segments.

### ISSUE THREAD

**Issue by rtpriya** [google/shaka-packager#498]
## System info
OS - macOS Seirra. 
packager version 8d11e5ea64-release

## Issue and steps to reproduce the problem
I tried to encode and package a test clip - BasketBallDrive_1080p50.y4m using shaka. 
My clis to encode and package are
./ffmpeg -i /Users/aathip/Videos/BasketballDrive_1920x1080_50.y4m -c:v libx264 -g 50 -x264-params keyint=50:scenecut=0:bitrate=1200 -f mp4 out.mp4
./packager 'in=/Users/aathip/Documents/ffmpeg/out.mp4,stream=video,segment_template=h264_1080p/$Number$.ts,playlist_name=h264_1080/main.m3u8' --hls_master_playlist_output master.m3u8 --segment_duration 2

This clip contains 501 frames. So the last segment is very small (just a single I frame for .02 sec).  

What is the expected result?
Expected peak bitrate arund 1200-1300kbps.
The peak bandwidth according to HLS spec is to be calculated as 
"   The peak segment bit rate of a Media Playlist is the largest bit rate
   of any contiguous set of segments whose total duration is between 0.5
   and 1.5 times the target duration.  The bit rate of a set is
   calculated by dividing the sum of the segment sizes by the sum of the
   segment durations."

What happens instead?
The peak bandwidth is shown as 6467.2 kb/s. This is bitrate extrapolated only for the last segment of 0.2 seconds based on  a single I frame which will bloat up the per second bitrate. 

```xml
#EXTM3U
## Generated with https://github.com/google/shaka-packager version 8d11e5ea64-release
#EXT-X-STREAM-INF:BANDWIDTH=6467200,AVERAGE-BANDWIDTH=1271496,CODECS="avc1.64002a",RESOLUTION=1920x1080
```

<Please attach the input files or email to shaka-packager-issues@google.com.>
<Please provide any additional information below.>

**Comment by kqyang** [comment]
@rtpriya Thanks for reporting the issue and pointing out the spec sentence. We will work on the fix ASAP.

**Comment by kqyang** [comment]
There is a bug in the original fix. See #581 for details.
