### ISSUE TITLE
Output directory permission

### ISSUE THREAD

**Issue by Jason239** [google/shaka-packager#499]
Even though I refer to link in [#259](https://github.com/google/shaka-packager/issues/259), the permissions of the directory created by packager are as follows.

`drwx--S--- 3 ec2-user ec2-user 4096 Oct 30 09:12 pack_test`

Is there a way to set permissions such as 'drwxr-xr-x' on the generated directories?

**Comment by rkuroiwa** [comment]
What version of the packager was used? What is the command that was run?

**Comment by Jason239** [comment]
Ah, it wasn't latest version.
Is this issue solved on latest version?

The command and version are as below.

`./packager --preserved_segments_outside_live_window 10 --time_shift_buffer_depth 60 --mpd_output output/dash/manifest.mpd in=udp://127.0.0.1:1234,stream=video,init_segment=output/dash/video/init.mp4,segment_template=output/dash/video/seg-$Number$.m4s in=udp://127.0.0.1:1234,stream=audio,init_segment=output/dash/audio/init.mp4,segment_template=output/dash/audio/seg-$Number$.m4s`

`version f49b892-release`

**Comment by Jason239** [comment]
The same issue is still reproduced in the latest version(53aa775ea4-release)

**Comment by kqyang** [comment]
@Jason239 Thanks for reporting the problem. We'll look into it.
