### ISSUE TITLE
documentation to start pssh.py 

### ISSUE THREAD

**Issue by ksuhiyp** [google/shaka-packager#500]
## System info
**Operating System**: <e.g. macOS Sierra, Ubuntu 14.04 trusty etc>
cosmic cuttlefish
**Shaka Packager Version**: <e.g. v1.6.1, commit SHA etc>
latest
## Issue and steps to reproduce the problem
documentation of pssh generator tool is advanced and not py beginner friendly

What is the expected result?
enhance the documentation to clearly walk through how to use pssh.py to generate pssh boxes right away
What happens instead?
unable to use pssh.py

**Comment by kqyang** [comment]
@ksuhiyp Thanks for reporting the concern. Running `pssh-box.py` without providing any parameters dumps the instructions on how to use the tool. Does that address your concerns? Or is there anything needs to be improved there?

**Comment by kqyang** [comment]
The document is updated in https://github.com/google/shaka-packager/commit/72c4797a593e28cf672dd7019a9d3109901a7a83. See the document at https://github.com/google/shaka-packager/tree/master/packager/tools/pssh.
