### ISSUE TITLE
The packager command does not work.

### ISSUE THREAD

**Issue by voiddeveloper** [google/shaka-packager#502]
## System info
**Operating System**:  Ubuntu 16.04 
**Shaka Packager Version**: packager version 53aa775-release

## Issue and steps to reproduce the problem

**Packager Command**:

Extra steps to reproduce the problem?
(1) Packager installed.
(2) cd /shaka_packager/src/out/Release
(3) ln -s /home/ubuntu/shaka_packager/src/out/Release/packager
(4) ./packager --version
(5) cd ../
(6) ./packager --version

What is the expected result?

I expected that the packager command would work on any path.

What happens instead?

-bash: ./packager: No such file or directory

![screen shot 2018-11-08 at 2](https://user-images.githubusercontent.com/17779284/48180054-43976f00-e365-11e8-92e7-c9c6d044b33c.png)

**Comment by jakubvojacek** [comment]
Hello,

believe this is up to you, to move the binary or create a symlink into `/usr/bin` for example.

**Comment by kqyang** [comment]
@voiddeveloper Please follow @jakubvojacek's suggestion. You can then use "packager" (not "./packager") in any directory.
