### ISSUE TITLE
Install shaka-pachakger

### ISSUE THREAD

**Issue by chavoosh** [google/shaka-packager#504]
**How to install Shaka Packager on Ubuntu?**

I successfully *built* Shaka Player and it perfectly runs by the following command:
`/home/.../out/Release/packager`

However, I need to run packager like a native application (i.e. `packager <options>`), instead of specifying the full path to it every time. How can I do this?

**Comment by jakubvojacek** [comment]
@chavoosh please follow instructions from https://github.com/google/shaka-packager/issues/502#issuecomment-436885741

**Comment by chavoosh** [comment]
Thanks for the prompt reply! The problem is solved.
