### ISSUE TITLE
-x264-params instead of -x264opts in the docs

### ISSUE THREAD

**Issue by benbro** [google/shaka-packager#507]
[Docs](https://github.com/google/shaka-packager/blob/master/docs/source/tutorials/encoding.rst) use -x264opts which is [deprecated](https://trac.ffmpeg.org/wiki/Encode/H.264). We should use -x264-params.

> Warning: Do not use the option x264opts, as it will eventually be removed. Use x264-params instead.

**Comment by kqyang** [comment]
Thanks for catching that! Will fix!
