### ISSUE TITLE
Simulate Live DASH + HLS

### ISSUE THREAD

**Issue by BobCu** [google/shaka-packager#509]
I need multiple (~25) multi-resolution/bandwidth (240p/480p/720p/1080i) simulated "live" HLS and DASH sources to support downstream systems.  In particular, I need to debug, test and tune caching HTTP/HTTPS reverse proxy servers for these streams.

I could take some webcams and generate "real" live content, but am hoping to avoid the need to run the transcoders needed for multiple resolutions.  Something that "acts" live is all I need: Looping over 10-minute static content would work fine.

I was going to try to write a Python script to take static VOD content and generate live DASH manifests and HLS playlists that loop over the VOD segments, but I'm wondering if Shaka could do this better, feeding a simple NGINX server.

I found no mentions of (or examples for) such a capability in the Shaka documentation, but I doubt I understood all the details and could easily have missed it.

Is this something Shaka can do?

**Comment by JuliusThms** [comment]
You can feed to nginx using #149, the release should be available with v2.4.; but you can compile it by you own; it's stable: https://github.com/3QSDN/shaka-packager/tree/http-upload

**Comment by BobCu** [comment]
I'm not worried about the HTTP output itself, but the looping over the static video content to feed "live" manifest/playlist generation.  Ideally, the live simulation would also generate symlinks to the static content that increment like "real" live segments, to ensure the caching reverse-proxy doesn't get lazy.

**Comment by JuliusThms** [comment]
I think it's the best to generate an mpegts output on ffmpeg and pipe it to shaka; have a look here: https://google.github.io/shaka-packager/html/tutorials/live.html.

**Comment by BobCu** [comment]
I'm looking at 100 parallel video streams (25 different sources in 4 resolutions each).  I don't mind a one-time hit to generate the static segments in advance, but would rather avoid having 75 transcoding sessions running continuously!

Ideally, the "live" segments would be created as symlinks to the static segments, where the symlink contains the ever-increasing segment number. My main problem is generating the live manifests/playlists *without* actually generating any "live" video.  Super lightweight simulation.

**Comment by JuliusThms** [comment]
Understand; maybe someone in this community can help.

**Comment by BobCu** [comment]
Actually, if I can get Shaka to generate only the manifests/playlists, I can write a simple script to parse them and generate the needed symlinks.  Hmmm, perhaps generate a bunch of "black" video streams to feed Shaka?

**Comment by BobCu** [comment]
The timestamp of a symlink can be handled by 'touch -h', forcing it to match that of the generated dummy segment.  When Shaka deletes out-of-window segments, it will delete the symlink, not the underlying static segment.

The underlying static segments could be generated by a single multi-resolution ffmpeg pass to ensure the results are suitable for adaptive streaming (same I-frame placement).

It would be best to avoid the need to do dynamic symlinking: Is it possible to present the pre-transcoded multi-resolution static segments to Shaka both synchronously and in a loop?  The cost of a copy operation is negligible, as I can do it to/from a ramdisk/tempfs mount.

**Comment by kqyang** [comment]
> The timestamp of a symlink can be handled by 'touch -h', forcing it to match that of the generated dummy segment. When Shaka deletes out-of-window segments, it will delete the symlink, not the underlying static segment.

I was talking about the presentation timestamps in the media.

**Comment by BobCu** [comment]
Doh!  Of course you're right.  So, at the very least, I do need to reprocess the looped video to generate fresh PTS.

Do you know if that is something ffmpeg can handle without need to simultaneously do transcoding for the other resolutions?

**Comment by kqyang** [comment]
> Do you know if that is something ffmpeg can handle without need to simultaneously do transcoding for the other resolutions?

I don't know if you can do it in ffmpeg, but you can use either tsplay or vlc. See https://github.com/google/shaka-packager/issues/509#issuecomment-440782898.

**Comment by BobCu** [comment]
Thanks so much for your patience!  Let's see if I have the gist of the workflow I need to create:

1. Get my reference 1080p videos (~10 minutes each).
2. Use ffmpeg to transcode each into the desired output resolutions for adaptive streaming, with the output for each gathered into a single TS with separate PIDs for each resolution. (Which I don't yet know how to do, but looks doable.) 
3. Use tsplay to loop the TS. (Per your example)
4. Use Shaka to generate the DASH + HLS,

Did I get that right?  Time for me to go nag the ffmpeg folks?

**Comment by kqyang** [comment]
Yes, that is correct! Let us know how it goes :)

**Comment by BobCu** [comment]
OK, before I go, I need to nail down the Shaka use:  The TS I hope to create will have multiple video PIDs, and perhaps one or more cloned audio PIDS (depending on what ffmpeg does).

How do I tell Shaka which video PID contains which resolution?

Or does tsplay somehow send the different Video+Audio PIDs to separate multicast ports?

**Comment by BobCu** [comment]
I was hoping to close this issue with a working recipe, but that's at least a few days away.  I doubt I'll need more support here, so I can close this now if there's a screaming need.

**Comment by kqyang** [comment]
Sure, let's keep it open for now.

**Comment by BobCu** [comment]
I searched for an example of simultaneous live DASH + HLS output, but failed to find one.  I did find issue #442 for static output, but am having trouble making it work for live.

Is an example of live DASH + HLS available?  If so, could it be added to the live tutorial (https://google.github.io/shaka-packager/html/tutorials/live.html)?

**Comment by kqyang** [comment]
You can add `--mpd_output h264.mpd` to the HLS example in https://google.github.io/shaka-packager/html/tutorials/live.html. It will then generate both DASH and HLS.

And sure, we can add a DASH+HLS example there if it helps.

**Comment by BobCu** [comment]
Next: I find I can't get --dump_stream_info to work wits a multi-program TS streaming on a socket (udp://127.0.0.1:33221).  There are 3 programs in the TS, each with its own audio & video PIDs (redundant, I know), having identical content, differing only in resolution.  The content is Big Buck Bunny, looped via tsplay to simulate live.

**Comment by kqyang** [comment]
@BobCu We do not support multi-program TS right now, see #82. Can you put all streams in the same program instead?

**Comment by BobCu** [comment]
I'm not sure how to get ffmpeg to put 3 video streams into a single program...

**Comment by kqyang** [comment]
@BobCu Assume that you have two files 1024.ts and 720.ts, both containing an audio stream and a video stream. You can merge them into one ts file with this:

```bash
$ ffmpeg -i 1024.ts -i 720.ts -c:a copy -c:v copy -map 0:0 -map 1:0 -map 0:1 -map 1:1 out.ts
```

**Comment by BobCu** [comment]
Here's my current ffmpeg command (that may not quite yet be perfect):

`    $ ffmpeg -i "big_buck_bunny_1080p_h264.mov" -threads 16 \
        -map 0:a -map 0:v -map 0:v -map 0:v \
        -c:a aac -ac 2 -b:a 128k \
        -force_key_frames "expr:eq(mod(n,$GOPSIZE),0)" -x264opts rc-lookahead=$GOPSIZE:keyint=$DOUBLE_GOPSIZE:min-keyint=$GOPSIZE \
        -force_key_frames 0:0:10 -pix_fmt yuv420p -preset veryslow -tune film -vsync cfr -x264-params "nal-hrd=cbr" \
        -s:v:0 1280x720 -c:v:0 libx264 -b:v:0 5000k -minrate 2000k -maxrate 2000k -bufsize 4000k \
        -s:v:1  854x480 -c:v:1 libx264 -b:v:1 1500k -minrate 1000k -maxrate 1000k -bufsize 2000k \
        -s:v:2  640x360 -c:v:2 libx264 -b:v:2  500k -minrate  500k -maxrate  500k -bufsize 1000k \
        -program program_num=1:title=multi_p30:st=0:st=1:st=2:st=3 \
        -f mpegts "big_buck_bunny_1080p_h264.mov.ts" -y`

**Comment by BobCu** [comment]
It turns out that stream specifiers are needed ***everywhere*** to get the desired result:

'$ ffmpeg -i "$INFILE" -threads 16 \'
'        -map 0:a -map 0:v -map 0:v -map 0:v \'
'        -c:a aac -ac 2 -b:a 128k \'
'        -force_key_frames "expr:eq(mod(n,300),0)" -max_interleave_delta 0 \'
'        -x264opts rc-lookahead=300:keyint=600:min-keyint=300 \'
'        -pix_fmt yuv420p -preset veryslow -tune film -vsync cfr -x264-params "nal-hrd=cbr" \'
'        -s:v:0 1280x720 -c:v:0 libx264 -b:v:0 5000k -minrate:v:0 2000k -maxrate:v:0 2000k -bufsize:v:0 4000k \'
'        -s:v:1  854x480 -c:v:1 libx264 -b:v:1 1500k -minrate:v:1 1000k -maxrate:v:1 1000k -bufsize:v:1 2000k \'
'        -s:v:2  640x360 -c:v:2 libx264 -b:v:2  500k -minrate:v:2  500k -maxrate:v:2  500k -bufsize:v:2 1000k \'
'        -program program_num=1:title=multi_p30:st=0:st=1:st=2:st=3 \'
'        -f mpegts "${INFILE}_720p_480p_360p.ts" -y'

**Comment by kqyang** [comment]
Cool. Thanks for the update!

**Comment by BobCu** [comment]
The following VLC command will loop the above TS with monotonically increasing PCR/DTS/PTS:

    cvlc ${INPUT_TS} --sout udp:${OUT_ADDR}:${OUT_PORT} --repeat --loop --sout-all --sout-keep -quiet

Packager command to follow.

**Comment by BobCu** [comment]
From what I'm seeing, `--preserved_segments_outside_live_window 2` does nothing: I see an ever-increasing number of files accumulate.  Is this feature actually implemented?  Should I open a separate issue for this?

**Comment by BobCu** [comment]
For live use, removing old data is critical.  From what I'm seeing, `--preserved_segments_outside_live_window 2` does nothing: I see an ever-increasing number of files accumulate. Is this feature actually implemented? Should I open a separate issue for this?

**Comment by BobCu** [comment]
OK, it seems I missed some related options, or at least failed to understand them.  If I want 10-second segments, what are the best values for each of the following?  My desire is only to keep the connected clients happy with minimal storage on the server.
`--time_shift_buffer_depth`
`--preserved_segments_outside_live_window`
`--segment_duration`
`--fragment_duration`

**Comment by kqyang** [comment]
@BobCu Great! Thanks for sharing the commands!

> My desire is only to keep the connected clients happy with minimal storage on the server.
--time_shift_buffer_depth
--preserved_segments_outside_live_window
--segment_duration
--fragment_duration

We recommend having at least a few minutes of time shift buffer, even if you are not planning to allow seeking in the client. This ensure that the client is still able to continue playing when it encountered an unexpected network condition and then recovers.

**Comment by BobCu** [comment]
I'll try  `--time_shift_buffer_depth 200`.   My concern was that the buffer depth would add delay to the live stream, something very noticeable for things like live sports, when OTT TV lags the radio by a minute or more, in which case a hiccup may be preferable to delay.  But that would not be the case for almost every other kind of content, so the higher value probably makes better sense overall.

Right now I'm testing 32 input streams that each become a pair of 3-resolution DASH and HLS outputs, for 192 outputs total.  For all these outputs the looper+packager presently uses about 500 MB or ramdisk/tmpfs, and about 1/3 of my hex-core hyperthreaded i7 laptop CPU.  Not bad!

Thanks!

**Comment by BobCu** [comment]
Side note about testing using Chrome:

To avoid the need for player code, I installed the [Native MPEG-Dash + HLS Playback](https://chrome.google.com/webstore/detail/native-mpeg-dash-%20-hls-pl/cjfbmleiaobegagekpmlhmaadepdeedn?hl=en) Chrome plugin.

I tested DASH playback by clicking the mpd links on [this page](http://dash-mse-test.appspot.com/media.html).

I throttle bandwidth using [this technique](https://www.addictivetips.com/web/limit-download-speed-in-chrome/).

**Comment by BobCu** [comment]
It also seems that `--preserved_segments_outside_live_window` doesn't do its job very well.  NGINX can hold an older m4s file open when Shaka packager is creating a new one, and the packager will never try to clean it up.

Workaround:  At the end of my startup script, I had to add this code:

    while true; do
      sleep 10
      echo "Press ^C to Exit."
      find "${WWW_ROOT}/www" -mmin +1 -name "*.m4s" -delete >/dev/null 2>&1
    done

**Comment by BobCu** [comment]
Didn't need to be reopened.

**Comment by kqyang** [comment]
> Edit2: A possible remediation would be for the packager to keep an explicit list of its segments that are in the window and preserved outside of it, then delete all of its segments not on that list.

That is roughly what we are doing for `preserved_segments_outside_live_window`.

> It also seems that --preserved_segments_outside_live_window doesn't do its job very well

Can you clarify? Is it not deleting the segments at all or not doing the deletion per your expectation?

You can enable the logging, by either set `--v=2` or `--vmodule="*representation*=2"`. It will dump the deletion operations to the console when the logging is enabled.

**Comment by BobCu** [comment]
Yes!  Without the webserver running, the files are deleted as expected.  Starting the webserver and watching a video prevents deletion, which is visible as disk use rapidly rising instead of being stable.

I'm using a small ramdisk for the packager output / webserver input, so too many extra files causes pain.

**Comment by kqyang** [comment]
I see, so seems like the files are still opened by the web server. I am sure that the web server won't hold the files forever and there are probably a setting somewhere in the server you can adjust.

That is one reason why we have the `preserved_segments_outside_live_window` flag in packager so you can adjust it to only delete the segments that are not held by the web server.

**Comment by BobCu** [comment]
The files are never held for more than ~30-40 seconds, max, which seems to be the time needed for the player to use up its buffer, give up, then try a lower speed.

It seems the packager makes one deletion attempt, and regardless of its success or failure, never tries again.

**Comment by kqyang** [comment]
> It seems the packager makes one deletion attempt, and regardless of its success or failure, never tries again.

Correct, that is what we are doing now, which can be improved.

**Comment by kqyang** [comment]
@BobCu I noticed that the segment duration is set to 10 seconds, which is a bit long and it does not align with the GOPs (12.5 seconds?) either.

Some general recommendations for doing live streaming:

- Use short segment duration, e.g. two seconds.
- The segment duration should align with GOPs, for example, the GOP can be 2 seconds or 1 second (48/24 frames for frame rate of 24).

It will help on the web server holding segment issue mentioned above as well.

**Comment by BobCu** [comment]
I'll look into this!  I thought I had told ffmpeg to do 10 second GOPs with scene-changes as needed.

The 10 second segment length comes from the system I'm simulating: I can't change it, but I will make the suggestion.

**Comment by colleenkhenry** [comment]
I can write this for you... and will try to find some time to do so :)

**Comment by BobCu** [comment]
Sigh.  I thought my input was 30 fps, so there was no need to change the fps.  It was actually 24 fps.  That's what I get for believing the filename.
