### ISSUE TITLE
Error while packaging stream using self hosted key_server_url

### ISSUE THREAD

**Issue by raghuborkar** [google/shaka-packager#512]
## System info
**Operating System**: CentOS 7
**Shaka Packager Version**: packager version 631bbdc-release

## Issue and steps to reproduce the problem
We are implementing the self hosted key server.
Am seeing following error message while creating the stream using self hosted key_server_url.

[1122/121906:ERROR:mpd_utils.cc(212)] UUID size is expected to be 16 but is 32 and the data in hex is 3330333033303330333033303330333033303330333033303330333933393339
[1122/121906:ERROR:mpd_utils.cc(318)] Failed to convert default key ID into UUID format.

After this error stream is created successfully, but during playback, 10 sec video is played fine and then stopped.

**Packager Command**:
./packager input=480p.mp4,stream=video,output=Test.mp4 \
> --enable_widevine_encryption \
> --key_server_url "valid server address" \
> --content_id "32323230303030303030303030323232" \
> --signer "test" \
> --aes_signing_key "validkey" \
> --aes_signing_iv "validIV" \
> --mpd_output Test.mpd

We are sending response based on Widevine_DRM_Encryption_API appendix.
KeyID, Key and PSSH generated and sent in Hex format. in this case Key ID sent in response is 30303030303030303030303030393939.

we have changed the Key ID to 16 byte ASCII ie 0000000000000999, we dont see error but while playback video is scrambled after 10 sec.
Above issue is not seen when we use --enable_raw_key_encryption where we send Key ID in Hex format, 

What is the expected result?
Stream creation must be successful without any error and playback should work fine on Chrome browser.

What happens instead?
Playback is stopped after 10 sec. 

Please let us know what is the right format need to be sent. 

Regards

**Comment by kqyang** [comment]
@raghuborkar It should not be hex encoded. It is base64 encoded raw bytes.

Can you share the command you are using when using `--enable_raw_key_encryption` and the JSON response from Widevine DRM encryption API when using `--enable_widevine_encryption`? You can include "--v=1" in packager command, which will dump the response.

**Comment by raghuborkar** [comment]
Hi Kongqun, Thank you for responding.

I have changed the response of key_id into ASCII 16 byte data and encoded with base64 format in response.
Now we dont see error. but we are not able to playback the content after 10. I have taken SD video only for simplifying test. 
We observe that stream is not able to decrypt and seen scrambled and it is buffering. There is no browser error or packaging error.

Whereas, when we encrypt stream with --enable_raw_key_encryption and do playback it works fine in same environment.

I am sending logs and .mpd files for your reference. Please see attached.
Please let us know if we have to change the response format.

[ToGithub.zip](https://github.com/google/shaka-packager/files/2618713/ToGithub.zip)

Regards,
Raghu

**Comment by kqyang** [comment]
@raghuborkar There are two more problems:

- Not only key_id, but key and PSSH are base64 encoded raw bytes too.
- tracks.pssh.data should contain PSSH data only instead of the whole PSSH box. You can use tracks.pssh.boxes instead if you want to put PSSH box in the JSON response.

**Comment by raghuborkar** [comment]
Hi Kongqun,
I have updated the database for Key, Key id and PSSH in base64 of RAW data format and added pssh data and boxes part in JSON.

Regarding 2nd point,
looks like "data" part cant be NULL otherwise there will be pssh data parsing error thrown by packager. 
I couln't get right reference to generate pssh data alone, I tried to generate pssh data separately using content-id.
something like:
	python /opt/widevine/shaka_packager/src/packager/tools/pssh/pssh-box.py \
	--content-id 36363630303030303030303030363636 \
	--widevine-system-id --base64
	AAAAMnBzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAABIiEDY2NjAwMDAwMDAwMDA2NjY=

Use case is:
Contnet id: 6660000000000666
Key ID: 	0000000000000101
Key:		12345678901234567890123456789012

Result:
We still see that stream is not able to decrypt and seen scrambled and it is buffering. There is no browser error or packaging error.

I have attached response log FYR, please have a look.
[log2.txt](https://github.com/google/shaka-packager/files/2624724/log2.txt)

Please help us know the right way,
1. How I can generate pssh data and pssh boxes separately for each tracks.
2. Is there any tool for stream analysis?

Regards,
-Raghu

**Comment by kqyang** [comment]
The keys do not match with what you use with `--enable_raw_key_encryption`. Can you use the same key, key_id and pssh?

> Is there any tool for stream analysis?

If you want to verify if the correct key is used, you don't really any special tool. The response logged in packager is JSON, i.e. base64 encoded. You can use a base64 decoder, e.g. https://www.base64decode.org/ and https://cryptii.com/pipes/base64-to-hex to decode the JSON message and encode key / key_id and pssh to hex, then compare them with what you use with `--enable_raw_key_encryption`.

> looks like "data" part cant be NULL otherwise there will be pssh data parsing error thrown by packager.

What is the error you are seeing? I just verified that it worked for me if there are `boxes` but no `data`.

> How I can generate pssh data and pssh boxes separately for each tracks.

As shown above, you don't need to generate pssh data. Having pssh boxes will be sufficient, for which you can use the pssh-box.py tool as what you have done.

**Comment by raghuborkar** [comment]
Hi,
I have updated to new packager version 2.2.1 and here i don't see packaging error related to PSSH data.
As you suggested I have updated with Key, Key ID, PSSH in Base64 encoded Raw bytes and it worked fine. 
Thanks a lot!

**Comment by kqyang** [comment]
Glad to help!
