### ISSUE TITLE
Automatic updating

### ISSUE THREAD

**Issue by Nethe** [google/shaka-packager#513]
Hi guys, I have a question about automatic deployment. 
We are using gitlab-ci for a lot of tasks, but I'm still thinking about shaka-packager.

As per Git, the basic script to compare local and remote repo looks something like this:

```
	cd $DIR && git fetch
	HEADHASH=$(git rev-parse HEAD >> $DEPLOY_LOG 2>&1)
	UPSTREAMHASH=$(git rev-parse master@{upstream} >> $DEPLOY_LOG 2>&1)
	if [ "$HEADHASH" != "$UPSTREAMHASH" ]
	then
 		echo "Need update of $DEPLOY_TYPE."
   		UPDATE=1
	else
 		echo "Update not needed."
  		UPDATE=0
	fi
```
I tried to read the documentation for depot_tools, but I cannot find commands like Git.
I would like to ask you if there is some similar way of how to compare local and remote repository?

Thank you!

**Comment by kqyang** [comment]
@Nethe We are using `depot_tools` for the dependency management. The code is still managed by `git`. You can just use the same git script you have to compare the local and remote repo for Shaka Packager. 

Let us know if you are seeing any problem.

**Comment by Nethe** [comment]
Hi @kqyang , thank you for the response. 
The issue is that when I clone the repository, there is no possibility to compile the packager using ```gclient config```, ```gclient sync``` and ```ninja``` command. Or is there any other way of how to compile/build the packager when I do ```git clone``` and after the ```git pull```?

Thank you.

**Comment by kqyang** [comment]
@Nethe Yes, you can compile / build the packager after `git clone` / `git pull`. You'll still need to run `gclient sync` to update the dependencies, but you can configure it not to update the main code repository with `--unmanaged` flag. `gclient` expects the code to reside in directory `src`, so you'll need to clone the code to `src`. Here is an example script:

```bash
$ mkdir packager
$ cd packager
$ git clone https://github.com/google/shaka-packager.git src
$ gclient config https://github.com/google/shaka-packager.git --name=src --unmanaged
$ gclient sync
...
```

And remember to run `gclient sync` again after `git pull` to update the dependencies.

**Comment by Nethe** [comment]
Ok, perfect, now I understand, thanks a lot!

**Comment by kqyang** [comment]
Glad to help!
