### ISSUE TITLE
Only last few chunks played by shaka player for shaka packager transcoded dash segments

### ISSUE THREAD

**Issue by parth2094** [google/shaka-packager#514]
## System info
**Operating System**: Ubuntu 14.04
**Shaka Packager Version**: 53aa775-release

## Issue and steps to reproduce the problem

**Packager Command**:
packager 'in=/media/default.mp4,stream=audio,init_segment=/media/LiveDefaultExp/init.mp4,segment_template=/media/LiveDefaultExp/$Number$.m4s' \
  --mpd_output /media/LiveDefaultExp/master.mpd

Extra steps to reproduce the problem?
(1) Followed the steps here : https://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html
to get shaka player up and running.
(2) Updated the field "availabilityStartTime" and "publishTime" in the shaka packager generated mpd file to a time stamp lets say 5 mins after the time of editing.
(3) In the file myapp.js as given in the next page of the above url, I set the manifestUri to the mpd generated by running the shaka packager command given above.
(4) Hosted the the shaka player on node js.

What is the expected result?
The shaka player should start streaming all the chunks starting from the first one at the time given in publishTime.

What happens instead?
At any given time stamp (tried at various time stamps) the player by default plays the last 4-5 chunks, i.e. if there are a total of 39 chunks, the network tab shows the browser fetching 36, 37, 38, 39th chunk every time

<Please attach the input files or email to shaka-packager-issues@google.com.>
<Please provide any additional information below.>

**Comment by kqyang** [comment]
@parth2094 Not sure what you are trying to achieve. If you want to always play from the beginning, you can add `--generate_static_mpd` to the command line, i.e.

```bash
packager \ 
'in=/media/default.mp4,stream=audio,init_segment=/media/LiveDefaultExp/init.mp4,segment_template=/media/LiveDefaultExp/$Number$.m4s'  \
--mpd_output /media/LiveDefaultExp/master.mpd \
--generate_static_mpd
```

There is no need to edit `availabilityStartTime` and `publishTime` in this case.

Please try and let us know if it is what you want.

**Comment by parth2094** [comment]
Not sure if this makes a difference but the mp4 file given as an input to shaka packager has been generated originally from an mp3 file by using two ffmpeg commands.
mp3 ->wav
ffmpeg -i <mp3_file> -ar 44100 <wav_file>
wav -> mp4
ffmpeg -loglevel error -y -i <wav_file> -threads 0 -map_chapters -1 -f mp4 -movflags faststart -map 0:0 -acodec libfdk_aac -profile:a aac_he -ac 2 -ar 44100 -b:a 48k -sn -vn <mp4_file>

**Comment by kqyang** [comment]
> Is it possible because time_of_play > availabilityStartTime + stream_duration ?

Yes. It happens if you waited too long after the content is generated or if the clock is out of sync between the client and the server.

> When you say it works as expected for you, does the stream start from the beginning or from somewhere in the middle based on the time of play and the availabilityStartTime/publishTime in the mpd?

Yes, it depends on when I start playing. It plays almost from the beginning when I start playing immediately after the content is generated; it plays at around ~5 minutes from the beginning if I waited for 5 minutes. If you have a very short content (for your case of ~3m) and if you waited for more than 5 minutes, you would observe what is described in https://github.com/google/shaka-packager/issues/514#issuecomment-442732321.

I'd strongly recommend trying with a longer content, preferably one hour or longer.

If you have more questions, you can ask our friends in Shaka Player Team: https://github.com/google/shaka-player/issues. They can help you locate where the live edge is.

**Comment by kqyang** [comment]
Close this issue. Feel free to reply if you have more questions.

**Comment by parth2094** [comment]
Hi Kqyang, I have a sample 10 hr long mp4 and if I run the command:
packager 'in=/media/test/data/inputAudio.mp4,stream=audio,init_segment=/media/LiveLongFileDash/init.m4a,segment_template=/media/LiveLongFileDash/$Number$.m4a' --segment_duration 10 --mpd_output /media/LiveLongFileDash/master.mpd

to generate live mpd.
As mentioned in #503 , I am unable to capture the whole of 10 hr long data. How can I generate dash output for whole of 10 hr using shakapackager?

**Comment by parth2094** [comment]
@kqyang , I tried the experiment with a 26 mins file. Played it 10 mins after it was generated and still shaka player picked only the last few chunks. Same happened with Dash player so seems like it isnt a player issue but has got to do something with the mpd or the chunks generated.
The fact that for 26 min long file it didn't work and even initially when I had changed the publish time of a smaller file it didn't work indicates that I might be missing something more than just the time of file generation and playing? Can you please help with this? I have attached the mpd in one of the earlier comments.

**Comment by kqyang** [comment]
> As mentioned in #503 , I am unable to capture the whole of 10 hr long data. How can I generate dash output for whole of 10 hr using shakapackager?

The default time shift buffer depth (`--time_shift_buffer_depth`) is set to 30 minutes. You can increase the value if needed. For example, you can set it to 10 hours, i.e. `--time_shift_buffer_depth=36000`.

**Comment by parth2094** [comment]
@kqyang The problem still persists :( I have eliminated the "waiting too long" issue by playing a longer media file so that it doesnt end before I try to stream it.
Another possibility is the the clock out of sync between client and server. Until now I was transcoding on cloud desktop which was in UTC and trying to stream on IST machine. I was speculating this could be an issue. So I tried to stream on a UTC timed client and even then the issue persisted.

You mentioned when you generated a dynamic mpd with dash chunks, shaka player was able to play the rightly calculated chunks. If there is no issue with the shaka packager command that I used, is it something to do with the input? It cannot be a player issue as shaka player and dash player both show the behaviour. I have mentioned how I transcoded mp3 -> wav -> m4 before giving to shaka packager.

Also did you find anything fishy with the mpd that i had attached earlier?

**Comment by kqyang** [comment]
> If there is no issue with the shaka packager command that I used, is it something to do with the input? 

That is possible. Can you share the source file and the command line you used? I'll be happy to take a look.

**Comment by parth2094** [comment]
Sure,
original mp3 file: https://drive.google.com/open?id=1jurEZUmv-bsXewR1XjJ8cg_t8w7aUMD1
STEP 1
mp3 ->wav
ffmpeg -i <mp3_file> -ar 44100 <wav_file>
STEP 2
wav -> mp4
ffmpeg -loglevel error -y -i <wav_file> -threads 0 -map_chapters -1 -f mp4 -movflags faststart -map 0:0 -acodec libfdk_aac -profile:a aac_he -ac 2 -ar 44100 -b:a 48k -sn -vn <mp4_file>
STEP 3
mp4 -> dash
packager 'in=/media/test/data/inputAudio.mp4,stream=audio,init_segment=/media/tenHourLiveData/init.m4a,segment_template=/media/tenHourLiveData/$Number$.m4a' --segment_duration 10 time_shift_buffer_depth=36000 --mpd_output /media/tenHourLiveData/master.mpd

Streamed the dash files on shaka/dash player

**Comment by kqyang** [comment]
@parth2094 Can you share the result mp4 generated by ffmpeg? This can help our re-pro.

**Comment by parth2094** [comment]
Here is the mp4 file generated by ffmpeg : https://drive.google.com/open?id=1tTe95gJqkN0sTvdPGe7IaCrzQgcD2UpC

**Comment by kqyang** [comment]
@parth2094 It works for me actually. Here is playback URL with the generated content: https://shaka-player-demo.appspot.com/demo/#asset=https://storage.googleapis.com/wvtemp/kqyang/live_514/master.mpd;lang=en-US;build=uncompiled. Note that it will only be play-able for ~10 hours from now as the stream is  10 hours long. 

> Also did you find anything fishy with the mpd that i had attached earlier?

If you are still seeing problems, can you re-package with your new long content (10 hours) and share the output with me? Please also describe the problems again in case if it is different to what you observed earlier.

**Comment by parth2094** [comment]
The shaka packager generated dash files
https://drive.google.com/open?id=1h8hpazrUNANvJo0ozE8aLSHAK7IT5zMK

**Comment by kqyang** [comment]
@parth2094 Your packaged content works perfectly for me: https://shaka-player-demo.appspot.com/demo/#asset=https://storage.googleapis.com/wvtemp/kqyang/514_user/master.mpd;lang=en-US;build=uncompiled. (It is playing at ~8 hours from the start right now)

How and where do you host your content? Please look into your web server setup. 

How do you test your playback? Have you tried Shaka Demo player available at https://shaka-player-demo.appspot.com/demo/?

**Comment by kqyang** [comment]
Closing this issue as there are no problems with the packaged content. 

@parth2094 If you are not satisfied with the answer or if you have more questions, you can reopen the issue with @shaka-bot reopen.
