### ISSUE TITLE
SRT, TTML and WebVTT for live

### ISSUE THREAD

**Issue by sammirata** [google/shaka-packager#520]
From what I have been able to gather on the documentation (needs more), ttml and srt are only supported as text output and webvtt is supported as text output and embedded mp4. Is this correct?
Does this mean that for a dash-live stream I can only use webvtt right now?
Is the same true for HLS/fmp4 or does it support text for live?

**Comment by kqyang** [comment]
@sammirata Yes, WebVTT is the only option right now for live stream, for both DASH and HLS. It can be outputted to text or embedded in mp4. 

We are looking to support TTML some time in 2019. Will that satisfy your need or is there any else in your wish list?

**Comment by sammirata** [comment]
Yes it does, thank you. Please close this issue.
