### ISSUE TITLE
Live DASH mpd not playable

### ISSUE THREAD

**Issue by BobCu** [google/shaka-packager#526]
## System info
**Operating System**: <e.g. macOS Sierra, Ubuntu 14.04 trusty etc>

- Ubuntu 18.04 under Win10 WSL

**Shaka Packager Version**: <e.g. v1.6.1, commit SHA etc>

- 061785285e-release

## Issue and steps to reproduce the problem

- Start VLC looping spooler on 127.0.0.1:out_port (with multi-resolution TS input generated by ffmpeg)
- Start packager taking input from 127.0.0.1
- Start NGINX web server on OUTPUT_IP_ADDR
- View local HLS url in browser: WORKS PERFECTLY (media segments OK)
- View remote DASH url in browser: WORKS PERFECTLY (player OK)
- View local DASH url in browser: Loads MPD, FAILS to fetch media

**Packager Command**:

    packager \
        "in=udp://127.0.0.1:${out_port},stream_selector=0,init_segment=audio_init.mp4,segment_template=audio_\$Number\$.m4s,playlist_name=audio.m3u8,hls_group_id=audio,hls_name=ENGLISH" \
        "in=udp://127.0.0.1:${out_port},stream_selector=1,init_segment=720p30_init.mp4,segment_template=720p30_\$Number\$.m4s,playlist_name=720p30.m3u8" \
        "in=udp://127.0.0.1:${out_port},stream_selector=2,init_segment=480p30_init.mp4,segment_template=480p30_\$Number\$.m4s,playlist_name=480p30.m3u8" \
        "in=udp://127.0.0.1:${out_port},stream_selector=3,init_segment=360p30_init.mp4,segment_template=360p30_\$Number\$.m4s,playlist_name=360p30.m3u8" \
        --hls_master_playlist_output master.m3u8  --hls_playlist_type LIVE --hls_base_url "https://${OUTPUT_IP_ADDR}/streaming${numBlade}/service${numInput}/" \
        --mpd_output manifest.mpd --default_language ENGLISH  --base_urls "https://${OUTPUT_IP_ADDR}/streaming${numBlade}/service${numInput}/" \
        --min_buffer_time 10 --minimum_update_period 10 --segment_duration 10 --fragment_duration 10 \
        --allow_approximate_segment_timeline --time_shift_buffer_depth 30 --preserved_segments_outside_live_window 1 \
        &

Extra steps to reproduce the problem?

- None.

What is the expected result?

- DASH video playing as well as HLS generated by same packager.

What happens instead?

- Player "waiting" spinner.........

<Please attach the input files or email to shaka-packager-issues@google.com.>

- manifest.mpd (attached)

[manifest.zip](https://github.com/google/shaka-packager/files/2650333/manifest.zip)

<Please provide any additional information below.>

- See overview: https://github.com/google/shaka-packager/issues/509

**Comment by kqyang** [comment]
@BobCu Thanks for the bug report. Need a few clarifications:

> View remote DASH url in browser: WORKS PERFECTLY (player OK)

What do you mean by `remote DASH url`? Another DASH url not generated by Shaka Packager?

> View local DASH url in browser: Loads MPD, FAILS to fetch media

What do you mean by `local DASH url`?

Do you have a live manifest url I can use and test on my machine?

**Comment by BobCu** [comment]
> @BobCu Thanks for the bug report. Need a few clarifications:
> 
> > View remote DASH url in browser: WORKS PERFECTLY (player OK)
> 
> What do you mean by `remote DASH url`? Another DASH url not generated by Shaka Packager?

Right, such as one of the test URLs mentioned in #509.  These are also great to test with: https://github.com/Dash-Industry-Forum/dash-live-source-simulator/wiki/Test-URLs

They are just to validate my player infrastructure.  To keep things simple, I installed this Chrome plugin: Native [MPEG-Dash + HLS Playback](https://chrome.google.com/webstore/detail/native-mpeg-dash-%20-hls-pl/cjfbmleiaobegagekpmlhmaadepdeedn?hl=en)

> > View local DASH url in browser: Loads MPD, FAILS to fetch media
> 
> What do you mean by `local DASH url`?

Generated by the packager, hosted by the server.  Like the HSL, which works fine.

> Do you have a live manifest url I can use and test on my machine?

No, I can't expose my insecure test server to the internet.

My testing was done within Chrome using this recipe:  [How To Limit Download Speed In Chrome](https://www.addictivetips.com/web/limit-download-speed-in-chrome/)

When viewing traffic using the inspector, the mpd is fetched OK, but no media requests are seen.

**Comment by BobCu** [comment]
My DASH and HLS URLs are built like this:
`    <a target="_blank" href="<dir_heirarchy>/manifest.mpd">DASH</a>`
`    <a target="_blank" href="<dir_heirarchy>/master.m3u8">HLS</a>`

The HLS player fetches the playlists generated by Shaka packager then plays the media.

The DASH player successfully fetches the manifest generated by Shaka packager, then nothing happens, no media requests are made.

Clearly, the manifest generated by Shaka packager isn't one the player can use to fetch the media files.

Why?

**Comment by BobCu** [comment]
Sending an email to shaka-packager-issues with temporary ngrok URLs to my test server.

**Comment by kqyang** [comment]
@BobCu Thanks! Can you share your source ts file as well? (The ts file provided to cvlc) 

The audio and video adaptation set does not align and they differ by ~ 3 segments, so the player is not able to find a timestamp with both audio and video segments. Increasing `time_shift_buffer_depth` may help. 

With the source ts file, we can try to re-produce the problem and figure out where the mis-alignment comes from.

**Comment by BobCu** [comment]
It's ~300 MB.  You really want it here?

**Comment by BobCu** [comment]
Just restarted with 60 second time_shift_buffer_depth.

Is there a Slack/Rocket/whatever channel we can use?

Robert (Bob) Cunningham
Senior Systems Engineer

**Comment by kqyang** [comment]
Re #https://github.com/google/shaka-packager/issues/526#issuecomment-444684124, I don't think you can attach it here. Can you send it to shaka-packager-issues or upload it to a cloud storage and attach the link here or shaka-packager-issues?

> Is there a Slack/Rocket/whatever channel we can use?

Not right now. It is probably be a good idea to get one.

**Comment by BobCu** [comment]
It may be both faster and better if you take the `ffmpeg` command from #509 and quickly roll your own TS file.

**Comment by kqyang** [comment]
It is possible that the problem is related to the specific file you have. We'd like to have the exact same setup so we can re-produce the same problem.

**Comment by BobCu** [comment]
I've updated the end of the web page to provide a link to the first TS file.

**Comment by kqyang** [comment]
Thanks!

**Comment by BobCu** [comment]
Come to think of it, how can it be related to the TS file?  Those segments play fine under HLS.   Isn't the same video decoder is used no matter how the segments are transported?

Remember: The video segments are **_never fetched_** by DASH.  For them to be bad, they'd at least have to be fetched, right?

**Comment by kqyang** [comment]
DASH and HLS are different. DASH manifests have a complete and accurate timeline of the media while HLS does not. The DASH player parses the manifest to determine which segment to fetch. For your case, there are no overlaps between audio presentation timeline and video presentation timeline so the player just keeps refreshing the manifest trying to find a time with both audio and video.

**Comment by BobCu** [comment]
Just restarted the server processes after re-transcoding the TS files overnight (the only change was to the text overlay), and DASH is suddenly working, for the first time ever.  I am still seeing the audio segment numbers race out ahead of the video (by about 10%), but the video keeps playing.

I'll keep opening video tabs each time the video loops to ensure fresh player instances are able to start.

I'm seeing no differences in the messages output by VLC and the packager, so I have no clue what's going on.  My next restart will enable verbose reporting.

**Comment by BobCu** [comment]
After 9 loops of a 10 minute video, the VLC looped output has good PCR and PTS, all now reading 01:29:50.xxx, with no misalignment between the 1 audio and 3 video streams.

It increasing seems the packager is skewing the audio segment timing relative to the 3 video segments.

I lack tools to easily peek inside the .m4s segment files to check their PCR/PTS against the manifest/playlist.  Presently trying a hex dump...

**Comment by kqyang** [comment]
@BobCu We are still investigating what is causing the skewing of the timing. Will let you know once there is an update. 

Not directly related to this issue, but some general recommendations to doing live streaming. See https://github.com/google/shaka-packager/issues/509#issuecomment-445330851.

**Comment by kqyang** [comment]
@BobCu We have found the root cause. It is a bug in VLC. It inserts an AUD between SPS/PPS and IDRSlice. Here is the sequence of NAL units from the live stream generated by VLC:

AUD | SPS | PPS | SPS | PPS | **AUD** | SEI | SEI | SEI | IDR_SLICE | AUD | SEI | NON_IDR_SLICE 

This is not compliant to H264 (ITU-T H.264 02/2014) spec. 

> ### 7.4.1.2.3 Order of NAL units and coded pictures and association to access units
> - When an access unit delimiter NAL unit is present, it shall be the first NAL unit. There shall be at most one access unit delimiter NAL unit in any access unit.

This confuses Shaka Packager and results in delayed processing of the NAL units: Shaka Packager does an early return when seeing AUD, so the access unit is not handled until the next access unit comes in. This effectively causes a skew of one frame, and it accumulates over time.

We will address it in packager. I suggest also filing a bug to VLC so the root cause can be fixed.

**Comment by kqyang** [comment]
No. I don't see the extra AUD in the raw stream provided by you.

**Comment by BobCu** [comment]
Let me know when to pull, and I'll build and test!

**Comment by BobCu** [comment]
Bug filed with VLC: https://trac.videolan.org/vlc/ticket/21549#ticket

**Comment by kqyang** [comment]
Thanks.

**Comment by BobCu** [comment]
Just noticed this is the last issue pending for v2.3: I've added myself as a repo watcher, and will try to build and test after every notification.

**Comment by kqyang** [comment]
@BobCu The workaround has just been pushed! Enjoy!

**Comment by BobCu** [comment]
Enjoying!

**Comment by BobCu** [comment]
VLC daily builds should now contain the fix for their problem.

**Comment by kqyang** [comment]
Great. Thanks for the update!
