### ISSUE TITLE
Trick Play - DASH

### ISSUE THREAD

**Issue by cgp1081** [google/shaka-packager#528]
I'm attempting to create a trick play track from _750 input - are there any input file requirements? I've tried every variation of on demand and live profiles I can think of, always get the same errors. The command works without trick play track

**Packager Command**:
packager 'in=/Path/To/Video/NCIS_188_AA_6CH_30M_1330855_3_aac_128.mp4,stream=audio,init_segment=/Path/To/Video/output/mp_clear1/NCIS_188_AA_6CH_30M_1330855_3_aac_128/init.m4v,segment_template=/Path/To/Video/output/mp_clear1/NCIS_188_AA_6CH_30M_1330855_3_aac_128/seg_$Number$.m4s' 'in=/Path/To/Video/NCIS_188_AA_6CH_30M_1330855_2_ac3_384.mp4,stream=audio,init_segment=/Path/To/Video/output/mp_clear1/NCIS_188_AA_6CH_30M_1330855_2_ac3_384/init.m4v,segment_template=/Path/To/Video/output/mp_clear1/NCIS_188_AA_6CH_30M_1330855_2_ac3_384/seg_$Number$.m4s' 'in=/Path/To/Video/NCIS_188_AA_6CH_30M_1330855_1_eac3_192.mp4,stream=audio,init_segment=/Path/To/Video/output/mp_clear1/NCIS_188_AA_6CH_30M_1330855_1_eac3_192/init.m4v,segment_template=/Path/To/Video/output/mp_clear1/NCIS_188_AA_6CH_30M_1330855_1_eac3_192/seg_$Number$.m4s' 'in=/Path/To/Video/NCIS_188_AA_6CH_30M_1330855_375.mp4,stream=video,init_segment=/Path/To/Video/output/mp_clear1/NCIS_188_AA_6CH_30M_1330855_375/init.m4v,segment_template=/Path/To/Video/output/mp_clear1/NCIS_188_AA_6CH_30M_1330855_375/seg_$Number$.m4s' 'in=/Path/To/Video/NCIS_188_AA_6CH_30M_1330855_750.mp4,stream=video,init_segment=/Path/To/Video/output/mp_clear1/NCIS_188_AA_6CH_30M_1330855_750/init.m4v,segment_template=/Path/To/Video/output/mp_clear1/NCIS_188_AA_6CH_30M_1330855_750/seg_$Number$.m4s' 'in=/Path/To/Video/NCIS_188_AA_6CH_30M_1330855_1500.mp4,stream=video,init_segment=/Path/To/Video/output/mp_clear1/NCIS_188_AA_6CH_30M_1330855_1500/init.m4v,segment_template=/Path/To/Video/output/mp_clear1/NCIS_188_AA_6CH_30M_1330855_1500/seg_$Number$.m4s' 'in=/Path/To/Video/NCIS_188_AA_6CH_30M_1330855_2100.mp4,stream=video,init_segment=/Path/To/Video/output/mp_clear1/NCIS_188_AA_6CH_30M_1330855_2100/init.m4v,segment_template=/Path/To/Video/output/mp_clear1/NCIS_188_AA_6CH_30M_1330855_2100/seg_$Number$.m4s' 'in=/Path/To/Video/NCIS_188_AA_6CH_30M_1330855_3000.mp4,stream=video,init_segment=/Path/To/Video/output/mp_clear1/NCIS_188_AA_6CH_30M_1330855_3000/init.m4v,segment_template=/Path/To/Video/output/mp_clear1/NCIS_188_AA_6CH_30M_1330855_3000/seg_$Number$.m4s' 'in=/Path/To/Video/NCIS_188_AA_6CH_30M_1330855_4500.mp4,stream=video,init_segment=/Path/To/Video/output/mp_clear1/NCIS_188_AA_6CH_30M_1330855_4500/init.m4v,segment_template=/Path/To/Video/output/mp_clear1/NCIS_188_AA_6CH_30M_1330855_4500/seg_$Number$.m4s' 'in=/Path/To/Video/NCIS_188_AA_6CH_30M_1330855_750.mp4,stream=video,init_segment=/Path/To/Video/output/mp_clear1/NCIS_188_AA_6CH_30M_1330855_750/init.m4v,segment_template=/Path/To/Video/output/mp_clear1/NCIS_188_AA_6CH_30M_1330855_750/seg_$Number$.m4s,trick_play_factor=1' --clear_lead 0 --segment_duration 6 --fragment_duration 6 --generate_static_mpd --mpd_output /Path/To/Video/output/mp_clear1/stream.mpd --ad_cues '0;407;730;1208'

[1206/164743:ERROR:status.cc(57)] Not implemented reached in std::string shaka::error::(anonymous namespace)::ErrorCodeToString(shaka::error::Code)Unknown Status Code: 19
[1206/164743:ERROR:demuxer.cc(319)] Failed to process sample 256 19 (UNKNOWN_STATUS): Trick play only supports stream info, segment info, and media sample messages.
[1206/164743:ERROR:mp4_media_parser.cc(773)] Failed to process the sample.
[1206/164745:ERROR:packager_main.cc(492)] Packaging Error: 8 (PARSER_FAILURE): Cannot parse media file

Trick play track input file:
Format                                   : MPEG-4
Format profile                           : Base Media
Codec ID                                 : isom (isom/iso2/avc1/mp41)
File size                                : 232 MiB
Duration                                 : 43 min 17 s
Overall bit rate                         : 748 kb/s
Writing application                      : Lavf57.71.100

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L4
Format settings                          : CABAC / 4 Ref Frames
Format settings, CABAC                   : Yes
Format settings, ReFrames                : 4 frames
Codec ID                                 : avc1
Codec ID/Info                            : Advanced Video Coding
Duration                                 : 43 min 17 s
Bit rate                                 : 750 kb/s
Width                                    : 768 pixels
Height                                   : 432 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Variable
Frame rate                               : 23.976 FPS
Minimum frame rate                       : 23.739 FPS
Maximum frame rate                       : 23.976 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.094
Stream size                              : 231 MiB (100%)
Writing library                          : x264 core 148
Encoding settings                        : cabac=1 / ref=2 / deblock=1:0:0 / analyse=0x3:0x113 / me=hex / subme=6 / psy=1 / psy_rd=1.00:0.00 / mixed_ref=1 / me_range=16 / chroma_me=1 / trellis=1 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-2 / threads=13 / lookahead_threads=2 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=3 / b_pyramid=2 / b_adapt=1 / b_bias=0 / direct=1 / weightb=1 / open_gop=0 / weightp=1 / keyint=48 / keyint_min=4 / scenecut=0 / intra_refresh=0 / rc_lookahead=30 / rc=2pass / mbtree=1 / bitrate=750 / ratetol=1.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / cplxblur=20.0 / qblur=0.5 / vbv_maxrate=900 / vbv_bufsize=750 / nal_hrd=none / filler=0 / ip_ratio=1.40 / aq=1:1.00

**Comment by kqyang** [comment]
@cgp1081 That is a bug. TrickPlay handler does not support Ad Cue messages. Will fix soon. Thanks for the report.

**Comment by kqyang** [comment]
@cgp1081 It should be fixed now. Let us know if you are still seeing problems.
