### ISSUE TITLE
[Question] Packaging DRM Widevine with 3rd party vendor Header information

### ISSUE THREAD

**Issue by gabrielboliveira** [google/shaka-packager#530]
## System info
**Operating System**: macOS Mojave
**Shaka Packager Version**: 2.2.0

This is a question on how to use shaka-packager to encrypt DASH with DRM support for Widevine, using a third party vendor that outputs a few different information that described on the documentation.

This vendor outputs a key, key_id, header and system_id information, but I'm not able to use it with shaka-packager. 

I have a working example with Bento4 that uses a `--widevine-header` tag and encryption key, so the vendor information is valid, I'm able to generate and playback the DRM media.

I'm also able to generate `--keys` attribute with key and key_id, but cannot find how to convert that Widevine Header to a valid PSSH payload so I can use it with shaka-packager.

This is what I've come up so far:

```
packager 'in=example-24.mp4,stream=audio,init_segment=dash/audio/init.mp4,segment_template=dash/audio/$Number$.m4s,drm_label=AUDIO' \
    'in=example-24.mp4,stream=video,init_segment=dash/video/init.mp4,segment_template=dash/video/$Number$.m4s,drm_label=HD' \
    --enable_raw_key_encryption \
    --protection_scheme cenc \
    --protection_systems Widevine \
    --keys label=HD:key_id=hex-key-id:key=hex-key,label=AUDIO:key_id=hex-key-id:key=hex-key \
    --pssh pssh? \
    --generate_static_mpd \
    --mpd_output \
    dash/stream.mpd
```

My example uses a script to get hex from key and key_id: `echo $key_b64 | base64 -d | xxd -p`. That worked out great, it outputs a valid key hex and I can generate the `--keys`. I've tried to use same xxd and base64 to convert the Header to PSSH, but it outputs this error. I believe it's not the right method 😄 

```
[1211/174641:ERROR:protection_system_specific_info.cc(45)] Failure while processing: reader.SkipBytes(size - 4)
[1211/174641:ERROR:raw_key_source.cc(108)] --pssh argument should be full PSSHboxes.
[1211/174641:ERROR:packager_main.cc(512)] Failed to initialize packager: 3 (INVALID_ARGUMENT): Failed to create key source.
```

Should I use `pssh-box` to generate that valid PSSH? This is what I'm not sure.

Any advice will help. Thanks!

**Comment by kqyang** [comment]
@gabrielboliveira Yes, please use pssh-box script available in https://github.com/google/shaka-packager/blob/master/packager/tools/pssh/pssh-box.py:

```bash
$ packager/tools/pssh/pssh-box.py --widevine-system-id --pssh-data <base64 widevine header you have>
```

**Comment by gabrielboliveira** [comment]
Thanks! You are awesome 😄 It worked with that pssh-box
