### ISSUE TITLE
[Question] How to monitor status during Run() with the packager library?

### ISSUE THREAD

**Issue by baniks3** [google/shaka-packager#532]
I am using the packager library libpackager.so to run multiple instances of the packager in parallel with live streams. I would like to have the ability to monitor the status of these instances to check for errors/warnings/input losses etc while they are running. 

Does the library offer an API/callback to accomplish this?

**Comment by baniks3** [comment]
Thanks @kqyang for the answer. I suppose a subscription to user logs would work as long as the subscriber can choose the log level it wants to subscribe to (The default might be too noisy/quiet for one's liking).

I think the ideal and perhaps the simplest solution I would like to have as a user is an API that lets you query the status of a Packager instance on demand. 

This is my use case - 
1. An application that runs multiple instances of shaka::Packager in parallel 
2. The application needs to be able to detect runtime errors/warnings including input loss so that it can take actions (restart shaka, alert user about input loss etc.) to rectify them.

**Comment by kqyang** [comment]
> I suppose a subscription to user logs would work as long as the subscriber can choose the log level it wants to subscribe to (The default might be too noisy/quiet for one's liking).

Yes, the log level will be configurable, including the logging module, just like the command line program.

> I think the ideal and perhaps the simplest solution I would like to have as a user is an API that lets you query the status of a Packager instance on demand.

It is hard to define what status a user wants to know and wants to act on. If you have any concrete examples, we will be glad to evaluate it. 

We also welcome external contributions. If you have an idea in mind and you'd like to implement it, let us know any time :) and we can start the design discussion.

> The application needs to be able to detect runtime errors/warnings including input loss so that it can take actions (restart shaka, alert user about input loss etc.) to rectify them.

Not sure what you are referring to for "input loss".

**Comment by baniks3** [comment]
@kqyang In regards to "input loss", what I meant was that our application needs to alert the user (NOT the end-user/client) about possible input loss so that they can fix any connection issues. Obviously, there are other means of detecting such incidents but it would be nice if Shaka too, had this ability.

**Comment by kqyang** [comment]
@baniks3 So what is an "input loss"? Is it for live streaming case only? Are you referring the "input is gone"?
