### ISSUE TITLE
descriptor header size limit in 'esds' box

### ISSUE THREAD

**Issue by Jason239** [google/shaka-packager#536]
Hi.

I wonder why the maximum header size of the esds(in 'mp4a') box is 64. 
It is defined as 'kMaxDecoderSpecificInfoSize' in es_descriptor.cc.

What is the purpose of this atom, and why is there a limit of 64? 
One of my files has an error because this value is 80. Is there a problem with this file?

**Comment by kqyang** [comment]
@Jason239 The limit of 64 is an arbitrary value to avoid supporting size >= 128, which we do not think it would happen. 

We'll fix the issue. Do you have a sample file we can use to verify the fix?

**Comment by Jason239** [comment]
Sure, here it is.

https://mpdsample.s3.amazonaws.com/share/BigBuckBunny_24_10m_aac%282ch%29.zip

Thanks.
