### ISSUE TITLE
Packaging with live key rotation

### ISSUE THREAD

**Issue by Jason239** [google/shaka-packager#537]
Hi.

I want to package live stream with key rotation in Multi-DRM.
If I have a KMS server that can continuously generate and manage keys and PSSHs, what parameters of the Shaka packager can be used?

I think it seems to need an event to read key and PSSH every period for packager.
Can I set an event listener that can handle events every period? 
Or is there a way to register a KMS Server url that can communicate with the packager in specific format such as CPIX?

**Comment by kqyang** [comment]
@Jason239 We don't support CPIX yet, which is on our Q3 2019 road map.

The best option right now is to implement [Widevine's Common Encryption API](https://storage.googleapis.com/wvdocs/Widevine_DRM_Encryption_API.pdf) in your KMS server. It is a JSON API and should be straight forward to implement. It also supports multi-DRM.

You can talk to the server that implements the API by following the tutorial here: https://google.github.io/shaka-packager/html/tutorials/widevine.html. The key rotation is enabled by having non-zero crypto periods (`--crypto_period_duration`).

Let us know if you have more questions.

**Comment by Jason239** [comment]
I see, then does FPS DRM also applied?

**Comment by Jason239** [comment]
Is there a separate window for feature requests?

**Comment by kqyang** [comment]
@Jason239 You can just file another issue in https://github.com/google/shaka-packager/issues.

**Comment by Jason239** [comment]
I got it. 

Thanks !
