### ISSUE TITLE
Help/Bug with pssh-box utility

### ISSUE THREAD

**Issue by levyshachar2** [google/shaka-packager#538]
## System info
**Operating System**: macOS 10.14
**Shaka Packager Version**: packager version v2.3.0-5bf8ad5ed5-release

## Issue and steps to reproduce the problem
Hi , I'm in the process of creating encrypted dash content with Widevine and using EZDRM.
I'm getting an error in the packager "--pssh argument should be full PSSH boxes"
which led me to the pssh-box python utility.
I looked at the README in "https://github.com/google/shaka-packager/tree/master/packager/tools/pssh" but I can't seem to get the script working.

Extra steps to reproduce the problem?
(1) I downloaded the script , and putted it in "../shaka_packager/src/out/Release/pyproto" (I did this because when I ran the script somewhere else I got "No module named widevine_pssh_data_pb2"
(2) tried to do a sanity and run python2 pssh-box.py 

What is the expected result?
some help text

What happens instead?
`Traceback (most recent call last):
  File "pssh-box.py", line 30, in <module>
    import widevine_pssh_data_pb2  # pylint: disable=g-import-not-at-top
  File "/Users/shacharlevy/Downloads/shaka_packager/src/out/Release/pyproto/../../../out/Release/pyproto/packager/media/base/widevine_pssh_data_pb2.py", line 8, in <module>
    from google.protobuf import reflection as _reflection
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/google/protobuf/reflection.py", line 70, in <module>
    from google.protobuf.internal import python_message
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/google/protobuf/internal/python_message.py", line 82, in <module>
    from google.protobuf import text_format
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/google/protobuf/text_format.py", line 630
    if o == 10: return rb"\n"   # optional escape`

<Please attach the input files or email to shaka-packager-issues@google.com.>
<Please provide any additional information below.>

The README was a little unclear on the steps. maybe someone can clarify it a little bit.

thank you

**Comment by kqyang** [comment]
@levyshachar2 

Thanks for filing the issue. We will update the README to make it clearer!

There are two ways you can run pssh-box utility:

(1) Option 1: Build shaka packager locally, which generates necessary files for pssh-box utility to run. 

(2) Option 2: Install protobuf including the pip package on your machine. Then compile widevine proto:

```
protoc -I=$SRC_DIR --python_out=. $SRC_DIR/packager/media/base/widevine_pssh_data.proto
```

Let us know if you have more questions!

**Comment by levyshachar2** [comment]
@kqyang thank you for your fast response. I got the shaka packager locally built , what are the next steps that I should perform in order to run the script?
What I tried so far is to download the pssh-box.py script to /shaka_packager/src/out/Release/pyproto
but as I mentioned above , I'm getting an error.
Is this the right path to put the script in? should there be any previous steps ( besides compiling the shaka packager) ?

Thank you

**Comment by kqyang** [comment]
@levyshachar2 Good finding! We'll do some clean-ups so you can run the script without installing protobuf.

> If I try to run the script in another folder I get "ImportError: No module named widevine_pssh_data_pb2"

If you keep the script in packager/tools/pssh, you should be able to run it from anywhere. Just add "packager/tools/pssh" to your paths.

**Comment by levyshachar2** [comment]
@kqyang finally working 👍 
Thank you very much for you assistance.

**Comment by gabrielboliveira** [comment]
Hey guys, jumping on this issue with a similar problem/solution. 

Previously we installed shaka-packager downloading binary from GitHub and moving to `/usr/local/bin`. Now we need to use `pssh-box` to generate the DRM pssh box with DRM header provided from third party. I've developed a script to build the package and link binaries so you can use packages whenever necessary.

Old Script:
```bash
curl -L "https://github.com/google/shaka-packager/releases/download/v2.3.0/packager-linux" -o "packager"
mv packager /usr/local/bin/packager
chmod +x /usr/local/bin/packager
```

New Script
```bash
#! /bin/bash

PACKAGER_VERSION=v2.3.0
apt-get install -y python-pip
pip install six

git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git /tmp/depot_tools --depth=1
PATH="$PATH:/tmp/depot_tools"
mkdir -p /tmp/shaka_packager
cd /tmp/shaka_packager
gclient config https://www.github.com/google/shaka-packager.git --name=src --unmanaged
gclient sync -r $PACKAGER_VERSION --no-history
cd src
ninja -C out/Release
cd packager/third_party/protobuf/python
PATH=../../../../out/Release/:"$PATH" python setup.py build
mkdir -p /usr/local/src/shaka-packager/packager/tools \
    /usr/local/src/shaka-packager/packager/third_party \
    /usr/local/src/shaka-packager/out
cp -r /tmp/shaka_packager/src/packager/tools/pssh/ /usr/local/src/shaka-packager/packager/tools
cp -r /tmp/shaka_packager/src/packager/third_party/protobuf /usr/local/src/shaka-packager/packager/third_party
cp -r /tmp/shaka_packager/src/out/Release /usr/local/src/shaka-packager/out

ln -s /usr/local/src/shaka-packager/packager/tools/pssh/pssh-box.py /usr/local/bin/pssh-box
ln -s /usr/local/src/shaka-packager/out/Release/packager /usr/local/bin/packager
```

This new script builds everything, so it may take a while to execute. Since we have to add this to our docker environment, all devs will have to build this, increasing **a lot** the build time (from a few secs to 15~20 minutes). We could pre-build this and download a `.tgz` from a public link, but not a general solution.

Is there any easier way to have the pssh-box script without having to build everything? Is it possible to build `pssh-box.py` into an executable similar to `packager`?

**Comment by kqyang** [comment]
> Since we have to add this to our docker environment, all devs will have to build this

I am curious why all devs need to rebuild it if it is included in your docker environment?

> Is there any easier way to have the pssh-box script without having to build everything? Is it possible to build pssh-box.py into an executable similar to packager?

We are updating the script. It will be pushed out this week. And yes, we'll update the released executable to include the script!

**Comment by gabrielboliveira** [comment]
> I am curious why all devs need to rebuild it if it is included in your docker environment?

Right now our docker env is based on [vessel](https://github.com/shipping-docker/vessel), and all Dockerfiles are on the same repository. We have plans to in the future have a private image with all our dependencies, but as it is right now all devs build images locally.

As I said, this is our requirement, and we can make it work without the binary, but having it easy to download would help a lot other developers.

> We are updating the script. It will be pushed out this week. And yes, we'll update the released executable to include the script!

This is great news, thanks for the hard work!

**Comment by kqyang** [comment]
@gabrielboliveira We have updated the script. You should be able to build it by running `ninja -C out/Release pssh_box_py`, which is much faster than `ninja -C out/Release`. See https://github.com/google/shaka-packager/tree/master/packager/tools/pssh for details.

We are planning to update our docker image and releases to include the tool as well. See #550 for details.
