### ISSUE TITLE
[DASH] Allow AdaptationSet switching on FLAC and Opus (or make the codecs customize-able)

### ISSUE THREAD

**Issue by ctoshni** [google/shaka-packager#542]
Hi, i'm using latest Shaka version ;

As per DASH-IF-IOP-v4.3 - "A content author may signal such seamless switching property across Adaptation Sets by providing a Supplemental Descriptor along with an Adaptation Set with @schemeIdUri set to  `urn:mpeg:dash:adaptation-set-switching:2016` and the @value is a comma separated list of Adaptation Set IDs that may be seamlessly switched to from this Adaptation Set."

I have 2 adaptation sets with same content but different codecs and I want to have seamless adaptive bitrate switching between them.

Which shaka-packager command can I use to generate a mpd with @schemeIdUri set to  `urn:mpeg:dash:adaptation-set-switching:2016` in adaptation sets?

**Comment by kqyang** [comment]
@ctoshni Shaka Packager generates the tag when seamless switching is possible, e.g. for SD and HD AdaptationSets, who are encrypted with different keys.

> I have 2 adaptation sets with same content but different codecs and I want to have seamless adaptive bitrate switching between them.

Normally for different codecs, seamless switching is not possible. May I know which codecs you'd like to allow seamless switching and which platform are you thinking of?

**Comment by kqyang** [comment]
I am not sure what is the best way to support it. One option is to add an argument to allow users to specify the switchable codecs. What do you think?

**Comment by kqyang** [comment]
@ctoshni We don't have bandwidth to work on it right now. I'll put it in v2.5 milestone for now.

Let us know if you'd like to help. We can give you pointers if you are interested.

**Comment by ctoshni** [comment]
> Let us know if you'd like to help. We can give you pointers if you are interested.

I would be happy to help but will not be able to do due to bandwidth issues. 
As you have made it part of v2.5 milestone, closing the issue.

**Comment by kqyang** [comment]
It needs to stay open to be included in future milestones :)

**Comment by kqyang** [comment]
We have two options:

  1. Add a new flag to allow users to specify the set of switchable codecs, e.g. `--allow_switching="opus,flac"` if users want to allow switching between Opus and FLAC; it can also support multiple sets of switching: `--allow_switching="opus,flac;h264,h265"` to allow switching between Opus and FLAC, and also switching between h264 and h265.

  2. Add a boolean flag to allow switching between different codecs: `--allow_codec_switching`. 

Option 1 has finer controls and is more flexible while option 2 is simpler and it might suffice in most usage scenarios.

**Comment by jakubvojacek** [comment]
I am for option 2 as it sounds it could be implemented easier. As per https://github.com/google/shaka-packager/issues/571, can you please provide some pointers, I can try to take a look whether its my capabilities.

**Comment by kqyang** [comment]
Certainly, I will take a look and get back to you later.

**Comment by kqyang** [comment]
@jakubvojacek The code that handles adaptation set switching is available here: https://github.com/google/shaka-packager/blob/master/packager/mpd/base/period.cc#L90. Right now it handles AdaptationSets with different content protections only. We need to extend it to allow switching between different codecs, if they have the same language, media type (audio, video etc) and container type.

AdaptationSet class does not store `MediaInfo` right now. We should make it `MediaInfo` a member of AdaptationSet constructor as it is useful to determine if the two AdaptationSets are switchable.

Here is the proposed steps:

1. Refactor AdaptationSet class to take `MediaInfo` as a constructor parameter.
    - We can then move Period::ProtectedAdaptationSetMap to AdaptationSet class to simplify code: https://github.com/google/shaka-packager/blob/master/packager/mpd/base/period.cc#L216.
2. Add a new parameter to GetAdaptationSetKey to be able to ignore codec: https://github.com/google/shaka-packager/blob/master/packager/mpd/base/mpd_utils.cc#L145.
3. Add a flag for `--allow_codec_switching` flag. You can do a code search to see how `allow_approximate_segment_timeline` is defined and follow the same approach.
4. Update the new Period::ProtectedAdaptationSetMap::Switchable (which is now AdaptationSet::Switchable), and if the flag is set, check for AdaptationSet key with codec ignored.

Let us know if there is any question. Thanks for helping out!

**Comment by jakubvojacek** [comment]
@kqyang Thank you, will check!

**Comment by kqyang** [comment]
Thanks @sr1990 for implementing the feature! 

The PR in #726 takes a slightly different approach as in https://github.com/google/shaka-packager/issues/542#issuecomment-475746652. The step 1 (code refactoring of Period::ProtectedAdaptationSetMap and AdaptationSet) is moved to a separate issue #733 instead.
