### ISSUE TITLE
[Survey] Shaka Packager features and support

### ISSUE THREAD

**Issue by kqyang** [google/shaka-packager#546]
**Please help us decide** what features to prioritize in Shaka Packager.  **Take the survey here**:
https://goo.gl/forms/UOpcaeMDsd1fRxmH2. It should take less than five minutes to complete.

The survey will open until March 1, 2019. After the survey is closed, we will share the aggregate results from the multiple choice questions. Other information, e.g. email addresses, company names, or any of the comments left in the open comment sections will not be shared.

**Comment by JuliusThms** [comment]
Done and thanks!

Gesendet über BlackBerry Hub für Android<http://play.google.com/store/apps/details?id=com.blackberry.hub>
Von: notifications@github.com
Gesendet: 23. Januar 2019 23:09
An: shaka-packager@noreply.github.com
Antworten: reply@reply.github.com
Cc: subscribed@noreply.github.com
Betreff: [google/shaka-packager] [Survey] Shaka Packager features and support (#546)



Please help us decide what features to prioritize in Shaka Packager. Take the survey here:
https://goo.gl/forms/UOpcaeMDsd1fRxmH2. It should take less than five minutes to complete.

The survey will open until March 1, 2019. After the survey is closed, we will share the aggregate results from the multiple choice questions. Other information, e.g. email addresses, company names, or any of the comments left in the open comment sections will not be shared.

-

**Comment by kqyang** [comment]
Just a quick reminder that we are seeking your feedback. Please take our survey (if you haven't) and help us decide what features to prioritize in Shaka Packager:
https://goo.gl/forms/UOpcaeMDsd1fRxmH2. 

The survey will be open until Mar 1, 2019.

Thanks!

**Comment by kqyang** [comment]
Please take our survey (if you haven't) and help us decide what features to prioritize in Shaka Packager:
https://goo.gl/forms/UOpcaeMDsd1fRxmH2.

The survey will be closed this week.

Thanks!

**Comment by hbengali** [comment]
The results of the survey are available here: https://drive.google.com/file/d/1wIvLWsjRL1nsHAsLRj4IVXBbcNls-G3r/view?usp=sharing

Thank you to everyone who participated!
