### ISSUE TITLE
Specify different pssh for single mpd file

### ISSUE THREAD

**Issue by ctoshni** [google/shaka-packager#547]
Hi, i'm using latest Shaka version ;

When multiple keys are used for different streams in single mpd file, the default shaka behaviour is to concatenate all of them. Is there any way I can have different pssh generated for different AdaptationSet?

For eg - below is the command which takes concatenated pssh
" packager "in=/tmp/tmp.elF85094Hz/295899917_320k.mp4,stream=audio,output=/media/295899917_drm/295899917_320k.mp4,drm_label=AUDIO_OPUS"
          "in=/tmp/tmp.elF85094Hz/295899917_44KHz16.mp4,stream=audio,output=/media/295899917_drm/295899917_44KHz16.mp4,drm_label=AUDIO_FLAC"
          --fragment_duration 10 --segment_duration 10  --clear_lead 30 --v=-1
          --enable_raw_key_encryption --keys label=AUDIO_OPUS:key_id=123:key=xyz,label=AUDIO_FLAC:key_id=456:key=abc --pssh <concetenated_pssh>           --generate_static_mpd --mpd_output /media/295899917_drm/295899917.mpd "

I want to give different pssh to be applied on AdaptationSets for AUDIO_OPUS and AUDIO_FLAC. Is there any way I can specify?

**Comment by kqyang** [comment]
No, that is not supported right now. It will certainly make it non-switchable between OPUS and FLAC as you have requested in #542.

I can see that you want to use different encryption keys for OPUS and FLAC. I'd suggest to use the same PSSH for OPUS and FLAC and have the license server to deliver both keys. Both Widevine and PlayReady supports delivering multiple keys in the same license. It saves unnecessary license requests and is more efficient. Will that work for you?

**Comment by ctoshni** [comment]
> I can see that you want to use different encryption keys for OPUS and FLAC. I'd suggest to use the same PSSH for OPUS and FLAC and have the license server to deliver both keys. Both Widevine and PlayReady supports delivering multiple keys in the same license. It saves unnecessary license requests and is more efficient. Will that work for you?
 
Yes, I want to use different encryption keys for OPUS and flac. I can use same pssh for both of them but I want to use different content ids. 

When I use 2 content ids in the pssh-box then it takes only 1st content id and generate pssh corresponding to it. The command that I used was -

pssh-box.py --hex --widevine-system-id --protection-scheme cenc --provider <Provider> --key-id $keyid --key-id $Two_keyid --content-id $keyid_hex --content-id $Two_keyid_hex 

Is there any way I can specify 2 content ids?

**Comment by kqyang** [comment]
> Is there any way I can specify 2 content ids?

Widevine PSSH does not support more than one content id. Can you use the same content id but different key ids for OPUS and FLAC? Like what we are doing for SD video and HD video?

**Comment by Jason239** [comment]
@kqyang 
But the payload in PlayReady's PSSH has key id like '<KID>key id</KID>'.
So in PlayReady, wouldn't it have to use different PSSHs if use different key ids?

**Comment by Jason239** [comment]
Even if use Shaka's feature to make PSSH(--protection_systems Widevine,PlayReady), PSSH of PlayReady seems to be applied differently.

**Comment by kqyang** [comment]
@Jason239 PlayReady 4.2.0 adds support for multiple key ids. See this document for details: http://download.microsoft.com/download/2/3/8/238F67D9-1B8B-48D3-AB83-9C00112268B2/PlayReady%20Header%20Object%202015-08-13-FINAL-CL.PDF or their latest specification at https://docs.microsoft.com/en-us/playready/specifications/playready-header-specification for details.

We will update the PlayReady PSSH generation in Shaka to support 4.3.0 some time this year, which is also needed to support cbcs in PlayReady.

**Comment by Jason239** [comment]
Ok, I got it.
By the way, do you have any sample which can be played as multiple keys in PlayReady?

**Comment by kqyang** [comment]
@Jason239 No. You can probably get samples from Microsoft.

**Comment by kqyang** [comment]
We have no plans to support specifying different PSSHs for different AdaptationSets so closing the issue as obsolete.

As for the v4.3.0 Playready PSSH generation, it is tracked in #735.
