### ISSUE TITLE
Incorrect Dimensions - HLS HEVC

### ISSUE THREAD

**Issue by cgp1081** [google/shaka-packager#548]
**Shaka Packager Version**: version v2.3.0-5bf8ad5ed5-release

Extra steps to reproduce the problem?
(1)Packaging HEVC streams at non-16:9 AR
(2) See dimensions in HLS output do not match content dimensions

**MP4 Content**
ID                                       : 1
Format                                   : HEVC
Format/Info                              : High Efficiency Video Coding
Format profile                           : Main@L5@Main
Codec ID                                 : hev1
Codec ID/Info                            : High Efficiency Video Coding
Duration                                 : 1 min 56 s
Bit rate                                 : 5 759 kb/s
**Width                                    : 2 560 pixels
Height                                   : 1 350 pixels**
Display aspect ratio                     : 1.896
Frame rate mode                          : Constant
Frame rate                               : 23.976 (24000/1001) FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.070
Stream size                              : 79.7 MiB (100%)
Writing library                          : x265 2.7:[Linux][GCC 4.8.4][64 bit] 8bit

**HLS Output:**
#EXT-X-STREAM-INF:BANDWIDTH=6777506,AVERAGE-BANDWIDTH=6086244,CODECS="hvc1.1.6.L150.90,mp4a.40.2",**RESOLUTION=2730x1440**

**Init segment:**
Video
ID                                       : 1
Format                                   : HEVC
Format/Info                              : High Efficiency Video Coding
Format profile                           : Main@L5@Main
Codec ID                                 : hvc1
Codec ID/Info                            : High Efficiency Video Coding
**Width                                    : 2 730 pixels
Height                                   : 1 440 pixels**
Display aspect ratio                     : 1.896
Frame rate                               : 23.976 (24000/1001) FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Writing library                          : x265 2.9:[Linux][GCC 4.8.4][64 bit] 8bit

What is the expected result?
Expect stream dimensions to match input content

What happens instead?
Metadata in manifest and init segments incorrect

**Comment by kqyang** [comment]
@cgp1081 Do you have a sample content that can re-produce this problem?

**Comment by cgp1081** [comment]
We've found that if we encode content to use the standard heights, 720, 1080, 1440 that the dimensions are reported correctly, but if we encode renditions to standard widths, the 1280, 1920, 2560, they are incorrect in the packaged streams.

This only affects content not in true 16:9

Samples sent via email

**Comment by kqyang** [comment]
@cgp1081 Can you provide the full packaging command you used to re-produce the problem? We were not able to re-produce it with our commands.

**Comment by cgp1081** [comment]
Command
`'in=testmedia_TestMedia_4k_Clip_6CH_1_eac3_192.mp4,stream=audio,init_segment=1604878_dash/testmedia_TestMedia_4k_Clip_6CH_1_eac3_192/init.m4v,segment_template=1604878_dash/testmedia_TestMedia_4k_Clip_6CH_1_eac3_192/seg_$Number$.m4s,hls_group_id=testmedia_TestMedia_4k_Clip_6CH_1_eac3_192' 'in=testmedia_TestMedia_4k_Clip_6CH_2_ac3_384.mp4,stream=audio,init_segment=1604878_dash/testmedia_TestMedia_4k_Clip_6CH_2_ac3_384/init.m4v,segment_template=1604878_dash/testmedia_TestMedia_4k_Clip_6CH_2_ac3_384/seg_$Number$.m4s,hls_group_id=testmedia_TestMedia_4k_Clip_6CH_2_ac3_384' 'in=testmedia_TestMedia_4k_Clip_6CH_3_aac_128.mp4,stream=audio,init_segment=1604878_dash/testmedia_TestMedia_4k_Clip_6CH_3_aac_128/init.m4v,segment_template=1604878_dash/testmedia_TestMedia_4k_Clip_6CH_3_aac_128/seg_$Number$.m4s,hls_group_id=testmedia_TestMedia_4k_Clip_6CH_3_aac_128' 'in=testmedia_TestMedia_4k_Clip_6CH_600.mp4,stream=video,init_segment=1604878_dash/testmedia_TestMedia_4k_Clip_6CH_600/init.m4v,segment_template=1604878_dash/testmedia_TestMedia_4k_Clip_6CH_600/seg_$Number$.m4s' 'in=testmedia_TestMedia_4k_Clip_6CH_1800.mp4,stream=video,init_segment=1604878_dash/testmedia_TestMedia_4k_Clip_6CH_1800/init.m4v,segment_template=1604878_dash/testmedia_TestMedia_4k_Clip_6CH_1800/seg_$Number$.m4s' 'in=testmedia_TestMedia_4k_Clip_6CH_3500.mp4,stream=video,init_segment=1604878_dash/testmedia_TestMedia_4k_Clip_6CH_3500/init.m4v,segment_template=1604878_dash/testmedia_TestMedia_4k_Clip_6CH_3500/seg_$Number$.m4s' 'in=testmedia_TestMedia_4k_Clip_6CH_6000.mp4,stream=video,init_segment=1604878_dash/testmedia_TestMedia_4k_Clip_6CH_6000/init.m4v,segment_template=1604878_dash/testmedia_TestMedia_4k_Clip_6CH_6000/seg_$Number$.m4s' 'in=testmedia_TestMedia_4k_Clip_6CH_10000.mp4,stream=video,init_segment=1604878_dash/testmedia_TestMedia_4k_Clip_6CH_10000/init.m4v,segment_template=1604878_dash/testmedia_TestMedia_4k_Clip_6CH_10000/seg_$Number$.m4s' --segment_duration 6 --fragment_duration 6  --generate_static_mpd --mpd_output 1604878_dash/stream.mpd --hls_master_playlist_output 1604878_dash/master.m3u8`

Output
`#EXTM3U
## Generated with https://github.com/google/shaka-packager version a1fdc11-release

#EXT-X-MEDIA:TYPE=AUDIO,URI="stream_2.m3u8",GROUP-ID="testmedia_TestMedia_4k_Clip_6CH_1_eac3_192",LANGUAGE="en",NAME="stream_2",AUTOSELECT=YES,CHANNELS="6"
#EXT-X-MEDIA:TYPE=AUDIO,URI="stream_3.m3u8",GROUP-ID="testmedia_TestMedia_4k_Clip_6CH_2_ac3_384",LANGUAGE="en",NAME="stream_3",AUTOSELECT=YES,CHANNELS="6"
#EXT-X-MEDIA:TYPE=AUDIO,URI="stream_5.m3u8",GROUP-ID="testmedia_TestMedia_4k_Clip_6CH_3_aac_128",LANGUAGE="en",NAME="stream_5",AUTOSELECT=YES,CHANNELS="2"

#EXT-X-STREAM-INF:BANDWIDTH=16390038,CODECS="hev1.1.6.L150.90,ec-3",RESOLUTION=3839x2026,AUDIO="testmedia_TestMedia_4k_Clip_6CH_1_eac3_192"
stream_0.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=1185727,CODECS="hev1.1.6.L90.90,ec-3",RESOLUTION=959x506,AUDIO="testmedia_TestMedia_4k_Clip_6CH_1_eac3_192"
stream_6.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=6577685,CODECS="hev1.1.6.L120.90,ec-3",RESOLUTION=1919x1012,AUDIO="testmedia_TestMedia_4k_Clip_6CH_1_eac3_192"
stream_4.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=3324627,CODECS="hev1.1.6.L93.90,ec-3",RESOLUTION=1279x676,AUDIO="testmedia_TestMedia_4k_Clip_6CH_1_eac3_192"
stream_1.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=10413355,CODECS="hev1.1.6.L150.90,ec-3",RESOLUTION=2559x1350,AUDIO="testmedia_TestMedia_4k_Clip_6CH_1_eac3_192"
stream_7.m3u8

#EXT-X-STREAM-INF:BANDWIDTH=16582038,CODECS="hev1.1.6.L150.90,ac-3",RESOLUTION=3839x2026,AUDIO="testmedia_TestMedia_4k_Clip_6CH_2_ac3_384"
stream_0.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=1377727,CODECS="hev1.1.6.L90.90,ac-3",RESOLUTION=959x506,AUDIO="testmedia_TestMedia_4k_Clip_6CH_2_ac3_384"
stream_6.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=6769685,CODECS="hev1.1.6.L120.90,ac-3",RESOLUTION=1919x1012,AUDIO="testmedia_TestMedia_4k_Clip_6CH_2_ac3_384"
stream_4.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=3516627,CODECS="hev1.1.6.L93.90,ac-3",RESOLUTION=1279x676,AUDIO="testmedia_TestMedia_4k_Clip_6CH_2_ac3_384"
stream_1.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=10605355,CODECS="hev1.1.6.L150.90,ac-3",RESOLUTION=2559x1350,AUDIO="testmedia_TestMedia_4k_Clip_6CH_2_ac3_384"
stream_7.m3u8

#EXT-X-STREAM-INF:BANDWIDTH=16324164,CODECS="hev1.1.6.L150.90,mp4a.40.2",RESOLUTION=3839x2026,AUDIO="testmedia_TestMedia_4k_Clip_6CH_3_aac_128"
stream_0.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=1119853,CODECS="hev1.1.6.L90.90,mp4a.40.2",RESOLUTION=959x506,AUDIO="testmedia_TestMedia_4k_Clip_6CH_3_aac_128"
stream_6.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=6511811,CODECS="hev1.1.6.L120.90,mp4a.40.2",RESOLUTION=1919x1012,AUDIO="testmedia_TestMedia_4k_Clip_6CH_3_aac_128"
stream_4.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=3258753,CODECS="hev1.1.6.L93.90,mp4a.40.2",RESOLUTION=1279x676,AUDIO="testmedia_TestMedia_4k_Clip_6CH_3_aac_128"
stream_1.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=10347481,CODECS="hev1.1.6.L150.90,mp4a.40.2",RESOLUTION=2559x1350,AUDIO="testmedia_TestMedia_4k_Clip_6CH_3_aac_128"
stream_7.m3u8`

**Comment by kqyang** [comment]
@cgp1081 Let's take the stream x_1800_x as an example:

It has FAR (Frame Aspect Ratio) of 1280:676, SAR (Sample Aspect Ratio) of 39039:39040.

    DAR = FAR * SAR

Thus it has DAR (Display Aspect Ratio) of 1279:676, which is the value shown in the HLS playlist.

Do you expect to see 1280x676 in the RESOLUTION field? If so, the source content should be encoded with a DAR of 1280:676 instead of a FAR of 1280:676.

**Comment by kqyang** [comment]
@cgp1081 Do you still questions or concerns?
