### ISSUE TITLE
Question - Variable segment lengths

### ISSUE THREAD

**Issue by arodrigoca** [google/shaka-packager#549]
## System info
**Operating System**: Windows 10
**Shaka Packager Version**: v2.3.0

Hi, I just have a question. For researching purposes, I am using shaka packager to create a static MPD, with various segments for only one representation. Here is the command:

`packager-win.exe in=output.mp4,stream=video,init_segment=h264_1080p/init.mp4,segment_template=h264_1080p/$Number$.m4s --segment_duration 2 --generate_static_mpd --mpd_output h264.mpd`

What do I get:

            <S t="0" d="32256"/>
            <S t="32256" d="30720"/>
            <S t="62976" d="36352"/>
            <S t="99328" d="30720" r="3"/>
            <S t="222208" d="28160"/>
            <S t="250368" d="30720"/>
            <S t="281088" d="28672"/>
            <S t="309760" d="30720" r="2"/>
            <S t="401920" d="35328"/>
            <S t="437248" d="30720" r="4"/>
            <S t="590848" d="35328"/>
            <S t="626176" d="30720" r="4"/>
Etc.

The goal that I have is to create a stream where parts of the video are segmented in 2 seconds chunks and other parts are segmented in 4 seconds chunks. Because the packager does not create exact duration segments, even if the source video is closed GOP and constant framerate (correct me if I am wrong), I cannot just simply segment 2 times using different segment duration and swap the segments and MPD timeline lines between the 2 to do this. I would like to know if there is a way to use the packager so it segments in various durations, or if I can actually make the segments be equally long. 
If you need more information about the source video that I am using (ffmpeg commands, etc)  or any other thing, please let me know.
Thanks.

**Comment by kqyang** [comment]
> Because the packager does not create exact duration segments, even if the source video is closed GOP and constant framerate

What is the GOP size of your source content? You should be able to package with exact duration if the GOP is divisible by the segment duration. For example, you should be able to get 2-second segments if GOP is 1 second or 2 seconds. 

We'll be glad to look into it if it is not the case. Can you send your source content to us in that case?

**Comment by kqyang** [comment]
Glad to hear that your problem is addressed!
