### ISSUE TITLE
Include pssh_tool (pssh_box.py) in docker image and release

### ISSUE THREAD

**Issue by kqyang** [google/shaka-packager#550]
https://github.com/google/shaka-packager/issues/538 removes external dependency for pssh_tool and simplifies building process. We should also include it in our docker image and in the release.

**Comment by SomeoneWeird** [comment]
Any update on this one? Would be great to have a standalone PSSH generator :)

**Comment by kqyang** [comment]
@SomeoneWeird We are working on it. Will push the changes out soon.
