### ISSUE TITLE
Question - How to create dynamically created Periods in Live streaming using Shaka Packager?

### ISSUE THREAD

**Issue by levyshachar2** [google/shaka-packager#551]
Hi!

We have a requirement where we want to differentiate when the actual live streaming starts.
For example , consider a scenario where there is a lecture , the technical team setup the live stream at 20:00 and the stream starts at 20:00 , but the lecture itself starts at 20:30 , we want to be able to have a dash with two periods , one from 20:00 - 20:30 and the second from 20:30 until the end.

I saw at the documentation  the flag ad_cues which does indeed creates a multiple periods dash , however we can't use this flag as it is given to the Shaka packager as an argument (known beforehand).

We would like the option to activate a new period dynamically with some way of interacting with the currently running command.

Any ideas if this is possible at the moment?

I saw online about SCTE 35 which is more related to ads that can achieve what we need, but I don't understand how I can send the SCTE 35 command to the Shaka packager itself

Thank you!

**Comment by kqyang** [comment]
@levyshachar2 Unfortunately we do not support this use case at this moment. A possible workaround is to package two sets of streams, i.e one at 20:00 and another at 20:30. Will that work for you?

We do not support SCTE35 right now. We may look into it later this year.

**Comment by levyshachar2** [comment]
ok thank you for the suggestion.

**Comment by TheModMaker** [comment]
I'm going to close this due to inactivity.  Adding SCTE-35 is tracked in #352.  If you have any other issues or questions, feel free to comment or open a new issue.
