### ISSUE TITLE
Can NOT sync with MacOS Mojave 10.14.2

### ISSUE THREAD

**Issue by ShuaiZhao** [google/shaka-packager#552]
@kqyang 

## System info
**Operating System**: <e.g. macOS Mojave>
**Shaka Packager Version**: <e.g. v1.6.1, commit SHA etc>

## Issue and steps to reproduce the problem

**Packager Command**:

Extra steps to reproduce the problem?
(1) when do "gclient sync'" will get the following error:
```
Syncing projects: 100% (19/19), done.

________ running '/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python src/packager/build/mac_toolchain.py' in '/Users/shuaizhao/shaka_packager'
Using local toolchain.

________ running '/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python src/gyp_packager.py --depth=src/packager' in '/Users/shuaizhao/shaka_packager'
Updating projects from gyp files...
Traceback (most recent call last):
  File "./build/mac/find_sdk.py", line 90, in <module>
    print main()
  File "./build/mac/find_sdk.py", line 58, in main
    sdks = [re.findall('^MacOSX(10\.\d+)\.sdk$', s) for s in os.listdir(sdk_dir)]
OSError: [Errno 2] No such file or directory: '/Library/Developer/CommandLineTools/Platforms/MacOSX.platform/Developer/SDKs'
gyp: Call to 'python ./build/mac/find_sdk.py 10.10' returned exit status 1 while in /Users/shuaizhao/shaka_packager/src/packager/packager.gyp.
Error: Command '/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python src/gyp_packager.py --depth=src/packager' returned non-zero exit status 1 in /Users/shuaizhao/shaka_packager
```

Please provide any additional information below.
The following is the where my SDK directory is located
```
/Library/Developer/CommandLineTools/SDKs

┌─[shuaizhao@SZ-MacB] - [~] - [2019-01-31 03:23:03]
└─[1] <> cd /Library/Developer/CommandLineTools
┌─[shuaizhao@SZ-MacB] - [/Library/Developer/CommandLineTools] - [2019-01-31 04:37:24]
└─[0] <> ls
Library  Packages SDKs     usr
```

However the code is looking for 
```
"/Library/Developer/CommandLineTools/Platforms/MacOSX.platform/Developer/SDKs"
```

**Comment by ShuaiZhao** [comment]
@kqyang 

in the src/packager/build/mac/find_sdk.py

```
  47
  48   job = subprocess.Popen(['xcode-select', '-print-path'],
  49                          stdout=subprocess.PIPE,
  50                          stderr=subprocess.STDOUT)
  51   out, err = job.communicate()
  52   if job.returncode != 0:
  53     print >> sys.stderr, out
  54     print >> sys.stderr, err
  55     raise Exception('Error %d running xcode-select' % job.returncode)
  56   sdk_dir = os.path.join(
  57       out.rstrip(), 'Platforms/MacOSX.platform/Developer/SDKs') .   <======== this is where it needs to be updated. 
  58   sdks = [re.findall('^MacOSX(10\.\d+)\.sdk$', s) for s in os.listdir(sdk_dir)]
  59   sdks = [s[0] for s in sdks if s]  # [['10.5'], ['10.6']] => ['10.5', '10.6']
  60   sdks = [s for s in sdks  # ['10.5', '10.6'] => ['10.6']
  61           if parse_version(s) >= parse_version(min_sdk_version)]
  62   if not sdks:
  63     raise Exception('No %s+ SDK found' % min_sdk_version)
  64   best_sdk = sorted(sdks, key=parse_version)[0]
  65
```

**Comment by kqyang** [comment]
@ShuaiZhao Where is your 'MacOSX10.14.sdk' located? What is your xcode version? 

Please see the system requirement here: https://github.com/google/shaka-packager/blob/master/docs/source/build_instructions.md#mac-system-requirements.

**Comment by ShuaiZhao** [comment]
@kqyang  xcode version is the latest 10.1

see the following regarding the SDK path:
```
└─[2] <> ls /Library/Developer/CommandLineTools
Library  Packages SDKs     usr

┌─[shuaizhao@SZ-MacB] - [/Library/Developer/CommandLineTools/SDKs] - [2019-02-01 09:49:08]
└─[0] <> ls
MacOSX.sdk      MacOSX10.14.sdk

```

Should be a easy fix.

**Comment by kqyang** [comment]
@ShuaiZhao Did you install the SDK in a custom directory?

I have the same exact xcode version and MaxOSX version but the SDK is installed in '.../Platforms/MacOSX.platform/Developer/SDKs/...', which I believe is the xcode's default.

And yes, we should still update our script to be more robust, so we can handle custom SDK directories, which requires a bit of work though.

**Comment by ShuaiZhao** [comment]
@kqyang actually it is the default path on my machine. I did not remember I have customized anything.  Thanks for addressing this issue. Let me know when you can patch this up. Much appreciated.

Also, would you please share how did you debug shaka in IDE? I am planning to use Clion as the debug IDE. If you were using others, please share the steps. Thanks a lot :)

**Comment by kqyang** [comment]
@ShuaiZhao 

One possible workaround for you for now is to create a symbolic link in '.../Platforms/MacOSX.platform/Developer/SDKs/...'.

> Also, would you please share how did you debug shaka in IDE? I am planning to use Clion as the debug IDE. If you were using others, please share the steps. Thanks a lot :)

I use [cgdb](https://cgdb.github.io/). One of my teammates use [VS code](https://code.visualstudio.com/). No special setups needed, other than compiling the code in Debug mode (`ninja -C out/Debug`).

**Comment by ShuaiZhao** [comment]
@kqyang found a solution https://stackoverflow.com/questions/17980759/xcode-select-active-developer-directory-error

"This problem happens when xcode-select developer directory was pointing to /Library/Developer/CommandLineTools, when a full regular Xcode was required (happens when CommandLineTools are installed after Xcode)"

Now it can be built...Thanks,

**Comment by kqyang** [comment]
Great. Thanks for the update!

**Comment by ShuaiZhao** [comment]
@kqyang  I am curious what kinda IDE do you use to build or you just simply use ninja to build it? most cmake based IDE such as CLION and visual studio can not be used to build shaka packager...I understand we can use vscode others you mentioned for debugging purpose, but it would be nice to know if there is any IDE or steps we can took to build and debug shaka in one IDE... can you share some thoughts..

I am able to open shaka packager use vscode for debugging purpose... But I really hope to find a solution to build and debug shaka packager in one IDE....thanks,

**Comment by kqyang** [comment]
Yes, I use ninja directly. 

> most cmake based IDE such as CLION and visual studio can not be used to build shaka packager

I believe you can use visual studio to build shaka packager, same for CLION. I have not used either one myself, but I believe both provides build command customizations. You should be able to customize the build command to launch 'ninja'.

You can also generate Visual Studio solution files, see https://github.com/google/shaka-packager/issues/426 for details.
