### ISSUE TITLE
Encrypt using IV from key server

### ISSUE THREAD

**Issue by akkermansadriaan** [google/shaka-packager#555]
When encrypting using the --enable_raw_key_encryption option it's possible to supply an IV using --iv. When using the --enable_widevine_encryption to dynamically get the keys from a key server that implements Common Encryption API for Widevine DRM it's not possible to use the --iv option. The documentation on Common Encryption API for Widevine DRM suggests however that the reply from the key server can contain an IV. At the moment this doesn't seem to be implemented. Is it possible to add this?

An example of such a response (with iv): [response.txt](https://github.com/google/shaka-packager/files/2855913/response.txt)

**Comment by kqyang** [comment]
@akkermansadriaan Do you have your own server which implements Widevine Common Encryption API? As far as I know, Widevine's server does not populate IV in the response.

For my own knowledge, what is your use case for fixing the IV instead of letting packager generate random IVs?

> Is it possible to add this?

Definitely.
