### ISSUE TITLE
A way to make ts contain both video and audio

### ISSUE THREAD

**Issue by RyanSiu1995** [google/shaka-packager#556]
## System info
**Operating System**: CentOS 7
**Shaka Packager Version**: 9f2da1e028696ee41e91206b19b3f5612f281c4a

## Issue and steps to reproduce the problem

**Packager Command**: packager \
 'in=h264_baseline_360p_600.mp4,stream=audio,segment_template=audio/$Number$.aac,playlist_name=audio/main.m3u8,hls_group_id=audio,hls_name=ENGLISH' \
 'in=input_text.vtt,stream=text,segment_template=text/$Number$.vtt,playlist_name=text/main.m3u8,hls_group_id=text,hls_name=ENGLISH' \
 'in=h264_baseline_360p_600.mp4,stream=video,segment_template=h264_360p/$Number$.ts,playlist_name=h264_360p/main.m3u8,iframe_playlist_name=h264_360p/iframe.m3u8' \
 'in=h264_main_480p_1000.mp4,stream=video,segment_template=h264_480p/$Number$.ts,playlist_name=h264_480p/main.m3u8,iframe_playlist_name=h264_480p/iframe.m3u8' \
 'in=h264_main_720p_3000.mp4,stream=video,segment_template=h264_720p/$Number$.ts,playlist_name=h264_720p/main.m3u8,iframe_playlist_name=h264_720p/iframe.m3u8' \
 'in=h264_high_1080p_6000.mp4,stream=video,segment_template=h264_1080p/$Number$.ts,playlist_name=h264_1080p/main.m3u8,iframe_playlist_name=h264_1080p/iframe.m3u8' \
  --hls_master_playlist_output h264_master.m3u8

I am running the sample command from the tutorial page. I try to make a server serving them with my own HTTP server. I have observed some out sync problem between the audio and video m3u8.
So I would like to embed my audio track into the ts. Is there any way to do this for Shaka packager?

**Comment by kqyang** [comment]
@RyanSiu1995 We do not support muxing video and audio in the same ts right now. 

> I have observed some out sync problem between the audio and video m3u8.

Can you describe what problem you are seeing? It will not result in A/V out of sync.
