### ISSUE TITLE
Support E-AC-3 in TS

### ISSUE THREAD

**Issue by ysamouhos** [google/shaka-packager#557]
## System info
OS: Ubuntu 18.04.2 LTS 64bit
Packager Version : packager-linux version v2.3.0-5bf8ad5-release

I have been trying to make this stream available but I keep getting unsupported stream type 0x6 

packager-linux in=out.ts -dump_stream_info

Here is the output of mediainfo of the file. 
General
ID                                       : 1 (0x1)
Complete name                            : out.ts
Format                                   : MPEG-TS
File size                                : 4.03 MiB
Duration                                 : 2 min 4 s
Overall bit rate mode                    : Constant
Overall bit rate                         : 271 kb/s

Audio
ID                                       : 297 (0x129)
Menu ID                                  : 1 (0x1)
Format                                   : E-AC-3
Format/Info                              : Enhanced AC-3
Commercial name                          : Dolby Digital Plus
Codec ID                                 : 6
Duration                                 : 2 min 4 s
Bit rate mode                            : Constant
Bit rate                                 : 192 kb/s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 48.0 kHz
Frame rate                               : 31.250 FPS (1536 SPF)
Compression mode                         : Lossy
Stream size                              : 2.86 MiB (71%)
Language                                 : English
Service kind                             : Complete Main

I have read in other threads that E-AC3 is now ok but... 

Any ideas? If you want a sample file I have it available

**Comment by kqyang** [comment]
@ysamouhos Yes, please attach the sample file or send it to shaka-packager-issues@google.com. Thanks.

**Comment by ysamouhos** [comment]
Attached. 


[out-partial.zip](https://github.com/google/shaka-packager/files/2874440/out-partial.zip)

**Comment by kqyang** [comment]
@ysamouhos Thanks!

We don't actually support E-AC-3 in TS yet. E-AC-3 in mp4 is supported.

I'll fix the documentation. 

I have also changed this issue to be a feature request for E-AC-3 in TS. Moved it to backlog for now. Let us know your use case. We'll evaluate if we want to prioritize this feature in the following quarters.

**Comment by ysamouhos** [comment]
ok let me try mp4 instead and I'll let you know. 
Problem is I somehow need a way to extract Teletext or DVB Subs from original TS into something useful like ttml for dash compatibility.

The use case is Original TS -> encode to X number of video resolutions + AAC + E-AC3 + Subs -> encrypt/package dash with packager. ->store to origin server on cdn.

**Comment by ysamouhos** [comment]
ok I switched to mp4 and looks good. I suggest someone also put a Note on README about this in the "Media Containers and codecs" section as well as in the documentation, to avoid misunderstandings.

**Comment by kqyang** [comment]
@ysamouhos Yes, we will correct the documentation.
