### ISSUE TITLE
ninja compile warnings

### ISSUE THREAD

**Issue by ShuaiZhao** [google/shaka-packager#562]
## System info
**Operating System**:
macOS Mojave 10.14.3, xcode Version 10.1 (10B61)

**Shaka Packager Version**: <e.g. v1.6.1, commit SHA etc>
packager version 6d6db76c-debug
Debug build (NDEBUG not #defined)

## Issue and steps to reproduce the problem
Ninja compile show the following warnings...

└─[0] <git:(VRMS-32 74ffcc9c✱) > ninja -C out/Debug
ninja: Entering directory `out/Debug'
[12/21] LINK packed_audio_unittest, POSTBUILDS
ld: warning: directory not found for option '-L../../packager/third_party/libc++-static'
[13/21] LINK webvtt_unittest, POSTBUILDS
ld: warning: directory not found for option '-L../../packager/third_party/libc++-static'
[14/21] LINK mp4_unittest, POSTBUILDS
ld: warning: directory not found for option '-L../../packager/third_party/libc++-static'
[15/21] LINK demuxer_unittest, POSTBUILDS
ld: warning: directory not found for option '-L../../packager/third_party/libc++-static'
[16/21] LINK mp2t_unittest, POSTBUILDS
ld: warning: directory not found for option '-L../../packager/third_party/libc++-static'
[18/21] LINK packager, POSTBUILDS
ld: warning: directory not found for option '-L../../packager/third_party/libc++-static'
[19/21] LINK packager_test, POSTBUILDS
ld: warning: directory not found for option '-L../../packager/third_party/libc++-static'
[20/21] LINK media_event_unittest, POSTBUILDS
ld: warning: directory not found for option '-L../../packager/third_party/libc++-static'
[21/21] STAMP obj/packager_builder_tests.actions_depends.stamp

Those are are all warnings... ideally we should fix those.. any inputs?

Best

**Comment by kqyang** [comment]
@ShuaiZhao I have not seen such warnings. Not sure what is happening. Can you try if you can re-produce the problem if you check out the code to a clean directory?
