### ISSUE TITLE
Packager crashes due to OOM when fed with fading signal (bad data) for a long time

### ISSUE THREAD

**Issue by kqyang** [google/shaka-packager#563]
Moved from https://github.com/google/shaka-packager/issues/533#issuecomment-467508279.

Recaptured the comments here:

https://github.com/google/shaka-packager/issues/533#issuecomment-467508279
Hello,
I am testing a case of antenna fading signal.
The fix in [6d6db76](/google/shaka-packager/commit/6d6db76c80fb31a6e333b4f9d178cb8b0192d477) does retry to delete old segments if it failed before; however, when shaka-packager is fed with corrupted data (due to low signal power for example) for a long enough period of time, old segments get accumulated and the application eventually crashes. If, at any point before the application crashes, “good” data comes in then the function to remove the old segments gets called and the old segments are removed.
It seems like the functions that delete the old segments- RemoveOldSegment for HLS and RemoveSegments for DASH, don't get called when the data is corrupted but new segments are still being added. Is there a reason why those functions don't get called all the time? For example, in packager/hls/base/media_playlist.cc the call to RemoveOldSegment() is at the end of the SlideWindow() function. Why not call it separately before calling SlideWindow() to ensure the cleanup of old files?

I am using an attenuator to reproduce the issue. The attenuator receives ATSC data and sends it to an ATSC RF receiver. The data is then turns into IP streams, fed into shaka packger and eventually being streamed out. I raise the level of the attenuator until the data is affected by it (can visually see pixelation) and let it run.

https://github.com/google/shaka-packager/issues/533#issuecomment-467655065
@ohMoshko Interesting. I admitted that we did not take data corruption into consideration when designing this solution.

Do you mind describing a little bit more on what is happening? For example, what does packager see for "bad" data? Valid TS streams with incorrect timestamps?

> the application eventually crashes

What is causing the crash? Out of storage space? Out of memory?

> Is there a reason why those functions don't get called all the time?

I do not know. One possibility is that the timestamp is corrupted causing SlideWindow() to exist early: https://github.com/google/shaka-packager/blob/master/packager/hls/base/media_playlist.cc#L581; it might also be possible that MediaPlaylist::SlideWindow() or MediaPlaylist::AddSegmentInfoEntry() is not invoked at all.

> Why not call it separately before calling SlideWindow() to ensure the cleanup of old files?

The files to be deleted are stored in `segments_to_be_removed_`, which is only updated when SlideWindow() is called, so `segments_to_be_removed_` does not grow if SlideWindow() is not called.

https://github.com/google/shaka-packager/issues/533#issuecomment-468325864
I am feeding the packager with different ATSC services. The services that are affected by the low signal power start accumulating .mp4 files (audio and video). The services’ media directory gets to around ~900MB and then the Linux OOM_killer is invoked and kills my app that is running shaka-packager:
[oom_killer_shaka_log.txt](https://github.com/google/shaka-packager/files/2915640/oom_killer_shaka_log.txt)

I can confirm that when the signal is fading, MediaPlaylist::SlideWindow() and MediaPlaylist::AddSegmentInfoEntry() are invoked but the timestamp is probably corrupted causing SlideWindow() to exit early:
https://github.com/google/shaka-packager/blob/master/packager/hls/base/media_playlist.cc#L581
If the signal is "good" again, SlideWindow() does not exit at the above if statement and the RemoveOldSegments() function is called and the old segments are removed correctly.
So I think that it shaka sees a bad data as a valid TS stream with incorrect timestamps.
When the function exits, current_play_time is not 0. It is usually between 1 and 14.
I analyzed the MPEG TS using tsDuck and observed large Discontinuities numbers for some of the PIDs (as expected).
If SlideWindow() continuously exits early, the media folder gets bigger and bigger and eventually the OOM_killer is invoked.

I can record the TS and send it to you if that would help.

**Comment by ohMoshko** [comment]
@kqyang first, thanks for the quick response. I wanted to ask you what would be the best way to send you the recorded stream?

**Comment by kqyang** [comment]
@ohMoshko You can upload it to a cloud storage and attach the link here. If you are not comfortable with sharing it publicly, you can email it to shaka-packager-issues@google.com.

**Comment by ohMoshko** [comment]
@kqyang I sent the recorded stream to: shaka-packager-issues@google.com.

**Comment by ohMoshko** [comment]
@kqyang I am trying to understand how is the start_time calculated exactly and what is the relationship between the stream's timestamp and the segment's start time. Can you please shed some light on those two topics?
Thanks!

**Comment by kqyang** [comment]
Thanks for the sample. I'll look into it some time this week.

Re https://github.com/google/shaka-packager/issues/563#issuecomment-469782024, the segment's start time is the earliest timestamp of the samples in the segment.

**Comment by kqyang** [comment]
Finally had some time to look into it today. The problem happens because the timestamp rewinds 1356.27 to 0. Our current sliding window logic is based on the timestamp. Thus all the segments would remain in the time shift buffer until timestamp reaches 1356.27 again. That is why the files are not removed and the memory usage keeps increasing until OOM.

I am working on a fix and will push it out soon.

**Comment by ohMoshko** [comment]
@kqyang sounds good. Thank you!

**Comment by ohMoshko** [comment]
@kqyang we tested it and it seems like the problem is solved. Thank you for the fix.

**Comment by kqyang** [comment]
You are welcome. Thanks for the verification.
