### ISSUE TITLE
generation  of independent segements in HLS

### ISSUE THREAD

**Issue by Jagansivam28** [google/shaka-packager#564]
## System info
**Operating System**: Ubuntu 18.04>
**Shaka Packager Version**: v2.3.0-5bf8ad5-release

## Issue and steps to reproduce the problem

hello ,
 i am new to shaka packager ..i need to generate independent segments In HLS using #EXT-X-INDEPENDENT-SEGMENTS tag (https://tools.ietf.org/html/rfc8216#page-35)(4.3.5.1) .is there anyway to insert these hls tags  in  shaka packager .
thank you !

**Comment by kqyang** [comment]
Shaka Packager does not insert this tag right now, but it should. We'll look into it.

**Comment by Jagansivam28** [comment]
ok thank you

**Comment by Jagansivam28** [comment]
can you tell me  where to modify the code to use these tag ( #EXT-X-INDEPENDENT-SEGMENTS) in shaka packager ?

**Comment by kqyang** [comment]
@Jagansivam28 Sure. A quick and dirty solution is to append the tag before this line https://github.com/google/shaka-packager/blob/master/packager/hls/base/master_playlist.cc#L444. 

A cleaner solution I think is to add a new argument to MasterPlaylist constructor to indicate whether the streams having independent segments, which can be passed down from earlier pipeline.

**Comment by Jagansivam28** [comment]
thank you ! i tried what you said . i modify the code . now i am able to insert the tag in master playlist.but still the segments are dependent. can u help me ?

**Comment by kqyang** [comment]
@Jagansivam28 Shaka Packager segments at key frame by default, i.e. in https://google.github.io/shaka-packager/html/documentation.html#chunking-options, `--segment_sap_aligned` and `--fragment_sap_aligned` are enabled by default. For a closed-GOP stream, the generated segments are independent.

Can you clarify why you think the segments are dependent?

**Comment by Jagansivam28** [comment]
well ...i want to replace one of the .ts files ( hls  segments) with my own generated .ts file. so the segments should be independent  to play the video without any interruptions .if the segments are dependent it won't work.  this is my need  can you help me ?

**Comment by Jagansivam28** [comment]
is replacing .ts files  with own generated .ts file   possible ?

**Comment by Jagansivam28** [comment]
it is  possible to replace the .ts files ?

**Comment by kqyang** [comment]
So you generate the segments yourself and want to use Shaka Packager to generate HLS playlists only? No, we do not support this use case right now. You can try to integrate Shaka Packager library and use https://github.com/google/shaka-packager/blob/master/packager/hls/base/simple_hls_notifier.h directly to generate the playlists.

> the segments should be independent to play the video without any interruptions .if the segments are dependent it won't work. this is my need can you help me ?

The segments generated by Shaka Packager should be independent. Let's know if it is not. We will look into it if that is the case.

**Comment by cbrown30309** [comment]
Has the #EXT-X-INDEPENDENT-SEGMENTS issue been resolved?

**Comment by kqyang** [comment]
@cbrown30309 Not yet. It should be safe to just insert the tag as Shaka Packager generates independent segments by default.

**Comment by JanSunavec** [comment]
There is no support for independent segmentations. Only when you use ts files. For m4s shaka packager use ext-x-map and it's not possible combine it with independent segmentation tag.
