### ISSUE TITLE
Feature Request - DVS Audio MPEG-DASH

### ISSUE THREAD

**Issue by cgp1081** [google/shaka-packager#565]
Feature request for support of DVS Accessibility audio in DASH.  The ability to specify an audio track for DVS signaling

Dash variant of feature: https://github.com/google/shaka-packager/issues/404

`<Accessibility
  schemeIdUri="urn:tva:metadata:cs:AudioPurposeCS:2007"
  value="1">
</Accessibility>
<Role
    schemeIdUri="urn:mpeg:dash:role:2011"
    value="alternate">
</Role>`

https://www.etsi.org/deliver/etsi_ts/103200_103299/103285/01.02.01_60/ts_103285v010201p.pdf
p. 29

**Comment by kqyang** [comment]
@cgp1081 We can add options to allow users to specify role and accessibility. Will that work for you?

**Comment by cgp1081** [comment]
Yes @kqyang , thank you!

**Comment by kqyang** [comment]
@cgp1081 Let us know if it works for you.

**Comment by cgp1081** [comment]
@kqyang  This is great, will get some tests going soon.

**Comment by jigneshdhruv** [comment]
@kqyang After checking out the latest shaka packager code, we are having playback issue with HLS manifest. On further debugging we found that "BANDWIDTH" is assigned a value of '0' in EXT-X-I-FRAME-STREAM-INF tag in master manifest file.

For eg in master HLS manifest we see:
#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=0,AVERAGE-BANDWIDTH=418540,CODECS="avc1.640028",RESOLUTION=1280x720,URI="378_AA_6CH_30M_1698529_3000/stream_iframe.m3u8"
#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=0,AVERAGE-BANDWIDTH=276336,CODECS="avc1.640028",RESOLUTION=1024x576,URI="378_AA_6CH_30M_1698529_2100/stream_iframe.m3u8"

Older versions of shaka packager represents correct value for BANDWIDTH. 

Can you please look into this?

**Comment by kqyang** [comment]
@jigneshdhruv I have filed a separate issue at https://github.com/google/shaka-packager/issues/610. It does look like a bug. We'll look into it ASAP.
