### ISSUE TITLE
Input mpegts over UDP stream with low frame count does not produce segments

### ISSUE THREAD

**Issue by idokasher** [google/shaka-packager#566]
## System info
**Operating System**: macOS Mujave
**Shaka Packager Version**: packager-osx version v2.2.0-9e9833e-release

## Issue and steps to reproduce the problem
I have a stream of incoming JPEG frames that I would like to stream as a movie.
I try to do so by repeatedly invoking ffmpeg on incoming chunks of JPEGs and transporting them to the packager over UDP.

The packager doesn't create an .mpd and .m4s unless a sufficient number of frames is transported.

Is there an option to flush earlier?

Thanks!

**Packager Command**:
packager input=udp://127.0.0.1:40000,stream=video,init_segment=panic1/init.mp4,segment_template=out/\$Number\$.m4s -mpd_output out/manifest.mpd

Extra steps to reproduce the problem?
(1)
I am using ffmpeg to stream them over UDP to the packager:
ffmpeg -f image2 -framerate 15 -i sample%04d.jpg -vcodec libx264 -f mpegts udp://127.0.0.1:40000

Where the number of JPEGs is about 80.

**Comment by kqyang** [comment]
@idokasher Are you trying to create a live stream? If not, you can generate a static ts file using ffmpeg and then feed the static file to packager.

> Is there an option to flush earlier?

Yes, you can adjust segment_duration, e.g. set it to 1s: `--segment_duration=1`.

**Comment by idokasher** [comment]
Thanks for the quick reply.
Yes, I am trying to create a live stream.

Reducing segment duration to 1 helped, but it required more than 80 frames (frame rate 15) to flush the first segment. Can you refer me to where in the code the decision to flush due to crossing the threshold is being made?

**Comment by kqyang** [comment]
Can you check the duration of the first segment? By default, packager segments at GOP boundary. FFmpeg has a big GOP by default. 

Can you try to set the GOP at 1 second, i.e. 15 (i.e. `-g <integer>`) as well?

**Comment by idokasher** [comment]
Sorry for the late reply.
I didn't have the chance to play with the GOP, and I am not sure when I will at the moment. Let's close this for now. Thanks for the help.
