### ISSUE TITLE
don´t save files in output directory config

### ISSUE THREAD

**Issue by JoeXavi** [google/shaka-packager#567]
## System info
**Operating System**: Centos 7
**Shaka Packager Version**: packager version a529d4677d-release

## Issue and steps to reproduce the problem
I execute the command in any folder, but the output files always are saved in another folder. how config the output folder? 
**Packager Command**:
packager  --segment_duration 2 'in=udp://ip:19360,stream=audio,segment_template=audio/$Number$.aac,playlist_name=audio/main.m3u8,hls_group_id=audio,hls_name=SPANISH' 'in=udp://ip:19360,stream=video,segment_template=h264_360p/$Number$.ts,playlist_name=h264_360p/main.m3u8,iframe_playlist_name=h264_360p/iframe.m3u8' 'in=udp://ip:19720,stream=video,segment_template=h264_720p/$Number$.ts,playlist_name=h264_720p/main.m3u8,iframe_playlist_name=h264_720p/iframe.m3u8'  --hls_master_playlist_output h264_master.m3u8  --hls_playlist_type LIVE
Extra steps to reproduce the problem?
(1) i tried to change folder on "--hls_master_playlist_output live/264_master.m3u8" or "--hls_master_playlist_output xxx/264_master.m3u8" but it does not work
(2) 

What is the expected result?
I would like to customize the output directory
What happens instead?

<Please attach the input files or email to shaka-packager-issues@google.com.>
<Please provide any additional information below.>

**Comment by kqyang** [comment]
For output files, are you talking about media files or playlist files? 

For media files, the path is relative to the current directory, e.g. you can do: segment_template=live/h264_720p/.... 

For playlist files, the path is relative to master playlist output directory. Sorry for the inconsistency to media files.

**Comment by JoeXavi** [comment]
Thank you for help me... the truth is that the packer was working previously and if I try to execute the command again fail

**Comment by kqyang** [comment]
@JoeXavi I am confused. 

> the truth is that the packer was working previously and if I try to execute the command again fail

Do you mean that it works as expected when running the below command for the first time,

```bash
packager --segment_duration 2 'in=udp://ip:19360,stream=audio,segment_template=audio/$Number$.aac,playlist_name=audio/main.m3u8,hls_group_id=audio,hls_name=SPANISH' 'in=udp://ip:19360,stream=video,segment_template=h264_360p/$Number$.ts,playlist_name=h264_360p/main.m3u8,iframe_playlist_name=h264_360p/iframe.m3u8' 'in=udp://ip:19720,stream=video,segment_template=h264_720p/$Number$.ts,playlist_name=h264_720p/main.m3u8,iframe_playlist_name=h264_720p/iframe.m3u8' --hls_master_playlist_output h264_master.m3u8 --hls_playlist_type LIVE
```

And it fails if you run it again? Is the same problem you mentioned in the initial report? Or is it a different problem?

Can you clarify?
