### ISSUE TITLE
Raw key, fairplay issue

### ISSUE THREAD

**Issue by welzon** [google/shaka-packager#568]
Dear Support,

## System info
Linux 4.9.0-6-amd64
shaka-packager version 26997bb-release

## Issue and steps to reproduce the problem

The command I tried:

> ../packager \\
> in=video/proba480.mp4,stream=audio,output=audio.mp4,playlist_name=audio.m3u8,hls_group_id=audio,hls_name=ENGLISH \\
>   in=video/proba480.mp4,stream=video,output=480.mp4,playlist_name=h264_480.m3u8 \\
>   in=video/proba324.mp4,stream=video,output=324.mp4,playlist_name=h264_324.m3u8 \\
>   in=video/proba216.mp4,stream=video,output=216.mp4,playlist_name=h264_216.m3u8 \\
>   --protection_scheme cbcs \\
>   --enable_raw_key_encryption \\
>   --keys label=:key_id=xxxx:key=xxxx \\
>   --pssh 00000020707373680000000029701FE43CC74A348C5BAE90C7439A4700000000 \\
>   --clear_lead=0 \\
>   --hls_master_playlist_output h264_master.m3u8 \\
>   --hls_key_uri skd://xxxx

I got the pssh from ticket #420, hopefully It is correct.

Do you see any problems with my command?

This is the result (one media playlist file head):

> #EXTM3U
> #EXT-X-VERSION:6
> #\# Generated with https://github.com/google/shaka-packager version 26997bb-release
> #EXT-X-TARGETDURATION:11
> #EXT-X-PLAYLIST-TYPE:VOD
> #EXT-X-MAP:URI="480.mp4",BYTERANGE="937@0"
> #EXT-X-KEY:METHOD=SAMPLE-AES,URI="skd://xxxx",KEYFORMATVERSIONS="1",KEYFORMAT="com.apple.streamingkeydelivery"

I can't play master playlist file. The media playlist files are starting, however the picture is crashed (green and pink picture changing). There is no voice also.  

What is the expected result?
I'm not too familiar with fairplay, but I read documentation and some issues, I would expect a correct HLS stream with fariplay.

If you can't see any problem in the command, then maybe the key uri/ key ID or the player make this issue.

If you have any advice or if you need any more information please let me know.

Best regards

**Comment by kqyang** [comment]
@welzon Are you using your own fairplay license server? Have you verified that it is working? And which platform are you testing the playback on?

**Comment by welzon** [comment]
We are currently using a multi DRM vendor. We can provide widevine and fairplay protected content with another packager, but I would like to use Shaka.
The vendor sent us the 'widevine_pssh_data_pb2' file, the key, the content ID-s and the key_uri. I can create widevine protected content with these informations, but fairplay is not woking right now.

So the license server should be okay. For testing I am using a native player. Maybe it could be the problem. Can you suggest another player, where I can test it properly?

All in all do you belive that the command is fine, and I should not add anything else to it, just verify that every key id is working?

**Comment by kqyang** [comment]
> For testing I am using a native player. Maybe it could be the problem. Can you suggest another player, where I can test it properly?

What do you mean by native player? I think you can use Safari to test the stream. There are instructions on how to do that in Fairplay server SDK provided by Apple.

> All in all do you belive that the command is fine, and I should not add anything else to it, just verify that every key id is working?

Yes, the command looks good to me. The fairplay PSSH is only used to signal to the internal pipeline that a fairplay key format needs to be indicated in the playlist, which works from the playlist you included. 

Make sure the key uri is correct. It should point to the key uri for the key id you used to encrypt the content.

**Comment by welzon** [comment]
Sorry for the late answer, but I had no time to work with it. However your explonation is pretty clear, I am going to look after it. Right now I close the ticket, because it is almost certainly not shaka packager issue.
Thanks for your help!
