### ISSUE TITLE
independent segments

### ISSUE THREAD

**Issue by manikandan97** [google/shaka-packager#569]
## System info
**Operating System**:ubuntu 18.04
Hi , is there any way to produce independent segments in hls using shaka packager ?

**Comment by kqyang** [comment]
@manikandan97 Are you referring to the #EXT-X-INDEPENDENT-SEGMENTS tag mentioned in #564 or something else?

**Comment by manikandan97** [comment]
yes

**Comment by kqyang** [comment]
Ok, let's track the problem there instead.
