### ISSUE TITLE
Feature request: Transmux the stream in different codecs and sizes

### ISSUE THREAD

**Issue by aminyazdanpanah** [google/shaka-packager#570]
Hi there,

Firstly, thank you for the great library!

Secondly, I have a feature request for transmuxing the streams from one codec and size to another codec and size.

For Instance, my video codec and size of my video are "H264" and "1080x720" respectively. 
Something like this:
``` bash
$ packager in=h264_720.mp4,stream=video,codec=h265,size=640x480,out=h265_480.mp4 
```

**Comment by kqyang** [comment]
@aminyazdanpanah I am glad that you like this project. The feature request involves transcoding. We have no plan to support it right now. You can try FFmpeg, which is a great tool for this use case.
