### ISSUE TITLE
Single media Multi-DRM package

### ISSUE THREAD

**Issue by Jason239** [google/shaka-packager#572]
Hi.

I want to create content that has multi-drm(PlayReady, Widevine, FPS) applied and consists of single media file.
So I mean, I tried to make a content in the form of having a dash and hls manifest file in a single media(segmented or not) file.
But for FPS, the encryption scheme should be cbcs, and the others are not.
I know that AES-CBC applies to HLS-FPS and AES-CTR applies to MPEG-DASH originally.
But aren't you support CMAF ?
If supported, Is there any command to package as CMAF?

**Comment by kqyang** [comment]
@Jason239 CMAF supports two encryption modes: cbcs (uses AES-CBC) and cenc (uses AES-CTR). You cannot mix cbcs and cenc in a single media.

All the three DRMs you mentioned (Widevine, PlayReady, FairPlay) now supports CMAF with cbcs. You can generate a single media using CMAF with cbcs. There isno special command. You just need to set `protection_scheme` to `cbcs` and set the output to mp4 files. Note that it will not work on old devices and old versions of Chrome / Edge.

Does that answer your question?

**Comment by Jason239** [comment]
Yes, thanks. I'll try it.

**Comment by Jason239** [comment]
Ah, I have one more.
Then how about subtitle's form?
Is it possible to make both segmented or single type outputs by receiving inputs in VTT format?

**Comment by kqyang** [comment]
@Jason239 Yes, I think you can. What is the use case for that?

**Comment by Jason239** [comment]
When I tried, VTT input is possible, but output is only possible with m4s or mp4.
For VTT output, Segmented text output with MPD was impossible, and single text output with HLS was also impossible.
Am I right ?

**Comment by kqyang** [comment]
I see what you meant now. I misunderstood your question earlier.

> For VTT output, Segmented text output with MPD(DASH) was impossible, and single text output with HLS was also impossible.

Unfortunately it is a limitation in DASH and HLS.

> So I can only use m4s or mp4 for output format.

I am not sure if it works in all HLS players though.

**Comment by Jason239** [comment]
Yes, actually I just tried to playback, but subtitles were not seen on ios media player and Bitmovin player on Safari.
Do you know what kind of HLS player can work ?

**Comment by kqyang** [comment]
I think it is supported in Shaka Player.

**Comment by Jason239** [comment]
I tested on various players(Bitmovin, Dash, Shaka, MS, ... etc) but couldn't see the subtitle on every player.
Even though the m4s, mp4 subtitle files are downloaded, but not displayed on the screen. It's weird..
Maybe the subtitles in the mp4 container don't seem to be supported in HLS streaming.

If you want to test, you can use the stream below. 
https://mpdsample.s3.amazonaws.com/SHARE/cmaf_nondrm_text/master.m3u8
https://mpdsample.s3.amazonaws.com/SHARE/cmaf_nondrm_text_single/master.m3u8

1. So I wonder why you don't support single VTT file output for HLS. Is there any specific reason?

2. This is another question. 
Don't you need to use extensions like .cmfv(for video) or .cmfa(for audio) when doing CMAF packaging in Shaka? I ask you because this extensions are mentioned in some CMAF document.

**Comment by kqyang** [comment]
> So I wonder why you don't support single VTT file output for HLS. Is there any specific reason?

It is not supported by HLS specification. In fact, the only supported WebVTT format in HLS is segmented WebVTT text: https://tools.ietf.org/html/rfc8216#section-3.5.

> Don't you need to use extensions like .cmfv(for video) or .cmfa(for audio) when doing CMAF packaging in Shaka?

Good question! Looks like we don't allow these extensions right now. We should add support for that. Can you file a separate issue for that? 

We won't enforce it in Shaka Packager, i.e. we will still leave it to the users to decide what extension they want to use.

**Comment by Jason239** [comment]
> Can you file a separate issue for that?
Yes, I did it.

> It is not supported by HLS specification. In fact, the only supported WebVTT format in HLS is segmented WebVTT text: https://tools.ietf.org/html/rfc8216#section-3.5.
Well, I think it doesn't seem to mean that we can't use single WebVTT format.
In fact, in the case of the following content, the content is packaged with subtitles in single vtt format. Playback also works well.
https://mpdsample.s3.amazonaws.com/SHARE/vtt_singleoutput_hls/master.m3u8
If the packaging with output subtitle in single vtt format is supported as the example above, the playback issue could be resolved, I think.

**Comment by kqyang** [comment]
@Jason239 Good point! Thanks for pointing that out. Yes, we should support that. Can you file a separate bug? We'd prefer not to mix different issues in the same issue.

**Comment by Jason239** [comment]
I filed it. So I'm gonna close this issue.
Thank you !
