### ISSUE TITLE
Support for packaging with CMAF brands

### ISSUE THREAD

**Issue by Jason239** [google/shaka-packager#574]
I think extensions like cmfv(video), cmfa(audio) and cmft(text) need to be added.
These are mentioned in [this document](https://mpeg.chiariglione.org/standards/mpeg-a/common-media-application-format/text-isoiec-cd-23000-19-common-media-application).

**Comment by ShuaiZhao** [comment]
@kqyang any idea when support with CMAF being available?

**Comment by kqyang** [comment]
@Jason239 @ShuaiZhao Shaka Packager now supports CMAF file extensions.
