### ISSUE TITLE
shaka packager and L1 vs L3 security level on widevine during packaging

### ISSUE THREAD

**Issue by sammirata** [google/shaka-packager#577]
We have a working implementation of Widevine DRM with Dash using shaka packager. Now, when we try the same encrypted streams with Samsung Galaxy S8 after an upgrade to Android 9, the video would not play anymore.
We had to lower the security level to L3 on the player to make it work even though the device is clearly L1 capable.
Is there anything that needs to be done during packaging to make it L1 compliant? Perhaps on the manifest or on the encryption process?

**Comment by kqyang** [comment]
Sorry for the late reply.

> Is there anything that needs to be done during packaging to make it L1 compliant? Perhaps on the manifest or on the encryption process?

You can configure the license policy in the license server. Your problem does not look like a license policy problem to me though, as L3 license works on L1 CDM (L1 license does not work on L3 CDM).

Your problem looks like a device problem. Looks like somehow L1 CDM is broken after device update. If you can get "adb logcat", I can get my colleagues in Android CDM team to take a look.
