### ISSUE TITLE
Video is Playing but no Sound

### ISSUE THREAD

**Issue by thexgreenfire** [google/shaka-packager#578]
## System info
**Operating System**: Windows 7 Ultimate 64 bit
**Shaka Packager Version**: v2.3.0-5bf8ad5ed5-release

(1) I have video encoded to x264 and the audio is in AAC
(2) Both video and audio remuxed into one file
(3) I use below script to generate .mpd file

`
packager ^
in="E:\Encoded\Suzzanna.mp4",stream=video,output="E:\Encoded\DASH\Suzzanna-DASH.mp4" ^
--mpd_output "E:\Encoded\DASH\Suzzanna-DASH.mpd"
`

When inserting the .mpd file into player, the video is playing but with no sound. Is that really i need to separate video and audio and should not remux them? Or is there any additional command i have to use?

**Comment by rkuroiwa** [comment]
Add another `in=` with `stream=audio`, or specify the audio stream ID `stream=1` (assuming that audio is at stream 1).

Example:
`in="E:\Encoded\Suzzanna.mp4",stream=audio,output="E:\Encoded\DASH\Suzzanna-DASH-audio.mp4"`

Like in this [first example](https://google.github.io/shaka-packager/html/tutorials/dash.html#examples)

[See here for finding out the stream ID](https://google.github.io/shaka-packager/html/tutorials/basic_usage.html#media-file-analysis).

**Comment by thexgreenfire** [comment]
rkuroiwa solution is working, but how if using 2 audios?
This code plays video 144p and 1080p all with 192 kbps audio, what i need is if video 144p selected then it will play 32 kbps audio, and if 1080p video selected it will play 192 kbps audio

`packager ^
in="E:\Encoded\Suzzanna-144p.mp4",stream=audio,output="E:\Encoded\DASH\Suzzanna-a32.mp4" ^
in="E:\Encoded\Suzzanna-1080p.mp4",stream=audio,output="E:\Encoded\DASH\Suzzanna-a192.mp4" ^
in="E:\Encoded\Suzzanna-144p.mp4",stream=video,output="E:\Encoded\DASH\Suzzanna-v144p.mp4" ^
in="E:\Encoded\Suzzanna-1080p.mp4",stream=video,output="E:\Encoded\DASH\Suzzanna-v1080p.mp4" ^
--mpd_output "E:\Encoded\DASH\Suzzanna.mpd"`

**Comment by kqyang** [comment]
That can be handled in the player. We don't support muxing audio and video in the output right now.
