### ISSUE TITLE
Ignore unsupported MPEG2TS stream type 0x2

### ISSUE THREAD

**Issue by arodrigoca** [google/shaka-packager#579]
## System info
**Operating System**: Ubuntu 18.04
**Shaka Packager Version**: Latest
**FFmpeg version**: 3.4.4

## Issue and steps to reproduce the problem

Shaka packager throws an error an doesn't produce any output files when piping or using udp from ffmpeg using MPEGTS container.

`ffmpeg -video_size 1600x900 -framerate 25 -f x11grab -i :0.0 -f mpegts udp://127.0.0.1:1025`

`sudo ./packager-linux 'in=udp://127.0.0.1:1025,stream=video,init_segment=init.mp4,segment_template=segment_$Number$.m4s' --mpd_output /var/www/html/dashcast.mpd --min_buffer_time 0 --minimum_update_period 500 --suggested_presentation_delay 0 --time_shift_buffer_depth 10 --allow_approximate_segment_timeline --segment_duration 2 --fragment_duration 1`

What is the expected result?

Shaka packager should output mpd and media segments.

What happens instead?

Packager throws an error when receiving the stream:

`[0405/201729:ERROR:mp2t_media_parser.cc(310)] Ignore unsupported MPEG2TS stream type 0x2`

**Comment by kqyang** [comment]
@arodrigoca MPEG2TS stream type 0x2 is MPEG2 video (H262), which we do not support in Shaka Packager. In fact, it is not supported in most browsers. You can pass the stream to FFmpeg first to transcode to H264 before parsing to Shaka Packager: https://google.github.io/shaka-packager/html/tutorials/ffmpeg_piping.html.

**Comment by arodrigoca** [comment]
@kqyang I see, I assumed for some reason that ffmpeg default codec for ts is H264, but it is clearly not. Thank you.

**Comment by kqyang** [comment]
No problem. FFmpeg's default codec seems to be different for different containers. H264 is not set as the default for TS container might be because of the license cost associated with H264.
