### ISSUE TITLE
cannot play CMAF packaged media with Chrome on android

### ISSUE THREAD

**Issue by bricemiramont** [google/shaka-packager#580]
## System info
**Operating System**: 
android Pie and android Oreo

**Shaka Packager Version**:
2.3

## Issue and steps to reproduce the problem
Media is packaged in CMAF with custom keys so we can use widevine and fairplay license servers.
Media plays fine with : 
iOS App  (hls)
iOS Safari (hls)
Macos Chrome (dash)
Macos Safari (hls)

Does not play on
Chrome android

**Packager Command**:
packager \
    in=/media/${audio_file}.mp4,stream=audio,drm_label=AUDIO,output=/media/${filename}/${filename}_a1_en_media.mp4,playlist_name=${filename}_a1_en_media.m3u8,hls_group_id=audio_1,hls_name=English \
    in=/media/${movie_file}.mp4,stream=video,drm_label=HD,output=/media/${filename}/${filename}_v1_media.mp4,playlist_name=${filename}_v1_media.m3u8,iframe_playlist_name=${filename}_v1_iframe.m3u8 \
    --default_language en \
    --protection_scheme cbcs \
    --enable_raw_key_encryption \
    --keys label=AUDIO:key_id=$au_key_id:key=$au_key,label=HD:key_id=$hd_key_id:key=$hd_key \
    --iv $iv \
    --pssh $pssh_widevine$pssh_fairplay \
    --hls_master_playlist_output /media/${filename}/${filename}_encrypted.m3u8 \
    --mpd_output /media/${filename}/${filename}_encrypted.mpd \
    --hls_playlist_type VOD

Extra steps to reproduce the problem?
(1) pssh are generated beforehand:
pssh_widevine=$(/usr/local/bin/pssh-box --widevine-system-id --content-id $contentID --provider $signer --protection-scheme cbcs --key-id $au_key_id --key-id $hd_key_id --hex)
pssh_fairplay=$(/usr/local/bin/pssh-box --system-id 29701FE43CC74A348C5BAE90C7439A47 --key-id $au_key_id --key-id $hd_key_id --hex)
(2)

What is the expected result?
Media should play in chrome on android. But I do not know whether the dash or hls should be used with chrome on android for the CMAF encrypted media.
mpd read fine on macOS but not on android and it seems that CMAF is supported only with HSL (widevine DRM for HLS document)

What happens instead?
Media does not play. 

Video player used is video.js with video-contrib-dash.js

![error_media](https://user-images.githubusercontent.com/35682863/55890202-909c9d00-5bb2-11e9-971f-b4bcc2203047.png)

**Comment by kqyang** [comment]
@bricemiramont This is a known issue with Chrome on Android. It is expected to be supported in Chrome 76. With that supported, you'll be able to use either HLS or DASH as long as it is supported in your player.

See https://bugs.chromium.org/p/chromium/issues/detail?id=813845 for details.

**Comment by kqyang** [comment]
Looks like it will be supported in Chrome 75.
