### ISSUE TITLE
Incorrect bandwidth caluclation for DASH manifest

### ISSUE THREAD

**Issue by Sidewinder53** [google/shaka-packager#581]
## System info
**Operating System**: Windows Server 2012 R2 Datacenter (Version 6.3, Build 9600)
**Shaka Packager Version**: v2.3.0-5bf8ad5ed5-release

## Issue and steps to reproduce the problem

**Packager Command**:
```
packager.exe `
in=newscast_01_.vtt,stream=text,out=t-english.vtt `
in=a-128k-opus.webm,stream=audio,out=ea-128k-opus.webm,drm_label=AUDIO `
in=a-128k-aac.mp4,stream=audio,out=ea-128k-aac.mp4,drm_label=AUDIO `
in=v-480x240-200k.webm,stream=video,out=ev-480x240-200k.webm,drm_label=VIDEO `
in=v-720x360-400k.webm,stream=video,out=ev-720x360-400k.webm,drm_label=VIDEO `
in=v-960x480-900k.webm,stream=video,out=ev-960x480-900k.webm,drm_label=VIDEO `
in=v-1200x600-1250k.webm,stream=video,out=ev-1200x600-1250k.webm,drm_label=VIDEO `
in=v-1440x720-1600k.webm,stream=video,out=ev-1440x720-1600k.webm,drm_label=VIDEO `
in=v-480x240-350k.mp4,stream=video,out=ev-480x240-350k.mp4,drm_label=VIDEO `
in=v-720x360-700k.mp4,stream=video,out=ev-720x360-700k.mp4,drm_label=VIDEO `
in=v-960x480-1300k.mp4,stream=video,out=ev-960x480-1300k.mp4,drm_label=VIDEO `
in=v-1200x600-1600k.mp4,stream=video,out=ev-1200x600-1600k.mp4,drm_label=VIDEO `
in=v-1440x720-2200k.mp4,stream=video,out=ev-1440x720-2200k.mp4,drm_label=VIDEO `
--enable_raw_key_encryption --keys ` 
label=AUDIO:key_id=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx:key=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx, `
label=VIDEO:key_id=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx:key=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx `
--mpd_output m-main.mpd
```
(Please ignore the backticks at line end, command is executed in a PowerShell environment)

**What is the expected result?**

Bandwidth in DASH manifest for input file `v-1440x720-1600k.webm` should be larger than bandwidth for `v-1200x600-1250k.webm`.

**What happens instead?**

Instead, bandwidth for the larger file is smaller:
```
<Representation id="3" bandwidth="2877990" codecs="vp09.00.31.08.01.02.02.02.00" mimeType="video/webm" sar="1:1" width="1200" height="600">
  <BaseURL>ev-1200x600-1250k.webm</BaseURL>
  <SegmentBase indexRange="361-1070" timescale="1000000">
    <Initialization range="0-360"/>
  </SegmentBase>
</Representation>
<Representation id="8" bandwidth="2789699" codecs="vp09.00.40.08.01.02.02.02.00" mimeType="video/webm" sar="1:1" width="1440" height="720">
  <BaseURL>ev-1440x720-1600k.webm</BaseURL>
  <SegmentBase indexRange="361-1073" timescale="1000000">
    <Initialization range="0-360"/>
  </SegmentBase>
</Representation>
```

**v-1200x600-1250k.webm transcode commands**
```
ffmpeg -i newscast_01_.mkv -r 30 -vf scale=1200:600 -b:v 1250k -minrate 625k -maxrate 2500k -g 60 -quality best -crf 31 -c:v libvpx-vp9 -an -dash 1 -pass 1 -speed 4 -f webm -y NUL
ffmpeg -i newscast_01_.mkv -r 30 -vf scale=1200:600 -b:v 1250k -minrate 625k -maxrate 2500k -g 60 -quality best -crf 31 -c:v libvpx-vp9 -an -dash 1 -pass 2 -speed 1 -y v-1200x600-1250k.webm
```
**v-1440x720-1600k.webm transcode commands**
```
ffmpeg -i newscast_01_.mkv -r 30 -vf scale=1440:720 -b:v 1600k -minrate 800k -maxrate 3200k -g 60 -quality best -crf 31 -c:v libvpx-vp9 -an -dash 1 -pass 1 -speed 4 -f webm -y NUL
ffmpeg -i newscast_01_.mkv -r 30 -vf scale=1440:720 -b:v 1600k -minrate 800k -maxrate 3200k -g 60 -quality best -crf 31 -c:v libvpx-vp9 -an -dash 1 -pass 2 -speed 1 -y v-1440x720-1600k.webm
```

MediaInfo of the video files in question:
[v-1200x600-1250k.webm.MediaInfo.txt](https://github.com/google/shaka-packager/files/3103627/v-1200x600-1250k.webm.MediaInfo.txt)
[v-1440x720-1600k.webm.MediaInfo.txt](https://github.com/google/shaka-packager/files/3103628/v-1440x720-1600k.webm.MediaInfo.txt)

I'm not sure if I am missing something, or if the inner workings of the bandwidth calculation process are just way more complex. Maybe someone can explain this? Right now the incorrect bandwidth values tamper with DASH playback logic and force the 600p stream to be favored over the 720p stream.

I would really appreciated if someone could help me out. Thanks!

**Comment by kqyang** [comment]
@Sidewinder53 Can you share the two streams with us? It will help us re-produce the problem.

You may send it to shaka-packager-issues@google.com if they cannot be shared publicly.

**Comment by Sidewinder53** [comment]
Thanks for the swift reply! I've made the video streams available here:
https://drive.google.com/drive/folders/14iaxY89lgpLQ5aj4H2vsLbDJBKv7aDAB?usp=sharing

You'll have to sign in as shaka-packager-issues@google.com to access the folder. Thanks again!

**Comment by kqyang** [comment]
@Sidewinder53 Here is why it occurs:

- According to DASH specification, Representation@bandwidth is the max bitrate of all segments.
- In your sample streams, the first segment and the last segment somehow have a much bigger bitrate than other segments (last segment 2874k vs first segment 1796k vs other segments ~800k for v-1200x600-1250k and last segment 2786k vs first segment 2275k vs ~1100k for v-1440x720-1600k). 
- The bitrate for the last segment of v-1200x600-1250k is larger than the bitrate for the last segment of v-1440x720-1600k (2874k vs 2786k).

Since the last segment is a partial segment (2.8 seconds < half of segment duration 6s), we should not take it into bandwidth calculation. I will fix this problem.

Note that you will still have the same problem with the fix if you change the segment duration to 2s. You may want to look into why the first segment and the last segment are that big.

**Comment by Sidewinder53** [comment]
Thank you for this detailed explanation, I really appreciate that!
Could you point me to the tool you used to analyze the individual segments? I wasn't aware that DASH respects them for bandwidth calculation, instead I believed it would calculate the mean value.

I suppose the first and last segment of the video stream need a rather large bandwidth, because they contain rapidly moving elements and involve many more changes from frame to frame, compared to the rest of the video. Since the maximum value for the VBR is factor 2x of the avarage, bitrate "spikes" are very much possible. I may consider reducing this value to 1.45x as suggested by the official VP9 encoding guidelines from Google.

**Comment by kqyang** [comment]
> Could you point me to the tool you used to analyze the individual segments?

The generated mp4 file contains a sidx box, for which the format is

```c
aligned(8) class SegmentIndexBox extends FullBox(‘sidx’, version, 0) {
  unsigned int(32) reference_ID;
  unsigned int(32) timescale;
  if (version==0) {
    unsigned int(32) earliest_presentation_time;
    unsigned int(32) first_offset;
  } else {
    unsigned int(64) earliest_presentation_time;
    unsigned int(64) first_offset;
  }
  unsigned int(16) reserved = 0;
  unsigned int(16) reference_count;
  for(i=1; i <= reference_count; i++) {
    bit (1) reference_type;
    unsigned int(31) referenced_size;
    unsigned int(32) subsegment_duration;
    bit(1) starts_with_SAP;
    unsigned int(3) SAP_type;
    unsigned int(28) SAP_delta_time;
  }
}
```

You can estimate the bandwidth for each individual segments from referenced_size and subsegment_duration fields.

> I wasn't aware that DASH respects them for bandwidth calculation, instead I believed it would calculate the mean value.

Here is a description of bandwidth in DASH spec:

>> Consider a hypothetical constant bitrate channel of bandwidth with the value of this attribute in bits per second (bps). Then, if the Representation is continuously delivered at this bitrate, starting at any SAP that is indicated either by @startWithSAP or by any Segment Index box, a client can be assured of having enough data for continuous playout providing playout begins after @minBufferTime * @ bandwidth bits have been received (i.e. at time @minBufferTime after the first bit is received).

It implies that bandwidth should be the max bitrate instead of average bitrate of all segments.

> they contain rapidly moving elements and involve many more changes from frame to frame, compared to the rest of the video

Ok, that makes sense. You may consider constraint "-minrate" and "-maxrate" some more to avoid having the computed bandwidth for 1250k stream to be larger than the computed bandwidth for 1600k stream.

You can also specify bandwidth in stream descriptor to avoid computing the bandwidth in packager, e.g. `in=v-1200x600-1250k.webm,stream=video,out=ev-1200x600-1250k.webm,drm_label=VIDEO,bandwidth=1250000` sets the bandwidth to 1250000.

**Comment by kqyang** [comment]
@Sidewinder53 Do you have additional questions? Can we close the issue?

**Comment by Sidewinder53** [comment]
Thank you for your explanations, no further questions from my side.
