### ISSUE TITLE
Linux binaries doesn't return stdout/stderr in node childprocess spawn

### ISSUE THREAD

**Issue by ksuhiyp** [google/shaka-packager#582]
## System info
**Operating System**: <e.g. macOS Sierra, Ubuntu 14.04 trusty etc>
UBUNTU 19.04
**Shaka Packager Version**: <e.g. v1.6.1, commit SHA etc>
latest
## Issue and steps to reproduce the problem

Using Node childprocess spawnSync I am not able to tell if the packager job went successful or not, since stdout/stderr in executing the following are null  
```
  const options = {
                detached: false,  // Do not let the child process continue without us
                stdio: 'inherit',  // Pass stdin/stdout/stderr straight through
            }
const packager = spawnSync('node_modules/shaka-packager/bin/packager-linux', [args], options);
//
Proccess log is: {"status":1,"signal":null,"output":[null,null,null],"pid":14134,"stdout":null,"stderr":null}
```
output files are empty after spawnsync is done which means that the packager process wasn't running properly. 

**Packager Command**:
```
// where jobFiles are name => path Map
 const args =
                `in=${jobFiles.get('vp9_360p')},stream=audio,output=${audioPath},drm_label=AUDIO \\
                in=${jobFiles.get('vp9_360p')},stream=video,output=${vp9_360p_protectedPath},drm_label=SD \\
                in=${jobFiles.get('vp9_480p')},stream=video,output=${vp9_480p_protectedPath},drm_label=SD \\
                in=${jobFiles.get('vp9_720p')},stream=video,output=${vp9_720p_protectedPath},drm_label=HD \\
            --clear_lead 0 \\
            --enable_raw_key_encryption \\
            --keys label=AUDIO:key_id=f3c5e0361e6654b28f8049c778b23946:key=a4631a153a443df9eed0593043db7519,label=SD:key_id=abba271e8bcf552bbd2e86a434a9a5d9:key=69eaa802a6763af979e8d1940fb88392,label=HD:key_id=6d76f25cb17f5e16b8eaef6bbf582d8e:key=cb541084c99731aef4fff74500c12ead \\
           --mpd_output h264.mpd`
```

What is the expected result?
get stdout *Packaging completed successfully.* or stderr to know why out files weren't packaged
What happens instead?
No stdout showing packaging were done nor stderr 
`{"status":1,"signal":null,"output":[null,null,null],"pid":14134,"stdout":null,"stderr":null}
`<Please attach the input files or email to shaka-packager-issues@google.com.>
https://s3-eu-west-1.amazonaws.com/dash-hls-adaptive/5ca69560b72a5a706260a8fe_21042019T011953_1.mp4/vp9_360p
https://s3-eu-west-1.amazonaws.com/dash-hls-adaptive/5ca69560b72a5a706260a8fe_21042019T011953_1.mp4/vp9_480p
https://s3-eu-west-1.amazonaws.com/dash-hls-adaptive/5ca69560b72a5a706260a8fe_21042019T011953_1.mp4/vp9_720p
<Please provide any additional information below.>
Node version 11.8

**Comment by kqyang** [comment]
Can you try adding "shell: true" to node options?

**Comment by kqyang** [comment]
Actually I think it is because of this option: **stdio: 'inherit'** option, which pass stdout/stderr through.

**Comment by kqyang** [comment]
It should work with the option removed. Closing the issue. Feel free to comment if it is still an issue.

**Comment by ksuhiyp** [comment]
> Actually I think it is because of this option: stdio: 'inherit' option, which pass stdout/stderr through.

thank you That worked!

aside from the main issue  stderr now reports error `Unknown field in stream descriptor ("label").`  
But executing the same arguments in the binary directly works with success.

args are 
`in=/tmp/db39ea36-6378-4805-969d-16dd1c70f3d3/vp9_360p.webm,stream=audio,output=/tmp/5b1c72351a1bf20f279b3309377189a3/out/audio.webm,drm_label=AUDIO \
in=/tmp/db39ea36-6378-4805-969d-16dd1c70f3d3/vp9_360p.webm,stream=video,output=/tmp/010786fc5a284054fd492be715dcae18/vp9_360p_protected.webm,drm_label=SD \
in=/tmp/861473ea-b383-4196-bb87-82a0c34128a4/vp9_480p.webm,stream=video,output=/tmp/d01bfbcfbb4a6ef4aeeafa6fbc6aaeeb/vp9_480p_protected.webm,drm_label=SD \
in=/tmp/d978bc6a-71e0-4f4c-a180-927dd880032a/vp9_720p.webm,stream=video,output=/tmp/5f5dc4a0e5732298a0ae47af4187e29f/vp9_720p_protected.webm,drm_label=HD \
--clear_lead 0 \
--enable_raw_key_encryption \
--keys label=AUDIO:key_id=f3c5e0361e6654b28f8049c778b23946:key=a4631a153a443df9eed0593043db7519,label=SD:key_id=abba271e8bcf552bbd2e86a434a9a5d9:key=69eaa802a6763af979e8d1940fb88392,label=HD:key_id=6d76f25cb17f5e16b8eaef6bbf582d8e:key=cb541084c99731aef4fff74500c12ead \
--mpd_output h264.mpd`

Can you point out when `Unknown field in stream descriptor ("label").` is thrown

**Comment by kqyang** [comment]
Great! You may be able to make it work by separate the single "args" to args list too, something like ['in=xx,stream=audio,output=...', 'in=xx,stream=video,output=...', '--clear_lead', '0', '--enable_raw_key_encryption', ...].
