### ISSUE TITLE
Shaka packager wont package E-AC3 for HLS

### ISSUE THREAD

**Issue by teb** [google/shaka-packager#583]
## System info
**Windows 10, WSL>
**Shaka Packager Version**: b85e5c9368-release>

## Issue and steps to reproduce the problem
When packaging a file-set to HLS, E-AC3 isnt passthroughed with HLS, Dash works

**Packager Command**:
 ./packager in=Solo_CRF_1.mp4,stream=audio,output=audio.mp4,playlist_name=audio.m3u8,hls_group_id=audio,hls_name=ENGLISH in=Solo_CRF_1.mp4,stream=video,output=Solo_CRF_1.mp4,playlist_name=Solo_CRF_1.m3u8 in=Solo_CRF_2.mp4,stream=video,output=Solo_CRF_2.mp4,playlist_name=Solo_CRF_2.m3u8 in=Solo_CRF_3.mp4,stream=video,output=Solo_CRF_3.mp4,playlist_name=Solo_CRF_3.m3u8 in=Solo_CRF_4.mp4,stream=video,output=Solo_CRF_4.mp4,playlist_name=Solo_CRF_4.m3u8 in=Solo_CRF_5.mp4,stream=video,output=Solo_CRF_5.mp4,playlist_name=Solo_CRF_5.m3u8 in=Solo_CRF_6.mp4,stream=video,output=Solo_CRF_6.mp4,playlist_name=Solo_CRF_6.m3u8 --hls_master_playlist_output h264_master.m3u8

*Apple Mediavalitator = successfull.
*Solo_CRF1-3 = AAC track, whilst the rest E-AC3 track

What is the expected result?
E-AC3 part of the manifest and or AAC on all tracks.

What happens instead?
In all profiles, all but the audio track are missing the audio track, both in the mp4 file and manifest

When doing it in Mpeg Dash, all is fine

<Please attach the input files or email to shaka-packager-issues@google.com.>
<Please provide any additional information below.>

**Comment by kqyang** [comment]
@teb Do you mean the packaging succeeds but the EC-3 audio does not play?

**Comment by teb** [comment]
> @teb Do you mean the packaging succeeds but the EC-3 audio does not play?

When parsing the mp4 files AFTER shaka has done its job, all mp4 files, and manifests doenst have any audio tracks.. only the audio only one..

**Comment by kqyang** [comment]
@teb That is expected. That is because "stream=video" is specified. It means that the first "video" stream in the input is included in the output.

Shaka Packager does not support more than one streams in the output stream.

**Comment by teb** [comment]
> @teb That is expected. That is because "stream=video" is specified. It means that the first "video" stream in the input is included in the output.
> 
> Shaka Packager does not support more than one streams in the output stream.

Ah! So if the first "input" file had an ec3 audio track, this would be the solo one instead of the aac one..?
Any plans to add support for multiple audio tracks, like EAC3 + AAC in 1 manifest? Same of different language?

**Comment by kqyang** [comment]
It is supported. You just need to specify it via stream descriptors, something like:

in=Solo_with_aac.mp4,stream=audio,output=Solo_aac.mp4,playlist_name=Solo_aac.m3u8 in=Solo_with_ec3.mp4,stream=audio,output=Solo_ec3.mp4,playlist_name=Solo_ec3.m3u8 
...

**Comment by teb** [comment]
> It is supported. You just need to specify it via stream descriptors, something like:
> 
> in=Solo_with_aac.mp4,stream=audio,output=Solo_aac.mp4,playlist_name=Solo_aac.m3u8 in=Solo_with_ec3.mp4,stream=audio,output=Solo_ec3.mp4,playlist_name=Solo_ec3.m3u8
> ...

Ah! But what if there are multiple versions with different languages? Can one use the combination?

**Comment by kqyang** [comment]
If the stream contains language metadata, it will be extracted and indicated in the manifest / playlist; otherwise if the stream does not contain language metadata, you can provide "language" in the stream descriptor, e.g. in=Solo_with_aac.mp4,stream=audio,output=Solo_aac.mp4,playlist_name=Solo_aac.m3u8,lang=eng, which can also be used to override the language metadata.

**Comment by teb** [comment]
Not to highjack my own thread, but i noticed the validator is reporting :

Solo_CRF_1_f.m3u8
--------------------------------------------------------------------------------
Processed 1293 out of 1293 segments
**### Average segment duration: 5.995514**
Total segment bitrates (all discontinuities): average: 193.14 kb/s, max: 637.26 kb/s
Playlist max bitrate: 708.537000 kb/s
Audio Group ID: audio


Discontinuity: sequence: 0, parsed segment count: 1293 of 1293, duration: 7752.200 sec, average: 193.14 kb/s, max: 637.26 kb/s
Track ID: 1
Video Codec: avc1
Video profile: High
Video level: 4,1
Video resolution: 480x270
Video average IDR interval: 4.000000, Standard deviation: 0.000000
Video frame rate: 25.000

They all are encoded with a 4 sec gop, so this surely must be wrong.. IS there a way to ENFORCE the segmenting to be 4 seconds or 8?

**Comment by kqyang** [comment]
@teb The segment duration is a user input. It is set to 6 seconds by default. You may adjust it yourself, e.g. you can set it to 4 using `--segment_duration=4`.

**Comment by kqyang** [comment]
@teb Does that answer your questions?

**Comment by teb** [comment]
> @teb The segment duration is a user input. It is set to 6 seconds by default. You may adjust it yourself, e.g. you can set it to 4 using `--segment_duration=4`.

thx! This suggestion was just what i needed!
