### ISSUE TITLE
UDP multicast not seen in Shaka Packager docker container

### ISSUE THREAD

**Issue by stefdaems** [google/shaka-packager#595]
## System info
**Operating System**: macOS Mojave, Docker version 18.09.2
**Shaka Packager Version**: packager version 72c4797-release

## Issue and steps to reproduce the problem
Using Shaka-packager docker container running with --net=host option to allow access to the host network layer. I've set up a multicast udp stream which on another device in the same network. I am able on watching the stream on the device where I'm running the docker Shaka packager.

The UDP stream is multicasted on udp://224.1.1.5:9876

In the docker container I execute following command to retrieve stream info
*** docker started with
docker run -v /media/:/media -it --net=host --rm google/shaka-packager

***packager command
packager input=udp://224.1.1.5:9876 --dump_stream_info

Resulting in

[0614/101626:INFO:demuxer.cc(88)] Demuxer::Run() on file 'udp://224.1.1.5:9876'.
[0614/101626:INFO:demuxer.cc(160)] Initialize Demuxer for file 'udp://224.1.1.5:9876'.

But no single stream info is shown. Any idea?

**Comment by kqyang** [comment]
It worked for me before. I'll take another look later.

**Comment by kqyang** [comment]
@stefdaems It still works for me on my Linux machine with latest google/shaka-packager docker image.

I am not sure if it is a docker problem on macOS. You may want to check with the docker community or try it on a Linux machine.
