### ISSUE TITLE
Working with live video with Nodejs

### ISSUE THREAD

**Issue by Sectur1** [google/shaka-packager#600]
Hey, I am building a Flutter app and I want to add a live stream feature. I accessed the camera streamed the feed to my server, but I don't know how to package my Dash content for live streaming. But from the docs, Shaka packager only receives data from UDP and I don't know how I get the data from http to UDP using Nodejs

**Comment by kqyang** [comment]
@Sectur1 You can try if you can pipe your source stream using FFmpeg to Shaka Packager: https://google.github.io/shaka-packager/html/tutorials/ffmpeg_piping.html.

**Comment by Sectur1** [comment]
Thank 

> @Sectur1 You can try if you can pipe your source stream using FFmpeg to Shaka Packager: https://google.github.io/shaka-packager/html/tutorials/ffmpeg_piping.html.

Thanks. I will try it out

**Comment by kqyang** [comment]
@Sectur1 Do you have other questions? If not, can we close it?
