### ISSUE TITLE
what are the recommended params of ffmpeg to transcode mp4 in different scale for packaging HLS streaming through packager 

### ISSUE THREAD

**Issue by rahulcbr** [google/shaka-packager#603]
## System info
**Operating System**: <e.g. macOS Sierra, Ubuntu 14.04 trusty etc>
**Shaka Packager Version**: <e.g. v1.6.1, commit SHA etc>

## Issue and steps to reproduce the problem
ffmpeg -i original.mp4 -c:a aac -strict experimental -b:a 128k -c:v libx265 -vf scale=144:256 144_256_h265.mp4 -hide_banner
ffmpeg -i original.mp4 -c:a aac -strict experimental -b:a 128k -c:v libx265 -vf scale=360:640 360_640_h265.mp4 -hide_banner
ffmpeg -i original.mp4 -c:a aac -strict experimental -b:a 128k -c:v libx265 -vf scale=720:1280 720_1280_h265.mp4 -hide_banner
ffmpeg -i original.mp4 -c:a aac -strict experimental -b:a 128k -c:v libx265 -vf scale=1080:1920 1080_1920_h265.mp4 -hide_banner
**Packager Command**:
packager-osx in=144_256_h265.mp4,stream=audio,output=hls/audio.mp4,playlist_name=audio.m3u8,hls_group_id=audio,hls_name=ENGLISH in=144_256_h265.mp4,stream=video,output=hls/h265_144p.mp4,playlist_name=h265_144p.m3u8,iframe_playlist_name=h265_144p_iframe.m3u8 in=360_640_h265.mp4,stream=video,output=hls/h265_360p.mp4,playlist_name=h265_360p.m3u8,iframe_playlist_name=h265_360p_iframe.m3u8 in=720_1280_h265.mp4,stream=video,output=hls/h265_720p.mp4,playlist_name=h265_720p.m3u8,iframe_playlist_name=h265_720p_iframe.m3u8  in=1080_1920_h265.mp4,stream=video,output=hls/h265_1080p.mp4,playlist_name=h265_1080p.m3u8,iframe_playlist_name=h265_1080p_iframe.m3u8 --hls_master_playlist_output hls/h265_master.m3u8

**Comment by kqyang** [comment]
@rahulcbr We don't have a guideline or recommendations on what resolutions to transcode for HLS streaming. You may want to check out [HLS Authoring Specification for Apple Devices](https://developer.apple.com/documentation/http_live_streaming/hls_authoring_specification_for_apple_devices). 

We do recommend a GOP size of 6 seconds or less.

> scale=144:256 

The width and height are reversed. Should be scale=256:144.

Hope that helps.
