### ISSUE TITLE
Question - Any way to calculate back the Unix Timestamp from $Time$ value

### ISSUE THREAD

**Issue by jatinderkumargupta** [google/shaka-packager#605]
I am using Segment template with $Time$ option.
Segment created at: 2019-06-28 12:19:16.467499657 +0530
have $Time$ value: 3637990264

Is there any way to calculate back the Unix Timestamp from $Time$ value?

**Comment by kqyang** [comment]
Yes. The time is based on the timescale in the SegmentTemplate and relative to availabilityStartTime in mpd.

You can calculate the presentation time as: MPD@availabilityStartTime + time / SegmentTemplate@timescale.

@jatinderkumargupta Does that answer your question?

**Comment by jatinderkumargupta** [comment]
Thanks for your response.
This information is available in case of DASH. How to get that in case of HLS?

**Comment by kqyang** [comment]
@jatinderkumargupta Yes. That is DASH only. For HLS, we'll need to rely on EXT-X-PROGRAM-DATE-TIME (https://github.com/google/shaka-packager/issues/365), which unfortunately, we don't support yet.
