### ISSUE TITLE
[Question] Is it possible using the keys from Google Cloud for FairPlay?

### ISSUE THREAD

**Issue by weiyuefei** [google/shaka-packager#606]
Hi, 

I want to use the Shaka-Packager to generate HLS content with FairPlay encryption, and it works with the raw_key options. 

But I'm wondering whether I can use the keys which are generated and managed by Google Cloud for FairPlay encryption? For example, before the packaging, I can firstly separately request the key_id and keys  from Google Cloud, then parse the keys from response results, and to execute the packaging cmd. 

I hope you could understand what I mean. In a word, I don't want to build our key system, I hope I can use the keys managed by Google Cloud for Fairplay, same as for Widevine.

**Comment by kqyang** [comment]
@weiyuefei Yes, you can use the keys managed by Google Widevine for Fairplay. You'll still need to set up your own Fairplay license server though as Widevine license server is not capable of delivering Fairplay license. 

Another option for you is to use Widevine iOS CDM library, which allows you to use CENC+Widevine on iOS devices. You can reach out to https://www.widevine.com/contact for more details on Widevine iOS CDM library.

Does that answer your questions?

**Comment by weiyuefei** [comment]
> @weiyuefei Yes, you can use the keys managed by Google Widevine for Fairplay. You'll still need to set up your own Fairplay license server though as Widevine license server is not capable of delivering Fairplay license.

I have made a simple test on getcontentkey API, and I got the results as follows:

{"status":"OK","drm":[{"type":"WIDEVINE","system_id":"edef8ba979d64acea3c827dcd51d21ed"}],"tracks":[{"type":"SD","key_id":"WsX1NL61UhuUrZuUsk+cYQ==","key":"P4pK/mVdXkyWPk8h5ixx7A==","pssh":[{"drm_type":"WIDEVINE","data":"IhVzZG1jX3dpZGV2aW5lX3Rlc3RpbmdI49yVmwY=","boxes":"AAAAPXBzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAAB0iFXNkbWNfd2lkZXZpbmVfdGVzdGluZ0jj3JWbBg=="}],"entitled_key":[],"content_groups":[]},{"type":"HD","key_id":"pVHySJWQUKa3T4wMqZKATA==","key":"rFNcjyEgDpMSJLF5xU41vQ==","pssh":[{"drm_type":"WIDEVINE","data":"IhVzZG1jX3dpZGV2aW5lX3Rlc3RpbmdI49yVmwY=","boxes":"AAAAPXBzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAAB0iFXNkbWNfd2lkZXZpbmVfdGVzdGluZ0jj3JWbBg=="}],"entitled_key":[],"content_groups":[]},{"type":"AUDIO","key_id":"PHEzumLPXLWGWLTo28kwyQ==","key":"309776hmYbJn2k8Rl9C+Sg==","pssh":[{"drm_type":"WIDEVINE","data":"IhVzZG1jX3dpZGV2aW5lX3Rlc3RpbmdI49yVmwY=","boxes":"AAAAPXBzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAAB0iFXNkbWNfd2lkZXZpbmVfdGVzdGluZ0jj3JWbBg=="}],"entitled_key":[],"content_groups":[]}],"already_used":true}

But it seems no iv found in the results. As I know, FairPlay needs iv for CBC encryption, when no iv option provided, packager will use the random iv for encryption,  right? I'm confused and unsure to handle this, plz give me a help.
 
> Another option for you is to use Widevine iOS CDM library, which allows you to use CENC+Widevine on iOS devices. You can reach out to https://www.widevine.com/contact for more details on Widevine iOS CDM library.

That sounds great, and I will try that later. If it works, that will be very cool for content protection with just Widevine for both Android and iOS devices.

**Comment by kqyang** [comment]
> But it seems no iv found in the results. As I know, FairPlay needs iv for CBC encryption, when no iv option provided, packager will use the random iv for encryption, right? I'm confused and unsure to handle this, plz give me a help.

That is expected. For FairPlay to work properly, you'll need to provide an IV to packager during packaging; in your Fairplay server, you need to return the same IV along with the content key from Widevine getcontentkey API when serving the Fairplay license request.

**Comment by weiyuefei** [comment]
> > But it seems no iv found in the results. As I know, FairPlay needs iv for CBC encryption, when no iv option provided, packager will use the random iv for encryption, right? I'm confused and unsure to handle this, plz give me a help.
> 
> That is expected. For FairPlay to work properly, you'll need to provide an IV to packager during packaging; in your Fairplay server, you need to return the same IV along with the content key from Widevine getcontentkey API when serving the Fairplay license request.

Do you mean that I can use a hard-coded iv which is the same for all FairPlay encrypted content? That's to say I can generate an iv beforehand by myself and use that to serve for all FairPlay content, right? For example, there is a hardcoded iv: 8ceded2ee4927c0c6a976296587492ad, and content A and B which are prepared for FairPlay encryption, then the iv for A and B is same to 8ceded2ee4927c0c6a976296587492ad.

**Comment by kqyang** [comment]
Yes, you can use the same IV for all your contents. Since you are getting the keys from Google cloud (Widevine) and you don't want to maintain a database for keys/ivs, another option for you is to derive the IV from the key_id, so it appears different each time.

**Comment by weiyuefei** [comment]
@kqyang Thank you for your answer. I will close this issue.
