### ISSUE TITLE
EXT-I-FRAME-STREAM-INF has "BANDWIDTH=0"

### ISSUE THREAD

**Issue by kqyang** [google/shaka-packager#610]
Moved from https://github.com/google/shaka-packager/issues/565#issuecomment-508325358 by @jigneshdhruv

@kqyang After checking out the latest shaka packager code, we are having playback issue with HLS manifest. On further debugging we found that "BANDWIDTH" is assigned a value of '0' in EXT-X-I-FRAME-STREAM-INF tag in master manifest file.

For eg in master HLS manifest we see:
#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=0,AVERAGE-BANDWIDTH=418540,CODECS="avc1.640028",RESOLUTION=1280x720,URI="378_AA_6CH_30M_1698529_3000/stream_iframe.m3u8"
#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=0,AVERAGE-BANDWIDTH=276336,CODECS="avc1.640028",RESOLUTION=1024x576,URI="378_AA_6CH_30M_1698529_2100/stream_iframe.m3u8"

Older versions of shaka packager represents correct value for BANDWIDTH.

Can you please look into this?

**Comment by jigneshdhruv** [comment]
@kqyang Let us know if you have any ETA on when will this ticket be resolved. Thanks.

**Comment by kqyang** [comment]
@jigneshdhruv I am not able to re-produce the problem. Do you have a sample input and command that I can use to re-produce the problem?

**Comment by jigneshdhruv** [comment]
@kqyang I can reproduce the problem with latest source code

I am using packager version:
packager version 15a4f05-release

My command is as follows:
packager 'in=/tmp/packager/video.mp4,stream=video,segment_template=/tmp/packager/output/video_3000/seg_$Number$.ts,iframe_playlist_name=video_3000/stream_iframe.m3u8,playlist_name=video_3000/stream.m3u8' 'in=/tmp/packager/audio.mp4,stream=audio,segment_template=/tmp/packager/output/audio_128/seg_$Number$.ts,playlist_name=audio_128/stream.m3u8,hls_group_id=audio_128,hls_name=ENGLISH' --default_language en --clear_lead 0 --segment_duration 6  --hls_master_playlist_output /tmp/packager/output/master.m3u8

I can send you mp4 files if you need them. But I am able to reproduce this error with all mp4's.

Master Variant has following entry for iframes:
#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=0,AVERAGE-BANDWIDTH=414892,CODECS="avc1.640028",RESOLUTION=1920x1080,URI="video_3000/stream_iframe.m3u8"

Let me know if you need any additional information.

**Comment by kqyang** [comment]
Emm... It works for me actually.

```hls
#EXTM3U
## Generated with https://github.com/google/shaka-packager version 15a4f0553c-release

#EXT-X-MEDIA:TYPE=AUDIO,URI="audio_128/stream.m3u8",GROUP-ID="audio_128",LANGUAGE="en",NAME="ENGLISH",DEFAULT=YES,AUTOSELECT=YES,CHANNELS="2"

#EXT-X-STREAM-INF:BANDWIDTH=1525693,AVERAGE-BANDWIDTH=1036108,CODECS="avc1.4d001e,mp4a.40.2",RESOLUTION=640x360,AUDIO="audio_128"
video_3000/stream.m3u8

#EXT-X-I-FRAME-STREAM-INF:BANDWIDTH=123328,AVERAGE-BANDWIDTH=26273,CODECS="avc1.4d001e",RESOLUTION=640x360,URI="video_3000/stream_iframe.m3u8"
```

@jigneshdhruv Yes, please send a mp4 file to us. We'll try if we can re-produce it with the same exact input.

**Comment by jigneshdhruv** [comment]
@kqyang I have sent video.mp4 and audio.mp4 files to your email address. Hope you are able to reproduce this issue. Thanks.

**Comment by kqyang** [comment]
@jigneshdhruv Thanks. Yes, I am able to reproduce the issue with your files. I think I know what is happening. We will have a fix soon.

**Comment by jigneshdhruv** [comment]
Thanks @kqyang

**Comment by jigneshdhruv** [comment]
Any ETA @kqyang

**Comment by kqyang** [comment]
@jigneshdhruv We are targeting this week.

**Comment by jigneshdhruv** [comment]
@kqyang Are you still targeting this week?

**Comment by kqyang** [comment]
Yes.

**Comment by kqyang** [comment]
@jigneshdhruv Should be fixed now! Let us know if you are still seeing problems.

**Comment by jigneshdhruv** [comment]
Thank you. I will test and let you know.
