### ISSUE TITLE
Video and audio chunks not deleted when not using mpd_output parameter

### ISSUE THREAD

**Issue by akkermansadriaan** [google/shaka-packager#625]
## System info
**Operating System**: Centos 7 Linux 3.10.0-957.12.1.el7.x86_64 x86_64 x86_64 x86_64 GNU/Linux
**Shaka Packager Version**: packager_linux version 5d80895-release

## Issue and steps to reproduce the problem

When using the packager to package live content as HLS  (and using specifically preserved_segments_outside_live_window set to a value so files get deleted) the files aren't getting deleted. When adding the parameter --mpd_output the files do get deleted.

inotifywait indicates indeed no DELETE happens when the packager is not provided with the mpd_output paramter

packager \
'in=udp://udp_ip:udp_port1?source=udp_source&reuse=1,stream=audio,init_segment=/mnt/live/hls/channel/audio/init.mp4,segment_template=/mnt/live/hls/channel/audio/$Time$.m4a,playlist_name=audio/main.m3u8,hls_group_id=audio' \
'in=udp://udp_ip:udp_port1?source=udp_source&reuse=1,stream=video,init_segment=/mnt/live/hls/channel/video/1/init.mp4,segment_template=/mnt/live/hls/channel/video/1/$Time$.m4s,playlist_name=video/1/main.m3u8,iframe_playlist_name=video/1/iframe.m3u8' \
'in=udp://udp_ip:udp_port2?source=udp_source&reuse=1,stream=video,init_segment=/mnt/live/hls/channel/video/2/init.mp4,segment_template=/mnt/live/hls/channel/video/2/$Time$.m4s,playlist_name=video/2/main.m3u8,iframe_playlist_name=video/2/iframe.m3u8' \
'in=udp://udp_ip:udp_port3?source=udp_source&reuse=1,stream=video,init_segment=/mnt/live/hls/channel/video/3/init.mp4,segment_template=/mnt/live/hls/channel/video/3/$Time$.m4s,playlist_name=video/3/main.m3u8,iframe_playlist_name=video/3/iframe.m3u8' \
'in=udp://udp_ip:udp_port4?source=udp_source&reuse=1,stream=video,init_segment=/mnt/live/hls/channel/video/4/init.mp4,segment_template=/mnt/live/hls/channel/video/4/$Time$.m4s,playlist_name=video/4/main.m3u8,iframe_playlist_name=video/4/iframe.m3u8' \
'in=udp://udp_ip:udp_port5?source=udp_source&reuse=1,stream=video,init_segment=/mnt/live/hls/channel/video/5/init.mp4,segment_template=/mnt/live/hls/channel/video/5/$Time$.m4s,playlist_name=video/5/main.m3u8,iframe_playlist_name=video/5/iframe.m3u8' \
'in=udp://udp_ip:udp_port6?source=udp_source&reuse=1,stream=video,init_segment=/mnt/live/hls/channel/video/6/init.mp4,segment_template=/mnt/live/hls/channel/video/6/$Time$.m4s,playlist_name=video/6/main.m3u8,iframe_playlist_name=video/6/iframe.m3u8' \
'in=udp://udp_ip:udp_port7?source=udp_source&reuse=1,stream=video,init_segment=/mnt/live/hls/channel/video/7/init.mp4,segment_template=/mnt/live/hls/channel/video/7/$Time$.m4s,playlist_name=video/7/main.m3u8,iframe_playlist_name=video/7/iframe.m3u8' \
'in=udp://udp_ip:udp_port8?source=udp_source&reuse=1,stream=video,init_segment=/mnt/live/hls/channel/video/8/init.mp4,segment_template=/mnt/live/hls/channel/video/8/$Time$.m4s,playlist_name=video/8/main.m3u8,iframe_playlist_name=video/8/iframe.m3u8' \
'in=udp://udp_ip:udp_port9?source=udp_source&reuse=1,stream=video,init_segment=/mnt/live/hls/channel/video/9/init.mp4,segment_template=/mnt/live/hls/channel/video/9/$Time$.m4s,playlist_name=video/9/main.m3u8,iframe_playlist_name=video/9/iframe.m3u8' \
'in=udp://udp_ip:udp_port10?source=udp_source&reuse=1,stream=video,init_segment=/mnt/live/hls/channel/video/10/init.mp4,segment_template=/mnt/live/hls/channel/video/10/$Time$.m4s,playlist_name=video/10/main.m3u8,iframe_playlist_name=video/10/iframe.m3u8' \
  --time_shift_buffer_depth 30 --preserved_segments_outside_live_window 5 \
  --hls_master_playlist_output /mnt/live/hls/channel/master.m3u8 --hls_playlist_type LIVE \
  --enable_raw_key_encryption --keys key_id=key_id:key=key --iv iv --hls_key_uri hls_key_uri \
  --protection_systems Fairplay --protection_scheme cbcs --clear_lead 0 \

What is the expected result?
The chunks are being deleted.

What happens instead?
The chunks aren't being deleted.

**Comment by kqyang** [comment]
@akkermansadriaan Thanks for the bug report. We'll see if we can re-produce the issue.

**Comment by kqyang** [comment]
@akkermansadriaan We are able to re-produce the problem. Working on the fix.

**Comment by kqyang** [comment]
@akkermansadriaan This is now fixed. Let us know if it is still a problem for you.
