### ISSUE TITLE
Support for multiple audio labels when using widevine encryption

### ISSUE THREAD

**Issue by yotta-stu** [google/shaka-packager#626]
## System info
- Ubuntu 16.04.5 LTS (GNU/Linux 4.4.0-138-generic x86_64)
- shaka-packager version 53aa775-release

## Issue and steps to reproduce the problem
When adding a second audio with a drm label AUDIO2 to generate a separate key for this component get a packager error 14. Cannot find key for 'AUDIO2'
Console log output below:
[0726/113256:INFO:demuxer.cc(88)] Demuxer::Run() on file '/home/packager/content/bbb-hevc720-2audio.mp4'.
[0726/113256:INFO:demuxer.cc(160)] Initialize Demuxer for file '/home/packager/content/bbb-hevc720-2audio.mp4'.
[0726/113256:ERROR:box_definitions.cc(627)] Not implemented reached in virtual bool shaka::media::mp4::SampleDescription::ReadWriteInternal(shaka::media::mp4::BoxBuffer *)SampleDecryption type 0 is not handled. Skipping.
[0726/113256:ERROR:box_definitions.cc(2087)] Not implemented reached in virtual bool shaka::media::mp4::MediaInformation::ReadWriteInternal(shaka::media::mp4::BoxBuffer *)
[0726/113256:ERROR:mp4_media_parser.cc(790)] Failed to process the sample.
[0726/113256:ERROR:packager_main.cc(518)] Packaging Error: 14 (INTERNAL_ERROR): Cannot find key for 'AUDIO2'.

**Packager Command**:

sudo ./packager \
  'input=/home/packager/content/'$content',stream=video,init_segment='$out'/video/init-video.mp4,segment_template='$out'/video/$Number$.m4s,drm_label=HD' \
  'input=/home/packager/content/'$content',stream=1,init_segment='$out'/audio/init-audio.mp4,segment_template='$out'/audio/$Number$.m4s,drm_label=AUDIO' \
  'input=/home/packager/content/'$content',stream=2,init_segment='$out'/audio2/init-audio2.mp4,segment_template='$out'/audio2/$Number$.m4s,drm_label=AUDIO2' \
  --enable_widevine_encryption \
  --key_server_url <licence server url> \
  --content_id <contentID> \
  --signer <signer> \
  --aes_signing_key <aes_key> \
  --aes_signing_iv <aes_iv> \
  --segment_duration 1 \
  --generate_static_mpd \
  --allow_approximate_segment_timeline \
  --segment_template_constant_duration \
  --mpd_output $out/manifest.mpd

Extra steps to reproduce the problem?
Reproduce issue each time script is run.

What is the expected result?
Require three keys to be generated for video, audio, and audio2.
In fact for our testing up to 8 audio components would be desirable, with different drm labels
AUDIO
AUDIO2
AUDIO3
AUDIO4
AUDIO5
AUDIO6
AUDIO7

What happens instead?
Error as described above.
<Please attach the input files or email to shaka-packager-issues@google.com.>
<Please provide any additional information below.>

**Comment by kqyang** [comment]
Widevine license server does not support multiple AUDIO keys by default. If you want to do that, you'll need to set up the license policy yourself or use your own license server. 

Also, since there isn't secure audio pipeline in most devices, it does not add much security benefits by having multiple audio keys. Any reason that you want to use different keys for audio?

**Comment by yotta-stu** [comment]
There may be some service profiles which could include specialized audio tracks which have different subscription models to the first audio. 

If the license server is setup for extra drm labels, will Shaka Packager automatically query the server for these, or does extra functionality need to be in place on Shaka?

**Comment by kqyang** [comment]
> If the license server is setup for extra drm labels, 

Do you run your own license server? How do you plan to signal the DRM labels? 

> will Shaka Packager automatically query the server for these, or does extra functionality need to be in place on Shaka?

No. There isn't a way to communicate the DRM lables from server to packager right now.

**Comment by astinus-1** [comment]
Given that Widevine license server has no plans to handle additional audio keys, currently this seems to be working as intended. I believe you could use your own license server and/or raw key content creation to provide separate keys for audio, but those would be server work rather than changes needed in the packager. Please re-open if there is any other information you need.
