### ISSUE TITLE
Not able to play Widevine + TS based stream

### ISSUE THREAD

**Issue by Ankur-Gupta04** [google/shaka-packager#628]
## System info
**Operating System**: Windows
**Shaka Packager Version**: v2.3.0-5bf8ad5ed5-release

##Not able to play Widevine + TS segments based HLS stream.

**Packager Command**:
packager ^
in=input.mp4,stream=audio,segment_template=audio/**Segment-$Number$.ts**,playlist_name=audio/main.m3u8,hls_group_id=audio,hls_name=English ^
in=input.mp4,stream=video,segment_template=video/**Segment-$Number$.ts**,playlist_name=video/main.m3u8,iframe_playlist_name=video/iframe.m3u8 ^
--enable_widevine_encryption ^
--enable_widevine_decryption ^
--protection_scheme cenc --key_server_url "<key_server_url>" ^
--content_id "<content_id>" --signer "widevine_test" --aes_signing_key  "<signer_key>" ^
--aes_signing_iv "<signer_iv>" ^
--protection_systems Widevine ^
-segment_duration 2 ^
--hls_master_playlist_output playlist.m3u8 
**Output stream is not played on https://video-dev.github.io/hls.js/demo/.** 

While corresponding Widevine + CMAF (fmp4) based HLS stream works fine on https://video-dev.github.io/hls.js/demo/.
packager ^
in=input.mp4,stream=audio,init_segment=audio/init.mp4,segment_template=audio/**Segment-$Number$.m4s**,playlist_name=audio/main.m3u8,hls_group_id=audio,hls_name=English ^
in=input.mp4,stream=video,init_segment=video/init.mp4,segment_template=video/**Segment-$Number$.m4s**,playlist_name=video/main.m3u8,iframe_playlist_name=video/iframe.m3u8 ^
--enable_widevine_encryption ^
--enable_widevine_decryption ^
--protection_scheme cenc --key_server_url "<key server url>" ^
--content_id "<content id>" --signer "widevine_test" --aes_signing_key  "<aes signing key>" ^
--aes_signing_iv "<signing iv>" ^
--protection_systems Widevine ^
-segment_duration 2 ^
--hls_master_playlist_output playlist.m3u8 

**Does shaka packager support Widevine + TS segments based HLS streams?**
I tried with 'cbcs' option with both cases, again same behavior. TS segment based stream doesn't play properly while CMAF(fmp4) based stream plays properly.

What is the expected result?
Widevine + TS segments based HLS stream should be played like Widevine + CMAF (fmp4) based HLS stream.

What happens instead?
It doesn't play. It stops after playing plain content in the TS segments based HLS stream. 

<Please attach the input files or email to shaka-packager-issues@google.com.>

<Please provide any additional information below.>

**Comment by kqyang** [comment]
@Ankur-Gupta04 Are you trying to play on Chrome? Unfortunately Chrome does not support TS directly. hls.js supports non-encrypted TS by transmuxing TS to mp4. Unfortunately, hls.js does not support transmuxing encrypted TS (with Widevine) right now. Please file a bug to hls.js if you want it to be supported.

**Comment by Ankur-Gupta04** [comment]
@kqyang Thanks for looking into it. I tried same stream on shaka player as well and it didn't work. I don't see CA_descriptor in TS_program_map_section of generated transport stream. Also in case of cenc protection_scheme, I see "#EXT-X-KEY:METHOD=**SAMPLE-AES**,URI="data:text/plain;base64,AAAAMHBzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAABAiCDAxMjM0NTY3SOPclZsG",KEYID=0x4189CB1521FB5C6291A79193D73BF95C,**IV=0x363476B48AC7C67C45303E06BD1E79A5**,KEYFORMATVERSIONS="1",KEYFORMAT="urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed"  in case of ts based stream while "#EXT-X-KEY:METHOD=**SAMPLE-AES-CTR**,URI="data:text/plain;base64,AAAAMHBzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAABAiCDAxMjM0NTY3SOPclZsG",KEYID=0x4189CB1521FB5C6291A79193D73BF95C,KEYFORMATVERSIONS="1",KEYFORMAT="urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed" in case of CMAF based stream. Do you see any issue here? 

Do we have any Widevine + TS based stream (with licence server url) working on shaka player or any other player?

**Comment by kqyang** [comment]
@Ankur-Gupta04 "METHOD=SAMPLE-AES-CTR" is an extension to support "cenc" with CTR. If you set the "protection_scheme" to "cbcs", the standard method of "SAMPLE-AES" will be used.

Widevine+TS requires both platform support and player support. You can try MPL on Chromecast and NexPlayer on Android.

As for web platforms such as Chrome, it is possible to do encrypted TS transmuxing to mp4, but as far as I know, none of the players support it right now.

**Comment by Ankur-Gupta04** [comment]
@kqyang That was my doubt. Shaka packager creates stream with standard method of **"SAMPLE-AES"** in case of **'cenc'** option with TS based streams. Is it correct? Should it create with "METHOD=SAMPLE-AES-CTR" just like in case of CMAF based streams? 

Did you try to analyze Widevine related information (using any tool) in generated transport stream (.ts) using shaka packager? I guess there is problem in generation of streams. 

Do you have any Widevine + TS stream which works on MPL on Chromecast or NexPlayer on Android?

**Comment by kqyang** [comment]
Ah, I see where your confusion comes from. 

For TS or HLS packed audio, the only supported protection scheme is [SAMPLE AES](https://developer.apple.com/library/archive/documentation/AudioVideo/Conceptual/HLS_Sample_Encryption/Encryption/Encryption.html#//apple_ref/doc/uid/TP40012862-CH2-SW6). The `--protection_scheme` flag is ignored for TS or HLS packed audio.

There is a specification to do [common encryption on TS](https://www.iso.org/standard/70175.html), which we don't support right now. As far as I know, there are no players / platforms supporting it either.

**Comment by Ankur-Gupta04** [comment]
So do you mean we can only create **'cbcs'** stream from **Shaka packager** for Widevine + TS based stream? Or Shaka packager doesn't support Widevine + TS based stream at all for any type of protection_scheme.

I tried with cbcs generated transport stream but still didn't get common encryption related information (like ca_descriptor using any tool) in generated transport stream (.ts). So it seems shaka packager doesn't support for **'cbcs'** protection_scheme as well. 

I think only nexplayer supports it and only for **'cbcs'** protection scheme for Widevine + TS based stream. 
https://www.nexplayersdk.com/widevine-player-sdk/

**Comment by kqyang** [comment]
What Nexplayer supports is SAMPLE AES. See https://developer.apple.com/library/archive/documentation/AudioVideo/Conceptual/HLS_Sample_Encryption/Encryption/Encryption.html#//apple_ref/doc/uid/TP40012862-CH2-SW6 and https://tools.ietf.org/html/rfc8216#section-4.3.2.4 for details.

"cbcs" in Common Encryption is based on Apple's SAMPLE AES in TS. They are similar, e.g. they are both pattern based encryption using AES-CBC. There are some differences too, e.g. the last 16-byte block is encrypted in "cbcs" but not encrypted in SAMPLE AES.

Also, SAMPLE AES in mp4 uses "cbcs" in Common Encryption.

HLS packed audio is a special elementary audio format defined by HLS: https://tools.ietf.org/html/rfc8216#section-3.4.

**Comment by Ankur-Gupta04** [comment]
@kqyang Thanks for your support. As there is no support of "common encryption on TS" so as per my understanding there is no way in shaka packager to create Widevine + TS based stream for any type of protection_scheme (cbcs, cbc1, cenc etc). 
Is there any plan to support it in future? 

Can I get any sample stream (Widevine + TS based)?

**Comment by kqyang** [comment]
@Ankur-Gupta04 What is your goal? If you want an encrypted TS stream that works, you should use SAMPLE AES encryption. (The same encrypted stream can use FairPlay on Apple devices and use Widevine on Android / Chromecast)

As mentioned above, we support Widevine + TS with SAMPLE AES encryption. 

We have no plan to support CETS (Common Encryption on TS) as there are no such use cases right now.

**Comment by Ankur-Gupta04** [comment]
@kqyang  _As mentioned above, we support Widevine + TS with SAMPLE AES encryption._
- Can you please share command for it.  I have confused here.  Is it related to https://google.github.io/shaka-packager/html/tutorials/raw_key.html but not sure what should licence server be used in this case when playing content?

**Comment by kqyang** [comment]
Here is the SAMPLE AES specification: https://developer.apple.com/library/archive/documentation/AudioVideo/Conceptual/HLS_Sample_Encryption/Encryption/Encryption.html#//apple_ref/doc/uid/TP40012862-CH2-SW6
