### ISSUE TITLE
Support for live subtitles in DASH stream

### ISSUE THREAD

**Issue by Nixon197** [google/shaka-packager#631]
Hi

We are looking into packaging live subtitles from UDP source -DVB Teletext subtitle for live DASH streams.
Is there any way to do this with shaka packager?

BR

**Comment by kqyang** [comment]
We don't support it directly right now. 

@jakubvojacek and his team got it working by processing it with ccextractor first then send the output to shaka packager. @jakubvojacek, would you be willing to share your set up with @Nixon197? Thanks.

**Comment by TheModMaker** [comment]
Actual teletext will be tracked in #272, a similar format called DVB-SUB is tracked in #832 and is almost done.
