### ISSUE TITLE
HDR10 Support

### ISSUE THREAD

**Issue by jigneshdhruv** [google/shaka-packager#632]
Hello,

Using shaka packager, we can package HDR10 content and we are able to play individual audio/video streams successfully. However we are having trouble playing the master variant and this may be due to the need of additional signaling in HLS master playlist. 

Can you please look into this issue and get it fixed in Shaka Packager.

Thanks,
Jignesh

**Comment by kqyang** [comment]
It is missing VIDEO-RANGE attribute.

From [HLS Authoring Specification for Apple Devices](https://developer.apple.com/documentation/http_live_streaming/hls_authoring_specification_for_apple_devices#topics) 9.16, the VIDEO-RANGE attribute MUST be specified unless all variants and renditions are SDR. 

The attribute is mentioned in the [latest draft HLS specification](https://tools.ietf.org/html/draft-pantos-hls-rfc8216bis-02#section-4.4.4.2).

**Comment by jigneshdhruv** [comment]
Thanks for verifying @kqyang 
Will you be able to add this attribute in the master variant in the upcoming release?

**Comment by jigneshdhruv** [comment]
@kqyang Also note that both FRAME-RATE and VIDEO-RANGE attributes are needed in the master variant.

**Comment by kqyang** [comment]
I moved FRAME-RATE to a separate issue: #634
