### ISSUE TITLE
A query on the support status of multiple HLS master playlists and multiple DASH outputs given a single input

### ISSUE THREAD

**Issue by Brainiarc7** [google/shaka-packager#642]
Hello there,

As stated above, this is a query on whether shaka-packager supports multiple HLS master playlists AND multiple DASH outputs in a single command line.

Compared to the likes of FFmpeg, where multiple outputs can be trivially derived using the [tee pseudo-muxer](https://ffmpeg.org/ffmpeg-formats.html#tee), for example, does such functionality exist in the packager?

**Applicability / feasibility of such a feature:**

There are instances where a deployment may require creating simultaneous duplicate outputs, say, to multiple CDNs as an example where high availability may be  needed without messing around with distributed file systems , etc. 

I've not tested if this is supported by the binary, so perhaps a developer here can comment on this? Thanks.

**Comment by kqyang** [comment]
@Brainiarc7 No. That is not supported. 

> There are instances where a deployment may require creating simultaneous duplicate outputs, say, to multiple CDNs as an example where high availability may be needed without messing around with distributed file systems , etc.

Isn't it easier and more efficient to setup CDN replication in this case?

**Comment by Brainiarc7** [comment]
Isn't it easier and more efficient to setup CDN replication in this case?

It's something I should definitely evaluate in production down the line.
However, being able to trivially handle multiple outputs from a single binary call, given one or more inputs, would still be awesome.

**Comment by kqyang** [comment]
@Brainiarc7 I see. Another way you can handle it is to duplicate the outputs locally before uploading the outputs to cloud. You may want to checkout our new project: https://github.com/google/shaka-streamer. It seems that we can achieve something like this easily there.

I'm closing this issue, but let us know if you have other questions.

**Comment by Brainiarc7** [comment]
I'll definitely take a look, thanks.
