### ISSUE TITLE
Question: Thread mode of the shaka-packager?

### ISSUE THREAD

**Issue by Romantic-LiXuefeng** [google/shaka-packager#649]
Like the title,  I read the architecture document.  
 [https://google.github.io/shaka-packager/html/design.html#architecture-diagram]()

The pipeline of package is described clearly.  Hope give some details info about the thread-mode.

**Comment by kqyang** [comment]
@Romantic-LiXuefeng Are you asking when does shaka-packager create new threads?

**Comment by Romantic-LiXuefeng** [comment]
The media processing pipeline : `demuxer`-> `chunking` -> `encryption(option)` -> `trick play(option)` -> `muxer`   ,I want to know whether these operations doing in different threads or not?

**Comment by kqyang** [comment]
Most processors are single threaded right now. All the listed operations above happen in the same thread. For every new input file, a new demuxer is created and a new thread is spawned.

**Comment by Romantic-LiXuefeng** [comment]
@kqyang  Thanks!  Do you think it's not necessary to transmux a new input file from one container to another container in multi threads?  After all, it is not a time-consuming operation.

**Comment by kqyang** [comment]
Correct.

**Comment by Romantic-LiXuefeng** [comment]
@kqyang  I am worried that it may drop some input data when the input source is living stream and do all the pipeline operations in one thread.
For example:

1.  Read the UDP data through socket into the buffer. 
2. When the `recvfrom()` return successfully,   The thread begin to transmux the media sample one by one until all the received data consumed.  When doing this, the UDP data may still send to Shaka-Packager,  whether these data may drop.

How to solve this scenes?

**Comment by kqyang** [comment]
@Romantic-LiXuefeng Sorry for not making it clearer earlier. All file IOs (including sockets) happens in separate threads and the data is buffered, which is done to solve the problem you mentioned :).

See the implementation in https://github.com/google/shaka-packager/blob/master/packager/file/threaded_io_file.cc and https://github.com/google/shaka-packager/blob/master/packager/file/io_cache.cc for details.
