### ISSUE TITLE
Question: How to insert mid-ad (get from own ad server) into the content when using packager HLS stream?

### ISSUE THREAD

**Issue by Romantic-LiXuefeng** [google/shaka-packager#650]
> ad_cues <start_time[;start_time]>
>  List of cuepoint markers separated by semicolon. The start_time represents the start of the cue marker in seconds (double precision) relative to the start of the program. This flag preconditions content for Dynamic Ad Insertion with Google Ad Manager. For DASH, multiple periods will be generated with period boundaries at the next key frame to the designated start times; For HLS, segments will be terminated at the next key frame to the designated start times and ‘#EXT-X-PLACEMENT-OPPORTUNITY’ tag will be inserted after the segment in media playlist.

I have some questions about this description.
>  This flag preconditions content for Dynamic Ad Insertion with Google Ad Manager. 
1.  Whether this ad options only works with  Google Ad Manager or not.  
     Before packager the HLS stream， I have request the pre-ad, mid-ad and post-ad 
     from our own ad server.   I found `ad_cues <start_time[;start_time]> ` only support 
     adding parameter `start_time`, Can't set the ad url.  If not support setting ad url, please 
    give some advice how to implement this feature.

> For HLS, segments will be terminated at the next key frame to the designated start times and ‘#EXT-X-PLACEMENT-OPPORTUNITY’ tag will be inserted after the segment in media playlist.
2.  I have searched the HLS draft. [https://tools.ietf.org/html/draft-pantos-http-live-streaming-23#section-4.3.4.1](url) .  I'm sorry, nothing has found about the `#EXT-X-PLACEMENT-OPPORTUNITY` tag.  
Also, I searched the `ExoPlayer`, the player also do nothing about this Tag.  Please hope give some useful information.

**Comment by kqyang** [comment]
Shaka Packager does not insert the Ads itself. What it does is to precondition the content for Ad insertion. 

#EXT-X-PLACEMENT-OPPORTUNITY is a Google extension for Ad Insertion. If you don't use Google Ad Manager, what you can do is to replace #EXT-X-PLACEMENT-OPPORTUNITY with #EXT-X-DISCONTINUITY followed by Ad segments (#EXTINF...) yourself.

@Romantic-LiXuefeng  Does that answer your question?

**Comment by Romantic-LiXuefeng** [comment]
Because of the Chine Internet firewall, i can't use the Google Ad Manager, so that I can't run a example with the options `ad_cues <start_time[;start_time]> ` to check the result HLS manifest. 

1. Whether the Shaka Packager only add a `#EXT-X-PLACEMENT-OPPORTUNITY` Tag.  The packager result like this. 
```
#EXTM3U
#EXT-X-VERSION:6
## Generated with https://github.com/google/shaka-packager version <tag>-<hash>-<test>
#EXT-X-TARGETDURATION:2
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-MAP:URI="bear-640x360-video-init.mp4"
#EXTINF:1.001,
bear-640x360-video-1.m4s
#EXTINF:1.001,
bear-640x360-video-2.m4s
#EXT-X-PLACEMENT-OPPORTUNITY
#EXTINF:0.734,
bear-640x360-video-3.m4s
#EXT-X-ENDLIST
```
from [https://github.com/google/shaka-packager/tree/master/packager/app/test/testdata/hls-audio-video-text-with-ad-cues](url)

I want to know when to insert the ad? If not insert ad, the player how to play ?

**Comment by kqyang** [comment]
#EXT-X-PLACEMENT-OPPORTUNITY is the place to insert mid-roll Ads. As mentioned earlier, you can just replace it with your Ad segment tags. 

For example, you have a mid-roll ad segment you want to insert: mid_roll_ad.ts

Packager pre-conditioned playlist:
```
#EXTM3U
#EXT-X-VERSION:6
## Generated with https://github.com/google/shaka-packager version <tag>-<hash>-<test>
#EXT-X-TARGETDURATION:2
#EXT-X-PLAYLIST-TYPE:VOD
#EXTINF:1.001,
bear-640x360-video-1.ts
#EXTINF:1.001,
bear-640x360-video-2.ts
#EXT-X-PLACEMENT-OPPORTUNITY
#EXTINF:0.734,
bear-640x360-video-3.ts
#EXT-X-ENDLIST
```

You can replace #EXT-X-PLACEMENT-OPPORTUNITY with your Ad segment:
```
#EXTM3U
#EXT-X-VERSION:6
## Generated with https://github.com/google/shaka-packager version <tag>-<hash>-<test>
#EXT-X-TARGETDURATION:2
#EXT-X-PLAYLIST-TYPE:VOD
#EXTINF:1.001,
bear-640x360-video-1.ts
#EXTINF:1.001,
bear-640x360-video-2.ts
#EXT-X-DISCONTINUITY
#EXTINF:1.000,
mid_roll_ad.ts
#EXT-X-DISCONTINUITY
#EXTINF:0.734,
bear-640x360-video-3.ts
#EXT-X-ENDLIST
```

As for pre-roll and post-roll ads, you can just insert it before all media segments and after all media segments respectively. They don't really need ads pre-conditioning.

>  If not insert ad, the player how to play ?

It should just work as the player ignores unrecognized tags according to HLS specification.

**Comment by Romantic-LiXuefeng** [comment]
ok! Thanks for your help.

**Comment by Romantic-LiXuefeng** [comment]
@kqyang  Just doing as your device to insert the mid ad. Not play correctly using `ExoPlayer`.  I have report a issue to `ExoPlayer`. But I can't confirm whether the bug of `ExoPlayer`.  # https://github.com/google/ExoPlayer/issues/6444

**Comment by kqyang** [comment]
Have you tried Shaka Player?

**Comment by Romantic-LiXuefeng** [comment]
@kqyang  I'm sorry. I'm not similar to Shaka Player, and try to play with it.  If have some result, I will report.  I also have sent the content to [shaka-packager-issues@google.com](url).

**Comment by Romantic-LiXuefeng** [comment]
```
First segment 1.aac starts at 0
hls_parser.js:698 Guessing stream type for #EXT-X-STREAM-INF:BANDWIDTH=5036450,AVERAGE-BANDWIDTH=2196630,CODECS="avc1.64001f,mp4a.40.2",RESOLUTION="1280x720",AUDIO="default-audio-group",URI="/media/mp4_to_hls/h264_1080p/h264.m3u8"
hls_parser.js:742 Guessing video.
hls_parser.js:1512 First segment 1.ts starts at 0.1
stream_utils.js:148 Dropping variant - audio not compatible with platform type=audio codecs=mp4a.40.2 bandwidth=undefined channelsCount=2
player.js:310 The walker saw an error:
(anonymous) @ player.js:310
$jscomp.generator.Engine_.nextStep_ @ generator_engine] :795
$jscomp.generator.Engine_.next_ @ generator_engine] :699
next @ generator_engine] :833
(anonymous) @ execute_async_generator] :68
$jscomp.asyncExecutePromiseGenerator @ execute_async_generator] :55
$jscomp.asyncExecutePromiseGeneratorFunction @ execute_async_generator] :99
handleError @ player.js:309
(anonymous) @ walker.js:376
$jscomp.generator.Engine_.nextStep_ @ generator_engine] :795
$jscomp.generator.Engine_.throw_ @ generator_engine] :745
throw @ generator_engine] :838
c @ execute_async_generator] :52
Promise.then (async)
f @ execute_async_generator] :62
(anonymous) @ execute_async_generator] :68
$jscomp.asyncExecutePromiseGenerator @ execute_async_generator] :55
$jscomp.asyncExecutePromiseGeneratorFunction @ execute_async_generator] :99
shaka.routing.Walker.takeNextStep_ @ walker.js:324
shaka.routing.Walker.doOneThing_ @ walker.js:231
(anonymous) @ walker.js:212
$jscomp.generator.Engine_.nextStep_ @ generator_engine] :795
$jscomp.generator.Engine_.next_ @ generator_engine] :699
next @ generator_engine] :833
b @ execute_async_generator] :48
Promise.then (async)
f @ execute_async_generator] :62
Promise.then (async)
f @ execute_async_generator] :62
Promise.then (async)
f @ execute_async_generator] :62
Promise.then (async)
f @ execute_async_generator] :62
Promise.then (async)
f @ execute_async_generator] :62
(anonymous) @ execute_async_generator] :68
$jscomp.asyncExecutePromiseGenerator @ execute_async_gene
```
@kqyang  [https://github.com/google/shaka-player/blob/master/docs/tutorials/basic-usage.md](),Doing by the description in the `tutorials/basic-usage.md`, the shaka player can't start to play.
I also test a url [http://n2.vod01.icntvcdn.com/newtv2/2016/11/01/hanzhan2/hanzhan2.m3u8](url) in Internet, the shaka player also can't start to play. I'm not sure whether using the shaka player not correctly.

**Comment by Romantic-LiXuefeng** [comment]
@kqyang  I followed the description in [https://github.com/google/shaka-player/blob/master/docs/tutorials/basic-usage.md](url). Can't start to play.  I also start to play the stream using Safari browser. It plays well.

**Comment by kqyang** [comment]
@Romantic-LiXuefeng You can just use the demo player at: https://shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;panel=HOME;build=uncompiled. 

Looks like ExoPlayer team has already figured out where the problem is :)

**Comment by Romantic-LiXuefeng** [comment]
@kqyang The ExoPlayer team has fixed the problem.   Hope to support muxing all the streams into TS container for reducing the process of demuxing ads into separate streams.

Also, there is a bug, Using Docker with latest version to insert multi mid ads, e.g. 60s and 120s. Only the first mid ad can generate `#EXT-X-PLACEMENT-OPPORTUNITY` Tag. others failed.
```
/ # packager 'in=/media/google_io_2017.mp4,stream=video,segment_template=/media/mp4_to_hls/h264_1080p/h264/$Number$.ts,playlist_name=/h264_1080p/h264.m3u8' \
>    'in=/media/google_io_2017.mp4,stream=audio,segment_template=/media/mp4_to_hls/h264_1080p/aac/$Number$.aac,playlist_name=/h264_1080p/aac.m3u8' \
>     --ad_cues 60;120 \
>             --segment_duration 10 \
>     --hls_master_playlist_output /media/mp4_to_hls/h264_master.m3u8
[0923/015017:INFO:demuxer.cc(88)] Demuxer::Run() on file '/media/google_io_2017.mp4'.
[0923/015017:INFO:demuxer.cc(160)] Initialize Demuxer for file '/media/google_io_2017.mp4'.
Packaging completed successfully.
/bin/sh: 120: not found
```

**Comment by kqyang** [comment]
@Romantic-LiXuefeng Can you provide the source stream you were using? We can try if we can re-produce the problem.

**Comment by Romantic-LiXuefeng** [comment]
I have sent the source stream to [shaka-packager-issues@google.com](url).

**Comment by kqyang** [comment]
@Romantic-LiXuefeng It works for me. Note that ";" is a special character in some Linux shells, so remember to enclose it (e.g. enclose in '': '60;120') or skip it (i.e. 60\;120) if you run the command in Linux shells. 

```m3u8
#EXTM3U
#EXT-X-VERSION:6
## Generated with https://github.com/google/shaka-packager version 3aa0bd6938-debug
#EXT-X-TARGETDURATION:20
#EXT-X-PLAYLIST-TYPE:VOD
#EXTINF:10.000,
1.ts
#EXTINF:16.000,
2.ts
#EXTINF:10.000,
3.ts
#EXTINF:10.000,
4.ts
#EXTINF:10.000,
5.ts
#EXTINF:9.800,
6.ts
#EXT-X-PLACEMENT-OPPORTUNITY
#EXTINF:10.680,
7.ts
#EXTINF:10.000,
8.ts
#EXTINF:10.000,
9.ts
#EXTINF:10.000,
10.ts
#EXTINF:12.440,
11.ts
#EXTINF:10.000,
12.ts
#EXT-X-PLACEMENT-OPPORTUNITY
#EXTINF:10.000,
13.ts
#EXTINF:10.000,
14.ts
#EXTINF:19.920,
15.ts
#EXTINF:9.960,
16.ts
#EXTINF:0.360,
17.ts
#EXTINF:10.000,
18.ts
#EXTINF:9.960,
19.ts
#EXTINF:3.680,
20.ts
#EXT-X-ENDLIST
```
