### ISSUE TITLE
Unable to write to a path with unicode characters on Linux (but works on MacOS)

### ISSUE THREAD

**Issue by vectronic** [google/shaka-packager#652]
## System info
**Operating System**: macOS Mojave 10.14.6 and Debian GNU/Linux 10 4.9.184-linuxkit 
**Shaka Packager Version**: v2.3.0-5bf8ad5-release

## Issue and steps to reproduce the problem

On MacOS, packaging works when output path contains UTF-8 characters. On Linux, it does not...

**Packager Command**:
On MacOS:

```
shaka in=/media/video-only.mp4,stream=video,output=/tmp/από/video.mp4,playlist_name=video.m3u8 --segment_duration 4 --fragment_duration 4 --hls_playlist_type VOD --hls_master_playlist_output /tmp/από/master.m3u8
```

produces:

```
[0911/163623:INFO:demuxer.cc(88)] Demuxer::Run() on file /media/video-only.mp4'.
[0911/163623:INFO:demuxer.cc(160)] Initialize Demuxer for file '/media/video-only.mp4'.
[0911/163623:INFO:single_segment_segmenter.cc(107)] Update media header (moov) and rewrite the file to '/tmp/από/video.mp4'.
[0911/163623:INFO:mp4_muxer.cc(171)] MP4 file '/tmp/από/video.mp4' finalized.
Packaging completed successfully.
```

However on Linux (via docker), the same effective command:

```
docker run -it --rm -v /media:/media -v /tmp:/tmp testcontainer \ 
shaka in=/media/video-only.mp4,stream=video,output=/tmp/από/video.mp4,playlist_name=video.m3u8 --segment_duration 4 --fragment_duration 4 --hls_playlist_type VOD --hls_master_playlist_output /tmp/από/master.m3u8 
```

produces:

```
[0911/154016:INFO:demuxer.cc(88)] Demuxer::Run() on file '/media/video-only.mp4'.
[0911/154016:INFO:demuxer.cc(160)] Initialize Demuxer for file '/media/video-only.mp4'.
[0911/154016:ERROR:packager_main.cc(523)] Packaging Error: 5 (FILE_FAILURE): Cannot open file to write /tmp/από/video.mp4
```

**What is the expected result?**

The command running on Linux should not have a FILE_FAILURE error. 

**What happens instead?**

The command running on Linux is unable to write to a path containing unicode characters.

**Further Notes**

For sanity I have invoked the Linux command using no UTF-8 characters and it works:

```
docker run -it --rm -v /media:/media -v /tmp:/tmp testcontainer \
shaka in=/media/video-only.mp4,stream=video,output=/tmp/abc/video.mp4,playlist_name=video.m3u8 --segment_duration 4 --fragment_duration 4 --hls_playlist_type VOD --hls_master_playlist_output /tmp/abc/master.m3u8 
```

produces:

```
[0911/155604:INFO:demuxer.cc(88)] Demuxer::Run() on file '/media/video-only.mp4'.
[0911/155604:INFO:demuxer.cc(160)] Initialize Demuxer for file '/media/video-only.mp4'.
[0911/155604:INFO:single_segment_segmenter.cc(107)] Update media header (moov) and rewrite the file to '/tmp/abc/video.mp4'.
[0911/155604:INFO:mp4_muxer.cc(171)] MP4 file '/tmp/abc/video.mp4' finalized.
Packaging completed successfully.
```

To rule out Docker volume mount issues, I have also tried writing to the Linux filesystem instead of the Docker host mounted `/tmp` location and this also does not work with UTF-8 characters as follows:

```
docker run -it --rm -v /media:/media testcontainer /bin/bash
```
followed by:
```
shaka in=/media/video-only.mp4,stream=video,output=/tmp/από/video.mp4,playlist_name=video.m3u8 --segment_duration 4 --fragment_duration 4 --hls_playlist_type VOD --hls_master_playlist_output /tmp/από/master.m3u8
[0912/161628:INFO:demuxer.cc(88)] Demuxer::Run() on file '/media/video-only.mp4'.
[0912/161628:INFO:demuxer.cc(160)] Initialize Demuxer for file '/media/video-only.mp4'.
[0912/161628:ERROR:packager_main.cc(523)] Packaging Error: 5 (FILE_FAILURE): Cannot open file to write /tmp/από/video.mp4
```

I have also tried escaping the characters as follows:

```
docker run -it --rm -v /media:/media testcontainer /bin/bash
```
followed by:
```
shaka in=/media/video-only.mp4,stream=video,output=/tmp/''$'\316\261\317\200\317\214'/video.mp4,playlist_name=video.m3u8 --segment_duration 4 --fragment_duration 4 --hls_playlist_type VOD --hls_master_playlist_output /tmp/''$'\316\261\317\200\317\214'/master.m3u8
[0912/161756:INFO:demuxer.cc(88)] Demuxer::Run() on file '/media/video-only.mp4'.
[0912/161756:INFO:demuxer.cc(160)] Initialize Demuxer for file '/media/video-only.mp4'.
[0912/161756:ERROR:packager_main.cc(523)] Packaging Error: 5 (FILE_FAILURE): Cannot open file to write /tmp/από/video.mp4
```

I have also checked the `locale` on each environment and they are both set as follows:

MacOS:

```
nick$ locale
LANG="en_GB.UTF-8"
LC_COLLATE="en_GB.UTF-8"
LC_CTYPE="en_GB.UTF-8"
LC_MESSAGES="en_GB.UTF-8"
LC_MONETARY="en_GB.UTF-8"
LC_NUMERIC="en_GB.UTF-8"
LC_TIME="en_GB.UTF-8"
LC_ALL=
```

Linux:

```
nick$ docker run -it --rm testcontainer locale
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=en_GB.UTF-8
LANGUAGE=
LC_CTYPE="en_GB.UTF-8"
LC_NUMERIC="en_GB.UTF-8"
LC_TIME="en_GB.UTF-8"
LC_COLLATE="en_GB.UTF-8"
LC_MONETARY="en_GB.UTF-8"
LC_MESSAGES="en_GB.UTF-8"
LC_PAPER="en_GB.UTF-8"
LC_NAME="en_GB.UTF-8"
LC_ADDRESS="en_GB.UTF-8"
LC_TELEPHONE="en_GB.UTF-8"
LC_MEASUREMENT="en_GB.UTF-8"
LC_IDENTIFICATION="en_GB.UTF-8"
LC_ALL=
```

I have also changed the locale to `LANG=c.UTF-8` with no success.

I cannot see any differences in the build configs for releasing Shaka, the source for Shaka or the environments I am testing which would explain why support for output paths containing UTF-8 characters works on MacOS but not Linux.

I am happy to do any further investigations required and/or submit PRs if you can point me to what needs to change.

**Comment by dim** [comment]
Any update on this? Same problem v2.6.1 and umlauts, e.g. `äöü`, etc

**Comment by joeyparrish** [comment]
Sorry, no update.  The community is busy refactoring the build system and dependencies right now, and nobody has looked at this issue.

The good news is that @kqyang said:

> I did an initial investigation. Looks like it is a problem in base::FilePath::FromUTF8Unsafe: https://github.com/shaka-project/shaka-packager/blob/d5ca6e84e6ccd543dc9a79ccc8d07b702010f491/packager/file/local_file.cc#L185

But all use of chromium's `base::` namespace is going away.  In the `cmake` branch, where that work is happening, that has been replaced with C++ standard library calls to the `std::filesystem::` namespace:

https://github.com/shaka-project/shaka-packager/blob/14a708d009a32aa98a609c4c2e6f98024ec3b8ff/packager/file/local_file.cc#L113

So it is likely that your problem will be solved by the porting work we're doing now.  You can follow along in #1047 (CMake porting) and #346 (replacing base:: with std:: and absl::).

The `cmake` branch isn't fully functional yet, but the file code there is done.  We could add a regression test to that branch to ensure that umlauts in path names are working on all platforms.
