### ISSUE TITLE
Question: How to ensure multi-rate synchronous outputs?

### ISSUE THREAD

**Issue by Romantic-LiXuefeng** [google/shaka-packager#655]
```
$ packager \
  'in=udp://225.1.1.8:8001?interface=172.29.46.122,stream=audio,init_segment=audio_init.mp4,segment_template=audio_$Number$.m4s,playlist_name=audio.m3u8,hls_group_id=audio,hls_name=ENGLISH' \
  'in=udp://225.1.1.8:8001?interface=172.29.46.122,stream=video,init_segment=h264_360p_init.mp4,segment_template=h264_360p_$Number$.m4s,playlist_name=h264_360p.m3u8' \
  'in=udp://225.1.1.8:8002?interface=172.29.46.122,stream=video,init_segment=h264_480p_init.mp4,segment_template=h264_480p_$Number$.m4s,playlist_name=h264_480p.m3u8' \
  'in=udp://225.1.1.8:8003?interface=172.29.46.122,stream=video,init_segment=h264_720p_init.mp4,segment_template=h264_720p_$Number$.m4s,playlist_name=h264_720p.m3u8' \
  'in=udp://225.1.1.8:8004?interface=172.29.46.122,stream=video,init_segment=h264_1080p_init.mp4,segment_template=h264_1080p_$Number$.m4s,playlist_name=h264_1080p.m3u8' \
  --hls_master_playlist_output h264_master.m3u8 \
  --hls_playlist_type LIVE
```
Like the above command, for the living stream, multi-inputs and multi-outputs for different bitrate. That is, multi packager pipelines are worked in parallel.   How to balance the pipelines to ensure the multi-rate outputs in synchronous?  Avoid the following scene，
When the player adaptively switches between different bitrate rates living streams according to network changes.  Avoid the stream which want to switch produce too low, has not generate the segment which want to switch. 

I have not find any code about balancing the `jobs` in `JobManager` .

**Comment by kqyang** [comment]
@Romantic-LiXuefeng For live streaming, we assume the input is more or less synchronized, thus we don't have any internal synchronizations. Is that assumption not true?

**Comment by Romantic-LiXuefeng** [comment]
In my opinion,  The packager server should ensure the adaptive living streaming's Manifests(e.g HLS media playlist)  contains the same segments at the same time.   For example: 
```
1080p media playlist: 
 ../1080p/segment2.ts
 ../1080p/segment3.ts
 ../1080p/segment4.ts
```

```
720p media playlist: 
 ../720p/segment2.ts
 ../720p/segment3.ts
 ../720p/segment4.ts
```

Only in this way，the player client can switch in different bitrate streams seamlessly. 
But now, multi packager pipelines are worked in different threads scheduled by OS , I think can't ensure the output in synchronized.   If I have any misunderstanding, please don’t hesitate to point out.

**Comment by kqyang** [comment]
@Romantic-LiXuefeng I agree with you that the output should be synchronized. 

We have two assumptions for live packaging:
- The inputs are synchronized
- There are enough CPU powers on the packaging machine

If the inputs are not synchronized, even if we do have some logic internally in packager to perform synchronizations, it does not help much. 

On the other hand, if the inputs are synchronized, the outputs are synchronized automatically without extra work.

I think our assumptions are realistic and works in practice. Let us know if it is not the case.
