### ISSUE TITLE
Playback stucks when using shaka-packager to gengerate live content

### ISSUE THREAD

**Issue by weiyuefei** [google/shaka-packager#657]
## System info
**Operating System**: 
Distributor ID:	CentOS
Description:	CentOS Linux release 7.3.1611 (Core) 
Release:	7.3.1611
Codename:	Core

**Shaka Packager Version**: 
packager version v2.3.0-5bf8ad5-release

## Issue and steps to reproduce the problem

**Packager Command**:
packager \
	'in=udp://127.0.0.1:40000?stream=audio,init_segment=audio_init.mp4,segment_template=audio_$Number$.m4s,playlist_name=audio.m3u8,hls_group_id=audio,hls_name=ENGLISH' \
	'in=udp://127.0.0.1:40000?stream=video,init_segment=video_init.mp4,segment_template=video_$Number$.m4s,playlist_name=video.m3u8' \
	--preserved_segments_outside_live_window 3 --segment_duration 6 --time_shift_buffer_depth 30 --hls_master_playlist_output master.m3u8 \
	--hls_playlist_type LIVE --allow_approximate_segment_timeline

Extra steps to reproduce the problem?
(1) Upload the source content to server in /root/content,  I have already sent the content to shaka-packager-issues@google.com.

(2) Run packager command in path /root/content/live: 
packager \
	'in=udp://127.0.0.1:40000?stream=audio,init_segment=audio_init.mp4,segment_template=audio_$Number$.m4s,playlist_name=audio.m3u8,hls_group_id=audio,hls_name=ENGLISH' \
	'in=udp://127.0.0.1:40000?stream=video,init_segment=video_init.mp4,segment_template=video_$Number$.m4s,playlist_name=video.m3u8' \
	--preserved_segments_outside_live_window 3 --segment_duration 6 --time_shift_buffer_depth 30 --hls_master_playlist_output master.m3u8 \
	--hls_playlist_type LIVE --allow_approximate_segment_timeline

(3) Open another command window, cd /root/content, and run ffmpeg command as follows:
ffmpeg -re -i h265.mp4 -vcodec copy -acodec aac -f mpegts -y udp://225.0.0.3:40000

(4) Play the live content generated by shaka-packager, using ExoPlayer/Shaka-Player/VLC etc.

What is the expected result?
The player should play smoothly.

What happens instead?
The playback is very unsmooth, sometimes stucks.

<Please attach the input files or email to shaka-packager-issues@google.com.>
I have recorded the source live stream into a mp4 file, and  I have already sent the recorded mp4 to shaka-packager-issues@google.com.

<Please provide any additional information below.>
Firstly, we try to open the recorded mp4 by VLC locally, and it plays smoothly.
Then, we then try to package the recorded mp4 into vod content using shaka-packager, and it plays smoothly too. 
Finally, we use FFMPEG to push the recorded mp4 as a live stream to shaka-packager, in this case, the player plays unsmoothly or even stucks.

**Comment by weiyuefei** [comment]
Hi @kqyang, do you have any idea on this issue?

**Comment by kqyang** [comment]
@weiyuefei Since you can play vod content smoothly, it does look like a packaging problem. I suspect that it is resource or network problem.

I have a couple of questions:

- Are you running ffmpeg and packager in the same machine?
- Is the packaged content served from the same machine or did you upload it to another web server?
- Have you tried Shaka-Player? 
- Do you see any logging in ffmpeg or in packager? 

I'll see if I can re-produce your problem.

**Comment by weiyuefei** [comment]
Hi @kqyang, sorry for the late reply.  

> I have a couple of questions:
> 
> * Are you running ffmpeg and packager in the same machine?

Yes, on the same machine.
> * Is the packaged content served from the same machine or did you upload it to another web server?

In our production environment, we uploaded the packaged content to another web server. In this issue described above, the packaged content was served from the same machine.
> * Have you tried Shaka-Player?

Not yet.
> * Do you see any logging in ffmpeg or in packager?

On FFMPEG side, there were loggings as follows:
![企业微信截图_15704965718763](https://user-images.githubusercontent.com/15873219/66359795-1014f880-e9ab-11e9-8136-b474d1c483fa.png)

And on Packager side,  there were loggings as follows:
![企业微信截图_157049661322](https://user-images.githubusercontent.com/15873219/66359910-7568e980-e9ab-11e9-9884-9f80e17d7591.png)
