### ISSUE TITLE
Question: Generate HLS stream with SAMPLE-AES encryption with identity key format

### ISSUE THREAD

**Issue by Romantic-LiXuefeng** [google/shaka-packager#659]
Just as the described in the HLS draft document. 
[https://tools.ietf.org/html/draft-pantos-http-live-streaming-23#section-4.3.2.4](url)
#EXT-X-KEY:<attribute-list>
> An encryption method of AES-128 signals that Media Segments are
      completely encrypted using the Advanced Encryption Standard
      [AES_128] with a 128-bit key, Cipher Block Chaining, and PKCS7
      padding [RFC5652].  CBC is restarted on each segment boundary,
      using either the IV attribute value or the Media Sequence Number
      as the IV; see Section 5.2.

**Comment by weiyuefei** [comment]
AES-128 is not supported by shaka-packager currently.

**Comment by kqyang** [comment]
@weiyuefei is right. We do not support AES-128 right now. I am interested in your use case. What is the reason that you want to use AES-128 instead of SAMPLE-AES?

**Comment by Romantic-LiXuefeng** [comment]
@kqyang Do you think the SAMPLE-AES encryption is more popular than AES-128? What's the benefit of the SAMPLE-AES than AES-128. There is no document in the HLS draft. The reason why I'm interested in AES-128 right now, just because of most players have not implements the sample-based SAMPLE-AES decryption.  Such as  `ExoPlayer`, it only support AES-128 right now. Our Android team is using it. I'm the beginner of how to encryption.

**Comment by kqyang** [comment]
@Romantic-LiXuefeng Yes, SAMPLE-AES is a sample based encryption scheme. It allows the streams to be processed even before it is decrypted. SAMPLE-AES in mp4 is compatible with industry [Common Encryption standard](https://www.iso.org/standard/68042.html). 

> There is no document about this in the HLS draft. 

That is not true. It is specified in [HLS specification](https://tools.ietf.org/html/rfc8216#page-15) and also [Apple's encryption specification](https://developer.apple.com/library/archive/documentation/AudioVideo/Conceptual/HLS_Sample_Encryption/Encryption/Encryption.html).

> Such as ExoPlayer, it only support AES-128 right now

That is not completely true. ExoPlayer supports SAMPLE-AES in mp4, which is basically the same as 'cbcs' encryption scheme in [CENC](https://www.iso.org/standard/68042.html).

**Comment by Romantic-LiXuefeng** [comment]
@kqyang  How to generate the HLS stream with non-CDM SAMPLE-AES protection? #https://github.com/google/ExoPlayer/issues/6488 . As the reference `Exoplayer` issue, we want to implement the feature, but we have no test content.

**Comment by Romantic-LiXuefeng** [comment]
@kqyang  Thanks very much for your help.
