### ISSUE TITLE
Wrong frame rate in output MPD with TS input

### ISSUE THREAD

**Issue by joeyparrish** [google/shaka-packager#662]
## System info
**Operating System**: gLinux / Debian testing
**Shaka Packager Version**: v2.3.0-5bf8ad5-release

## Issue and steps to reproduce the problem

**Packager Command**:

```sh
wget https://storage.googleapis.com/shaka-streamer-assets/test-assets/Sintel.2010.720p.Small.mkv

# Transcode into a TS container.
ffmpeg \
  -y -loglevel error \
  -to 0:01 -i Sintel.2010.720p.Small.mkv \
  -an -c:v h264 -b:v 3M intermediate.ts

# Package that TS into MP4 in DASH.
packager \
  'in=intermediate.ts,stream=video,output=from_ts.mp4' \
  --mpd_output from_ts.mpd

# Transcode into an MP4 container.
ffmpeg \
  -y \
  -to 0:01 -i Sintel.2010.720p.Small.mkv \
  -an -c:v h264 -b:v 3M intermediate.mp4

# Package that MP4 into MP4 in DASH, in a different manifest file from before.
packager \
  'in=intermediate.mp4,stream=video,output=from_mp4.mp4' \
  --mpd_output from_mp4.mpd
```

What is the expected result?

I would expect the frame rate in the MPD to be correct in both cases.

What happens instead?

The frame rate of the input file is 24 fps according to ffprobe.  The frame rate of both intermediate.ts and intermediate.mp4 are 24 fps according to ffprobe.  After packaging, the frame rate of both from_mp4.mp4 and from_ts.mp4 are 24 fps.

In from_mp4.mpd, the `frameRate` attribute is `12288/512`, or 24 fps.

In from_ts.mpd, the `frameRate` attribute is `90000/7500`, or **12** fps.

Something seems to go wrong when the intermediate file is TS instead of MP4.

If you run the same test with a different source file (https://storage.googleapis.com/shaka-streamer-assets/sample-inputs/Sintel.2010.720p.mkv), Packager does the right thing.  It's not clear why that would be.

**Comment by kqyang** [comment]
@joeyparrish Thanks for the report. Will take a look.

**Comment by kqyang** [comment]
I assume this is caused by the same problem as #751. Mark it as a duplicate.
