### ISSUE TITLE
The resolution of some live stream in HLS output master playlist suggested  incorrectly

### ISSUE THREAD

**Issue by Romantic-LiXuefeng** [google/shaka-packager#663]
## System info
**Operating System**:  macOS Mojave 10.14
**Shaka Packager Version**:  The least release version

@kqyang As described in @https://github.com/google/shaka-streamer/issues/36.

**Comment by kqyang** [comment]
@Romantic-LiXuefeng I think this is a bug in ExoPlayer. See https://github.com/google/ExoPlayer/issues/6551#issuecomment-543383218 for details.

**Comment by Romantic-LiXuefeng** [comment]
@kqyang  I have a question to ask which maybe not associate with this `shaka-packager`.
 As your described in [6551#issuecomment](https://github.com/google/ExoPlayer/issues/6551#issuecomment-543383218).  I believe you are familiar with the [DAR, SAR,PAR]. So I hope you give me some advice.
My use case is:
Our content sources are news which contains government leaderships, So the player can't display deformation. 
1.  There exists some source which infos is 768x576 [SAR 4:3 DAR 16:9]. (dump by `FFmpeg`)
2. The `Android MediaPlayer` hasn't given interface to get the display aspect ratio[DAR 16:9].
3. Our OTT Tv device's screen size always 16:9.

There is a deformation when `MediaPlayer` to display this source.
(The frame [width x height] is [768x576], this aspect ratio is  [4:3],  I match with the screen[16:9] , so  the display is deformation).

So I need to transcode this source, **but I don't want to  reduce the quality of frame, that is I don't want to change the frame width and height.** 
resulting into the transcoded source info is 768x576 [SAR 1:1 DAR 4:3].  Hope you give some `FFmpeg` command.

**Comment by kqyang** [comment]
@Romantic-LiXuefeng You can specify SAR or DAR during transcoding. See https://video.stackexchange.com/questions/9947/how-do-i-change-frame-size-preserving-width-using-ffmpeg/9967.
