### ISSUE TITLE
[MPEG2 TS] Packager fails with SPS/PPS in the end of access units

### ISSUE THREAD

**Issue by Romantic-LiXuefeng** [google/shaka-packager#665]
## System info
**Operating System**: <e.g. macOS Mojave, version10.14>
**packager version** : v2.3.0-5bf8ad5-release

- UDP socket
```
packager \
  'in=udp://127.0.0.1:40000,stream=audio,init_segment=live_cam_audio.mp4,segment_template=live_cam_audio_$Number$.m4s' \
  'in=udp://127.0.0.1:40000,stream=video,init_segment=live_cam_video.mp4,segment_template=live_cam_video_$Number$.m4s' \
  --mpd_output live_cam.mpd \
  --io_block_size 65536
```
```
$ ffmpeg -re -stream_loop 100 -thread_queue_size 200 -i media/google_io_2017.mp4 -vcodec copy -acodec copy -f mpegts udp://127.0.0.1:40000
```
The console logs:
```
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'media/google_io_2017.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 1
    compatible_brands: isomavc1iso6
    creation_time   : 2017-02-03T03:59:54.000000Z
    album           : Yinyuetai
    artist          : yinyuetai.com
    comment         : Yinyuetai-1TR1166
    date            : 02/03/17 11:59:53
  Duration: 00:03:23.20, start: 0.000000, bitrate: 2124 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1280x720, 2028 kb/s, 25 fps, 25 tbr, 25k tbn, 50 tbc (default)
    Metadata:
      creation_time   : 2017-02-03T03:59:54.000000Z
      handler_name    : 264@GPAC0.5.1-DEV-rev5472
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 95 kb/s (default)
    Metadata:
      creation_time   : 2017-02-03T03:57:11.000000Z
      handler_name    : Sound Media Handler
Output #0, mpegts, to 'udp://127.0.0.1:40000':
  Metadata:
    major_brand     : isom
    minor_version   : 1
    compatible_brands: isomavc1iso6
    date            : 02/03/17 11:59:53
    album           : Yinyuetai
    artist          : yinyuetai.com
    comment         : Yinyuetai-1TR1166
    encoder         : Lavf58.20.100
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1280x720, q=2-31, 2028 kb/s, 25 fps, 25 tbr, 90k tbn, 25k tbc (default)
    Metadata:
      creation_time   : 2017-02-03T03:59:54.000000Z
      handler_name    : 264@GPAC0.5.1-DEV-rev5472
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 95 kb/s (default)
    Metadata:
      creation_time   : 2017-02-03T03:57:11.000000Z
      handler_name    : Sound Media Handler
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame=  360 fps= 25 q=-1.0 Lsize=     998kB time=00:00:14.28 bitrate= 572.7kbits/s speed=   1x    
video:727kB audio:147kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 14.252379%
```
```
[1018/112143:INFO:demuxer.cc(88)] Demuxer::Run() on file 'udp://127.0.0.1:40000'.
[1018/112143:INFO:demuxer.cc(160)] Initialize Demuxer for file 'udp://127.0.0.1:40000'.
[1018/112156:ERROR:packager_main.cc(523)] Packaging Error: 8 (PARSER_FAILURE): Cannot parse media file udp://127.0.0.1:40000
```

- pipe
```
mkfifo pipe1

packager \
  'in=pipe1,stream=audio,init_segment=live_cam_audio.mp4,segment_template=live_cam_audio_$Number$.m4s' \
  'in=pipe1,stream=video,init_segment=live_cam_video.mp4,segment_template=live_cam_video_$Number$.m4s' \
  --mpd_output live_cam.mpd

ffmpeg -re -stream_loop 100 -thread_queue_size 200 -i media/google_io_2017.mp4 -vcodec copy -acodec copy -f mpegts pipe: > pipe1
```
The console logs:
```
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'media/google_io_2017.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 1
    compatible_brands: isomavc1iso6
    creation_time   : 2017-02-03T03:59:54.000000Z
    album           : Yinyuetai
    artist          : yinyuetai.com
    comment         : Yinyuetai-1TR1166
    date            : 02/03/17 11:59:53
  Duration: 00:03:23.20, start: 0.000000, bitrate: 2124 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1280x720, 2028 kb/s, 25 fps, 25 tbr, 25k tbn, 50 tbc (default)
    Metadata:
      creation_time   : 2017-02-03T03:59:54.000000Z
      handler_name    : 264@GPAC0.5.1-DEV-rev5472
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 95 kb/s (default)
    Metadata:
      creation_time   : 2017-02-03T03:57:11.000000Z
      handler_name    : Sound Media Handler
Output #0, mpegts, to 'pipe:':
  Metadata:
    major_brand     : isom
    minor_version   : 1
    compatible_brands: isomavc1iso6
    date            : 02/03/17 11:59:53
    album           : Yinyuetai
    artist          : yinyuetai.com
    comment         : Yinyuetai-1TR1166
    encoder         : Lavf58.20.100
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 1280x720, q=2-31, 2028 kb/s, 25 fps, 25 tbr, 90k tbn, 25k tbc (default)
    Metadata:
      creation_time   : 2017-02-03T03:59:54.000000Z
      handler_name    : 264@GPAC0.5.1-DEV-rev5472
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 95 kb/s (default)
    Metadata:
      creation_time   : 2017-02-03T03:57:11.000000Z
      handler_name    : Sound Media Handler
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
av_interleaved_write_frame(): Broken pipeB time=00:00:11.14 bitrate= 506.6kbits/s speed=   1x    
Error writing trailer of pipe:: Broken pipe
frame=  289 fps= 25 q=-1.0 Lsize=     711kB time=00:00:11.44 bitrate= 509.3kbits/s speed=0.999x    
video:529kB audio:111kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 11.130236%
Conversion failed!
```
```
[1018/113337:INFO:demuxer.cc(88)] Demuxer::Run() on file 'pipe1'.
[1018/113337:INFO:demuxer.cc(160)] Initialize Demuxer for file 'pipe1'.
[1018/113400:ERROR:packager_main.cc(523)] Packaging Error: 8 (PARSER_FAILURE): Cannot parse media file pipe1
```

**Comment by Romantic-LiXuefeng** [comment]
@kqyang  I know the `shaka-steramer `also using  FFmpeg to redirect / pipe input to packager. In mac OS Mojave works well.

**Comment by kqyang** [comment]
@Romantic-LiXuefeng Do you mean that `shaka-streamer` works but it does not work if you run `ffmpeg` and `packager` directly?

**Comment by kqyang** [comment]
@joeyparrish Do you see anything wrong with @Romantic-LiXuefeng command above? Have you seen similar problems during the development of `shaka-streamer`?

**Comment by joeyparrish** [comment]
I don't see anything obviously wrong with the commands.  @Romantic-LiXuefeng, do your results change if you re-encode the video & audio (instead of using "copy")?

**Comment by Romantic-LiXuefeng** [comment]
> Do you mean that shaka-streamer works but it does not work if you run ffmpeg and packager directly?
@kqyang Yes.

> do your results change if you re-encode the video & audio (instead of using "copy")?
@joeyparrish I don't understand what's the meaning. Is there any requirements for the input decode format?

**Comment by Romantic-LiXuefeng** [comment]
@kqyang @joeyparrish  Thanks! As you said, re-encode the video & audio (instead of using "copy") is ok. but why?
```
ffmpeg -y -stream_loop -1 -re -i media/google_io_2017.mp4  -vf "scale=-2:720" -map 0 -c copy -c:v libx264 -c:a aac -f mpegts pipe: > pipe1
```

**Comment by joeyparrish** [comment]
It's not clear to me why, but it's a clue.  If re-encoding fixes the issue, it might be caused by some characteristic of the original file.  If you could provide us with a copy of it, we might be able to tell you more.

**Comment by Romantic-LiXuefeng** [comment]
@joeyparrish  As your said! I have sent the origin file to [shaka-packager-issues@google.com](url).  Our team have many different format sources. So I need to know clearly what's the limitations using the `pipe`  and` shaka-packager` (luckily there is `shaka-streamer` ).

**Comment by Romantic-LiXuefeng** [comment]
@joeyparrish  Maybe your commit the [issues/664](https://github.com/google/shaka-packager/issues/664) is also a limitation using `FFmpeg` ,`pipe` and `shaka-packager`.

**Comment by kqyang** [comment]
@Romantic-LiXuefeng The problem is not because of pipe but due to content problem.

The sample stream you provided have samples with SPS/PPS in the end of the sample, which violates H264 specification.

Per [H264](https://www.itu.int/rec/T-REC-H.264) section 7.4.1.2.3 Order of NAL units and coded pictures and association to access units
> Sequence parameter set NAL units or picture parameter set NAL units may be present in an access unit, but cannot follow the last VCL NAL unit of the primary coded picture within the access unit, as this condition would specify the start of a new access unit.

However, in the content you provided, there are a number of samples with SPS/PPS in the end. It also explains why it works after re-encoding.

How is your original content generated?

**Comment by Romantic-LiXuefeng** [comment]
@kqyang Sorry, I'm not clear what's your meaning, How to detect there are a number of samples with SPS/PPS in the end of the original mp4 content. 
> How is your original content generated?
It's some history datas, I'm not known how to generate.

**Comment by kqyang** [comment]
Every H264 frames comprises of a number of NAL units. If you parse the frames in your source video files, you'll find SPS and PPS NAL units in the end of some frames.

These SPS/PPS NAL units are not useful and should not be present in the end of H264 frames according to H264 specification quoted above. 

> How to detect there are a number of samples with SPS/PPS in the end of the original mp4 content

You can write a NAL unit parser yourself. Alternatively, the below command will dump out the NAL units along with packaging:

```shell
packager in=media/google_io_2017.mp4,stream=video,out=out.mp4 \
  --enable_raw_key_encryption \
  --keys label=:key_id=12345678901234561234567890123456:key=12345678901234561234567890123456 \
  --vmodule="*nalu*=4,*mp4*=4
```

You'll see `NALU type: 8` following `NALU type: 1`. NAL unit 8 is PPS.

> Addition I can use this original mp4 content to packager directly.

That is because we do not fail when seeing trailing SPS/PPS NAL units in mp4 frames, but we do care in MPEG2TS frames as it is used to determine the frame boundary. It is possible to workaround the problem but it is not necessary just for just one bad content. It is easier to just fix the content or change to another valid content.

**Comment by Romantic-LiXuefeng** [comment]
#https://gitlab.com/mbunkus/mkvtoolnix/issues/2179

**Comment by Romantic-LiXuefeng** [comment]
@kqyang  I'm sorry, There is no output logs with NAL units using your command.  I used the packager version is v2.3.0-5bf8ad5-release.  Is there any other configure?

```
[1023/155738:INFO:demuxer.cc(88)] Demuxer::Run() on file 'media/google_io_2017.mp4'.
[1023/155738:INFO:demuxer.cc(160)] Initialize Demuxer for file 'media/google_io_2017.mp4'.
[1023/155738:VERBOSE2:mp4_media_parser.cc(314)] Skipping top-level box: ftyp
[1023/155738:VERBOSE3:mp4_muxer.cc(188)] Finalizing segment 0 duration 250000
[1023/155738:VERBOSE3:mp4_muxer.cc(188)] Finalizing segment 250000 duration 150000
[1023/155738:VERBOSE3:mp4_muxer.cc(188)] Finalizing segment 400000 duration 250000
[1023/155738:VERBOSE3:mp4_muxer.cc(188)] Finalizing segment 650000 duration 250000
[1023/155738:VERBOSE3:mp4_muxer.cc(188)] Finalizing segment 900000 duration 250000
[1023/155738:VERBOSE3:mp4_muxer.cc(188)] Finalizing segment 1150000 duration 250000
[1023/155738:VERBOSE3:mp4_muxer.cc(188)] Finalizing segment 1400000 duration 245000
[1023/155738:VERBOSE3:mp4_muxer.cc(188)] Finalizing segment 1645000 duration 117000
[1023/155738:VERBOSE3:mp4_muxer.cc(188)] Finalizing segment 1762000 duration 89000
[1023/155738:VERBOSE3:mp4_muxer.cc(188)] Finalizing segment 1851000 duration 311000
[1023/155738:VERBOSE3:mp4_muxer.cc(188)] Finalizing segment 2162000 duration 250000
[1023/155738:VERBOSE3:mp4_muxer.cc(188)] Finalizing segment 2412000 duration 250000
[1023/155738:VERBOSE3:mp4_muxer.cc(188)] Finalizing segment 2662000 duration 134000
[1023/155738:VERBOSE3:mp4_muxer.cc(188)] Finalizing segment 2796000 duration 177000
[1023/155738:VERBOSE3:mp4_muxer.cc(188)] Finalizing segment 2973000 duration 250000
[1023/155738:VERBOSE3:mp4_muxer.cc(188)] Finalizing segment 3223000 duration 250000
[1023/155738:VERBOSE3:mp4_muxer.cc(188)] Finalizing segment 3473000 duration 250000
[1023/155738:VERBOSE3:mp4_muxer.cc(188)] Finalizing segment 3723000 duration 249000
[1023/155738:VERBOSE3:mp4_muxer.cc(188)] Finalizing segment 3972000 duration 249000
[1023/155738:VERBOSE3:mp4_muxer.cc(188)] Finalizing segment 4221000 duration 249000
[1023/155738:VERBOSE3:mp4_muxer.cc(188)] Finalizing segment 4470000 duration 259000
[1023/155738:VERBOSE3:mp4_muxer.cc(188)] Finalizing segment 4729000 duration 249000
[1023/155738:VERBOSE2:mp4_media_parser.cc(314)] Skipping top-level box: free
[1023/155738:VERBOSE3:mp4_muxer.cc(188)] Finalizing segment 4978000 duration 92000
[1023/155739:INFO:single_segment_segmenter.cc(107)] Update media header (moov) and rewrite the file to 'out.mp4'.
[1023/155739:INFO:mp4_muxer.cc(171)] MP4 file 'out.mp4' finalized.
Packaging completed successfully.
```

> you'll find SPS and PPS NAL units in the end of some frames

The pipeline:  Demux mp4 -> Sample --> Encrypt -> Encrypted Sample --> Mux mp4 , are there any operators about NAL units parser?

**Comment by kqyang** [comment]
Oops, you'll need to use the debug build: https://github.com/google/shaka-packager/blob/26bc55503dadb249422bc2f9ea7b9e7c884d58b0/packager/media/codecs/nalu_reader.cc#L292.

Alternatively, use ffmpeg:

```shell
ffmpeg -i media/google_io_2017.mp4 -c copy -bsf:v trace_headers -f null - 2> NALUS.txt
```

You'll see "Picture Parameter Set" after "Slice Header".

**Comment by kqyang** [comment]
@Romantic-LiXuefeng The sequence you described above is allowed and supported by Shaka Packager. The case we don't support is if the SPS/PPS is after the last video slice, which is explicitly prohibited by H264 spec: https://github.com/google/shaka-packager/issues/665#issuecomment-544736956.

If you want to dig into the code, here is where it is handled: https://github.com/google/shaka-packager/blob/master/packager/media/formats/mp2t/es_parser_h26x.cc#L197.

> Recently I update the Mac OS to 10.15 SDK , I can't build the project.

That is a known bug: https://github.com/google/shaka-packager/issues/660, unfortunately.

**Comment by Romantic-LiXuefeng** [comment]
@kqyang  I'm still not clear what's the meaning ` the SPS/PPS is after the last video slice`?
![image](https://user-images.githubusercontent.com/9837705/67619124-50d59400-f82a-11e9-9520-09872f3f9282.png)


What's the last video slice? 
In my opinion, If the I/P/B Frame(Access Unit) has split into multi NALU(Slice), it’s the last NALU(Slice).
If the I/P/B Frame has only contains one NALU(Slice), it is the first video slice and the last video slice.
So in the That’s the forth and eighth  NALU. 

> Sequence parameter set NAL units or picture parameter set NAL units may be present in an access unit, but cannot follow the last VCL NAL unit of the primary coded picture within the access unit, as this condition would specify the start of a new access unit.

I don't image what the sequence of NALU looks as the described by the spec? What the different with the 7,8,9 NALUs in above picture?
Please point out what's wrong with my opinion?

**Comment by kqyang** [comment]
What kind of frame it is is irrelevant here. 

Simply put, the spec allows something like this:

```
AUD | PPS | VCL | AUD | VCL | AUD | ...
```

and 

```
AUD | VCL | PPS | VCL | AUD | VCL | AUD | ...
```

but not

```
AUD | VCL | PPS | AUD | VCL | AUD | ...
```
