### ISSUE TITLE
Alternate Subtitles with DASH

### ISSUE THREAD

**Issue by cgp1081** [google/shaka-packager#670]
We've found that alternate language subtitles do not render on any available dash players.  The init segments for each are requested but no segments every requested.  Samples provided via email.

Players tested:
Exo
dash.js Reference
https://bitmovin.com/demos/stream-test

    <AdaptationSet id="6" contentType="text" lang="es-MX" segmentAlignment="true">
    <AdaptationSet id="7" contentType="text" lang="pt-BR" segmentAlignment="true">
    <AdaptationSet id="8" contentType="text" lang="en" segmentAlignment="true">

**Comment by kqyang** [comment]
@cgp1081 Have you tried shaka-player? There are multi-language demo there which works.

**Comment by kqyang** [comment]
@cgp1081 Is your problem addressed after updating the source files to have correct timestamps? Can we close this issue?
