### ISSUE TITLE
Question: How to ensure the mid ad inserted position are aligned in the audio/video/subtitle streams?

### ISSUE THREAD

**Issue by Romantic-LiXuefeng** [google/shaka-packager#676]
1. Because of the audio ,video, subtitle streams are packaged in different pipeline(threads).  So the pipeline operation's doing speed are controlled by CPU. 
2.  I know that the ad insert position of video stream will adjust to the first key frame which timestamp is greater than the `--ad_cues ` configured insert position. e.g.  `--ad_cues = 20`, but at the time of 20s, there is not a KEY frame, and at the time of  21s, it's a KEY frame, so the video stream will end the segment at this time . and insert the ` #EXT-X-PLACEMENT-OPPORTUNITY` tag .
3.  Whether insert the media ad into the  audio/subtile streams at the time of `--ad_cues ` configured ? As the result of HLS manifest ,the   #EXT-X-PLACEMENT-OPPORTUNITY` tag are insert aligned basically(Not at the same time, there is some deviation). so it may not as this rule.  because of there may exits some error, when the GOP size is large. 

 So I have some doubt:
- When to insert the ad tag into the audio or subtile Manifest? 
- How to ensure the insert position are aligned between different threads?

**Comment by kqyang** [comment]
@Romantic-LiXuefeng Good question. Shaka Packager performs synchronization internally to make sure audio/subtitle streams are roughly aligned with video streams at the Ad cues (Ad insertion points). If you are curious how we do it, you can take a look the implementation here: https://github.com/google/shaka-packager/blob/master/packager/media/chunking/cue_alignment_handler.cc.

> Whether insert the media ad into the audio/subtile streams at the time of --ad_cues configured ? As the result of HLS manifest ,the #EXT-X-PLACEMENT-OPPORTUNITY` tag are insert aligned basically(Not at the same time, there is some deviation). 

Some deviations are expected as audio frames are discrete. For example, for an audio stream of 48kHz, the audio frame duration is 1024/48000.0 if it is encoded in AAC. The closest audio frame to 21s is frame 984 starting at 20.992 ending at 21.013333. We will break the audio stream at 21.013333, which means there is about 0.013333s misalignment between audio and video streams.

The misalignment should always be less than one audio frame duration. Let us know if it is not the case.

@Romantic-LiXuefeng Does that answer your question?

**Comment by Romantic-LiXuefeng** [comment]
@kqyang  Thanks for your detail answer!  
I have a look at the https://github.com/google/shaka-packager/blob/master/packager/media/chunking/cue_alignment_handler.cc.  
 I found that it may cause some issue in this scene:
In the mode there is a video input.  If the video stream pipeline is slower than the audio stream pipeline.  
```
if (stream->samples.size() > kMaxBufferSize) {
    LOG(ERROR) << "Stream " << stream_index << " has buffered "
               << stream->samples.size() << " when the max is "
               << kMaxBufferSize;
    return Status(error::INVALID_ARGUMENT,
                  "Streams are not properly multiplexed.");
  }
```
To clear that, if the audio stream has cached the 1000 audio samples,  but the video stream has not reach the sync point due to the pipeline is slower.  This will cause the `Streams are not properly multiplexed` exception.  
I don't think this is not properly multiplexed of the origin source.  If I make some mistake, please give some explain. Thanks!

**Comment by kqyang** [comment]
@Romantic-LiXuefeng No, that won't happen. See the description of CueAlignmentHandler here: https://github.com/google/shaka-packager/blob/master/packager/media/chunking/cue_alignment_handler.h#L22.

```
/// There should be a cue alignment handler per demuxer/thread and not per
/// stream. A cue alignment handler must be one per thread in order to properly
/// manage blocking.
```

So all the streams in a particular CueAlignmentHandler comes from the same input source, i.e. they are multiplexed. 

If the audio and video streams are more than 1000 frames, i.e. ~20 seconds, apart, it is reasonable to assume that the input is not properly multiplexed.

If you are curious, the synchronization between different input sources are handled by the [SyncPointQueue](https://github.com/google/shaka-packager/blob/master/packager/media/chunking/sync_point_queue.cc) class, which is used by CueAlignmentHandler.

**Comment by Romantic-LiXuefeng** [comment]
> I don't think this is not properly multiplexed of the origin source . because the audio stream demux thread only extract audio sample, and the video stream thread demux the source again, only extract the video sample, the two thread not extract audio sample and video sample one by one.
If I make some mistake, please give some explain. Thanks!

@kqyang Yes,  It's a mistake. If all the streams come from the same input source. Only use one demuxer(thread) and one CueAlignmentHandler.

> If you are curious, the synchronization between different input sources are handled by the SyncPointQueue class, which is used by CueAlignmentHandler.
Yes, in fact in my last [issuecomment](https://github.com/google/shaka-packager/issues/676#issuecomment-552747621). I want to know how to sync between different input sources. 
```
  if (EveryoneWaitingAtHint()) {
    std::shared_ptr<const CueEvent> next_sync;
    RETURN_IF_ERROR(GetNextCue(hint_, sync_points_, &next_sync));
    RETURN_IF_ERROR(UseNewSyncPoint(next_sync));
  }
```
The demuxer(thread) extracts the streams , if the streams don't have video stream, the thread will waiting on a hint.   Until other demuxer(thread) which has video stream  update the sync point, then to notify the waiting threads.  or all the demuxer-s has no video stream, the waiting threads will be notified when all streams had cached to the hint point.
