### ISSUE TITLE
Unable to create playable widevine content using EZDRM 

### ISSUE THREAD

**Issue by manherna** [google/shaka-packager#677]
## System info
**Operating System**:Ubuntu 18.04.3 LTS
**Shaka Packager Version**: v2.3.0-5bf8ad5-release

## Issue and steps to reproduce the problem
Run this packager code and then try to play content in Exo player.
**Packager Command**:
```
packager \
  in=$IN_VIDEO,stream=audio,init_segment=$OUTDIR/DASH/tt/audio_init.mp4,init_segment=$OUTDIR/audio\$Number\$.mp4 \
  in=$IN_VIDEO,stream=video,init_segment=$OUTDIR/DASH/tt/video_init.mp4,init_segment=$OUTDIR/video\$Number\$.mp4 \
  --enable_raw_key_encryption \
  --protection_scheme cbcs \
  --keys label=:key_id=xxx:key=yyy \
  --mpd_output $OUTDIR/DASH/tt/manifest.mpd \
  --hls_master_playlist_output $OUTDIR/DASH/tt/master.m3u8
```

Extra steps to reproduce the problem?
(1) Get key and key_id from ezdrm server
(2) 

What is the expected result?
Playable widevine encrypted content is created
What happens instead?
After the command is executed (succesfully), the content is created. But when trying to play it with, for example, ExoPlayer, an error rises: "Media includes video tracks but none are playable for this device".

I have tried several devices/videos and no combination seemed to work
Please take into consideration that I am new to this industry and I am trying to learn as fast as possible.

Thanks for the help

<Please attach the input files or email to shaka-packager-issues@google.com.>
<Please provide any additional information below.>

**Comment by kqyang** [comment]
@manherna There are two problems:

- The command is incorrect. Please follow examples at https://google.github.io/shaka-packager/html/tutorials/raw_key.html. 
- You may need to provide a pre-generated PSSH depends on what ezdrm server wants. Please check with ezdrm.

I am closing this issue, but feel free to reply or reopen if you have more questions.

**Comment by manherna** [comment]
Hi @kqyang, would you mind telling me what is wrong with this code? 
Also, EZDRM does provide a pre-generated PSSH, but when trying to use `--pssh` option it yields `--pssh argument should be full PSSH boxes`

**Comment by kqyang** [comment]
> would you mind telling me what is wrong with this code?

In your command, the second `init_segment` should be `segment_template`.

> Also, EZDRM does provide a pre-generated PSSH, but when trying to use --pssh option it yields --pssh argument should be full PSSH boxes

Looks like EZDRM provides only pssh data. You can use our pssh-box.py script to generate PSSH box from PSSH data, i.e.

```bash
$ pssh-box.py --widevine-system-id --pssh-data AAAABCICEjQ= --hex
```
