### ISSUE TITLE
Can't package Dash/Webm with PlayReady using Raw Key

### ISSUE THREAD

**Issue by salmoro** [google/shaka-packager#678]
## System info
**Operating System**: Windows 10
**Shaka Packager Version**: v2.3.0-5bf8ad5ed5-release

## Issue and steps to reproduce the problem

**Packager Command**:

```
packager \
in=./360_600_vp8.webm,stream=video,output=./dist/dash_vp8/video/360_600_vp8.webm \ 
in=./480_1000_vp8.webm,stream=video,output=./dist/dash_vp8/video/480_1000_vp8.webm \ 
in=./720_3000_vp8.webm,stream=video,output=./dist/dash_vp8/video/720_3000_vp8.webm \ 
in=./1080_6000_vp8.webm,stream=video,output=./dist/dash_vp8/video/1080_6000_vp8.webm \ 
in=./64_eng_vorbis.webm,stream=audio,output=./dist/dash_vp8/audio/64_eng_vorbis_eng.webm,language=eng \ 
in=./64_heb_vorbis.webm,stream=audio,output=./dist/dash_vp8/audio/64_heb_vorbis_heb.webm,language=heb \ 
in=./128_eng_vorbis.webm,stream=audio,output=./dist/dash_vp8/audio/128_eng_vorbis_eng.webm,language=eng \ 
in=./128_heb_vorbis.webm,stream=audio,output=./dist/dash_vp8/audio/128_heb_vorbis_heb.webm,language=heb \ 
in=./text/en.vtt,stream=text,output=./dist/dash_vp8/text/en_en.vtt,language=en \ 
in=./text/fr.vtt,stream=text,output=./dist/dash_vp8/text/fr_fr.vtt,language=fr \ 
in=./text/he.vtt,stream=text,output=./dist/dash_vp8/text/he_he.vtt,language=he \ 
in=./text/hu.vtt,stream=text,output=./dist/dash_vp8/text/hu_hu.vtt,language=hu \ 
in=./text/pt.vtt,stream=text,output=./dist/dash_vp8/text/pt_pt.vtt,language=pt \ 
in=./text/es.vtt,stream=text,output=./dist/dash_vp8/text/es_es.vtt,language=es \ 
in=./text/ru.vtt,stream=text,output=./dist/dash_vp8/text/ru_ru.vtt,language=ru \ 
in=./text/yi.vtt,stream=text,output=./dist/dash_vp8/text/yi_yi.vtt,language=yi \ 
--enable_raw_key_encryption \ 
--clear_lead 10 \ 
--keys label=HD:key_id=[$key_id_hex]:key=[$key_hex],label=AUDIO:key_id=[$key_id_hex]:key=[$key_hex],label=SD:key_id=[$key_id_hex]:key=[$key_hex] \ 
--protection_systems PlayReady \ 
--mpd_output ./dist/dash_vp8/master.mpd
```

### What is the expected result?
   Manifest should be playable on Edge with Shaka Demo Player

### What happens instead?
- Shaka player throws "[REQUESTED_KEY_SYSTEM_CONFIG_UNAVAILABLE](https://shaka-player-demo.appspot.com/docs/api/shaka.util.Error.html#value:6001)"
- MPD doesn't have any mention of "mspr"

### Note
When I run the same command with the addition of `,Widevine` in the protection_systems value and provide a pssh the content packages well for Widevine and is playable on widevine-supported browsers.

**Comment by kqyang** [comment]
@salmoro Thanks for the bug report. Would you be able to share a link to the packaged content to help us re-produce the problem?

We generates the new cenc:pssh element only. We do not support the legacy mspr:pro element. 

@joeyparrish Does Shaka Player support the new cenc:pssh element for PlayReady? See Microsoft documentation here: https://docs.microsoft.com/en-us/playready/specifications/mpeg-dash-playready#2-playready-dash-content-protection-scheme.

**Comment by salmoro** [comment]
@kqyang I've emailed the links to shaka-packager-issues@google.com

If it can better help you resolve this issue I can make a small script which mimics my process from input video to output MPD.

Thanks!

**Comment by joeyparrish** [comment]
Shaka Player supports both `cenc:pssh` and `mspr:pro`.  Not sure what you mean by "new", though.  Has it changed in some way I'm not aware of?

**Comment by kqyang** [comment]
It is not really new, but compared to "mspr:pro", it is newer :).

**Comment by joeyparrish** [comment]
Gotcha.  Yes, we support both.  :-)

**Comment by joeyparrish** [comment]
Ironically, we supported `cenc:pssh` first. and only added support for the older `mspr:pro` recently.  :-)

**Comment by kqyang** [comment]
Debugged the problem together with @joeyparrish, we suspected the problem is because Edge does not support encrypted WebM. @salmoro Can you try mp4 instead?

**Comment by salmoro** [comment]
@kqyang Thanks for the info. I'll try mp4 and report back here.
