### ISSUE TITLE
Packager with v1 common PSSH box,packager-win.exe does not create the proper PSSH for Widevine

### ISSUE THREAD

**Issue by EZDRM** [google/shaka-packager#680]
Using the prebuilt release v2.3.0 and useing the RAW key method for both WV and PR

packager-win.exe in=BigBuckBunny_320x180_Frag.mp4,stream=audio,output=audio.mp4,drm_label=AUDIO in=BigBuckBunny_320x180_Frag.mp4,stream=video,output=h264_360p.mp4,drm_label=SD  --enable_raw_key_encryption --keys label=AUDIO:key_id=0fbf6013e4645deb99707d3899c29651:key=d225a6b115e45a8fe62236dc5e720fdd,label=SD:key_id=0fbf6013e4645deb99707d3899c29651:key=d225a6b115e45a8fe62236dc5e720fdd --protection_systems Widevine,PlayReady --mpd_output h264.mpd

the PSSH is not playable in the Shaka-Player

We see in the DRM request to the WV server:
response={"status":"INVALID_REQUEST","status_message":"Content ID is missing.","supported_tracks":

It seems the packager-win.exe does not create the proper PSSH for Widevine

**Comment by kqyang** [comment]
The generated Widevine PSSH does not contain content id. You'll need either a server implementation that accepts key id only or you can provide content id in license server url during playback.

If neither is possible, you'll have to provide your own PSSH with content_id during packaging: https://google.github.io/shaka-packager/html/tutorials/raw_key.html#examples. 

@EZDRM I am closing this issue, but feel free to reply if you still have questions.

**Comment by EZDRM** [comment]
Hello

Would we jus use the WV PSSH or
WV PSSH,PR PSSH?

Since it auto generates the PR PSSH properly, if we just provide the WV PSSH will that sill work?
The pssh-box script need to be created, is there a pre made one or does the Win Packager.exe have this built in?

**Comment by kqyang** [comment]
Yes, you can mix --pssh and --protection_systems.

> The pssh-box script need to be created, is there a pre made one or does the Win Packager.exe have this built in?

Not right now, but we'll include it in the future releases.

**Comment by EZDRM** [comment]
Hello

Thank you for the assistance

We were able to get it working, one thing that was not clear in the documentation was if we had
--protection_systems widevine, PlayReady
While providing the WV PSSH as well as both protection systems caused the MPD to have several PSSH listed the one we provided and the common

So by trial and error we used only --protection_systems PlayReady

This may be something you wish to clear up in the docs

Thank you
David

**Comment by kqyang** [comment]
@EZDRM Thanks for the feedback. We'll update our documentation to make it clearer.
