### ISSUE TITLE
Not able to retrieve the license from https://license.uat.widevine.com/cenc/getcontentkey/widevine_test

### ISSUE THREAD

**Issue by mmarko-globallogic** [google/shaka-packager#681]
Hi guys,

I was trying to retrieve the license from https://license.uat.widevine.com/cenc/getcontentkey/widevine_test for https://github.com/google/shaka-packager/tree/master/packager/app/test/testdata/encryption-with-multi-drms test content and it doesn't seem to work. I'm getting 400 response code.
Can you please confirm that this license acquisition URL is the right one for the content (when using WIDEVINE)?

Thanks

**Comment by kqyang** [comment]
Please look at examples here: https://google.github.io/shaka-packager/html/tutorials/widevine.html. 

Please contact [Widevine](https://support.google.com/widevine/troubleshooter/6027072) if you have problems on Widevine servers.
