### ISSUE TITLE
[Question] How to verify that HW accelerated AES is used during runtime?

### ISSUE THREAD

**Issue by baniks3** [google/shaka-packager#682]
## System info
**Operating System**: Custom embedded Linux kernel based on Ubuntu 16.04
**Shaka Packager Version**: v2.3.0, 1bcaf0a8355022fbfab431462666d396b4d119de

## Issue and steps to reproduce the problem
I have an application that runs `n` packager instances in a multiple threads (not via CLI). v2.3.0 is said to have support for HW accelerated AES via the latest boringssl update. However, I'm not noticing any improvement in CPU%. The application runs on an intel processor with AES-NI support and I've confirmed that it is enable and active in the processor as well as the kernel. I've also benchmarked using the `openssl speed` command and see significant performance boost with the `-evp` flag, which validates my verification of AES-NI being active. I suspect that boringssl is not using AES-NI, at least not in the same way that openssl does. Unfortunately boringssl's `bssl speed` command doesn't provide benchmarking support for just AES-CBC (their speed test does AES-*-CBC-SHA1), which is the cipher I'm using. This prevents me from performing an apple to apple comparison of openssl vs bssl for my needs.

My question is how to verify that hardware acceleration is being used by shaka/boringssl during runtime? 

**Packager Command**:
The packager library is used - no commands.

What is the expected result?
Lower CPU overhead as compared to v2.2.1 that didn't have support for HW acceleration.

What happens instead?
No noticeable difference in CPU overhead with v2.3.0.

**Comment by kqyang** [comment]
@baniks3 Hardware accelerated AES is added in #198, which will be included in v2.4. So v2.3 does not have it yet. 

Can you try compiling from latest packager source code? Alternatively, you may wait for v2.4 release in coming weeks.

**Comment by baniks3** [comment]
@kqyang Thanks for the quick reply. Sorry I gave you the wrong impression when I mentioned v2.3.0. What I'm running is a compiled build of Iaba52f0fc6c97d413e973f9a3d8c74cf8c83aa03 which is a couple of commits behind the latest master but has the hw aes support. Any other flag I need to enable somewhere?

**Comment by kqyang** [comment]
No. It should just work, unless OPENSSL_NO_ASM is disabled somehow.

We have a unittest you can use to verify: https://github.com/google/shaka-packager/blob/master/packager/media/base/aes_cryptor_unittest.cc#L628.

Since you built the library yourself, you may also add a CHECK to confirm that hwaes_capable is returning true: https://github.com/google/boringssl/blob/f4d8b969200f1ee2dd872ffb85802e6a0976afe7/crypto/fipsmodule/aes/internal.h#L34.

Note that AES uses only a small portion of the CPU used during packaging, so there are no significant gains even though it is actually enabled.

**Comment by baniks3** [comment]
Thanks @kqyang. I was able to confirm that HW acceleration is in fact active using the `hwaes_capable()` function. I also ran the unit test and they passed but am not sure how they can be used to measure performance. A clarifying comment on that might be helpful for future. But, for the most part, I got the answer I was looking for. Closing as resolved.

**Comment by kqyang** [comment]
> I also ran the unit test and they passed but am not sure how they can be used to measure performance. 

You can compile with OPENSSL_NO_ASM or hardcode hwaes_capable to return false to see the difference.

There are a few other opportunities we can improve the AES performance, e.g. #667. It can actually result in more gains compared to using HWAES alone. Let us know if you are interested in working on that.
