### ISSUE TITLE
gclient sync error windows 10

### ISSUE THREAD

**Issue by jeybs** [google/shaka-packager#688]
Hi, currently i'm following the guide for windows installation.. current i'm using Windows 10, but i keep getting error on 'gclient sync' command. 

Below is the error i got when running `gclient confif`

![Untitled](https://user-images.githubusercontent.com/3271075/70655559-6b0ce980-1c93-11ea-9c65-8f6bb5c1208e.png)

**Comment by kqyang** [comment]
See https://google.github.io/shaka-packager/html/build_instructions.html#windows-system-requirements. Have you followed the above instructions and installed Visual Studio and Windows 10 SDK?

**Comment by jeybs** [comment]
@kqyang yes i've already installed the following sysgem requirements for windows state on the guide.

**Comment by kqyang** [comment]
Can you try Visual Studio 2015?

**Comment by jeybs** [comment]
Hi @kqyang Thanks! i've finally made it work. I just need to install the Visual Studio 2015 to make it build.
