### ISSUE TITLE
link error(LNK1169) caused by using openssl and boringssl

### ISSUE THREAD

**Issue by Jason239** [google/shaka-packager#689]
If I have to use openssl API with Shaka library, how can I use both of them?
If I link both(Openssl and Shaka libs), A redundancy error occurs for openssl and boringssl.
So I've only linked openssl, but 'CRYPTO_library_init' API has been added as a recent update is not in openssl. So after updating, link error has been occurring.

Can't I use openssl ? or is there any link option to avoid redundancy?

**Comment by kqyang** [comment]
@Jason239 Any reason that you want to use openssl but not boringssl in your code?

I think you can replace it with 

```c++
OPENSSL_init_ssl(0, nullptr);
```

It is present in both openssl and boringssl. Feel free to send us a pull request if it works for you.

**Comment by Jason239** [comment]
> Any reason that you want to use openssl but not boringssl in your code?

There are no these APIs in boringssl but I use.
```
OPENSSL_add_all_algorithms_noconf
ERR_load_RSA_strings
ERR_load_CRYPTO_strings
```

> I think you can replace it with

I'll try it, thanks !

**Comment by kqyang** [comment]
> There are no these APIs in boringssl but I use.

You may want to take a look at the porting guide here: https://boringssl.googlesource.com/boringssl/+/HEAD/PORTING.md

**Comment by Jason239** [comment]
> You may want to take a look at the porting guide here:

Thanks, and I think I can remove or replace those APIs and only use boringssl.
