### ISSUE TITLE
Compilation Error: cannot bind ‘std::unique_ptr<shaka::media::MpdNotifyMuxerListener, std::default_delete<shaka::media::MpdNotifyMuxerListener> >’ lvalue to ‘std::unique_ptr<shaka::media::MpdNotifyMuxerListener, std::default_delete<shaka::media::MpdNotifyMuxerListener> >&&’

### ISSUE THREAD

**Issue by ronak2121** [google/shaka-packager#694]
## System info
**Operating System**: Amazon Linux 1
**Shaka Packager Version**: v2.4.0

## Issue and steps to reproduce the problem
I'm just trying to compile Shaka Packager on my platform. I have GCC 4.9.4, and am running on Amazon Linux 1. 

Here's the error I get:

../../packager/media/event/muxer_listener_factory.cc: In function ‘std::unique_ptr<shaka::media::MuxerListener> shaka::media::{anonymous}::CreateMpdListenerInternal(const shaka::media::MuxerListenerFactory::StreamData&, shaka::MpdNotifier*)’:
../../packager/media/event/muxer_listener_factory.cc:47:10: error: cannot bind ‘std::unique_ptr<shaka::media::MpdNotifyMuxerListener, std::default_delete<shaka::media::MpdNotifyMuxerListener> >’ lvalue to ‘std::unique_ptr<shaka::media::MpdNotifyMuxerListener, std::default_delete<shaka::media::MpdNotifyMuxerListener> >&&’
   return listener;
          ^
In file included from /home/ronakp/pkg-cache/packages/GCC/GCC-4.9.x.209680.0/build/gcc-4.9.4/include/c++/4.9.4/memory:81:0,
                 from ../../packager/media/event/muxer_listener_factory.h:10,
                 from ../../packager/media/event/muxer_listener_factory.cc:7:
/home/ronakp/pkg-cache/packages/GCC/GCC-4.9.x.209680.0/build/gcc-4.9.4/include/c++/4.9.4/bits/unique_ptr.h:220:2: note: initializing argument 1 of ‘std::unique_ptr<_Tp, _Dp>::unique_ptr(std::unique_ptr<_Up, _Ep>&&) [with _Up = shaka::media::MpdNotifyMuxerListener; _Ep = std::default_delete<shaka::media::MpdNotifyMuxerListener>; <template-parameter-2-3> = void; _Tp = shaka::media::MuxerListener; _Dp = std::default_delete<shaka::media::MuxerListener>]’
  unique_ptr(unique_ptr<_Up, _Ep>&& __u) noexcept
  ^
../../packager/media/event/muxer_listener_factory.cc:48:1: error: control reaches end of non-void function [-Werror=return-type]
 }
 ^
cc1plus: all warnings being treated as errors 

What is the expected result?
Compilation succeeds

What happens instead?
Compilation Fails

<Please attach the input files or email to shaka-packager-issues@google.com.>
<Please provide any additional information below.>

The problem is this code:

```
std::unique_ptr<MuxerListener> CreateMpdListenerInternal(
    const MuxerListenerFactory::StreamData& stream,
    MpdNotifier* notifier) {
  DCHECK(notifier);

  auto listener = base::MakeUnique<MpdNotifyMuxerListener>(notifier);
  listener->set_accessibilities(stream.dash_accessiblities);
  listener->set_roles(stream.dash_roles);

  return listener;
}
```

where the compiler is unable to cast the auto pointer to the base class on its own.

I'm forced to modify your code like so:

```
std::unique_ptr<MpdNotifyMuxerListener> listener = base::MakeUnique<MpdNotifyMuxerListener>(notifier);
listener->set_accessibilities(stream.dash_accessiblities);
listener->set_roles(stream.dash_roles);
MuxerListener *rawListener = listener.get();
std::unique_ptr<MuxerListener> baseListener;
baseListener.reset(rawListener);
return baseListener;
```

to have compilation succeed.

Can this code change be made in your repository so I don't have this modification on my end?

**Comment by rkuroiwa** [comment]
It feels like a compiler bug than the code not being spec compliant. Is there a reason why it doesn't use the clang toolchain that is bundled with the project?
Also the modification is probably using freed memory.
The 4th line should be 

```
MuxerListener *rawListener = listener.release();
```

**Comment by ronak2121** [comment]
We cannot use that; as our build environment can’t use clang. We have to use GCC 4.9.4.

**Comment by kqyang** [comment]
@ronak2121 We are not able to re-produce the problem gcc either. The version I tried is gcc 8.3.0. So I agree with @rkuroiwa's assessment. This is a bug in old version of gcc and has been fixed.

Can you update your gcc to a newer version?

**Comment by ronak2121** [comment]
We were able to upgrade and this is now fixed. Thanks.
