### ISSUE TITLE
Can't play HLS/FairPlay content

### ISSUE THREAD

**Issue by salmoro** [google/shaka-packager#696]
## System info
**Operating System**: Ubuntu 16.04
**Shaka Packager Version**: v2.4.0p2-c731217-release

## Issue and steps to reproduce the problem
I followed the tutorial for creating HLS/Fairplay content but when trying to play on Shaka Demo player I get `Shaka Error DRM.INIT_DATA_TRANSFORM_ERROR (RangeError: Malformed FairPlay init data)`

[Here](https://shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;asset=https://temp-for-testing-shlomo.s3.amazonaws.com/fairplay-shaka-issue/master.m3u8;license=https://fps.ezdrm.com/api/licenses/0f3f9b02-2163-4fed-bc84-657ce217a3e9;certificate=https://jem-ccdb-media.s3.amazonaws.com/video/static/fairplay.cer;panel=CUSTOM%20CONTENT;build=uncompiled)'s the link to the demo with all the relevant urls.

**Packager Command**:
Shortly I'll send an email to shaka-packager-issues@google.com with the exact commands used to create the content.

**What is the expected result**?
Content should continue playing past the clear-lead section (15s-17s)

**What happens instead**?
Content gets stuck when reaching the encrypted section (~17s)

Thank you

**Comment by Canta** [comment]
Well... IDK if it has anything to do with your case, but looking at the contents of a medialist of yours I can see this:

`#EXT-X-KEY:METHOD=SAMPLE-AES-CTR,URI="skd://[REDACTED URI]",KEYFORMATVERSIONS="1",KEYFORMAT="com.apple.streamingkeydelivery"`

I have several working HLS+FairPlay streams, which have this other syntax:

`#EXT-X-KEY:METHOD=SAMPLE-AES,URI="skd://[REDACTED URI]",KEYFORMATVERSIONS="1",KEYFORMAT="com.apple.streamingkeydelivery"`

The difference I see is my method "SAMPLE-AES" versus your "SAMPLE-AES-CTR".
I don't have the tools to test it here (no apple hardware), but I remember having trouble with the encryption method back when I was setting this up, so maybe you can easily check out if that's the problem by changing that parameter in your command line. I use `--protection_scheme cbcs` for my HLS streams.

**Comment by salmoro** [comment]
@Canta Thanks for your input. CBCS doesn't seem to fix it.

**Comment by kqyang** [comment]
@salmoro Do you have a link to the demo with cbcs content? On what platform are you trying playback on?

**Comment by salmoro** [comment]
@kqyang 
1. [Here](https://shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;asset=https://temp-for-testing-shlomo.s3.amazonaws.com/fairplay-shaka-issue/v2/master.m3u8;license=https://fps.ezdrm.com/api/licenses/0f3f9b02-2163-4fed-bc84-657ce217a3e9;certificate=https://jem-ccdb-media.s3.amazonaws.com/video/static/fairplay.cer;panel=CUSTOM%20CONTENT;build=uncompiled)'s the link to the same as the above just with cbcs.
2. So far on any IOS/MacOS Safari browser I've tried. I just now verified on IPhone8/IOS-13 and MacOS-Catalina/Safari-13.

**Comment by SeawardT** [comment]
To confirm, you get the exact same error whether you use iOS or OSX?

**Comment by salmoro** [comment]
@SeawardT Yes! Same error.

**Comment by kqyang** [comment]
+@SeawardT to take a look. Also @joeyparrish if there is any insight on the Shaka Player error.

**Comment by joeyparrish** [comment]
`DRM.INIT_DATA_TRANSFORM_ERROR (RangeError: Malformed FairPlay init data)` means that you need to customize the init data transform.  See the [FairPlay tutorial](https://shaka-player-demo.appspot.com/docs/api/tutorial-fairplay.html) for more information.

**Comment by salmoro** [comment]
@joeyparrish I saw that section in the tutorial but miss-interpenetrated it as referring to special cases.
How would I go about creating the `getMyContentId(initData)` function mentioned there?

**Comment by kqyang** [comment]
@salmoro I am closing the issue as it looks like a player configuration issue. Please file an issue in Shaka Player instead: https://github.com/google/shaka-player/issues.
