### ISSUE TITLE
Change AV1 cbcs encryption to start alignment

### ISSUE THREAD

**Issue by kqyang** [google/shaka-packager#698]
AV1-ISOBMFF spec is updated [recently](https://github.com/AOMediaCodec/av1-isobmff/pull/116) to use start alignment instead of end alignment for cbcs:

- for the protected scheme cbcs:
    - BytesOfProtectedData SHALL start on the first byte and end on the last byte of the decode_tile structure (including any trailing bits).
    - A subsample SHALL be created for each tile, even if its size is less than 16 bytes.
    - ...

cenc protection scheme is not affected.

**Comment by vladimir-kazakov** [comment]
Can this change somehow affect playback in media players built before this change?

**Comment by kqyang** [comment]
As far as I know, it does not affect devices using Widevine and PlayReady. This is a request from Apple and Apple devices will only support start alignments.

**Comment by vladimir-kazakov** [comment]
This started confusing me even more. Now that all DRM systems support cbcs as well, how players will act when noticing this change? Sure, Apple can update their stuff, but not everyone will be updated at the same time. How old, not updated things will handle this change?

**Comment by kqyang** [comment]
This affects AV1 only. If you have AV1 contents packaged before this change, they'll need to be re-packaged to work on Apple devices.
