### ISSUE TITLE
Does it support fragments decryption?

### ISSUE THREAD

**Issue by qchroman** [google/shaka-packager#704]
Hello Shaka team,

I have today found that the packager allows you specifying the "enable_raw_key_decryption" property, but I couldn't find any examples of how it may be used?

Based on the information I have found, it may be used on fMP4 + CENC files to decrypt them if one has a key. Does it mean that one may also decrypt files that contain fragments only? Is it possible at all using the shaka-packager?

Thank you in advance!

**Comment by kqyang** [comment]
@qchroman As long as the fragment is a self-initializing media segment, then it can be decrypted. Alternatively, you can concatenate the fragment with an initialization segment yourself before feeding it to shaka-packager.

I'm closing this issue, but feel free to reply if you have more questions or if there are problems.

**Comment by qchroman** [comment]
Thank you @kqyang !

ffmpeg will help concatenate init fragment with other fragments, but how would the command for the shaka-packager look like if I may ask? I couldn't find anything on that matter. Something like:

```
packager-win.exe ^
in=input-audio.mp4,stream=audio,output=output-audio.mp4 ^
in=intpu-video.mp4,stream=video,output=output-video.mp4 ^
--enable_raw_key_decryption ^
--keys key_id=yyy:key=xxx ^
```

Also, I presume the packager doesn't work with MPEG 2 TS fragments (not fMP4 + CENC fragments)? I.e. those can't be decrypted, correct?

**Comment by kqyang** [comment]
> ffmpeg will help concatenate init fragment with other fragments

You don't really need a ffmpeg to do it. You can literally concatenate the init fragment with other fragments byte by byte, e.g. you can do it in Linux with "cat init.mp4 fragment_1.mp4 > out.mp4".

And yes, the command looks correct to me. Note that if audio and video are encrypted with different keys, you'll need to provide two keys here.

> Also, I presume the packager doesn't work with MPEG 2 TS fragments (not fMP4 + CENC fragments)? I.e. those can't be decrypted, correct?

SAMPLE-AES encrypted MPEG 2 TS fragments are supported. You can provide fragment by fragment for MPEG 2 TS.

**Comment by qchroman** [comment]
Thank you again for your fast replies. I will try some commands and see if I will be able to succeed.

**Comment by qchroman** [comment]
Ok, it worked perfectly fine with DASH. For HLS (MPEG 2 TS) it didn't for some reason. I created the asset

```
packager-win.exe ^
in=sintel_trailer-480p.mp4,stream=audio,segment_template=./drm/hls/frags-ts/audio/$Number$.ts,playlist_name=./drm/hls/frags-ts/audio/main.m3u8,hls_group_id=audio,hls_name=ENGLISH ^
in=sintel_trailer-480p.mp4,stream=video,segment_template=./drm/hls/frags-ts/480p/$Number$.ts,playlist_name=./drm/hls/frags-ts/480p/main.m3u8,iframe_playlist_name=./drm/hls/frags-ts/480p/iframe.m3u8 ^
--enable_raw_key_encryption ^
--protection_scheme cbcs ^
--keys key_id=d86bf8bc8fea4b25b2a6da42e623a007:key=447b4ac8d73103d316e102d51db12062 ^
--hls_key_uri skd://d86bf8bc8fea4b25b2a6da42e623a007 ^
--iv d86bf8bc8fea4b25b2a6da42e623a007 ^
--pssh 00000034707373680100000029701FE43CC74A348C5BAE90C7439A4700000001d86bf8bc8fea4b25b2a6da42e623a00700000000 ^
--clear_lead 0 ^
--hls_master_playlist_output ./drm/hls/frags-ts/manifest.m3u8
```

I then ran (using WSL)
```
cat ./drm/hls/frags-ts/480p/1.ts ./drm/hls/frags-ts/480p/2.ts ./drm/hls/frags-ts/480p/3.ts ./drm/hls/frags-ts/480p/4.ts ./drm/hls/frags-ts/480p/5.ts ./drm/hls/frags-ts/480p/6.ts ./drm/hls/frags-ts/480p/7.ts > ./drm/hls/frags-ts/480p/out.mp4
```

And tried decrypting video portion to simply check whether the video will play after decryption
```
packager-win.exe ^
in=./drm/hls/frags-ts/480p/out.mp4,stream=video,output=./drm/hls/frags-ts/480p/out.dec.mp4 ^
--enable_raw_key_decryption ^
--keys key_id=2b6c9ed01c934a0ea9ec1ce0bd0bf57c:key=21111eebd1788ab71acaa8a2da8cebd5
```

I ended up with
```
[0130/002139:INFO:demuxer.cc(88)] Demuxer::Run() on file './drm/hls/frags-ts/480p/out.mp4'.
[0130/002139:INFO:demuxer.cc(160)] Initialize Demuxer for file './drm/hls/frags-ts/480p/out.mp4'.
[0130/002139:ERROR:mp2t_media_parser.cc(310)] Ignore unsupported MPEG2TS stream type 0xdb
[0130/002139:ERROR:packager_main.cc(533)] Packaging Error: 6 (END_OF_STREAM):
```

I may be missing something. The original asset is a SAMPLE-AES protected HLS with MPEG2-TS segments.

If you have time to look into what I did wrong, that would be great.

Thank you in advance.

**Comment by kqyang** [comment]
@qchroman Ooops. 0xdb is encrypted stream, so we actually don't support decrypting SAMPLE-AES protected MPEG2-TS right now. 

Feel free to file a feature request for it if you'd like to get it supported (we do not have bandwidth to work on it right now though).

**Comment by qchroman** [comment]
Got it. Thank you!
