### ISSUE TITLE
DASH stream descriptor field "roles" not taken into account for WebVTT text streams

### ISSUE THREAD

**Issue by francois-cabrol** [google/shaka-packager#708]
## System info
**Operating System**: Windows 10
**Shaka Packager Version**: v2.4.1-c731217607-release

## Issue and steps to reproduce the problem

**Packager Command**: packager in=TestVideo_2160p23.mp4,stream=video,output=TestVideo_2160p23.mp4 in=TestVideo_lcaac_AraSPK.mp4,stream=audio,output=TestVideo_lcaac_AraSPK.mp4 in=TestVideo_lcaac_EngSPK.mp4,stream=audio,output=TestVideo_lcaac_EngSPK.mp4 in=TestVideo_lcaac_FraSPK.mp4,stream=audio,output=TestVideo_lcaac_FraSPK.mp4 in=TestVideo_lcaac_ZhoSPK.mp4,stream=audio,output=TestVideo_lcaac_ZhoSPK.mp4 in=TestVideo_Subtitle_AraCC.vtt,stream=text,lang=ar,dash_roles=caption,out=TestVideo_Subtitle_AraCC.vtt in=TestVideo_Subtitle_EngCC.vtt,stream=text,lang=en,dash_roles=caption,out=TestVideo_Subtitle_EngCC.vtt in=TestVideo_Subtitle_FraSUB.vtt,stream=text,lang=fr,dash_roles=subtitle,out=TestVideo_Subtitle_FraSUB.vtt in=TestVideo_Subtitle_ZhoSUB.vtt,stream=text,lang=zh,dash_roles=subtitle,out=TestVideo_Subtitle_ZhoSUB.vtt --mpd_output master.mpd 

**Extra steps to reproduce the problem?**
N/A

**What is the expected result?**
In the description of the WebVTT streams, I expect a <role> tag with the values specified in the **dash_roles** field (caption or subtitle) nested in the **AdaptationSet** or the **Representation** tags.

**What happens instead?**
No <role> tag is generated.  Here is the extract of the **master.mpd** dealing with the .vtt files:
` <Period id="0">
    <AdaptationSet id="0" contentType="text" lang="ar" subsegmentAlignment="true">
      <Representation id="0" bandwidth="256" mimeType="text/vtt">
        <BaseURL>TestVideo_Subtitle_AraCC.vtt</BaseURL>
      </Representation>
    </AdaptationSet>
    <AdaptationSet id="1" contentType="text" lang="en" subsegmentAlignment="true">
      <Representation id="1" bandwidth="256" mimeType="text/vtt">
        <BaseURL>TestVideo_Subtitle_EngCC.vtt</BaseURL>
      </Representation>
    </AdaptationSet>
    <AdaptationSet id="2" contentType="text" lang="fr" subsegmentAlignment="true">
      <Representation id="2" bandwidth="256" mimeType="text/vtt">
        <BaseURL>TestVideo_Subtitle_FraSUB.vtt</BaseURL>
      </Representation>
    </AdaptationSet>
    <AdaptationSet id="3" contentType="text" lang="zh" subsegmentAlignment="true">
      <Representation id="3" bandwidth="256" mimeType="text/vtt">
        <BaseURL>TestVideo_Subtitle_ZhoSUB.vtt</BaseURL>
      </Representation>
    </AdaptationSet>`

I have the same behavior regardless if I name the field **roles** or **dash_roles** in my command line.

<Please attach the input files or email to shaka-packager-issues@google.com.>
<Please provide any additional information below.>

**Comment by kqyang** [comment]
Thanks for reporting the problem. Yes, that is a bug.

**Comment by kqyang** [comment]
The fix was cherry-picked to v2.4.2.
