### ISSUE TITLE
Disable a segment timeline for continuous streaming

### ISSUE THREAD

**Issue by r0bust-one** [google/shaka-packager#715]
## System info
**Operating System**: Windows 10 Enterprise 1909 (build 18363.657)
**Browser**: Google Chrome Version 79.0.3945.130 (Official Build) (64-bit)
**FFMPEG Version**:  git-2020-01-31-62d92a8 (Build: ffmpeg-20200131-62d92a8-win64-static)
**Shaka Packager Version**: version v2.4.1-c731217607-release (packager-win.exe)
**Shaka Player Version**: version v2.5.9 (shaka-player.compiled.js, [CDN link](https://cdnjs.cloudflare.com/ajax/libs/shaka-player/2.5.9/shaka-player.compiled.js) )

## Description
I'm trying to establish a long-living/continuous live streaming using MPEG-DASH. "Long-living" means that a live stream can last hours or even days. For that purpose, I use an already prepared bunch of .mp4 files, which should be "streamed" sequentially one after another. The point here is to use a segment template with a fixed segment duration (i.e. 5 seconds per segment) all the time. Thus, I don't need to use a segment timeline at all (I don't need the ability to seek stream backward or forward, I don't need to know where the start and the end are, time offsets, etc. - just play new incoming segments one by one).
To achieve that, I tried to use the solution from issue #400 , but it didn't help. 
Looks like those flags `--allow_approximate_segment_timeline --segment_template_constant_duration` don't help to solve such cases anymore, or I'm using them wrong... More details are below.

## Issues
1. Instead of producing a manifest with SegmentTemplate tag with "duration" attribute in it, for some reason Shaka Packager produces SegmentTimeline inside of a SegmentTemplate and completely ignores "duration" attribute.
2. On the client side, it affects a playback - when I stop streaming one .mp4 file and start to stream it again (to Shaka Packager), the Shaka Player will wait N amount of time at which the previous playback was stopped and only then will play the stream. For example, if you streamed 80 seconds of some .mp4 file, then stopped that streaming process (ffmpeg), and then run it again, the client side will wait 80 seconds before starting the playback.

## Steps to reproduce the problem
1. Shaka Packager is set up to receive data from UDP:
`
packager-win   "in=udp://127.0.0.1:40000,stream=audio,init_segment=audio_init.mp4,segment_template=audio_$Number$.m4s" 
--segment_duration 5 
--mpd_output=manifest.mpd 
--allow_approximate_segment_timeline  
--segment_template_constant_duration
`
2. FFMPEG is used to stream already prepared data over UDP:
`ffmpeg -re -i output.mp4 -c:a copy -f mpegts udp:127.0.0.1:40000`

3. Stop FFMPEG process and check the content of a manifest.mpd file after 1 minute of playback:
```
<?xml version="1.0" encoding="UTF-8"?>
<!--Generated with https://github.com/google/shaka-packager version v2.4.1-c731217607-release-->
<MPD xmlns="urn:mpeg:dash:schema:mpd:2011" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:mpeg:dash:schema:mpd:2011 DASH-MPD.xsd" profiles="urn:mpeg:dash:profile:isoff-live:2011" minBufferTime="PT2S" type="dynamic" publishTime="2020-02-21T10:52:33Z" availabilityStartTime="2020-02-21T10:51:41Z" minimumUpdatePeriod="PT5S" timeShiftBufferDepth="PT1800S">
  <Period id="0" start="PT0S">
    <AdaptationSet id="0" contentType="audio" segmentAlignment="true">
      <Representation id="0" bandwidth="132788" codecs="mp4a.40.2" mimeType="audio/mp4" audioSamplingRate="44100">
        <AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="2"/>
        <SegmentTemplate timescale="90000" initialization="audio_init.mp4" media="audio_$Number$.m4s" startNumber="1">
          <SegmentTimeline>
            <S t="126000" d="325996"/>
            <S t="451996" d="449300" r="1"/>
            <S t="1350596" d="451404"/>
            <S t="1802000" d="449305" r="1"/>
            <S t="2700610" d="451397"/>
            <S t="3152007" d="449306" r="1"/>
            <S t="4050619" d="451396"/>
            <S t="4502015" d="449306"/>
          </SegmentTimeline>
        </SegmentTemplate>
      </Representation>
    </AdaptationSet>
  </Period>
</MPD>
```
4. Run the same FFMPEG command again
5. Again, check the content of a manifest.mpd file after 1 minute of playback:
```
<?xml version="1.0" encoding="UTF-8"?>
<!--Generated with https://github.com/google/shaka-packager version v2.4.1-c731217607-release-->
<MPD xmlns="urn:mpeg:dash:schema:mpd:2011" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:mpeg:dash:schema:mpd:2011 DASH-MPD.xsd" profiles="urn:mpeg:dash:profile:isoff-live:2011" minBufferTime="PT2S" type="dynamic" publishTime="2020-02-21T10:56:19Z" availabilityStartTime="2020-02-21T10:51:41Z" minimumUpdatePeriod="PT5S" timeShiftBufferDepth="PT1800S">
  <Period id="0" start="PT0S">
    <AdaptationSet id="0" contentType="audio" segmentAlignment="true">
      <Representation id="0" bandwidth="132788" codecs="mp4a.40.2" mimeType="audio/mp4" audioSamplingRate="44100">
        <AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="2"/>
        <SegmentTemplate timescale="90000" initialization="audio_init.mp4" media="audio_$Number$.m4s" startNumber="1">
          <SegmentTimeline>
            <S t="126000" d="325996"/>
            <S t="451996" d="449300" r="1"/>
            <S t="1350596" d="451404"/>
            <S t="1802000" d="449305" r="1"/>
            <S t="2700610" d="451397"/>
            <S t="3152007" d="449306" r="1"/>
            <S t="4050619" d="451396"/>
            <S t="4502015" d="449306"/>
            <S t="4951321" d="194361"/>
            <S t="126000" d="325996"/>
            <S t="451996" d="449300" r="1"/>
            <S t="1350596" d="451404"/>
            <S t="1802000" d="449305" r="1"/>
            <S t="2700610" d="451397"/>
            <S t="3152007" d="449306" r="1"/>
            <S t="4050619" d="451396"/>
            <S t="4502015" d="449306"/>
          </SegmentTimeline>
        </SegmentTemplate>
      </Representation>
    </AdaptationSet>
  </Period>
</MPD>
```

## What is the expected result?

1. the manifest.mpd content like this (without segment timeline and with segment duration instead):
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<MPD xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="urn:mpeg:dash:schema:mpd:2011" xmlns:xlink="http://www.w3.org/1999/xlink" xsi:schemaLocation="urn:mpeg:DASH:schema:MPD:2011 http://standards.iso.org/ittf/PubliclyAvailableStandards/MPEG-DASH_schema_files/DASH-MPD.xsd" profiles="urn:mpeg:dash:profile:isoff-live:2011" type="dynamic" minimumUpdatePeriod="PT5S" suggestedPresentationDelay="PT5S" availabilityStartTime="2020-02-18T20:35:00.000Z" publishTime="2020-02-18T20:48:36.860Z" minBufferTime="PT10.0S">
  <Period id="0" start="PT0.0S">
    <AdaptationSet id="0" contentType="audio" segmentAlignment="true" bitstreamSwitching="true">
      <Representation id="0" mimeType="audio/mp4" codecs="mp4a.40.2" bandwidth="128000" audioSamplingRate="44100">
        <AudioChannelConfiguration schemeIdUri="urn:mpeg:dash:23003:3:audio_channel_configuration:2011" value="2"/>
        <SegmentTemplate timescale="1000000" duration="5000000" availabilityTimeOffset="4.977" initialization="init-stream$RepresentationID$.m4s" media="chunk-stream$RepresentationID$-$Number%05d$.m4s" startNumber="1"/>
      </Representation>
    </AdaptationSet>
  </Period>
</MPD>
```
This example was produced by ffmpeg: 
`ffmpeg -i ... -f dash -seg_duration 5 -use_template 0 -use_timeline 1 -streaming 1 manifest.mpd`

2. After restarting the streaming process (ffmpeg), playback at the client side (shaka player) should play incoming segments without waiting for some point in time, at which the previous streaming process was stopped.

**Comment by kqyang** [comment]
@r0bust-one Are you trying to turn a set of mp4 files to repeated live streams? @joeyparrish Is it something [Shaka Streamer](https://github.com/google/shaka-streamer) supports?

**Comment by joeyparrish** [comment]
The issue with playback going funny seems to me to be caused by starting and stopping ffmpeg.  Each time it starts, timestamps begin again at 0, I suspect.  If you want a long-lived stream, you need a long-lived instance of ffmpeg.

For this, I see a couple of options:
  1. If your set of MP4s is finite and known in advance, I would suggest you build a single MP4 with all of their contents, and feed that to ffmpeg with `-stream_loop -1` to keep looping that same MP4 over and over.
  2. If your set of MP4s is not finite and known in advance, I would suggest you feed them through a pipe (fifo, named pipe, etc) to ffmpeg with `-fflags +genpts` to generate new timestamps for the input as it comes in through the pipe.

Also, if you know your set of MP4s in advance, another option is [Shaka Streamer](https://github.com/google/shaka-streamer).  It will run ffmpeg and Shaka Packager for you and loop your inputs.  All you do is write a config file.  It can output your live stream either to a local file or to cloud storage (Google or Amazon).

Shaka Streamer does not currently have the ability to concatenate several inputs together for you, but it **can** loop inputs for you forever, and it **can** take separate audio and video inputs.  So you can concatenate the inputs together and combine with ffmpeg once as pre-work, then feed that longer single input to Shaka Streamer for a never-ending live stream.

If you'd like Shaka Streamer to concatenate inputs for you, you can [file a feature request on Streamer](https://github.com/google/shaka-streamer/issues) and we'll look into it.

Does this help?

**Comment by r0bust-one** [comment]
@kqyang, @joeyparrish Hi guys! Thank you for your replies!
My set of MP4 files is **not** finite and is **not** known in advance, it's dynamically generated by another process.

@kqyang I don't try to create a repeated stream, but rather be able to re-stream some mp4 file multiple times (not even sequentially) when it's necessary.

@joeyparrish You are right in your second suggestion, that's what I tried to do before posting this question.

A little clarification of what's going on:
The external process runs the ffmpeg instance to mux some input data into mp4 content. 
Then, that newly generated mp4 content should be live-streamed to the packager. 
It is very important to have control over the "live-streaming" of that content, since that external process has to know when to start another muxing process (when to repeat all that I've just described, but for the new input data). For that purpose, `-re` option is used for the ffmpeg, thus it streams that content on its original playback speed. 
So at the end of that stream, the external process has a termination event which signals to it that it is time to run the process again for new input data.

Let's consider the imaginary example to understand what I mean:
Let's say you want to imitate a children TV channel, which shows cartoons :)
You have a bunch of short-series cartoons, like episodes of "Tom & Jerry", "Donald Duck", and "Pokemon". And you want to make it go by schedule or randomly, like: 213th episode of "Pokemon" goes first, then goes 14th episode of "Tom & Jerry", then goes 67th episode of "Donald Duck", and so on. So that orchestration by moving through a schedule or random selection is being handled by some external process, i.e. program on Python or Node, whatever.
So that external process will determine the next cartoon to play, then run a child ffmpeg process to mux the original file into mp4 content and to stream it live to the packager, and at the end of the stream will repeat those actions for the next cartoon (Of course, in real scenarios, such kind of content is already muxed, but that's an example, and muxing part cannot be omitted in my original case).
You might be wondering why not to pre-generate all those content first, but I'd like to say that it's more efficient in that way, because of only necessary content generation, less disc space consumption, and most importantly - signals of the necessary events.

So at this point, we have at least two options: to stream that mp4 content "on the fly" while it's creating (as ffmpeg developers usually suggest to do), or to generate mp4 output file first, and then feed that file to another ffmpeg process, which will actually stream it's incoming input data forever, thus to use pipes.

The result of the first variant has already been described in the description of this question: packager receives packets gracefully as expected, but generates the manifest in its own way, ignoring details.

With the second variant, however, I ran into trouble with piping: MP4 itself cannot be piped directly, because in that case, ffmpeg says that the output does not support a seekable format.
Some `movflags` does the trick, by placing _moov_ header at the begging of the file. The following setting allowed me to send mp4 file to the `pipe:` output directly `-movflags +faststart+empty_moov`. But the receiver-ffmpeg instance (which reads the pipe) immediately throws an error: "moov atom not found. Invalid data found when processing input".
The only way that worked for me is when I used the _mpegts_ container.
I write to the pipe like this:
```
ffmpeg -re -i output3.mp4 -c:a copy -movflags +frag_keyframe+faststart+empty_moov -f mpegts /tmp/pipe1
```
then, read that data from pipe and distribute it:
```
ffmpeg -re -f mpegts -i /tmp/pipe1 -c:a copy -f mpegts udp://127.0.0.1:40000
```
But in that case, everything ends when a named pipe has been read completely... And I don't know for now how to prevent that termination, unfortunately (to be able to read from named pipe forever). The only way I now work without termination is to use stdin/stdout instead (i.e. `pipe:`), but I can be wrong here, need to check it.

@joeyparrish, So in terms of what you suggest, if I understood you correctly, I need to add the `-fflags +genpts` to my ffmpeg command (of streaming instance) and make the pipe live as long as needed, like this:
```
ffmpeg -re -fflags +genpts -f mpegts -i /tmp/pipe1 -c:a copy -f mpegts udp://127.0.0.1:40000
```

Also, regarding the timestamps. Sorry for annoying questions but: 
1) Are those timestamps required by MPEG-DASH protocol specs, or only by Shaka Packager? 
2) Why does it matter to have timestamps in situations when we explicitly define segmentation with constant duration? The segment number is always increasing (as Shaka Player requires according to its docs), the manifest updates provide necessary info about playback... why don't just take that segment and play... (actually, dash.js does exactly that atm).

And, also, could you please tell why those parameters for Shaka Packager (`--segment_duration`, `--allow_approximate_segment_timeline`, `--segment_template_constant_duration` - neither together, not separate) don't disable timeline and don't provide duration, but did that in issue #400 ? Are they outdated/deprecated?

**Comment by r0bust-one** [comment]
I've just tested the suggestion above and it worked, `-fflags +genpts` and `pipe:` helped me, thank you!
The only question left is this one:

> And, also, could you please tell why those parameters for Shaka Packager (--segment_duration, --allow_approximate_segment_timeline, --segment_template_constant_duration - neither together, nor separate) don't disable timeline and don't provide duration, but did that in issue #400 ? Are they outdated/deprecated?

**Comment by joeyparrish** [comment]
> Are those timestamps required by MPEG-DASH protocol specs, or only by Shaka Packager?
Why does it matter to have timestamps in situations when we explicitly define segmentation with constant duration? The segment number is always increasing (as Shaka Player requires according to its docs), the manifest updates provide necessary info about playback... why don't just take that segment and play... (actually, dash.js does exactly that atm).

The timestamps that ffmpeg outputs in the TS container are the same timestamps that packager outputs in the final segments.

DASH playback in a browser works through the MediaSource API.  MediaSource uses those timestamps to piece together the presentation.  If you feed MediaSource a single segment with timestamp 30 and duration 10, the buffered range is 30-40.  Seek the video element to 0, and nothing will play, because there's nothing in the buffer at that time.

There are other ways to use MediaSource (different modes, timestamp adjustments), but those are the basics, and that's why the timestamps matter.  (I don't know which of these things dash.js does to manipulate the segments it's playing, but Shaka Player assumes that the manifest is accurate.)

**Comment by r0bust-one** [comment]
@joeyparrish Ok, thank you very much for these clarifications!

One more question has just appeared: could you please point me out how to set up more that one adaptation set in the output manifest for Shaka Packager?
I have three streams muxed with one codec, and one stream muxed with another codec, so four streams and two codecs in summary. 
Currently, Shaka Packager simply ignores that fourth stream with different codec... (But if I'm not wrong, the stream with a different codec should be placed in another adaptation set in the manifest)
Usually, to achieve this with ffmpeg, I use the following option: `-adaptation_sets "id=0,streams=0,1,2 id=1,streams=3"` of the `dash` muxer. But how to do that with Shaka Packager?
And excuse me for the off-top, but I haven't found related info in the docs, thus decided to ask about it here.

**Comment by kqyang** [comment]
@r0bust-one You can index stream by stream number, e.g. if there are four different streams in the input, you can use "in=udp://127.0.0.1:40000,stream=**k**,init_segment=..." with k being 0..3 to select kth stream in the input. Shaka Packager generates multiple adaptation sets automatically if the streams cannot adapt to each other.

**Comment by r0bust-one** [comment]
@kqyang Thanks for the reply!
Also, could you please tell me: what are the ways to set ISO BMFF input for Shaka Packager **in case of streaming**? What I mean is that. Even though MPEG2TS container can carry on streams of many types, there are cases when ISO BMFF is the only way to go (my case). I know that it can't be streamed in a simple way, but... maybe there are some workarounds, like pipes, or segmentation, etc ?

**Comment by joeyparrish** [comment]
Shaka Streamer uses fragmented MP4 exclusively in its internal pipelines.  So all input to Shaka Packager from Shaka Streamer is now in MP4.

There's nothing special you need to do from Shaka Packager's perspective.  To generate fragmented MP4 that can be piped into Packager via named pipe or UDP, you need the following options in ffmpeg:

https://github.com/google/shaka-streamer/blob/609dd4b30b83c984186e9c9f26d4c5beccbaadde/streamer/transcoder_node.py#L176-L181
```py
        # Output MP4 in the pipe, for all codecs.
        '-f', 'mp4',
        # These flags make it fragmented MP4, which is necessary for a pipe.
        '-movflags', '+faststart+frag_keyframe',
        # Opus in MP4 is considered "experimental".
        '-strict', 'experimental',
```

Does this help?

**Comment by r0bust-one** [comment]
@joeyparrish Hi!
I've tried that previously, and I've just tested this again - an error occurred.
The command that starts Shaka Packager:
```
packager-win ^ 
	"in=udp://127.0.0.1:40000,stream=audio,init_segment=../receiver/audio0_init.mp4,segment_template=../receiver/audio0_$Number$.m4s" ^
	--segment_duration 5 ^ 
	--mpd_output=../receiver/manifest2.mpd ^ 
	--allow_approximate_segment_timeline ^ 
	--segment_template_constant_duration
```
The ffmpeg command for delivering mp4 to the packager: 
```
ffmpeg -re -i output_short.mp4 -map 0:a -c:a copy -f mp4 -strict -2 -movflags +faststart+frag_keyframe udp://127.0.0.1:40000
```
Shaka Packager output, including error:
```
[0226/232015:INFO:demuxer.cc(88)] Demuxer::Run() on file 'udp://127.0.0.1:40000'.
[0226/232015:INFO:demuxer.cc(160)] Initialize Demuxer for file 'udp://127.0.0.1:40000'.
[0226/232712:ERROR:box_reader.cc(121)] NOT IMPLEMENTEDBox 'moov' run to EOS.
[0226/232712:ERROR:packager_main.cc(533)] Packaging Error: 8 (PARSER_FAILURE): Cannot parse media file udp://127.0.0.1:40000
```
How it all behaves: ffmpeg **sequentially** writes the entire mp4 file (20 seconds long) into UDP, **and only then** Shaka Packager consumes that file and produces the output above... 

The variant `-movflags +faststart+frag_keyframe+empty_moov`  hasn't helped - same output as above.

**Comment by kqyang** [comment]
For pipe, it does not matter, but for udp, you'll need to start packager first to avoid missing the init segment. Also, you need to use `+faststart+frag_keyframe+empty_moov`. 

@r0bust-one Did you start packager or ffmpeg first?

**Comment by joeyparrish** [comment]
@kqyang, we used to use `+faststart+frag_keyframe+empty_moov`, but the `+empty_moov` caused issues with Packager and AV1.  Removing `+empty_moov` seems to be necessary in some cases.

**Comment by r0bust-one** [comment]
> Did you start packager or ffmpeg first?
I started Shaka Packager first, then started ffmpeg

**Comment by kqyang** [comment]
@joeyparrish Interesting. I tried ffmpeg command with audio output, `moof` is only generated if `empty_moov` is included in the option. I'll confirm later.

**Comment by kqyang** [comment]
@r0bust-one For audio, you'll need to set fragment duration explicitly, e.g. `-frag_duration=3` as every audio frame is a key frame so it does not fragment at key frame automatically.

@joeyparrish You are right that `empty_moov` is not needed. It did not generate `moof` because without `-frag_duration`, ffmpeg puts everything in the first segment, i.e. in `moov` when `empty_moov` is not specified. 

The AV1 problem looks like a bug to me though, as it should still generate a valid moov with proper codec configuration record even though it does not contain any frames.

**Comment by r0bust-one** [comment]
@kqyang ,

```
[0227/010817:INFO:demuxer.cc(88)] Demuxer::Run() on file 'udp://127.0.0.1:40000'.
[0227/010817:INFO:demuxer.cc(160)] Initialize Demuxer for file 'udp://127.0.0.1:40000'.
[0227/010852:ERROR:box_reader.cc(121)] NOT IMPLEMENTEDBox 'moov' run to EOS.
[0227/010852:ERROR:packager_main.cc(533)] Packaging Error: 8 (PARSER_FAILURE): Cannot parse media file udp://127.0.0.1:40000
```

1) by using `--fragment-duration 5` on Shaka Packager side only - occurs error above, and packager waits whole file.

2) by using `-frag_duration 5` on ffmpeg side only - occurs same error above, but in that case packager reacts immediately.

3) using flags on both sides at the same time ( case 1) and case 2) ) get the same error immediately..

**Comment by kqyang** [comment]
@r0bust-one Is the error `NOT IMPLEMENTEDBox 'moov' run to EOS.` in `moov` or another box?

**Comment by r0bust-one** [comment]
@kqyang I don't know, I receive this error from packager right after I start the ffmpeg process (by command described in prev message), it happens immediately. Then packager crashes and exits, and ffmpeg goes further sending file to UDP.
If there is any way to determine what you ask about (regarding the moov or another box), please tell me how to do that, and I'll bring you all the necessary info.

**Comment by kqyang** [comment]
@r0bust-one What is the exact error message from packager output? Is the text after "Box" `moov`? I tried just now but wasn't able to re-produce your problem though.

Also, what is the total duration of your input content?

Anyway, here is the script I used:

```shell
./packager \
       'in=udp://127.0.0.1:40000,stream=audio,init_segment=test/audio0_init.mp4,segment_template=test/audio0_$Number$.m4s' \
        --segment_duration 5 \
        --mpd_output=test/manifest2.mpd \
        --allow_approximate_segment_timeline \
        --segment_template_constant_duration
```

```shell
ffmpeg -re -i ../bourne_1000k.mp4 -map 0:a -c:a copy -f mp4 -strict -2 -movflags +faststart+frag_keyframe -frag_duration 3 udp://127.0.0.1:40000
```

**Comment by r0bust-one** [comment]
@kqyang 
This is the exact output just copied from the terminal:
```
[0227/015340:INFO:demuxer.cc(88)] Demuxer::Run() on file 'udp://127.0.0.1:40000'.
[0227/015340:INFO:demuxer.cc(160)] Initialize Demuxer for file 'udp://127.0.0.1:40000'.
[0227/015353:ERROR:box_reader.cc(121)] NOT IMPLEMENTEDBox 'moov' run to EOS.
[0227/015353:ERROR:packager_main.cc(533)] Packaging Error: 8 (PARSER_FAILURE): Cannot parse media file udp://127.0.0.1:40000
```
So, `NOT IMPLEMENTEDBox 'moov' run to EOS.` it's how it exaclty outputted in the terminal.

>what is the total duration of your input content?

 Duration: 00:00:20.02, start: 0.000000, bitrate: 2194 kb/s

**Comment by kqyang** [comment]
@r0bust-one Can you share your content? I'll try if I can re-produce with it.

**Comment by r0bust-one** [comment]
@kqyang,
 https://we.tl/t-erjlYUPF5m

**Comment by kqyang** [comment]
@r0bust-one Yes, I was able to re-produce the problem. I think it is a bug in FFmpeg, which generates unbounded `moov` box when there are multiple audio streams in the output.

You can workaround it by mapping different audio streams to different endpoints. Here is an example command that maps the first audio stream only. You can adapt it to support multiple outputs.

```shell
ffmpeg -re -i ../bourne_1000k.mp4 -map 0:a:0 -c:a copy -f mp4 -strict -2 -movflags +faststart+frag_keyframe -frag_duration 3 udp://127.0.0.1:40000
```

**Comment by r0bust-one** [comment]
@kqyang  Thank you! Previously I tried to do so but had no success, however, now the `frag_duration` did the trick, and it works. My problem is almost finished. 
Could you please help me with the following:
Packager runs with this command
```
packager-win ^ 
	"in=udp://127.0.0.1:40000,stream=audio,init_segment=../receiver/audio0_init.mp4,segment_template=../receiver/audio0_$Number$.m4s" ^ 
	"in=udp://127.0.0.1:40001,stream=audio,init_segment=../receiver/audio1_init.mp4,segment_template=../receiver/audio1_$Number$.m4s" ^
	--segment_duration 5 ^ 
	--mpd_output=../receiver/manifest2.mpd ^ 
	--allow_approximate_segment_timeline ^ 
	--segment_template_constant_duration
```
Then, ffmpeg process starts, which reads mp4 data from stdin and sends it to packager (the idea is to read the input forever along with generation of new timestamps, as @joeyparrish suggested previously):
```
ffmpeg -re -stream_loop -1 -fflags +genpts -f mp4 -i pipe: ^ 
	-map 0:a:0 -c:a copy -movflags +faststart+frag_keyframe -strict -2 -f mp4 -frag_duration 5 udp://127.0.0.1:40000 ^ 
	-map 0:a:1 -c:a copy -movflags +faststart+frag_keyframe -strict -2 -f mp4 -frag_duration 5 udp://127.0.0.1:40001
```
And lastly, another ffmpeg process is piped into a previous one (it is piped to previous one in the external app, thus such kind of piping can be done as much as needed)
```
ffmpeg -re -i output_short.mp4 -map 0:a -c:a copy -f mp4 -strict -2 -movflags +faststart+frag_keyframe -frag_duration 5 pipe:
```
The problem is that at the end of sending mp4 file in the latter command, I get the following errors from ffmpeg:
```
[mov,mp4,m4a,3gp,3g2,mj2 @ 000001fad5edcbc0] stream 0, offset 0xa54: partial file
pipe:: Invalid data found when processing input
size=     429kB time=00:00:19.99 bitrate= 175.8kbits/s speed=   1x
video:0kB audio:5197kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Error writing trailer of pipe:: Broken pipe
```
and Packager also reacts with this output:
```
[0228/001649:INFO:demuxer.cc(88)] Demuxer::Run() on file 'udp://127.0.0.1:40000'.
[0228/001649:INFO:demuxer.cc(88)] Demuxer::Run() on file 'udp://127.0.0.1:40001'.
[0228/001649:INFO:demuxer.cc(160)] Initialize Demuxer for file 'udp://127.0.0.1:40000'.
[0228/001649:INFO:demuxer.cc(160)] Initialize Demuxer for file 'udp://127.0.0.1:40001'.
[0228/001716:ERROR:box_reader.cc(121)] NOT IMPLEMENTEDBox 'mfra' run to EOS.
[0228/001716:ERROR:box_reader.cc(121)] NOT IMPLEMENTEDBox 'mfra' run to EOS.
[0228/001716:WARNING:fragmenter.cc(70)] Unexpected sample with zero duration @ dts 881975
[0228/001716:ERROR:packager_main.cc(533)] Packaging Error: 8 (PARSER_FAILURE): Cannot parse media file udp://127.0.0.1:40000
```
I'm definitely sure that the issue is somewhere in the ffmpeg command. I which I was more experienced with it, but unfortunalely, I have no clue of how to fix that, I haven't found a solution.
Please have a look at this

**Comment by kqyang** [comment]
@r0bust-one I am afraid that you cannot pipe two mp4 files - there are a number of problems:

- Every new mp4 file introduces a new `moov`, which may not match with the others
- At the end of a mp4 file, `FFmpeg` ends it with unbounded `mfra` box which runs to the end of file, so the parser/packager won't be able to recognize the data after it.

Is there any reason that you don't want to use MPEG2-TS?

**Comment by r0bust-one** [comment]
@kqyang 

> Is there any reason that you don't want to use MPEG2-TS?
I would like to use it so much (because this overall process perfectly works with it), but MPEG2-TS can't carry on lossless codecs, like flac

**Comment by r0bust-one** [comment]
@kqyang Anyway, thank you for your help!

Regarding ffmpeg, could you please tell me:
If we step away from mp4 for a while - do you know some way to constantly generate new timestamps for incoming data? (like `stream_loop` or `concat` do, but for dynamic input, like pipe)
Or to avoid such kind of problems, when the next file comes after previous one:
```
Non-monotonous DTS in output stream 0:0; previous: 881714, current: 51200; changing to 881715. This may result in incorrect timestamps in the output file.
```
I thought the `-fflags +genpts` does that, but it doesn't. `use_wallclock_as_timestamps 1` solves issue above but makes playback completely unlistenable (playback twitches in fragments, repeats, etc).
Maybe some additional flags, bitstream filters or simple filters?

**Comment by kqyang** [comment]
@r0bust-one Unfortunately I don't have experience with this. Does it work for MPEG2-TS?

@joeyparrish may be able to help.

**Comment by r0bust-one** [comment]
@kqyang 

> Does it work for MPEG2-TS?

Yes, works perfectly

**Comment by joeyparrish** [comment]
Sorry, `-fflags +genpts` is all I know off-hand.  I tend to spend a lot time searching the full ffmpeg docs (https://ffmpeg.org/ffmpeg-all.html) whenever I need to figure out something new.  It's not fun, and this is one the main reasons we created Shaka Streamer, so that we could formalize the things that work well and stop having to type so many arcane ffmpeg parameters.

I'm not sure if Shaka Streamer is good fit for your use-case or not, though.  We do have something you might be interested in for this sequential-but-unpredictable-input scenario.  You can configure an input type which launches an external command that outputs continuous media to a named pipe.  We don't care what it is, so long as it's able to write to a named pipe in any format that ffmpeg can read from a named pipe.  This is how we generate a [live stream of the Shaka Player git history](https://shaka-player-demo.appspot.com/demo/#asset=https://storage.googleapis.com/shaka-live-assets/player-source.mpd;build=compiled).  Every time we loop to the beginning of the history, the loop incorporates new commits made since the last iteration, so the loop gets a little longer day-by-day.

If you want to build an external script or tool that outputs a continuous stream of video to a pipe, making whatever scheduling decisions in a background thread, that might work with Shaka Streamer.  Let me know if you'd like to pursue that as a solution, and we can start a new thread on the Streamer repo to figure out the details.

**Comment by r0bust-one** [comment]
@kqyang @joeyparrish 
Sorry for a late reply, I wasn't able to write.
I just want to say thank you guys for your help and support!
Definitely, I won't stop on this issue and will look for a solution. Thus, I would be glad to see you again in Shaka Streamer repo thread, soon)
As for this thread, let's consider it as closed/solved.
