### ISSUE TITLE
Is it possible to decrypt HLS/Fairplay (non single-file)?

### ISSUE THREAD

**Issue by salmoro** [google/shaka-packager#718]
## System info
**Operating System**: WIndows 10
**Shaka Packager Version**: 2.4.1

## Issue and steps to reproduce the problem

This is more of a question than a bug report.

I'd like to know if it is possible to decrypt Fairaply HLS content which wasn't packaged as a single file.

I can successfully decrypt Wdievine/Webm but with FairPlay HLS I get `Could not find 'moov' box in file` when trying to decrypt the individual files.

I'm assuming this is something related to not passing in the init file but it's not clear to me how and if this is supported.

My arguments look like this:
```
in=video\360_600_264_1.mp4,stream=video,out=out\360_600_264_1.mp4 \
in=video\360_600_264_2.mp4,stream=video,out=out\360_600_264_2.mp4 \
in=video\360_600_264_3.mp4,stream=video,out=out\360_600_264_3.mp4 \
in=video\360_600_264_4.mp4,stream=video,out=out\360_600_264_4.mp4 \
in=video\360_600_264_5.mp4,stream=video,out=out\360_600_264_5.mp4 \
--enable_raw_key_decryption \
--keys label=HD:key_id=${keyID}:key=${key},label=SD:key_id=${keyID}:key=${key}
```
I also have `360_600_264_init.mp4` and `360_600_264.m3u8` files but I don't use them as  I don't know how.

Thanks!

**Comment by kqyang** [comment]
@salmoro Multi-files decrypt is not supported right now. You can concatenate the files before passing it to packager.

In Linux, you can simply use `cat` to concatenate the files.

Does that answer your question?

**Comment by salmoro** [comment]
@kqyang Yes! that works perfectly.
Thank you very much.
