### ISSUE TITLE
Update latest Docker image

### ISSUE THREAD

**Issue by night91** [google/shaka-packager#720]
Currently https://hub.docker.com/r/google/shaka-packager is at 2.3.0. Could be good to upload the latest release at 2.4.1.

**Comment by kqyang** [comment]
Ahh, the docker hub auto build has stopped working. I'll see if we can bring it back.

**Comment by kqyang** [comment]
This is now fixed!

(We are still not able to bring back DockerHub auto-build, but we have created a local script to push images to DockerHub)
