### ISSUE TITLE
Question - How i can create a hls stream with Sample-Aes encryption with multiple ts segments  and seperate key for a group of segments.

### ISSUE THREAD

**Issue by Virender-Dangi** [google/shaka-packager#723]
## System info
I am ok with any system. Linux or windows

## Things i tried
I tried this command but this gives me single key for all commands
 packager-win.exe in=test.mp4,stream=video,segment_template=output/$Number$.ts,playlist_name=output/main.m3u8,iframe_playlist_name=output/iframe.m3u8,drm_label=SD  --hls_master_playlist_output test.m3u8  --enable_raw_key_encryption --keys label=SD:key_id=f3c5e0361e6654b28f8049c778b23946:key=a4631a153a443df9eed0593043db7519 --iv 11223344556677889900112233445566 --hls_key_uri https://dummyurl/uniqueid/1.key --segment_duration=10

## This is what my output should look like 
I want my m3u8 to look like this

#EXTM3U
#EXT-X-TARGETDURATION:10
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-PLAYLIST-TYPE:VOD
#EXTINF:9.96,	
#EXT-X-KEY:METHOD=SAMPLE-AES,URI="https://dummyurl/uniqueid/test_Key_Proxy_0.key",IV=0x73fbe3277bdf0bfc5217125bde4ca589
test_Proxy_0.ts
#EXTINF:10,	
test_Proxy_1.ts
#EXTINF:10,	
test_Proxy_2.ts
#EXTINF:10,	
test_Proxy_3.ts
#EXTINF:10,	
test_Proxy_4.ts
#EXTINF:10,	
test_Proxy_5.ts
#EXTINF:9.92,	
test_Proxy_6.ts
#EXTINF:10,	
test_Proxy_7.ts
#EXTINF:10,	
test_Proxy_8.ts
#EXTINF:9.96,	
test_Proxy_9.ts
#EXTINF:10,	
#EXT-X-KEY:METHOD=SAMPLE-AES,URI="https://dummyurl/uniqueid/test_Key_Proxy_1.key",IV=0xd3c8ab5f62a2f82d990978057602181f
test_Proxy_10.ts
#EXTINF:9.88,	
test_Proxy_11.ts
#EXTINF:10,	
test_Proxy_12.ts
#EXTINF:10,	
test_Proxy_13.ts
#EXTINF:10,	
test_Proxy_14.ts
#EXTINF:9.88,	
test_Proxy_15.ts
#EXTINF:9.88,	
test_Proxy_16.ts
#EXTINF:10,	
test_Proxy_17.ts
#EXTINF:9.96,	
test_Proxy_18.ts
#EXTINF:10,	
test_Proxy_19.ts
#EXTINF:10,	
#EXT-X-KEY:METHOD=SAMPLE-AES,URI="https://dummyurl/uniqueid/test_Key_Proxy_2.key",IV=0x23926a684d0476db82d83c640068f662
test_Proxy_20.ts
#EXTINF:9.88,	
test_Proxy_21.ts
#EXT-X-ENDLIST

**Comment by kqyang** [comment]
@Virender-Dangi This is basically key rotation. Raw key rotation is not supported right now. We do support key rotation using [Widevine DRM Common Encryption API](http://storage.cloud.google.com/wvdocs/Widevine_DRM_Encryption_API.pdf). 

One option for you is to set up a common encryption server following Widevine DRM Common Encryption API. Does that work for you?

**Comment by Virender-Dangi** [comment]
@kqyang - Thanks for your reply. I am new to this and trying to understand. Here is my requirement. 
1. I want hls stream to play in Safari with some encryption. 
 Currently we have a legacy system where we use apple media file segmentor with AES-128 encryption to generate the hls streams. 
Since we want to do this in cloud we can't run the legacy system as per my understanding media file segmentor only runs in mac. 

So i am trying shaka packager to create the hls stream with encryption. What you suggest to be the best option here.

Also if i want to have a single package with multiple DRM like (Widevine, Fairplay or Sample -AES, Playready) what will be the best approach? 

FYI- The link you send me for Widevine DRM common Encyption API is giving me access issue. Also i am not able to check the same document on github documentation as well because of access issue. 
https://google.github.io/shaka-packager/html/tutorials/widevine.html takes me to 
https://storage.googleapis.com/wvdocs/Widevine_DRM_Encryption_API.pdf

**Comment by Virender-Dangi** [comment]
Can you give the command to run for this. Also where a can pass the Playready server url ?

**Comment by kqyang** [comment]
You can checkout examples here: https://google.github.io/shaka-packager/html/tutorials/raw_key.html. The auto-generated PlayReady PSSH does not contain PlayReady server URL. You can provide your own PSSH in --pssh if you need PlayReady server url in the PSSH.

**Comment by Virender-Dangi** [comment]
Thanks @kqyang . I will try this.
