### ISSUE TITLE
Initial gclient sync on windows error 

### ISSUE THREAD

**Issue by ab5y** [google/shaka-packager#724]
## System info
**Operating System**: WIndows 10 Home
**Shaka Packager Version**: commit 055c67888b5e75b2c0bc88ac58da24e1aec86667

## Issue and steps to reproduce the problem
Followed the steps for building from release on Windows. Got the dependencies installed, ran the gclient config command and then ran the gclient sync command for the first time.

**Packager Command**: gclient sync

Extra steps to reproduce the problem?
None

What is the expected result?
Successful installation of dependencies

What happens instead?
![image](https://user-images.githubusercontent.com/4251453/76112147-a9524480-6007-11ea-8997-c64d7d818ed2.png)

<Please attach the input files or email to shaka-packager-issues@google.com.>
<Please provide any additional information below.>

**Comment by kqyang** [comment]
Do you have `python` installed? What happens if you try to run `python` in the command line?

**Comment by ab5y** [comment]
I have both python2 (2.7.17) and python3 (3.8.0) installed. The `python` command runs python2.

**Comment by ab5y** [comment]
Found [this explanation of the error on S/O ](https://stackoverflow.com/questions/9531683/problems-using-subprocess-call-in-python-2-7-2-on-windows). 
I added the `shell=True` argument to lines 36 and 45 of the `generate_version_string.py` file. It now works, but the version string it generates says "unknown-version". Would this cause an issue?

_Code modification_:
![image](https://user-images.githubusercontent.com/4251453/76162206-4eccfb80-6161-11ea-8010-c51113e913ea.png)

**Comment by kqyang** [comment]
@ab5y What happens if you run `git rev-parse --short HEAD` in command line?

**Comment by ab5y** [comment]
The `git rev-parse --short HEAD` gave the following output:
`055c67888b`
I checked with the main repo and saw that my copy is behind. So I pulled the latest version. This time, with the above changes to the `generate_version_string.py` file, a version string does get printed. But without the changes, the `sync` command still throws the same error. Should I create a pull request?

**Comment by kqyang** [comment]
@ab5y Yes, please.

**Comment by ab5y** [comment]
Could you tell me on which branch to make the request on?
