### ISSUE TITLE
Support splitting WebVTT text file at cue points

### ISSUE THREAD

**Issue by jigneshdhruv** [google/shaka-packager#725]
Shaka Packager does not support splitting WebVTT text file right now at cue points. 

We are trying to use dash ondemanad profile with shaka packager - multi-period. Shaka Packager created a multi-period dash manifest, however adapatationset for caption is only in period 1 and not subsequent periods. What we noticed on Roku is that while playing period 1, caption works, we are able to switch caption track in different languages but once it reaches the second period, it stops working. 

So the question is why does shaka packager not parse and add adaptation set for caption in each period for multi-period dash ondemand profile?

Let me know if you have questions.

Thanks.

**Comment by kqyang** [comment]
@jigneshdhruv I assume this is no longer needed. Can we close the issue?
