### ISSUE TITLE
Shaka-packager live packaging fails

### ISSUE THREAD

**Issue by sridhard** [google/shaka-packager#738]
## System info
**Operating System**: <e.g. macOS Sierra, Ubuntu 14.04 trusty etc>
Ubuntu 16

**Shaka Packager Version**: <e.g. v1.6.1, commit SHA etc>
packager version v2.4.1-c731217-release

## Issue and steps to reproduce the problem

**Packager Command**:packager   'in=udp://127.0.0.1:40001,stream=audio,init_segment=audio_init.mp4,segment_template=audio_$Number$.m4s'   'in=udp://127.0.0.1:40002,stream=video,init_segment=480p_init.mp4,segment_template=480p_$Number$.m4s'   'in=udp://127.0.0.1:40003,stream=video,init_segment=360p_init.mp4,segment_template=360p_$Number$.m4s'   --segment_duration 4 --fragment_duration 4 --time_shift_buffer_depth 7200 --preserved_segments_outside_live_window 0 --suggested_presentation_delay 5 --minimum_update_period 8 --mpd_output livedash6.mpd

Extra steps to reproduce the problem?
We are doing live packaging to DASH. Input to shaka packager is from FFMPEG. After 2-3 minutes shaka-packager fails with the below error
**0325/033843:ERROR:box_reader.cc(143)] Box '?' size (3925868548) is too large.**

After this error shaka-packager stops and doesnot produce any DASH Segments.

What is the expected result?
1. Recover from failure: Shaka packager should not stop processing the input and produce DASH segments even if the input has some issues particularly in live packaging. Can shaka-packager ignore the packet which has issue and continue producing the DASH segments.
2. Also we need to check why the above error happens and solve the issue.

What happens instead?
Shaka packager stops and dont produce any output segments

<Please attach the input files or email to shaka-packager-issues@google.com.>
<Please provide any additional information below.>

**Comment by kqyang** [comment]
> Recover from failure: Shaka packager should not stop processing the input and produce DASH segments even if the input has some issues particularly in live packaging. Can shaka-packager ignore the packet which has issue and continue producing the DASH segments.

We try to recover from recoverable errors, but the problem you are seeing is not recoverable.

> Also we need to check why the above error happens and solve the issue.

Can you re-produce the problem? Can you share the re-pro instructions?
