### ISSUE TITLE
v2.4.1 chunking behavior has changed from v1.6.2

### ISSUE THREAD

**Issue by donghaima** [google/shaka-packager#741]
## System info
**Operating System**: <e.g. macOS Sierra, Ubuntu 14.04 trusty etc>
macOS Catalina, Debian 4.9.189
 
**Shaka Packager Version**: <e.g. v1.6.1, commit SHA etc>
v2.4.1

## Issue and steps to reproduce the problem
We have been using the v1.6.2 Shaka Packager to transmux a TS segment to a fMP4 fragment, like this:
```
./packager-osx-v1.6.2 -segment_duration 100.0 -fragment_duration 100.0 'input=cheddar-cbn-5611783243405.ts,stream=audio,output=/dev/null,segment_template=v1.6.2/frag-$Time$.isma,output_format=MP4,bandwidth=128000'
```
The TS segment is ~4 seconds. The packager generates one output fragment file for one input TS.

While testing the new v2.4.1 release, I notice for _some_ TS segment files, the v2.4.1 Packager is generating more than one fragment for a given input TS. The command line parameters for v2.4.1 packager are the same as the ones for v1.6.2 packager, like this:

I am attaching one of the input TS files, `cheddar-cbn-5611783243405.ts`, that has this symptom. Note that only a handful of the input TS files have this chunking issue. 

Same issue when the input .ts file has a/v muxed. 
 
My questions are:
1. Why the v2.4.1 packager is chunking the segment differently than the v1.6.2 version? Does the attached .ts file have anything special?

2. Are there parameters that I can set for the v2.4.1 packager such that I can have one fMp4 fragment generated from one TS segment? 
 
**Packager Command**:
```
./packager-osx-v2.4.1 -segment_duration 100.0 -fragment_duration 100.0 'input=cheddar-cbn-5611783243405.ts,stream=audio,output=/dev/null,segment_template=v2.4.1/frag-$Time$.isma,output_format=MP4,bandwidth=128000'
``` 

Extra steps to reproduce the problem?
(1) Download the attached TS file: cheddar-cbn-5611783243405.ts
(2) Run the v2.4.1 packager with the above command line options. 
(3) Look at the output fragment files: frag-$Time$.isma 
(4) Run v1.6.2 packager and note the different behavior

What is the expected result?
One .isma file is generated for one input .ts file

What happens instead?
For the attached .ts file, two .isma files are generated by the v2.4.1 Shaka Packager.

<Please attach the input files or email to shaka-packager-issues@google.com.>

<Please provide any additional information below.>
Rename the attached file to 'cheddar-cbn-5611783243405.ts' when downloading it from github. 

![cheddar-cbn-5611783243405 ts](https://user-images.githubusercontent.com/730081/77681773-3d129300-6f6c-11ea-9945-e9d7e9e72547.png)

**Comment by kqyang** [comment]
@donghaima In v1.6.2, when generating segments/chunks, we make sure the duration of the generated segments are always more than the specified segment duration. There is a problem with this approach for live streams as it leads to mis-aligned segments in different resolutions. 

In v2.4, we use consistent chunking algorithm to address the problem: we always create segments/chunks at the first key frame after (timestamp % duration) changes.

To fix your problem, I think we can allow negative segment duration, which when specified, disable chunking. Let me know if that works for you.

Let me know too if you are interested in working on it!

**Comment by donghaima** [comment]
Thanks @kqyang for your quick reply! 

Yes I am interested in working on a fix but I will need to get my dev environment up and running first. I have had troubles with my macOS dev environment setup. The Docker build also is not working for me at the moment. 

Another issue I observed is that the v2.4.1 packager may chunk audio and video segments differently given a muxed TS input file.  I am attaching one example TS file for you to repro (rename the file to `24.ts` after downloading).
![24 ts](https://user-images.githubusercontent.com/730081/77763681-d0ea6a80-7011-11ea-8452-78a9173d0cca.png)

One video segment (`frag-8780646.ismv`) is generated when I run the following command:
```
./packager-osx-v2.4.1 -segment_duration 100.0 -fragment_duration 100.0 'input=24.ts,stream=video,output=/dev/null,segment_template=v2.4.1/frag-$Time$.ismv,output_format=MP4,bandwidth=2400000'
``` 

When I change to segment audio stream with the following command, however, two audio segments are 
generated: `frag-8777286.isma` and `frag-9001926.isma`:
```
./packager-osx-v2.4.1 -segment_duration 100.0 -fragment_duration 100.0 'input=24.ts,stream=audio,output=/dev/null,segment_template=v2.4.1/frag-$Time$.isma,output_format=MP4,bandwidth=128000'
```

**Comment by kqyang** [comment]
@donghaima 

> Yes I am interested in working on a fix but I will need to get my dev environment up and running first

Great. Let us know what problems you are seeing. We can help you address that.

> Another issue I observed is that the v2.4.1 packager may chunk audio and video segments differently given a muxed TS input file

What is the difference you are observing? Note that you want to have perfectly aligned audio and video segments, you need to have a matching audio sampling rate and video GoP. See the comments https://github.com/google/shaka-packager/issues/330#issuecomment-367891229 and https://github.com/google/shaka-packager/issues/330#issuecomment-368222430 on the explanations.
