### ISSUE TITLE
Feature Request: Include (legacy) <mspr:pro> element in DASH's <ContentProtection> for PlayReady

### ISSUE THREAD

**Issue by tim-lansen** [google/shaka-packager#743]
## System info
**Operating System**: Any
**Shaka Packager Version**: Any

## Issue
No option to use `<mspr:pro>` element in DASH's `<ContentProtection>`.
It is important because many older SmartTVs fail to work properly with `<cenc:pssh>` when PlayReady DRM is used.

## Proposition
I propose to add `-mspro <base64 encoded PRO>` option that should cause
```
<ContentProtection schemeIdUri="urn:uuid:9a04f079-9840-4286-ab92-e65be0885f95"
  <mspr:pro>.....</mspr:pro>
</ContentProtection>
```
to appeared in MPD.

#### Example Packager Command
```
packager --mpd_output manifest.mpd \
 --enable_raw_key_encryption \
 --keys key_id=11111111111111111111111111111111:key=22222222222222222222222222222222 \
 input=src/packager/media/test/data/sintel-1024x436.mp4,strea m_selector=video,init_segment=init_v.mp4,segment_template='v_$Number$.m4s' \
 --clear_lead 0 --mspro 'MDEyMw==' --segment_duration 4
```

#### Expected result
```
<?xml version="1.0" encoding="UTF-8"?>
<!--Generated with https://github.com/google/shaka-packager version 069dbc82f7-release-->
<MPD xmlns="urn:mpeg:dash:schema:mpd:2011" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:mpeg:dash:schema:mpd:2011 DASH-MPD.xsd" xmlns:cenc="urn:mpeg:cenc:2013" xmlns:mspr="urn:microsoft:playready" profiles="urn:mpeg:dash:profile:isoff-live:2011" minBufferTime="PT2S" type="dynamic" publishTime="2020-04-03T14:20:37Z" availabilityStartTime="2020-04-03T14:20:36Z" minimumUpdatePeriod="PT5S" timeShiftBufferDepth="PT1800S">
  <Period id="0" start="PT0S">
    <AdaptationSet id="0" contentType="video" width="1024" height="436" frameRate="12288/512" segmentAlignment="true" par="40:17">
      <ContentProtection value="cenc" schemeIdUri="urn:mpeg:dash:mp4protection:2011" cenc:default_KID="11111111-1111-1111-1111-111111111111"/>
      <ContentProtection schemeIdUri="urn:uuid:9a04f079-9840-4286-ab92-e65be0885f95">
        <mspr:pro>MDEyMw==</mspr:pro>
      </ContentProtection>
      <Representation id="0" bandwidth="227753" codecs="avc1.64001f" mimeType="video/mp4" sar="1:1">
        <SegmentTemplate timescale="12288" initialization="init_v.mp4" media="v_$Number$.m4s" startNumber="1">
          <SegmentTimeline>
            <S t="0" d="58880"/>
            <S t="58880" d="14848"/>
          </SegmentTimeline>
        </SegmentTemplate>
      </Representation>
    </AdaptationSet>
  </Period>
</MPD>
```

Weak ref to
https://github.com/google/shaka-packager/issues/678

**Comment by kqyang** [comment]
@tim-lansen Thanks for bringing this up. 

I think we can include both cenc:pssh and mspr:pro in the result MPD by default. It is recommended by PlayReady specification too: https://docs.microsoft.com/en-us/playready/specifications/mpeg-dash-playready#212-including-a-playready-object-in-the-mpd.

Here is the code that needs to be updated: https://github.com/google/shaka-packager/blob/55349aa4c88b43b6bd6fd996efd15f8d9bfdfdb1/packager/mpd/base/mpd_utils.cc#L419. For PlayReady, we should add an extra element for mspr:pro. The data can be derived from cenc:pssh (basically pssh without header).

@tim-lansen Are you interested in helping us implement it?

**Comment by tim-lansen** [comment]
@kqyang yes, i just working on it. I tried to add '--mspr <base64 PRO>' option, but it's getting lost in that part of code
```
shaka-packager/packager/mpd/base/mpd_utils.cc:

      if(!entry.mspr().empty()) {
          drm_content_protection.subelements.push_back(
              GenerateMsprProElement(entry.mspr()));
      }
```
The `entry.mspr` here is always empty, but `raw_key.mspr` is not
```
shaka-packager/packager/mpd/base/raw_key_source.cc:103
```
What should i do to pass mspr's PRO from proto/raw_key?

another approach is to extract PRO from given PSSH, but i don't think it is a good idea.

**Comment by tim-lansen** [comment]
@kqyang sorry i've missed last line
```
. For PlayReady, we should add an extra element for mspr:pro. The data can be derived from cenc:pssh (basically pssh without header).
```
It's not that hard, but is it correct approach?
Should i parse multiple PSSHs to extract multiple PROs?
Should i implement `mspr:pro` suppress option?

Here is my current  diff patch
[patch.txt](https://github.com/google/shaka-packager/files/4450133/patch.txt)
I also looked at `ProtectionSystemSpecificInfo` and i cannot find where it's `psshs` being used as source...
If i init `psshs` in `RawKeySource::Create`, it's content appears in `entry.pssh` taken from `media_info.protected_content()` in `shaka-packager/packager/mpd/base/mpd_utils.cc:419`

**Comment by tim-lansen** [comment]
Okay i've emitted this dirty piece
```
Element GenerateMsprProElement(const std::string& pssh)
{
    std::unique_ptr<media::PsshBoxBuilder> b =
        media::PsshBoxBuilder::ParseFromBox((const uint8_t*)pssh.data(), pssh.size());

    const std::vector<uint8_t> *p_pssh = &b->pssh_data();
    std::string base64_encoded_mspr;
    base::Base64Encode(base::StringPiece((const char*)p_pssh->data(), p_pssh->size()),
        &base64_encoded_mspr);

    Element mspr_pro;
    mspr_pro.name = kMsproElementName;
    mspr_pro.content = base64_encoded_mspr;
    return mspr_pro;
}
```

it seems to be working, so i'll push it to my fork

**Comment by tim-lansen** [comment]
I should add `system_id` check, of course $)

**Comment by kqyang** [comment]
> It's not that hard, but is it correct approach?

Yes, I think so. My understanding of PlayReady specification is 

(1) It is recommended to include both `<cenc:pssh>` and `<mspr:pro>` for backward compatibility.
(2)  `<cenc:pssh>` and `<mspr:pro>` should contain identical information. 

So we should not expect users to provide information for both explicitly. It also allows us to generate both entries internally without users providing either PlayReady pssh or PlayReady pro.

> Should i parse multiple PSSHs to extract multiple PROs?

Seems like you have figured out already. https://github.com/google/shaka-packager/blob/55349aa4c88b43b6bd6fd996efd15f8d9bfdfdb1/packager/mpd/base/mpd_utils.cc#L419 entry.pssh() contains single PSSH, and you can extract pssh data using `media::PsshBoxBuilder::ParseFromBox`.

> Should i implement mspr:pro suppress option?

I don't think we'll need it but I could be wrong. We can implement it later if anyone requests the option to not generate mspr:pro.

> it seems to be working, so i'll push it to my fork

Great. Looking forward to your pull request.

**Comment by tim-lansen** [comment]
@kqyang i've made [pull request](https://github.com/google/shaka-packager/pull/749), but i don't see how to link issue.
And it tells that CLA is not signed, but it is %)

**Comment by kqyang** [comment]
@tim-lansen Cool. Thanks. I'll take care of the linking later when merging the change.

> And it tells that CLA is not signed, but it is %)

I am not able to find your name in our CLA database too. Can you make sure your Git committer email is included in CLA?

**Comment by tim-lansen** [comment]
CLA is ok, CI pending )
