### ISSUE TITLE
Segmentation fault on large files

### ISSUE THREAD

**Issue by TomHetmer** [google/shaka-packager#748]
## System info
**Operating System**: Debian 10
**Shaka Packager Version**: packager version v2.4.1-c731217-release

## Issue and steps to reproduce the problem

**Packager Command**:
`/opt/shaka/packager in=/pecko/incoming/3444/0,stream=0,init_segment=cmaf/cze/maininit.cmfa,segment_template=cmaf/cze/main_\$Number%09d\$.cmfa,playlist_name=cmaf/cze/main.m3u8,language=cze,hls_group_id=program_audio_0,hls_name=Čeština,drm_label=CDN77 in=/pecko/incoming/3444/0,stream=1,init_segment=cmaf/1080p/maininit.cmfv,segment_template=cmaf/1080p/main_\$Number%09d\$.cmfv,playlist_name=cmaf/1080p/main.m3u8,drm_label=CDN77 in=/pecko/incoming/3444/0,stream=2,init_segment=cmaf/720p/maininit.cmfv,segment_template=cmaf/720p/main_\$Number%09d\$.cmfv,playlist_name=cmaf/720p/main.m3u8,drm_label=CDN77 in=/pecko/incoming/3444/0,stream=3,init_segment=cmaf/576p/maininit.cmfv,segment_template=cmaf/576p/main_\$Number%09d\$.cmfv,playlist_name=cmaf/576p/main.m3u8,drm_label=CDN77 --default_language cze --hls_master_playlist_output index.m3u8 --mpd_output index.mpd --generate_static_live_mpd --segment_duration 4 --fragment_duration 0 --enable_raw_key_encryption --protection_systems PlayReady,Widevine --keys label=CDN77:key_id=B120724B6111FBA5CDA3D63347E3DE9C:key=3089C113A5B873C50D674FB92884610E --clear_lead 10`

What is the expected result?
No errors.

What happens instead?
```
[0404/170606:INFO:demuxer.cc(88)] Demuxer::Run() on file '/pecko/incoming/3444/0'.
[0404/170606:INFO:demuxer.cc(160)] Initialize Demuxer for file '/pecko/incoming/3444/0'.
tcmalloc: large alloc 1275068416 bytes == 0x186ab2d5000 @ 
Segmentation fault
```

Links to input file emailed to the Google address.  

The file is a MPEG-TS DVR output from Flussonic streaming server.
We convert it to mp4 with
` ffmpeg -i input.ts -map 0 -c:v copy -c:a copy output.mp4`

**Comment by kqyang** [comment]
@TomHetmer 

> Links to input file emailed to the Google address.

Which email did you send it to? We did not receive it in shaka-packager-issues@google.com

Can you run packager again with more verbose logging, e.g. by setting --v=4?

**Comment by TomHetmer** [comment]
I sent it there, yes. I'll post it here http://1737293223.rsc.cdn77.org/large.ts

>Can you run packager again with more verbose logging, e.g. by setting --v=4?
ok, will try.

**Comment by TomHetmer** [comment]
It appears the issue is related to corrupted input files, we're checking why that's happening

**Comment by TomHetmer** [comment]
It’s definitely caused by broken files. I guess it’s hard to tell if it’s valid or not so shaka doesn’t give any clue about that.

In our case conversion of large files with ffmpeg ts->mp4 and unreliable downloads both produced corrupted files that ended on segmentation faults.
