### ISSUE TITLE
Would it be great to put different kids in the same pssh?

### ISSUE THREAD

**Issue by Sean-X** [google/shaka-packager#75]
The reason I want to ask it I just found when enabled --generate_dash_if_iop_compliant_mpd, the videos with different bitrate are put int different adaptation set. Which will casue that player couldn't do bitrate switch because they are in different adaptation set. 
So I am wondering if it could the different kids in the same pssh then one adaptation could share one pssh data. Player could switch bitrate correctly respectively.

**Comment by kqyang** [comment]
It actually has nothing to do with whether they can use the same pssh or not.

DASH-IF-IOP v3.0 requires representations encrypted with different keys to be in different AdaptationSets. We have an internal logic to determine whether the video is sd or hd (can be adjusted with flag --max_sd_pixels, see help for details). sd video and hd video are encrypted with different keys. When --generate_dash_if_iop_compliant_mpd is set to true, they are put in different AdaptationSets but the same @group to allow adapt / bitrate switch between the two AdaptationSets. You need to update your player to support adapting between AdaptationSets within the same @group if it is not supported yet. 

That is the major difference with --generate_dash_if_iop_compliant_mpd enabled. You may stick with --generate_dash_if_iop_compliant_mpd being disabled if you don't care about being strictly dash-if-iop compliant.

Feel free to reopen the bug if you have more questions.

**Comment by Sean-X** [comment]
Thanks, I got your point.

**Comment by Sean-X** [comment]
Sorry, I just have more questions. 
From iop v3.2, 3.8 switching across adaptation sets. A content author may signal such seamless switching property across adaptation sets by providing a supplemental descriptor along with an adaptation Set wth **@schemeIdURI** ..... and **@value** is a comma-separated list ..... 
The case is  with --generate_dash_if_iop_compliant_mpd enabled, even xoplayer couldn't do switching between HD and SD which however is very important feature in real case.   This option --generate_dash_if_iop_compliant_mpd is also necessary to make a generic dash solution. So it is a lot effort to make player(like xoplayer) to support switching sd and hd dash contents which are created by edash-packager.

**Comment by kqyang** [comment]
Thanks for bringing this up. We are considering supporting the new scheme introduced in v3.2. I assume you are talking about exoplayer. Does exoplayer supports this scheme already?

**Comment by kqyang** [comment]
The cross adaptation set switching scheme from DASH IF IOP 3.2 should already be supported in both shaka packager and exoplayer. Closing this bug.
