### ISSUE TITLE
Resolution appears to be misidentified when reading avc3 files

### ISSUE THREAD

**Issue by SingingTree** [google/shaka-packager#750]
## System info
**Operating System**: Windows 10
**Shaka Packager Version**: 2.4.2

## Issue and steps to reproduce the problem
1. Download an avc3 file to package such as [bear.zip](https://github.com/google/shaka-packager/files/4472288/bear.zip). I've tested this with [test media from Chromium](https://source.chromium.org/chromium/chromium/src/+/master:media/test/data/bear-1280x720-v_frag-avc3.mp4?originalUrl=https:%2F%2Fcs.chromium.org%2F), which I've also attached here as `bear.zip`, and [BBC's Big Buck Bunny avc3 media](http://rdmedia.bbc.co.uk/). My output below uses the bear video from Chromium that I saved as `bear.mp4`.
2. Package with command below.

**Packager Command**:
`packager-win.exe in=bear.mp4,stream=video,init_segment=avc3-video-init.mp4,segment_template=avc3-video-$Number$.m4s`

What is the expected result?
The packager completes without issue.

What happens instead?
```
[0413/160541:INFO:demuxer.cc(88)] Demuxer::Run() on file 'bear.mp4'.
[0413/160541:INFO:demuxer.cc(160)] Initialize Demuxer for file 'bear.mp4'.
[0413/160541:WARNING:mp4_media_parser.cc(588)] Resolution in VisualSampleEntry (1280,720) does not match with resolution in AVCDecoderConfigurationRecord (909193011,825505072). Use AVCDecoderConfigurationRecord.
[0413/160541:INFO:mp4_muxer.cc(177)] MP4 file 'avc3-video-init.mp4' finalized.
Packaging completed successfull
```

The complaint about resolution seems like an error given the dimensions involved.

**Comment by kqyang** [comment]
@SingingTree Thanks for the bug report! Seems like we are missing a zero-initialization in the AVC Decoder Configuration Record parser: https://github.com/google/shaka-packager/blob/6b4a75b6bacdac6b0b9f598c365c8f84f0a7fd70/packager/media/codecs/avc_decoder_configuration_record.h#L55.

Let us know if you are interested in helping us fix it.

**Comment by kqyang** [comment]
Cherry picked to v2.4.x branch for v2.4.3 release.
