### ISSUE TITLE
Mpeg2 video format support in shaka packager

### ISSUE THREAD

**Issue by vengateshvengi** [google/shaka-packager#752]
As i am working in hls  packaging the live feed(udp),the input video codec is Mpeg2 .so is there any possibilities for packaging Mpeg2 feed.If not possible give me some suggestion without transcoding.

**Comment by kqyang** [comment]
No, Mpeg2 codec is not supported. We do not have plans to support it right now. 

I don't think it is supported by Chrome and Firefox either. So the only option is to transcode it before packaging. You can use FFmpeg to do the transcoding then pipe the data to packager using either Linux pipes or udp.
