### ISSUE TITLE
Dolby DD+JOC support and using MPEG scheme for audio channel configuration

### ISSUE THREAD

**Issue by ShaoWeiguo** [google/shaka-packager#753]
Shaka Packager does not support Dolby DD+JOC, and still Dolby scheme for audio channel configuration descriptor. According to latest DD+ specs ETSI TS 102 366 V1.4.1, should prefer to use MPEG scheme.

I will send the pull request to fix these two issues.

Thanks.

**Comment by kqyang** [comment]
@ShaoWeiguo Great. Thanks for helping out!
