### ISSUE TITLE
Dolby AC-4 codec support

### ISSUE THREAD

**Issue by ShaoWeiguo** [google/shaka-packager#754]
Shaka Packager does not support Dolby AC-4 codec. More and more content providers want to deliver AC-4 streaming service, but they don't have the packager.

I  will send the pull request to add this feature.

Thanks.

**Comment by kqyang** [comment]
@ShaoWeiguo Great. Thanks for helping out! Appreciated.

**Comment by ShaoWeiguo** [comment]
I plan to submit the pull request to resolve this issue. But I have a question about the copyright. There are several new files in the PR, I am not sure about what's the copyright for these files? Google's copyright or our company's copyright?

**Comment by kqyang** [comment]
@ShaoWeiguo Can you use Google's copyright header to be consistent?

**Comment by ShaoWeiguo** [comment]
Grep the existing code base, all files seem to have a "Copyright xxxx Google Inc." statement.
I see. I will use Google's copyright header for new files. 
Thanks.
