### ISSUE TITLE
Support LAURL for PlayReady PSSH generation

### ISSUE THREAD

**Issue by Jason239** [google/shaka-packager#756]
Can I set the multiple PlayReady PSSH for each track(SD, HD, AUDIO, etc.) ?

I know it is possible if I use multiple key set by using option(--enable_raw_key_encryption and label=SD:key_id:...:key=...,label=HD:.....) with '-protection_systems PlayReady', but there is no way to set the PlayReady Server URL in PSSH.
I can not use '-playready_server_url' as well, because if I try to use this option, I have to use enable_playready_encryption, and then I can't use --enable_raw_key_encryption option.

So I mean, I want to set different PlayReady PSSH(version about PRH 4.0.0.0, not 4.2.0.0 or higher.) for each track
or set PlayReady server url in PSSH with '-protection_systems PlayReady' and my own key sets option.

**Comment by kqyang** [comment]
@Jason239 I assume that all the PSSHs share the same server URL, can we solve your problem by adding --playready_server_url support to --enable_raw_key_encryption?

**Comment by Jason239** [comment]
I tried it but this error was occurred.
`ERROR: --program_identifier is required if --enable_playready_encryption.`

So I also added --program_identifier, then the following error occurs.
`ERROR:shaka_main.cc(332)] Only one of --enable_widevine_encryption, --enable_playready_encryption, --enable_raw_key_encryption can be enabled.`

So I can not use --enable_raw_key_encryption, but I want to use multiple different key sets by using --enable_raw_key_encryption.

**Comment by Jason239** [comment]
Ah, for clarity, 

> or set PlayReady server url in PSSH with '-protection_systems PlayReady' and my own key sets option.
I mean this '<LA_URL>' in PSSH.

**Comment by kqyang** [comment]
@Jason239 It is not supported yet. Will it work for you if we add support for it in `--enable_raw_key_encryption`?

**Comment by Jason239** [comment]
Probably it will

**Comment by kqyang** [comment]
@Jason239 Is the license acquisition URL the same for different keys or different?

**Comment by Jason239** [comment]
Yes, LAURL is same for all stream

**Comment by kqyang** [comment]
@Jason239 I am thinking of adding a generic flag `--playready_header_extra_data`, which allows users to include `LA_URL`, `LUI_URL` and even `CUSTOMATTRIBUTES`. 

The implementation can be broken into two phases.

## Phase 1. Support the flag in PlayReadyPsshGenerator

1. Define a command line flag in https://github.com/google/shaka-packager/blob/master/packager/media/base/playready_pssh_generator.cc#L21.

```c++
DEFINE_string(playready_header_extra_data, "", "Extra data to be included in PlayReady Header.");
```

2. Perform basic validation of the the flag, e.g. make sure it starts with "<" and ends with ">" and optionally check that it contains valid PlayReady tags.

3. Include the flag in https://github.com/google/shaka-packager/blob/master/packager/media/base/playready_pssh_generator.cc#L35 and https://github.com/google/shaka-packager/blob/master/packager/media/base/playready_pssh_generator.cc#L43.

## Phase 2. Support the flag in the Packager library

1. Move the flag definition to [raw_key_encryption_flags.cc](https://github.com/google/shaka-packager/blob/master/packager/app/raw_key_encryption_flags.cc)

2. Define the parameter in [RawKeyParams](https://github.com/google/shaka-packager/blob/master/packager/media/public/crypto_params.h#L105) and propagate it to PlayReadyPsshGenerator

@Jason239 What do you think about this proposal? Let us know if you are interested in helping us implement it.

**Comment by Jason239** [comment]
I will be happy to help you later after I finish what I'm working on now.
