### ISSUE TITLE
seg fault on shaka::media::webm::Segmenter::Finalize() with empty segment

### ISSUE THREAD

**Issue by murillo128** [google/shaka-packager#757]
## System info
**Ubuntu 18.04
**master branch

## Issue and steps to reproduce the problem
I have a media server that receives data over webrtc and produces mpeg dash with shaka packager. Sometimes I am getting a segmentation fault on shaka::media::webm::Segmenter::Finalize()

I think it is because the  medias server didn't receive any more data on the video track before finalizing all the segments and the prev_sample in https://github.com/google/shaka-packager/blob/master/packager/media/formats/webm/segmenter.cc#L154 is null.

Checking the prev_sample for null would just solve the issue.

**Comment by kqyang** [comment]
@murillo128 I think this happens only if it is not receiving any samples, i.e. the stream is empty. Can you confirm if that is the case?

**Comment by murillo128** [comment]
I think this is the case, yes. Anyway adding a check would be harmless and not cause a regression

**Comment by kqyang** [comment]
@murillo128 I am wondering if the check should be added in an earlier stage. In any case, you are welcomed to send a pull request to us!

**Comment by murillo128** [comment]
Done.

If it is in the last segment, I could send an EOS frame, but I don't know how could I fix it from my app if I don't receive any media frame during the segment duration.
