### ISSUE TITLE
Wrong video bandwith for hls if audio bandwidth is defined

### ISSUE THREAD

**Issue by gleb-shchavlev** [google/shaka-packager#758]
## System info
**Operating System**: CentOS Linux release 7.6.1810 (Core)
**Shaka Packager Version**: v2.4.2-c60e988-release

## Issue and steps to reproduce the problem

Shaka Packager always add last **audio** bandwidth to all **video** bandwidths if bw option is defined.

```
wget https://storage.googleapis.com/shaka-streamer-assets/test-assets/Sintel.2010.720p.Small.mp4

ffmpeg -i Sintel.2010.720p.Small.mkv -c:v copy -c:a copy Sintel.2010.720p.Small.mp4

mkdir hls

packager \
"in=Sintel.2010.720p.Small.mp4,stream=0,bw=1000000,init_segment=hls/init_1.m4v,segment_template=hls/1_\$Time\$.m4v" \
"in=Sintel.2010.720p.Small.mp4,stream=1,bw=96000,init_segment=hls/init_2.m4v,segment_template=hls/2_\$Time\$.m4v" \
--segment_duration 5 \
--fragment_duration 5 \
--time_shift_buffer_depth 30 \
--preserved_segments_outside_live_window 2 \
--hls_master_playlist_output hls/master.m3u8 \
--hls_playlist_type VOD
```

What is the expected result?

```
#EXTM3U
## Generated with https://github.com/google/shaka-packager version v2.4.1-c731217-release

#EXT-X-MEDIA:TYPE=AUDIO,URI="stream_1.m3u8",GROUP-ID="default-audio-group",LANGUAGE="en",NAME="stream_1",AUTOSELECT=YES,CHANNELS="6"

#EXT-X-STREAM-INF:BANDWIDTH=1000000,AVERAGE-BANDWIDTH=76090,CODECS="avc1.64001f,mp4a.40.2",RESOLUTION=1280x544,FRAME-RATE=24.390,AUDIO="default-audio-group"
stream_0.m3u8
```

What happens instead?

```
#EXTM3U
## Generated with https://github.com/google/shaka-packager version v2.4.1-c731217-release

#EXT-X-MEDIA:TYPE=AUDIO,URI="stream_1.m3u8",GROUP-ID="default-audio-group",LANGUAGE="en",NAME="stream_1",AUTOSELECT=YES,CHANNELS="6"

#EXT-X-STREAM-INF:BANDWIDTH=1096000,AVERAGE-BANDWIDTH=76090,CODECS="avc1.64001f,mp4a.40.2",RESOLUTION=1280x544,FRAME-RATE=24.390,AUDIO="default-audio-group"
stream_0.m3u8
```

**Comment by kqyang** [comment]
@gleb-shchavlev Is anything wrong with this? The bandwidth should be the combined bandwidth of the renditions, i.e. audio+video in this case: https://tools.ietf.org/html/rfc8216#section-4.3.4.2

> the BANDWIDTH value MUST be the largest sum of peak
      segment bit rates that is produced by any playable combination of
      Renditions.

**Comment by gleb-shchavlev** [comment]
http://ffmpeg.org/pipermail/ffmpeg-devel/2018-February/224777.html
> - The definition for BANDWIDTH changed to peak bitrate only in v7 of the HLS spec. Earlier BANDWIDTH was mentioned as overall bitrate. So, there should be an option to turn on or turn off peak bitrate calculation.

**Comment by kqyang** [comment]
@gleb-shchavlev Not sure what you want. Do you want to have an option to support HLS spec v6 or earlier?

Back to the original topic, I think BANDWIDTH is the combined bitrate for both HLS specs before v7 and after v7.

**Comment by gleb-shchavlev** [comment]
Support for all the differences of the 7th version is not needed.
There will be enough options for changing the calculation parameters of banwidth.

https://datatracker.ietf.org/doc/draft-pantos-http-live-streaming/07/?include_text=1
> BANDWIDTH
>   The value is a decimal-integer of bits per second.  It MUST be an
>   upper bound of the overall bitrate of each media segment (calculated
>   to include container overhead) that appears or will appear in the
>   Playlist.

**Comment by kqyang** [comment]
@gleb-shchavlev I am really confused on what your point is. Per your latest comment https://github.com/google/shaka-packager/issues/758#issuecomment-619363206, the bandwidth is the overall bitrate, which is what we are doing now. 

Do take note that a "#EXT-X-STREAM-INF" tag in HLS indicates a combination of renditions, including audio and video and possibly text. So both audio and video are considered in BANDWIDTH calculation.

https://tools.ietf.org/html/rfc8216#section-4.3.4.2

>    The EXT-X-STREAM-INF tag specifies a Variant Stream, which is a set
   of Renditions that can be combined to play the presentation.  The
   attributes of the tag provide information about the Variant Stream.
