### ISSUE TITLE
PTS/DTS  not reliable for segmented video

### ISSUE THREAD

**Issue by francoisbussery** [google/shaka-packager#764]
## System info
**Operating System**: Ubuntu 19
**Shaka Packager Version**: 8e113af215-release

## Issue and steps to reproduce the problem

**Packager Command**:
tested with http://twitch-event-engineering-public.s3.amazonaws.com/sync-footage/Sync-Footage-V1-H264.mp4 as input file

packager \
in=tmp/Sync-Footage-V1-H264.mp4,stream=video,init_segment=video/v_init.mp4,segment_template=video/v_\$Number\$.m4s \
   -generate_static_live_mpd  --segment_duration=6 --mpd_output test_seg.mpd

Extra steps to reproduce the problem?
(1) package the video with packager
(2) retreive from the .m4s chunks a mp4 file
(3) probe both mp4 and show packets (ffprobe -show_packets video.mp4)

What is the expected result?
for last packet, for instance, last pts, dts, pts_time and dts_time should be the same)
for both video
What happens instead?
pts_time is 50% smaller. 

<Please attach the input files or email to shaka-packager-issues@google.com.>
<Please provide any additional information below.>

**Comment by kqyang** [comment]
@astinus-1 Can you try if we can re-produce the problem? Thanks.

**Comment by sr1990** [comment]
I am not able to reproduce this issue. ffprobe on both original mp4 and concatenated m4s files show the same pts, dts, pts_time, dts_time for last packet: 
```
  [PACKET]
pts=7200000
pts_time=120.000000
dts=7199000
dts_time=119.983333
[/PACKET]
```

**Comment by kqyang** [comment]
@sr1990 Thanks for jumping in. @francoisbussery Waiting on your response.

**Comment by francoisbussery** [comment]
Sorry for this bug report. I did try again and I confirm its is working. You can close this issue.
