### ISSUE TITLE
[Question] Simulate Live DASH

### ISSUE THREAD

**Issue by weiyuefei** [google/shaka-packager#768]
Hi @kqyang,

I have a requirement to simulate live broadcast and  I use ffmpeg to read VOD file one by one for streaming, and use packager for segments packaging. I found an issue that when a file finishes streaming, and then switchs to the next file, the timestamp will change, the packager detects that changes. However, packager does not write a new period (For HLS, packager will add the "#X-EXT-DISCONUNITY" to m3u8, so it is ok for HLS playback), but continues to update the segments in the original period, which leads to the stucking issue during playback.  I am wondering whether it is possible to let the packager add new Period when it detects that.  

thanks

**Comment by kqyang** [comment]
@weiyuefei We don't support multi-period DASH during live packaging right now. What is the FFmpeg command you are using? If the content is an exact multiple of segment duration, there shouldn't be a GAP.

**Comment by weiyuefei** [comment]
@kqyang My usage scenario is as follows: 

I have some VOD content, and I want to simulate LIVE service. I use ffmpeg to read files for streaming and use packager for HLS/DASH ouptut. 

Assuming that I have two VOD files, 1.mp4 and 2.mp4, firstly I start a packager process receiving the live streams as follows:

$ packager \
  'in=udp://239.0.0.1:5000?interface=172.29.46.122,stream=audio,init_segment=audio_init.mp4,segment_template=audio_$Number$.m4s,playlist_name=audio.m3u8,hls_group_id=audio,hls_name=ENGLISH' \
  'in=udp://239.0.0.1:5000?interface=172.29.46.122,stream=video,init_segment=h264_360p_init.mp4,segment_template=h264_360p_$Number$.m4s,playlist_name=h264_360p.m3u8' \
   --hls_master_playlist_output h264_master.m3u8 \
  --hls_playlist_type LIVE \
  --mpd_output h264.mpd


then I will create a process starting ffmpeg to read 1.mp4 for streaming, command is as follows:

ffmpeg -re -i 1.mp4 -c copy -f mpegts udp://239.0.0.1:5000

when ffmpeg finishes streaming 1.mp4, the process exited, and I will re-create a new process starting ffmpeg to read 2.mp4 for streaming, and push to the same address, command is as follows:

ffmpeg -re -i 2.mp4 -c copy -f mpegts udp://239.0.0.1:5000

At this time, the timestamp of stream that was simulated by files will change, but the packager doesn't aware that the stream in the head-end had already been interrupted and it just detects that the timestamp has been changed. In this case, for the HLS output, packager will add "X-EXT-DISCONUNITY" to m3u8 playlist, which helps the iOS devices play smoothly at the break point. However, packager will continues to update the mpd using the changed timestamp (jump backward) which will cause the DASH player stucked when playing reaches the break point.

**Comment by weiyuefei** [comment]
My question is that whether there is a way to achive the same goal as that in HLS (add "X-EXT-DISCONUNITY" to m3u8 playlist) for DASH output when meeting this situation above? Thanks

**Comment by kqyang** [comment]
As mentioned in https://github.com/google/shaka-packager/issues/768#issuecomment-629710357, multi-period DASH during live packaging is not supported right now. 

Do you know the duration of 1.mp4, 2.mp4 etc? If so, you may try workaround it by using `output_ts_offset` in FFmpeg.

**Comment by weiyuefei** [comment]
> As mentioned in [#768 (comment)](https://github.com/google/shaka-packager/issues/768#issuecomment-629710357), multi-period DASH during live packaging is not supported right now.
> 
> Do you know the duration of 1.mp4, 2.mp4 etc? If so, you may try workaround it by using `output_ts_offset` in FFmpeg.

yes, I can get the file duration, and thanks for your advice, I will try  `output_ts_offset ` in FFmpeg.

BTW, is there any plan to support this feature in the near future?

@kqyang  Thanks again for your answer, I will close this issue.

**Comment by kqyang** [comment]
@weiyuefei No, we don't have plans currently.
