### ISSUE TITLE
CLion IDE instructions

### ISSUE THREAD

**Issue by avrecko** [google/shaka-packager#772]
I'd appreciate if you write how to set up Shaka with CLion IDE in your documentation.

I have no experience with C/C++ build tools. Just a little familiarity with (c)make. I am not a C/C++ developer.

I don't know how to make the CMakeList.txt that CLion wants. It defeats the purpose of having an IDE if code navigation doesn't work.

Your build instructions are very nicely done. I'd really like to see IDE instructions as well. For CMake based projects it is not a problem. But for this I am just scratching my head.

**Comment by kqyang** [comment]
> I'd really like to see IDE instructions as well

That is a good idea, but there are just too many different IDEs people use :). 

I personally don't have experience with CLion. 

As for generating CMakeList.txt, you can try with this command:

```shell
$ GYP_GENERATORS=cmake gclient runhooks
```

It will generate CMakeList.txt in `out/Debug` and `out/Release` directories. Let us know if it works. You are also welcomed to add an IDE instructions page in our documentation: https://github.com/google/shaka-packager/tree/master/docs/source!

**Comment by avrecko** [comment]
The command did generate the CMakeList.txt. But there are some problems:

> 
> CMake Error at CMakeLists.txt:7 (enable_language):
>   No CMAKE_ASM_COMPILER could be found.
> 
>   Tell CMake where to find the compiler by setting either the environment
>   variable "ASM" or the CMake cache entry CMAKE_ASM_COMPILER to the full path
>   to the compiler, or to the compiler name if it is in the PATH.

When I commented out the 

> enable_language(ASM)

I got

> 
> CMake Error at CMakeLists.txt:3811 (add_executable):
>   Cannot find source file:
> 
>     ../../packager/third_party/curl/source/src/tool_mfiles.c
> 
>   Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
>   .hpp .hxx .in .txx

I looked at the source and indeed tool_mfiles.c is missing. There are a bunch of other tool_something.c files but mfiles is not one of them.

**Comment by avrecko** [comment]
What I ended up doing is commenting out curl, protobuf, test lib and putting absolute paths in. Some lines in CMakeLists are referring to macos dir. This is not going to work on linux.

Can you make CMakeLists use absolute paths and don't include macos stuff on linux?

**Comment by kqyang** [comment]
I don't know. It is generated by tool under `packager/tools/gyp/pylib/gyp/generator/cmake.py`. It seems like it is out-dated.

**Comment by avrecko** [comment]
With some manual editing of CMakeLists.txt I am able to import into CLion. Code navigation works. I am building via command line. It is fine for some quick edits.

In terms of shaka I guess this is as good as it gets.
