### ISSUE TITLE
fMP4 - Audio & Video Segment Length Consistency

### ISSUE THREAD

**Issue by dclarkprod** [google/shaka-packager#777]
## System info
**Operating System**: macOS Mojave, GCP COS
**Shaka Packager Version**: v2.4.1-c731217-release

## Issue and steps to reproduce the problem
Hello, we are working to generate a HLS ABR stack packaged with fMP4 segments and have come across issues with varying segment lengths between our audio and video variants. At this point, playback seems to be in sync for these sources; however, downstream processes require our EXTINF values to be in sync across variants in order to ensure proper operation.

Looking through other issues, I did see that there were comments relating to this in other tickets and the proposed solution was to utilize partial second segment lengths. Are there any other ways to force the segment length of audio variants to match their video counterparts?

I've tested this with:

1. Isolated audio and video TS file streams as inputs for packager - each input gets its own variant
2. Muxed audio and video TS file streams that then get split into their own variants.

In each occasion, the lengths of the audio segments appear to be consistent between the tests and do not match the segmentation lengths of the video segments.

**Sample Audio Variant:**

```
#EXTM3U
#EXT-X-VERSION:6
#EXT-X-TARGETDURATION:7
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-MAP:URI="iso-192K-init.mp4"
#EXTINF:4.608,
iso-192K/iso-192K_00001.mp4
#EXTINF:5.995,
iso-192K/iso-192K_00002.mp4
#EXTINF:6.016,
iso-192K/iso-192K_00003.mp4
#EXTINF:5.995,
iso-192K/iso-192K_00004.mp4
#EXTINF:5.995,
iso-192K/iso-192K_00005.mp4
```

**Sample Video Variant:**

```
#EXTM3U
#EXT-X-VERSION:6
#EXT-X-TARGETDURATION:7
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-MAP:URI="iso-5472K-init.mp4"
#EXTINF:6.006,
iso-5472K/iso-5472K_00001.mp4
#EXTINF:6.006,
iso-5472K/iso-5472K_00002.mp4
#EXTINF:6.006,
iso-5472K/iso-5472K_00003.mp4
#EXTINF:6.006,
iso-5472K/iso-5472K_00004.mp4
#EXTINF:6.006,
iso-5472K/iso-5472K_00005.mp4
```

**Packager Command**: 

_Inputs muxed A/V present on incoming TS:_
```
packager \
'in=encodeAV-450K.ts, stream=audio, init_segment=avRouted-64K-init.mp4, segment_template=avRouted-64K/avRouted-64K_$Number%05d$.mp4, playlist_name=avRouted-64K.m3u8, hls_group_id=a1, hls_name=English, language=en' \
'in=encodeAV-2372K.ts, stream=audio, init_segment=avRouted-128K-init.mp4, segment_template=avRouted-128K/avRouted-128K_$Number%05d$.mp4, playlist_name=avRouted-128K.m3u8, hls_group_id=a2, hls_name=English, language=en' \
'in=encodeAV-5472K.ts, stream=audio, init_segment=avRouted-192K-init.mp4, segment_template=avRouted-192K/avRouted-192K_$Number%05d$.mp4, playlist_name=avRouted-192K.m3u8, hls_group_id=a3, hls_name=English, language=en' \
'in=nagy-atbat.vtt, stream=text, segment_template=avRouted-webVTT/webVTT_$Number%05d$.vtt, playlist_name=avRouted-webVTT.m3u8, hls_group_id=sub1, hls_name=English, language=en' \
'in=encodeAV-1672K.ts, stream=video, init_segment=avRouted-1672K-init.mp4, segment_template=avRouted-1672K/avRouted-1672K_$Number%05d$.mp4, playlist_name=avRouted-1672K.m3u8, iframe_playlist_name=avRouted-1672K-I-Frame.m3u8' \
'in=encodeAV-450K.ts, stream=video, init_segment=avRouted-450K-init.mp4, segment_template=avRouted-450K/avRouted-450K_$Number%05d$.mp4, playlist_name=avRouted-450K.m3u8, iframe_playlist_name=avRouted-450K-I-Frame.m3u8' \
'in=encodeAV-736K.ts, stream=video, init_segment=avRouted-736K-init.mp4, segment_template=avRouted-736K/avRouted-736K_$Number%05d$.mp4, playlist_name=avRouted-736K.m3u8, iframe_playlist_name=avRouted-736K-I-Frame.m3u8' \
'in=encodeAV-1072K.ts, stream=video, init_segment=avRouted-1072K-init.mp4, segment_template=avRouted-1072K/avRouted-1072K_$Number%05d$.mp4, playlist_name=avRouted-1072K.m3u8, iframe_playlist_name=avRouted-1072K-I-Frame.m3u8' \
'in=encodeAV-2372K.ts, stream=video, init_segment=avRouted-2372K-init.mp4, segment_template=avRouted-2372K/avRouted-2372K_$Number%05d$.mp4, playlist_name=avRouted-2372K.m3u8, iframe_playlist_name=avRouted-2372K-I-Frame.m3u8' \
'in=encodeAV-3372K.ts, stream=video, init_segment=avRouted-3372K-init.mp4, segment_template=avRouted-3372K/avRouted-3372K_$Number%05d$.mp4, playlist_name=avRouted-3372K.m3u8, iframe_playlist_name=avRouted-3372K-I-Frame.m3u8' \
'in=encodeAV-3872K.ts, stream=video, init_segment=avRouted-3872K-init.mp4, segment_template=avRouted-3872K/avRouted-3872K_$Number%05d$.mp4, playlist_name=avRouted-3872K.m3u8, iframe_playlist_name=avRouted-3872K-I-Frame.m3u8' \
'in=encodeAV-5472K.ts, stream=video, init_segment=avRouted-5472K-init.mp4, segment_template=avRouted-5472K/avRouted-5472K_$Number%05d$.mp4, playlist_name=avRouted-5472K.m3u8, iframe_playlist_name=avRouted-5472K-I-Frame.m3u8' \
--hls_master_playlist_output avRouted.m3u8 --hls_playlist_type VOD --segment_duration 6 --default_language en
```

_Inputs isolated - separate audio/video TS:_
```
packager \
'in=encodeISO-64K.ts, stream=audio, init_segment=iso-64K-init.mp4, segment_template=iso-64K/iso-64K_$Number%05d$.mp4, playlist_name=iso-64K.m3u8, hls_group_id=a1, hls_name=English, language=en' \
'in=encodeISO-128K.ts, stream=audio, init_segment=iso-128K-init.mp4, segment_template=iso-128K/iso-128K_$Number%05d$.mp4, playlist_name=iso-128K.m3u8, hls_group_id=a2, hls_name=English, language=en' \
'in=encodeISO-192K.ts, stream=audio, init_segment=iso-192K-init.mp4, segment_template=iso-192K/iso-192K_$Number%05d$.mp4, playlist_name=iso-192K.m3u8, hls_group_id=a3, hls_name=English, language=en' \
'in=nagy-atbat.vtt, stream=text, segment_template=iso-webVTT/webVTT_$Number%05d$.vtt, playlist_name=iso-webVTT.m3u8, hls_group_id=sub1, hls_name=English, language=en' \
'in=encodeISO-1672K.ts, stream=video, init_segment=iso-1672K-init.mp4, segment_template=iso-1672K/iso-1672K_$Number%05d$.mp4, playlist_name=iso-1672K.m3u8, iframe_playlist_name=iso-1672K-I-Frame.m3u8' \
'in=encodeISO-450K.ts, stream=video, init_segment=iso-450K-init.mp4, segment_template=iso-450K/iso-450K_$Number%05d$.mp4, playlist_name=iso-450K.m3u8, iframe_playlist_name=iso-450K-I-Frame.m3u8' \
'in=encodeISO-736K.ts, stream=video, init_segment=iso-736K-init.mp4, segment_template=iso-736K/iso-736K_$Number%05d$.mp4, playlist_name=iso-736K.m3u8, iframe_playlist_name=iso-736K-I-Frame.m3u8' \
'in=encodeISO-1072K.ts, stream=video, init_segment=iso-1072K-init.mp4, segment_template=iso-1072K/iso-1072K_$Number%05d$.mp4, playlist_name=iso-1072K.m3u8, iframe_playlist_name=iso-1072K-I-Frame.m3u8' \
'in=encodeISO-2372K.ts, stream=video, init_segment=iso-2372K-init.mp4, segment_template=iso-2372K/iso-2372K_$Number%05d$.mp4, playlist_name=iso-2372K.m3u8, iframe_playlist_name=iso-2372K-I-Frame.m3u8' \
'in=encodeISO-3372K.ts, stream=video, init_segment=iso-3372K-init.mp4, segment_template=iso-3372K/iso-3372K_$Number%05d$.mp4, playlist_name=iso-3372K.m3u8, iframe_playlist_name=iso-3372K-I-Frame.m3u8' \
'in=encodeISO-3872K.ts, stream=video, init_segment=iso-3872K-init.mp4, segment_template=iso-3872K/iso-3872K_$Number%05d$.mp4, playlist_name=iso-3872K.m3u8, iframe_playlist_name=iso-3872K-I-Frame.m3u8' \
'in=encodeISO-5472K.ts, stream=video, init_segment=iso-5472K-init.mp4, segment_template=iso-5472K/iso-5472K_$Number%05d$.mp4, playlist_name=iso-5472K.m3u8, iframe_playlist_name=iso-5472K-I-Frame.m3u8' \
--hls_master_playlist_output iso.m3u8 --hls_playlist_type VOD --segment_duration 6 --fragment_duration 2 --default_language en
```

Extra steps to reproduce the problem?
(1) Audio streams are all 48kHz at varying bitrates - split and encoded from the same input file
(2) Video files are a mixture of 29.97 and 59.94 at varying bitrates and resolutions - split and encoded from the same file. GOP is 2 seconds on all (60frames or 120frames). GOP is closed with scenecut disabled.

What is the expected result?
Audio and video streams should maintain the same, predictable segment length as specified by --segment_duration and fragements should align from --fragment_duration

What happens instead?
Audio follows it's own segment length pattern while video segments stay at a consistent length.

Sample files will be emailed to shaka-packager-issues@google.com

<Please attach the input files or email to shaka-packager-issues@google.com.>
<Please provide any additional information below.>

**Comment by dclarkprod** [comment]
In addition, I have tested with the `--allow_approximate_segment_timeline` argument from #330 without any change to the chunking.
Is it required with the current iteration of packager to dynamically set the segment lengths based upon not just video GOP but the audio samples as well?

**Comment by z0mb1ek** [comment]
Hi, I see the same with ffmpeg encoding. I think for fmp4 audio schould not be the same length as video

**Comment by kqyang** [comment]
@dclarkprod The result is expected. This is because:

- For audio frame
  - There are always 1024 audio samples in an audio frame. For a frequency of 48kHz, the audio frame size is: 1024/48000 = 0.21333... seconds
  - 6 / (1024/48000) = 281.25. 
  - We try to create segments aligned with the segment timeline from target segment duration. Since the number of audio frames must be an integer, the number of alternates between 281 frames and 282 frames, with the duration of 281 * 1024/48000 = 5.995, 282 * 1024/48000 = 6.016.
- For video video
  - The frame duration is 1/29.97 seconds
  - So the segment duration is 30 * 6 * 1/29.97 = 6.006 (most of the time).

`--allow_approximate_segment_timeline` is only for DASH. HLS requires a sufficient accurate duration, so we cannot use approximate values.

If you need audio and video to align exactly, you cannot use arbitrary segment duration. It has to satisfy the below equations:
- num_audio_frames = segment_duration / (1024/audio_sampling_rate) is an integer
- num_video_frames = segment_duration / (1/video_frame_rate) is an integer

For a frame rate of 29.97, it is not possible to find a segment duration where audio and video align exactly. Is it possible to use a different frame rate?

**Comment by dclarkprod** [comment]
Understood regarding the math for the frames; however, what are we able to do to at least get a consistent segment length for the audio similarly to our video playbacks?

For this situation, it is not possible to adjust frame rates.

**Comment by kqyang** [comment]
@dclarkprod You can set segment duration to 5.994 or 5.995. There will still be occasional outliers, but should be the same most of the time.

Out of curiosity, what is the reason that your downstream process requires the segment duration to be the same?

**Comment by kqyang** [comment]
@dclarkprod I am closing this issue as your problem has been addressed. Feel free to reply if you have more questions.
