### ISSUE TITLE
Problem On Live Stream packaging

### ISSUE THREAD

**Issue by mhzae** [google/shaka-packager#781]
Operating system : Ubuntu 18.04
Packager version : v1.2.0 (base on : https://google.github.io/shaka-packager/html/build_instructions.html)

I am new using shaka packager, i want to use it to package my local live stream from my streamer with output UDP stream

When i try this command
` # ./packager-linux in=udp://227.10.20.1:1234,stream=audio,output=live/audio_channel1.mp4 in=udp://227.10.20.1:1234,stream=video,output=live/video_channel1.mp4 --mpd_output=live/stream_channel1.mpd`

The notification is
```
[0608/164248:INFO:demuxer.cc(88)] Demuxer::Run() on file 'udp://227.10.20.1:1234'.
[0608/164248:INFO:demuxer.cc(160)] Initialize Demuxer for file 'udp://227.10.20.1:1234'.
[0608/164248:ERROR:udp_file.cc(199)] Could not bind UDP socket, error = 98
[0608/164248:ERROR:packager_main.cc(533)] Packaging Error: 5 (FILE_FAILURE): Cannot open file for reading udp://227.10.20.1:1234
```
The live stream is accessible using VLC on my laptop

Any advice what should i do to solve this ?

Thank you

**Comment by kqyang** [comment]
> Could not bind UDP socket, error = 98

It means it is already in use. Are you using it in another application?

Can you use a different UDP address? You may also try adding "reuse=1" option: https://google.github.io/shaka-packager/html/tutorials/live.html#udp-file-options?

> Packager version : v1.2.0

v1.2.0 is very old. You should use a more recent version instead.

**Comment by mhzae** [comment]
> It means it is already in use. Are you using it in another application?

Yes, there is another application on my server. And need UDP stream too

> v1.2.0 is very old. You should use a more recent version instead.

is this link https://github.com/google/shaka-packager/releases for package latest version right ?

**Comment by kqyang** [comment]
Yes

**Comment by mhzae** [comment]
Thank you for your help, it's helping me
