### ISSUE TITLE
Live Packaging to HLS/Dash, AV Sync Issue in HLS but not DASH

### ISSUE THREAD

**Issue by msauer2000** [google/shaka-packager#783]
## System info
**Operating System**: Ubuntu 18.04
**Shaka Packager Version**: packager version 8913dbd-release

## Issue and steps to reproduce the problem

**Packager Command**:

packager \
  'in=udp://239.0.0.224:5500?reuse=1&interface=192.168.0.101,stream=audio,init_segment=cbc_audio_init.mp4,segment_template=cbc_audio_$Time$.m4s,playlist_name=cbc_audio.m3u8,hls_group_id=cbc_audio,hls_name=ENGLISH' \
  'in=udp://239.0.0.224:5500?reuse=1&interface=192.168.0.101,stream=video,init_segment=cbc_h264_720p_init.mp4,segment_template=h264_720p_$Time$.m4s,playlist_name=cbc_h264_720p.m3u8' \
  'in=udp://239.0.1.224:5500?reuse=1&interface=192.168.0.101,stream=video,init_segment=cbc_h264_540p_init.mp4,segment_template=h264_540p_$Time$.m4s,playlist_name=cbc_h264_540p.m3u8' \
  'in=udp://239.0.2.224:5500?reuse=1&interface=192.168.0.101,stream=video,init_segment=cbc_h264_480p_init.mp4,segment_template=h264_480p_$Time$.m4s,playlist_name=cbc_h264_480p.m3u8' \
  'in=udp://239.0.3.224:5500?reuse=1&interface=192.168.0.101,stream=video,init_segment=cbc_h264_360p_init.mp4,segment_template=h264_360p_$Time$.m4s,playlist_name=cbc_h264_360p.m3u8' \
  'in=udp://239.0.4.224:5500?reuse=1&interface=192.168.0.101,stream=video,init_segment=cbc_h264_270p_init.mp4,segment_template=h264_270p_$Time$.m4s,playlist_name=cbc_h264_270p.m3u8' \
  --hls_master_playlist_output cbc_h264_master.m3u8 \
  --hls_playlist_type LIVE \
  --mpd_output cbc_h264_master.mpd \
  --time_shift_buffer_depth 30 

Extra steps to reproduce the problem?
(1) I am using a live transcoder to output multicast mpeg transport streams to 239.0.[0-4].224:5500 at various resolutions. The video codec is H.264 and the audio codec is AAC.
(2) I put the output files in the web server directory for nginx to serve the streams

What is the expected result?
I expected the video to play with HLS and DASH, and that the audio and video would be in sync in both cases.

What happens instead?
The DASH output is in sync, but the HLS playback is out of sync. The audio video sync issue in HLS seems consistent from the start all the way through, it's like there is a constant offset between the audio and video tracks. 

<Please attach the input files or email to shaka-packager-issues@google.com.>
<Please provide any additional information below.>

**Comment by kqyang** [comment]
@msauer2000 

Three questions:

- Do you have a way for us to re-produce your problems? 
- What player are you using for HLS playback? Have you tried other players?
- Also, is the content encrypted? If so, is the A/V sync happening on clear HLS as well?

**Comment by kqyang** [comment]
Have you tried using Shaka Player?

**Comment by msauer2000** [comment]
I did not know of Shaka Player. I will try it.

**Comment by msauer2000** [comment]
The stream plays great in shaka player. Perhaps the issue I was having before is an issue with that plugin then. Thanks.

**Comment by kqyang** [comment]
Cool. I'll close this bug since the stream works in Shaka Player. You may want to file an issue to the owner of the plugin if you want to pursue.
