### ISSUE TITLE
Problem on VoD Packaging with DRM (Widevine)

### ISSUE THREAD

**Issue by mhzae** [google/shaka-packager#784]
Operating System : Ubuntu 18.04
Packager version : v2.4.2

I want to package VoD with output DASH, and using DRM encryption too (Widevine)

When i try this command

`# ./packager-linux in=animal-planet.mp4,stream=audio,output=animal-widevine/audio.mp4,drm_label=AUDIO in=animal-planet.mp4,stream=video,output=animal-widevine/video.mp4,drm_label=VIDEO --enable_raw_key_encryption --keys label=AUDIO:key_id=bFlxxxxxxxxxxxxxxqQ==:key=pSxxxxxxxxxxxxxPpA==,label=VIDEO:key_id=bxxxxxxxxxxqQ==:key=pSxxxxxxxxxxxxxxPpA== --pssh CAxxxxxxxxxxxxxxxxxxxxJTRA== --mpd_output animal-widevine/stream.mpd`

The notification is
```
Invalid hex string for --pssh: CAExxxxxxxxxxxxxxxxxxxxRA==
ERROR: failed validation of new value 'CAxxxxxxxxxxxxxxxxxxxxxxxxxJTRA==' for flag 'pssh'
```

When i check, there is no typo on value of pssh 
Any advice to solve this ?

Thank you

**Comment by kqyang** [comment]
Your pssh is base64 encoded, while the argument needs to be hex encoded. Can you convert it to hex format instead?

**Comment by mhzae** [comment]
I don't get it what you mean

But, i receive value of content_id, key, key_id, key_idguid, key_idhex, pssh, and full_psshbox from DRM provider that i use

Do you mean i should use value of the key_idhex in the option/parameter key_id on the command ?

**Comment by mhzae** [comment]
Sory, i mean key_hex

**Comment by kqyang** [comment]
@mhzae Hex and base64 are two different encodings to encode binary data. Shaka Packager expects "hex" encoded data in "key_id, key and --pssh". 

If what your content provider gives you is base64 encoded, you can always translate it into hex format using a base64 to hex conversion tool. 

Here is an example command to convert base64 to hex:

```shell
$ echo -n "7WkoOEfwfTTioxG6CatHBw==" | base64 -d | xxd -ps
```

Also, what is in `--pssh` should be full psshbox.

**Comment by mhzae** [comment]
Oh i see

It's work by the way, there is no error again

Then i want to test playback, when i open shaka player demo on this [link](https://shaka-player-demo.appspot.com/demo/
)

The website is blank
![Blank-site](https://user-images.githubusercontent.com/31914112/84114493-a461be80-aa56-11ea-9b48-791acd1cdc02.png)

I already access it on my friend's laptop, it's blank too
Do you have an alternative player to test playback ?

**Comment by mhzae** [comment]
Thank you, it's work by the way, there is no error again when i package the content

After that, I try to test playback using [Shaka-player-demo](https://shaka-player-demo.appspot.com/demo)

This my configuration
[Image-here](https://ibb.co/fX4r0Jb)

When i try to playback, there is an error
[Image-here](https://ibb.co/h2jQTTj)

The http value error is 1002

What should i do ?

**Comment by kqyang** [comment]
Looks like player or website configuration issue. Can you ask the questions in https://github.com/google/shaka-player/issues?
