### ISSUE TITLE
Support for generating dash based encrypted m4s files with muxed audio and video

### ISSUE THREAD

**Issue by suhaskam** [google/shaka-packager#786]
Is there any support for the below requirement ?

Given a video file containing audio and video (or take input from 1 audio stream and 1 video stream)

Generate mpd and m4s files.
The m4s files should have audio and video muxed and also encrypted using using clear key/cenc.
.ie segment-001.m4s should contain audio and video muxed and also be able to encrypt.

Is such content generation possible by shaka packager? Also wonder if players like Shaka player be able to play such content.

Thanks

**Comment by kqyang** [comment]
No. We do not support it in Shaka Packager. It is also against DASH recommendation. Is there any reason that you want muxed content?
