### ISSUE TITLE
Download Encrypted VoD

### ISSUE THREAD

**Issue by mhzae** [google/shaka-packager#787]
Operating System : Ubuntu 18.04
Packager version : v2.4.2

Does shaka packager support encrypted VoD with DRM to be downloadable ?

Thank you

**Comment by mhzae** [comment]
Yes i mean for offline playback, it's like spotify and joox maybe (for the music)

**Comment by kqyang** [comment]
Packager is agnostic. It depends on what the player you use. [Shaka Player](https://github.com/google/shaka-player/) supports offline playback.
