### ISSUE TITLE
PR for IV for raw key encryption

### ISSUE THREAD

**Issue by jforaci** [google/shaka-packager#794]
Hello, I had a need to be able to specify the IV for each key given in the `--keys` option and would like to submit the following PR if you think it's okay: https://github.com/google/shaka-packager/pull/793. I updated the documentation but may need some additional docs, and tests to ensure coverage.

Not supplying the IV will generate its own random one, as before. And the `--iv` param still works if the key isn't supplied in this new way.

There seems to be a few tickets that may be related but the earliest I've found is https://github.com/google/shaka-packager/issues/292. And one, https://github.com/google/shaka-packager/issues/543, seems to be part of the [v2.5 milestone](https://github.com/google/shaka-packager/milestone/14). Let me know if there's anything I can do to help.

Thanks,
joe

**Comment by kqyang** [comment]
Thanks for working on this feature. Appreciated!

I'll merge it into #543 as it is really a duplicate. Also, as in https://github.com/google/shaka-packager/issues/543#issuecomment-455368057, do you need different HLS key uri (#470) at the same time?

**Comment by jforaci** [comment]
Hi @kqyang, yeah, good point. I was considering the HLS key URI and thought it may be supplied the same way, per-key, but I wasn't sure since it's HLS-specific, and only for raw key encryption. I was thinking maybe the `hls_key_uri` could be tokenized per-DRM label like `--keys` is, to keep them separate but I'm not too familiar and didn't know if that's the right approach either. In my case I can just do a simple post-edit, so in the end I figured it would be nice to have in a separate logical PR, if you agree.

**Comment by kqyang** [comment]
Yes, that is totally fine. I agree that it is better to have it in a separate PR. 

If it works, it will be cleaner to support something described in https://github.com/google/shaka-packager/issues/470#issuecomment-455373692. I am fine with having a separate attribute in `key_info_string` too if necessary.

**Comment by jforaci** [comment]
Sounds good. I updated the PR with your suggestions.

> If it works, it will be cleaner to support something described in #470 (comment). I am fine with having a separate attribute in key_info_string too if necessary.
Ah, I hadn't considered that -- the `<key_id>` token sounds like a good idea to me.

**Comment by karlg-arris** [comment]
@kqyang when do you think this one will make it into a release?

**Comment by kqyang** [comment]
@kqyang We will try to release v2.5 by the end of September 2020.
