### ISSUE TITLE
Removing unnecessary libraries and/or file formats

### ISSUE THREAD

**Issue by Reapss** [google/shaka-packager#797]
Hello, I am working on a project requiring I package MPEG2-TS input into DASH fragments, all the while implementing encryption and linking it to a Playready Server. 

This is all possible thanks to Shaka-Packager, however, as the project will run on limited resources, i wanted to know if it were possible to build the packager while excluding some features. And if so, how would one achieve it.

Thanks in advance.

**Comment by kqyang** [comment]
Yes, there are a few easy changes you can make:

(1) Compile MPEG2-TS demuxer only. You can achieve it by removing all the "cases" except for `case CONTAINER_MPEG2TS`: https://github.com/google/shaka-packager/blob/master/packager/media/demuxer/demuxer.cc#L182

(2) Compile MP4 muxer only. You can achieve it by removing all the "cases" except for `case CONTAINER_MOV`: https://github.com/google/shaka-packager/blob/master/packager/app/muxer_factory.cc#L41

(3) Remove HLS support by commenting this line: https://github.com/google/shaka-packager/blob/master/packager/packager.cc#L947

I am closing this issue, but feel free to reply if you are encountering any problems.
