### ISSUE TITLE
Shaka Packager doesn't immediately consume the data on written to a input pipe 

### ISSUE THREAD

**Issue by buriedgod** [google/shaka-packager#800]
## System info
**Operating System**: Ubuntu 16.04
**Shaka Packager Version**: packager version v2.4.2-c60e988-release

## Issue and steps to reproduce the problem
The pipeline has ffmpeg take the input and transcodes it the audio and video to pipes, shaka packager is waiting for input on these pipes , but in my case takes even around 7 seconds to read from the pipe and starts the packaging process and runs further with no issues.

**Packager Command**: 
/bin/packager in=/var/media/pipes/v0,stream=video,init_segment=/var/media/240p/v_init.mp4,segment_template=/var/media/240p/v_$Time$.m4s,playlist_name=/var/media/240p/v.m3u8 in=/var/media/pipes/a0,stream=audio,init_segment=/var/media/240p/a_init.mp4,segment_template=/var/media/240p/a_$Time$.m4a,playlist_name=/var/media/240p/a.m3u8 --hls_master_playlist_output /var/media/index.m3u8 --time_shift_buffer_depth 120 --preserved_segments_outside_live_window 18 --segment_duration 1 --fragment_duration 1 --generate_sidx_in_media_segments --hls_playlist_type LIVE --v=4

Extra steps to reproduce the problem?
(1) Watch the timing of ffmpeg write (by using inotify) to pipe and start of read by packager log (Following is the sample log of packager from my case) : [0717/192619:VERBOSE2:local_file.cc(118)] Read 65536 return 65536 error 0

What is the expected result?
Packager would consume (almost) immediately from the pipe.
What happens instead?
Packager delayed start of consuming from pipe by around 7 seconds.

**Comment by kqyang** [comment]
@buriedgod Can you isolate the problem to video or audio? You can do this by having the video or audio stream only in FFmpeg and packager.

Another thing you can try is to reduce the `io_block_size` even further, e.g. to 1000.

**Comment by buriedgod** [comment]
@kqyang i have reduced the `io_block_size` and the issue seems resolved.

Very sorry about the delayed response.

**Comment by kqyang** [comment]
Cool. That is a limitation of using the pipe as it blocks until the number of bytes are available. 

Glad that reducing `io_block_size` works for you. Another thing you can try is to use UDP sockets.
