### ISSUE TITLE
"Got a block with negative timecode offset" error for a video generated with ffmpeg that plays back fine

### ISSUE THREAD

**Issue by naktinis** [google/shaka-packager#801]
## System info
**Operating System**: Ubuntu 18.04 bionic
**Shaka Packager Version**: v2.4.2

## Issue and steps to reproduce the problem

**Packager Command**:
```
./packager-linux in=test.webm,stream=video,output=test-dash.webm --mpd_output test.mpd
```
Extra steps to reproduce the problem?
N/A

What is the expected result?
test.mpd should be generated.

What happens instead?
```
[0717/153244:INFO:demuxer.cc(88)] Demuxer::Run() on file 'test.webm'.
[0717/153244:INFO:demuxer.cc(160)] Initialize Demuxer for file 'test.webm'.
[0717/153244:ERROR:webm_cluster_parser.cc(324)] Got a block with negative timecode offset -3386
[0717/153244:ERROR:packager_main.cc(533)] Packaging Error: 8 (PARSER_FAILURE): Cannot parse media file test.webm
```

Test video:
https://www.dropbox.com/t/JIhhnKIwB5kywNqa

Normally I'd just accept this as a problem on my side, however:
 - this video was transcoded the same way as hundreds of other videos from a variety of sources that work with shaka packager just fine (same ffmpeg version, same filters)
 - this video was transcoded from an mp4/h264 video with ffmpeg v4.2.2, which is relatively recent
 - this video plays on VLC, Firefox, and Chrome without any issues or decoding errors, so whatever decoders they use, seem to be able to silently work around the issue that shaka packager is encountering

Let me know if I can provide any further information.

**Comment by kqyang** [comment]
@naktinis It is an upstream limitation from Chrome: https://source.chromium.org/chromium/chromium/src/+/master:media/formats/webm/webm_cluster_parser.cc;drc=42859f7ad2f95f7a5bf7e5810e2abfba0008c1b8;l=464.

Also see: https://bugs.chromium.org/p/chromium/issues/detail?id=271794.

It may work with SRC in Chrome but it won't work with [MSE](https://developers.google.com/web/fundamentals/media/mse/basics) in Chrome.

I am closing this issue but feel free to comment if you have other comments.

**Comment by naktinis** [comment]
Would you have any insights of how I could approach working around these negative timestamps? For example, do you think it's something that could be addressed by changing how the video is transcoded from the source or by switching away from shaka-packager to something else? It looks like the content is there, so seems like it's just about changing the representation (but maybe I'm wrong).

Also, another question about the chromium issue you've posted: do you think it would make sense for me to reopen it or do you know of anything technical that would prevent this from being fixed?

**Comment by kqyang** [comment]
> Would you have any insights of how I could approach working around these negative timestamps? 

It is very surprising that FFmpeg generates a negative timecode. I don't know if it is a bug in FFmpeg. If it is just one P-Frame, we may be able to workaround it by just ignoring the frame. If that works, you are welcome to send a PR to us with the workaround.

> another question about the chromium issue you've posted: do you think it would make sense for me to reopen it 

Yes, Chromium is an open source project. Feel free to re-open the bug to ask the developers to look into it again.

**Comment by naktinis** [comment]
Thank you for the advice! By the way, would you know of any way that would let me debug these timestamp values (to see if it's just one P-Frame, for example). The closest I could get was using ffprobe:
```
ffprobe -i test.webm -show_frames
```

which for the first packet produces this:
```
pkt_pts_time=0.000000
pkt_dts_time=0.000000
best_effort_timestamp=-7
best_effort_timestamp_time=-0.007000
pkt_duration_time=0.013000
```

All the other `best_effort_timestamp` values seem positive.

However, I'm unable to obtain the timestamp value reported by shaka packager/chromium parser: `-3386`, so I'm not quite sure this is the same thing.

**Comment by kqyang** [comment]
You may use a [ebml viewer](https://code.google.com/archive/p/ebml-viewer/) or [mkv parser](https://github.com/remko/go-mkvparse) to read the tags.

You may also dump all the timestamps using FFmpeg/FFprobe to see if there is anyone malicious.
