### ISSUE TITLE
Dash video doesnt play first 3-5 second

### ISSUE THREAD

**Issue by tarikkilic** [google/shaka-packager#804]
## System info
**Operating System**: CentOS Linux 7 (Core)
**Shaka Packager Version**: packager-linux version v2.4.2-c60e988-release

## Issue and steps to reproduce the problem

**Packager Command**:

`/root/bin/packager-linux \
in=/home/www/alignment_test/1595265001/fs_1.mp4,stream=audio,output=/home/www/alignment_test/1595265001/shaka/out_audio.mp4 \
in=/home/www/alignment_test/1595265001/fs_1.mp4,stream=video,output=/home/www/alignment_test/1595265001/shaka/out_1.mp4 \
in=/home/www/alignment_test/1595265001/fs_2.mp4,stream=video,output=/home/www/alignment_test/1595265001/shaka/out_2.mp4 \
--mpd_output manifest.mpd --default_language ENGLISH  \
--mpd_output /home/www/alignment_test/1595265001/shaka/stream.mpd`

I get a recording from UDP before packing. Steps:

`timeout -s SIGINT 1m /root/bin/ffmpeg -y -i udp://225.1.1.2:1234?reuse=1 -c:a copy -c:v copy -threads 0 -r 24 -g 48 -keyint_min 48 -sc_threshold 0 -max_muxing_queue_size 9999 /home/www/alignment_test/$now/1.mp4 &> /dev/null &
`
And I fix the mp4 container like that :

`/root/bin/ffmpeg -y -i /home/www/alignment_test/$now/1.mp4 -codec copy -movflags faststart /home/www/alignment_test/$now/fs_1.mp4`

If I dont fix video, beggining of video is distorted.

And finally I fragmented(out_1.mp4) and packaged( stream.mpd) with shaka.

**What is the expected result?**

I expect the video to play properly on the player.

**What happens instead?**

 But The first 3-5 seconds of the video does not play. If i seek  beginning of video, video player crashes. But If I play fragmented out_mp4 with shaka, its okey.  But after packging doesnt work, I can not play first 3-5 seconds. Could it be related to audio?

If I re-encode 1.mp4, shaka packager packaged and play correctly. But Re-encode operation is using cpu more. I don't want to use CPU unnecessary.

**Comment by kqyang** [comment]
@tarikkilic Sorry for the late reply. I am confused. Can you clarify the three sections below:

> But The first 3-5 seconds of the video does not play. 

Do you mean playing stream.mpd in a DASH Player?

> But If I play fragmented out_mp4 with shaka, its okey.

Do you mean playing out_1.mp4 and out_2.mp4 directly in a browser?

> But after packging doesnt work, I can not play first 3-5 seconds. 

Is it the same as the first comment, i.e. playing stream.mpd?
