### ISSUE TITLE
How can I insert widevine PSSH to init.mp4

### ISSUE THREAD

**Issue by jgkim0518** [google/shaka-packager#805]
## System info
**Operating System**: CentOS Linux release 7.5.1804
**Shaka Packager Version**: v2.4.2

## Issue and steps to reproduce the problem

Hello.
I want to insert widevine PSSH to init.mp4. How can I do it?

**Packager Command**:
```
    --enable_widevine_encryption \
    --key_server_url http://123.456.789.0:0000/abc/def/ghi \
    --clear_lead 0 --content_id $(echo -n $OUTPUT_FILENAME | xxd -pu) --content_name $OUTPUT_FILENAME --content_type LIVE --enc_type CENC --file_name $OUTPUT_FILENAME.mpd --crypto_period_duration 180 \
```

**Comment by kqyang** [comment]
@jgkim0518 Can you clarify your question or what problem are you seeing? If you haven't, you can read our tutorials here: https://google.github.io/shaka-packager/html/tutorials/drm.html.

**Comment by jgkim0518** [comment]
> @jgkim0518 Can you clarify your question or what problem are you seeing? If you haven't, you can read our tutorials here: https://google.github.io/shaka-packager/html/tutorials/drm.html.

I have used widevine encryption. It instert PSSH to .mpd and .m4s but don't init.mp4. I want to insert PSSH to init.mp4 too. I can't find a way on shaka packager doc and web searching. How can I insert PSSH to init.mp4?

**Comment by kqyang** [comment]
The PSSH is not inserted in the init.mp4 when key rotation is enabled. This is because the PSSH is different for different segments. Why do you need PSSH in init.mp4 in this case?

**Comment by jgkim0518** [comment]
I don't know...I am editing source code. thank you.
