### ISSUE TITLE
Changing availabilityStartTime of the DASH live

### ISSUE THREAD

**Issue by psytechno604** [google/shaka-packager#806]
## System info
**Operating System**: tried Windows 10, Mac Os, Ubuntu
**Shaka Packager Version**: v2.4.2

## Issue and steps to reproduce the problem

I need to set up a **DASH live stream from file played in a loop. The resulting manifest must have   availabilityStartTime="1970-01-01T00:00:00Z"**. Exactly like this - https://live.unified-streaming.com/scte35/scte35.isml/.mpd.

I tried this solution: https://github.com/google/shaka-packager/issues/509#issuecomment-443853403, hoping that I will be able to change availabilityStartTime somehow in the end. But all my attempts failed.

I know that --availability_start_time_offset was deprecated many years ago, and --suggested_presentation_delay is supposed to be used instead. But it seems that it has no effect on availabilityStartTime value in the output.

I also tried to use cvlc's --sout-ts-dts-delay on the stage where I create udp stream from file, but I cannot move it to the past more that by ~1 day (it is in milliseconds and most likely does not support big numbers). So, to be more clear - changing dts (and pts?) of the source stream is somehow working, but the needed value cannot be achieved, the maximum effect you get there is to have availabilityStartTime pointing to yesterday or like that.

Is there a way to change availabilityStartTime of DASH?

**Comment by kqyang** [comment]
@psytechno604 

`availablityStartTime` is computed from media timestamp. For MPEG2-TS, timestamp is 33 bit, so it is limited to (1<<33) / 90000 seconds. We do not support extracting the time signal embedded in SCTE35 yet.

What is the reason that you want to fix `availablityStartTime` to `1970-01-01T00:00:00Z`?

**Comment by psytechno604** [comment]
The reason is third-party server-side ad insertion software that we are using.. It requires availabilityStartTime="1970-01-01T00:00:00Z", otherwise simply does not work. I cannot do anything with it, because it is out of my scope (this is proprietary software).

Maybe you can give me a clue on how to move forward? I understand the thing with timestamp capacity - that is exactly what I supposed first.

**Comment by kqyang** [comment]
@psytechno604 A possible workaround is to adjust Period@start instead of adjusting MPD@availablityStartTime. So we can fix availabilityStartTime="1970-01-01T00:00:00Z". Would that work with your third-party server-side ad insertion software?

It will require some changes in the code here: https://github.com/google/shaka-packager/blob/8e113af215d48e704b5b031442fe3841b4e6940c/packager/mpd/base/mpd_builder.cc#L296.

**Comment by psytechno604** [comment]
If it will have availabilityStartTime="1970-01-01T00:00:00Z" - then it would work with our server. But if the timestamps inside segments are the same as with "standart" DASH stream with availabilityStartTime=<stream start time> - it will not play on any player (except VLC). I tried already to do similar thing - changing manifest and segment names accordingly. Players simply skip these segments, because their logic behind is to compare [availabilityStartTime + timestamp] with current time, and if it differs by more than some allowed limit (approx. ~30 seconds) - segment does not play.

**Comment by kqyang** [comment]
@psytechno604 Did you modify the `Period@start` as well? It should work on DASH compliant players, e.g. [Shaka Player](https://github.com/google/shaka-player).

**Comment by psytechno604** [comment]
A bit busy now, but I will definitely try, it is on my list. As I understood, I need to find out how to change it in the code, not in the command line or like that? And build everything from source?

**Comment by kqyang** [comment]
@psytechno604 You may also try modifying the manifest directly using some script first, which should be easier than modifying packager source code.

**Comment by psytechno604** [comment]
Changing MPD tag's property "availabilityStartTime" without changing anything else makes no sense. Players will not accept this. Only if you change timestamps in segment timeline and file names accordingly - it will play in VLC, but only in VLC. Other players fail. I tried this method already, and I already have this kind of script. But, well, ok, it is using other packager as a source. Maybe this is an issue. I'll try again.

**Comment by kqyang** [comment]
@psytechno604 As mentioned earlier, you'll need to change both MPD@availabilityStartTime and Period@start. For example, if you reduce MPD@availabilityStartTime by 100 days, and you add the 100 days to Period@start, the net result is the same. It is compliant to DASH specification, so it should work on all DASH compliant players, e.g. Shaka Player.
