### ISSUE TITLE
Ninja -C out/Release not working on Ubuntu 20.04

### ISSUE THREAD

**Issue by PestoPatrick** [google/shaka-packager#807]
## System info
**Operating System**: Ubuntu 20.04
**Shaka Packager Version**: v2.4.2

## Issue and steps to reproduce the problem

Hello, 

I was not sure of where to put this but after struggling with trying to build the binaries in Ubuntu I wanted to post or write up just in case anyone had a similar issue.

When following the steps at https://github.com/google/shaka-packager/blob/master/docs/source/build_instructions.md everything would continue fine until the ninja -C out/Release command where an error would appear stating that libtinfo.so.5 was not found; no such file exists'. This has happened in some other projects it appears such as https://github.com/commercialhaskell/stack/issues/1012 and https://github.com/purescript/spago/issues/104. One suggestion was that the later Ubuntus ship with libtinfo.so.6 where as for instance Ubuntu 16.04 ships with libtinfo.so.5. The solution to get Ninja to build, that worked for me anyway, is by installing libtinfo.so.5 files by using the command sudo apt-get install libncurses5-dev. I hope that if this is in the wrong place that it can at least inform the devs of this issue or inform anyone else who had no idea what to do.

**Packager Command**:

ninja -C out/Release

What is the expected result?
built binaries

What happens instead?
build fails (but not anymore)

<Please attach the input files or email to shaka-packager-issues@google.com.>
<Please provide any additional information below.>

**Comment by kqyang** [comment]
Thanks @PestoPatrick for the report.

Can you try if `sudo apt-get install libtinfo5` works? 

Do you want to submit a PR to fix the build instructions? Appreciated.

**Comment by PestoPatrick** [comment]
Yeah sure. I will get on that later today.

**Comment by kqyang** [comment]
@PestoPatrick Any updates?

**Comment by Ragnoroct** [comment]
I'm also using Ubuntu 20.04 and I had the same problem.

`sudo apt-get install libtinfo5` fixed it for me :+1:

**Comment by joeyparrish** [comment]
Thanks!
