### ISSUE TITLE
Key rotation content's audio stream playback is failing after 6 seconds

### ISSUE THREAD

**Issue by mkcdot** [google/shaka-packager#811]
## System info
**Operating System**: Windows 10
**Shaka Packager Version**:  v2.4.2-c60e988afa-release

## Issue and steps to reproduce the problem
1. Plain mp4 file with h.264 video and AAC audio codec is encrypted and packaged in dash format with key rotation and `enable_raw_key_encryption` options for clearkey and/or widevine DRMs.
2. Output Dash content is played using exoplayer with clearkey DRM.
3. If only video stream is selected with no audio stream, video plays fully by acquiring all required keys from license server.
4. But when audio stream is selected along with/without video stream, playback fails after 6 seconds.
5. If I play google's key rotation sample hosted at [https://storage.googleapis.com/playerinfra/wv/sintel_3min_rotate.mpd](url), exoplayer plays both audio and video without any problem using widevine DRM.
So exoplayer supports key rotation and there is no exoplayer configuration issue.

**Packager Command**:
`packager \
  in=video_360p_h264-600k.mp4,stream=audio,output=audio.mp4,drm_label=AUDIO \
  in=video_360p_h264-600k.mp4,stream=video,output=h264_360p.mp4,drm_label=SD \
  in=video_480p_h264-1000k.mp4,stream=video,output=h264_480p.mp4,drm_label=SD \
  in=video_720p_h264-3000k.mp4,stream=video,output=h264_720p.mp4,drm_label=HD \
  in=video_1080p_h264-6000k.mp4,stream=video,output=h264_1080p.mp4,drm_label=HD \
  --enable_raw_key_encryption \
  --crypto_period_duration 120 \
  --keys label=AUDIO:key_id=279926496a7f5d25da69f2b3b2799a81:key=eee0f2b3b279926496a7f5d25da692f6,label=SD:key_id=279926496a7f5d25da69f2b3b2799a81:key=eee0f2b3b279926496a7f5d25da692f6,label=HD:key_id=279926496a7f5d25da69f2b3b2799a81:key=eee0f2b3b279926496a7f5d25da692f6 \
  --protection_systems Widevine,CommonSystem \
  --mpd_output h264.mpd`

What is the expected result?
Both video along with audio streams should be played without any failure in exoplayer.

What happens instead?
Only video stream plays fully. Audio stream playback fails after 6 seconds.

<Please attach the input files or email to shaka-packager-issues@google.com.>
Shaka packager dash output files (Converted from xml to txt to attach here):
[h264.txt](https://github.com/google/shaka-packager/files/5020570/h264.txt)
MP4Box -diso output logs:
[audio_info.txt](https://github.com/google/shaka-packager/files/5020592/audio_info.txt)
[h264_360p_info.txt](https://github.com/google/shaka-packager/files/5020593/h264_360p_info.txt)

Reference content mentioned above from google:
[https://storage.googleapis.com/playerinfra/wv/sintel_3min_rotate.mpd](url)

<Please provide any additional information below.>

Additional information:
When audio stream is selected and played in exoplayer and playback is seeked to any particular timestamp of the content (i.e. in my sample content, between 0 to 4 min 20 sec), corresponding key is acquired by exoplayer from license server correctly. But playback immediately fails.

**Comment by kqyang** [comment]
@mkcdot I am curious how you set up your license server. Does it have the keys for both audio and video.

Also note that the key rotation with `--enable_raw_key_encryption` is only for testing as it simply rotates the keys literally (e.g. 0x eee0f2b3b279926496a7f5d25da692f6 becomes 0xe0f2b3b279926496a7f5d25da692f6ee in the next crypto period).

**Comment by mkcdot** [comment]
Yes. I have configured all the keys as per 1 byte circular left shift. And same keys are used for audio as well as video as you can check in packager command. Same is verified using mp4box -diso output log files for audio and video streams. 
Video stream plays without any issue and as I mentioned in additional information, during audio stream playback, keys are fetched correctly. Only audio stream playback is failing.
Please check the cpix file of license server attached here: (I am using axinom clearkey license server)
[content_keys.txt](https://github.com/google/shaka-packager/files/5026335/content_keys.txt)

**Comment by kqyang** [comment]
Oh, I see. I didn't notice that the keys were the same. Can you try if it works if using different keys for audio and video?

**Comment by mkcdot** [comment]
I tried with different keys for audio and video. Now also same issue persists. Video alone plays fully. But audio with/without video stream fails after 6 sec.

**Comment by kqyang** [comment]
Are you using Widevine license server? It seems to be a policy configuration problem to me. What did you set for the policy? What is the error you are seeing? Have you tried Shaka Player?

**Comment by mkcdot** [comment]
I am using clearkey server. There are no policies set for content.
Recently, I played it on Shaka Player. Audio and video both can be played on shaka player.
 So I posted question on exoplayer forum. Check this: [https://github.com/google/ExoPlayer/issues/7716](url).
On exoplayer, there is some issue with FMP4 container structure. Its a bug in exoplayer.

I am able to play following widevine key-rotation content generated using shaka-packager on exoplayer:
[https://storage.googleapis.com/playerinfra/wv/sintel_3min_rotate.mpd](url).
So there might be some option in shaka-packager which will generate the dash content as supported by exoplayer as of now.
**Is there any option in shaka-packager to package the content as expected by exoplayer?**

**Comment by kqyang** [comment]
Looking at Exoplayer dev's reply, it is a bug in Exoplayer.

It is not happening for Widevine key-rotation content, as the content does not have seek prerolls in audio and your content does.

I suggest waiting for Exoplayer's fix.

If you want to workaround it in Shaka Packager before it is fixed in ExoPlayer, swapping the code at https://github.com/google/shaka-packager/blob/master/packager/media/formats/mp4/fragmenter.cc#L195 and https://github.com/google/shaka-packager/blob/master/packager/media/formats/mp4/fragmenter.cc#L206 should work.

**Comment by mkcdot** [comment]
The issue got fixed from exoplayer side with latest commit: [https://github.com/google/ExoPlayer/commit/6a54ddd2173d3fd6def0c7e1320a3197e5ac2f44](url) .

Thanks for your support.
