### ISSUE TITLE
Sending Packaged Content to Google Cloud Storage

### ISSUE THREAD

**Issue by akyker20** [google/shaka-packager#813]
I am using Shaka Packager to create DASH content. Right now, I am outputting the segment files and manifest to my server's file system. What I want to do is send these files to Google Cloud Storage. And I'd like to do it as efficiently as possible.

Can you provide some recommendations on how to send these files to Google Cloud Storage? My server is written in Python. My plan right now is to create a directory to output my shaka packaged files, and then have another process that checks for new files in the directory every second and if it finds any, sends them to Cloud Storage.

Is there a better, more efficient way to do this?

Love this package :)

**Comment by kqyang** [comment]
@akyker20 Yes, it should work. Note that you'll also need to push the updated manifests in addition to the media segments; and also make sure the media files are pushed first before pushing the manifests to the cloud. 

You may also try the Shaka Streamer tool, which supports pushing to cloud storage: https://github.com/google/shaka-streamer.

We are also adding support for "cloud" files but that won't be done any time soon.

Let us know if you have other questions.
