### ISSUE TITLE
License Request Got Results With Status INVALID_REQUEST

### ISSUE THREAD

**Issue by weiyuefei** [google/shaka-packager#826]
Hi Widevine Team,

I used the external keys to perform Widevine DRM encryption on the content, and bellow is the packager command for my testing, and the {`key_id`, `key`} pairs were fecthed from the third-party key server beforehand:

packager \
  in=h264_baseline_360p_600.mp4,stream=audio,output=audio.mp4,drm_label=AUDIO \
  in=h264_baseline_360p_600.mp4,stream=video,output=h264_360p.mp4,drm_label=SD \
  in=h264_main_480p_1000.mp4,stream=video,output=h264_480p.mp4,drm_label=SD \
  in=h264_main_720p_3000.mp4,stream=video,output=h264_720p.mp4,drm_label=HD \
  in=h264_high_1080p_6000.mp4,stream=video,output=h264_1080p.mp4,drm_label=HD \
  --enable_raw_key_encryption \
  --keys \
 label=AUDIO:key_id=f3c5e0361e6654b28f8049c778b23946:key=a4631a153a443df9eed0593043db7519,label=SD:key_id=abba271e8bcf552bbd2e86a434a9a5d9:key=69eaa802a6763af979e8d1940fb88392,label=HD:key_id=6d76f25cb17f5e16b8eaef6bbf582d8e:key=cb541084c99731aef4fff74500c12ead \
  --protection_systems Widevine \
  --mpd_output manifest.mpd

After packaging, I tried to play this content by Andriod device, and the License Proxy Server got the certificate request from client device.  In this scenario, the License Proxy Server should inject the external content encryption keys into the license request by `content_key_specs`, and bellow is the license message that the proxy server built:

`{"allowed_track_types":"SD_UHD1","content_id":"NzQ2NTczNzQyMDYzNmY2ZTc0NjU2ZTc0MjA2OTY0","content_key_specs":[{"key":"YTQ2MzFhMTUzYTQ0M2RmOWVlZDA1OTMwNDNkYjc1MTk=","key_id":"ZjNjNWUwMzYxZTY2NTRiMjhmODA0OWM3NzhiMjM5NDY="},{"key":"NjllYWE4MDJhNjc2M2FmOTc5ZThkMTk0MGZiODgzOTI=","key_id":"YWJiYTI3MWU4YmNmNTUyYmJkMmU4NmE0MzRhOWE1ZDk="},{"key":"Y2I1NDEwODRjOTk3MzFhZWY0ZmZmNzQ1MDBjMTJlYWQ=","key_id":"NmQ3NmYyNWNiMTdmNWUxNmI4ZWFlZjZiYmY1ODJkOGU="}],"payload":"CAESuw0KwgwIARLrCQquAggCEhDLtt5wknBXNHbKGqVXVrV2GNzZvtsFIo4CMIIBCgKCAQEAoDp4DwMtafzsTtZ/FNzzhm+OnAlKlASVZeDTMJAsuxbjJEgomqOTfkcVlHxOlYJMM9kTdng0nfQnNIzPG88EyAmEZBm3U8qSL0IEMHEMeENNKAKQbqKmVyhSrgaoA5M2y+BghLYcQg158tN/M4dPmbamgrNMnoJ6rLn/8JgzCKfhDG9ijv+kc0uVloJRuKvVWop2V0flufha29ekSjzQBxZm6XNtMFNSp3XHwxbZ3qqze1PS/mFe6K934w3R3K1hRLKpFXKoVB7EhaUQ3lRIIXk8V/HoJV7lIE5PtyTEJJ8wI9GD3Wi7PbL+xnBkoUBIgsfgGoyS6GBnBqu1+AKG3QIDAQABKN0iEoACto9g9IQSHUImLyEgiz4fe8x6xTKqAtxYul+fFPasL0w0Gg54NK0WzH51t0WQr5kkYd0vpvTygyLfzFVy2VhORc0K3inspqnriKOyr2lmNuliJqz2pVzsmvalH/lri7BZ96EcEfmH32ReQsSc7P8xxguAEVBD5Wep1IGX2aGK6DGmgGB5grrbVKdrsL42z6khox6wqLzF3fY6Knxp+UGJaTvJeo4ZtmEwsoRQNHcqpuy2dXX1DX3WSIOeBip1ohZZWW+mO7DnOFB4VAmlLBl0cKjj3+BY1KpvYnnDdAPxLbQLImJEqOQNs8Twm5EKOJDTfsBmPgkiJtd4bf+JzP2lohq0BQquAggBEhAX3Lwn0RNB1JcTVEKhiNqmGI+JgJEFIo4CMIIBCgKCAQEA0hrddUnSdIs0lFJqnD+4bHk3a76MiFb2AbjRBGH3esxzMbEN6/NlEgBWzbVmLSWQe3TxI4Lw9KDKR17qlWKBXGIo9vaYraJ4ediJDyotlqdG3e9TFjAcADUZwqIlA1RnQWn92kHOFNPFK+p6IDhFFQEtWVKziqGeFehWPMeqqBwhIogKo3CmT+ojxT+4OsPbV1MhRzCjSeB/ZL8yvn6tMNAmEq8RC7RPsI4dMIFzsyfvZNQMQWOVQrLRpzyYpmB+xsaDtROlhHBRQQbvh64ee5xpW5OhBN90N7/EFneJdIpD7SCPLB+nEHk8aIiF6ucyqL/fW0I7I9dbiPwK3I+9tQIDAQABKN0iEoADctL7iAmLo7hba0NU4Ddn2+LXckZj+wpiq/dwTqkQ4B8iE0nuFtAVLHaThAUM54UgZowGzP09eJrz62n/FjYVzWCRaf2+LhWgKdNK0mBWJbyBhEydHizgUZA583ma2u+GZB4gsDPcFt8uW5oaKkF7i7O3pNmtGpk2dEhYfaE93gWj7Z1i+kIHiXO0qkAmPXv6I/EHLpTN8yP6RfeECII+VcT0xccjgZz0TObZjlDATsJNk7GquId7kQi5yjkTCOGjZF67Dnysu0C1RRVg7XmUIYc7+1q7kX+mDbnHfLhgavfjFCYm9epA5cuKoInY59apNhk1xCakRQ6ovC5XKQ078KCWKZHSqRt1L8gMPn5OVQM9cclLMlMHpogV8CZEj1aidBzr78GOjBQvX2K/qmeikVF93pgtjNWp3249Opm4BvbWCZE1jFvncRfU8xaPM0jpoEhTn4kvTXgxUseoCVIkqla3jFz3vRqxsXnAwNEePDushMFBoAGRMh46zBckLmg8GhYKDGNvbXBhbnlfbmFtZRIGSFVBV0VJGhUKCm1vZGVsX25hbWUSB0JBSC1XMDkaHgoRYXJjaGl0ZWN0dXJlX25hbWUSCWFybTY0LXY4YRoWCgtkZXZpY2VfbmFtZRIHSFdCQUgtURoTCgxwcm9kdWN0X25hbWUSA0JBSBpNCgpidWlsZF9pbmZvEj9IVUFXRUkvQkFIL0hXQkFILVE6Ny4wL0hVQVdFSUJBSC1XMDkvQzIzM0IyODU6dXNlci9yZWxlYXNlLWtleXMaLQoJZGV2aWNlX2lkEiBnYXVwYWV7YW5PcENsaUpseWl6TWpCVEdxZGtWYUJRABomChR3aWRldmluZV9jZG1fdmVyc2lvbhIOdjQuMC4wLWFuZHJvaWQaJAofb2VtX2NyeXB0b19zZWN1cml0eV9wYXRjaF9sZXZlbBIBMDIIEAEgACgLMAASZApiCjwSEPPF4DYeZlSyj4BJx3iyOUYSEG128lyxf14WuOrva79YLY4SEKu6Jx6Lz1UrvS6GpDSppdlI49yVmwYQARogMUEwQTkxQ0FCQTgyQkUwMDAxMDAwMDAwMDAwMDAwMDAYASCK0pL6BTAVOP6ml8QMGoACFXEc/TyuNUgDxwoSvxika+HPCLzwuq2m9FON59pgQygWcItlN42JJuX7mW8X3CKRW/RiNhSXmm4nBxTnPLUwZx3gyDQpYKTMZ76wIsRwXdleTVWBBNwe7zdbjoi4AENzGmrWvkc+jZ0bPHhT1cE2i4c8Z2k5J35c6xXwa2BTPxGBVln99dz3TQpTjcoHUSBUYcQMXpYbDGv3sim2935tlHpmF95RDkV/PB9lb8KHXhoCxP7cguHPAS5i460NTyIhysZCMck52UYTZv9FTUOsuYOaxYv4DGpt40LJ8YKZqhxjahScuyK9WIaMiFeW7/d3jWls90R4LIWQERb2p1AZdQ==","provider":""}`

After that, the proxy server sent this license request to Google License Cloud, but got result with `Status` INVALID_REQUEST, and bellow is the total results:

`Status:INVALID_REQUEST License: Make:Generic Field Provisioning Model:Android KLP ARM SecurityLevel:3 InternalStatus:169 DRMCertSerialNumber:Y2JiNmRlNzA5MjcwNTczNDc2Y2ExYWE1NTc1NmI1NzY= DeviceWhitelistState:DEVICE_WHITELISTED MessageType: Platform:android DeviceState:RELEASED ClientMaxHDCPVersion:HDCP_NONE PlatformVerificationStatus:PLATFORM_NO_VERIFICATION ContentOwner: ContentPRovider: SessionState:{LicenseID:{RequestID: SessionID: PurchaseID: Type: Version:0} SigningKey: KeyboxSystemID:0 LicenseCounter:0} LicenseMetadata:{ContentID:NzQ2NTczNzQyMDYzNmY2ZTc0NjU2ZTc0MjA2OTY0 LicenseType:STREAMING RequestType:NEW} SupportedTracks:[] PSSHData:{KeyID: ContentID:} ClientInfo:[{Name:company_name Value:HUAWEI} {Name:model_name Value:BAH-W09} {Name:architecture_name Value:arm64-v8a} {Name:device_name Value:HWBAH-Q} {Name:product_name Value:BAH} {Name:build_info Value:HUAWEI/BAH/HWBAH-Q:7.0/HUAWEIBAH-W09/C233B285:user/release-keys} {Name:device_id Value:gaupae{anOpCliJlyizMjBTGqdkVaBQ} {Name:widevine_cdm_version Value:v4.0.0-android} {Name:oem_crypto_security_patch_level Value:0}]`
 
Can anyone help me out to make me clear where I'm wrong in the whole process? Thanks

**Comment by kqyang** [comment]
@weiyuefei Please send Widevine related questions to Widevine support or CWIP discussion group.
