### ISSUE TITLE
Writing frameRate on live MPD by realtime

### ISSUE THREAD

**Issue by jgkim0518** [google/shaka-packager#827]
hello.

I having streamed Video on live 3 channel.

frameRate of Ch.1 mpd is "90000/3003". frameRate of Ch.2 mpd is "90000/3600". frameRate of Ch.3 mpd is "90000/10800".
but now, Ch.3 is streaming 25fps. I think that it write from sample segment(first segment) when start streaming by shaka packager.

How to write frameRate "90000/3600" on live MPD?
How to write frameRate on live MPD by realtime?

Thank you.

1.mpd
```
...
<AdaptationSet id="0" contentType="video" maxWidth="1920" maxHeight="1080" frameRate="90000/3003" segmentAlignment="true" par="16:9">
...
```

2.mpd
```
...
<AdaptationSet id="0" contentType="video" maxWidth="1920" maxHeight="1080" frameRate="90000/3600" segmentAlignment="true" par="16:9">
.. 
```

3.mpd
```
...
<AdaptationSet id="0" contentType="video" maxWidth="1920" maxHeight="1080" frameRate="90000/10800" segmentAlignment="true" par="16:9">
...
```

**Comment by kqyang** [comment]
@jgkim0518 I am not sure what you mean. Shaka Packager computes the frame rate from the input streams. Do you mean that your input stream has some frame rate in the beginning then changes to a different frame rate later?

**Comment by jgkim0518** [comment]
1.mpd of Ch.1 , 2.mpd of Ch.2, 3.mpd of Ch.3 are different. They are live channel. Input is UDP. simply, Ch.3 is playing 25fps. but, frameRate was written "90000/10800". I want to be written "90000/3600" How to do? Thank you.

**Comment by kqyang** [comment]
Do you mean that the frame rate of the input stream is 25 fps, but the value in the mpd is `90000/10800`? If so, then there is a bug in Shaka Packager. Can you provide an output mpd with some media files for ch.3?

**Comment by jgkim0518** [comment]
Input stream provided CDN. so i can't provide. My Question are why frameRate(frameRate="90000/10800") on live Mpd(3.mpd of Ch.3) and framerate(25fps) being playing actually are different and how make same. I think media is low fps when start. Very sorry. my English very short.

**Comment by kqyang** [comment]
As mentioned earlier, it is computed from the data in the input stream. 

From what you have described, looks like there is a bug in the computation of the frame rate. In this case, we'll need to look at either the input or the output to see where the problem may be. 

If the stream cannot be shared publicly, can you send it shaka-packager-issues@google.com?

**Comment by jgkim0518** [comment]
Would you talk to me about being computed frameRate on Live MPD from the data in the input stream? How do compute frameRate on Live MPD from the data in the input stream? OK. I will send input udp and command to you. thank you so much.

**Comment by kqyang** [comment]
Right now it is computed from the duration of the first frame it sees, regardless of whether it is live stream or not.

**Comment by jgkim0518** [comment]
first frame in first segment on MPD, right? If framerate of input video into udp change sent CDN, Do frameRate Change as from "frameRate="90000/3003"" to "frameRate="90000/3600"", "frameRate="90000/3600"" to "frameRate="90000/10800"" or "frameRate="90000/10800"" to "frameRate="90000/3600""? thank you so much!

**Comment by kqyang** [comment]
It is based on the first frame of "THE" stream.

Do you mean that frame rate change can change in the stream?

**Comment by jgkim0518** [comment]
Packager connect with ffmpeg. ffmpeg receive some server send video stream through multicast . ffmpeg don't change framerate. if frameRate of the video stream be changed  because of playlist or order, Do frameRate of MPD(packager) Change in to be right real-time statue? Thank you so much. your my hero!!!!

**Comment by kqyang** [comment]
No. In that case, frame rate shouldn't change. Can you send the packager output to shaka-packager-issues@google.com so can analyze the output?

**Comment by jgkim0518** [comment]
send. thank you. if I will edit forced Shaka Packager source code for calculating average of some frames in real time, Could you expect problems as performance or logic? If I edit somewhere in shaka packager source code, can shaka packager calculate framerate on in real time and write frameRate to MPD?

**Comment by kqyang** [comment]
@jgkim0518 Can you send the contents of the files instead of an inaccessible address?

> if I will edit forced Shaka Packager source code for calculating average of some frames in real time, Could you expect problems as performance or logic? If I edit somewhere in shaka packager source code, can shaka packager calculate framerate on in real time and write frameRate to MPD?

It will depend on how you do it.

**Comment by jgkim0518** [comment]
Sorry. I use input source through UDP.  I sent it to you. thank you so much.
