### ISSUE TITLE
Use remote url in <BaseURL> Manifest

### ISSUE THREAD

**Issue by siddhesh1996** [google/shaka-packager#830]
Hello,

How can I use remote video URL in the manifest `.mdp` file?
**For Eg:**
`<Representation id="0" bandwidth="406245" codecs="avc1.64001e" mimeType="video/mp4" sar="1:1" width="640" height="360">
        **<BaseURL>http://www.myserver.com/sample/video.mp4</BaseURL>**
        <SegmentBase indexRange="870-997" timescale="15360">
          <Initialization range="0-869"/>
        </SegmentBase>
</Representation>`

I know how to use it with the filesystem, but what if the videos are hosted in cloud storage?

Cheers,
Siddhesh

**Comment by kqyang** [comment]
@siddhesh1996 Is [--base_urls](https://google.github.io/shaka-packager/html/tutorials/dash.html#dash-options) you are looking for?

**Comment by siddhesh1996** [comment]
@kqyang not exactly 
packager in=h264_baseline_360p_600.mp4,stream=audio,output=**audio.mp4**
--mpd_output h264.mpd
By using the above command
The below given baseURL would be generated in the manifest h264.mdp.
`<BaseURL>audio.mp4</BaseURL>` 
My expected requirement is:-
packager in=http://www.myserver.com/h264_baseline_360p_600.mp4,stream=audio,output=**http://www.myserver.com/dest/audio.mp4**

**Comment by kqyang** [comment]
@siddhesh1996 The result manifest generated by the below command is equivalent.

```bash
packager in=h264_baseline_360p_600.mp4,stream=audio,output=audio.mp4  \
  --mpd_output h264.mpd --base_urls http://www.myserver.com/dest/
```

Is there a reason that it does not meet your needs?

**Comment by siddhesh1996** [comment]
@kqyang Thanks for the help, yes it worked. Actually had no clue about --base_urls. Thanks again Cheers!

**Comment by kqyang** [comment]
@siddhesh1996 Great!
