### ISSUE TITLE
Missing parentheses around Python print statements in build scripts break Linux distros switching to Python 3 for /usr/bin/python

### ISSUE THREAD

**Issue by TheChuckster** [google/shaka-packager#831]
## System info
**Operating System**: Arch Linux
**Shaka Packager Version**: Latest

## Issue and steps to reproduce the problem

I look in the clang scripts directory, and the Python files are riddled with these non-Pythonic print statements.

**Packager Command**:

Extra steps to reproduce the problem?
(1) `gclient config https://www.github.com/google/shaka-packager.git --name=src --unmanaged`
(2) Run `gclient sync`

What is the expected result?

Per build instructions, new source tree is expected ready to be built upon running this command.

What happens instead?

```
Running hooks:  80% ( 4/ 5)      
________ running 'vpython src/gyp_packager.py --depth=src/packager' in '/home/chuck/shaka_packager'
Updating projects from gyp files...
  File "./tools/clang/scripts/update.py", line 119
    print ' Done.'
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(' Done.')?
gyp: Call to 'python ./tools/clang/scripts/update.py --print-revision' returned exit status 1 while in /home/chuck/shaka_packager/src/packager/packager.gyp.
Error: Command 'vpython src/gyp_packager.py --depth=src/packager' returned non-zero exit status 1 in /home/chuck/shaka_packager
```

**Comment by kqyang** [comment]
@TheChuckster Thanks for the bug report. Will you be interested in helping us fixing it? You may try bumping up the version here: https://github.com/google/shaka-packager/blob/master/DEPS#L71 to the latest: https://chromium.googlesource.com/chromium/src/tools/clang/+/89d15db59117ae3086a47ee3d7abb45f5430bbd1.

After making the change, run `gclient sync` again.

**Comment by joeyparrish** [comment]
I believe this has been resolved as part of the GitHub Actions CI work.  (Python3 is the default in GitHub's latest Ubuntu VMs.)  @TheChuckster, if this is still an issue for you, please let us know and we will reopen and investigate.  Thanks!
