### ISSUE TITLE
Update pssh box utility to work with Python 3

### ISSUE THREAD

**Issue by crazyghost12** [google/shaka-packager#833]
## System info
**Operating System**: Ubuntu 18.04
**Shaka Packager Version**: 2.4.3

## Issue and steps to reproduce the problem
Using pssh-box.py with python 3 fails.
Error message: can't concat str to bytes

**Packager Command**:
python3 pssh-box.py --widevine-system-id --content-id 1231897231 --hex

What is the expected result?
A pssh box must be generated

What happens instead?
Got the error message 'can't concat str to bytes'

**Comment by kqyang** [comment]
Thanks for the bug report. You are welcomed to submit a PR to fix this issue.
