### ISSUE TITLE
Generating a PSSH box for both widevine and playready

### ISSUE THREAD

**Issue by crazyghost12** [google/shaka-packager#839]
I want to generate a PSSH box for both widevine and playready which I will then use with the Shaka packager.
While I see that there is a widevine system id in the pssh-box.py script, there is no system id for playready.
What command should I use?
The key id that I am generating is a base64 encoded 16 byte long random string like: xxPUOTb6nxJoAFycg+03DQ==

**Comment by kqyang** [comment]
You can provide the PlayReady system id in `--system-id` to `pssh-box.py` script.

Alternatively, Shaka Packager supports generating Widevine PSSH and PlayReady directly. See the last example in https://google.github.io/shaka-packager/html/tutorials/raw_key.html#examples.

Let us know if that answers your question.

**Comment by crazyghost12** [comment]
I used the following command to generate the pssh box for both widevine and playready:
pssh-box.py --hex --widevine-system-id --pssh-data xxPUOTb6nxJoAFycg+03DQ== -- --system-id 9A04F07998404286AB92E65BE0885F95 --pssh-data xxPUOTb6nxJoAFycg+03DQ==

And it generated the following output:
000000307073736800000000EDEF8BA979D64ACEA3C827DCD51D21ED00000010C713D43936FA9F1268005C9C83ED370D0000003070737368000000009A04F07998404286AB92E65BE0885F9500000010C713D43936FA9F1268005C9C83ED370D

Next I used this generated output to parse the box:
pssh-box.py --from-hex 000000307073736800000000EDEF8BA979D64ACEA3C827DCD51D21ED00000010C713D43936FA9F1268005C9C83ED370D0000003070737368000000009A04F07998404286AB92E65BE0885F9500000010C713D43936FA9F1268005C9C83ED370D

And got the following output:
PSSH Box v0
  System ID: Widevine edef8ba9-79d6-4ace-a3c8-27dcd51d21ed
  PSSH Data (size: 16):
    Widevine Data:
      ERROR: Tag had invalid wire type.
PSSH Box v0
  System ID: PlayReady 9a04f079-9840-4286-ab92-e65be0885f95
  PSSH Data (size: 16):
    PlayReady Data:
      ERROR: Length incorrect

What am I doing wrong here?
Also, do the Base64 encrypted keyIds have to be given as pssh-data or something else? And do they have to be different for each DRM type or can they be the same?

**Comment by kqyang** [comment]
Isn't `xxPUOTb6nxJoAFycg+03DQ==` key-id instead of `pssh-data`? It should be provided using `--key-id` instead.

**Comment by crazyghost12** [comment]
Doesn't the key-id have to be hex?
I get this error if I use key-id instead of pssh-data:

**Comment by kqyang** [comment]
You can convert base64 to hex format first. Try googling for base64 to hex converter.

`pssh-data` is the data contained in the pssh. It is an opaque data defined by content protection system providers. For example, Widevine's pssh-data is a protobuf, while PlayReady's pssh-data is an xml.

**Comment by crazyghost12** [comment]
That worked. 
I swear I had tried it before but did not get a 32 digit hex keyId after converting (maybe I did something while generating the base64). 
One last thing, can you confirm that the keyId for both widevine and playready be the same while generating the pssh box.

Can you also confirm that the output that I receive after parsing the generated pssh box is correct.
I used this:
./pssh-box.py --hex --widevine-system-id --key-id c713d43936fa9f1268005c9c83ed370d -- --system-id 9A04F07998404286AB92E65BE0885F95 --key-id c713d43936fa9f1268005c9c83ed370d
and got:
000000327073736800000000EDEF8BA979D64ACEA3C827DCD51D21ED000000121210C713D43936FA9F1268005C9C83ED370D0000003470737368010000009A04F07998404286AB92E65BE0885F9500000001C713D43936FA9F1268005C9C83ED370D00000000

upon parsing the string I got this response:
PSSH Box v0
  System ID: Widevine edef8ba9-79d6-4ace-a3c8-27dcd51d21ed
  PSSH Data (size: 18):
    Widevine Data:
      Key IDs (1):
        c713d439-36fa-9f12-6800-5c9c83ed370d
PSSH Box v1
  System ID: PlayReady 9a04f079-9840-4286-ab92-e65be0885f95
  Key IDs (1):
    c713d439-36fa-9f12-6800-5c9c83ed370d
  PSSH Data (size: 0):


Why is the widevine pssh box v0?

**Comment by kqyang** [comment]
> That worked.

Great. 

> Can you also confirm that the output that I receive after parsing the generated pssh box is correct.

Yes, the format is correct. I recommend checking with your license providers as they may have different requirements.

> Why is the widevine pssh box v0?

This is for maximum compatibility with legacy devices. Some old Android devices do not support pssh box v1.

I am closing this bug as your questions have been addressed. Feel free to reply or file another issue if you have more questions.
