### ISSUE TITLE
Multi codec together

### ISSUE THREAD

**Issue by Ballevill** [google/shaka-packager#843]
Hi, I have a question:

Is it possible to put 2 audio versions in one mpd, e.g. acc and opus together and several versions of the video versions, for example, I have coded:

audio - acc mp4
audio - opus webm
720p - x264 mp4
1080p - x264 mp4
1080p - vp9 webm

and if the TV does not support vp9 shaka player will play:

1080p - x264 mp4 + acc
720p - x264 mp4 + acc

If the TV supports vp9 and opus, shaka player will play:

1080p - vp9 webm + opus
720p - x264 + acc

If the TV supports vp9 but not opus shaka player will play:

1080p - vp9 webm + acc
720p - x264 + acc

If yes how then pack it using Shaka Packager.

Thank you very much for help. :)

**Comment by kqyang** [comment]
Yes, you can package multi-codec in one mpd using Shaka Packager. Here is an example command:

```
$ packager  \
  in=h264.mp4,stream=video,out=h264_video.mp4  \
  in=vp9.mp4,stream=video,out=vp9_video.mp4  \
  ...
```
  
Here is a Shaka Player demo content packaged by Shaka Packager:
https://shaka-player-demo.appspot.com/demo/#audiolang=en-US;textlang=en-US;uilang=en-US;asset=https://storage.googleapis.com/shaka-demo-assets/angel-one/dash.mpd;panel=ALL_CONTENT;build=uncompiled.

@joeyparrish Is there any way to signal to Shaka Player that "vp9" should be used if it is supported by the platform, and fallback to "h264" if it is not supported?

**Comment by Ballevill** [comment]
kqyang thank you for the answer, but I have a second question, will Shaka Packager automatically detect which codecs the browser supports? Is it possible to set in Shaka Player?.

Have a nice weekend

**Comment by joeyparrish** [comment]
@kqyang, @Ballevill, Shaka Player will query the browser for every codec in a manifest and choose from among those that are supported.  Fallback to supported codecs is completely automatic and requires no configuration.

If multiple codecs are supported, today, Shaka Player will choose the one with the lowest average bandwidth consumption.  In the future, we will offer some configuration callback for codec preferences.

**Comment by krychu90** [comment]
> If multiple codecs are supported, today, Shaka Player will choose the one with the lowest average bandwidth consumption. In the future, we will offer some configuration callback for codec preferences.

What happens when I have videos in big resolution (e.g. 4k) in av1 codec, medium in vp9 and small in x264? There will be full list of resolutions that are supported in the client browser (like youtube) or only resolutions from one supported codec?

**Comment by Ballevill** [comment]
@joeyparrish 

So if I have:

1080p in vp9
720p in x264

it won't show 2 resolutions? Only 1080p if tv supports vp9?

**Comment by joeyparrish** [comment]
@Ballevill, that's correct.  Shaka Player's codec-selection logic currently makes the simplifying assumption that you will provide the same or similar resolutions for all codecs.  Why would you have 720p only in h264 and 1080p only in vp9?  That seems unrealistic.

The logic also assumes that you will have constant quality/resolution and vary the bitrate to meet those targets.  That would make more efficient codecs obvious by bitrate alone.  For example, vp9 can achieve the same resolution and quality as h264 with lower bitrate.  If you have encoded your content with the same bitrate across codecs, but different quality levels, that logic will no longer select the best codec.

For the future, to better support content libraries with encoding practices that break our original assumptions, we will offer some additional configurability for codec selection.

Does this help?
