### ISSUE TITLE
PSSH box is being generated despite providing pssh manually to packager

### ISSUE THREAD

**Issue by crazyghost12** [google/shaka-packager#846]
## System info
**Operating System**: Ubuntu 18.04
**Shaka Packager Version**: 2.4

## Issue and steps to reproduce the problem

**Packager Command**: packager input=test.mp4,stream=audio,output=output.mp4 --mpd_output master.mpd --segment_duration 1 --fragment_duration 1 --enable_raw_key_encryption --protection_scheme cenc --keys label=AUDIO:key_id=1d6c226cec8846378629f788fe180f2c:key=de0cfa0e2dcff081824a06027e4c0fe1 --protection_systems Widevine,PlayReady --iv a7871e0a616f9e14 --pssh 000000327073736800000000EDEF8BA979D64ACEA3C827DCD51D21ED000000121210C713D43936FA9F1268005C9C83ED370D0000003470737368010000009A04F07998404286AB92E65BE0885F9500000001C713D43936FA9F1268005C9C83ED370D00000000

What is the expected result? The manifest is generated with one ContentProtection block for each PlayReady and Widevine

What happens instead? The generated manifest contains 2 ContentProtection blocks for each DRM system. One has the PSSH box that was passed through the packager command and the second was generated by the packager

<Please attach the input files or email to shaka-packager-issues@google.com.>
<Please provide any additional information below.>

**Comment by kqyang** [comment]
`--protection_systems` specify protection systems to be generated. If you don't want packager to auto-generate the protection systems, you should remove `--protection_systems` flag.

See https://google.github.io/shaka-packager/html/tutorials/drm.html for details.

**Comment by kqyang** [comment]
I am closing this bug. Feel free to re-open it or reply if you have more questions.
