### ISSUE TITLE
DASH Packaging and the XML namespaces positioning

### ISSUE THREAD

**Issue by vish91** [google/shaka-packager#847]
Question about the DASH mpd and the xml namespace headers. https://github.com/google/shaka-packager/blob/master/packager/mpd/base/mpd_builder.cc#L44-L46
1) Is it possible to make the XMLNS attributes optional on the manifests ? 
2) Does the DASH-IF IOP mention it anywhere in the spec that it is necessary to have `xmlns:xsi` , `xsi:schemaLocation` on the <MPD> xml node ? 
3) Same as 2) but about other namespace attributes e.g why does the <MPD> object have the `xmlns:cenc` attribute defined instead should it not be in the `<ContentProtetion>` xml node ?
Would appreciate if you could point to a doc somewhere that defines if these are optional or spec guidelines on their placement in <MPD>.

**Comment by kqyang** [comment]
I believe it is required by XML specification. It tells the XML validator where to look for the XML schema for DASH specification. 

DASH mpd is an XML document, so it must conform to XML specification.

See this [W3C](https://www.w3.org/TR/xmlschema11-1/) doc for details.

I am closing this issue, but feel free to reply if you have more questions.

**Comment by vish91** [comment]
@kqyang gotcha that makes sense. I believe they are optional and players don't necessarily look for those. 
Also for point 3. do we have a list of all xml namespace attributes could exist in a packaged manifest ? if shaka docs or Dash spec has anything that you can point me to, would be helpful.
e.g do you think these 7 found in the function mentioned above covers everything.
```
  mpd->SetStringAttribute("xmlns", kXmlNamespace);
  mpd->SetStringAttribute("xmlns:xsi", kXmlNamespaceXsi);
  mpd->SetStringAttribute("xsi:schemaLocation", kDashSchemaMpd2011);

  const std::map<std::string, std::string> uris = {
      {"cenc", kCencNamespace},
      {"mas", kMarlinNamespace},
      {"xlink", kXmlNamespaceXlink},
      {"mspr", kMsprNamespace},
  }; 
```

**Comment by kqyang** [comment]
> I believe they are optional and players don't necessarily look for those.

It depends on the player - some players performs an XML schema check before starting playback.

> e.g do you think these 7 found in the function mentioned above covers everything.

There could be more entries in the future, but I think that is everything we use in Shaka Packager right now.
