### ISSUE TITLE
HLS --default-language sets DEFAULT=YES on the DVS track instead of AUDIO

### ISSUE THREAD

**Issue by vish91** [google/shaka-packager#857]
## System info
**Operating System**: macOS, ubuntu
**Shaka Packager Version**: shaka-packager version v2.4.3-dd98700-release

## Issue and steps to reproduce the problem

**Packager Command**:
shaka-packager 'in=...lang=en,playlist_name=aac_128/stream.m3u8,hls_group_id=audio_aac,hls_name=English,drm_label=audio' 'in=...,iframe_playlist_name=test/stream_iframe.m3u8,playlist_name=stream.m3u8,drm_label=sd' 'in=...,iframe_playlist_name=test/stream_iframe.m3u8,playlist_name=test_4200/stream.m3u8,drm_label=hd' 'in=...,lang=en,playlist_name=dvs_128/stream.m3u8,hls_group_id=audio_aac,hls_name=English AD,hls_characteristics=public.accessibility.describes-video,drm_label=audio' --clear_lead 0 --segment_duration 6 --default_language en --hls_master_playlist_output /tmp/hls/master.m3u8 --enable_raw_key_encryption --keys label=audio:key_id=x:key=y,label=sd:key_id=a1=a2,label=hd:key_id=a3=a4 --iv some_iv --protection_scheme cbcs --pssh some_pssh --hls_key_uri 'some_key_url'

What is the expected result?
The expected result is an HLS master manifest with 1 audio 1 dvs, 2 video tracks and iframe playlist. 
Audio `English` track should have `AUTOSELECT=YES` and `DEFAULT=YES` 
and DVS track `English AD` should have `AUTOSELCT=YES` only.

What happens instead?
Instead result we got is an HLS master manifest with 1 audio 1 dvs, 2 video tracks and iframe playlist. 
Audio DVS track `English AD` track had `AUTOSELECT=YES` and `DEFAULT=YES` 
and Audio track `English` didn't have AUTOSELECT or DEFAULT on it. 
```
from: https://developer.apple.com/documentation/http_live_streaming/hls_authoring_specification_for_apple_devices
2.13. If you provide DVS, the AUTOSELECT attribute MUST have a value of "YES".
```
We should have a better flag to control that behavior or fix `--default-language` so that it checks before setting default if there is another non-DVS audio track with the same language. 
As per HLS spec AUTOSELECT=YES should always be present on the DVS Characteristics tracks, but here the packager is instead also incorrectly setting the DEFAULT=YES on the DVS instead of the audio track. 

BUG 2: It even produces different result if you change the track names to be case sensitive. Try the example that I have above and if I have track labels as `English` and `ENGLISH AD`

**Comment by kqyang** [comment]
@vish91 Thanks for reporting the issue. Can DVS audio track be tagged as `DEFAULT=YES`? Or it should never be tagged with that? 

Two examples, what is the expected behavior when there are two audio tracks, one regular and one DVS? What if there is only one audio track which is DVS?

**Comment by vish91** [comment]
@kqyang  I don't believe so. From what I understand for DVS i.e a type of accessibility a/v track, HLS spec says that it should **always** be marked as `AUTOSELECT=YES` and beyond that we leave the selection to player, so doesn't require setting any `DEFAULT` property at all.

When there are 2 audio tracks one regular and one DVS: 
-> If default language flag is passed
 - it should mark the regular as default=yes and do nothing with the dvs

-> if the default lang lag is not passed (which means we are not asking that any track be selected as default)
  - it should leave both tracks marked as `AUTOSELECT=YES` and none of the them variants should contain default.

What is there is only one audio track ? 
- Still the same, `AUTOSELECT=YES` which keeps us spec compliant and for this case players should select it when there are no other tracks (which doesn't require the `DEFAULT` attribute at all). Players generally do as that is the hierarchy of audio track selection as I understand.

**Comment by kqyang** [comment]
@vish91 SG. Thanks.

**Comment by kqyang** [comment]
@vish91 It should be fixed now. Let us know if you are still seeing issues with the latest build.
