### ISSUE TITLE
Is HLS + TS only support SIMPLE-AES ?

### ISSUE THREAD

**Issue by lys1737** [google/shaka-packager#861]
## System info
**Operating System**: Ubuntu 14.04.12
**Shaka Packager Version**: 2.4.3

## Issue and steps to reproduce the problem

 I use  '--protection-scheme 'cbcs' or 'cenc' to output  m4s and m3u8, it is encrypt by SIMPLE-AES-CTR or SIMPLE-AES.
but use it to output ts and m3u8, it is encrypt only by SIMPLE-AES. 

**Packager Command**:

Extra steps to reproduce the problem?
(1)
(2)

What is the expected result?

I want to use SIMPLE-AES-CTR to encrypt ts .

What happens instead?

m3us show method is SIMPLE-AES.
 
<Please attach the input files or email to shaka-packager-issues@google.com.>
<Please provide any additional information below.>

**Comment by lys1737** [comment]
Operating System:  Ubuntu 14.04.12
Shaka Packager Version: 2.4.3

**Comment by kqyang** [comment]
I assume you mean `SAMPLE-AES`. 

The answer to your question is yes. `SAMPLE-AES-CTR` is only available for MP4, not for TS.
