### ISSUE TITLE
Don't support Interlaced video?

### ISSUE THREAD

**Issue by zsmsky** [google/shaka-packager#863]
## System info
**Operating System**: <e.g. macOS Sierra, Ubuntu 14.04 trusty etc>
**Shaka Packager Version**: <e.g. v1.6.1, commit SHA etc>

packager version db5413e-release

## Issue and steps to reproduce the problem
file: shaka_packager\src\packager\media\codecs\h264_parser.cc
if (sps->separate_colour_plane_flag) {
    LOG_ERROR_ONCE("Interlaced streams not supported");                **// here  return  error** 
    return kUnsupportedStream;
  }

  READ_BITS_OR_RETURN(sps->log2_max_frame_num_minus4 + 4, &shdr->frame_num);
  if (!sps->frame_mbs_only_flag) {
    READ_BOOL_OR_RETURN(&shdr->field_pic_flag);
    if (shdr->field_pic_flag) {
      LOG_ERROR_ONCE("Interlaced streams not supported");          **// here  return  error**
      return kUnsupportedStream;
    }
  }

**Packager Command**:
h264 ts stream input,  hls mp4 output

Extra steps to reproduce the problem?
(1)
(2)

What is the expected result?
I hope packager can encode interlaced video.

What happens instead?

<Please attach the input files or email to shaka-packager-issues@google.com.>
<Please provide any additional information below.>

**Comment by kqyang** [comment]
Correct. We don't support interlaced video. As far as I know, it is not supported in common web browsers either (e.g. Chrome). 

I'll mark the issue as "won't fix", but feel free to comment and add your use case in the issue. We may re-evaluate it in the future.
