### ISSUE TITLE
Subtitles management question

### ISSUE THREAD

**Issue by tonimoro** [google/shaka-packager#866]
Hi  guys,

Firstable thanks for the great job you have done with this project.
I would like to sum up the subtitles option that it's currently managed.
From what I understand, the following things are possible :

- webvtt text input  ---> webvtt output text
- ttml text input      ---> ttml output text

Recently (commits from november), you added theses new options  :
- webvtt text input  ---> ttml text output
- webvtt text input  --->  ttml or webvtt embedded in mp4 container 

Do you plan to support ttml and webvvt in mp4 as input ? and a conversion from ttml to webvtt ?

Regards.

**Comment by kqyang** [comment]
> Do you plan to support ttml and webvvt in mp4 as input

@tonimoro Is there a use-case to support ttml / webvtt in mp4 as input? As far as our understanding, the input is usually carried in raw text (webvtt, ttml) or in transport stream. 

That being said, we will consider it if there is significant interest in having it support in Shaka.

> and a conversion from ttml to webvtt ? 

I think it should be supported already. @TheModMaker Correct me if I am wrong?

**Comment by TheModMaker** [comment]
We don't support TTML input, only output.  TTML is a big spec and a lot of things are possible.  So it would involve a lot of work or it would involve restricting supported features.  We do support TTML pass-through, just not conversion.

**Comment by tonimoro** [comment]
Yes,  the question can be closed. Thanks for the answer.
@kqyang  the case to support support ttml / webvtt in mp4 as input  is when you have already a packaged fm4 input for instance and you want to repackage it with a different segmentation, or perform conversion from dash format  to hls-ts for example...

**Comment by kqyang** [comment]
@tonimoro I see. Please file a feature request if it is critical to your use case. As far as I can, it can be workarounded by keeping the original text files.
