### ISSUE TITLE
Exception: Visual Studio Version 2015 (from GYP_MSVS_VERSION) not found.

### ISSUE THREAD

**Issue by ubm1** [google/shaka-packager#867]
**Operating System**: windows 10 Pro version 1909

I was using the docs and the steps to install shaka packager https://google.github.io/shaka-packager/html/build_instructions.html
I’m almost certain I did everything right. These are  the steps I did to get where I’m at.

1. I downloaded the depot_tools.zip, and extracted it inside my “c:\src\depot_tools” folder on my computer. I made sure the .git file was inside the project of depot_tools. (https://imgur.com/a/wZZzSZD)

2. Added to the PATH c:\src\depot_tools so that the executable (NOTE: I made sure this was added in front of any directory that could have python or git installed) could be found. I also added a new variable called “DEPOT_TOOLS_WIN_TOOLCHAIN” and gave it a value of “0”. I made sure that these changes were done inside the system variables, and not user variables.
(https://imgur.com/a/y8lQkOm)

3. I ran “gclient” without any arguments for the first time to install any dependencies the first time inside the “cmd” console making sure it wasn't using powershell or bash, I didn’t get any errors although I got a warning message “WARNING: Your metrics.cfg file was invalid or nonexistent. A new one will be created.”

4. Made a directory called “shaka_packager” and went inside it using this command “mkdir shaka_packager && cd shaka_packager”.

5. This is when I ran the last command “gclient sync" and got the error listed above not being able to find the VS Code version.

“Traceback (most recent call last):
  File "src/packager/tools/clang/scripts/update.py", line 921, in <module>
    sys.exit(main())
  File "src/packager/tools/clang/scripts/update.py", line 917, in main
    return UpdateClang(args)
  File "src/packager/tools/clang/scripts/update.py", line 455, in UpdateClang
    CopyDiaDllTo(os.path.join(LLVM_BUILD_DIR, 'bin'))
  File "src/packager/tools/clang/scripts/update.py", line 379, in CopyDiaDllTo
    dia_path = os.path.join(GetVSVersion().Path(), 'DIA SDK', 'bin', 'amd64')
  File "src/packager/tools/clang/scripts/update.py", line 366, in GetVSVersion
    vs_toolchain.SetEnvironmentAndGetRuntimeDllDirs()
  File "C:\Users\14068\Desktop\WebDev\boilerplates\es6\public\audio\shaka_packager\src\packager\build\vs_toolchain.py", line 78, in SetEnvironmentAndGetRuntimeDllDirs
    os.environ['GYP_MSVS_OVERRIDE_PATH'] = DetectVisualStudioPath()
  File "C:\Users\14068\Desktop\WebDev\boilerplates\es6\public\audio\shaka_packager\src\packager\build\vs_toolchain.py", line 154, in DetectVisualStudioPath
    ' not found.') % (version_as_year))
Exception: Visual Studio Version 2015 (from GYP_MSVS_VERSION) not found.
Error: Command 'vpython.bat src/packager/tools/clang/scripts/update.py --if-needed' returned non-zero exit status 1 in C:\Users\14068\Desktop\WebDev\boilerplates\es6\public\audio\shaka_packager

If you have any questions let me know. I appreciate anyone who is willing to help, I've been pulling my hair out :). Thanks again.

**Comment by kqyang** [comment]
As mentioned in https://google.github.io/shaka-packager/html/build_instructions.html#windows-system-requirements, Visual Studio 2015 Update 3 or later is required. Have you installed Visual Studio?

**Comment by ubm1** [comment]
I have Visual Studio 2019, and have the newest Visual Studio code. Thanks for the reply I appreciate it.

**Comment by kqyang** [comment]
Can you try if installing Visual Studio 2015 solves the issue: https://visualstudio.microsoft.com/vs/older-downloads/?

**Comment by ubm1** [comment]
@kqyang Okay got it working. I had to install the exact version and uninstall all other versions. Thank you for taking the time for the reply I appreciate it, have a good day.

**Comment by kqyang** [comment]
Thanks for the confirmation! We'll keep the issue open to address the issue for VS 2015 later.

**Comment by ubm1** [comment]
I have one more question that's not related to the issue of this thread. Hopefully it's okay to ask here. Anyways, is there a way to run packager globally, as of right now I have to go to this path "shaka_packager/src/out/Release/" to use shaka_packager. I appreciate the help, thanks again.

**Comment by kqyang** [comment]
Yes, you can add the path `shaka_packager/src/out/Release` to your system path or move the binary to the system bin directory.

**Comment by ubm1** [comment]
@kqyang thanks a lot! That was easy, I really appreciate not only the reply, but getting back to me so fast. Have a wonderful day :)
