### ISSUE TITLE
How to know Sample Auxiliary Information in ts h

### ISSUE THREAD

**Issue by lys1737** [google/shaka-packager#870]
In fMP4 I can know Sample Auxiliary Information from senc box, but how can I get the right Sample Auxiliary Information in SAMPLE-AES h264 video.

**Comment by kqyang** [comment]
There is not a Sample Auxiliary Information data in SAMPLE-AES encrypted TS file. The TS stream is encrypted according to Apple specification: https://developer.apple.com/library/archive/documentation/AudioVideo/Conceptual/HLS_Sample_Encryption/Encryption/Encryption.html.

I'm closing this issue but feel free to reply if you have additional questions.
