### ISSUE TITLE
packager return different output md5 with the same input

### ISSUE THREAD

**Issue by kocoten1992** [google/shaka-packager#872]
## System info
**Operating System**: Ubuntu 20.04
**Shaka Packager Version**: v2.4.3

## Issue and steps to reproduce the problem
shaka-packager return different output with the same input.

Extra steps to reproduce the problem?
(1) create a random sound file
```
ffmpeg -f lavfi -i "sine=frequency=1000:duration=10" -ac 8 test.mp4
```
(2) create output from shaka-packager
```
packager-linux in=test.mp4,stream=audio,output=out1.mp4
packager-linux in=test.mp4,stream=audio,output=out2.mp4
```

What is the expected result?
`out1.mp4` and `out2.mp4` should have the same md5

What happens instead?
Everytime packager-linux run, file result file is different
There are case where it is the same, vp9 codec and webm container, but the same md5 every run should be the default ?

**Comment by kocoten1992** [comment]
My use case is:
- I know shaka-packager output a different file than original, so when encoding I try to use shaka-packager output as `encoded` file (rather than having 2 files: an encoded file and an shaka-packager output file)
- I've try with vp9 (webm), no matter how many times I repacked output, it still result exactly one file (ideal case)

For example:
I have video `test.webm` file,
```
./packager-linux in=test.webm,stream=video,output=out1.webm

// then use that output to another output
./packager-linux in=out1.webm,stream=video,output=out2.webm
```
`out1.webm` and `out2.webm` having identical md5sum (ideal case), but that wasn't the case in my example with mp4 above, is this a bug or expected behavior ?

**Comment by kqyang** [comment]
It is expected as the mp4 stream includes creation timestamp, which is different in different runs. You can use flag `--use_fake_clock_for_muxer` to use a fake clock (a clock always returns 0) to generate the same output.

**Comment by kocoten1992** [comment]
@kqyang thank you very much <3
