### ISSUE TITLE
[feature] ignore creation of new file when already packed previously

### ISSUE THREAD

**Issue by kocoten1992** [google/shaka-packager#877]
Hi,

When shaka-packager run, it will create a new file.

The idea is that, I'm already run packed when encoding, so there is no need to rerun it when create mpd file (I did it as two phase, 1 encode, 2 create mpd).

I was trying to hackaround with `output=/dev/null`, but shaka-packager don't allow multiple same output destination.

```
packager-linux in=test.webm,stream=video,output=/dev/null in=test2.webm,stream=video,output=/dev/null --mpd_output=output.mpd
```

Do we interest in this hack (still don't allow duplicated destination, except when destination is `/dev/null`) ? If so I will create a PR with test for this.

P/s: If there are better idea, please let me know :P

**Comment by kocoten1992** [comment]
clarification, this is why I ask for https://github.com/google/shaka-packager/issues/872

**Comment by kqyang** [comment]
@kocoten1992 Is the encode done by Shaka Packager too? It will be error-prone if it is not done by Shaka Packager as the ranges could be different. 

If it is, you can follow the instructions here: https://github.com/google/shaka-packager/issues/709#issuecomment-583972746. Does that work for you?

**Comment by kocoten1992** [comment]
thank you very much, it work perfectly.

Encode part was done by custom build ffmpeg.

But then I packed with packager - now I will generate output_media_info while packed too, and just use that for generate mpd, no file needed - it perfect.
