### ISSUE TITLE
WEBVTT: packager warning about Text alignment

### ISSUE THREAD

**Issue by vish91** [google/shaka-packager#882]
noticed today some warnings from the newer builds after the commit referenced below from Oct 2020 
https://github.com/google/shaka-packager/blob/b231c365399bdd2a8e6b6aef299b4191523e2fcd/packager/media/formats/webvtt/webvtt_parser.cc#L176-L193

https://github.com/google/shaka-packager/commit/414f4589c87283b9ad3f06feb3bbecd2bde54761

Do we have a spec that we followed while updating these.. coz looking around it seems a lot of players and parsers do actually support `center` and `middle` both as acceptable options. 
I couldn't find it in the published WEBVTT spec, but I am assuming it must be at one point since we see it referenced in a lot of places. 

https://www.w3.org/wiki/VTT_Concepts#Text_Align
https://www.speechpad.com/captions/webvtt#toc_13
https://webplatform.github.io/docs/concepts/VTT_Captioning/#Text-Align

So when shaka-packager runs into this does it just print the WARNING but still add it in the m4s packages it has created ? 
I'm hoping it doesn't skip it over otherwise we could have more player side issues. 
Do you think we can add something to make this backwards compatible to support `middle` and `center`

**Comment by kqyang** [comment]
Looks like both should be allowed. @TheModMaker What do you think?

**Comment by TheModMaker** [comment]
Sure, supporting both sounds fine.  Note that we will convert to using "center", so it won't preserve what you had originally.  But that is what the [current spec](https://www.w3.org/TR/webvtt1/#dom-vttcue-align) says to use anyway.

**Comment by vish91** [comment]
Yeah that's fine if we can support both and still convert it to "center" as per spec, I think that's fine.

**Comment by kqyang** [comment]
@vish91 Do you want to submit a PR for this one as well?

**Comment by vish91** [comment]
yeah sure. @kqyang  It would be a lot easier if you can help me with build instructions for latest macOS and xcode. I hate building and testing it from docker instances to make these PRs and issue reports :D

**Comment by kqyang** [comment]
@vish91 Thanks.

As for the latest macOS build problem, see the latest comment in the bug, which should be able to workaround the problem. As for the actual fix, we'll need to update the Chromium build to a newer copy. Unfortunately, that also requires us to update from GYP to GN, which requires about a week of work. We do not have any bandwidth ourselves on that. I am curious if you will have time working on it not.

**Comment by vish91** [comment]
Awesome. yeah I didn't see the comment there. I can try that. 🤞🏽 hopefully works out.
