### ISSUE TITLE
[DASH] packager fails on inputs without DRM label

### ISSUE THREAD

**Issue by vish91** [google/shaka-packager#883]
## System info
**Operating System**: Ubuntu
**Shaka Packager Version**: master

## Issue and steps to reproduce the problem

**Packager Command**:
Run dash packager where audio/video input have a DRM label , key etc all necessary information and subtitle input without drm_label.
e.g
 ./packager 'in=/YR_12025_jb_2CH_401160_375.mp4,stream=video,init_segment=/YR_12025_jb_2CH_401160_375/init.m4v,segment_template=/420776_cenc_dash/YR_12025_jb_2CH_401160_375/seg_$Number$.m4s,drm_label=sd' 'in=/YR_12025_jb_2CH_401160_2100.mp4,stream=video,init_segment=/YR_12025_jb_2CH_401160_2100/init.m4v,segment_template=/YR_12025_jb_2CH_401160_2100/seg_$Number$.m4s,drm_label=hd' 'in=/YR_12025_jb_2CH_en-US_401160_3_aac_128.mp4,stream=audio,init_segment=/YR_12025_jb_2CH_en-US_401160_3_aac_128/init.m4v,segment_template=/YR_12025_jb_2CH_en-US_401160_3_aac_128/seg_$Number$.m4s,lang=en,drm_label=audio' **'in=/en/en.vtt,stream=text,init_segment=/en/vtt_init.m4v,language=en,segment_template=/en/seg_$Number$.m4s'** --clear_lead 0 --segment_duration 6 --fragment_duration 6 --generate_static_live_mpd --mpd_output /stream.mpd --enable_raw_key_encryption --keys label=audio:key_id=82..:key=e4...,label=sd:key_id=82..:key=e4..,label=hd:key_id=82...:key=e4... --pssh 000...something..0

What is the expected result?
Packager completes successfully with non encrypted DASH Subtitle Adaptation set in the manifest

What happens instead?
[0113/021906:ERROR:packager_main.cc(556)] Packaging Error: 17 (NOT_FOUND): Key for '' was not found.

In order to now package this successfully try passing a drm_label to the vtt `in:`  and some key for that label in the command above and it will start working as expected. for example:
**'in=/en/en.vtt,stream=text,init_segment=/en/vtt_init.m4v,language=en,segment_template=/en/seg_$Number$.m4s,drm_label=sd'**

This isn't happening on earlier release, so something has changed to cause this behavior to break between the `release` version and latest `master` branch.

**Comment by kqyang** [comment]
@vish91 Thanks for the report. I assume that the `drm_label` is not specified because you do not want it to be encrypted? Can you try if it works if you add `skip_encryption=1` tag?

**Comment by vish91** [comment]
@kqyang Yeah that's correct. `drm_label` is not specified on the subtitle stream input because we do not want it to be encrypted. It does exist on the other inputs, so if I try with `skip_encryption` wouldn't that skip encryption for all the inputs ?

**Comment by kqyang** [comment]
No, `skip_encryption` is a stream descriptor tag, so you can do something like:

```
'in=/en/en.vtt,stream=text,init_segment=/en/vtt_init.m4v,language=en,segment_template=/en/seg_$Number$.m4s,skip_encryption=1'
```

**Comment by vish91** [comment]
Gotcha. yeah that worked. using `skip_encryption` descriptor worked and ignored drm just for that stream. 
So, what are your thoughts ? we use this as the standard solution going forward or this would be a breaking change for people when the update to new version in next release ?

**Comment by kqyang** [comment]
I don't see why we want to encrypt the text, so I think we should always keep text unencrypted.

The problem seems to be introduced by this commit https://github.com/google/shaka-packager/commit/2909ca0c774dd9530ee188b1de499c7eef8e91d6.

It can be fixed by moving line 704 (https://github.com/google/shaka-packager/commit/2909ca0c774dd9530ee188b1de499c7eef8e91d6#diff-f6e5f987988040a1154edb22bb6607c88d1fc630230056d4af3a4815b58693a1R704) under the else condition above it.

@vish91 Do you want to try if that fixes your problem? If it works, you are welcomed to submit a PR to us.

@TheModMaker Let us know if you have a different thoughts.

**Comment by vish91** [comment]
Gotcha sounds good to me. Can wait if @TheModMaker has something to add or  I'll make a PR.
