### ISSUE TITLE
[DRM] 8 bytes IV should use padding 8-15 bytes as a counter according to 23001-7 Clause 9.3

### ISSUE THREAD

**Issue by XingzhaoYun** [google/shaka-packager#887]
According to specs 23001-7 Clause 9.3,
When a 8 byte per_sample_IV_Size is indicated, the least significant 8 bytes of the 16 byte IV (bytes 8 to 15) SHALL be set to zero and used as a 64 bit block counter that is incremented by one for each subsequent 16 byte cipher block of encrypted sample data.

In Shaka packager, 8-15 bytes of IV is always set to 0. I'm not sure if this is an issue.

**Comment by kqyang** [comment]
No. It is used as a counter, and is incremented by one for each block of data: https://github.com/google/shaka-packager/blob/master/packager/media/base/aes_encryptor.cc#L85.
