### ISSUE TITLE
multi audio in same source

### ISSUE THREAD

**Issue by cooliobr** [google/shaka-packager#890]
Any plan to implement multi audio stream in same source?
Today many systems cam process many tracks in same source, in shaka-packager it is a big problem because we need to make many different sources if channel have more than one audio track.
One example is Fox Channel in Brazil, they has 5 audio tacks, so i will need to make 5 different output only for audio.
this is crazy...

**Comment by kqyang** [comment]
Can you use number based stream selector to select the audio stream to package: https://google.github.io/shaka-packager/html/documentation.html#stream-descriptors?

**Comment by cooliobr** [comment]
I tried alread but dont wotk

**Comment by cooliobr** [comment]
Thanks, is working

**Comment by kqyang** [comment]
Great. Thanks for the confirmation!
