### ISSUE TITLE
How to set number of segments in playlist ( HLS Live )

### ISSUE THREAD

**Issue by cooliobr** [google/shaka-packager#896]
Is possible to set number of segments in playlist when using hls live ?
my playlist has almost 200 segments inside

**Comment by kqyang** [comment]
Yes, it is configurable via [--time_shift_buffer_depth](https://google.github.io/shaka-packager/html/documentation.html#hls-options).

I am closing this issue, but feel free to reply if you have more questions.

**Comment by cooliobr** [comment]
thanks :D
