### ISSUE TITLE
unrecognized host aarch64 when trying to run gclient sync

### ISSUE THREAD

**Issue by lovgrandma** [google/shaka-packager#906]
## System info
**Operating System**: Amazon Linux 2 on arm64 architecture (aarch64)
**Shaka Packager Version**: 2.4.3

## Issue and steps to reproduce the problem
When running gclient sync in the shaka packager installation tutorial I get : 
Syncing projects: 100% (21/21), done.

________ running 'vpython src/packager/build/linux/sysroot_scripts/install-sysroot.py --running-as-hook' in '/home/ec2-user/shaka-packager/depot_tools/shaka_packager'

Unrecognized host arch: aarch64
Error: Command 'vpython src/packager/build/linux/sysroot_scripts/install-sysroot.py --running-as-hook' returned non-zero exit status 1 in /home/ec2-user/shaka-packager/depot_tools/shaka_packager

**Packager Command**: gclient sync

What is the expected result?
For the installation to complete to proceed to the next step

What happens instead?
Says I don't have the correct architecture but I am running arm64.

<Please attach the input files or email to shaka-packager-issues@google.com.>
<Please provide any additional information below.>

It seems in the source code https://chromium.googlesource.com/chromium/src/+/61153f138c728fb3e71cb2b8ff55742544497890/build/linux/sysroot_scripts/install-sysroot.py
I can set gyp_defines for the DetectTargetArch() method to override this issue but the problem is is that it is using the DetectHostArch() method which does not allow that. Down the rabbit hole I go and it seems that platform.machine() returns what the command uname -m gives me "aarch64".

This was the final thing I had to do to release this application live and now it looks like the tiny mistep I took by choosing 64-bit Arm instead of 64-bit (x86) in the ec2 setup has just ruined my week if it follows that I must setup my entire architecture on x86.

**Comment by kqyang** [comment]
@lovgrandma Sorry to hear your issue. One workaround you can do is to hardcode the arch in https://github.com/google/shaka-packager/blob/master/DEPS#L102. 

```
    'action': ['python', 'src/packager/build/linux/sysroot_scripts/install-sysroot.py',
               '--arch', 'arm64'],
```

We have never tested it on a ARM64 machine, so it is possible that there could be other problems. Let us know how it goes with the workaround above.

**Comment by lovgrandma** [comment]
Just a bad idea to try to run this build on arm architecture. More problems arise as binaries don't run easily on ARM64
