### ISSUE TITLE
Clear lead not working as expected 

### ISSUE THREAD

**Issue by chrandez** [google/shaka-packager#911]
## System info
**Operating System**: <e.g. macOS Sierra, Ubuntu 14.04 trusty etc> macOS Catalina 10.15.7
**Shaka Packager Version**: <e.g. v1.6.1, commit SHA etc> 5bf8ad5-release

## Issue and steps to reproduce the problem

**Packager Command**: packager in=test.mp4,stream=audio,output=fps/testing.mp4,playlist_name=testing.m3u8,drm_label=AUDIO --protection_scheme cbcs --enable_raw_key_encryption --keys label=AUDIO:key_id=<uuid>:key=<uuid> --protection_systems FairPlay --segment_duration 10 --iv <uuid> --clear_lead 10 --hls_master_playlist_output fps/master.m3u8 --hls_key_uri skd://<keyId>

What is the expected result?
Manifest created with clear lead able to be played through Safari.

What happens instead?
Safari buffers immediately at the beginning of playback with no clear lead. This is solved by manually moving the `EXT-X-KEY` tag after the first segment. **Is there a native way in Shaka packager to do this?**

<Please attach the input files or email to shaka-packager-issues@google.com.>
<Please provide any additional information below.>

**Comment by kqyang** [comment]
The version you are using is a bit out-dated. Can you try v2.4.3?

**Comment by chrandez** [comment]
Just built v2.4.3 and re-ran the same command with the same result. Is the location of the `EXT-X-KEY` tag always expected to be before the first segment?

**Comment by kqyang** [comment]
No, it should be after the first segment. Can you attach your input file (or the link to your input) and the generated outputs?

**Comment by chrandez** [comment]
Input file: https://dl.espressif.com/dl/audio/ff-16b-2c-44100hz.mp4
Outputs: https://drive.google.com/drive/folders/1O_CcXDCoPyVkFF5CK-DtGoTFvDVG62tP?usp=sharing

**Comment by kqyang** [comment]
@chrandez Thanks for the files. Yes, it is a bug, which happens only when generating a single output file

**Comment by kqyang** [comment]
Some code update will be needed: the `NotifyEncryptionUpdate` event needs to be updated to follow the same practice as `NotifyNewSegment ` in `OnNewSegment()`, i.e. if there are no segment templates, the event needs to be cached and issued in `OnMediaEnd()`. The code is available in https://github.com/google/shaka-packager/blob/master/packager/media/event/hls_notify_muxer_listener.cc.

We will try to get it fixed by the end of this month. If you are interested in helping us fixing it, let us know. We welcome PRs :).

**Comment by kqyang** [comment]
Close this issue as obsolete as clear lead does not work properly with fairplay anyway. See #918 for details.

@chrandez Let us know if you have concerns. Thanks.
