### ISSUE TITLE
PresentationTimeOffset

### ISSUE THREAD

**Issue by Jason239** [google/shaka-packager#916]
Can I know when the presentationTimeOffset is created in SegmenTemplate ?

**Comment by kqyang** [comment]
You can find out by searching the code. It is set in MpdBuilder::UpdatePeriodDurationAndPresentationTimestamp from the media timestamps. 

I am closing the issue, but feel free to reply if you have more questions.

**Comment by Jason239** [comment]
If the presentationTimeOffset is 1005, but the earliest start time is 0(<S t="0">), is it right a bug?
As far as I know, the start time(<S t="0">) should be higher than the presentationTimeOffset.

**Comment by kqyang** [comment]
It may happen on audio streams, as presentationTimeOffset is set according to the video stream timestamp, so video stream is adjusted to start at 0. 

That is allowed by the DASH specification, the samples with time smaller than presentationTimeOffset will not be presented.
