### ISSUE TITLE
Hearing a noticeable gap between clear lead boundary

### ISSUE THREAD

**Issue by chrandez** [google/shaka-packager#918]
## System info
Operating System: <e.g. macOS Sierra, Ubuntu 14.04 trusty etc> macOS Catalina 10.15.7
Shaka Packager Version: <e.g. v1.6.1, commit SHA etc> dd9870075f-release

## Issue and steps to reproduce the problem

Packager Commands: 
```
packager in=test.mp4,stream=audio,output=fps/testing.mp4,playlist_name=testing.m3u8,drm_label=AUDIO --protection_scheme cbcs --enable_raw_key_encryption --keys label=AUDIO:key_id=:key= --protection_systems FairPlay --segment_duration 10 --iv --clear_lead 10 --hls_master_playlist_output fps/master.m3u8 --hls_key_uri skd://
```

```
packager 'in=/media/test.mp4,stream=audio,init_segment=init.mp4,segment_template=/media/$Number$.m4s,playlist_name=main.m3u8,hls_group_id=audio,hls_name=ENGLISH' --protection_scheme cbcs --enable_raw_key_encryption --keys label=AUDIO:key_id=:key= --protection_systems FairPlay --segment_duration 10 --iv --clear_lead 10 --hls_master_playlist_output fps/master.m3u8 --hls_key_uri skd://
```

What is the expected result?
Track plays without noticeable gap between clear lead boundaries 

What happens instead?
Follow up of https://github.com/google/shaka-packager/issues/911. As a workaround, I have manually parsed and moved the `EXT-X-KEY` tag to just after the first segment. This enables clear lead to work however there is a noticeable gap at the 10s clear lead mark. I assume this has something to do with the `#EXT-X-DISCONTINUITY` tag not being there.  However, manually adding this before the `#EXT-X-KEY` tag leads to the audio player not being able to play back at all. 

Also tried with separate fmp4 files using the second command and having the same issue.

**Comment by chrandez** [comment]
I was able to partially get around this by creating two separate files, one 10s unencrypted file, one encrypted file beginning at 10s onwards, and combining them into a single playlist file. Then, at the unencrypted/encrypted boundary I insert additional #EXT-X-MAP, #EXT-X-DISCONTINUITY, and #EXT-X-KEY tags. 

```
#EXTM3U
#EXT-X-VERSION:6
## Generated with https://github.com/google/shaka-packager version v2.4.3-dd9870075f-release
#EXT-X-TARGETDURATION:11
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-MAP:URI="unencrypted_test.mp4",BYTERANGE="825@0"
#EXTINF:10.008,
#EXT-X-BYTERANGE:163843@825
unencrypted_test.mp4
#EXT-X-DISCONTINUITY
#EXT-X-MAP:URI="encrypted_test.mp4",BYTERANGE="922@0"
#EXT-X-KEY:METHOD=SAMPLE-AES,URI="skd://...",KEYFORMATVERSIONS="1",KEYFORMAT="com.apple.streamingkeydelivery"
#EXTINF:10.008,
#EXT-X-BYTERANGE:162680@1182
encrypted_test.mp4
...
```

This removes the gap when playing on my Mac but the gap is still noticeable on my iPhone. This seems to be a lot of manual work in generating the playlist. Is there a more official way to do this?

**Comment by chrandez** [comment]
@kqyang Any idea if these two issues are related? (911 and 918)

**Comment by kqyang** [comment]
@chrandez Yes, this will likely be addressed by fixing #911. Can you try if you are seeing the issues using segment template?

**Comment by chrandez** [comment]
Facing the same issue with the segment template where the `EXT-X-DISCONTINUITY` and `EXT-X-KEY` tags are in the correct place, but still hearing a faint blip/glitch at the unencrypted/encrypted transition no matter what parameters I pass to Shaka. Also tried packaging varying source assets with no success.

Wondering if you've encountered this issue before? Or if you're able to successfully package HLS manifests with clear lead without hearing any artifacts.

**Comment by kqyang** [comment]
What is the GOP size? Does it align well with the segment duration?

**Comment by chrandez** [comment]
This is an audio only file. The segment and fragment durations were precisely calculated to align with a 44.1kHz AAC sample. 

```
(1024/44100) ~ .0232s per audio frame
=> 10s / 0.0232s ~ 430frames in a second interval
=> 430 * .0232s ~ 9.984580498866213s per segment

packager ... --segment-duration 9.984580498866213 --fragment-duration 9.984580498866213 --clear_lead 9.984580498866213 ...
```

Even without passing in the segment, fragment, and clear_lead options, I am able to hear the glitch at the default clear lead (6s).

**Comment by kqyang** [comment]
I see. Do you write the player yourself? Could it be caused by the slow license exchange? 

Can you try if you are still seeing the issue using static key instead of fairplay?

**Comment by chrandez** [comment]
I'm using Safari's native HLS player. Also tried Shaka player and another player that was built in house with the same results. 

I am not seeing the issue with a static key exchange. I'm guessing the content decryption happens on the spot rather than asynchronously causing the slight blip. This theory also supports the fact that the artifact is more noticeable on slower networks (WiFi on iOS vs wired connection on my desktop)

**Comment by chrandez** [comment]
Had a meeting with Apple this morning and they confirmed that clear lead is not supported in the traditional sense. They advised adding two sets of keys to mimic what we are trying to accomplish; one master key acting as the clear track, and the remainder as the encrypted with FPS.

Closing as there is no action on your side, thanks!
