### ISSUE TITLE
HLS should explicitly signal a lack of captions

### ISSUE THREAD

**Issue by djeikyb** [google/shaka-packager#922]
**NOTE**: This issue was transferred from Shaka Player to Shaka Packager.  See https://github.com/google/shaka-packager/issues/922#issuecomment-804304019 and https://github.com/google/shaka-packager/issues/922#issuecomment-804364460 for the most relevant details.

-----

-----

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**

Yes

**What version of Shaka Player are you using?**

3.0.10, but I checked each release back to 3.0.0 and see the same behaviour. 

**Can you reproduce the issue with our latest release version?**

Yes

**Can you reproduce the issue with the latest code from `master`?**

Yes

**Are you using the demo app or your own custom app?**

Custom, following the [shaka ui basic usage tutorial](https://shaka-player-demo.appspot.com/docs/api/tutorial-ui.html)

**If custom app, can you reproduce the issue using our demo app?**

Not sure, I wasn't able to run the demo app

**What browser and OS are you using?**

macos 10.14.6, safari 14.0.3 (14610.4.3.1.7)

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**

n/a

**What are the manifest and license server URIs?**

https://github.com/djeikyb/shaka_player_spurious_caption_bug_report/blob/main/2MinTest/master.m3u8

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

```
{
  "drm": {
    "retryParameters": {
      "maxAttempts": 2,
      "baseDelay": 1000,
      "backoffFactor": 2,
      "fuzzFactor": 0.5,
      "timeout": 0
    },
    "servers": {},
    "clearKeys": {},
    "advanced": {},
    "delayLicenseRequestUntilPlayed": false,
    "logLicenseExchange": false,
    "updateExpirationTime": 1
  },
  "manifest": {
    "retryParameters": {
      "maxAttempts": 2,
      "baseDelay": 1000,
      "backoffFactor": 2,
      "fuzzFactor": 0.5,
      "timeout": 0
    },
    "availabilityWindowOverride": null,
    "disableAudio": false,
    "disableVideo": false,
    "disableText": false,
    "defaultPresentationDelay": 0,
    "dash": {
      "clockSyncUri": "",
      "ignoreDrmInfo": false,
      "xlinkFailGracefully": false,
      "ignoreMinBufferTime": false,
      "autoCorrectDrift": true,
      "initialSegmentLimit": 1000,
      "ignoreSuggestedPresentationDelay": false,
      "ignoreEmptyAdaptationSet": false
    },
    "hls": {
      "ignoreTextStreamFailures": false,
      "useFullSegmentsForStartTime": false
    }
  },
  "streaming": {
    "retryParameters": {
      "maxAttempts": 2,
      "baseDelay": 1000,
      "backoffFactor": 2,
      "fuzzFactor": 0.5,
      "timeout": 0
    },
    "rebufferingGoal": 2,
    "bufferingGoal": 10,
    "bufferBehind": 30,
    "ignoreTextStreamFailures": false,
    "alwaysStreamText": false,
    "startAtSegmentBoundary": false,
    "smallGapLimit": 0.5,
    "jumpLargeGaps": false,
    "durationBackoff": 1,
    "forceTransmuxTS": false,
    "safeSeekOffset": 5,
    "stallEnabled": true,
    "stallThreshold": 1,
    "stallSkip": 0.1,
    "useNativeHlsOnSafari": true,
    "inaccurateManifestTolerance": 2
  },
  "offline": {
    "usePersistentLicense": true
  },
  "abr": {
    "enabled": true,
    "defaultBandwidthEstimate": 1000000,
    "switchInterval": 8,
    "bandwidthUpgradeTarget": 0.85,
    "bandwidthDowngradeTarget": 0.95,
    "restrictions": {
      "minWidth": 0,
      "maxWidth": null,
      "minHeight": 0,
      "maxHeight": null,
      "minPixels": 0,
      "maxPixels": null,
      "minFrameRate": 0,
      "maxFrameRate": null,
      "minBandwidth": 0,
      "maxBandwidth": null
    }
  },
  "preferredAudioLanguage": "",
  "preferredTextLanguage": "",
  "preferredVariantRole": "",
  "preferredTextRole": "",
  "preferredAudioChannelCount": 2,
  "restrictions": {
    "minWidth": 0,
    "maxWidth": null,
    "minHeight": 0,
    "maxHeight": null,
    "minPixels": 0,
    "maxPixels": null,
    "minFrameRate": 0,
    "maxFrameRate": null,
    "minBandwidth": 0,
    "maxBandwidth": null
  },
  "playRangeStart": 0,
  "playRangeEnd": null
}
```

**What did you do?**

I made a repo that reproduces the bug:

https://github.com/djeikyb/shaka_player_spurious_caption_bug_report

1. Host the files there in a web server. I used nginx in docker, like:

```
docker run --rm -p 8080:80 --name web -v "$PWD":/usr/share/nginx/html nginx:1.19
```

2. Open index.html in macos safari, I used safari 14.0.3 (14610.4.3.1.7): http://localhost:8080

3. Look at the text tracks, there is a track labeled "Unrecognized ()".

But you can see that no text tracks are configured. None in the hls playlist, none in the player config.

**What did you expect to happen?**

I expected no text tracks

**What actually happened?**

I found and can select a track labeled "Unrecognized ()". This is the output of `player.getTextTracks()`

> JSON.stringify(player.getTextTracks(), null, 2)
```
[
  {
    "id": 1,
    "active": false,
    "type": "text",
    "bandwidth": 0,
    "language": "",
    "label": "",
    "kind": "captions",
    "width": null,
    "height": null,
    "frameRate": null,
    "pixelAspectRatio": null,
    "mimeType": "application/cea-608",
    "codecs": null,
    "audioCodec": null,
    "videoCodec": null,
    "primary": false,
    "roles": [
      "captions"
    ],
    "audioRoles": null,
    "videoId": null,
    "audioId": null,
    "channelsCount": null,
    "audioSamplingRate": null,
    "audioBandwidth": null,
    "videoBandwidth": null,
    "originalVideoId": null,
    "originalAudioId": null,
    "originalTextId": ""
  }
]
```

![gif of bug; first click kebab control panel icon, then click captions, then see a text track labeled "Unrecognized ()"](https://user-images.githubusercontent.com/794743/111713706-64154500-880d-11eb-92de-02c3f60fca47.gif)

I used shaka packager to create the hls playlist and segments.

**Comment by joeyparrish** [comment]
Alright.  I've transferred the issue to Shaka Packager and renamed it.

@kqyang, @TheModMaker, it seems that HLS content should explicitly signal a lack of captions with CLOSED-CAPTIONS=NONE on the EXT-X-STREAM-INF tag.  Otherwise, if there is no positive or negative information about captions, some versions of Safari will assume captions and show UI accordingly.  It should be pretty trivial to have Packager always generate an explicit CLOSED-CAPTIONS attribute, right?

See https://github.com/google/shaka-packager/issues/922#issuecomment-804304019 for more details.

**Comment by kqyang** [comment]
Correct. Shaka Packager does not have explicit support for CLOSED-CAPTIONS. I think we can tag EXT-X-STREAM-INF with CLOSED-CAPTIONS=NONE for all streams. 

If it is necessary, i.e. if anybody wants the implicit CLOSED-CAPTIONS support, we can add a flag later to control the behavior.

It should just be one line change after
https://github.com/google/shaka-packager/blob/master/packager/hls/base/master_playlist.cc#L255:

```c++
    tag.AddString("CLOSED-CAPTIONS", "NONE");
```

There will be a few unit-tests and end-to-end tests need to be updated. 

@djeikyb Will you be interested in making the change, validating the change and sending a PR to us?

**Comment by djeikyb** [comment]
@kqyang I don't think I'm a good candidate, never worked with c++ before. I took a look, but I'm having trouble establishing an environment that can build the project.

**Comment by joeyparrish** [comment]
Sounds quick enough, and I've done this before.  I'll try.
