### ISSUE TITLE
create Dash packaged files inside Akamai instead of an internal file system

### ISSUE THREAD

**Issue by chathurangamt** [google/shaka-packager#928]
I have created a live dash stream using shaka packager.Need to deliver it through Akamai CDN

**Comment by kqyang** [comment]
We added `HTTP PUT` support recently. See https://google.github.io/shaka-packager/html/tutorials/http_upload.html for details. If Akamai CDN supports HTTP PUT, you should be able to use it to upload the streams to the Akamai directly. I am closing the issue, but feel free to reply if you have more questions.
