### ISSUE TITLE
HLS subtitles segmentation not working in latest master branch

### ISSUE THREAD

**Issue by Nixon197** [google/shaka-packager#929]
## System info
**Operating System**: centos
**Shaka Packager Version**: f6c02e6-release
## Issue and steps to reproduce the problem
Packager is outputting the following error when  .vtt input is given for HLS generation.
[0412/143151:INFO:demuxer.cc(89)] Demuxer::Run() on file 'test.vtt'.
[0412/143151:INFO:demuxer.cc(155)] Initialize Demuxer for file 'test.vtt'.
terminate called after throwing an instance of 'std::regex_error'
  what():  regex_error

This problem does not exists in release version v2.4.1-c731217-release

**Packager Command**:
packager \
'in=test.vtt,stream=text,segment_template=sub/text_$Number$.vtt,playlist_name=sub/main.m3u8,hls_group_id=text,hls_name=ENGLISH' \
--hls_master_playlist_output playlist.m3u8

Extra steps to reproduce the problem?
(1)
(2)

What is the expected result?
HLS playlist and chunklist is generated
What happens instead?
packager exits with error

<Please attach the input files or email to shaka-packager-issues@google.com.>
<Please provide any additional information below.>
[test.zip](https://github.com/google/shaka-packager/files/6296679/test.zip)

**Comment by kqyang** [comment]
It should be the same issue as #865.

@Nixon197 What is your CentOS version and your gcc version?

**Comment by Nixon197** [comment]
Hi,

I just tested the latest master release and it is working as expected so I am closing this issue.

BR
