### ISSUE TITLE
Fails to parse matroska  file with projection metadata

### ISSUE THREAD

**Issue by wader** [google/shaka-packager#932]
## System info
**Operating System**: Alpine linux 3.12.1
**Shaka Packager Version**: 2.4.3 (5bf8ad5e-release)

## Issue and steps to reproduce the problem

**Packager Command**:

Matroska file with projection metadata:
```sh
$ packager 'input=test_projection.mkv,stream=video,format=webm,init_segment=init.webm,segment_template=$Number$.webm'
[0416/114025:INFO:demuxer.cc(88)] Demuxer::Run() on file 'test_projection.mkv'.
[0416/114025:INFO:demuxer.cc(160)] Initialize Demuxer for file 'test_projection.mkv'.
[0416/114025:ERROR:packager_main.cc(523)] Packaging Error: 8 (PARSER_FAILURE): Cannot parse media file test_projection.mkv
```

Matroska file without projection metadata:
```sh
$ packager 'input=test_no_projection.mkv,stream=video,format=webm,init_segment=init.webm,segment_template=$Number$.webm'
[0416/114136:INFO:demuxer.cc(88)] Demuxer::Run() on file 'test_no_projection.mkv'.
[0416/114136:INFO:demuxer.cc(160)] Initialize Demuxer for file 'test_no_projection.mkv'.
[0416/114136:WARNING:vp_codec_configuration_record.cc(45)] VPx video full range flag is inconsistent, 1 vs 0
[0416/114136:INFO:webm_muxer.cc(57)] WEBM file 'init.webm' finalized.
Packaging completed successfully.
```

What is the expected result?

Clearer error messge? Maybe possibility to filter out/ignore projection metadata? Maybe automatically ignore if projection metdata is a "identity" projection. In the original file with this metadata the video is just a flat video not meant to be projected on a non-flat surface which makes me think that `StereoMode: top - bottom (left eye is first)` and 
`ProjectionType: equirectangular` means identify projection and could probably be ignored, but i'm not 3d video expert.

What happens instead?

```
[0416/114025:ERROR:packager_main.cc(523)] Packaging Error: 8 (PARSER_FAILURE): Cannot parse media file test_projection.mkv
```

The parse error i suspect is due to that matroska EBML tags Projection/ProjectionType and StereoMode are not defined in https://github.com/google/shaka-packager/blob/master/packager/media/formats/webm/webm_parser.cc

[test_no_projection.mkv.zip](https://github.com/google/shaka-packager/files/6324723/test_no_projection.mkv.zip)
[test_projection.mkv.zip](https://github.com/google/shaka-packager/files/6324724/test_projection.mkv.zip)

**Comment by kqyang** [comment]
Yes, you are right. @wader Will you be interested in helping us adding support for it? Alternatively, we can ignore all the unknown tags.

**Comment by wader** [comment]
Im interested, do you have any ideas how it could work? Im thinking something like this: If there is projection metadata automatically ignore "identity" projections if it is possible detect. Otherwise fail with error unless some explicit argument to ignore has been given?

Another option i think is to just make the error message clearer and not support it. Then it would at least make it clear to a user what they needs to filter out.

**Comment by kqyang** [comment]
@wader Thanks for your interest in helping us!

Your proposal SGTM. 

- To do that, we'll first need to add support for `Projection` and its children tags. You can find the definition of these tags in Matroska specification: https://www.matroska.org/technical/elements.html, and look for `Projection`.
- Then add the Ids to https://github.com/google/shaka-packager/blob/master/packager/media/formats/webm/webm_constants.h.
- Add a `kWebMProjection` with type `LIST` to `kVideoIds`: https://github.com/google/shaka-packager/blob/master/packager/media/formats/webm/webm_parser.cc#L184.
- Add a `kProjectionIds` just like `kColorIds`: https://github.com/google/shaka-packager/blob/master/packager/media/formats/webm/webm_parser.cc#L203
- Add an entry in `kListElementInfo` for projection: https://github.com/google/shaka-packager/blob/master/packager/media/formats/webm/webm_parser.cc#L403.
- The values can be handled appropriately in `webm_video_client.cc`: https://github.com/google/shaka-packager/blob/master/packager/media/formats/webm/webm_video_client.cc#L255.
