### ISSUE TITLE
Packager connects to two Windows named pipe instances

### ISSUE THREAD

**Issue by meryacine** [google/shaka-packager#937]
## System info
**Operating System**: Windows 10
**Shaka Packager Version**: v2.4.3

## Issue and steps to reproduce the problem

When creating a named pipe on Windows with 2 instances, and run Shaka-Packager to read from this named pipe, Shaka-Packager connects to both instances, the first instance functions well, the second produces an error upon performing any operation on it.

**Packager Command**:
```
packager in=\\.\pipe\test,stream=video,init_segment=video_720p_2M_h264_init.mp4,segment_template=video_720p_2M_h264_$Number$.mp4 --segment_duration 10 --generate_static_live_mpd --mpd_output dash.mpd
```

## Extra steps to reproduce the problem?
1) run the python script attached below.
2) run the Shaka-Packager command.

### What is the expected result?
The second pipe instance to be free.

### What happens instead?
The second pipe instances is captured by Shaka-Packager and raises an error upon using it.

## Screenshots
![Screenshot_337](https://user-images.githubusercontent.com/56920956/115838659-362dac80-a41a-11eb-923e-0f17e39b0622.png)

![Screenshot_338](https://user-images.githubusercontent.com/56920956/115839935-72154180-a41b-11eb-9434-b3756e45bdcf.png)

## Python script

```
import win32pipe, win32file


BUF_SIZE = 64 * 1024
PATH = r'\\.\pipe\test'

pipe1 = win32pipe.CreateNamedPipe(
  PATH,
  win32pipe.PIPE_ACCESS_DUPLEX,
  win32pipe.PIPE_WAIT | win32pipe.PIPE_TYPE_BYTE | win32pipe.PIPE_READMODE_BYTE,
  2,
  BUF_SIZE,
  BUF_SIZE,
  -1,
  None
)

pipe2 = win32pipe.CreateNamedPipe(
  PATH,
  win32pipe.PIPE_ACCESS_DUPLEX,
  win32pipe.PIPE_WAIT | win32pipe.PIPE_TYPE_BYTE | win32pipe.PIPE_READMODE_BYTE,
  1,
  BUF_SIZE,
  BUF_SIZE,
  -1,
  None
)

while True:
  try:
    print(win32pipe.GetNamedPipeClientProcessId(pipe1))
    print(win32pipe.GetNamedPipeClientProcessId(pipe2))
    break
  except:
    pass

dummy_data = b'\x00\x00\x00$ftypisom'

win32file.WriteFile(pipe1, dummy_data)
print("wrote to pipe1\n")

win32file.WriteFile(pipe2, dummy_data)
print("wrote to pipe2\n")

# packager in=\\.\pipe\test,stream=video,init_segment=video_720p_2M_h264_init.mp4,segment_template=video_720p_2M_h264_$Number$.mp4 --segment_duration 10 --generate_static_live_mpd --mpd_output dash.mpd
```

**Comment by kqyang** [comment]
Shaka Packager does not perform anything special for named pipes. It is handled using standard Windows file APIs. 

I am not familiar with named pipes on Windows, but it looks like there is a problem in your script.

Here is what I found on Microsoft documentation: https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-createnamedpipea.

```
nMaxInstances

The maximum number of instances that can be created for this pipe. The first instance of the pipe can specify this value; the same number must be specified for other instances of the pipe. Acceptable values are in the range 1 through PIPE_UNLIMITED_INSTANCES (255).
```

The value must be the same on all instances, which is not the case in your script.

I am closing this issue as "external", but feel free to reply if you have Shaka packager specific follow up questions.
