### ISSUE TITLE
VPx video full range flag is inconsistent, 1 vs 0.

### ISSUE THREAD

**Issue by DeadInside1985** [google/shaka-packager#938]
## System info
**Operating System**: Ubuntu 18.04
**Shaka Packager Version**: v2.4.2-c60e988-release

## Issue and steps to reproduce the problem
I got this  warning [0427/103227:WARNING:vp_codec_configuration_record.cc(45)] VPx video full range flag is inconsistent, 1 vs 0. Cant some one explain what is mean? I have some problem in chromium to decode video, when enable hardware decode.  

**Packager Command**:
ffmpeg_binary/packager-linux  'in=/home/files/9.730664.webm,stream=video,output=/home/files/730664/9.730664,init_segment=/home/files/730664/9.730664/init.webm,segment_template=/home/files/730664/9.730664/$Number$.webm' 'in=/home/files/10.730664.webm,stream=video,output=/home/files/730664/10.730664,init_segment=/home/files/730664/10.730664/init.webm,segment_template=/home/files/730664/10.730664/$Number$.webm' 'in=/home/files/4.730664-0.webm,stream=audio,output=/home/files/730664/4.730664-0,init_segment=/home/files/730664/4.730664-0/init.webm,language=ru0,segment_template=/home/files/730664/4.730664-0/$Number$.webm' --generate_static_live_mpd --mpd_output /home/files/730664/730664.mpd

**Comment by DeadInside1985** [comment]
Same warn I have seen with youtube encoded video.

**Comment by DeadInside1985** [comment]
Problem present if input video container is webm with mp4 all is right.

**Comment by kqyang** [comment]
It is complaining that the `full_range_flag` in the WebM container does not match with the flag parsed from the codec metadata. When it happens, the config in the container takes precedence. 

It shouldn't cause decoding problems, but if you want to experiment, you can toggle the configuration, e.g. add a line after https://github.com/google/shaka-packager/blob/6c8ad30217c286d4eecadc9df12420767d389942/packager/media/codecs/vp_codec_configuration_record.cc#L47:

```c++
*dest_value = source_value;
```
