### ISSUE TITLE
Packager should stop and return an error if one of the stream fails to be parsed

### ISSUE THREAD

**Issue by kqyang** [google/shaka-packager#94]
Currently packager may proceed and continue running until all streams fails to be parsed.

**Comment by vaage** [comment]
Is there a sample command I can use to reproduce this case?

**Comment by kqyang** [comment]
You may try with a valid mp4 file and an invalid mp4 file, and do something like:

```shell
$ packager in=valid.mp4,stream=video,out=valid_out.mp4  \
           in=invalid.mp4,stream=video,out=invalid_out.mp4
```
