### ISSUE TITLE
MultiDrm CMAF command

### ISSUE THREAD

**Issue by sridhard** [google/shaka-packager#940]
## System info
**Operating System**: macOS Sierra
**Shaka Packager Version**: 2.4.3

Hi,
I want to generate CMAF content with widevine,playready,fairplay. I have the below queries:

1. When using raw keys below is the format in which we give keys for widevine/playready as per the docs
--keys label=AUDIO:key_id=f3c5e0361e6654b28f8049c778b23946:key=a4631a153a443df9eed0593043db7519,label=SD:key_id=abba271e8bcf552bbd2e86a434a9a5d9:key=69eaa802a6763af979e8d1940fb88392,label=HD:key_id=6d76f25cb17f5e16b8eaef6bbf582d8e:key=cb541084c99731aef4fff74500c12ead \

But for fairplay we need to give the IV also. How can we use one command to generate content for widevine,playready,fairplay?

2. When generating CMAF content with widevine,playready,fairplay, I am getting the following warning:
[0502/111215:WARNING:simple_hls_notifier.cc(494)] HLS: Ignore unknown or unsupported system ID: 9A04F07998404286AB92E65BE0885F95
[0502/111215:WARNING:simple_hls_notifier.cc(494)] HLS: Ignore unknown or unsupported system ID: 5E629AF538DA4063897797FFBD9902D4

Is this warning ok? or there will be some issue in the generated content?

**Comment by kqyang** [comment]
@sridhard Yes, you can ignore the warnings in 2. 

> But for fairplay we need to give the IV also. How can we use one command to generate content for widevine,playready,fairplay?

You can specify the IV using --iv command line argument. It will work for Widevine and PlayReady too.

I am closing this issue, but feel free to reply if you have more questions.
