### ISSUE TITLE
How can i package playready protected contents? Is there any "running" example or test case?

### ISSUE THREAD

**Issue by fingul** [google/shaka-packager#949]
## System info
Operating System: macOS Sierra
Shaka Packager Version: 2.4.3

How can i package playready protected contents?

Is there any running example or test case?

eg) using https://testweb.playready.microsoft.com/

Thanks.

**Comment by kqyang** [comment]
@fingul There are two ways to package for PlayReady. 

Option 1: You can request for keys from your license provider and provide them to Shaka Packager using `Raw Key`. The PSSH can either be internally generated by packager or externally provided if your license server requires custom parameters. See https://google.github.io/shaka-packager/html/tutorials/raw_key.html for examples.

Option 2: If you have a PlayReady Key Server supports [AcquirePackagingData Web Method specification](http://bit.ly/2M9NuOt), you can also use that. See https://google.github.io/shaka-packager/html/tutorials/playready.html for examples.

Hope that addresses your questions.
