### ISSUE TITLE
Packaging Error: 5 (FILE_FAILURE): Cannot open file for reading /media/example.mp4

### ISSUE THREAD

**Issue by nuzhatgawhar** [google/shaka-packager#962]
## System info
*Operating System*: <Windows 10, Ubuntu 20.04>
*Shaka Packager Version*: <release-v1.6.2>

## Issue and steps to reproduce the problem

*Packager Command*: $ docker run -v /media/:/media -it --rm google/shaka-packager (media is the folder in my PC that has the video)
$ packager input=/media/example.mp4,stream=audio,output=/media/audio.mp4 \
           input=/media/example.mp4,stream=video,output=/media/video.mp4 \
           --mpd_output /media/example.mpd 

when I run this I get the error,
[0621/083740:ERROR:packager_main.cc(551)] Packaging Error: 5 (FILE_FAILURE): Cannot open file for reading /media/example.mp4

[ShakaPlayerError](https://user-images.githubusercontent.com/86228377/122735105-01ee3500-d27f-11eb-91ba-4257ad31f62f.png)_

Please help me to solve this

**Comment by kqyang** [comment]
Can you run `ls` on docker and on host to see if the file is accessible?

**Comment by nuzhatgawhar** [comment]
> Can you run `ls` on docker and on host to see if the file is accessible?

Yes I did. In my host machine it shows the 2 video files inside the media folder. But in docker it shows something else. I attached the pictures. Can you please
![Screenshot (2)](https://user-images.githubusercontent.com/86228377/123604909-9581b180-d7fb-11eb-8eee-cc574060d1a0.png)
![Screenshot (3)](https://user-images.githubusercontent.com/86228377/123604912-961a4800-d7fb-11eb-8022-36e0e3080ccf.png)
 tell me how to solve it?

**Comment by bugre** [comment]
@nuzhatgawhar you are mounting "/media" from your host, but your video files apear to be in "~/media". 
Can you please show "ls -l ~/media" and "ls -l /media" on your host machine?

**Comment by nuzhatgawhar** [comment]
> @nuzhatgawhar you are mounting "/media" from your host, but your video files apear to be in "~/media".
> Can you please show "ls -l ~/media" and "ls -l /media" on your host machine?

here it is
![Screenshot (4)](https://user-images.githubusercontent.com/86228377/123615573-b818c800-d805-11eb-87c9-7dfdd44d4569.png)

**Comment by bugre** [comment]
as expected, the second "ls -l /media" shows the same files you see inside the container.  
You can..
- update the host path used on the mount, something like `docker run ... -v ~/media/:/media ...`, or
- move your files to /media

**Comment by nuzhatgawhar** [comment]
> as expected, the second "ls -l /media" shows the same files you see inside the container.
> You can..
> 
> * update the host path used on the mount, something like `docker run ... -v ~/media/:/media ...`, or
> * move your files to /media  (_edit_: take care not overwriting files without knowing what they're used for)

I used ~media now but it still shows the same error
![Screenshot (5)](https://user-images.githubusercontent.com/86228377/123620246-498a3900-d80a-11eb-8a3f-ec2b058356a2.png)

**Comment by nuzhatgawhar** [comment]
> as expected, the second "ls -l /media" shows the same files you see inside the container.
> You can..
> 
> * update the host path used on the mount, something like `docker run ... -v ~/media/:/media ...`, or
> * move your files to /media  (_edit_: take care not overwriting files without knowing what they're used for)

I used the path ~/media. But now it shows this error
![Screenshot (6)](https://user-images.githubusercontent.com/86228377/123621326-607d5b00-d80b-11eb-8271-1ede92486c2f.png)

**Comment by bugre** [comment]
the first command is incorrect, as you're mounting  host "~/media" to "/media" inside the container.

the second command does finally find the 'video files', but seems to fail not recognising them. Are you sure example.mp4 is a valid mp4 with audio and video streams?

share the output of : `ffmpeg -i ~/media/example.mp4` on your host

**Comment by nuzhatgawhar** [comment]
> the first command is incorrect, as you're mounting host "~/media" to "/media" inside the container.
> 
> the second command does finally find the 'video files', but seems to fail not recognising them. Are you sure example.mp4 is a valid mp4 with audio and video streams?
> 
> share the output of : `ffmpeg -i ~/media/example.mp4` on your host

Here it is,
![Screenshot (7)](https://user-images.githubusercontent.com/86228377/123626319-0384a380-d811-11eb-8f6e-ec81aa965d18.png)
![Screenshot (8)](https://user-images.githubusercontent.com/86228377/123626322-04b5d080-d811-11eb-98fa-8fee90e5e5a7.png)

**Comment by kqyang** [comment]
example.mp4 contains a video stream only, so it is expected that "stream=audio" is not available.

Thanks @bugre for helping on this issue.
