### ISSUE TITLE
how to confirm the size of kInitBufSize and kBufSize

### ISSUE THREAD

**Issue by FeiCao** [google/shaka-packager#97]
Hello,
I want to know how to confirm the size of kInitBufSize (https://github.com/google/edash-packager/blob/master/packager/media/base/demuxer.cc#L26) and kBufSize (https://github.com/google/edash-packager/blob/master/packager/media/base/demuxer.cc#L27), there may be an question that it will wait for a few seconds to generate the first segment?

**Comment by kqyang** [comment]
I am not sure if I understand the question correctly. Are you seeing some delays generating the first segment when packaging a live stream?

The size of kInitBufSize and kBufSize is small enough. And also, the read is non-blocking. It shouldn't affect or delay the generation the segments.

Packager will wait until it sees a key frame before starting packaging. This may contribute some delays. The init_segment will be written when media information is available, i.e. after seeing a key frame. The first media segment is only written when there are enough frames in the segment. (Controlled by flag --segment_duration)

**Comment by FeiCao** [comment]
Right, I mean that I have two different type cameras(different Resolution and different framerate), I want to spend the same time to generate segments for a live stream. But cameras send different size video data, the packager spend different times to receive `kInitBufSize` and `kBufSize ` data, the first video segment of the different cameras will be generated different time. so I have an idea that modify the size of  `kInitBufSize` and `kBufSize ` dynamically to adapt to different cameras.

**Comment by kqyang** [comment]
Emm... I am interested in knowing more about your situation:
1. How do you use packager? Can you share your command line parameters?
2. Do you have more numbers, e.g. the resolutions / framerates / delays / segment sizes etc?
3. Does adjusting ```kInitBufSize``` and ```kBufSize``` work for you? What values do you set respectively? (Though I don't think that is the cause and it will work - prove that I am wrong :))

**Comment by FeiCao** [comment]
1. I use two packagers, one for camera1, the other one for camera2. `dir `is a directory and the command line：
`tcp://0.0.0.0:6669,stream=video,init_segment=dir//live-video-sd.mp4,segment_template=dir//live-video-sd-$Number$.mp4,bandwidth=2000000 --profile live --mpd_output dir//live.mpd --segment_duration=2`
2. camera1: resolution=1920X1080  framerate=15 segment size=230KB delay=5s
camera2:resolution=1280X960  framerate=15 segment size=80KB delay=6s
3. I hope that I can adjust `kInitBufSize` and  `kBufSize` and packager can adapt different cameras, Now I set they default value 64K and 2MB. 
 
I just want you to give me some idea, I did not say you wrong, thank you!

**Comment by kqyang** [comment]
A couple of questions:

1. I noticed that you were using a different protocol: tcp, which is not supported in edash-packager. Do you have a patch to make it support "tcp"? What is it? Using "tcp" and a transport protocol and carrying mpeg2-ts stream?

2. From your point 2, is the delay for the first camera is 5 seconds and the delay for the second camera 6 seconds? Is the problem only for the first segment? Do you still see the problem for the subsequent segments? Are they always out of sync for about 1 second?

3. Are the streams generated from the two cameras gop-aligned and synchronized? If not, we won't be able to synchronize it in packager if they are not synchronized in the source.

**Comment by kqyang** [comment]
Closed due to inactivity. Feel free to re-open the bug if needed.
