### ISSUE TITLE
Packager: Permission denied

### ISSUE THREAD

**Issue by cvjude** [google/shaka-packager#994]
## System info
**Operating System**: macOS bigsur M1
**Shaka Packager Version**: v2.6.0

## Issue and steps to reproduce the problem
I am unable to run the packager on files, I didn't have this issue with my previous computer, which was a macOS sierra intel core i5.

**Packager Command**:
```
./packager \
    input=sample720.mp4,stream=audio,output=dest/sample720_audio.mp4 \
    input=sample720.mp4,stream=video,output=dest/sample720_video.mp4 \
    input=sample540.mp4,stream=audio,output=dest/sample540_audio.mp4 \
    input=sample540.mp4,stream=video,output=dest/sample540_video.mp4 \
    input=sample360.mp4,stream=audio,output=dest/sample360_audio.mp4 \
    input=sample360.mp4,stream=video,output=dest/sample360_video.mp4 \
--profile on-demand \
--mpd_output sample-mainfest-full.mpd \
--min_buffer_time 3 \
--segment_duration 3
```

What is the expected result?
I expect to see the mpd files generated

What happens instead?
./packager: Permission denied

**Comment by joeyparrish** [comment]
Most likely, you have downloaded the executable, but not set the executable permission bit on it.  You can do this on the command-line with:

```sh
chmod +x ./packager
```

Does this help?
